### ISSUE TITLE
Getting "Failed: Data source does not exist" errors

### ISSUE THREAD

**Issue by yanne** [robotframework/RIDE#1028]
> *Originally submitted to [Google Code](http://code.google.com/p/robotframework-ride/issues/detail?id=989) by rohitmah... on 19 Jun 2012*

I just installed RIDE with the following versions:
20120619 14:52:53.309 [INFO]: Started RIDE 0.45 using python version 2.7.2 with wx version 2.8.12.1.

I ran my set of tests for the first time after installation and I am getting the following errors:
working directory: C:\
command: pybot.bat 175.80.27.183/#home --argumentfile c:\users\rmahatma\appdata\local\temp\RIDEmqjv1n.d\argfile.txt --listener C:\Python27\lib\site-packages\robotide\contrib\testrunner\SocketListener.py:50451 Users\rmahatma\Desktop\SVNWorkspace\Selenium\Robot\RohitTestFolder
[ WARN ] Parsing 'C:\172.27.8.161:8181\mobile\#home' failed: Data source does not exist.
[ WARN ] Parsing 'C:\--outputdir' failed: Data source does not exist.
[ WARN ] Parsing 'C:\--monitorcolors' failed: Data source does not exist.
[ WARN ] Parsing 'C:\off' failed: Data source does not exist.
[ WARN ] Parsing 'C:\--monitorwidth' failed: Data source does not exist.
[ WARN ] Parsing 'C:\131' failed: Data source does not exist.

[ WARN ] Parsing 'C:\--listener' failed: Data source does not exist.
[ WARN ] Parsing 'C:\Python27\lib\site-packages\robotide\contrib\testrunner\SocketListener.py:50451' failed: Data source does not exist.

[ ERROR ] Opening output file 'C:\output.xml' failed: Permission denied

Try --help for usage information.

test finished 06/19/12 14:58:57

Is this a defect or I might have missed something while installing RIDE?

I appreciate the helpful comments.

Thanks!

**Comment by yanne** [comment]
> *Originally submitted to [Google Code](http://code.google.com/p/robotframework-ride/issues/detail?id=989#c2) by @mkorpela on 29 Jul 2012*


<a class="closed_ref" href="https://code.google.com/p/robotframework-ride/issues/detail?id=1013" title="robotframework-ride display [WARN ]"> Issue 1013 </a> has been merged into this issue.

**Comment by yanne** [comment]
> *Originally submitted to [Google Code](http://code.google.com/p/robotframework-ride/issues/detail?id=989#c4) by nkc24nk... on 30 Jul 2012*


I found how to resolve this issue.
When use RIDE to run Jybot, we can found argifile.txt, pythonpath need to setting path.

You can to Tools -&gt; Preferences -&gt; Importing Pythonpath   &lt;= please enter path

**Comment by yanne** [comment]
> *Originally submitted to [Google Code](http://code.google.com/p/robotframework-ride/issues/detail?id=989#c5) by @mkorpela on 30 Jul 2012*


<a class="closed_ref" href="https://code.google.com/p/robotframework-ride/issues/detail?id=1013" title="robotframework-ride display [WARN ]"> Issue 1013 </a> has been merged into this issue.

**Comment by yanne** [comment]
> *Originally submitted to [Google Code](http://code.google.com/p/robotframework-ride/issues/detail?id=989#c6) by @mkorpela on 30 Jul 2012*


The given command in the original report:
" pybot.bat 175.80.27.183/#home --argumentfile c:\users\rmahatma\appdata\local\temp\RIDEmqjv1n.d\argfile.txt .. "
Doesn't work as arguments text "175.80.27.183/#home" is not a valid pybot argument.

Unfortunately pybot currently thinks that everything after that will be datasources and it will report a bad warning about parsing errors instead of telling that "175.80.27.183/#home" is not a valid argument.

**Comment by yanne** [comment]
> *Originally submitted to [Google Code](http://code.google.com/p/robotframework-ride/issues/detail?id=989#c7) by @mkorpela on 3 Aug 2012*


<a class="closed_ref" href="https://code.google.com/p/robotframework-ride/issues/detail?id=925" title="Log and report button disabled, arguments tab not working and selection of test cases in a test suite not happening"> Issue 925 </a> has been merged into this issue.

**Comment by yanne** [comment]
> *Originally submitted to [Google Code](http://code.google.com/p/robotframework-ride/issues/detail?id=989#c8) by @mkorpela on 3 Aug 2012*


<a class="closed_ref" href="https://code.google.com/p/robotframework-ride/issues/detail?id=925" title="Log and report button disabled, arguments tab not working and selection of test cases in a test suite not happening"> Issue 925 </a> describes in comments a problem related to pythonpath configurations.

This also will result in similar errors as the ones defined in this issue.

**Comment by yanne** [comment]
> *Originally submitted to [Google Code](http://code.google.com/p/robotframework-ride/issues/detail?id=989#c9) by @mkorpela on 3 Aug 2012*


<a class="closed_ref" href="https://code.google.com/p/robotframework-ride/issues/detail?id=975" title="The function that select specific test cases to run doesn't work"> Issue 975 </a> has been merged into this issue.

**Comment by yanne** [comment]
> *Originally submitted to [Google Code](http://code.google.com/p/robotframework-ride/issues/detail?id=989#c10) by @mkorpela on 3 Aug 2012*


I've done the following fixes:

1) Problems with pythonpath containing empty text should now be fixed
<a href="https://github.com/robotframework/RIDE/commit/bc4ea8f5c984558576dccc39451bbf3cf937a97e" rel="nofollow">https://github.com/robotframework/RIDE/commit/bc4ea8f5c984558576dccc39451bbf3cf937a97e</a>
Also a migration script that will fix empty pythonpath in an old configuration has been added
<a href="https://github.com/robotframework/RIDE/commit/a7d14cbe98d5c914bd40b3f0a9fe70762e0fcfe1" rel="nofollow">https://github.com/robotframework/RIDE/commit/a7d14cbe98d5c914bd40b3f0a9fe70762e0fcfe1</a>

2) Invalid arguments field on run tab is now highlighted with a red background color and a tooltip explaining the current problem.

This should be fully implemented after <a href="https://github.com/robotframework/RIDE/commit/7c465d386f9386390626abf33d4b49bf5fd0d4f2" rel="nofollow">https://github.com/robotframework/RIDE/commit/7c465d386f9386390626abf33d4b49bf5fd0d4f2</a>

**Comment by psharma0016** [comment]
My Python/Robot have been installed on C: Drive. I have correctly configured those as Environment Variables in System-> Advanced Settings -> Environment Variables.
My Robot Test is in P: Drive . When i run the test.robot, it gives me this error:
[ ERROR ] Parsing 'P:\Robot' failed: Data source does not exist.
