### ISSUE TITLE
It shows wrong Character for non-ascii characters when running

### ISSUE THREAD

**Issue by yanne** [robotframework/RIDE#1064]
> _Originally submitted to [Google Code](http://code.google.com/p/robotframework-ride/issues/detail?id=1025) by qit... on 12 Aug 2012_

My test suite is "Test\测试套件.txt". When I run the test, it shows the following in running panel.( RIDE0.47.0 )
# 
# Test   
# Test.▓Γ╩╘╠╫╝■                                                                     
# Then I reinstall RIDE0.46.1,the running panel is:

Test  ==================================================================================
# Test.测试套件                                                                     
1. RF2.7.3(Python2.7.1)
2. ride version: 0.47.0
3. OS: windows 7

I guess maybe cause by the fixed <a class="closed_ref" href="https://code.google.com/p/robotframework-ride/issues/detail?id=1015" title="Directory doesn't accept non-ascii characters (V.0.46.1)"> issue 1015 </a> in 0.47.
<a href="https://code.google.com/p/robotframework-ride/issues/detail?id=1015" rel="nofollow">https://code.google.com/p/robotframework-ride/issues/detail?id=1015</a>

**Explain the defect you encountered either using free text or steps. Mention**
**the expected and actual results.**

**Always include the framework version, Python or Jython version, and**
**operating system. You can, for example, copy the output of 'pybot/jybot**
**--version'.**

**For new features and other enhancements, please use the Enhancement request**
**template.**

**All this text can be deleted.**

**Comment by HelioGuilherme66** [comment]
Yay! This should be fixed since 1.7.4a1.
