### ISSUE TITLE
Ride's Search unused keywords utility does not work correctly with embedded arguments

### ISSUE THREAD

**Issue by yanne** [robotframework/RIDE#1072]
> *Originally submitted to [Google Code](http://code.google.com/p/robotframework-ride/issues/detail?id=1033) by jkohvakk on 21 Aug 2012*

Ride version 0.44
Robot Framework 2.7.2
2.6.32-42-generic #95-Ubuntu SMP Wed Jul 25 15:56:09 UTC 2012 x86_64 GNU/Linux

Ride does not find usage of keywords with embedded arguments correctly. For example, consider following test case:

*** test cases ***
Ride find unused keywords will fail with embedded arguments
    Pick 'apple' and 'peel' it

*** keywords ***
Pick '${fruit}' and '${action}' it
    Fail     not implemented yet

If one puts it to a file and asks Ride to find unused keywords, it will report that Pick '${fruit}' and '${action}' it is never used.

**Comment by yanne** [comment]
> *Originally submitted to [Google Code](http://code.google.com/p/robotframework-ride/issues/detail?id=1033#c4) by @mikahanninen on 24 Aug 2012*


FIxed <a href="https://github.com/robotframework/RIDE/commit/691fa799712fe0a980b72a00fe2f65347a2ce647" rel="nofollow">https://github.com/robotframework/RIDE/commit/691fa799712fe0a980b72a00fe2f65347a2ce647</a>

**Comment by hpschry** [comment]
I still do observe this issue in RF 1.5 at least temporarily (for some keywords with embedded arguments it is working, for others not at all)
