### ISSUE TITLE
Scrolling of the test case tree by mouse wheel extremely slow

### ISSUE THREAD

**Issue by yanne** [robotframework/RIDE#1127]
> _Originally submitted to [Google Code](http://code.google.com/p/robotframework-ride/issues/detail?id=1089) by icts... on 22 Oct 2012_

OS: Ubuntu 12.04.1 x64
Robot Framework 2.7.4 (Python 2.7.3 on linux2)
RIDE: 0.51

Expand tests suites or cases in the tree so it takes couple of screen height and rotate mouse wheel. As result the tree scrolls very slow by one line and stops only after a while.

It's very annoying.

**Comment by yanne** [comment]
> *Originally submitted to [Google Code](http://code.google.com/p/robotframework-ride/issues/detail?id=1089#c1) by @Tattoo on 6 Nov 2012*


Bug is reproducible as described: open big project, start opening up nodes in the tree, see scrolling slowing down.

There might be way to lazy load the tree, see: <a href="http://wiki.wxpython.org/TreeControls" rel="nofollow">http://wiki.wxpython.org/TreeControls</a>

However, it might not be trivial

**Comment by yanne** [comment]
> *Originally submitted to [Google Code](http://code.google.com/p/robotframework-ride/issues/detail?id=1089#c3) by @mkorpela on 20 Nov 2012*


Seems like the instructions in <a href="http://wiki.wxpython.org/TreeControls" rel="nofollow">http://wiki.wxpython.org/TreeControls</a> will not help with this issue.

**Comment by yanne** [comment]
> *Originally submitted to [Google Code](http://code.google.com/p/robotframework-ride/issues/detail?id=1089#c4) by kun.l... on 6 May 2013*


I also met same issue.

**Comment by yanne** [comment]
> *Originally submitted to [Google Code](http://code.google.com/p/robotframework-ride/issues/detail?id=1089#c5) by dbillor on 17 Mar 2014*


This is a big issue when running RIDE on a Linux machine.  I'm currently in the process of setting up an Ubuntu server which multiple users will bring up RIDE and use it to navigate and develop tests.

This is a very annoying problem and greatly impacts work flow as it sometimes takes close to a minute to scroll to the bottom of a big test suite.

Any updates on this issue?

**Comment by yanne** [comment]
> *Originally submitted to [Google Code](http://code.google.com/p/robotframework-ride/issues/detail?id=1089#c6) by derek.robati on 18 Mar 2014*


Same issue here. This is very frustrating.

**Comment by yanne** [comment]
> *Originally submitted to [Google Code](http://code.google.com/p/robotframework-ride/issues/detail?id=1089#c7) by cdoville... on 28 Apr 2014*


Same issue on a Debian Wheezy and RIDE 1.2.3 running on Python 2.7.3.

One of my core is at 100&#37; when the scroll is very slow.

**Comment by yanne** [comment]
I suspect this is a problem with the CustomTreeCtrl we are using. It might be necessary to use the native wrapping TreeCtrl, and do the test case selection in some other way. The primary reason for using the CustomTreeCtrl are the checkboxes, and that could be probably solved differently.

**Comment by dbavery** [comment]
Confirmation -- we see this all of the time.

Ride on Ubuntu 14.04 -- latest stable version. Load a large project and after a little while of open different test cases the mouse wheel scrolling of the navigation window ultimately results in hanging the ride GUI.

The only work around is to kill ride and reopen.

**Comment by MisterChild** [comment]
Same for us on Ubuntu 14.04.

**Comment by jnhyperion** [comment]
it's resolved by: https://github.com/robotframework/RIDE/pull/2237/files
