### ISSUE TITLE
Overriding --outputdir in argumentfile is not possible

### ISSUE THREAD

**Issue by yanne** [robotframework/RIDE#1134]
> _Originally submitted to [Google Code](http://code.google.com/p/robotframework-ride/issues/detail?id=1096) by dennisma... on 5 Nov 2012_

I want to set my --outputdir in a seperate file, no problem there. The issue is that RIDE's file ( --argumentfile c:\users\dfm\appdata\local\temp\RIDE1m8tyh.d\argfile.txt ) has an outputdir specified as well and because it is loaded after mine it gets used.

In my Arguments I pass "-A C:\test.txt".
And RIDE passes
"command: pybot.bat -A C:\test.txt --argumentfile c:\users\dfm\appdata\local\temp\RIDE1m8tyh.d\argfile.txt".

Is there a way to force my file to be used, or to change the order?

**Comment by yanne** [comment]
> *Originally submitted to [Google Code](http://code.google.com/p/robotframework-ride/issues/detail?id=1096#c1) by @mkorpela on 6 Nov 2012*


Currently output dir must be added by using the Arguments field (add -d or --outputdir option).

**Comment by yanne** [comment]
> *Originally submitted to [Google Code](http://code.google.com/p/robotframework-ride/issues/detail?id=1096#c2) by almquist.johan on 6 Nov 2012*


Yes, but that won't work since the argumentfile is provided later on the command line and seem to override the outputdir option.

**Comment by yanne** [comment]
> *Originally submitted to [Google Code](http://code.google.com/p/robotframework-ride/issues/detail?id=1096#c3) by @mkorpela on 6 Nov 2012*


But if you have defined the option then it will be used and not overriden.

We will change this before 1.0 so that custom arguments will be the last ones given.

**Comment by yanne** [comment]
> *Originally submitted to [Google Code](http://code.google.com/p/robotframework-ride/issues/detail?id=1096#c4) by almquist.johan on 6 Nov 2012*


Ok, my bad. I was using an equal sign after the outputdir option, and that won't work, nor will it warn me.  without the equal sign, it works.

However, we tried to specify the outputdir in the pybot-script, and that will not work. RIDE will always provide the same option and override any such option set in the pybot script.

**Comment by yanne** [comment]
> *Originally submitted to [Google Code](http://code.google.com/p/robotframework-ride/issues/detail?id=1096#c5) by dennisma... on 7 Nov 2012*


Thanks for the clarification on this.

**Comment by yanne** [comment]
> *Originally submitted to [Google Code](http://code.google.com/p/robotframework-ride/issues/detail?id=1096#c6) by @jussimalinen on 19 Nov 2012*


Okay, so if I understood correctly, the problem is that overriding outputdir in an argumentfile does not work.

I updated the issue name and moved this to future.

It would be handy though to be able to use = in argument file. That is going to be a robot issue.

**Comment by yanne** [comment]
> *Originally submitted to [Google Code](http://code.google.com/p/robotframework-ride/issues/detail?id=1096#c7) by almquist.johan on 19 Nov 2012*


Well, in our situation, we tried to specify the outputdir in our version of the pybot script, so that we could run our tests either through RIDE or command line and expect the output to end up in the same specified output folder... However, RIDE will always define and override outputdir either with a default value or with the one specified in the text field.

**Comment by yanne** [comment]
> *Originally submitted to [Google Code](http://code.google.com/p/robotframework-ride/issues/detail?id=1096#c8) by @pekkaklarck on 20 Nov 2012*


@&#8288;almquist.johan Equal sign not working in argument files is a missing feature in Robot Framework. I submitted an issue about it and it will be included into the next Robot release:
<a href="https://code.google.com/p/robotframework/issues/detail?id=1281" rel="nofollow">https://code.google.com/p/robotframework/issues/detail?id=1281</a>

**Comment by HelioGuilherme66** [comment]
Fixed by #2453 (hopefully ;) )
