### ISSUE TITLE
Excludes: exclude test case- and resource files

### ISSUE THREAD

**Issue by yanne** [robotframework/RIDE#1191]
> _Originally submitted to [Google Code](http://code.google.com/p/robotframework-ride/issues/detail?id=1152) by @Tattoo on 10 Dec 2012_

Excludes should be extended to work with also test case- and resource files.

Currently excludes do support excluding single files, as it just excludes based on path. Therefore, the Tree component just needs UI to be able to exclude single files.

**Comment by JFoederer** [comment]
I believe this feature is currently available and that this issue can be closed.
