### ISSUE TITLE
Issue with calc.Calculator in Sikuli that using in Robot Framework RIDE

### ISSUE THREAD

**Issue by yanne** [robotframework/RIDE#1220]
> *Originally submitted to [Google Code](http://code.google.com/p/robotframework-ride/issues/detail?id=1181) by sieudang... on 3 Jan 2013*

I did <a href="http://blog.mykhailo.com/" rel="nofollow">http://blog.mykhailo.com/</a> by cmd that it was OK.
But i want to check Calculator on RIDE by using calc.py as external library.
When i didn't import "from sikuli.Sikuli import *", RIDE could receive some functions in calc.py. If i imported "from sikuli.Sikuli import *", RIDE couldn't receive functions.

See more attachment below.
Could you help me fix the issue?

**Comment by yanne** [comment]
> *Originally submitted to [Google Code](http://code.google.com/p/robotframework-ride/issues/detail?id=1181#c1) by morozm... on 4 Jan 2013*


It seems that RIDE experiences issues when trying to load your library. You can look inside RIDE log for more details.

According to following doc libraries written on Java could not be loaded directly into RIDE for keyword comletion:
<a href="https://github.com/robotframework/RIDE/wiki/Keyword-Completion#wiki-libraries-not-available-locally-or-written-in-java" rel="nofollow">https://github.com/robotframework/RIDE/wiki/Keyword-Completion#wiki-libraries-not-available-locally-or-written-in-java</a>

But you still able to use and see them when generate specification and feed it instead to RIDE as it described in the document below:
<a href="https://github.com/robotframework/RIDE/wiki/Keyword-Completion#wiki-using-library-specs" rel="nofollow">https://github.com/robotframework/RIDE/wiki/Keyword-Completion#wiki-using-library-specs</a>

Have fun!

**Comment by yanne** [comment]
> *Originally submitted to [Google Code](http://code.google.com/p/robotframework-ride/issues/detail?id=1181#c2) by sieudang... on 7 Jan 2013*


I have PYTHONPATH=C:\\Python27;C:\\Python27\Lib;C:\\Python27\\Scripts;C:\\Python27\\Lib\\site-packages;C:\\jython2.5.1\\Lib\\site-packages;C:\\jython2.5.1\\Lib;C:\\Python27\\Lib\\site-packages\\robot\\libraries;C:\\Python27\\Scripts\\calculator\\calc.sikuli;C:\Python27\Scripts\calculator\calc.sikuli\calc.py;C:\Python27\Scripts\calculator\calc.sikuli\Calculator.py;C:\Python27\Scripts\calculator\Lib\sikuli

CLASSPATH=C:\Program Files\Sikuli X\sikuli-script.jar;C:\jython2.5.2\jython.jar;C:\mysql-connector;./dblibrary-2.0.jar;./mysql-connector-java-5.1.22-bin.jar;./trilead-ssh2-build213.jar;./fitlibrary.jar;./webtest.jar;./selenium-server-standalone.jar

First link, if i added C:\\Program Files\\Sikuli X\\sikuli-script.jar\\Lib into PYTHONPATH, i met a error that can't run ride.py.

Second link, I have read the link <a href="https://github.com/robotframework/RIDE/wiki/Keyword-Completion#wiki-using-library-specs" rel="nofollow">https://github.com/robotframework/RIDE/wiki/Keyword-Completion#wiki-using-library-specs</a>, but i can't understand how to use library specs.
Could you give me more detail how to use the library specs?
I want to run verify_operations.txt, but i met some issues.
[ ERROR ] Error in file 'C:\RIDE\Client_DemoRobotFramework_OnCodeGoogle\CiscoICEPG\Defined_Functions\Tests\verify_operations.txt' in table 'Settings': Importing test library 'calc.Calculator' failed: ImportError: No module named java.io.File
Traceback (most recent call last):
  File "C:\Python27\Scripts\calculator\calc.sikuli\calc.py", line 2, in &lt;module&gt;
    from sikuli.Sikuli import *
  File "C:\Python27\Scripts\calculator\calc.sikuli\sikuli\__init__.py", line 3, in &lt;module&gt;
    from Sikuli import *
  File "C:\Python27\Scripts\calculator\calc.sikuli\sikuli\Sikuli.py", line 8, in &lt;module&gt;
    import java.io.File

**Comment by yanne** [comment]
> *Originally submitted to [Google Code](http://code.google.com/p/robotframework-ride/issues/detail?id=1181#c3) by sieudang... on 7 Jan 2013*


With "CLASSPATH=/usr/lib/jvm/sun-java-6/lib/tools.jar:myjavalib-0.1.jar jython libdoc.py -f XML MyJavaLibrary " in your link.

I understood like:
myjavalib-0.1.jar as sikuli-script.jar 
what and where is libdoc.py?
What is MyJavaLibrary ?

**Comment by yanne** [comment]
> *Originally submitted to [Google Code](http://code.google.com/p/robotframework-ride/issues/detail?id=1181#c4) by @mkorpela on 17 Jan 2013*


RIDE is pure python program.

Sikuli runs with jython - and any code that uses jython only modules (such as Sikuli) is not compatible with RIDE.

You need to use libdoc tool to produce a xml spec from your library then you are able to see the keywords in that library. See the links in morozmike's comment.

Closing as WontFix.

**Comment by yanne** [comment]
> *Originally submitted to [Google Code](http://code.google.com/p/robotframework-ride/issues/detail?id=1181#c5) by sieudang... on 21 Jan 2013*


I got it. I used to libdoc tool to produce a xml spec from my library that it is OK. Thank you so much.

**Comment by Bboukhari** [comment]
Hello yanne,
I have a sikuli library created Like on Mike's How to blog I wan't to produce an xml spec. I guess once done i can use this library in ride and compile using pybot ? ( so i can use remote library too ? )
