### ISSUE TITLE
Seg faults can occur on Linux

### ISSUE THREAD

**Issue by yanne** [robotframework/RIDE#1223]
> _Originally submitted to [Google Code](http://code.google.com/p/robotframework-ride/issues/detail?id=1184) by bmannix on 7 Jan 2013_

I am seeing some segmentation faults in RIDE 1.0

Ubuntu 12.10
Python 2.7
Wx-Python 2.8.12.1

---

Ride crashes with the following output:

[6866:6866:0107/154344:ERROR:layout.cc(160)] Not implemented reached in ui::ScaleFactor ui::GetScaleFactorForNativeView(GtkWidget_)
[6866:6866:0107/154529:ERROR:layout.cc(160)] Not implemented reached in ui::ScaleFactor ui::GetScaleFactorForNativeView(GtkWidget_)
Segmentation fault (core dumped)

**Comment by yanne** [comment]
> *Originally submitted to [Google Code](http://code.google.com/p/robotframework-ride/issues/detail?id=1184#c1) by @mkorpela on 17 Jan 2013*


Can not reproduce. Needs more information.

**Comment by yanne** [comment]
> *Originally submitted to [Google Code](http://code.google.com/p/robotframework-ride/issues/detail?id=1184#c2) by bmannix on 4 Apr 2013*


What kind of information can I provide?  

Are there debug flags that I should be using or logs that I can be including?

**Comment by yanne** [comment]
> *Originally submitted to [Google Code](http://code.google.com/p/robotframework-ride/issues/detail?id=1184#c3) by @mkorpela on 4 Apr 2013*


We would need a reproducible test case OR if this occurs very often you could try to bisect the exact commit that introduces this problem.

I will not close this issue as it definitely exists.

**Comment by yanne** [comment]
> *Originally submitted to [Google Code](http://code.google.com/p/robotframework-ride/issues/detail?id=1184#c4) by @Tattoo on 3 Sep 2013*


Closing due to not being able to reproduce.

**Comment by yanne** [comment]
> *Originally submitted to [Google Code](http://code.google.com/p/robotframework-ride/issues/detail?id=1184#c5) by @mkorpela on 10 Feb 2014*


Opening again to give a place for people to post ways to reproduce this.

**Comment by yanne** [comment]
> *Originally submitted to [Google Code](http://code.google.com/p/robotframework-ride/issues/detail?id=1184#c6) by guy.kisel on 24 Feb 2014*


I get this occasionally, just during ordinary usage of RIDE. My Ubuntu development environment is running inside Virtualbox 4.3.6 in OS X 10.9.1

I'm running in a virtualenv, and had to follow this guide to get wxPython to work: <a href="http://iambusychangingtheworld.blogspot.com/2013/10/how-to-install-wxpython-inside.html" rel="nofollow">http://iambusychangingtheworld.blogspot.com/2013/10/how-to-install-wxpython-inside.html</a>

lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 12.04.3 LTS
Release:	12.04
Codename:	precise
 

$ pip freeze
Pygments==1.6
argparse==1.2.1
decorator==3.4.0
distribute==0.6.24
docutils==0.11
fake-factory==0.3.2
pymssql==2.0.1
requests==2.2.1
robotframework==2.8.4
robotframework-databaselibrary==0.6
robotframework-faker==0.5
robotframework-requests==0.3.6
robotframework-ride==1.3
robotframework-selenium2library==1.4.0
selenium==2.37.2
truecar-robot==1.0
wsgiref==0.1.2
wxPython==2.8.12.1
wxPython-common==2.8.12.1



(robot)sdet@&#8288;sdet-VirtualBox:/opt/######/src/qa/#####$ ride.py .
OpenGL Warning: Failed to connect to host. Make sure 3D acceleration is enabled for this VM.
libGL error: failed to load driver: vboxvideo
libGL error: Try again with LIBGL_DEBUG=verbose for more details.
OpenGL Warning: Failed to connect to host. Make sure 3D acceleration is enabled for this VM.
libGL error: failed to load driver: vboxvideo
libGL error: Try again with LIBGL_DEBUG=verbose for more details.
OpenGL Warning: Failed to connect to host. Make sure 3D acceleration is enabled for this VM.
libGL error: failed to load driver: vboxvideo
libGL error: Try again with LIBGL_DEBUG=verbose for more details.
OpenGL Warning: Failed to connect to host. Make sure 3D acceleration is enabled for this VM.
libGL error: failed to load driver: vboxvideo
libGL error: Try again with LIBGL_DEBUG=verbose for more details.
OpenGL Warning: Failed to connect to host. Make sure 3D acceleration is enabled for this VM.
libGL error: failed to load driver: vboxvideo
libGL error: Try again with LIBGL_DEBUG=verbose for more details.
OpenGL Warning: Failed to connect to host. Make sure 3D acceleration is enabled for this VM.
libGL error: failed to load driver: vboxvideo
libGL error: Try again with LIBGL_DEBUG=verbose for more details.
OpenGL Warning: Failed to connect to host. Make sure 3D acceleration is enabled for this VM.
libGL error: failed to load driver: vboxvideo
libGL error: Try again with LIBGL_DEBUG=verbose for more details.
OpenGL Warning: Failed to connect to host. Make sure 3D acceleration is enabled for this VM.
libGL error: failed to load driver: vboxvideo
libGL error: Try again with LIBGL_DEBUG=verbose for more details.
OpenGL Warning: Failed to connect to host. Make sure 3D acceleration is enabled for this VM.
libGL error: failed to load driver: vboxvideo
libGL error: Try again with LIBGL_DEBUG=verbose for more details.
OpenGL Warning: Failed to connect to host. Make sure 3D acceleration is enabled for this VM.
libGL error: failed to load driver: vboxvideo
libGL error: Try again with LIBGL_DEBUG=verbose for more details.
OpenGL Warning: Failed to connect to host. Make sure 3D acceleration is enabled for this VM.
libGL error: failed to load driver: vboxvideo
libGL error: Try again with LIBGL_DEBUG=verbose for more details.
Segmentation fault (core dumped)
(robot)sdet@&#8288;sdet-VirtualBox:/opt/#####/src/qa/#####$ ride.py .

(python2.7:16443): GLib-GObject-WARNING **: instance of invalid non-instantiatable type `&lt;invalid&gt;'

(python2.7:16443): GLib-GObject-CRITICAL **: g_signal_handlers_disconnect_matched: assertion `G_TYPE_CHECK_INSTANCE (instance)' failed

(python2.7:16443): GLib-GObject-WARNING **: instance of invalid non-instantiatable type `&lt;invalid&gt;'

(python2.7:16443): GLib-GObject-CRITICAL **: g_signal_handlers_disconnect_matched: assertion `G_TYPE_CHECK_INSTANCE (instance)' failed

(python2.7:16443): GLib-GObject-WARNING **: instance of invalid non-instantiatable type `&lt;invalid&gt;'

(python2.7:16443): GLib-GObject-CRITICAL **: g_signal_handlers_disconnect_matched: assertion `G_TYPE_CHECK_INSTANCE (instance)' failed

(python2.7:16443): GLib-GObject-WARNING **: instance of invalid non-instantiatable type `&lt;invalid&gt;'

(python2.7:16443): GLib-GObject-CRITICAL **: g_signal_handlers_disconnect_matched: assertion `G_TYPE_CHECK_INSTANCE (instance)' failed

(python2.7:16443): GLib-GObject-WARNING **: instance of invalid non-instantiatable type `&lt;invalid&gt;'

(python2.7:16443): GLib-GObject-CRITICAL **: g_signal_handlers_disconnect_matched: assertion `G_TYPE_CHECK_INSTANCE (instance)' failed

(python2.7:16443): GLib-GObject-WARNING **: instance of invalid non-instantiatable type `&lt;invalid&gt;'

(python2.7:16443): GLib-GObject-CRITICAL **: g_signal_handlers_disconnect_matched: assertion `G_TYPE_CHECK_INSTANCE (instance)' failed
Segmentation fault (core dumped)

**Comment by yanne** [comment]
> *Originally submitted to [Google Code](http://code.google.com/p/robotframework-ride/issues/detail?id=1184#c7) by guy.kisel on 27 Feb 2014*


I had a segfault happen just now when I was rapidly clicking between test tag fields in different test cases and pasting text into them. (I was just trying to update a few tags to mark my tests as implemented).

**Comment by wxjeacen** [comment]
I have this problem as well. How is the status of this ticket?

**Comment by HelioGuilherme66** [comment]
This issue is very old. Please post here the versions of RIDE, O.S., Python and wxPython. Post also the conditions on how the bug happens.

**Comment by chevi** [comment]
_OS: Ubuntu 14.04 x32
RIDE: 1.5.2.1 
Python: 2.7.6
wxPython: 2.8.12.1 (gtk2-unicode)_

**Steps to reproduce:**

1. Oped RIDE
2. Open test
3. Right click on keyword -> Find where used
4. After searching is stopped, click on any result of the search

**Result:** RIDE closed. Error: Segmentation fault (core dumped)

**Comment by MisterChild** [comment]
Same system as chevi...

We couldn't reproduce this but we are faced with this error from time to time. Sometimes (if it crashes) ride crashes during marking cells in table view, sometimes during inserting lines. 

Is there any log file or something to find the root cause?

Best regards.

**Comment by chevi** [comment]
I investigated with [Gdb](https://wiki.python.org/moin/DebuggingWithGdb) and found error "IA__gtk_widget_get_direction: assertion 'GTK_IS_WIDGET (widget)' failed"
Than I changed my GTK theme to standart one and my problem with crash was resolved.

**Comment by HelioGuilherme66** [comment]
Closed because (use OR operator):
- is too old,
- newest version should have it fixed,
- not reproducible,
- not an issue,
- is a question,
- lacks logs, versions info, e.t.c.,
- there is no other reason that justifies being opened.
