### ISSUE TITLE
Keyword auto complete doesn't work when prefixed with Given, Then, And or When

### ISSUE THREAD

**Issue by yanne** [robotframework/RIDE#1224]
> *Originally submitted to [Google Code](http://code.google.com/p/robotframework-ride/issues/detail?id=1185) by iliveina... on 10 Jan 2013*

When writing test cases, auto complete for keywords only works if you aren't using the Gherkin syntax keywords already in the line.

I'd expect the search for keywords to take these into account when looking for auto complete options.

Using:
Python 2.7.3 32 bit 
Windows 7 
RIDE 1.0
Robot Framework 2.7.6

**Comment by yanne** [comment]
> *Originally submitted to [Google Code](http://code.google.com/p/robotframework-ride/issues/detail?id=1185#c1) by @mkorpela on 17 Jan 2013*


You are requesting that Given/When/Then/And should be ignored when autocompletion is checking for keywords?

In my opinion it is not a defect but a feature request.

This goes to future. If someone is willing to make a patch concerning this issue we will happily merge it.

**Comment by yanne** [comment]
> *Originally submitted to [Google Code](http://code.google.com/p/robotframework-ride/issues/detail?id=1185#c2) by @mkorpela on 17 Jan 2013*


You are requesting that Given/When/Then/And should be ignored when autocompletion is checking for keywords?

In my opinion it is not a defect but a feature request.

This goes to future. If someone is willing to make a patch concerning this issue we will happily merge it.

**Comment by yanne** [comment]
> *Originally submitted to [Google Code](http://code.google.com/p/robotframework-ride/issues/detail?id=1185#c3) by o... on 5 Nov 2013*


I have made a possible solution to this issue. To whom can I send it for verification ?

/Simon

**Comment by yanne** [comment]
> *Originally submitted to [Google Code](http://code.google.com/p/robotframework-ride/issues/detail?id=1185#c4) by @pekkaklarck on 5 Nov 2013*


Sounds great! You can either submit a patch here or, preferably, send a pull request to RIDE project on GitHub.

**Comment by HelioGuilherme66** [comment]
Please see if a remake of #17 done by #1573 is good enough to close this issue and PR.

**Comment by yanne** [comment]
This is fixed by #1573
