### ISSUE TITLE
multiple blank display issue

### ISSUE THREAD

**Issue by yanne** [robotframework/RIDE#1242]
> _Originally submitted to [Google Code](http://code.google.com/p/robotframework-ride/issues/detail?id=1203) by lxg0... on 16 Feb 2013_

In version 1.0.1,I got this issue:
I have to input strings that contain multiple spaces.
in txt edit mode ,it is substitude by several "\ ",which is ok.But in edit mode
multiple spaces shrink to single one. The number of spaces does count for me!
could you make an enhancement to support display multiple spaces?

**Comment by yanne** [comment]
> *Originally submitted to [Google Code](http://code.google.com/p/robotframework-ride/issues/detail?id=1203#c1) by @mkorpela on 18 Feb 2013*


Yep. There seems to be issues with whitespaces.

This also affects keyword recognition.

**Comment by jnhyperion** [comment]
in grid `| log | a  a   a  |`  will be converted in text editor `| log       a \ \ a \ \ \ a |`.

But applying changes `| log       a \ \ a \ \ \ a |` in text editor then switch to grid editor, it's not converted at all.

**Comment by HelioGuilherme66** [comment]
Issue fixed:
Screen captures of RIDE v2.0.2.dev1 in Fedora Linux 36, Python 3.10.10, wxPython 4.0.7 (KDE Plasma 5 with darkmode, custom colors):
![image](https://user-images.githubusercontent.com/2866630/230768668-6e35ffa3-6219-4bcf-80ce-ae0b005d63ca.png)

![image](https://user-images.githubusercontent.com/2866630/230768721-af95c313-ff85-4869-a841-4599eecd3d59.png)

Test file:
```robot
*** Test Cases ***
example
    Log    a aa \ aaa \ \ aaaa\n" a quoted and \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ spaced string"
    log    a \ \ a \ \ \ a \ \ \ \ b
    A \ \ \ \ \ \ \ \ spaced keyword    this is a \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ spaced argument
*** Keywords ***
A \ \ \ \ \ \ \ \ spaced keyword
    [Arguments]    ${arg \ \ \ \ \ one}=None
    Log    Argument one is \ \ \ \ \ \ \ \ \ \ \ \ ${arg \ \ \ \ \ one}

```
