### ISSUE TITLE
Hover tooltip takes focus off RIDE window

### ISSUE THREAD

**Issue by yanne** [robotframework/RIDE#1244]
> _Originally submitted to [Google Code](http://code.google.com/p/robotframework-ride/issues/detail?id=1205) by rojwi... on 20 Feb 2013_

When using the RIDE test case or keyword editor grid, if I hover over a cell with a keyword or parameter, the yellow tooltip will pop up showing context information.  However, this tooltop takes focus away from the RIDE window, preventing me from sending any keyword input to RIDE (such as pressing 'CTRL' to get more information about the keyword, or simply editing the field).  I have to move the mouse away to some spot where it won't pop-up a tooltip to continue using RIDE, which is frustrating when I'm trying to quickly make changes.

Mac OSX 10.7.5
Python 2.7.2
Robot Framework 2.7.6 (Python 2.7.2 on darwin)
RIDE 1.1

**Comment by yanne** [comment]
> *Originally submitted to [Google Code](http://code.google.com/p/robotframework-ride/issues/detail?id=1205#c2) by @mkorpela on 25 Feb 2013*


Currently RIDE core team doesn't work on OSX related defects. Patches can be included if someone from the open source community will provide them.

**Comment by yanne** [comment]
> *Originally submitted to [Google Code](http://code.google.com/p/robotframework-ride/issues/detail?id=1205#c3) by @yanne on 28 May 2015*


I took a look at this, but it seems that for some reason setting focus to the grid does not work correctly in OSX. Could not create a reasonable workaround either.

**Comment by serhatbolsu** [comment]
hi, 
Is there any update or workaround this problem, for years this has been preventing using ride smootly
Thank you

**Comment by jnhyperion** [comment]
Not reproduced in latest version.
