### ISSUE TITLE
Cannot click through to keyword after external file change

### ISSUE THREAD

**Issue by robotframework-ride** [robotframework/RIDE#1263]
> _Originally submitted to [Google Code](http://code.google.com/p/robotframework-ride/issues/detail?id=1225) by stevejeffers on 13 Mar 2013_

RIDE: 1.1
Python: 2.7.3
wxPython: 2.8.12.1

To reproduce:
1. Open a test suite which links to a resource file containing keywords used in one of the tests in the test suite
2. Check that you can click through to the resource file keywords from the test
3. Make a change to the resource file outside of RIDE
4. In RIDE focus on the resource file so that you are prompted to reload - click Yes when prompted
5. Attempt to click through to the resource file keywords from the test - This is no longer possible the link between the test and the resource file appears to be broken. You have to reload the project in RIDE to make it work again.

I've attached an simple example project - unzip and open that directory in RIDE, check the link in TC1 to KW1 works when clicked, make an external change to resource_1.txt, click the resource file in RIDE and click yes to reload with the external changes. Then try and click the KW1 link in TC1.

**Comment by jnhyperion** [comment]
resolved by: https://github.com/robotframework/RIDE/pull/2232
