### ISSUE TITLE
RIDE not refreshing new resources from its path

### ISSUE THREAD

**Issue by robotframework-ride** [robotframework/RIDE#1264]
> _Originally submitted to [Google Code](http://code.google.com/p/robotframework-ride/issues/detail?id=1226) by lesiec... on 13 Mar 2013_
1. I have saved file with not existing resource path (marked as red) - cause there is different path on test enviroment.
2. Change resource path to correct file
3. Saving changes.
4. In "Suite explorer" on the left side new keywords are not visible - it is necessary to restart RIDE to see them.

**Comment by HelioGuilherme66** [comment]
This issue is still observable on 1.7.4.1dev0, Windows10, wxPython 4.0.7post2 and Python 2.7.16.

**Comment by jnhyperion** [comment]
Close due to fail to reproduce this bug.
