### ISSUE TITLE
error message "Trying to remove a child that doesn't believe we're it's parent"

### ISSUE THREAD

**Issue by robotframework-ride** [robotframework/RIDE#1269]
> *Originally submitted to [Google Code](http://code.google.com/p/robotframework-ride/issues/detail?id=1231) by jerry57 on 21 Mar 2013*

RIDE v1.1
OS Ubuntu 64 12.04
Python v2.7.3
wxPython '2.8.12.1 (gtk2-unicode)'

Every time I close RIDE on Ubuntu 12.04 I am getting the following:

(python:24493): LIBDBUSMENU-GLIB-WARNING **: Trying to remove a child that doesn't believe we're it's parent.

(python:24493): LIBDBUSMENU-GLIB-WARNING **: Trying to remove a child that doesn't believe we're it's parent.

(python:24493): LIBDBUSMENU-GLIB-WARNING **: Trying to remove a child that doesn't believe we're it's parent.

(python:24493): LIBDBUSMENU-GLIB-WARNING **: Trying to remove a child that doesn't believe we're it's parent.

(python:24493): LIBDBUSMENU-GLIB-WARNING **: Trying to remove a child that doesn't believe we're it's parent.

(python:24493): LIBDBUSMENU-GLIB-WARNING **: Trying to remove a child that doesn't believe we're it's parent.

command to open RIDE was:
"ride.py . &amp;"

**Comment by yanne** [comment]
This is obviously a wxPython problem, and since it's not fatal, I think we can safely close it here.
