### ISSUE TITLE
Ride hangs the system occasionally

### ISSUE THREAD

**Issue by robotframework-ride** [robotframework/RIDE#1270]
> *Originally submitted to [Google Code](http://code.google.com/p/robotframework-ride/issues/detail?id=1232) by berryman... on 22 Mar 2013*

Using RIDE 1.1 running on Python 2.7.3 on Windows 7 64-bit 16GB RAM 4 cores 3 GHz.

During normal use of RIDE, navigating the test hierarchy, editing a keyword etc, the whole system will occasionally hang and lock up.

No more navigation within RIDE so you try to alt-tab away but the system just queues the requests up.  Can't bring up the task manager, click on the task bar etc.  Ctrl + alt + delete does work, but seems to be the only thing.

A couple of the cores seem to spike when watching the task manager but not enough to explain the lock up.

Sorry this isn't more reproducible but it does happen every few minutes for a couple of seconds.  Our source files are 120 odd MB, python session for RIDE is using about 300 MB (from task manager).

**Comment by robotframework-ride** [comment]
> *Originally submitted to [Google Code](http://code.google.com/p/robotframework-ride/issues/detail?id=1232#c1) by berryman... on 26 Mar 2013*


Also happens in 1.0.1 seems to happen most obviously when opening a resource link, but does seem to happen just navigating, so I wondered if it had anything to do with background checking for changed files...

I'll keep trying to reproduce, effectively.

**Comment by robotframework-ride** [comment]
> *Originally submitted to [Google Code](http://code.google.com/p/robotframework-ride/issues/detail?id=1232#c2) by @mkorpela on 27 Mar 2013*


thanks for the report!

**Comment by yanne** [comment]
This issue is too vague to be kept open, sorry.
