### ISSUE TITLE
Extreme slowdown during test data loading after excluding "suite" directories and relaunching ride 

### ISSUE THREAD

**Issue by robotframework-ride** [robotframework/RIDE#1278]
> _Originally submitted to [Google Code](http://code.google.com/p/robotframework-ride/issues/detail?id=1240) by saka.... on 4 Apr 2013_

System information: Ubuntu 12.04(.02) 64bit, Robot Framework 2.7.7, python 2.7.3, wxPython 2.8.12.1
(from ride's log. pybot --version and lsb_release -a)
Longer system data included at the end of this.

As far as i'm aware, everything's using the latest version.

The problem: Exclude.
We have several(make that hundreds) testcase directories(just directories containing test specific files) inside the suite directories.
Tried out excluding them yesterday, in an attempt to make the scrolling less tedious.

Restarting RIDE after this caused extreme slowdown in loading the test data(Automatically opening the last recently used location after restart). It started loading just fine, but didn't finish - went busy, gray.
Forced quit, then opened a smaller section of the tests with RIDE, had slowdowns again - from the usual 5-6 seconds to 9 seconds + busy, nonresponding time(ranging from half a minute to a whole minute). It actually loaded!

In search of a possible solution, a few python errors sparsely appeared in the terminal. There were other errors, like one or two times but i couldn't manage to reproduce them - those dealt with "non existing directory ...", actual ride/robot-framework erros. (Of course, those directories existed.)

Two of these were:
- python: Fatal IO error 11 (Resource temporarily unavailable) on X server localhost:10.0
- python: Fatal IO error 0 (Success) on X server localhost:10.0

I tracked the problem down to the file: ~/.robotframework/ride/excludes
Removed it and there were/are no more slowdowns. The list had over a 100 entries.(~115ish?)

As a daring guess, it would be a "problem" in loading the whole test directory while checking against/for excluded stuff.

Maybe i shouldn't be fiddling with exclude, but rather i'd need something in RIDE that could make non-suite-related directories hidden.

Longer version of system data:
ride's log:
20130404 09:48:49.159 [INFO]: Started RIDE 1.1 using python version 2.7.3 with wx version 2.8.12.1 in linux2.

pybot --version:
Robot Framework 2.7.7 (Python 2.7.3 on linux2)

lsb_release -a:
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 12.04.2 LTS
Release:    12.04
Codename:   precise

uname -a:
Linux test-server2 3.2.0-39-generic #62-Ubuntu SMP Thu Feb 28 00:28:53 UTC 2013 x86_64 x86_64 x86_64 GNU/Linux

**Comment by robotframework-ride** [comment]
> *Originally submitted to [Google Code](http://code.google.com/p/robotframework-ride/issues/detail?id=1240#c1) by @mkorpela on 4 Apr 2013*


Thanks for the report!

**Comment by robotframework-ride** [comment]
> *Originally submitted to [Google Code](http://code.google.com/p/robotframework-ride/issues/detail?id=1240#c2) by @Tattoo on 3 Sep 2013*


saka.tox: do you remember how exactly did you excluded the files?

**Comment by robotframework-ride** [comment]
> *Originally submitted to [Google Code](http://code.google.com/p/robotframework-ride/issues/detail?id=1240#c3) by saka.... on 3 Sep 2013*


Thankfully yes.

I right-clicked on the "resource" folders under a given test suite directory and excluded them one by one.

Let me provide a cropped screenshot example, for a more clear case.

**Comment by jnhyperion** [comment]
Closed, cannot reproduce
