### ISSUE TITLE
Adding a line to seperate between tests in Message Log

### ISSUE THREAD

**Issue by robotframework-ride** [robotframework/RIDE#1282]
> _Originally submitted to [Google Code](http://code.google.com/p/robotframework-ride/issues/detail?id=1244) by MeitalBo... on 14 Apr 2013_

Adding a line to seperate between tests in Message Log.
It will make it easier to debug failures without the need to open the Log file.

**Comment by robotframework-ride** [comment]
> *Originally submitted to [Google Code](http://code.google.com/p/robotframework-ride/issues/detail?id=1244#c1) by @mkorpela on 21 May 2013*


There is already a line between test executions in message log.

Example:

Starting test: Tmp.Suite.Passing
Ending test:   Tmp.Suite.Passing

Starting test: Tmp.Suite.Failing
20130521 14:13:58.135 :  FAIL : AssertionError
Ending test:   Tmp.Suite.Failing

Could you clarify what do you mean?

**Comment by robotframework-ride** [comment]
> *Originally submitted to [Google Code](http://code.google.com/p/robotframework-ride/issues/detail?id=1244#c2) by MeitalBo... on 21 May 2013*


Not an empty line, something like this:

Starting test: Tmp.Suite.Passing
Ending test:   Tmp.Suite.Passing

************************************************************

Starting test: Tmp.Suite.Failing
20130521 14:13:58.135 :  FAIL : AssertionError
Ending test:   Tmp.Suite.Failing

**Comment by jnhyperion** [comment]
Feature already implemented.
