### ISSUE TITLE
When saving or focusing out from the Text Editor it jumps to the top

### ISSUE THREAD

**Issue by robotframework-ride** [robotframework/RIDE#1284]
> _Originally submitted to [Google Code](http://code.google.com/p/robotframework-ride/issues/detail?id=1246) by MeitalBo... on 17 Apr 2013_

When saving or focusing out from the Text Editor it jumps to the top, and it's annoying. I think that it should stay at the last cursor position.

**Comment by HelioGuilherme66** [comment]
Closing because can be tested on soon to be pre-released, v2.0b1.
