### ISSUE TITLE
Show arguments and return values when standing on a keyword

### ISSUE THREAD

**Issue by robotframework-ride** [robotframework/RIDE#1287]
> *Originally submitted to [Google Code](http://code.google.com/p/robotframework-ride/issues/detail?id=1249) by MeitalBo... on 28 Apr 2013*

Currently the only way to see the arguments and return values of a keywords is by going to the "Text Edit" tab.

It would be nice if standing on a keyword whould open a text window with the arguments and return values (like the usage box).

**Comment by robotframework-ride** [comment]
> *Originally submitted to [Google Code](http://code.google.com/p/robotframework-ride/issues/detail?id=1249#c1) by @mikahanninen on 4 Jun 2013*


You can see the KW details when mouse is over the KW name. After small delay the pop up shows information about the KW and pressing CTRL will reveal arguments also.

Granted it does not show return value.

**Comment by yanne** [comment]
The arguments and return value are part of the keyword's settings. I think that should be enough.
