### ISSUE TITLE
RIDE says "Invalid Data File" when opening Resource Files using the UI. 

### ISSUE THREAD

**Issue by robotframework-ride** [robotframework/RIDE#1296]
> *Originally submitted to [Google Code](http://code.google.com/p/robotframework-ride/issues/detail?id=1258) by acampbell on 12 Jun 2013*

It is possible to open resource files from the command line using 

ride.py &lt;filename&gt;

in the same manner as one would open test cases.

However, when attempting to use Open (ie, Open Test Suite) a popup is shown saying "invalid data file."

Some problems with this - 
1. "invalid data file" doesn't indicate the actual problem, that you are trying to load a resource using a test suite method. 

2. The 'Open' dialogue doesn't specify that you are loading a test suite (ie, exclusively a test suite). So if you always use ctrl+o, you have absolutely no indication as to why the file won't open.

3. ride.py starts equally well when opening testsuites or resource files on the command line, and the problems only seem to occur through the UI.

**Comment by robotframework-ride** [comment]
> *Originally submitted to [Google Code](http://code.google.com/p/robotframework-ride/issues/detail?id=1258#c1) by acampbell on 13 Jun 2013*


Took a dive into the source code, and found that changing mainframe.py to

    def open_suite(self, path):
        self._controller.update_default_dir(path)
        self._controller.load_data(path, LoadProgressObserver(self))
        self._populate_tree()

worked to 'alleviate' the issue. The behavior is exactly the same opening from the command line, while the Ctrl+O adds the resource to the external resources list. The behavior seemed odd until I realized that the external resources is independent of what resources are actually used by the test suite.

An alternate (probably better) fix would be an 'Open Resource' menu button. I think the way load_data falls back is keeping the previously open test suite open, leading to the 'adding' behavior for the resource.

**Comment by robotframework-ride** [comment]
> *Originally submitted to [Google Code](http://code.google.com/p/robotframework-ride/issues/detail?id=1258#c2) by @jussimalinen on 17 Jul 2013*


When would you like to use this? I could see why someone would like to edit a resource file alone without having any suites open.

But is there really a need to open resource files that are not used in a test suite, but still keep that suite open?

**Comment by robotframework-ride** [comment]
> *Originally submitted to [Google Code](http://code.google.com/p/robotframework-ride/issues/detail?id=1258#c3) by HarmanTe... on 17 Jul 2013*


I need to do this all the time, and I have trained countless people in RF usage. The intuitive way to open and edit a resource file is to ctrl+o and select the resource file, but this does not work. 

The bottom line is, both Test Suites and Resource files are valid RF file formats. However, only one is working through the open menu item, and it doesn't need to be this way. At a bare minimum, the texts for the open dialog and the error message should more specifically alert the user to the problem.

**Comment by robotframework-ride** [comment]
> *Originally submitted to [Google Code](http://code.google.com/p/robotframework-ride/issues/detail?id=1258#c4) by @jussimalinen on 18 Jul 2013*


Which approach would then be better? Open the resource file alone and close all existing files or open it as an additional external resource and keep existing suite open?

Or are these somehow different use cases and should both be supported? Humm...

(Of course already now when you import a resource in your test suite, it will then always be available.)

**Comment by yanne** [comment]
I think that we should drop the support of opening individual files altogether, and instead focus on directory based projects.
