### ISSUE TITLE
saving txt file in text edit mode automatically scrolls to the top (l

### ISSUE THREAD

**Issue by robotframework-ride** [robotframework/RIDE#1297]
> *Originally submitted to [Google Code](http://code.google.com/p/robotframework-ride/issues/detail?id=1259) by sajjadmalang on 18 Jun 2013*

**Explain the defect you encountered either using free text or steps. Mention**
**the expected and actual results.**

**Always include the framework version, Python or Jython version, and**
**operating system. You can, for example, copy the output of 'pybot/jybot**
**--version'.**

**For new features and other enhancements, please use the Enhancement request**
**template.**

**All this text can be deleted.**

**Comment by robotframework-ride** [comment]
> *Originally submitted to [Google Code](http://code.google.com/p/robotframework-ride/issues/detail?id=1259#c1) by sajjadmalang on 18 Jun 2013*


Sorry i pressed enter without filling out the description and it got submitted. Please find the description below.

When I save a file in "text edit" mode with ctr+s or save button it automatically scrolls to the top of the page (similar to what happens when pressing ctr+home).

Its a bit confusing and i end up editing the wrong keyword. I dont expect that save with scroll, so i logged it as a defect. maybe its a feature request.

version
RIDE 1.1 running on Python 2.7.2. 
Robot Framework 2.7.7 (Python 2.7.2 on win32)
Win7

**Comment by robotframework-ride** [comment]
> *Originally submitted to [Google Code](http://code.google.com/p/robotframework-ride/issues/detail?id=1259#c2) by @jussimalinen on 17 Jul 2013*


I would call this a defect. Pretty annoying.

**Comment by robotframework-ride** [comment]
> *Originally submitted to [Google Code](http://code.google.com/p/robotframework-ride/issues/detail?id=1259#c4) by @mkorpela on 9 Sep 2013*


Now using old caret position whenever data is reset.
<a href="https://github.com/robotframework/RIDE/commit/c770c15c0428433a2211b8ae79ac0a6b627b323f" rel="nofollow">https://github.com/robotframework/RIDE/commit/c770c15c0428433a2211b8ae79ac0a6b627b323f</a>

Marking this issue as Done.

**Comment by etiaxie** [comment]
i find similar bug in 2.0alpha 1,after I save the text,it will scroll up a few lines until my last modify line be the last line of the editor view
