### ISSUE TITLE
Persist font size changes done in text editor

### ISSUE THREAD

**Issue by robotframework-ride** [robotframework/RIDE#1298]
> _Originally submitted to [Google Code](http://code.google.com/p/robotframework-ride/issues/detail?id=1260) by sajjadmalang on 18 Jun 2013_

The default font size on text edit tab is too big. So i ctr+scroll to reduce the font size. But when i switch to the edit tab and then back to the "text edit" tab the font size is reset to the initial size. should be this an enhancement request or bug report?

Thanks,

version
RIDE 1.1 running on Python 2.7.2. 
Robot Framework 2.7.7 (Python 2.7.2 on win32)
Win7

**Comment by robotframework-ride** [comment]
> *Originally submitted to [Google Code](http://code.google.com/p/robotframework-ride/issues/detail?id=1260#c1) by @mikahanninen on 19 Jun 2013*


What is your text editor font size ? (check from menu Tools - Preferences, item "Text Edit Colors and Font Size")

**Comment by robotframework-ride** [comment]
> *Originally submitted to [Google Code](http://code.google.com/p/robotframework-ride/issues/detail?id=1260#c2) by sajjadmalang on 19 Jun 2013*


The font size is 8 and my screen resolution is 1600x900. I have very long sqls and unix commands. so its had to see it. please see attached screen shot.

**Comment by robotframework-ride** [comment]
> *Originally submitted to [Google Code](http://code.google.com/p/robotframework-ride/issues/detail?id=1260#c3) by @mkorpela on 19 Jun 2013*


I think this is a valid issue (call it a bug or a feature): default font size should be updated if scintilla ctrl-scroll zoom is used.

**Comment by Nyral** [comment]
@HelioGuilherme66 

"But when i switch to the edit tab and then back to the "text edit" tab the font size is reset to the initial size."

In latest version the size is not reset. Ctrl-scroll doesn't change the actual font size. If anything, the better solution here would be to increase font size range. Currently it's only between 8 and 15.
