### ISSUE TITLE
[Error 123] The filename, directory name, or volume label syntax is incorrect

### ISSUE THREAD

**Issue by robotframework-ride** [robotframework/RIDE#1302]
> *Originally submitted to [Google Code](http://code.google.com/p/robotframework-ride/issues/detail?id=1264) by myaskev... on 20 Jul 2013*

I face the following error every time I'm trying to run the tests:

[Error 123] The filename, directory name, or volume label syntax is incorrect

RIDE console gives me the following output:

command:  --argumentfile c:\users\myaske~1\appdata\local\temp\RIDEritjej.d\argfile.txt --listener "C:\Program Files (x86)\Python 2.7.3\lib\site-packages\robotide\contrib\testrunner\TestRunnerAgent.py:50975" D:\teee\teee.txt
[Error 123] The filename, directory name, or volume label syntax is incorrect

RIDE 1.1 running on Python 2.7.3.
Robot Framework 2.8.1 (Python 2.5.4 on win32)
Python 2.5.4 (the only Python in the PATH)
Windows 7 Version 6.1 (Build 7601: SP1)

**Comment by robotframework-ride** [comment]
> *Originally submitted to [Google Code](http://code.google.com/p/robotframework-ride/issues/detail?id=1264#c1) by myaskev... on 20 Jul 2013*


Sorry. I didn't notice that my Execution profile setting was actually set to "custom script" instead of "pybot".

Please close the issue.

**Comment by robotframework-ride** [comment]
> *Originally submitted to [Google Code](http://code.google.com/p/robotframework-ride/issues/detail?id=1264#c2) by @jussimalinen on 23 Jul 2013*


okay, good that you found the problem.

**Comment by kalyanghosh** [comment]
I too am facing the same problem.
Can you please elaborate on the steps to resolve the issue.

Thanks
