### ISSUE TITLE
Bad error message when Robot Framework is not installed

### ISSUE THREAD

**Issue by robotframework-ride** [robotframework/RIDE#1317]
> *Originally submitted to [Google Code](http://code.google.com/p/robotframework-ride/issues/detail?id=1279) by @Tattoo on 3 Sep 2013*

RIDE could give a better error message if Robot Framework is not installed to the system.

Now it says "Cannot find file" which is really confusing.

**Comment by robotframework-ride** [comment]
> *Originally submitted to [Google Code](http://code.google.com/p/robotframework-ride/issues/detail?id=1279#c3) by @yanne on 2 Jun 2015*


Fixed in <a href="https://github.com/robotframework/RIDE/commit/468c18b168735f875de0295514c232fc4b97bd27" rel="nofollow">https://github.com/robotframework/RIDE/commit/468c18b168735f875de0295514c232fc4b97bd27</a>

**Comment by yanne** [comment]
#1464 happens after the fix.

**Comment by michel117** [comment]
I can verify that error message does not appear any more after sucessful test run on Mac OS 10.10.3
