### ISSUE TITLE
Please keep the origin text format

### ISSUE THREAD

**Issue by robotframework-ride** [robotframework/RIDE#1333]
> *Originally submitted to [Google Code](http://code.google.com/p/robotframework-ride/issues/detail?id=1295) by 52537380... on 17 Oct 2013*

I don't use RIDE for developing robot framework case. And I neat, elegant code style when develop code or automation.

But there's big problem which make me so annoyed, after I write test case or resource file using vim or sublime text, the texts were always messed by my colleague's RIDE!

git diff result is as follows,

     Wait Until Input Form Show Up
-    ${row num} =       Get Activity Row Number    ${activity}
-    Run Keyword If     0 &lt; ${row num} &lt; 3         Input Text
-               ...     xpath=//tr[${row num}]/td[6]/div/span/form/input
-               ...     ${UsualAccount}${\n}
-               ...     ELSE                       Input Text
-               ...     xpath=//tr[1]/td[6]/div/span/form/input
-               ...     ${UsualAccount}${\n}
+    ${row num} =    Get Activity Row Number    ${activity}
+    Run Keyword If    0 &lt; ${row num} &lt; 3    Input Text    xpath=//tr[${row num}]/td[6]/div/span/form/input    ${UsualAccount}${\n}    ELSE    Input Text
+    ...    xpath=//tr[1]/td[6]/div/span/form/input    ${UsualAccount}${\n}
     Submit Form

above all, I sincerely hope you can add a configuration about keeping the origin text format when open robot framework files.

Thanks,
Xin

**Comment by michel117** [comment]
So, where is the duplicate?
I have the same problem:
e.g.:
    Library           ../../.
becomes
    | Library        | ../..
Would be great to have an option not to touch the files?
Or if this is not possible for now:
What is the preferred, supported robot file format in order to not run into these kind of problems?
Thank you.
