### ISSUE TITLE
support Free keyword arguments (**kwargs) in RIDE

### ISSUE THREAD

**Issue by robotframework-ride** [robotframework/RIDE#1341]
> *Originally submitted to [Google Code](http://code.google.com/p/robotframework-ride/issues/detail?id=1303) by qit... on 10 Nov 2013*

Robot Framework 2.8 added the support for free keyword arguments using Python's **kwargs syntax.

platform:
Win7 32bit
RF 2.8.1
RIDE 1.2.1

I create a test library and one method user free keyword arguments. the code is :

def demo(**kwargs):
    for name, value in kwargs.items():
        print 'kwarg:', name, value

When I call this keyword in RIDE, the arguments cell is red.
Well, I run the case and it passed.
So it looks red but can run pass.

I hope new version RIDE can support keywords with **kwargs. Tks.

**Comment by robotframework-ride** [comment]
> *Originally submitted to [Google Code](http://code.google.com/p/robotframework-ride/issues/detail?id=1303#c2) by zycha... on 20 Aug 2014*


this will be good for fresh man to understand.

**Comment by robotframework-ride** [comment]
> *Originally submitted to [Google Code](http://code.google.com/p/robotframework-ride/issues/detail?id=1303#c3) by @yanne on 19 May 2015*


<a class="closed_ref" href="https://code.google.com/p/robotframework-ride/issues/detail?id=1373" title="red marked after input argument to kwargs that with **kwargs parameter in library"> Issue 1373 </a> has been merged into this issue.

**Comment by yanne** [comment]
This is resolved as part of #1446
