### ISSUE TITLE
Copy multiple rows to pop-up menu

### ISSUE THREAD

**Issue by robotframework-ride** [robotframework/RIDE#1352]
> _Originally submitted to [Google Code](http://code.google.com/p/robotframework-ride/issues/detail?id=1312) by aki.sivula on 4 Dec 2013_

Grid has "Insert rows", "Delete rows" etc. but no "Copy rows" functionality. Only way to copy multiple rows contents is to select rectangular area and then copy cells.

It would be useful to have such feature as it improves usability.

Version: Ride 1.2.2
OS: Windows 7 64bit SP1

**Comment by robotframework-ride** [comment]
> *Originally submitted to [Google Code](http://code.google.com/p/robotframework-ride/issues/detail?id=1312#c1) by @mkorpela on 9 Dec 2013*


Grid has a row specific context menu in the first column with numbers ( I assume you are referring to this one? ).

Copy operation currently can be done already from context menu that comes from the grid (not the first column), or from Edit menu or by pressing Ctrl+C.

If I understood it correctly, you are now requesting adding this also in the row specific context menu.
I'll mark this request as accepted.

**Comment by robotframework-ride** [comment]
> *Originally submitted to [Google Code](http://code.google.com/p/robotframework-ride/issues/detail?id=1312#c2) by aki.sivula on 9 Dec 2013*


Yes I referred to the context menu that is shown when clicking with 2nd mouse button the column with numbers.

**Comment by HelioGuilherme66** [comment]
Fixed long time ago, probably after 2.0.8.1.
Columns are now selectable. The cells menus have the Copy/Paste function for selected Rows and Columns.
Users should only copy one Column at the time, for Rows multiple are OK.
