### ISSUE TITLE
Sometimes RIDE does not show message log and the test hang

### ISSUE THREAD

**Issue by robotframework-ride** [robotframework/RIDE#1356]
> *Originally submitted to [Google Code](http://code.google.com/p/robotframework-ride/issues/detail?id=1316) by lianglia... on 18 Dec 2013*

The "Show message log" checkbox is checked, usually the first try works, message log is printed at the bottom section, but the second try will fail: no message log printed, and the test hang there.

The versions:

robotframework 2.8.3
robotframework-ride 1.2.3
robotframework-selenium2library 1.4.0
selenium 2.39.0

My machine is Win7 sp1 64 bit, and IE 9.

**Comment by robotframework-ride** [comment]
> *Originally submitted to [Google Code](http://code.google.com/p/robotframework-ride/issues/detail?id=1316#c1) by @mkorpela on 21 Jan 2014*


Could you give a concrete example case where this happens?

**Comment by robotframework-ride** [comment]
> *Originally submitted to [Google Code](http://code.google.com/p/robotframework-ride/issues/detail?id=1316#c2) by kairanta on 16 Jan 2015*


I've seen this also in situation where you run a test that doesn't close the browser. If you don't manually close the browser, the following test runs will have this effect, message log is not visible and test hangs.

After this it doesn't help just to close browsers and try again, but I have to kill RIDE (it hangs when trying to close properly). and open it again to make the tests start working. 

Haven't seen this issue when test closes browser properly or if you manually close the browser before running a new test.

My environment:
robotframework 2.8.6
robotframework-ride 1.3 running python 2.7.8
robotframework-selenium2library 1.6.0
Win7 64bit
Chrome 39.0.2171.95

**Comment by robotframework-ride** [comment]
> *Originally submitted to [Google Code](http://code.google.com/p/robotframework-ride/issues/detail?id=1316#c3) by cesargau... on 1 Apr 2015*


Running: 
Windows 7 Professional 64 bit
RIDE 1.3 with Python 2.7.9
robotframework 2.8.7
Selenium2Library 1.6.0
AppiumLibrary 1.2.5


- I too have experienced this issue.

Example:
In your resource.txt or resource.robot file declare the "Selenium2Library" and the "AppiumLibrary".  Both of these libraries have a 'Capture Page Screenshot' feature takes a snapshot of the page, upon failure.

If a user does not disable one of the 'Capture Page Screenshot' features or does not tell RIDE which 'Capture Page Screenshot' to use - the following happens:

If and when the test fails:

Log Message Reads: 
Multiple keywords with name 'Capture Page Screenshot' found.
Give the full name of the keyword you want to use.
Found: 'AppiumLibrary.Capture Page Screenshot' and 'Selenium2Library.Capture Page Screenshot'

The open browser under test - does not close - it hangs.  The user must close the browser manually.

If the user tries to run the test again, or any other test, the LOG mechanism is no longer workign (aka: logging/debugging).  The bottom pane is blank.

When the user tries to close out RIDE, it hangs. The user has to manually kill the process using "Task Manager".

After killing RIDE, the user starts RIDE again, the logging mechanism is now working fine.

This is repeatable.

**Comment by yanne** [comment]
I think the problem really is that the Selenium session is not cleaned. RIDE itself cannot know that Selenium is used, so it's unable to do the cleanup. You need to always make sure that Close Browser keyword is used in Test/Suite Teardown to prevent this problem.

This is not a RIDE issue, so I'll close it.
