### ISSUE TITLE
Persist manual set column width

### ISSUE THREAD

**Issue by robotframework-ride** [robotframework/RIDE#1361]
> _Originally submitted to [Google Code](http://code.google.com/p/robotframework-ride/issues/detail?id=1321) by thorsten.froehlich.7000 on 24 Jan 2014_

It is annoying, that grid cells are always set back to default size when changing the view.
It would be great if manual set column width would be persistet or if grid cells work like the content based 'flowsized' Tag fields.

**Comment by robotframework-ride** [comment]
> *Originally submitted to [Google Code](http://code.google.com/p/robotframework-ride/issues/detail?id=1321#c1) by derek.robati on 26 Mar 2014*


I agree. This is very irritating. It is pointless as of now to adjust the cell width because I move around user keywords and test case frequently.

Thanks.

**Comment by robotframework-ride** [comment]
> *Originally submitted to [Google Code](http://code.google.com/p/robotframework-ride/issues/detail?id=1321#c4) by oriordan... on 30 May 2015*


ya thats wastes alot of time for me also

**Comment by Nyral** [comment]
@HelioGuilherme66 Latest RIDE version can autosize columns depending on content. I don't think there's any point in keeping this issue open.
