### ISSUE TITLE
Pressing delete in the search box on the text edit tab, deletes from the test text.

### ISSUE THREAD

**Issue by robotframework-ride** [robotframework/RIDE#1367]
> _Originally submitted to [Google Code](http://code.google.com/p/robotframework-ride/issues/detail?id=1327) by ate.fokk... on 11 Feb 2014_

The title says most of it.
1. type something in the search box on the text edit tab.
2. use the delete key to remove something from the search box

Expected result: characters are removed from the search box
Actual result: characters are removed from text file, where the caret was.

This is using RIDE 1.2.3

**Comment by HelioGuilherme66** [comment]
This is valid on 1.5.2.1 (as reported on Slack by @stefan)
![2016-11-24 08h57_58](https://cloud.githubusercontent.com/assets/2866630/20600500/e18dab40-b24b-11e6-8c0b-28587465aa67.gif)

**Comment by Nyral** [comment]
@HelioGuilherme66 I can't reproduce it anymore.

**Comment by HelioGuilherme66** [comment]
@Nyral It is still valid in 1.7.4a1dev1! (from 2014!!!)

**Comment by Nyral** [comment]
@HelioGuilherme66 I tried that, really. 
On what OS did you check?

**Comment by HelioGuilherme66** [comment]
Fedora 28, wxPython 4.0.5, Python 3.6.8.
