### ISSUE TITLE
Change format -> import list events do not work

### ISSUE THREAD

**Issue by robotframework-ride** [robotframework/RIDE#1368]
> *Originally submitted to [Google Code](http://code.google.com/p/robotframework-ride/issues/detail?id=1328) by @mkorpela on 12 Feb 2014*

Structure:
tests/foo.txt:
*** Settings ***
Resource          Zoo.txt

*** Test Cases ***
Bar
    No Operation

tests/zoo.txt
*** Keywords ***
uk
    No Operation:

---- WHAT TO DO TO REPRODUCE
1) on tests level change format recursively to .robot
2) Go to foo.robot import table and do changes
--&gt; File changed updates marker (*) doesn't appear to foo.robot

**Comment by yanne** [comment]
I do not think it wise to spend time on format changing functionality. These can always be handled with robotidy.
