### ISSUE TITLE
Use installed RF to list standard libraries

### ISSUE THREAD

**Issue by robotframework-ride** [robotframework/RIDE#1371]
> *Originally submitted to [Google Code](http://code.google.com/p/robotframework-ride/issues/detail?id=1331) by qit... on 20 Feb 2014*

Robotframework2.8.3
RIDE 1.2.3

the BuiltIn Library in Robotframework 2.8.3 add new keywords, for example: Log to Console.
In RIDE , press F5, search keyword can't find it in BuiltIn. The color of this keyword is black.
Running the test case is OK.

There are many new keywords in Robotframework (2.8.3) Libraries can't be shown in RIDE search keyword.

I think maybe it find the RIDE's lib Robotframework ,and it is old version.

**Comment by robotframework-ride** [comment]
> *Originally submitted to [Google Code](http://code.google.com/p/robotframework-ride/issues/detail?id=1331#c1) by @yanne on 19 May 2015*


You are correct, the bundled RF takes precedence over installed RF. This should be fixed.

**Comment by aaltat** [comment]
Just thinking out loud, would this be a problem if the jar file is used?

**Comment by yanne** [comment]
I think I found a reasonably elegant solution:

1) on start up, check RF installation location. This can be done e.g. with `subprocess`, by running `[sys.executable, '-c', 'import robot; print robot.__file__']`
2) If RF installation is found, modify `sys.path` in such a way that installed RF libraries is found before bundled RF libraries.

This of course requires that RF is installed with same Python as RIDE, but hopefully this is not a huge problem. If you are using the jar file, you either have to live with the bundled libraries, or install Python version of RF just for the sake of RIDE.

**Comment by aaltat** [comment]
Would it be feasible to make RF as dependency for RIDE?

**Comment by yanne** [comment]
The reason for bundling RF with RIDE is to protect against API changes. We want to avoid users breaking RIDE by upgrading RF, and on the other hand, it's impossible to release RF and compatible RIDE release at the same time. If Python had more sensible packaging and dependency system (i.e. possibility to have multiple versions of the same package installed in parallel), this would not be a problem.

**Comment by aaltat** [comment]
I did not think that, point well made.
