### ISSUE TITLE
Ctrl + Up don't work on Ubuntu

### ISSUE THREAD

**Issue by robotframework-ride** [robotframework/RIDE#1377]
> _Originally submitted to [Google Code](http://code.google.com/p/robotframework-ride/issues/detail?id=1337) by guillaum... on 4 Mar 2014_

System : Linux 3.2.0-59-generic #90-Ubuntu SMP Tue Jan 7 22:43:51 UTC 2014 x86_64 x86_64 x86_64 GNU/Linux

Python : Python 2.7.3

Description : 
When a test case is selected, a Ctrl + Up must make de test case go up in the list (and Ctrl + Down make it go down).
That doesn't work on Ubuntu.

**Comment by maxrossello** [comment]
Any plan to fix this in Linux? It is very uncomfortable to use the right-click menu for each single step and it is a very common situation for me.
Thanks

**Comment by HelioGuilherme66** [comment]
This issue is not reproducible in Fedora Linux 36, Python 3.10.10, wxPython 4.0.7, 4.2.0. RIDE 2.0.2.dev1.
