### ISSUE TITLE
Must click a cell twice to input Chinese

### ISSUE THREAD

**Issue by robotframework-ride** [robotframework/RIDE#1378]
> *Originally submitted to [Google Code](http://code.google.com/p/robotframework-ride/issues/detail?id=1338) by adw... on 9 Mar 2014*

In RIDE, I can click at a cell once, and then when I type English, the content will go into the cell auotomatically. However, if I click a cell once, and type Chinese, the content will get lost. To input Chinese, I have to click twice, and make a cursor blicking inside a cell, by this time, I can type Chinese in without a problem. This is very annoying, because this will cause some Chinese typing get lost.

**Comment by yanne** [comment]
This is probably a problem with the wxPython toolkit, since we do nothing do prevent the Chinese input being processed. I'll close this as won't fix, since I think this cannot be solved in RIDE.
