### ISSUE TITLE
No word wrapping in RIDE

### ISSUE THREAD

**Issue by robotframework-ride** [robotframework/RIDE#1379]
> *Originally submitted to [Google Code](http://code.google.com/p/robotframework-ride/issues/detail?id=1339) by adw... on 9 Mar 2014*

We edit manual test cases, sometimes I have to write a long sentence, I hope RIDE can support word wrapping and automatic resize the cell, so that I can see the full content

**Comment by robotframework-ride** [comment]
> *Originally submitted to [Google Code](http://code.google.com/p/robotframework-ride/issues/detail?id=1339#c1) by adw... on 14 Mar 2014*


We think we know how to implement this now, we are thinking add a prefernce to RIDE to control whether to turn word wrapping on or off, if we can pull this off, can we get this code mrege in?

**Comment by robotframework-ride** [comment]
> *Originally submitted to [Google Code](http://code.google.com/p/robotframework-ride/issues/detail?id=1339#c2) by @mkorpela on 14 Mar 2014*


Yes - we will be happy to get your contributions!

The source code is in github - just fork your own version of RIDE and do the changes and send a pull request.

There are some guidelines about making the contribution in BUILD file <a href="https://github.com/robotframework/RIDE/blob/master/BUILD.rest" rel="nofollow">https://github.com/robotframework/RIDE/blob/master/BUILD.rest</a>

**Comment by yanne** [comment]
Automatic cell size expanding can be turned on with settings in RIDE 1.4, so closing this.
