### ISSUE TITLE
Editing keyword name will result the text change in test case step when the step contains the same text as keyword.

### ISSUE THREAD

**Issue by robotframework-ride** [robotframework/RIDE#1390]
> _Originally submitted to [Google Code](http://code.google.com/p/robotframework-ride/issues/detail?id=1350) by s... on 21 Apr 2014_

Editing keyword name will result the text change in test case step when the step contains the same text as keyword name.

As you can tell from pic one, i have a keyword "Google Search", and in test case i want to verify the website contains text "Page Should Contain Google Search". Later on i rename the keyword to "Google Name Search", like in pic two, and the test case step is changed to "Page Should Contain Google Name Search", which should not happen.

**Comment by robotframework-ride** [comment]
> *Originally submitted to [Google Code](http://code.google.com/p/robotframework-ride/issues/detail?id=1350#c1) by @mkorpela on 21 Apr 2014*


Do you have a concrete case where this has caused issues?

It is fairly hard to identify what is a keyword and what is just text because Robot framework allows keywords that execute other keywords that have been given as arguments (Run Keyword etc.)

**Comment by robotframework-ride** [comment]
> *Originally submitted to [Google Code](http://code.google.com/p/robotframework-ride/issues/detail?id=1350#c2) by s... on 21 Apr 2014*


The caused issue is just like in the sample test case. When the keyword is used in a lot of test cases, all of them need to verify page contains the non-keyword text. But once the keyword is renamed, the same text is renamed everywhere,include those non-keyword texts, and hence result in the failing verification. Is it possible to detect the previous word of the renamed keyword, and only allow its refracting when the previous word is not a keyword or it is but a special keyword(Run Keyword etc.)?

**Comment by HelioGuilherme66** [comment]
This issue is no longer existing in v2.0.6.

Nine years later is being closed :).
