### ISSUE TITLE
renaming keyword used in "Run Keywords" of setup/teardown totally mess up the setup/teardown "Run Keywords" statement.

### ISSUE THREAD

**Issue by robotframework-ride** [robotframework/RIDE#1391]
> _Originally submitted to [Google Code](http://code.google.com/p/robotframework-ride/issues/detail?id=1351) by s... on 21 Apr 2014_

RIDE 1.3 running on Python 2.7.6. 
Robot Framework 2.8.4 (Python 2.7.6 on win32)

The original test setup is as pic one,it will first execute keyword 'Go To Yahoo' to go to the website, and then execute the keyword "'Yahoo Search RobotFramework' to input 'robotframework' in the search field and click 'search' button.
However, after i renamed the keyword 'Yahoo Search RobotFramework' to 'Search RobotFramework', the statement in test setup became a mess, as pic two.

**Comment by robotframework-ride** [comment]
> *Originally submitted to [Google Code](http://code.google.com/p/robotframework-ride/issues/detail?id=1351#c1) by @yanne on 19 May 2015*


This is a bug in how Run Keyword is handled when keywords are renamed

**Comment by MarkAWalters** [comment]
I was about to log what I think is exactly the same issue, then realised it might already be logged.  I am not seeing any Pic one or Pic two as referred to above, so I have pasted part of what I was logging below:

My guess is that the rename function assumes there is only one keyword in the setup.

EXAMPLE - Before rename:  

`**Run Keywords** | Setup - Do Something | AND | Setup - Do something Else`

EXAMPLE - After renaming "Setup - Do Something" to "Setup - Dont Do Anything", it becomes:

`**Setup - Dont Do Anything** | Setup - Do Something | AND | Setup - Do something Else`

EXAMPLE - Intended result was :

`Run Keywords | **Setup - Dont Do Anything** | AND | Setup - Do something Else`

It would be great if this could be upped in the priority list as I use "Run Keywords" fairly often and consequently have had this problem several time already.

Thanks

**Comment by HelioGuilherme66** [comment]
@MarkAWalters Thank you for reporting (confirming that this bug from 2014 is still valid). Unfortunately, I do not get notifications of comments, so only today I saw you comment. I will investigate about this.

**Comment by HelioGuilherme66** [comment]
This issue is still observable on 1.7.4.1dev0, Windows10, wxPython 4.0.7post2 and Python 2.7.16.
