### ISSUE TITLE
If robot libraries use a lot of memory, repeated test runs eventually fail to allocate memory

### ISSUE THREAD

**Issue by robotframework-ride** [robotframework/RIDE#1396]
> _Originally submitted to [Google Code](http://code.google.com/p/robotframework-ride/issues/detail?id=1356) by guy.kisel on 5 May 2014_

I have a library that caches a lot of test data (up to 80 MB). When I run it 10 or 20 times in RIDE without closing RIDE, eventually RIDE fails to allocate memory with the error below. This is in Ubuntu 12.04 with 2 GB of RAM. This is annoying but easy to work around (by closing and reopening RIDE).

20140505 16:41:05.038 [INFO]: Started RIDE 1.3 using python version 2.7.3 with wx version 2.8.12.1 in linux2.

Stack trace:
[Errno 12] Cannot allocate memoryTraceback (most recent call last):
 File "/home/sdet/.virtualenvs/robot/local/lib/python2.7/site-packages/robotide/contrib/testrunner/testrunnerplugin.py", line 274, in OnRun
   self._test_runner.run_command(command, self._get_current_working_dir())
 File "/home/sdet/.virtualenvs/robot/local/lib/python2.7/site-packages/robotide/contrib/testrunner/testrunner.py", line 172, in run_command
   self._process.run_command(command)
 File "/home/sdet/.virtualenvs/robot/local/lib/python2.7/site-packages/robotide/contrib/testrunner/testrunner.py", line 287, in run_command
   **subprocess_args)
 File "/usr/lib/python2.7/subprocess.py", line 679, in __init__
   errread, errwrite)
 File "/usr/lib/python2.7/subprocess.py", line 1143, in _execute_child
   self.pid = os.fork()
OSError: [Errno 12] Cannot allocate memory

**Comment by robotframework-ride** [comment]
> *Originally submitted to [Google Code](http://code.google.com/p/robotframework-ride/issues/detail?id=1356#c1) by @yanne on 19 May 2015*


Now the only thing to figure out is where the memory leak is ;)

**Comment by HelioGuilherme66** [comment]
Closing this issue, because we have a fail safe for the Message Log panel in Test Runner, which stops logging if memory used by the RIDE process is exceeded by 80% of the initial use. Assuming that it was the original memory leak.
Currently with RIDE v2.0.2.dev1 in Fedora Linux 36, Python 3.10.10, wxPython 4.0.7.
