### ISSUE TITLE
Option to use monospace font in grid

### ISSUE THREAD

**Issue by robotframework-ride** [robotframework/RIDE#1401]
> *Originally submitted to [Google Code](http://code.google.com/p/robotframework-ride/issues/detail?id=1361) by kormbrek on 14 May 2014*

The default font makes it hard to spot things like missing or extra apostrophes when using the extended variable syntax. It is more visible in the Text Edit tab, but for those who primarily edit in the Edit tab, it would be nice to be able to use a monospace font to make spotting typos easier.

As a workaround, I simply changed
wx.FONTFAMILY_DEFAULT -&gt; wx.FONTFAMILY_MODERN
in editor/kweditor.py

and that seems to work well.

**Comment by yanne** [comment]
Fixed in #1456
