### ISSUE TITLE
Crash on startup with bad import file path

### ISSUE THREAD

**Issue by robotframework-ride** [robotframework/RIDE#1410]
> _Originally submitted to [Google Code](http://code.google.com/p/robotframework-ride/issues/detail?id=1370) by mac7... on 18 Jul 2014_

In the tools&gt;preferences&gt;importing menu, if a bad file path is entered in the pythonpath, RIDE will crash on startup and will be unrecoverable until fixing the file path in settings.cfg.

Continually recreate-able in RIDE 1.3 with 32 bit python 2.7.3, on Windows 7.

RIDE should try to find some way of aborting those imports, otherwise it locks up and does not allow you to make any changes, including fixing the import file path.

**Comment by robotframework-ride** [comment]
> *Originally submitted to [Google Code](http://code.google.com/p/robotframework-ride/issues/detail?id=1370#c1) by Raphael.Castaneda on 18 Jul 2014*


For anyone landing on this page looking for a work around, you can modify the RIDE settings file to remove the offending path. On Windows 7, you can find that here:

&#37;APPDATA&#37;\RobotFramework\ride\settings.cfg

**Comment by yanne** [comment]
Can not reproduce, has anyone an example of path that causes this?

**Comment by Nyral** [comment]
@HelioGuilherme66 Invalid\not reproducible.

**Comment by HelioGuilherme66** [comment]
Closed because (use OR operator):
- is too old,
- newest version should have it fixed,
- not reproducible,
- not an issue,
- is a question,
- lacks logs, versions info, e.t.c.,
- there is no other reason that justifies being opened.

(thanks @Nyral for validating)
