### ISSUE TITLE
When saving in the Text Edit screen, all test case checkboxes are cleared

### ISSUE THREAD

**Issue by robotframework-ride** [robotframework/RIDE#1416]
> *Originally submitted to [Google Code](http://code.google.com/p/robotframework-ride/issues/detail?id=1376) by billmat... on 28 Aug 2014*

RIDE unchecks any checked test cases when the file is saved in the Text Edit screen.  This makes it extra work when going between editing and re-running test cases.  It doesn't do this in the grid Edit screen.

I can see the challenge if the edits actually added or removed test cases, especially if it removed a checked test case.  However it would be nice if RIDE could remember which tests are checked, and at the point of saving/re-rendering the treeview, maintain the checks that are still relevant (i.e. the test case still exists by name).

This is with RIDE 1.3 on Windows 2008 <a href="https://code.google.com/p/robotframework-ride/source/detail?r=2">R2</a>.

**Comment by yanne** [comment]
Fixed in #1586
