### ISSUE TITLE
Error-Red highlight in cells even when arguments continue on the next line

### ISSUE THREAD

**Issue by robotframework-ride** [robotframework/RIDE#1418]
> _Originally submitted to [Google Code](http://code.google.com/p/robotframework-ride/issues/detail?id=1378) by edbran... on 2 Oct 2014_

When using the "Set Variable If" keyword with all its arguments on the following lines (as shown in the second example at [1]), the last cell on the first line is improperly colored Red.

[1]: <a href="https://robotframework.googlecode.com/hg/doc/libraries/BuiltIn.html?r=2.6.1#Set" rel="nofollow">https://robotframework.googlecode.com/hg/doc/libraries/BuiltIn.html?r=2.6.1#Set</a> Variable If

Code:

Select Thing by PermID SQL
    [Arguments]    ${permID}=${None}
    [Documentation]    This keyword is here to support "Set Variable Conditionally".
    ${where_clause}=    Set Variable If    # Ignore this red box. \ Value on the next line.
    ...    ${permID}    perm_id = '${permID}'
    ...    ${true}    perm_id is null
    [Return]    ${where_clause}

Observed result: (see attachment)

**Comment by robotframework-ride** [comment]
> *Originally submitted to [Google Code](http://code.google.com/p/robotframework-ride/issues/detail?id=1378#c1) by @yanne on 19 May 2015*


This formatting is anyway lost when suite is saved/restarted, so the impact is probably quite low.

**Comment by Nyral** [comment]
Line continuation is deprecated in latest RF version . There is no point in fixing this.
