### ISSUE TITLE
If same resource file is imported with different cases, it is shown twice in the file tree

### ISSUE THREAD

**Issue by robotframework-ride** [robotframework/RIDE#1421]
> _Originally submitted to [Google Code](http://code.google.com/p/robotframework-ride/issues/detail?id=1381) by minh.ngu... on 15 Oct 2014_

I'm using RIDE 1.3 and it has a problem here.

When I create resources, RIDE will duplicate it (see image)

I don't know how to reproduce this problem.

Thanks.

**Comment by robotframework-ride** [comment]
> *Originally submitted to [Google Code](http://code.google.com/p/robotframework-ride/issues/detail?id=1381#c1) by @yanne on 19 May 2015*


What information exactly is duplicated?

**Comment by robotframework-ride** [comment]
> *Originally submitted to [Google Code](http://code.google.com/p/robotframework-ride/issues/detail?id=1381#c2) by minhnguy... on 19 May 2015*


You can see there are 2 Resources file such as:
- BusinessKeywordsInWindows.txt (one is gray-out)
- CommonKeywordsInWindows.txt (one is gray-out)
...

This issue occurs on all version of Windows!

**Comment by robotframework-ride** [comment]
> *Originally submitted to [Google Code](http://code.google.com/p/robotframework-ride/issues/detail?id=1381#c3) by @yanne on 19 May 2015*


On a further look, this is probably the same issue as #1399. It is caused when you have different cases in imports of the same file, something like:

Resource  |  resources/BusinessKeywords.txt

and 

Resource  |  RESOURCES/BusinessKeywords.txt

In Windows, these two point to the same file, because the file system is case insensitive. This is not handled by RIDE though, so it thinks they are different files.

**Comment by robotframework-ride** [comment]
> *Originally submitted to [Google Code](http://code.google.com/p/robotframework-ride/issues/detail?id=1381#c4) by @yanne on 19 May 2015*


<a class="closed_ref" href="https://code.google.com/p/robotframework-ride/issues/detail?id=1399" title="Resource files displayed twice after restarting RIDE if import statements are not case sensitive"> Issue 1399 </a> has been merged into this issue.

**Comment by HelioGuilherme66** [comment]
Still valid on Windows 10 with RIDE 1.7.4.1dev.
![image](https://user-images.githubusercontent.com/2866630/71607165-f4b32700-2b6e-11ea-9d6a-c769f99ce06b.png)

Possible solution is to uniform cases (all lower, for example) so the paths won't be different.

**Comment by HelioGuilherme66** [comment]
Closed by #2105
