### ISSUE TITLE
replace('\n','') will be updated to replace('\n ','') when saving case by RIDE

### ISSUE THREAD

**Issue by robotframework-ride** [robotframework/RIDE#1427]
> _Originally submitted to [Google Code](http://code.google.com/p/robotframework-ride/issues/detail?id=1387) by ying_zhu... on 11 Nov 2014_

In my test case, there's one text: replace('\n','')

If I write &amp; save this test case using RIDE, this text will be automatically updated to: replace('\n&lt;br&gt;','')
It caused my test points can't be verified.

**Comment by yanne** [comment]
Where in the test case you have this text? Can you attach a sample line before and after writing it with RIDE. I cannot reproduce this.

**Comment by Nyral** [comment]
@HelioGuilherme66 Not reproducible for me.

**Comment by HelioGuilherme66** [comment]
Closing because is too old and we cannot reproduce, or lack of information.
