### ISSUE TITLE
Import of python modules in a package is not working

### ISSUE THREAD

**Issue by robotframework-ride** [robotframework/RIDE#1428]
> *Originally submitted to [Google Code](http://code.google.com/p/robotframework-ride/issues/detail?id=1388) by trustmania1892 on 26 Nov 2014*

Hello,

RIDE has a nice feature, the function catalog (shortcut F5).

This is not working, if you import the library with the python syntax "package.module".

The testcase it self is working without a problem.

So, we have a libraries folder in this folder we have different packages i.e. foo. In the foo package we have a module bar. Before we start RIDE the libraries folder will be added to the PYTHONPATH.

So python can find the package foo and the module bar. The import is in red and the function catalog don't show the library.

Is there the possibility to fix this in the next version?

Best regards,

Sascha

**Comment by yanne** [comment]
I could not reproduce this, i.e. I got a nested module structure recognised by just setting the tope level directory to `PYTHONPATH`.  If you still have this problem, please share the details of your directory structure and the command used to set `PYTHONPATH` and open RIDE
