### ISSUE TITLE
Rename Keyword textfield sometimes gets orphaned and sticks around forever

### ISSUE THREAD

**Issue by robotframework-ride** [robotframework/RIDE#1430]
> _Originally submitted to [Google Code](http://code.google.com/p/robotframework-ride/issues/detail?id=1390) by edbran... on 2 Dec 2014_

Steps to reproduce:
1. Select a keyword.
2. Press F2 to begin Renaming it.
3. Add a character and then remove it again (we just want to dirty the text field)
   4a. A wild dialog box appears!  Click OK.  OR:
   4b. (Windows) Press the Start Menu button on your keyboard, then click on the start menu a couple times.

Expected results:

Either:
1. Changes are not applied and the text field disappears, OR
2. The text field persists, and the rename can be completed normally upon returning focus to RIDE.

Observed results:

The text field is orphaned and remains visible over the tree, even if the tree nodes are collapsed or if you click on the text field and press Enter.  I have not found a way to remove it without restarting RIDE.

The following traceback appears on the console:

Traceback (most recent call last):
  File "c:\Python27\lib\site-packages\wx-2.8-msw-unicode\wx\lib\agw\customtreectrl.py", line 1228, in OnKillFocus
    if not self.AcceptChanges():
  File "c:\Python27\lib\site-packages\wx-2.8-msw-unicode\wx\lib\agw\customtreectrl.py", line 1146, in AcceptChanges
    self._owner.SetItemText(self._itemEdited, value)
  File "c:\Python27\lib\site-packages\wx-2.8-msw-unicode\wx_core.py", line 14619, in __getattr__
    raise PyDeadObjectError(self.attrStr &#37; self._name)
wx._core.PyDeadObjectError: The C++ part of the TreeTextCtrl object has been deleted, attribute access no longer allowed.

**Comment by robotframework-ride** [comment]
> *Originally submitted to [Google Code](http://code.google.com/p/robotframework-ride/issues/detail?id=1390#c1) by @yanne on 18 May 2015*


Hmm, I run Windows/Linux Mint in VirtualBoX in OSX and cannot reproduce this in either env. I don't have the start menu key mapped, but if that's the only way to reproduce this, I consider this quite a minor bug.

**Comment by kubilaykarpat** [comment]
I also experience this issue quite often

**Comment by edbrannin** [comment]
I experienced this yesterday without using the start-menu key, but I don't remember exactly how (I think I did hit `^C` to copy something).  I'll try to retrace my steps better the next time it happens.

**Comment by Nyral** [comment]
![2019-05-19_20-20-38](https://user-images.githubusercontent.com/39315668/58292878-ccd73600-7dcb-11e9-9fbb-130f209d121d.gif)

Here's an example with it occurring. This issue is much more apparent on RIDE with python 3.
It seems that when textfield is visible you can somehow select the label behind it. Or the event does not exit properly. It's a very tricky bug.
Currently it has only been possible to reproduce on Windows.

**Comment by Nyral** [comment]
[This is a wx bug.](https://github.com/wxWidgets/Phoenix/issues/1235)

It will be fixed starting `wxPython==4.1.0`

**Comment by jnhyperion** [comment]
it has been fix by wxPython.
