### ISSUE TITLE
init file is not initialized at startup if there is no suite within the directory

### ISSUE THREAD

**Issue by robotframework-ride** [robotframework/RIDE#1432]
> *Originally submitted to [Google Code](http://code.google.com/p/robotframework-ride/issues/detail?id=1392) by mr on 6 Jan 2015*

- There is a directory without a suite inside
- I write documentation for the directory
- The documentation is persisted and showed by RIDE
- I restart RIDE
- The documentation for the directory is not showed anymore
:-(

**Comment by robotframework-ride** [comment]
> *Originally submitted to [Google Code](http://code.google.com/p/robotframework-ride/issues/detail?id=1392#c1) by mr on 6 Jan 2015*


Additionally if there is a directory with an init file and without a suite inside the directory, and when you change the format, than the init file will be removed.

**Comment by robotframework-ride** [comment]
> *Originally submitted to [Google Code](http://code.google.com/p/robotframework-ride/issues/detail?id=1392#c2) by @yanne on 18 May 2015*


This is most likely due to the fact that these directories are not `valid` from RF point of view; they contain no executable test cases.

Should take a look whether these are already discarded during parsing.

**Comment by yanne** [comment]
The init files for directories that contain no test case files are discarded by RF parsing modules. Unless we re-write the whole data loading mechanism, this is too difficult to fix compared to the benefit.

**Comment by joris255** [comment]
I wanted to add that RF DOES see the files, RIDE does not display them. Maybe it was different in June. I currently run RobotFramework 2.8.6 and RIDE 1.5. 

I really regret that this is not possible. Tagging folders has been found really useful, but sometimes there is no sense to run any test at this level. The fact that RIDE does not see the files makes the tag filtering obsolete in this case. Could this be reopened?

**Comment by HelioGuilherme66** [comment]
Interesting, I don't see joris255 message in github, but here it goes.

First, you are using a very old RF version, maybe RIDE 1.5 is not the best
version for it.

How about creating a test suite for those folders with a test case like,
BuiltIn.No Operation ?

**Comment by joris255** [comment]
HelioGuilherme66,
I deleted my message because I realized my errors. __init__.robot files ARE visible in RIDE if there is a sub-folder containing a test. I did not realize the init file was visible when clicking on the folder. 

I agree with your solution, a No Operation keyword is a suitable work around, or even a BuiltIn.Comment, in the case where there is no subfolder containing a test.
