### ISSUE TITLE
Argument file options are not reflected (--outputdir)

### ISSUE THREAD

**Issue by robotframework-ride** [robotframework/RIDE#1433]
> *Originally submitted to [Google Code](http://code.google.com/p/robotframework-ride/issues/detail?id=1393) by swarup.rohit on 8 Jan 2015*

When we create an argument file having key-value pairs of arguments and values and pass it in RIDE Arguments field then it picks all but --outputdir argument. 

But when we explicitly mention --outputdir directly under Arguments field then it correctly reflects the change. Refer the screenshot and sample argument file.

**Comment by yanne** [comment]
Testrunnerplugin only check the custom argument strings for the presence of `--outputdir` option. One way to fix this would be processing `--argumentfile` option and checking whether output dir is defined in arg file. This can get hairy, because in theory, the argument files may be chained.

**Comment by yanne** [comment]
This is a duplicate of #1134
