### ISSUE TITLE
Keyboard shortcuts don't work in text editors and the tree in OSX

### ISSUE THREAD

**Issue by robotframework-ride** [robotframework/RIDE#1441]
> _Originally submitted to [Google Code](http://code.google.com/p/robotframework-ride/issues/detail?id=1401) by ah... on 10 Apr 2015_

When i am on the run tab, then focus the arguments field, there is no paste option. I cannot past with the keyboard shortcut either.

**Comment by robotframework-ride** [comment]
> *Originally submitted to [Google Code](http://code.google.com/p/robotframework-ride/issues/detail?id=1401#c1) by aidan.ma... on 14 Apr 2015*


I cannot replicate this issue; pasting into the 'Arguments:' field works for me. Maybe provide some system information? 

I have a Windows 7 machine with RIDE 1.3 running on Python 2.7.9.

**Comment by robotframework-ride** [comment]
> *Originally submitted to [Google Code](http://code.google.com/p/robotframework-ride/issues/detail?id=1401#c3) by @yanne on 12 May 2015*


Seems to be OSX only issue.

**Comment by yanne** [comment]
This seems to be a part of larger problem with keyboard shortcuts in OSX. It seems that most of the text controls are not responding to standard editing shortcuts.

**Comment by yanne** [comment]
I'll change the title of this issue to reflect the larger problem, and close other individual issues related to this.

**Comment by jnhyperion** [comment]
fixed with this PR: https://github.com/robotframework/RIDE/pull/2216
