### ISSUE TITLE
RIDE 1.3 couldn't import library spec xml on Mac

### ISSUE THREAD

**Issue by robotframework-ride** [robotframework/RIDE#1443]
> *Originally submitted to [Google Code](http://code.google.com/p/robotframework-ride/issues/detail?id=1403) by qit... on 22 Apr 2015*

When I import library spec xml, I can't click the xml file. It is gray.
I have to copy it to the /User/myusername/.robotframework/RIDE/library_xmls 
then restart RIDE, import Library, it works.

Mac osx 10.10.3
RIDE 1.3

**Comment by robotframework-ride** [comment]
> *Originally submitted to [Google Code](http://code.google.com/p/robotframework-ride/issues/detail?id=1403#c1) by qit... on 22 Apr 2015*


I changed the specimporter.py to fix this issue.
before:
wildcard = ('Library Spec XML | *.xml')
change to:
wildcard = ('*.xml')
Then I can import xml on Mac osx.

**Comment by yanne** [comment]
It seems that the actual problem is the space between `|` and `*.xml`

**Comment by yanne** [comment]
Fixed in #1457
