### ISSUE TITLE
Go Back Keybinding Causing Segmentation Fault

### ISSUE THREAD

**Issue by robotframework-ride** [robotframework/RIDE#1444]
> *Originally submitted to [Google Code](http://code.google.com/p/robotframework-ride/issues/detail?id=1404) by derek.robati on 4 May 2015*

Reproducible in my environment.

Steps:
Open Ride.
Navigate views.
Edit a view. (I used Ctrl+D to delete a line.)
Go back a view using (Alt+Z).

This was an issue on Lubuntu 14.04.

**Comment by robotframework-ride** [comment]
> *Originally submitted to [Google Code](http://code.google.com/p/robotframework-ride/issues/detail?id=1404#c1) by derek.robati on 4 May 2015*


RIDE 1.3 on Python 2.7.6

**Comment by robotframework-ride** [comment]
> *Originally submitted to [Google Code](http://code.google.com/p/robotframework-ride/issues/detail?id=1404#c2) by @yanne on 12 May 2015*


Can you paste the whole error output from the console?

I can't reproduce this in my Linux Mint box.

**Comment by robotframework-ride** [comment]
> *Originally submitted to [Google Code](http://code.google.com/p/robotframework-ride/issues/detail?id=1404#c3) by @yanne on 2 Jun 2015*


Closing due to lack of information

**Comment by MisterChild** [comment]
Hi...
I can see the same behaviour with RIDE 1.5.2.1  (RFW 2.9.2, wxPython 2.8.12.1, Python 2.7.6, virtualenv 13.1.0).
What kind of information could I provide for a better reproducing?

Message:
$ ride.py
[Errno 1] Operation not permitted: '/tmp/e01da850-6e56-4466-b2cd-945a61c6b0b6-ride.log'[Errno 1] Operation not permitted: '/tmp/4d80bd85-e43e-466a-82a5-ba8af210508d-ride.log'[Errno 1] Operation not permitted: '/tmp/7db33848-66ec-4fa8-9700-96f4e737d6dd-ride.log'Segmentation fault (core dumped)

Thanks and regards,
MisterChild

By the way, I think I'm working for the same company like the thread opener. :-) Maybe it's a problem with some internal packages.
