### ISSUE TITLE
Support RF 2.9

### ISSUE THREAD

**Issue by robotframework-ride** [robotframework/RIDE#1445]
> *Originally submitted to [Google Code](http://code.google.com/p/robotframework-ride/issues/detail?id=1405) by @yanne on 19 May 2015*

Robot Framework 2.9 is in alpha2, and we need start working on a compatible RIDE version ASAP

**Comment by yanne** [comment]
This means at least following changes need to be implemented:

- [ ] Support dictionary variables
  - [ ] Read, edit, create and save dict variables
  - [ ] Validate dict variable values 
  - [ ] Recognise dict variables used as arguments to keywords
  - [ ] Add dict variables to auto completion suggestions
  - [ ] Add dict variable support to user keyword arguments
- [ ] Support keywords tags
- [ ] Adapt to API changes, and specifically
  - [ ] Check whether one namespace for all variables affect auto completion

**Comment by pekkaklarck** [comment]
RF 2.9 is likely to include also new for loop flavors `FOR ... IN ZIP` (robotframework/robotframework#1952) and `FOR ... IN ENUMERATE` (robotframework/robotframework#1954). PR robotframework/robotframework#1989 implementing both looks pretty good and there ought to be enough time to get that into RF 2.9, perhaps even to alpha 3.

**Comment by yanne** [comment]
I am using the branch https://github.com/robotframework/RIDE/tree/RF2.9-compatibilty for implementing these changes, and will update the list whenever somethings ready in that branch. Be warned, that this is a development branch, and I may use `push --force` when necessary.

**Comment by yanne** [comment]
Just updated the development branch (with a force push) to RF 2.9rc1. 

It seems that the new For loop flavours do not need special treatment in RIDE.

**Comment by yanne** [comment]
We are now compatible with the new features and API changes of RF 2.9rc1. I think I'll do the merge only after the official RF release, though.
