### ISSUE TITLE
(Visual) Editor columns auto-resize

### ISSUE THREAD

**Issue by VipSaran** [robotframework/RIDE#1449]
Currently (RIDE v1.3, Windows 32-bit on Windows 7 64-bit) the columns have fixed width which makes reading some longer values hard.

It would be usable to have (a preference contolled switch for) automatic resizing of Editor column widths based on widest/longest contents.

**Comment by yanne** [comment]
Should there still be a max width for the columns? Or is it the responsibility of the user to have "reasonable" content when using this switch?

**Comment by VipSaran** [comment]
Configurable max width (with sensible default) should help this auto-resize feature doesn't get into the other side of usefulness.

So, do you think something like this would be feasible:
+ Auto-resize column widths
  + Don't auto-resize over [200] px

**Comment by yanne** [comment]
Fixed in #1456

**Comment by VipSaran** [comment]
:+1:

**Comment by yanne** [comment]
@VipSaran Are you able to test the master version to see if the auto width works reasonably? It had some performance issues, which I was hopefully able to fix.

**Comment by VipSaran** [comment]
@yanne Unfortunately, I'm on vacation and will be able to verify it only after June 15th.
Plus, I don't have a build environment set up...

**Comment by VipSaran** [comment]
Tried 1.4b3 and the enhancement works fine so far.

**Comment by VipSaran** [comment]
An issue (in keywords):
![2015-06-17_132008](https://cloud.githubusercontent.com/assets/995948/8205796/111e96a4-14f4-11e5-9d7c-00f3f579d3ea.png)

Default: 100
Auto: true
Max: 300
