### ISSUE TITLE
Remebering the customized (visual) Editor column widths

### ISSUE THREAD

**Issue by VipSaran** [robotframework/RIDE#1450]
Currently (RIDE v1.3, Windows 32-bit on Windows 7 64-bit) when columns widths are resized, leaving the current view forgets those customizations.

It would be usable for Editor to remember the customized column widths (per view) for the current session.

**Comment by yanne** [comment]
This is a duplicate of #1361

**Comment by VipSaran** [comment]
This doesn't seem to work (i.e. columns manually resized are not remembered), regardless if Auto size columns is off or on.

**Comment by yanne** [comment]
Yes, it is not implemented yet. I just closed this, because the issue already existed as #1361. We'll try to have only one open issue per a feature request :)

**Comment by VipSaran** [comment]
:+1: 
It's clear, sorry. Dunno how I missed the "duplicate" comment...
