### ISSUE TITLE
Windows (Vista+) taskbar icon links don't work

### ISSUE THREAD

**Issue by VipSaran** [robotframework/RIDE#1452]
Currently (RIDE v1.3, Windows 32-bit on Windows 7 64-bit) the icon properly displays a history of last opened test suits (see the attached screenshot), but clicking on the links does nothing.

Expected behaviour would be that clicking on a link opens new RIDE instance with the corresponding suite loaded.
If the link does not point to an existing file anymore, the new RIDE instance should still be opened, but with an appropriate error message.

**Comment by yanne** [comment]
I cannot see the screenshot.

**Comment by VipSaran** [comment]
Sorry, forgot it. Here you go:
![taskbar](https://cloud.githubusercontent.com/assets/995948/7962566/518c553c-0a0e-11e5-969a-f8f1d9ce4785.png)

**Comment by jnhyperion** [comment]
I don't think we should support this feature.
