### ISSUE TITLE
When the IDE startup in windows,will it don't also open the dos window?

### ISSUE THREAD

**Issue by yanne** [robotframework/RIDE#146]
> *Originally submitted to [Google Code](http://code.google.com/p/robotframework-ride/issues/detail?id=111) by rover.zh... on 26 Feb 2009*

When start up the IDE,will it only open the software and don't open the
dos-style window?

**Comment by yanne** [comment]
> *Originally submitted to [Google Code](http://code.google.com/p/robotframework-ride/issues/detail?id=111#c1) by @yanne on 13 Mar 2009*


The DOS window is opened by Windows OS itself, we can't do much to it unless we
change the way ride is started, and that's not going to happen soon.

**Comment by yanne** [comment]
> *Originally submitted to [Google Code](http://code.google.com/p/robotframework-ride/issues/detail?id=111#c2) by @pekkaklarck on 13 Mar 2009*


There's actually pythonw.exe that can be used to start Python apps without opening a
console window. I haven't tried that myself (and I currently only have Mac available
where RIDE doesn't work) but if it works, that could be documented somewhere.

**Comment by yanne** [comment]
> *Originally submitted to [Google Code](http://code.google.com/p/robotframework-ride/issues/detail?id=111#c3) by dietrich... on 13 Oct 2011*


It is quite simple, copy ride.py in Python/cripts to ride.pyw. That file is automatically executed by pythonw.exe without a console window.

**Comment by cmorty** [comment]
@yanne What about providing a `ridew.pyw` for windows? That would avoid having to adjust the system. Especially as running `pythonw -m rideide` does not work.

**Comment by HelioGuilherme66** [comment]
@cmorty You commented in a Closed issue from 2015!!!
Newer versions of RIDE can create a desktop shortcut for you.
This is the command of my current 1.7.4b1dev1 version:
```
"C:\Program Files\Python37\pythonw.exe"  -c "from robotide import main; main()"
```
