### ISSUE TITLE
Alert before run when user didn't check any test case could run all test cases.

### ISSUE THREAD

**Issue by synsun** [robotframework/RIDE#1463]
I got many test suites and cases in my ride environment.
Sometimes, I forgot check test case to run only some cases.
Then my first test case of my registered start to run. I don't want to be like this.

I thought 2 ways to resolve this problem.
First, pop-up alert message to choose run all or not.
Second, do sleep 5 seconds with alert message.
Or is there any better idea to solve this problem?

**Comment by yanne** [comment]
I don't like the idea of adding additional steps to the workflow just to prevent user errors. There could be a list of test cases that are selected for the execution, which is shown before the execution starts. Then you could double check that correct tests are about to be run.

**Comment by MoonSungHoon** [comment]
Yes, you right. Additional steps are not required. But sometimes people do mistake that they don't want.
Then how about just print a message to notify that "All test cases will be run".?

**Comment by HelioGuilherme66** [comment]
Implemented since 1.7.3
