### ISSUE TITLE
RIDE 1.4 beta 2 on MacOS 10.10.3

### ISSUE THREAD

**Issue by michel117** [robotframework/RIDE#1464]
Test execution on MacOS 10.10.3 is successful. Although I get this error Window after execution:

Robot Framework installation not found.
To run tets, you need to install Robot Framework separately.
See http://robotframework.org for installation instructions.

**Comment by yanne** [comment]
True, this seems to be an issue with the fix implemented for #1317. I'll reopen the original issue
