### ISSUE TITLE
iCCP: known incorrect sRGB profile

### ISSUE THREAD

**Issue by Twoflower2** [robotframework/RIDE#1469]
"iCCP: known incorrect sRGB profile" error in openSuse KDE 4.14.9 with plasma 5 using RIDE = 1.4b3 or 1.3

**Comment by yanne** [comment]
Is this fatal, i.e. does it prevent RIDE from starting at all?

**Comment by yanne** [comment]
Fixed in ad48e3be6eb97b1ae4b8ee01537770bbe6c07e77
