### ISSUE TITLE
Search Keywords 'Find Usages' does not find all usages

### ISSUE THREAD

**Issue by robotride** [robotframework/RIDE#1470]
Framework version: 2.8.7
Python: 2.7
Operating system: Windows 7 Enterprise
Using RIDE 1.3 (although I saw this issue on 1.4b3 as well)

The RIDE keyword completion is obviously powerful. Say my keyword is:
CreateSchedulerAddParameter

RIDE will recognize all of the following as the above keyword:
    Create Scheduler Add Parameter
    CreateSchedulerAddParameter
    create scheduler add parameter
    createscheduleraddparameter
    create scheduleraddparameter
    create scheduler addparameter
    create scheduler add parameter
    createscheduleradd parameter
    createscheduleradd_parameter
    Create_SchedulerAddParameter
    Create_Scheduler_Add_Parameter

Yet, when I use the 'Find Usages' button, the only usage which is returned is the last one (Create_Scheduler_Add_Parameter). It would be great if the 'Find Usages' was just as powerful as the keyword completion. 

Because of this issue, we can just about not even use the 'Find Usages' functionality.

Another example. Say my keyword is:
Add_Import_Export_Runtime_Parameters

RIDE will recognize all of the following as the above keyword:
    Add_Import_Export_Runtime_Parameters
    Add Import Export Runtime Parameters
    add_import export runtime parameters

Yet, when I use the "Find Usages' button, the only usage which is returned is the first one (Add_Import_Export_Runtime_Parameters)

Thx.

**Comment by yanne** [comment]
Thanks for the report, I'll look into it in more detail soon.
