### ISSUE TITLE
Keyword mouseover tooltip is mouseoverthrough-y

### ISSUE THREAD

**Issue by VipSaran** [robotframework/RIDE#1472]
After pressing CTRL and mousing over a keyword, a tooltip for that KW appears (as expected).
But, after (still holding CTRL) you wanted to click on the tooltip (to have it in a separate window) it changes content based on keywords _underneath it_, hence it's "mouseoverthrough-y" :)

Check the video:
https://vid.me/r03N

Expected behavior would be that mouse cursor is _above_ the tooltip or effectively that the tooltip is not mouseoverthrough-y :)

**Comment by jnhyperion** [comment]
cannot reproduce in latest version.
