### ISSUE TITLE
Column numbers get updated in all List variables in a resource file when updating only one

### ISSUE THREAD

**Issue by Lanbaster** [robotframework/RIDE#1475]
I have three different list variables in my resource file:
![image](https://cloud.githubusercontent.com/assets/8429447/8332172/34a77892-1a95-11e5-8ea6-7661ce717af4.png)

When I try to update the number of columns in one:
![image](https://cloud.githubusercontent.com/assets/8429447/8332215/71d81294-1a95-11e5-97ac-7e008a8c8976.png)

It gets updated in all of them:
![image](https://cloud.githubusercontent.com/assets/8429447/8332255/9cb02d4e-1a95-11e5-806d-a6ff1692601d.png)

**Comment by yanne** [comment]
It is intentionally implemented this way, i.e. it is a global setting that applies to all list variable dialogs. It would require some additional work to track this setting by individual variables.

**Comment by yanne** [comment]
I think it would be more useful to fix this by redesigning the editor, so barring outside help, this won't get fixed.
