### ISSUE TITLE
Windows installer problem with "robotframework-ride-1.4.win-amd64.exe"

### ISSUE THREAD

**Issue by rajavesw** [robotframework/RIDE#1477]
While installing with the MSI installer named "robotframework-ride-1.4.win-amd64.exe" on Windows 7 with Python 27, it says "no Python installation found in registry" even though I already have python installed in my machine.

**Comment by yanne** [comment]
How have you installed Python? I suspect some kind of installation failure, since this has not been reported elsewhere.

**Comment by rajavesw** [comment]
Hello, I have installed Python using the installer exe in the following sequence.
wxPython2.8-win32-unicode-2.8.12.1-py27.exe
python-3.4.3.msi
ActivePython-2.7.0.2-win32-x86.msi
Followed by : robotframework-2.8.1.win32.exe & then robotframework-ride-1.2.3.win32.exe.
From here I tried to upgrade to the RIDE 1.4.
Thanks for your help and time.

**Comment by yanne** [comment]
You need to remove Python 3 installation, I think. RF and RIDE are only compatible with Python 2.6 and 2.7
