### ISSUE TITLE
Can not run robotframework-ride properly

### ISSUE THREAD

**Issue by yuzhangoscar** [robotframework/RIDE#1488]
I have installed robotframework-ride on two PCs of mine. Everything works fine on one PC but could not have RIDE running on other PC.

I have the following installed on both PCs 
- Python 2.7.8 on win32 
- Robot framework 2.8.6
- wxPython 2.8.12.1
- robotframeowkr-ride-1.4.1b1

When I tried to execute "python ride.py" on the second PC, I got a message:

too many values to unpack
Something more interesting is, if I uninstall robot framework from the second PC, I could execute "python ride.py" but of course there is no point doing this.

Anyone can help me out here?

**Comment by yanne** [comment]
Is there really no other output in the command prompt?

Does the RIDE window open at all?

**Comment by yuzhangoscar** [comment]
Hi yanne, 

No, RIDE window does not open at all. It only opens after I pip uninstall robot. After I pip uninstalled robot, RIDE window would appear after I executed ride.py or python ride.py, but I could not execute any test as it requires pybot to run a test.

**Comment by yuzhangoscar** [comment]
The whole message I got is:

Too many values to unpack

User --help to get usage information.

**Comment by yanne** [comment]
Can you verify that you are really running 1.4.1b1.

Open command prompt, then
```
Z:\RIDE>python
Python 2.7.9 (default, Dec 10 2014, 12:28:03) [MSC v.1500 64 bit (AMD64)] on win
32
Type "help", "copyright", "credits" or "license" for more information.
>>> from robotide import version
>>> version.VERSION
'1.4.1b1'
>>>
```

I am asking this because that version should print the whole stack trace if something breaks on startup.

**Comment by yuzhangoscar** [comment]
I got:
>>>version.VERSION
'1.4'

**Comment by yanne** [comment]
That means you don't have 1.4.1b1 installed. Try running:
`pip install -U robotframework-ride==1.4.1b1`

**Comment by yuzhangoscar** [comment]
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\robotide\__init__.py", line 74, in main
    _run(inpath, not noupdatecheck, debug_console)
  File "C:\Python27\lib\site-packages\robotide\__init__.py", line 100, in _run
    ride = RIDE(inpath, updatecheck)
  File "C:\Python27\lib\site-packages\robotide\application\application.py", line
 41, in __init__
    wx.App.__init__(self, redirect=False)
  File "C:\Python27\lib\site-packages\wx-2.8-msw-unicode\wx\_core.py", line 7981
, in __init__
    self._BootstrapApp()
  File "C:\Python27\lib\site-packages\wx-2.8-msw-unicode\wx\_core.py", line 7555
, in _BootstrapApp
    return _core_.PyApp__BootstrapApp(*args, **kwargs)
  File "C:\Python27\lib\site-packages\robotide\application\application.py", line
 49, in OnInit
    self.namespace = Namespace(self.settings)
  File "C:\Python27\lib\site-packages\robotide\namespace\namespace.py", line 41,
 in __init__
    self._set_pythonpath()
  File "C:\Python27\lib\site-packages\robotide\namespace\namespace.py", line 62,
 in _set_pythonpath
    self._settings.get('installed robot version', None))
  File "C:\Python27\lib\site-packages\robotide\namespace\robotlibraryloader.py",
 line 35, in find_installed_robot_libraries
    rf_file, rf_version = output.strip().split(', ')
ValueError: too many values to unpack


Use --help to get usage information.

**Comment by yuzhangoscar** [comment]
Thanks, I re-installed robotframework-ride 1.4.1b. 

I am sorry I did not realize I was using 1.4. Now I got a full screen of tracetrack.

**Comment by yanne** [comment]
Okay, can you do one more thing for me:

Edit the file C:\Python27\lib\site-packages\robotide\namespace\robotlibraryloader.py, put `print output` in the line 34, just before the erroring line, and try starting again. Thanks!

**Comment by yuzhangoscar** [comment]
Traceback (most recent call last):
  File "<string>", line 1, in <module>
AttributeError: 'module' object has no attribute '__version__'

Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\robotide\__init__.py", line 74, in main
    _run(inpath, not noupdatecheck, debug_console)
  File "C:\Python27\lib\site-packages\robotide\__init__.py", line 100, in _run
    ride = RIDE(inpath, updatecheck)
  File "C:\Python27\lib\site-packages\robotide\application\application.py", lin
 41, in __init__
    wx.App.__init__(self, redirect=False)
  File "C:\Python27\lib\site-packages\wx-2.8-msw-unicode\wx\_core.py", line 798
, in __init__
    self._BootstrapApp()
  File "C:\Python27\lib\site-packages\wx-2.8-msw-unicode\wx\_core.py", line 755
, in _BootstrapApp
    return _core_.PyApp__BootstrapApp(*args, **kwargs)
  File "C:\Python27\lib\site-packages\robotide\application\application.py", lin
 49, in OnInit
    self.namespace = Namespace(self.settings)
  File "C:\Python27\lib\site-packages\robotide\namespace\namespace.py", line 41
 in __init__
    self._set_pythonpath()
  File "C:\Python27\lib\site-packages\robotide\namespace\namespace.py", line 62
 in _set_pythonpath
    self._settings.get('installed robot version', None))
  File "C:\Python27\lib\site-packages\robotide\namespace\robotlibraryloader.py"
 line 36, in find_installed_robot_libraries
    rf_file, rf_version = output.strip().split(', ')
ValueError: too many values to unpack


Use --help to get usage information.

**Comment by yuzhangoscar** [comment]
What I did was:
33: robot_found = 'ImportError' not in output
34: print output
35: if robot_found:

**Comment by yuzhangoscar** [comment]
I am going to bed, my base is in New Zealand. But I will get back tomorrow morning, first thing tomorrow morning. 

Thank you very much for your help.

**Comment by yanne** [comment]
What do you get if run in Python prompt

```

Z:\RIDE>python
Python 2.7.9 (default, Dec 10 2014, 12:28:03) [MSC v.1500 64 bit (AMD64)] on win
32
Type "help", "copyright", "credits" or "license" for more information.
>>> import robot
>>> print robot.__file__
C:\Python27\lib\site-packages\robot\__init__.pyc
>>> print robot.__version__
2.9rc1
```

**Comment by yuzhangoscar** [comment]
I got:
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: 'module' object has no attribute '__version__'

But if I pip uninstall robot, I got:
Uninstalling robot-20071211:
  c:\python27\lib\site-packages\robot-20071211.dist-info\description.rst
  c:\python27\lib\site-packages\robot-20071211.dist-info\metadata
  c:\python27\lib\site-packages\robot-20071211.dist-info\metadata.json
  c:\python27\lib\site-packages\robot-20071211.dist-info\record
  c:\python27\lib\site-packages\robot-20071211.dist-info\top_level.txt
  c:\python27\lib\site-packages\robot-20071211.dist-info\wheel
  c:\python27\lib\site-packages\robot\__init__.py
  c:\python27\lib\site-packages\robot\__init__.pyc
  c:\python27\lib\site-packages\robot\models.py
  c:\python27\lib\site-packages\robot\models.pyc
  c:\python27\lib\site-packages\robot\settings.py
  c:\python27\lib\site-packages\robot\settings.pyc
  c:\python27\lib\site-packages\robot\urls.py
  c:\python27\lib\site-packages\robot\urls.pyc
  c:\python27\lib\site-packages\robot\views.py
  c:\python27\lib\site-packages\robot\views.pyc
  c:\python27\robot\templates\robot\base.html
  c:\python27\robot\templates\robot\login.html
  c:\python27\robot\templates\robot\notify.txt
  c:\python27\robot\templates\robot\request.txt
  c:\python27\robot\templates\robot\request_list.html
  c:\python27\robot\templates\robot\request_new.html
  c:\python27\robot\templates\robot\request_view.html
Proceed (y/n)? y
  Successfully uninstalled robot-20071211


And if I do pip install robot, I got:

C:\Python27\Lib>pip install robot
Collecting robot
C:\Python27\lib\site-packages\pip\_vendor\requests\packages\urllib3\util\ssl_.py
:90: InsecurePlatformWarning: A true SSLContext object is not available. This pr
events urllib3 from configuring SSL appropriately and may cause certain SSL conn
ections to fail. For more information, see https://urllib3.readthedocs.org/en/la
test/security.html#insecureplatformwarning.
  InsecurePlatformWarning
Installing collected packages: robot
Successfully installed robot-20071211

**Comment by yanne** [comment]
Ah, but that's not Robot Framework package at all. Robot Framework is installed by:
`pip install robotframework'

**Comment by yuzhangoscar** [comment]
I am so sorry for my stupid mistake, I tried pip install robotframework, and everything is working now. 

I apologize for my silly mistake.

**Comment by yanne** [comment]
No problem, glad that you got it working.
