### ISSUE TITLE
How do I fix error “Invalid locator strategy: css selector”

### ISSUE THREAD

**Issue by FGagneau** [robotframework/RIDE#1490]
I'm new to robotframework, I have just installed Python 2.7.9, wxpython2.8.1 unicode and ride 1.3 then appiumlibrary. When I run a test with the KeyWord "Click Element":

Click Element  id=fr.axa.soon.qa:id/subscription

I get an error message :

    WebDriverException: Message: Invalid locator strategy: css selector

I know it's not a css selector, but I'm on a native app and I don't understand why this isn't a AppiumDriver.

How do I fix this ?

**Comment by HelioGuilherme66** [comment]
I think that is a bug from Selenium 2.46.1 (see
https://github.com/SeleniumHQ/selenium/issues/842).

You may try to downgrade Selenium with:
pip install --upgrade selenium==2.46.0

Please subscribe to robotframework-users @ groups.google.com for questions,
this is for Issues tracking.

**Comment by FGagneau** [comment]
thank's a lot, problem solved. I suspected there was a problem with Selenium, but I couldn't see where.
