### ISSUE TITLE
For Loop does not error on blank line in loop body

### ISSUE THREAD

**Issue by AndrewNewell2** [robotframework/RIDE#1493]
If a blank line is left inside a 'FOR loop' body, a "Keyword Cannot Be Empty" error was previously thrown but in the new RIDE 1.41.b1 the script executes up to the blank line and then returns to the top of the loop for the next iteration. 

RIDE 1.41.b1, Python 2.7.6, Xubuntu 14.04

**Comment by yanne** [comment]
If you run the tests without RIDE, using `pybot`, what is the result then?

**Comment by AndrewNewell2** [comment]
Hi Janne,

The result is the same using Pybot as it is running tests with RIDE.

**Comment by yanne** [comment]
Then the change is actually in Robot Framework. RIDE run plugin uses whatever version of RF you have installed, and since you are describing runtime behaviour, I think this has nothing to do with RIDE itself. (This would be a RIDE bug if for some reason the empty FOR loop would be saved differently, but I don't think that's the case/)

**Comment by pekkaklarck** [comment]
I doubt there has been changes to how Robot handles empty rows, but obviously anything is possible. It could also be that RIDE has earlier written `\` or even `${EMPTY}` in this particular case and is not doing it anymore. Regardless what has caused the change, I would say ignoring empty lines is much better than complaining about them.

**Comment by AndrewNewell2** [comment]
Hi Pekka, it is not simply a case of ignoring blank lines.  It is stopping the loop script execution at that point and starting the next iteration from the loop entry point.  Any code below the blank line is not executed.

**Comment by pekkaklarck** [comment]
That sounds really strange. Please share a simple example that we can analyze or even run/edit on our system.

**Comment by AndrewNewell2** [comment]
The usual behaviour in RIDE is that any blank lines in a script are deleted on clicking the ‘Save’ buttonb but this does not appear to happen when the blank line is within a loop structure. If the loop script is extensive the blank line can be overlooked.

I would have expected the failure to occur at the first occurrence of the blank line (${EMPTY}) but the loop continues to iterate through the range before failing with “Keyword name cannot be empty”

If this is normal behaviour in that it starts the next iteration on arriving at a blank line then there needs to be a change in behaviour of the Save action so that blank lines in loops are also removed.


[cid:image001.png@01D0D437.C8805DD0]

Loop Fail
    : FOR    ${index}    IN RANGE    0    5
    \    Log    ${index}    INFO
    \    Log    This will be logged    INFO
    \    Log    So will this    INFO
    ${EMPTY}
    \    Log    But this won't    INFO


Output
Starting test: Ptus.Robotframework.ManualSupport.Test.Loop Fail
20150811 13:06:14.924 :  INFO : 0
20150811 13:06:14.931 :  INFO : This will be logged
20150811 13:06:14.936 :  INFO : So will this
20150811 13:06:14.941 :  INFO : 1
20150811 13:06:14.946 :  INFO : This will be logged
20150811 13:06:14.952 :  INFO : So will this
20150811 13:06:14.958 :  INFO : 2
20150811 13:06:14.963 :  INFO : This will be logged
20150811 13:06:14.967 :  INFO : So will this
20150811 13:06:14.973 :  INFO : 3
20150811 13:06:14.978 :  INFO : This will be logged
20150811 13:06:14.983 :  INFO : So will this
20150811 13:06:14.988 :  INFO : 4
20150811 13:06:14.995 :  INFO : This will be logged
20150811 13:06:15.000 :  INFO : So will this
20150811 13:06:15.003 :  FAIL : Keyword name cannot be empty.
Ending test:   Ptus.Robotframework.ManualSupport.Test.Loop Fail

**Comment by yanne** [comment]
This works exactly as it should.

As long as the first cell in a row is escaped, that row belongs to the `:FOR` loop body.

In your example the row containing `${EMPTY}` terminates the `:FOR` loop, and `${EMPTY}` is not part of the loop. This explains the runtime behaviour you get.
