### ISSUE TITLE
Need RIDE installer for windows 32 bit version

### ISSUE THREAD

**Issue by jbkrishna** [robotframework/RIDE#1494]
Hi
I am seeing only 64 bit installer for RIDE "robotframework-ride-1.4.win-amd64.exe". I have windows 32 bit. Can you get 32 bit installer pointer?
Thanks

**Comment by yanne** [comment]
I do not have a 32-bit Windows machine available. Can you install `pip`: https://pypi.python.org/pypi/pip, and install RIDE with `pip install robot framework-ride`

**Comment by pekkaklarck** [comment]
It's actually possible to install 32bit Python on 64bit Windows. Could consider dropping separate Win-installers in favor of pip altogether. Win-installers do create desktop shortcuts, though.

**Comment by yanne** [comment]
I will create 32 bit installers for the 1.5 release. at least.
