### ISSUE TITLE
I am unable to download the String library

### ISSUE THREAD

**Issue by bhajojo** [robotframework/RIDE#1495]
I am unable to download the String library by using the commad
pip install robotframework-string

**Comment by HelioGuilherme66** [comment]
The String library is included in robotframework.
You would only need to
import    String

(locate it if needed in ../site-packages/robot/libraries)

**Comment by bhajojo** [comment]
I am able to view the file in the location, but how it could be imported to Ride
in setting using  the following is not working 
Library C:/Python27/Lib/site-packages/robot/libraries/String.py

**Comment by HelioGuilherme66** [comment]
The correct syntax is:
Library    String

(I was wrong in my previous comment)

**Comment by bhajojo** [comment]
Thanks for your help 
The path of file needs to be given as 
Library   robot\libraries\String.py

**Comment by yanne** [comment]
Just the name of the library should be enough, i.e. what @HelioGuilherme66 said.

This is not a valid issue, closing it.

**Comment by bhajojo** [comment]
Please do not mark it as invalid issue,as it was not working without giving the path of that library..

Others may also face this issue and may get help by looking into this query
Sent from my Sony Xperia™ smartphone

---- Janne Härkönen wrote ----

**Comment by mkorpela** [comment]
@bhajojo :
A valid issue is something that requires changes to the product - in this case RIDE. As this does not, it will be closed as an invalid issue.

**Comment by VipSaran** [comment]
Possibly leave it open as a reminder until this is addressed e.g. through docu update?

**Comment by qajiny** [comment]
Hi Bhajojo ,
I am also facing same issue . I've tried many commands but not able to import String library .

"import library C:\Python27\Lib\site-packages\robot\libraries\String"  also did not work .

Could you please give me exact command ?

- Thanks ,
  Veena

**Comment by bhajojo** [comment]
U just need to give path as /robot/libraries/string 

That will solve the issue

**Comment by bhajojo** [comment]
U just need to give path as /robot/libraries/string 

That will solve the issue

**Comment by bhajojo** [comment]
U just need to give path as /robot/libraries/string.py

That will solve the issue

**Comment by qajiny** [comment]
Hi ,
I tried following command at cmd :-
c:\python27\Lib\site-packages\robot> import library robot/libraries/string.py

but it did not work & I got following message :-
'import' is not recognized as an internal or external command,
operable program or batch file.

Please let me know right command . 

- Thanks ,
  Veena
