### ISSUE TITLE
Cannot execute RIDE by pythonw.exe at first time

### ISSUE THREAD

**Issue by MoonSungHoon** [robotframework/RIDE#1497]
I know that RIDE write some preferences at "%USERPROFILE%\AppData\Roaming\RobotFramework".

But after I finished installing RIDE, I cannot execute with pythonw.exe.
( maybe stdout problem with pythonw )

I should have execute with python.exe at first. After that, pythonw is okay.

**Comment by yanne** [comment]
I don't know what we could do to fix this. Additionally, why can't you always run RIDE with python.exe?

**Comment by MoonSungHoon** [comment]
I made a windows intaller program with RIDE.
That include ride runner using pythonw.exe
But user have to execute with python.exe
This is not critical issue. If this is wontfix I just want to know about is there a way to solve this.
