### ISSUE TITLE
unable to run ride.py on mac machine 

### ISSUE THREAD

**Issue by bhajojo** [robotframework/RIDE#1498]
I am getting error when tried to run ride.py on the mac machine 

The error log is as follows 
Segementation fault :11

System configuration is as follows 
Python version 2.7.9
Robot framework version : 2.8.7
MAc OS X 10

**Comment by HelioGuilherme66** [comment]
After seeing the log in robotframework-users group:
I think that the reason is that RIDE needs 32bit Python in MAC OSX.
This is the text from the installation instructions:

Preconditions  
Python 

RIDE runs only on the regular Python, not on Jython nor IronPython. Python 2.6 is the minimum version. Notice that similarly as Robot Framework, RIDE does not yet support Python 3. Notice also that on OS X RIDE requires 32-bit Python version.

**Comment by yanne** [comment]
Which wxPython version you have installed?

Make sure you set Python to 32-bit mode with `export VERSIONER_PYTHON_PREFER_32_BIT=yes`

**Comment by bhajojo** [comment]
How to check the wx.python version is there any command to do so

Sent from my Sony Xperia™ smartphone

---- Janne Härkönen wrote ----

**Comment by yanne** [comment]
Open python interpreter and run
```
>>> import wx
>>> wx.version
<function version at 0x1799770>
>>> wx.version()
'2.8.12.1 (mac-unicode)'
>>>
```

**Comment by bhajojo** [comment]
The Wx python version is found to be 2.9.4 OS X-cocoa 
Please let me know if this is supported 

Date: Fri, 14 Aug 2015 03:21:35 -0700

**Comment by yanne** [comment]
This is not (and will not be) a supported version. Please install wxPython 2.8.12.1, it it the only supported version in OSX.

**Comment by rdmclin2** [comment]
wxPython 2.8.12.1 cannot be installed in my MBP(the new version of EI Capitan), i tried to install it using the installer, but failed :
```
$ sudo installer -pkg /Volumes/wxPython2.8-osx-unicode-2.8.12.1-universal-py2.7/wxPython2.8-osx-unicode-universal-py2.7.pkg/ -target /
installer: Package name is wxPython2.8-osx-unicode-universal-py2.7
installer: Installing at base path /
2015-10-30 17:01:55.380 installer[12052:206655] Package /Volumes/wxPython2.8-osx-unicode-2.8.12.1-universal-py2.7/wxPython2.8-osx-unicode-universal-py2.7.pkg uses a deprecated pre-10.2 format (or uses a newer format but is invalid).
installer: The install failed
```

**Comment by yanne** [comment]
Have you allowed unidentified installations? The wxPython installer is not properly signed.

**Comment by rdmclin2** [comment]
@yanne yes, i have allowed to install applications from any sources, but it doesn't work.

**Comment by jmagaru** [comment]
Please try my workaround:
https://github.com/jmagaru/wxPython2.8-osx-unicode-flat-package-py2.7
It works in El Capitan.

**Comment by edisonquisiguina** [comment]
Thanks @jmagaru, 
Your solution works for me on OSX Sierra.

**Comment by NiveditaMirjikar** [comment]
@jmagaru When i try ur solution it displays no such file or directory. Really stuck at this problem. Can anyone clarify wxPython can be installed on mac sierra. I am not able to install ride on mac. Please give me proper steps to install ride on High sierra.
