### ISSUE TITLE
Highlighting selected cell (and matches) does not work.

### ISSUE THREAD

**Issue by MoonSungHoon** [robotframework/RIDE#1502]
When I clicked a cell with variable, same variables turned be yellow.

But after 1.4 release, it doesn't work well in windows environment.

**Comment by MoonSungHoon** [comment]
At 1.4b3, I could check yellow coloring doesn't work when the variable is exist in arguments.

**Comment by VipSaran** [comment]
:+1:

**Comment by MichaelHallik** [comment]
RF 2.9, RIDE 1.4.1, Pytho 2.7.10.

The highlighting (through yellow background color) of cells that contain the same string as the currently selected cell, does indeed not function anymore.

E.g. for cells that contain the same keyword as the cell currently selected (e.g. all cells in the current test case that contain 'Run keyword if').

Or cells that contain the variable that is declared/assigned by the currently selected cell. Such as cells that use the variable name in some expression.

**Comment by yanne** [comment]
Okay, I'll investigate this for 1.5 release.

**Comment by MichaelHallik** [comment]
FYI:

When entering a string that will not be recognized by RIDE into a cell (e.g.: abc), then the cell WILL have the yellow background color.

Hovering over that cell with the mouse cursor will then yield the 'Keyword not found!' tooltip message.

**Comment by MoonSungHoon** [comment]
If string could be colored not background, it would be better to find.
