### ISSUE TITLE
Python Variable File

### ISSUE THREAD

**Issue by astrosuf** [robotframework/RIDE#1508]
I have created variable files in python to use with robot framework, when I run them using the command line it works fine. But when I load the project into RIDE the variable files do not show. 

Does RIDE accommodate .py variable files, if so how does it work? 

If not , will the next few releases of RIDE accommodate them?? 

Thanks in advance for any help.

**Comment by yanne** [comment]
This is not currently supported, and is in my opinion a critical missing feature. That said, current development resources are not sufficient to implement this in the near future.

**Comment by Nyral** [comment]
@HelioGuilherme66 This works if you use Variables import. So it appears that it has been implemented at some point.

![image](https://user-images.githubusercontent.com/39315668/58207019-8a89f800-7cea-11e9-8402-74dc3fb90b44.png)
![image](https://user-images.githubusercontent.com/39315668/58207157-c6bd5880-7cea-11e9-9911-9ec12244a605.png)
![image](https://user-images.githubusercontent.com/39315668/58207211-e94f7180-7cea-11e9-933e-1c1162014408.png)
RIDE recognizes them and even shows them in autocomplete.

**Comment by HelioGuilherme66** [comment]
Closed because (use OR operator):
- is too old,
- newest version should have it fixed,
- not reproducible,
- not an issue,
- is a question,
- lacks logs, versions info, e.t.c.,
- there is no other reason that justifies being opened.

(thanks @Nyral for validating)
