### ISSUE TITLE
Double clicking in the cell doesn't focus on the right place

### ISSUE THREAD

**Issue by nigotiator** [robotframework/RIDE#1516]
I have for example //a[@class='logout'] written on the cell. I double click the word logout and the focus is set to ' after the word logout.
Found on 1.5a2 and it correctly worked on 1.4.1

![ride_focus](https://cloud.githubusercontent.com/assets/477138/9677216/d988841e-52df-11e5-9fab-e6e9cf8d0a8f.jpg)

**Comment by yanne** [comment]
Which OS?

Thanks for the report, I'll take a look at this before 1.5 final

**Comment by nigotiator** [comment]
Oh, Win 7

**Comment by HelioGuilherme66** [comment]
Closing Issue as fixed.
Currently on RIDE v2.0.2.dev1 in Fedora Linux 36, Python 3.10.10, wxPython 4.0.7 (KDE Plasma 5 with darkmode, custom colors).
