### ISSUE TITLE
Changing a variable name in the tree does NOT change the name in the editor pane (and tests fail)

### ISSUE THREAD

**Issue by MichaelHallik** [robotframework/RIDE#1519]
Setup:
- Win7
- Python 2.7.10
- RF 2.9.1
- RIDE 1.5a2

Preconditions & actions (see also the repro path of issue #812.):
1. Open RIDE.
2. Make sure yo have a (e.g. scalar) variable somewhere.
3. In the project tree, select the variable.
4. Click it or press F2 to edit it.
5. Change the var name.
6. Press Enter.

Expected result:

Both in the tree and in the right hand pane, the var name has been modified

Actual result:

Only in the tree the var name has been modified. Running a test which references the var (directly or indirectly), now fails due to an unknown var name.

Note:
1. Modifying the var name through the right hand pane, then the changes WILL be reflected in the tree node. So it only fails the other way around.

**Comment by HelioGuilherme66** [comment]
I am looking for a fix of this one.
There exists a FindVariableOccurrences() but it is not called from code. This method is a subclass of FindOccurrences which is designed for Keywords. I could use some logic from it but it must be rewritten. I have already found an entry point (common from Tree and Settings section).

**Comment by HelioGuilherme66** [comment]
Fixed (at least since 1.7.4a1)
