### ISSUE TITLE
/tmp/ride.log collision when multiple users using the same host and running ride.py in unix enviroments

### ISSUE THREAD

**Issue by dgonyier** [robotframework/RIDE#1520]
In UNIX environments, if multiple users are runing ride.py from different VNC sessions, etc. on the same host, after the first session has created /tmp/ride.log, any other user trying to run ride.py will get a stack trace due to permissions denied error on /tmp/ride.log as the permissions are set by the first user running that file. This is traced to code in robotide/context/logger.py in the '\__init_\_' and '_output' methods of the 'Syslog' class.

As a workaround for UNIX environments, maybe prepend the ride.log filename with either the running userid or the PID of the ride.py process to create unique /tmp/*ride.log files per user or per session.

(reference: https://github.com/robotframework/robotframework/issues/2138)

**Comment by yanne** [comment]
This is definitely a bug and will be fixed.

In the meantime, you can prevent creation of the log file by editing `~/.robotframework/ride/settings.cfg`, and setting `[[Log]] log_to_file = False`

**Comment by dgonyier** [comment]
I have also found another work around by setting the environment variable TMP to another directory before starting ride.py
