### ISSUE TITLE
Argument validation error thrown when a valid ordering is specified

### ISSUE THREAD

**Issue by daveesposito** [robotframework/RIDE#1523]
Ride 1.5a2
Robot Framework 2.9.1 (Python 2.7.8 on Win32)

This is a little confusing (I'm still learning how dictionary variables play into this for keyword arguments) but I think there is a bug in the RIDE argument validator.

Prior to RF2.9 (RIDE 1.5) we had plenty of keywords where we specified required arguments, then optional arguments and then list arguments in the form:

${req} | ${opt}=def |@{varargs}

With RIDE 1.5a2 creating a new keyword with arguments in this form causes an error stating that list and scalar arguments must be before named and dictionary arguments.  If I move the optional argument to the end of the arguments I don't get this validation error, however, it's not correct according to Robot Framework rules so that when I run the test it fails because the args are in the wrong order.

I can open existing files with keywords in the correct order and it doesn't cause any issues but making new keywords doesn't work from within RIDE.

![ride error](https://cloud.githubusercontent.com/assets/8275951/9877704/8f09e364-5b8c-11e5-88bf-e53f35e8fd62.png)

**Comment by yanne** [comment]
Thanks for the report, I'll look into it.
