### ISSUE TITLE
Messed up UI when adding tags to the TC

### ISSUE THREAD

**Issue by nigotiator** [robotframework/RIDE#1524]
RIDE 1.5a2 running on Python 2.7.10. 
Win 7

The tag part of the UI is messed up when adding new tag to the test case. 
The < Add New > box is on top of the older tags and if you write tags to that box those are shown after you return back to the test case.

![ride_tags](https://cloud.githubusercontent.com/assets/477138/9898627/7a50106c-5c5c-11e5-91ac-3c9006b01098.jpg)

**Comment by Nyral** [comment]
@HelioGuilherme66 Not an issue anymore.

**Comment by HelioGuilherme66** [comment]
Closed because (use OR operator):
- is too old,
- newest version should have it fixed,
- not reproducible,
- not an issue,
- is a question,
- lacks logs, versions info, e.t.c.,
- there is no other reason that justifies being opened.

(thanks @Nyral for validating)
