### ISSUE TITLE
View all tags(F7) doesn't work.

### ISSUE THREAD

**Issue by synsun** [robotframework/RIDE#1526]
No response after push "F7" key or click "View all tags" in menu.

No error in Log.

in 1.5a2

**Comment by yanne** [comment]
Which operating system? Works for me, both in OS X and Linux

**Comment by MoonSungHoon** [comment]
in Windows

exactly Windows 7 Enterprise SP1.

Last available version is 1.4b2. I use this version because of this problem.

**Comment by yanne** [comment]
This is (hopefully) fixed now
