### ISSUE TITLE
Comment lines removed

### ISSUE THREAD

**Issue by bnccg** [robotframework/RIDE#1533]
Most of comment lines are removed or moved when editing the .robot file.  The editor should only perform the modifications done by the user.

Examples:
1.- File header. Usually files have a header, for example including SVN details (file, revision, author). The file header is completely removed.
2.- Commented libraries. If a library is commented, it is moved as a comment from the previous library
Library    MyLib
# Library    MyLibDummy

is changed to
Library    MyLib     #Library    MyLibDummy
3.- Other comments, as separators for keywords, etc. I consider usefull having separator lines. These lines are either removed or moved to incorrect positions.
###### 

**\* Variables ***
###### 

I think that the editor should only perform the modifications done by the user, but not automatic modifications like these ones.

Version: RIDE 1.5a2 running on Python 2.7.3.

**Comment by yanne** [comment]
This is due to the fact that RIDE uses Robot Framework parsing modules to parse the test data, and commented lines are not preserved in that model. 

Fixing this would require writing a separate parser, which, for now, is too big a task.

**Comment by Nyral** [comment]
@HelioGuilherme66 This is not feasible to implement.

**Comment by HelioGuilherme66** [comment]
I agree with issue author. See below, original file on the left, edited with RIDE on the right:
![image](https://user-images.githubusercontent.com/2866630/58292532-9abcd880-7db9-11e9-98be-58fc017a5467.png)
