### ISSUE TITLE
Add Dialog option to remove READ ONLY flag from a file.

### ISSUE THREAD

**Issue by StefanIGit** [robotframework/RIDE#1538]
We use SSCM and when you get files from the repository they have always the read only flag set.
I think it has something do do with it's "is  modified" detection.

It would be nice when the current dialog box "Modification prevented" had the option to remove the read only flag, like a yes/no question, so I would not have to go to file explorer and do it per file.

Basically it could work like in Notepad++ where you cannot edit until you remove the flag by context menu on the file tap.
Or like in Eclipse where it pops up a dialog when you start editing it.

**Comment by yanne** [comment]
There could be a warning when starting to edit such a file. Adding permissions might be tricky, at least ClearCase does not allow doing this without a cc command.

**Comment by StefaniGit** [comment]
OK, how about an option in in the TestSuite(Case) context menu to remove/set the read only flag or at least an "Open Folder" in the file-exploer or how the thing in is called in windows. Is there a default thing for other OSs too?
As far as I understand with these I can check for read only and remove read only and it should be OS independed:
if os.access(sDocu, os.W_OK):
    os.chmod(sDocu, stat.S_IWRITE)

**Comment by HelioGuilherme66** [comment]
Hello @StefanIGit 
(you still around? ;) )
We have this feature covered now. Please confirm.
Thanks.

**Comment by StefanIGit** [comment]
o hi... ,

Sorry I didn't realize I had to close it.

Thx bye
