### ISSUE TITLE
Create Dictionary Variable is missing from the tree context menu

### ISSUE THREAD

**Issue by luisxiaomai** [robotframework/RIDE#1541]
Hi,

I updated RIDE to 1.5 version, but I can't create dictionary variable in UI. It still only create list or scalar variable. Do you have any plan for this?

Thanks
Luis

**Comment by yanne** [comment]
Actually, you can create dictionary variables with a button on the right side of the variable list. The tree context menu is missing this action though, I'll update the issue accordingly.
