### ISSUE TITLE
Using Ride on Mac - Fonts in test case Steps are too small

### ISSUE THREAD

**Issue by pedgarcia** [robotframework/RIDE#1544]
I am using Ride on Mac with wxPython 2.8 installed. Everything seems fine in terms of font size, except the ones in the grid where I should add the case steps.

Please see attached image.

Thanks

![ride_-_assets](https://cloud.githubusercontent.com/assets/3932415/11351560/4f5048d0-9205-11e5-8794-240c861d5e6b.png)

**Comment by HelioGuilherme66** [comment]
Can't you change the size in Preferences > Grid Editor ?
![ride_grid_text_prefs](https://cloud.githubusercontent.com/assets/2866630/11352289/7a85d1c2-9233-11e5-9be7-a89dd4e62ead.png)

**Comment by pedgarcia** [comment]
Ops, my mistake. I am new to this and I look everywhere. It seems I didn't do a good job :) I will close the ticket. Thanks
