### ISSUE TITLE
no python installation found in the registry while try to install RIDE 1.5

### ISSUE THREAD

**Issue by malli02422** [robotframework/RIDE#1546]
Hi ,
I have installed python 2.7 , WXpython3.0 and robotframe work 3.0a1
I have downloaded RIDE robotframework-ride-1.5.win-amd64 when I have try to install it , then I am getting "no python installation found in the registry"  .
Please help me in solving the issue

**Comment by HelioGuilherme66** [comment]
Which installation guide did you follow? I don't think that the official guide would mention wxPython 3.0. For RIDE 1.5 it must be wxPython 2.8.12.

Is your Python 2.7, 64bit? If it is, there are some registry hacks that must be done.

(I think that there are plans to stop using Windows installer for RIDE)
The best way to install is by using pip in a command window, like:
C:\> pip install robotframework-ride

**Comment by zyklonwu** [comment]
download robotframework-ride-1.5.tar.gz

**Comment by yanne** [comment]
I think the original issue is that you have installed 32 bit version of Python, which cannot install the RIDE package.
