### ISSUE TITLE
Mismatch of Issue IDs with the correct issues on the Release-notes page.

### ISSUE THREAD

**Issue by vippin** [robotframework/RIDE#1553]
This is not actually an issue with RIDE but rather the RIDE-Release Notes page on github.

On the following page:
https://github.com/robotframework/RIDE/wiki/Release-notes

When clicking on an IssueID in any of the RIDE release tables, the issue it takes you to doesn't seem to match the Summary text that was in the table.
> 
> e.g. Clicking on:
> Issue 1326 If wxpython is not installed or correct version, point user to the correct download page
> 
> takes you to:
> Could RIDE be capable of supporting double FOR loop ? #1326

**Comment by yanne** [comment]
That is an old page. It seems that the issue links were broken when we migrated from Google Code to GitHub. I updated the page accordingly, with a link to the more recent release notes and release page.
