### ISSUE TITLE
How to find the release notes of 1.4 and 1.5 version

### ISSUE THREAD

**Issue by ChuanyuWang** [robotframework/RIDE#1555]
I would like to check out the release notes of 1.4 and 1.5 version, while I fail to look for them within RIDE wiki or other places, anyone could point it out?
Many thanks!

**Comment by HelioGuilherme66** [comment]
When you browse this Git project there is a link with the number of releases, just click on it and look for the ones you want.
https://github.com/robotframework/RIDE/releases

You should ask questions at the robotframework Google group. This tracker is for real Issues (defects or improvements).

**Comment by ChuanyuWang** [comment]
Thanks for the info, I found [google group](http://groups.google.com/group/robotframework-users). It's quite usefully, thanks again.
