### ISSUE TITLE
AltGr Key makes lost cell focus sometimes

### ISSUE THREAD

**Issue by jamofer** [robotframework/RIDE#1557]
AltGr Key makes lost cell focus sometimes. With spanish keyboard you need it for type "{" or "}" making that while typing variables you can accidentally clear all the cell content.

Tested using Ubuntu 14.04

**Comment by HelioGuilherme66** [comment]
Closing Issue as fixed.
Currently on RIDE v2.0.2.dev1 in Fedora Linux 36, Python 3.10.10, wxPython 4.0.7 (KDE Plasma 5 with darkmode, custom colors).
