### ISSUE TITLE
Default tags are not returned to test case when adding and removing a tag

### ISSUE THREAD

**Issue by kaisur** [robotframework/RIDE#1560]
RIDE 1.5

Precondition: Test suite has default tags, test case doesn't have any tags

Steps to reproduce:
- Add a new tag to one test case (default tags are not used and not visible in UI for that test case)
- Remove the added tag from the test case

Expected result: Default tags should be returned to the test case, since it doesn't have any tags. In Text edit view, [Tags] label should be removed from the test case.

Actual result: Default tags are not returned to the test case. No tags visible in Edit view, Text edit view for test case shows label '[Tags]' without any tags.

**Comment by yanne** [comment]
This is a bit complicated. The test case may have an empty `[Tags]`, which means "override default tags, but do not add any own tags". The `Clear` button removes also the empty `[Tags]`, and restores the view to showing the default tags.

**Comment by yanne** [comment]
Closing as invalid.
