### ISSUE TITLE
Support for Robot Framework 3.0

### ISSUE THREAD

**Issue by w60001** [robotframework/RIDE#1568]
Now that Robot Framework 3.0 has been released with Python 3.x support, RIDE also needs to be updated.  The current setup.py installation procedure is not Python 3.x compatible.

**Comment by pekkaklarck** [comment]
I don't think wxPython is Python 3 compatible. Also, I don't think RIDE implementation language really matters.

**Comment by yanne** [comment]
wxPython3 at least claims to be Python 3 compatible, haven't tested it myself. So, in theory this is possible after wxPython3 is the only supported wxPython version.

**Comment by pekkaklarck** [comment]
I thought wxPy3 just uses wxWidgets 3 and separate Project Phoenix would be Py3 compatible. I could be wrong and Phoenix could have been rebranded to wxPy3. Regardless of that, RIDE's language shouldn't matter much. I doubt, for example, that there would be benefits RIDE supporting both Py2 and Py3.

**Comment by yanne** [comment]
They are currently the same, i.e. wxPython3.0.3 will be Python3 compatible. As long as Python 2 is widely available, I agree that there's no rush to change RIDE runtime. If wxPython starts to gain Python3 only features, this discussion becomes more relevant.

**Comment by w60001** [comment]
From an end user point of view, especially when deploying these tools to an organization of engineers, I would much rather have only one version of Python installed (with the preference being Python3 now that RF supports it).

I understand that there is an extra dependency on wxPython, but it seems to me that RIDE should support all of the Python runtimes that Robot Framework supports.  If it does not, then it isn't a very effective IDE.  Just my 2 cents...

**Comment by yanne** [comment]
The issue is not so straightforward, IMO. RIDE implementation language is not relevant as long as it supports the execution of tests with all Robot runtimes (currently, you can run tests with e.g. Jython too)

Having less dependencies is of course good, and that might be good enough reason to do 2 to 3 transition at some point. Agree that supporting both versions would be waste.

**Comment by antakar** [comment]
Robot Framework is now quite stable with Python 3.x. WxPython3.0.2, from what I read, is stable too.
Is there any progress updating RIDE to use Python 3?

**Comment by HelioGuilherme66** [comment]
Closed because (use OR operator):
- is too old,
- newest version should have it fixed,
- not reproducible,
- not an issue,
- is a question,
- lacks logs, versions info, e.t.c.,
- there is no other reason that justifies being opened.
