### ISSUE TITLE
wxversion 2.8 does not use wxversion to check wx version in centos

### ISSUE THREAD

**Issue by wxjeacen** [robotframework/RIDE#1569]
wxversion 2.8 does not use wxversion to check wx version in Centos Server.

And another API for wx.version() to get the current wx version.
So, the wx version detect method in robotide.**init** may need change.

**Comment by yanne** [comment]
What is the API used by CentOs? Which wxPython version you have installed?

**Comment by HelioGuilherme66** [comment]
Closed because (use OR operator):
- is too old,
- newest version should have it fixed,
- not reproducible,
- not an issue,
- is a question,
- lacks logs, versions info, e.t.c.,
- there is no other reason that justifies being opened.
