### ISSUE TITLE
Use `setuptools', not `distutils` for installation

### ISSUE THREAD

**Issue by pekkaklarck** [robotframework/RIDE#1582]
`distutils` is deprecated and `setuptools` should be used instead. If I've got it right, installations using `pip` will always injecting `setuptools` into the process somehow, but when installing with `python setup.py install` that's not the case. `pip` is also trying to drop the special `distutils` support, although it seems they needed to revert that now: https://github.com/pypa/pip/issues/3384

Robot Framework has implemented this with the following code after normal `distutils` imports in `setup.py`. Apparently `setuptools` automagically monkeypatches `distutils` somehow.

``` python
try:
    import setuptools    # use setuptools when available
except ImportError:
    pass
```

Alternatively it should be possible to just import needed entry points directly from `setuptools`. It is also questionable is a fallback to `distutils` needed. At least `request` has recently dropped it: https://github.com/kennethreitz/requests/pull/2973

**Comment by yanne** [comment]
I think we can safely drop the support for distutils. I do not think many people install from source package anyway, and those people should be able to acquire setuptools if they don't already have it.
