### ISSUE TITLE
[DEV] Discussion about wx version detection and setup improvements

### ISSUE THREAD

**Issue by HelioGuilherme66** [robotframework/RIDE#1585]
This issue is to talk about improving the way wxPython is detected.

Currently the user does not have a way to select a older wx version (i.e. it always selects the highest version installed). The code enforcing this is in `__init__.py`:
```python
supported_versions = ["2.8"]

try:
    import wxversion
    from wxversion import VersionError
    if sys.platform == 'darwin':
        supported_versions.append("2.9")
    wxversion.select(supported_versions)
```
I propose that this mechanism is removed, to allow the user to select the wx version installed by:
- Setting `wx.pth` (in site-packages) with the default version name, or
- Passing an environmental variable, like `WXPYTHON` to override the default.

This suggestion also implies not using the module `wxversion`, which is the one forcing the highest installed version.

**Comment by yanne** [comment]
I think this was originally implemented because there were some linux systems with wxPython 2.6 and 2.8 around. I think the wxVersion.select() call can be dropped, but I think we should still either give a warning or outright fail if we know an incompatible version if used.

**Comment by HelioGuilherme66** [comment]
I'd like for you to try my branch [setup_improv](https://github.com/HelioGuilherme66/RIDE/tree/setup_improv) to help me getting a working ride_postinstall.py in Windows.
These are the changes in the branch:
- Removed distutils fallback
- Changed to setuptools and ez_install
- Replaced TK dialogs by wx dialogs
- Removed wxversion use
- Added a "--version" option to RIDE (I had the intention to report it in ride_postinstall.py, but did not due to major problem in Windows).
- Added the creation of a Desktop shortcut to RIDE in Linux (user must run `ride_postinstall -install` after setup or pip)
- Added the creation of a Desktop shell script to call RIDE in Mac OS X (user must run `ride_postinstall -install` after setup or pip)

The problems with Windows installer are:
- There is an error of loading the C++ DLL when ride_postinstall.py calls verify_install() which uses wx. The only way to workaround is not to use wx in ride_postinstall.py and Windows. I am almost certain that the distutils package to create the installer (`python setup.py bdist_wininst`) is getting a 32bit DLL that crashes on my x64 Windows 7.
- The ride_postinstall.py can only be called from the Windows installer (due to special function call). This prevents me to have a similar solution as for Linux and OS X.
- The creation of MSI installer (`python setup.py bdist_msi`) fails because the present version includes one more revision number instead of only three. This is, we have 1.5.2.1 when is expecting something like 1.5.3.

Thanks for all the help and thoughts about this.

**Comment by pekkaklarck** [comment]
Have you investigated is it possible to create shortcuts etc. when using pip? I think it wasn't earlier but don't know the current situation.

In general it would be great to get rid of separate Windows installers, but shotcuts etc. are important. One alternative would be asking users to run something like `python -m robotide.setup` after installation. There could also be a menu entry to run that.

**Comment by HelioGuilherme66** [comment]
I found a way to create desktop shortcut in Windows. It works automatically after setup.py install or pip install. Right now I have disabled questioning the creation of shortcut to user under Windows, this could be reactivated if decided to not use installer (it still crashes!). I can go further to try to use the old shortcut creation without questioning when using the installer, but then will have other code to run ride_postinstall.py standalone.

This new method of standalone shortcut creation adds a new dependency, `pywin32` which does not have PyPy packages.

For Linux and OS X there are now problems because usually the install is with `sudo`, and so the Desktop location needs better detection.

I have another branch that includes this automated post-install, here: [setup_test](https://github.com/HelioGuilherme66/RIDE/tree/setup_test)

**Comment by HelioGuilherme66** [comment]
Houston, we have a PR!
Don't you love the smell of PRs at 3:40h?
Check it out: PR#1589

:-) :fireworks:

**Comment by HelioGuilherme66** [comment]
Following the PR #1589 comments, I now have another branch [desktopshort](https://github.com/HelioGuilherme66/RIDE/tree/desktopshort) where:
 - Removed ez_setup.py
 - Transformed ride_postinstall.py into a module: `python -m robotide.postinstall -install`
Next, I will create a menu entry and a "first time run detection" to call the module from RIDE.

**Comment by HelioGuilherme66** [comment]
Final PR is #1597.
The major improvement is that now we have a desktop shortcut created in Linux, Windows and OS X.
The desktop shortcut can be created from command line or from RIDE.
