### ISSUE TITLE
Error while installing RIDE

### ISSUE THREAD

**Issue by moshere** [robotframework/RIDE#1587]
Hi,
I'm trying to install RIDE on windows environment with pip.
I'm getting the following error. Can you help with this?

thank you

c:\AMAN\testautomation\robotframework-ride-1.5.2.1>"c:\Users\mosher\AppData\Local\Programs\Python\Python35-32\Scripts\pip.exe" install robotframework-ride
Collecting robotframework-ride
  Using cached robotframework-ride-1.5.2.1.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\mosher\AppData\Local\Temp\pip-build-iq5l48tv\robotframework-ride\setup.py", line 20, in <module>
        execfile(join(ROOT_DIR, 'src', 'robotide', 'version.py'))
    NameError: name 'execfile' is not defined

**Comment by HelioGuilherme66** [comment]
You are using Python 3.5.
RIDE is only compatible with Python 2.6 and 2.7.
(Seems you are using a full path for "pip" and a unusual location for Python. I advise you to install Python at C:\Python27)

**Comment by yanne** [comment]
Closing this, since this is not a relevant issue.
