### ISSUE TITLE
Problems with tests selection from View All Tags dialog

### ISSUE THREAD

**Issue by HelioGuilherme66** [robotframework/RIDE#1588]
There are some problems with the selection of tests from the View All Tags dialog.
(created a video [here](https://youtu.be/QEz6gQEGdbA))

- First access to View All Tags shows list in descending order.
- Selection of tests by tag is not always correct.

This is observed in RIDE 1.5.2.1 and 1.5.2 (when View All Tags sort feature was added #1565).

**Comment by HelioGuilherme66** [comment]
This will be fixed by PR #1593.

**Comment by yanne** [comment]
Fixed by a58a45311978e64
