### ISSUE TITLE
Unknown variables color not documented

### ISSUE THREAD

**Issue by StefanIGit** [robotframework/RIDE#1590]
I tried to find out why some of my variables are pink.... turns out that these are unknown variables.
It would be nice tohave that setting in the preferences > Grid Editor settings:
- to see (docu)
- to change

[here I found the answer](https://github.com/robotframework/RIDE/commit/d57386688ce0063c472d7afdd0b2ab63024eae5f)
![Preferences](https://cloud.githubusercontent.com/assets/15795837/12941560/132883ce-cfd4-11e5-96cb-475d77cddc14.png)

**Comment by yanne** [comment]
This seems to be a valid issue.

**Comment by HelioGuilherme66** [comment]
Fixed by #1907
