### ISSUE TITLE
Error running ride.py after install

### ISSUE THREAD

**Issue by kbesser** [robotframework/RIDE#1591]
After install I tried to run ride.py and received this error:

File "/path/to/file/bin/ride.py", line 19, in <module>
    import wxversion
ImportError: No module named wxversion

To fix the issue I went to the log.py file in  
File "/path/to/file/lib/python/robotide/log/log.py" and on line 43

 tempfile.gettempdir(), '{}-ride.log'.format(uuid.uuid4()))

I changed it to 

tempfile.gettempdir(), '{0}-ride.log'.format(uuid.uuid4()))

and now ride.py works from command line

**Comment by HelioGuilherme66** [comment]
That fix is totally unrelated with the initial error.
You did not refer which version of RIDE (and wxPython) you installed and Python version.

That fix should be part of a global code refactor to have it compatible with Python 3.x.

**Comment by kbesser** [comment]
I am using RIDE 1.5.2.1 with wxPython 2.8.12.1 and have Python version 2.6.6 and also using Robot Framework 3.0.

The only issue that I am now faced with when running a .robot file in RIDE is during the run:

[ ERROR ] Taking listener '/path/to//lib/python/robotide/contrib/testrunner/TestRunnerAgent.py:51817:False' into use failed: Importing listener '/path/to/lib/python/robotide/contrib/testrunner/TestRunnerAgent.py' failed: Creating instance failed: AttributeError: 'module' object has no attribute 'getpid'
Traceback (most recent call last):
  File "/path/to/lib/python/robotide/contrib/testrunner/TestRunnerAgent.py", line 112, in __init__
    self._send_pid()
  File "/path/to/lib/python/robotide/contrib/testrunner/TestRunnerAgent.py", line 128, in _send_pid
    self._send_socket("pid", os.getpid())

The test runs and does as expected and passes but am unsure about the error above.

As for the fix not being related to the initial error I am not quite sure how it fixed the issue. I can double check again to see if I made any other changes but I do not believe that I do.

**Comment by kbesser** [comment]
For the error above...
we compiled this code

	import java.lang.management.ManagementFactory;

	public class javaPID{

		public static int intPID()
		{
			String pID = ManagementFactory.getRuntimeMXBean().getName();
			String num = "";
			int i = 0;
			while(pID.charAt(i) != '@')
			{
				num += pID.charAt(i);
				i++;
			}
			return Integer.parseInt(num);
		}
	}

javaPID.class file and placed it in /path/to/directory/jython2.7/Lib/site-packages

then in /lib/python/robotide/contrib/testrunner/TestRunnerAgent.py
added
	
	try:
		import javaPID
	except Exception:
		pass
and after the def _send_pid(self) line 
added

	try:
        	self._send_socket("pid", os.getpid())
	except Exception:
		self._send_socket("pid", javaPID.intPID())

after this I was able to run ride.py and run my .robot file without error.

**Comment by yanne** [comment]
I guess the error is from the test runner plugin, and you ar executing the tests with a jybot profile. As to why your Jython does not have `os.getpid`, I have no idea. What Jython version are you running?

In any case, I don't think there is really a RIDE bug here, so I am closing this.
