### ISSUE TITLE
 User keyword remains on tree view after deleted from a suite

### ISSUE THREAD

**Issue by anole1980** [robotframework/RIDE#1601]
VERSION: RIDE 1.5.2.1(git main)

DESCRIPTION:
    I'm sure that this is a new issue, you can reproduce it by following steps:
        1. Run RIDE without opening a existing project
        2. Create a new test suite
        3. Create a new user keyword in the test suite
        4. Right click the user keyword and click "Delete" item on context menu
   Now, strange thing happens, the user keyword item remains there, but the test suite was marked as dirty and it was indeed modified.

MORE:
     I've done a little bit debug things, and I found that there was a exception raised in following codes:

```
class TestSelectionController(object):

    def __init__(self):
        self._tests = {}

    def is_empty(self):
        return not bool(self._tests)

    def is_test_selected(self, test):
        return test.longname in self._tests.keys() <--- 
```

The exception said something like : "The UserKeyworkController object has no attribute longname", there could be something wrong while handling the object identification,  what do you think, guys?

PS: Sorry for my poor english, :-)

**Comment by HelioGuilherme66** [comment]
Fixed by #1890.
