### ISSUE TITLE
pool performance when loading many resource/case files from a suite

### ISSUE THREAD

**Issue by divfor** [robotframework/RIDE#1602]
I have a suite that have 100+ case/resource .txt files. when I open RIDE it spends 4s to load data files and 45s to populate from these data files. PyCharm's profilor reports that there are thread lock conflicts that lead to too much wait time.
![diagram](https://cloud.githubusercontent.com/assets/3319979/13164273/f31365f0-d6ee-11e5-992c-ca2a3b7aec20.png)

**Comment by divfor** [comment]
def _load_datafile(self, path, load_observer):
        datafile = self._loader.load_datafile(path, load_observer) #spend 4s
        if not datafile:
            return None
        self._populate_from_datafile(path, datafile, load_observer) #spend 36s
        return datafile

**Comment by divfor** [comment]
def resources_for(self, datafile, load_observer):
        return self._load(_ResourceLoader(
            datafile, self._namespace.**get_resources**), load_observer)

**Comment by divfor** [comment]
I addressed the pool performance is located in below three functions. can we improve it?
```python
 def _collect_each_res_import(self, datafile, ctx, collector):
        items = set()
        ctx.set_variables_from_datafile_variable_table(datafile)
        for imp in self._collect_import_of_type(datafile, robotapi.Resource):
            res = self._resource_factory.get_resource_from_import(imp, ctx)
            if res and res not in ctx.parsed:
                ctx.parsed.add(res)
                collector(res, ctx, items)
        return items

    def get_resources_from(self, datafile):
        resources = list(self._get_resources_recursive(datafile,
                                                       RetrieverContext()))
        resources.sort(key=operator.attrgetter('name'))
        return resources

    def _get_resources_recursive(self, datafile, ctx):
        resources = set()
        res = self._collect_each_res_import(datafile, ctx, self._add_resource)
        resources.update(res)
        for child in datafile.children:
            resources.update(self.get_resources_from(child))
        return resources
```

**Comment by yanne** [comment]
I am not sure how easy it is to optimise that code, but it's definitely worth taking a look.

**Comment by kolesnikandrei** [comment]
I think it needs to move on to asynchronous actions
