### ISSUE TITLE
[DEV] wxPhoenix - Renaming of a file due to conflicts with wx.grid imports

### ISSUE THREAD

**Issue by HelioGuilherme66** [robotframework/RIDE#1611]
When dealing with the GridEditor/GridCellEditor which must be overriden and instantiated, this is done in edtor/grid.py. This causes some conflicts when importing wx.grid and .grid. I need to know if it will be OK to rename grid.py to (for example) owngrid.py. The files which are using its classes are listed below:
```
[helio@localhost RIDE]$ grep -l -R --include "*.py" "\.grid" * 
src/robotide/editor/fieldeditors.py
src/robotide/editor/settingeditors.py
src/robotide/editor/kweditor.py
src/robotide/editor/grid.py
src/robotide/editor/tooltips.py
utest/editor/test_gridcolorizer.py
utest/editor/test_grid.py
```
May I proceed with the change? I am doing this in my branch wxPhoenix, but before I do a PR, I want to be sure that it is OK.

**Comment by yanne** [comment]
You can always use `import as XXX` in these kinds of situations to avoid the name clash.

However, I think renaming `grid` to `gridbase` would make sense.

**Comment by HelioGuilherme66** [comment]
Closing via #1616
