### ISSUE TITLE
monitorcolors not recognized

### ISSUE THREAD

**Issue by por3et** [robotframework/RIDE#1615]
Just setup Ride on windows.

So i was following a simple test case creation video:
https://www.youtube.com/watch?v=6F_xGKdoN1E

And I got the following error when running my test:
```
command: pybot.bat --argumentfile c:\users\por~1\appdata\local\temp\RIDEjguw_f.d\argfile.txt --listener C:\Python27\lib\site-packages\robotide\contrib\testrunner\TestRunnerAgent.py:50813:False C:\Users\por\Documents\robotframework-ride-1.5.2.1\src\bin\suite.robot
[ ERROR ] option --monitorcolors not recognized

Try --help for usage information.

test finished 20160307 10:54:00
```

I cant find anyone getting this issue online. DOes anyone have any idea what the problem might be?

Thanks,
Philip

**Comment by HelioGuilherme66** [comment]
I am almost certain that you are using an old version of Robot Framework with the newest version of RIDE.
Best is to upgrade Robot Framework, or edit pybot.bat and replace `--monitorcolors` by `-C`, if you want to use the old version.

**Comment by por3et** [comment]
Hi, thanks for your reply. 
I'm using: RIDE 1.4.1 running on Python 2.7.11. 

```
C:\Users\por\pybot --version
Robot Framework 3.0 (Python 2.7.11 on Win32)
```

I think my RObot is the latest, so I'll try and change the pybot.bat if I figure out how :)

**Comment by HelioGuilherme66** [comment]
Sorry about that. I assumed you where using RIDE 1.5.2.1 because of `C:\Users\por\Documents\robotframework-ride-1.5.2.1\src\bin\suite.robot ` 
Just upgrade RIDE and the problem is long gone ;).

**Comment by por3et** [comment]
you are correct :) it worked, thanks very much. I didnt install the latest version in the first place because it woon't install, but the problem was I was trying to install by double clicking instead of via cmd.

All good now, thanks again! closing
