### ISSUE TITLE
auto completion MAC

### ISSUE THREAD

**Issue by julienb29** [robotframework/RIDE#1617]
Hello,

I would like to use the Keyboard shortcut for code completion on Mac OS X.
I see in the help menu ^_

I am not sure to understand. It doestn't work. 
- Ride - 2.0a1

Thanks in advance.

**Comment by julienb29** [comment]
I notice that copy/paste don't work no more.

**Comment by HelioGuilherme66** [comment]
Closed because (use OR operator):
- is too old,
- newest version should have it fixed,
- not reproducible,
- not an issue,
- is a question,
- lacks logs, versions info, e.t.c.,
- there is no other reason that justifies being opened.
