### ISSUE TITLE
Ride does log during the test execution only in first run

### ISSUE THREAD

**Issue by Yulesha** [robotframework/RIDE#1619]
Hi! I have a problem. 

Ride does not show log information during test. Only in first launch does it.
[https://cloud.mail.ru/public/KGkT/TGMz5WxQd](url)

**Comment by HelioGuilherme66** [comment]
Sometimes it happens when the first time execution was interrupted.

**Comment by Yulesha** [comment]
It happens even if first time execution was not interrupted.  When I try disable Test Runner in the Manage Plugins Ride hangs out.

**Comment by HelioGuilherme66** [comment]
There should be something wrong with your RIDE install or environment.
Could you go to chat in our #ride channel in [slack](https://robotframework.slack.com/) (you can create an account from this project README page).
Please post here the text from Tools>View RIDE Log.

**Comment by Yulesha** [comment]
Thanks, but I accidentally resolved my problem. 

Previous I did not Close Browser by test. 

Now I do Suite Teardown   Close Browser and all are ok. 

I do not know why.
