### ISSUE TITLE
Test case repeat execute

### ISSUE THREAD

**Issue by tangkelu** [robotframework/RIDE#1620]
RIDE 1.5.2.1 running on Python 2.7.11.
DESCRIPTION:
My test case:
单节点，在DB服务不能启动时断网后恢复，业务无法恢复
单节点，在DB服务不能启动时重启网络，业务无法恢复
1 The "单节点，在DB服务不能启动时断网后恢复，业务无法恢复" will repeat execute, and the result is failed.
2 This two test case is the same in the first 13 words.
3 If i rename the test case to "单节点，aaa在DB服务不能启动时断网后恢复，业务无法恢复", then execute result OK.

Expection:
Judge the test case name with the full name to difference them.

![robot_bug](https://cloud.githubusercontent.com/assets/2888607/13842053/35218a66-ec67-11e5-92ef-40f260fb9aae.png)

**Comment by HelioGuilherme66** [comment]
This should be a Windows specific problem; I did not reproduced in Linux.
Could you test in a window command using pybot or robot?
(and maybe Robot Framework version would be important to know, although I have tested with 2.8.7, 2.9.2 and 3.0)
![asian_tests_ok_official_ride_rf3](https://cloud.githubusercontent.com/assets/2866630/13843749/8327b008-ec2d-11e5-8c9f-bc91cebaad5a.png)

**Comment by HelioGuilherme66** [comment]
Closed because (use OR operator):
- is too old,
- newest version should have it fixed,
- not reproducible,
- not an issue,
- is a question,
- lacks logs, versions info, e.t.c.,
- there is no other reason that justifies being opened.
