### ISSUE TITLE
[ ERROR ] option --monitorcolors not recognized

### ISSUE THREAD

**Issue by kumsan-ha** [robotframework/RIDE#1623]
Hi,

I am new to Robotframework and RIDE and i tried to test my first test case (sample) and then i got the error:
//
command: pybot.bat --argumentfile c:\users\admin\appdata\local\temp\RIDEkxon41.d\argfile.txt --listener C:\Python27\lib\site-packages\robotide\contrib\testrunner\TestRunnerAgent.py:49793:False C:\Python27\Scripts\MySecond.html
[ ERROR ] option --monitorcolors not recognized

Try --help for usage information.

test finished 20160326 13:29:02
//

Please help me to resolve this issue.

Thanks.

**Comment by StefanIGit** [comment]
Sounds like your robot framework and Ride versions are not compatible...
What does it say when in Ride, Menu > Tools  >View RIDE Log...
Should be the first 2 lines like this
`20160502 08:44:09.720 [INFO]: Found Robot Framework version 2.9.2 from 'C:\Python27\lib\site-packages\robot'.
20160502 08:44:09.720 [INFO]: Started RIDE 1.5 using python version 2.7.9 with wx version 2.8.12.1 in win32.`

**Comment by HelioGuilherme66** [comment]
Please update RIDE to 1.5.2.1, where that problem is fixed.
`pip install --upgrade robotframework-ride`

**Comment by kumsan-ha** [comment]
Hi,

Thanks, after updating the issue got resolved.

Thanks and Regards,

V PRASANNA KUMAR.

On 2 May 2016 at 15:02, StefanIGit <notifications@github.com> wrote:

> Sounds like your robot framework and Ride versions are not compatible...
> What does it say when in Ride, Menu > Tools >View RIDE Log...
> Should be the first 2 lines like this
> 20160502 08:44:09.720 [INFO]: Found Robot Framework version 2.9.2 from
> 'C:\Python27\lib\site-packages\robot'.
> 20160502 08:44:09.720 [INFO]: Started RIDE 1.5 using python version 2.7.9
> with wx version 2.8.12.1 in win32.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/robotframework/RIDE/issues/1623#issuecomment-216172830>
>



-- 
Best Regards,

V PRASANNA KUMAR
visit http://www.tamilrhymes.com

**Comment by HelioGuilherme66** [comment]
Closed because (use OR operator):
- is too old,
- newest version should have it fixed,
- not reproducible,
- not an issue,
- is a question,
- lacks logs, versions info, e.t.c.,
- there is no other reason that justifies being opened.
