### ISSUE TITLE
Ride is showing very small font size in mac os 10.9.5

### ISSUE THREAD

**Issue by sunita7** [robotframework/RIDE#1630]
I have installed python version 2.7.11 and installed robotframework 3.0 and wx python(3.0.2.0) and also installed RIDE (1.5.2.1). Ride was opening properly but text size is very small not able to increase the size. Coule you pls help me to increase the font size inside the editor.

Note: RIDE supports only wx python 2.8.12.1 but we are not able to use this in mac thats why i use brew to install wx python 3.0 and updated init.py to use wx python 3.0.

**Comment by Nyral** [comment]
@HelioGuilherme66 Must have been some sort of incompatibility between versions/packages.
I think this can be closed.

**Comment by HelioGuilherme66** [comment]
Closed because (use OR operator):

- is too old,
- newest version should have it fixed,
- not reproducible,
- not an issue,
- is a question,
- lacks logs, versions info, e.t.c.,
- there is no other reason that justifies being opened.

(thanks @Nyral for validating)
