### ISSUE TITLE
Runtime ERROR R6034 during SETUP RIDE Robot Framework

### ISSUE THREAD

**Issue by rashtrapathy** [robotframework/RIDE#1636]
![ride_issue](https://cloud.githubusercontent.com/assets/19791856/15847362/e9e69bb4-2ca2-11e6-9cd0-bf94e5347fe4.png)

![ride_issue_1](https://cloud.githubusercontent.com/assets/19791856/15850126/feb67558-2cb3-11e6-991e-fe8052d2629d.png)

R6034 error during installation on Windows 7
robotframework-ride-1.5.2.1.win-amd64 --- tried to install this version.
Python26 -- already installed
wxPython3.0-win64-3.0.2.0-py26 --- installed this wxPython.

C:\Python26>python
Python 2.6.6 (r266:84297, Aug 24 2010, 18:13:38) [MSC v.1500 64 bit (AMD64)] on
win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import wx
>>> print wx.VERSION
(3, 0, 2, 0, '')
>>>

i tried the other way, and got the following error

C:\Users\Desktop\robotframework-ride-1.5.2.1>ride_postinstall.py -
install
Installation successful.
Traceback (most recent call last):
  File "C:\Users\Desktop\robotframework-ride-1.5.2.1\ride_postinst
all.py", line 31, in <module>
    create_desktop_shortcut()
  File "C:\Users\Desktop\robotframework-ride-1.5.2.1\ride_postinst
all.py", line 21, in create_desktop_shortcut
    link = join(get_special_folder_path("CSIDL_DESKTOPDIRECTORY"), 'RIDE.lnk')
NameError: global name 'get_special_folder_path' is not defined

C:\Users\Desktop\robotframework-ride-1.5.2.1>

**Comment by HelioGuilherme66** [comment]
This is what I would do:
- Replace Python 2.6 by Python 2.7.
- Not use the windows installer (it will be dropped). Use `pip` that would be the same for all operative systems (it is already included in Python 2.7).

For your second error:
- The version 3.0.2 of wxPython does not have that get_special_folder_path().
- If you insist on installing with Windows installer, it will only work with wxPython 2.8.12.1.

(If you want, you may use experimental releases at [my Git fork](https://github.com/HelioGuilherme66/RIDE/releases)

**Comment by rashtrapathy** [comment]
Thanks for your quick reply on this issue. I have uninstalled Python26 and installed Python 2.7.11 & wxPython 2.8.12.1 (unicode) for Python 2.7 

BUT when i import i got the below error on wx. Let me know what is missing.

C:\Users\rchandrasekar>python
Python 2.7.11 (v2.7.11:6d1b6a68f775, Dec  5 2015, 20:32:19) [MSC v.1500 32 bit (
Intel)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import wx
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Python27\lib\site-packages\wx-2.8-msw-unicode\wx\__init__.py", line 4
5, in <module>
    from wx._core import *
  File "C:\Python27\lib\site-packages\wx-2.8-msw-unicode\wx\_core.py", line 4, i
n <module>
    import _core_
ImportError: DLL load failed: %1 is not a valid Win32 application.
>>>


WHEN i tried to install ride.py it say wxPython is not installed.

C:\Users\rchandrasekar>
C:\Users\rchandrasekar>python C:\Python27\Scripts\ride.py
wxPython not found.
You need to install wxPython 2.8.12.1 with unicode support to run RIDE.
wxPython 2.8.12.1 can be downloaded from http://sourceforge.net/projects/wxpytho
n/files/wxPython/2.8.12.1/

C:\Users\rchandrasekar>

**Comment by rashtrapathy** [comment]
Worked fine with below executables.

python-2.7.amd64
wxPython2.8-win64-unicode-2.8.12.1-py27
pip install robotframework
pip install robotframework-ride
python c:\Python27\Scripts\ride.py

**Comment by Harshika-Pareek** [comment]
WHEN i tried to install ride.py it say wxPython is not installed.

C:\Users\rchandrasekar>
C:\Users\rchandrasekar>python C:\Python27\Scripts\ride.py
wxPython not found.
You need to install wxPython 2.8.12.1 with unicode support to run RIDE.
wxPython 2.8.12.1 can be downloaded from http://sourceforge.net/projects/wxpytho
n/files/wxPython/2.8.12.1/

rashtrapathy@ Hi I am facing the same issue could you please help me out with this?

**Comment by rashtrapathy** [comment]
Worked fine with below executables.

python-2.7.amd64
wxPython2.8-win64-unicode-2.8.12.1-py27
pip install robotframework
pip install robotframework-ride
python c:\Python27\Scripts\ride.py

**Comment by Harshika-Pareek** [comment]
Thanks for the Reply ..  it worked!
