### ISSUE TITLE
Issue is running RIDE test cases

### ISSUE THREAD

**Issue by AmitAjgaonkar123** [robotframework/RIDE#1638]
Hi 
i did upgrade to robotframework using the below command 
 > pip install robotframework --upgrade

After opening the RIDE am trying to run a simple test 
log| hi in  RIDE 

i am getting the below error 
--------------------------------------------------------------------------
command: pybot.bat --argumentfile c:\users\ajgaonka\appdata\local\temp\RIDExieo7z.d\argfile.txt --listener C:\Python27\lib\site-packages\robotide\contrib\testrunner\TestRunnerAgent.py:57907:False C:\Python27\TestProj\Test\1.robot
[ ERROR ] option --monitorcolors not recognized

Try --help for usage information.

test finished 20160608 18:23:23
-------------------------------------------------------------------------

can anyone please help me in fixing this ? 
am not able to figure out what is causing this issue 
thanks
amit

**Comment by AmitAjgaonkar123** [comment]
Hi 

i update RIDE by using this command 
pip install robotframework-ride --upgrade 
and it has started working now :) 

RIDE v1.5.2.1 
python : 2.7.6 
Robotframework  3.0 

Please close the issue 
thanks

**Comment by HelioGuilherme66** [comment]
@AmitAjgaonkar123, good that you solved your problem. Could you please close this issue? Thanks.

**Comment by AmitAjgaonkar123** [comment]
closing :)
