### ISSUE TITLE
RIDE cannot execute custome script when custome script end with space

### ISSUE THREAD

**Issue by krizex** [robotframework/RIDE#1639]
I config my custom script in ride, but unfortunately I more hit a space at the end of the custom script, see the picture below, the RIDE raise the error, I spend much time to detect the issue, and I have open a PR for this issue, hope it can help others.
![image](https://cloud.githubusercontent.com/assets/3365993/16071621/e755c3f8-330e-11e6-9d33-884bec420ad2.png)

**Comment by krizex** [comment]
fixed in #1640

**Comment by Nyral** [comment]
@HelioGuilherme66 This looks fixed. Can you double check?

**Comment by HelioGuilherme66** [comment]
Closed because (use OR operator):

- is too old,
- newest version should have it fixed,
- not reproducible,
- not an issue,
- is a question,
- lacks logs, versions info, e.t.c.,
- there is no other reason that justifies being opened.

(thanks @Nyral for validating)
