### ISSUE TITLE
Keyword drop-down displays blank 

### ISSUE THREAD

**Issue by ghost** [robotframework/RIDE#1643]
Once I've created a new test case, I click in the 1st row of column 1 and press command + space. A drop-down of available keywords should display from an imported library, but just displays an empty grey box. Is this a problem for other users? What might be the reason behind why I cannot view available keywords from my library?

**Comment by HelioGuilherme66** [comment]
You checked that the library import is not red text?
If you import a standard library (like Strings, OperativeSystem) or start typing BuiltIn and activate keywords suggestions with command+space, would you see the suggestions as expected?
I assume that the suggestions algorithm may need one or two characters to start searching the keywords list.
There is a small chance that the problem you describe is happening in your system. What is the Operative System, wxPython version and Python, and RIDE version too?

**Comment by Nyral** [comment]
@HelioGuilherme66 No point in keeping this open if he hasn't responded until now.

**Comment by HelioGuilherme66** [comment]
Closed because (use OR operator):

- is too old,
- newest version should have it fixed,
- not reproducible,
- not an issue,
- is a question,
- lacks logs, versions info, e.t.c.,
- there is no other reason that justifies being opened.

(thanks @Nyral for validating)
