### ISSUE TITLE
Ride Doesn't start:  ImportError: No module named robotide

### ISSUE THREAD

**Issue by SRobotic** [robotframework/RIDE#1647]
Hi,

I'm not able to start the Ride. It was working fine before. As I reinstalled the TCL, and Python 24, I'm getting this error. I've both Python24 & Python27 in my PATH.

Can somebody help me with the following error I'm getting:

C:\Python27\Scripts>ride.py
Traceback (most recent call last):
  File "C:\Python27\Scripts\ride.py", line 20, in ?
    from robotide import main
ImportError: No module named robotide

**Comment by vcarnogu** [comment]
The version of Python used is not the one where you have RIDE installed. Yo have both in the PATH but the incorrect one is the first.

**Comment by shreemanrao** [comment]
@vcarnogu: Could you tell me how to add ride path on Linux machine?
I have installed **robotframework** as well as **robotframework-ride**.

     testuser@ubuntu:/usr/lib/python2.7$ /usr/local/bin/ride.py 
     Traceback (most recent call last):
       File "/usr/local/bin/ride.py", line 20, in <module>
         from robotide import main
     ImportError: No module named robotide
     testuser@ubunut:/usr/lib/python2.7$

Please help me on this.

**Comment by Wmjanderson** [comment]
@SRobotic your PATH variable should be in ~/.profile. While installing a component such as Robot you'll want the python path (the correct one as @vcarnogu points out) to be the first entry, as the search path for the shell is attempted in left-to-right order. Also, are you sure you want to use py 2.7? Maybe it's a Mac thing, but that's the only version of py that Robot actually works in for me.

**Comment by vcarnogu** [comment]
Yup, first check that the `PATH` definition problem is you situation by running `echo $PATH` in shell.
Then depending on your shell you will need to modify a config file. Check `~/.profile` (as @Wmjanderson points out) or `~/.bash_profile` for existing `PATH` variable definition and modify it.

**Comment by WLee-CWT** [comment]
Hi i have the same problem, i was upgrading my Python 2.7 to python 3.0 and ride 3.0 as well, i am done on most of them. what should be placed in our environment variables?

**Comment by rsaravanan19** [comment]
it is because of the two python versions installed i had the same problem and i suggest removing the python version which is not need and it works

**Comment by cnmaple** [comment]
just run :

>  python /usr/local/bin/ride.py
 python is /usr/local/bin/python  and the version is 2.7

**Comment by Nikkithakur** [comment]
i have 2 versions of python installed. python2 and python3.
i added python3 to my path.
i installed virtualenv, created an environment for python2 and installed robotframework,ride.
ride is not working, no module name robotide is the error.

Is it necessary for me to uninstall one version of python to make it work?

**Comment by silientpeng** [comment]
> i have 2 versions of python installed. python2 and python3.
> i added python3 to my path.
> i installed virtualenv, created an environment for python2 and installed robotframework,ride.
> ride is not working, no module name robotide is the error.
> 
> Is it necessary for me to uninstall one version of python to make it work?

you can try:
python -c "from robotide import main ; main()"

**Comment by Nyral** [comment]
@HelioGuilherme66 Installation issue. Invalid.

**Comment by HelioGuilherme66** [comment]
Closed because (use OR operator):

- is too old,
- newest version should have it fixed,
- not reproducible,
- not an issue,
- is a question,
- lacks logs, versions info, e.t.c.,
- there is no other reason that justifies being opened.

(thanks @Nyral for validating)
