### ISSUE TITLE
Context-menu to open folder in OS file browser

### ISSUE THREAD

**Issue by edbrannin** [robotframework/RIDE#1650]
It would be helpful to be able to right-click on a folder in the tree and open it in the OS file browser.

This would be especially nice for folders that have test data or Python libraries but no .robot files, since they just show up as empty in RIDE.

Note to self/implementor:
- http://stackoverflow.com/a/1795849/25625
- https://docs.python.org/2/library/os.html#os.startfile for Windows

**Comment by StefanIGit** [comment]
I have that function implemented in RIDE 1.5.2.1 for Windows, maybe it is OS independened :) 
it works on folders, test suite files and resource files.
I just have the figure out a way submit a  pull request and we will see if my solution is okish.
Oh and I have a "Remove Read Only" for files too :D

![image](https://cloud.githubusercontent.com/assets/15795837/18509737/75184df2-7a7a-11e6-9d16-ab2167c93618.png)

**Comment by edbrannin** [comment]
@StefanIGit I don't suppose you've had a chance to put together a pull-request for this?

**Comment by StefanIGit** [comment]
I have it now :D 
https://github.com/robotframework/RIDE/pull/1663
... as normal "Works for me!!!1!11"

**Comment by Nyral** [comment]
@HelioGuilherme66 It has been added with the PR from above. Can be closed.

**Comment by HelioGuilherme66** [comment]
Close because is implemented since 1.7.3.
