### ISSUE TITLE
Shortcuts like Ctrl+C doesn't work in Ubuntu with russian keyboard layout

### ISSUE THREAD

**Issue by chevi** [robotframework/RIDE#1653]
The keyboard shortcuts doesn't work in Russian layout on Ubuntu OS

**Comment by Nyral** [comment]
Of course they don't work. With a Russian layout you're not pressing the same letters.

**Comment by HelioGuilherme66** [comment]
Closed because (use OR operator):
- is too old,
- newest version should have it fixed,
- not reproducible,
- not an issue,
- is a question,
- lacks logs, versions info, e.t.c.,
- there is no other reason that justifies being opened.

(thanks @Nyral for validating)
