### ISSUE TITLE
Ride.py  can't show menu content when I click right-hand 

### ISSUE THREAD

**Issue by satiling** [robotframework/RIDE#1654]
Hi,

I met a problem, I open the ride.py, I right click tree on the left menu area , right content can't show,I don't know why ,who can  help me?

**Comment by HelioGuilherme66** [comment]
If you right click on the blank area, there is no context menu. If right clicking on Test Suite, Test Case or External Resources, then the context menu is shown.
(This is bug tracker, please ask questions in [UserGroup](https://groups.google.com/forum/#!forum/robotframework-users) or [Slack](https://robotframework.slack.com/messages/ride))

**Comment by Nyral** [comment]
@HelioGuilherme66 Not an issue.

**Comment by HelioGuilherme66** [comment]
Closed because (use OR operator):
- is too old,
- newest version should have it fixed,
- not reproducible,
- not an issue,
- is a question,
- lacks logs, versions info, e.t.c.,
- there is no other reason that justifies being opened.

(thanks @Nyral for validating)
