### ISSUE TITLE
Ride Tool :: Execution logs not displayed for new run,if previous browser is not closed  

### ISSUE THREAD

**Issue by sachinGirish** [robotframework/RIDE#1656]
Ride Tool :: Execution logs not displayed for new run,if previous browser is not closed and try to run test case.

**Comment by Nyral** [comment]
@sachinGirish There's no relation between the two.

@HelioGuilherme66 Invalid issue.

**Comment by HelioGuilherme66** [comment]
Closed because (use OR operator):
- is too old,
- newest version should have it fixed,
- not reproducible,
- not an issue,
- is a question,
- lacks logs, versions info, e.t.c.,
- there is no other reason that justifies being opened.

(thanks @Nyral for validating)
