### ISSUE TITLE
ImportError: No module named stages

### ISSUE THREAD

**Issue by nor31** [robotframework/RIDE#1657]
Hi,

I am running latest version of robot framework and ride on linux mint. And having environment errors when try to run test cases.

**1st issue:**

[Error] Error in file ‘/home/vs3/s3-swift/automation/robot/platform/platform.config.txt’ : Importing test library ‘/home/vs3/s3-swift/automation/robot/ lib/ConfigLibrary/ConfigLibrary.py‘ failed. ImportError: No module named stages 
Traceback (most recent call):

File ‘/home/vs3/s3-swift/automation/robot/ lib/ConfigLibrary/ConfigLibrary.py‘ , Line 8, in <module>
Import stages

How to resolve this issue? Can anybody help? I have installed robotframework stage library but still not able to solve this error.

I will appreciate your time and help.

**Comment by HelioGuilherme66** [comment]
Closed because (use OR operator):
- is too old,
- newest version should have it fixed,
- not reproducible,
- not an issue,
- is a question,
- lacks logs, versions info, e.t.c.,
- there is no other reason that justifies being opened.

(thanks @Nyral for validating)
