### ISSUE TITLE
Variable not found

### ISSUE THREAD

**Issue by nor31** [robotframework/RIDE#1658]
Hi,

In Ride when i try to run test case directly from git repository, i got  the following error...

[Error] Error in file ‘/home/vs3/s3-swift/automation/robot/modules/platform/quotactl.base.txt : Variable ‘${FIRST_SALTMASTER}’ not found

Please help to solve this error and setting up ride and robot framework environment.

**Comment by aihuasxy** [comment]
where is the resource file  containing variable ‘${FIRST_SALTMASTER}’ ?

**Comment by Nyral** [comment]
@HelioGuilherme66 Issue is not related to RIDE.

**Comment by HelioGuilherme66** [comment]
Closed because (use OR operator):

- is too old,
- newest version should have it fixed,
- not reproducible,
- not an issue,
- is a question,
- lacks logs, versions info, e.t.c.,
- there is no other reason that justifies being opened.

(thanks @Nyral for validating)
