### ISSUE TITLE
The file has been changed on the file system

### ISSUE THREAD

**Issue by jiriarte93** [robotframework/RIDE#1660]
RIDE/Robot Framework alway displays the message: 

![ride](https://cloud.githubusercontent.com/assets/22770850/19272466/f04ff9d0-8fc8-11e6-8051-89ed44cee0bf.png)

The message appears whenever I make any change in RF and not let me save changes.
Moreover when I click en yes or not, temporary files are created in the folder where I am working.

**Comment by StefanIGit** [comment]
Do you have  aggressive Anti Virus? Maybe try to exclude the .robot files or the complete workspace folder from it.
I get this messages only when I check-in the robot files into source control system while RIDE is running.

**Comment by jiriarte93** [comment]
Thank you by your answer but I have already solved this issue. It was caused by a special character (:), in the Test Case name.

> Do you have  aggressive Anti Virus? Maybe try to exclude the .robot files or the complete workspace folder from it.
> I get this messages only when I check-in the robot files into source control system while RIDE is running.
> 
> -- 
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/robotframework/RIDE/issues/1660#issuecomment-259656651


--
_______________________________________________________
__
Javier Iriarte Marzal
Ingenier�a electrónica de telecomunicaciones
Escuela Técnica Superior de Ingenier�a
Universidad de Valencia
_______________________________________________________
__

**Comment by HelioGuilherme66** [comment]
@jiriarte93 Please Close this Issue. Thanks.
