### ISSUE TITLE
python-wxgtk2.8 in the Installation-Instructions

### ISSUE THREAD

**Issue by ppKrauss** [robotframework/RIDE#1666]
On UBUNTU 16 the installation  `pip install robotframework-ride` works fine (!), perhaps need to remove or explain why to suggest `sudo apt-get install python-wxgtk2.8`.

```
Package python-wxgtk2.8 is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source

E: Package 'python-wxgtk2.8' has no installation candidate
```

**Comment by ppKrauss** [comment]
Another problem, as this [2012 tutorial](https://bluntinstrumentsoftesting.com/2014/10/04/install-robot-framework-to-ubuntu-14-04/comment-page-1/), UBUNTU need  
`sudo apt-get install libwxgtk2.8-dev libwxgtk2.8-dbg`... But  is also impossible, error "Unable to locate package libwxgtk2.8-dev" and no new distribution of the package for UBUNTU 16 LTS.

**Comment by momo007** [comment]
i have the same problem! : (

**Comment by Sarath197** [comment]
I have a problem like this
sudo apt-get install python-wxgtk2.8-dev libwxgtk2.8-dbg
Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: Unable to locate package python-wxgtk2.8-dev
E: Couldn't find any package by glob 'python-wxgtk2.8-dev'
E: Couldn't find any package by regex 'python-wxgtk2.8-dev'
E: Unable to locate package libwxgtk2.8-dbg
E: Couldn't find any package by glob 'libwxgtk2.8-dbg'
E: Couldn't find any package by regex 'libwxgtk2.8-dbg'


How can overcome this

**Comment by Nyral** [comment]
Not a RIDE issue.

**Comment by HelioGuilherme66** [comment]
Closed because (use OR operator):
- is too old,
- newest version should have it fixed,
- not reproducible,
- not an issue,
- is a question,
- lacks logs, versions info, e.t.c.,
- there is no other reason that justifies being opened.

(thanks @Nyral for validating)
