### ISSUE TITLE
Strange characters appear after saving changes

### ISSUE THREAD

**Issue by meysammahfouzi** [robotframework/RIDE#1667]
Sometimes strange characters like `ś` appear at different random locations in the file after saving the changes.

**Comment by HelioGuilherme66** [comment]
Those are the most elusive bugs that exist. We would need to create a good trap to catch them!

**Comment by meysammahfouzi** [comment]
@HelioGuilherme66 Is there anything I can do to help you catch it? :)

**Comment by HelioGuilherme66** [comment]
We can give a try. The goal is to see if you find the conditions to have it reproducible. I would like to know:

- The Operative System
- Is the file too big?
- Does it happen using the Text Editor, or the Cell Editor?
- Are you opening only the Test File, or Test Suite folder?
- Do you have other editor with the file opened at same time?
- Is it a local disk or a network (shared filesystem) file?
- Is the file encoded in UTF-8 or other?

I am assuming that you are using RIDE 1.5.2.1 and wxPython 2.8.12.1, and also that the problem only happens with RIDE.

**Comment by meysammahfouzi** [comment]
@HelioGuilherme66 

- OS: Linux Mint 17.3 Rosa
- Size of robot files: around 5K
- I think it only happens with the Text Editor
- I am opening the Test Suite folder
- The file is not open in another editor at the same time 
- It's a local disk file
- The encoding of my robot files is `text/x-diff; charset=us-ascii`
- RIDE 1.5.2.1 running on Python 2.7.6.
- Yes the problem only happens with RIDE

I hope this information helps :)

**Comment by HelioGuilherme66** [comment]
> The encoding of my robot files is text/x-diff; charset=us-ascii

This may be the reason of the issue.
I would always use UTF-8, because it is known to have less problems, specially on *nix systems.
I found this on Robot Framework User Guide:

> Similarly as with the TSV test data, plain text files are always expected to use UTF-8 encoding. As a consequence also ASCII files are supported.

**Comment by meysammahfouzi** [comment]
@HelioGuilherme66 
Probably. Let me give it a try :)

**Comment by HelioGuilherme66** [comment]
Closed because (use OR operator):
- is too old,
- newest version should have it fixed,
- not reproducible,
- not an issue,
- is a question,
- lacks logs, versions info, e.t.c.,
- there is no other reason that justifies being opened.

(thanks @Nyral for validating)
