### ISSUE TITLE
Opening large amount of tests in RIDE folder tree freezes

### ISSUE THREAD

**Issue by Rochet2** [robotframework/RIDE#1668]
I have a directory that contains 800 tests.
Those tests are foldered into multiple folders that have subfolders and so on.
If I open multiple folders / suites that contain tests at the same time, RIDE starts to freeze the whole computer.

I did not seem to notice any change in RAM or CPU usage.
The freezing happens so that when you are in RIDE and click on something - anything: a button in RIDE, some other program on task bar - anything.
The freezing can take from some seconds to for example 10 seconds or possibly more. Usually it is a relatively long time.
Once the freezing happens once, it happens from that  point onwards until RIDE is closed and opened again.

You can try to reproduce this by having a directory that contains 5 folders.
Those folders contain 10 suites each.
The suites contain 1 to 10 tests each.
(Ok, lets just say that the whole left folder tree in RIDE is full of suites and tests. Completely white - having 40 suites open or similar)
When you open all this up in RIDE it will start to freeze. It may require a bit of waiting or fiddling around or trying to click on RIDE and some other program and then RIDE again multiple times or clicking something in RIDE to get the freezing to start happening.

It seems that I am not the only one having this problem as I have witnessed others having it as well.

We all used the latest release, which is https://github.com/robotframework/RIDE/releases/tag/v1.5.2.1

RIDE is a nice tool compared to maintaining things manually in the text files - but this freezing keeps interrupting work and forces restarting RIDE multiple times every day.

With the folder tree I mean the left side of RIDE
![ride_1](https://cloud.githubusercontent.com/assets/468816/20605254/1aa926e4-b273-11e6-90ba-0f5ccbe00dd7.png)

**Comment by Rochet2** [comment]
[tests.zip](https://github.com/robotframework/RIDE/files/1016451/tests.zip)
Here is an example of some test data you can use to try freeze your RIDE.
It contains 160 folders that have 10 suits that have 10 tests each.

To use the data simply place it somewhere, open RIDE, click to open directory in RIDE and select the Tests folder. To test the freeze simply scroll the tree view up and down once by grabbing the scroll bar with your mouse and then try to change the window focus to any other program, like notepad for example. The system should freeze and you cannot do anything.

I tried profiling RIDE and disabling everything that seemed like a problem, but the freeze still exists.
I disabled for example _sendMessage in publisher entirely as it was called 100 000 times.

The profiling would suggest that the whole program time is almost entirely (not counting data loading) spent in the GUI MainLoop
![diagram](https://cloud.githubusercontent.com/assets/468816/26279163/9e1b7078-3db4-11e7-868c-8e311d66dea8.png)

**Comment by HelioGuilherme66** [comment]
I do confirm that this long tree of tests causes application freeze. In my system (Linux) the scrolling of the tree did not cause the freeze, but it happened when right-click and Select All Tests or Unselect All Tests.

There is an alternate version of RIDE in my [fork](https://github.com/HelioGuilherme66/RIDE/releases/tag/v1.6b3) (which includes some fixes, but not related to the tree). You may experiment it, to see if it makes any difference. Please note, that using wxPython 2.8.12.1 there should not be any unknown bugs, but with newer wxPython there are some.

![1600_tests_ride](https://cloud.githubusercontent.com/assets/2866630/26280187/86788886-3dc1-11e7-8072-d4b0ca1fe7ee.png)

**Comment by Rochet2** [comment]
I tested with all
https://github.com/robotframework/RIDE/commit/31c89037ab3aaccb1abcb9a0c4a5b36cd5fa8e4a (latest release)
https://github.com/robotframework/RIDE/commit/dcdccfec631517743d24c8e31fc6687fd29338a0 (latest source in github)
https://github.com/HelioGuilherme66/RIDE/commit/baf4bf19346bf5d1315b222c4a9febf3d380e758 (your fork latest release)
and the issue happens on all of them. I did not test the latest source from your repo since it requires newer invoke.
The latest RIDE source could not run the tests in the folders that had hypens in their names but the latest releases from you and in RIDE repo can. The nice thing about your version was that utf8 errors dont appear in console even though the output still cannot handle the hypens in the folder names.

The way select all tests and similar actions have been coded certainly introduces a lot of lag. (expand all tree items and collapse them)
But that is not an issue for me/us as it happens only when you try to select a bunch of tests, so it happens when you expect it to happen and it will only freeze RIDE so you can still access other programs (which this issue we are in does not allow). Most of the time I/we dont run huge amounts of tests through RIDE, we only develop using RIDE so only small amounts of tests are run usually. RIDE has nice capabilities for selecting tests, pausing, stepping, editing documentation of tests and such.

**Comment by Rochet2** [comment]
A small update:
I did some searching and found that after this change there seems to be no freeze:
C:\Python27\Lib\site-packages\robotide\ui\tree.py
```diff
    def _create_node_with_handler(self, parent_node, controller, index=None):
        handler_class = action_handler_class(controller)
        node = self._create_node(parent_node, controller.display_name, self._images[controller],
                                 index, with_checkbox=(handler_class == TestCaseHandler and self._checkboxes_for_tests))
        if isinstance(controller, ResourceFileController):
            if not controller.is_used():
                self.SetItemTextColour(node, wx.ColorRGB(0xA9A9A9))
-        self.SetPyData(node, handler_class(controller, self, node, self._controller.settings))
+        self.SetPyData(node, None if handler_class is TestCaseFileHandler else handler_class(controller, self, node, self._controller.settings))
        if controller.is_excluded():
            self._set_item_excluded(node)
        return node
```
Basically I made the action handler to be None for when it would use TestCaseFileController.

I tried changing it to wx.Window as that seemed to be the class that it inherited from at the very bottom, but the freeze still happened with it. ( I basically tried to remove all RIDE related code from the handler by doing this )

I tried to print how many of each controller was used and 3260, a huge amount, used TestCaseFileHandler.

**Comment by narayanyadav007** [comment]
Hi Rochet2,
Your solution of adding below line is not working 
self.SetPyData(node, None if handler_class is TestCaseFileHandler else handler_class(controller, self, node, self._controller.settings))

Throws error for 'TestCaseFileHandler'. 

Could you please help.... Getting frustated with slow response on windows 10 :(

**Comment by pakal** [comment]
Maybe have a look at https://github.com/robotframework/RIDE/issues/2017 and tell if this bugfix helps in your case

**Comment by HelioGuilherme66** [comment]
@pakal The fix you propose is on code that was added much after 1.5.2.1.

**Comment by Nyral** [comment]
Fix mentioned by pakal is not related to this issue.

**Comment by Nyral** [comment]
> Do note that the freeze in this issue does not only cause RIDE to freeze like selecting all tests does. Instead the whole computer freezes when you select some other window as active in the windows UI. I believe RIDE is somehow making a huge deal of rendering something or similar. Its hard to analyse this as the whole windows UI is frozen, but I think the window management process was elevated for a moment in the task manager.

@Rochet2 @Soothsilver @HelioGuilherme66 

I managed to figure out a few other things about this issue. 

- The 'freeze' doesn't actually affect windows, it only seems to prevent/delay [all mouse events](https://wxpython.org/Phoenix/docs/html/wx.MouseEvent.html) from taking action).
- After the 'freeze' is over, all mouse events that were being delayed are released and take effect.
- It's not necessary to click on another window, simply moving the mouse outside the RIDE frame causes it to occur. When doing this, EVT_MOTION is sent.
- Keeping the mouse inside the RIDE frame will not trigger the 'freeze'.
- The issue is definitely related in some way to the tree. When scrolling, a delay builds up. As such, even if you stop scrolling, it continues to do so by itself. If in this time you click on a cell in grid editor, the action will not take effect until scrolling stops. The delay I mentioned before also starts to expend in the background. If during this time you do not move the mouse outside the window, then you will be able to edit as you do normally, without any 'freeze'. But if you move the mouse outside the window, while this internal delay hasn't finished, then mouse events will be affected.

**Comment by Soothsilver** [comment]
Okay, wow, good job. Now I really want to know what's causing this.

Somebody could also send this to Microsoft. It could be a bug in Windows and we now have a perfect repro case, even if it's somewhat involved.

**Comment by Nyral** [comment]
@Soothsilver Thanks, but I still need to separate the tree from RIDE first, in order to eliminate all the other possibilities.
Yes, it's the same issue. We should probably merge them at some point.

**Comment by valeriobruno** [comment]
Hello guys.

I've spent some time with casca to reproduce the issue on the current master version.

We have opened a directory containing many tests (thousands).

Loading the directory takes about 1 minute (which might be acceptable).

We opened 3 nodes so to have about 20-30 nodes visible.

We have observed two bad behaviors.

1) When we try to scroll on the "Test Suites" tree, RIDE and Windows 10 freeze for a couple of minutes.
If we try the same on Mac OS X 10.15, we observe slowness on the response of the scroll (which suggests heavy computation) but the rest of the OS GUI remains responsive.


2) if we right click on the root and "Select All Tests", RIDE and Windows freeze for several minutes (>15 minutes).
The same scenario on Mac freezes RIDE for about the same time. The OS GUI remains responsive.


The general impression is that the UI is better segregated on Mac, compared to Window.


Replicating the second scenario, we have stopped the execution with the debugger. And that showed the following stack of the Main thread.
![threads](https://user-images.githubusercontent.com/2890177/81439051-0f755800-916e-11ea-82fe-5db23c2b9ea3.png)


We're not Python experts, but the select all tests causes to 

* Expand recursively all the sub-nodes
  * Which causes the rendering of the sub-nodes.
 
At the end all the expanded nodes are collapsed back.



treeplugin.py
```python
    def _for_all_tests(self, item, func):
        item_was_expanded = self.IsExpanded(item)
        if not self.HasAGWFlag(customtreectrl.TR_HIDE_ROOT) or \
                item != self.GetRootItem():
            if isinstance(item.GetData(), ResourceRootHandler or
               ResourceFileHandler):
                return

            is_item_expanded = self.IsExpanded(item)
            if not is_item_expanded:
                self.Expand(item)
            if self._is_test_node(item):
                func(item)
            if not self.IsExpanded(item):
                return

        for child in item.GetChildren():
            self._for_all_tests(child, func)

        if not item_was_expanded:
            self.Collapse(item)
```
Does anybody know why we expand all the sub-nodes, when we really want just to select (ie graphically highlight) the currently expanded nodes?

cc: @HelioGuilherme66 

Thanks.

**Comment by Rochet2** [comment]
@valeriobruno If I remember correctly from back then, the reason was that the tests are not loaded and parsed unless viewed. There is some kind of lazy loading scheme. I assume it is needed due to long test files and data.
To have an object where the system can set "test selected" status to true it must load the test data from disk, which is done by opening and collapsing the tree.

**Comment by valeriobruno** [comment]
Thanks for the reply @Rochet2 

> When a user normally expands the tree view the system loads the tests as you go.

That seems reasonable when the user manually expands a node.

> To have an object where the system can set "test selected" status to true it must load all of the tests from disk, which is done by opening and collapsing the tree (emulating a user).

I think this could be handled better: the model behind the three can maintain the list of (selected) tests. In case of "Select All Tests", it would iterate over the list of tests to mark them selected _on the model_, without expanding the sub-nodes _on the graphical tree_. 

Iterate over a list of thousand elements takes less then a second on a modern computer. And keeping the list of tests in memory (not the actual tests!) should not use much memory.

I can try to implement it, if we believe it's the approach we want.

(And what does RIDE load when opening a directory, by the way??? )

**Comment by HelioGuilherme66** [comment]
@valeriobruno @Rochet2 Thank you for researching on this. With the new Robot Framework v3.2.1 the new parser may help in speeding up the tree build. New parser allows to consult only some parts of a test suite, like for example getting its Test Names. I am in the beginning of this adaptation to RIDE, but it will take some time, until try to optimize the tree build.
On the current development version, `master`, I have made an attempt to separate the Project Explorer, from the main code to see if it can be better optimized. Unfortunately, the Tree is one of essential components initialized at start, so, even if we start RIDE with the Project Explorer hidden, there is no much improvement. But this component separation can help in making a test program, to benchmark the future optimizations. This should be the way to go.

- Make a standalone program using  `src/robotide/ui/treeplugin.py`
- Include timer and memory probes to register performance
- With `rfgen.py` prepare a large test suite to be zipped and shared with participating in the benchmarking,
- Members will do benchmarking of that component, on different operating systems and conditions.

Interested persons in programming in Python and wxPython, should run the wxPython demo, that you can download from wxpython.org. (then locate the wx.lib.agw.customtreectrl corresponding demo)

**Comment by valeriobruno** [comment]
@HelioGuilherme66 , All.

The reason the Select all freezes the system is Tree._for_all_tests(), which expands all the nodes of the trees, which causes lots of computation to create the new instances (nodes+handlers) and possibly update the UI.

> To have an object where the system can set "test selected" status to true it must load all of the tests from disk, which is done by opening and collapsing the tree (emulating a user).

It might had made sense in the past, but now RIDE is loading all the tests under the instance of the class Project. This also explains why it's slow to open a project with many tests.

Moreover, expanding all the nodes, adds more nodes to the WxWidget tree, which is probably causing more issues as in https://github.com/robotframework/RIDE/issues/1843#issuecomment-626391519  


I re-implemented the select all (here: https://github.com/valeriobruno/RIDE/tree/1668_freeze )
so that 
- Every TestCase instance keeps the information of being selected or not in TestCase.selected.
- The "select/deselect all" iterates over the model tree (controllers under the instance of Project) and set TestCase.selected
- When TestCase.selected changes, an instance of RideTestSelectedForRunningChanged is broadcasted. The graphical tree updates the visible test nodes.

I hope this strategy makes sense.



I tested [with the test folder provided by](https://github.com/robotframework/RIDE/issues/1668#issuecomment-302898615) @Rochet2 and it takes about two seconds to select/unselect all tests. While the current master takes minutes to do the same.

Being new to the code base, I have some design doubts, but the algorithm is much faster.
The code isn't complete, there are few cases to cover: the selection of failed/passed tests for example.

It would be very useful to have some feedback before proceeding. So let me know if you have any thoughts!

Thanks

**Comment by HelioGuilherme66** [comment]
@valeriobruno Thanks for the code. Looks good, there is a noticeable improvement on the loading of the tree (just starting RIDE with the folder as argument). See below my charts, where the reduced one is the new code, it takes 17 seconds to stabilize, whereas the code at master takes around 21 seconds for the same test.
Chart:
![image](https://user-images.githubusercontent.com/2866630/84079550-aaae5700-a9d2-11ea-9f43-f8015cef717a.png)

The command I use is `mprof run invoke devel -a path_to_test_dir` and then `mprof plot name_of_file.dat` (you can install these tools with `pip install matplotlib memory-profiler`).

Attached is the new test folder structure: 
[tests.zip](https://github.com/robotframework/RIDE/files/4748583/tests.zip)

I did not tested in Windows, but, at least, the same improvement should be noticed.
My System: Fedora 32, Python 3.8.3, wxPython 4.0.7.

**Comment by HelioGuilherme66** [comment]
@valeriobruno Unfortunatelly the same testing did not work on Windows.

We have in master, since today, a fix to allow staring RIDE with Tree or File Explorer panels disabled or hidden. This allowed to have a loading time before stabilization of 9 seconds (on the previous system and test folder). This is the chart:
![image](https://user-images.githubusercontent.com/2866630/84212574-1c130600-aab6-11ea-9dfd-1562f5edaea5.png)

Assuming that the behavior is the same on Windows, users can hide the Tree panel, before loading large test suites folders, of they must enable it again when wanting to navigate on files or test suites.

**Comment by valeriobruno** [comment]
Pull request: https://github.com/robotframework/RIDE/pull/2210

**Comment by HelioGuilherme66** [comment]
@valeriobruno @Rochet2 @Soothsilver @Nyral Great news. The freeze is gone with @valeriobruno PR.
See here:
**Before fix:**
![Current_master_tree_selection_RIDE](https://user-images.githubusercontent.com/2866630/84965070-cbc72400-b105-11ea-80d8-b1da06ea094a.gif)
**After fix:**
![Fixed_master_tree_selection_RIDE](https://user-images.githubusercontent.com/2866630/84965120-ef8a6a00-b105-11ea-8ebc-14296626f06d.gif)

My system: Windows 7 Professional x64, Python 3.7.6, wxPython 4.0.7.post2, RF 3.2.1.

**Comment by Soothsilver** [comment]
Great news!! Does this also fix the freeze-upon-scrolling problem?

**Comment by HelioGuilherme66** [comment]
I think so. I did scrolled, it was a bit slow, but no crash.

**Comment by valeriobruno** [comment]
> Great news!! Does this also fix the freeze-upon-scrolling problem?
It should at least reduce the scrolling problem. With this fix, only the nodes explicitly opened by the user are attached to the WX Tree. Therefore, the WX Tree must handle few nodes (as opposed to ALL).

**Comment by jnhyperion** [comment]
with this PR: https://github.com/robotframework/RIDE/pull/2237

this issue should be totally resolved.

**Comment by IlfirinPL** [comment]
@HelioGuilherme66 
I have recently try to open project ( 500+ test cases and many resources ) using most recent sources (Oct 3, 2020) from RIDE using Python 3.8.

Total time increase from less than 30 sec to more then 5 mins

Using profile command
python -m profile -o ride.profile -s tottime  -m robotide.__init__
 
its show most of time is related with "~:0(<method 'acquire' of '_thread.lock' objects>)"

![image](https://user-images.githubusercontent.com/1460956/95472421-4fda3b80-0983-11eb-8c55-1a0153376170.png)
I have attached profile file 
[ride.profile.zip](https://github.com/robotframework/RIDE/files/5348552/ride.profile.zip)

**Comment by HelioGuilherme66** [comment]
@jnhyperion Ping. Please take a look to this, thanks.

**Comment by IlfirinPL** [comment]
@HelioGuilherme66  I can confirm latest changes improve performance tremendous ( now now open under 3 sec vs  5 min)

**Comment by HelioGuilherme66** [comment]
@IlfirinPL Great. Thanks for the feedback.
The fix was made by @JFoederer  so all the credits goes to him!
