### ISSUE TITLE
How to use RIDE in macbook

### ISSUE THREAD

**Issue by ddoraemon** [robotframework/RIDE#1670]
mac version :10.11.6
python version: 2.7.12 Mac OS X 64-bit/32-bit installer

It seems that the command “defaults write com.apple.versioner.python Prefer-32-Bit -bool yes” only works on Python(2.7.10) embedded in the macOS
How can I run 32bit mode for python 2.7.12  installed from .dmg file and it located in /Library/Frameworks/Python.framework/Versions/2.7/bin/python

**Comment by Nyral** [comment]
@HelioGuilherme66 Not an issue.

**Comment by HelioGuilherme66** [comment]
Closed because (use OR operator):

- is too old,
- newest version should have it fixed,
- not reproducible,
- not an issue,
- is a question,
- lacks logs, versions info, e.t.c.,
- there is no other reason that justifies being opened.

(thanks @Nyral for validating)
