### ISSUE TITLE
ride crashes sometimes if the help window is open

### ISSUE THREAD

**Issue by ImmoWetzel** [robotframework/RIDE#1672]
commandline output just
segmentaion fault  (core dumped)

[14:16:26][immow@host:~/]$ pip freeze
cffi==1.9.1
click==6.6
cryptography==1.7.1
decorator==4.0.10
dnspython==1.15.0
ecdsa==0.13
enum34==1.1.6
Flask==0.12
idna==2.2
ipaddress==1.0.17
itsdangerous==0.24
Jinja2==2.8
lxml==3.7.0
MarkupSafe==0.23
ncclient==0.5.2
paramiko==1.16.0
pyasn1==0.1.9
pycparser==2.17
pycrypto==2.6.1
pyftpdlib==1.5.1
pyparsing==2.1.10
requests==2.12.4
robotframework==3.0
robotframework-ftplibrary==1.3
robotframework-ride==1.5.2.1
robotframework-selenium2library==1.8.0
robotframework-sshlibrary==2.1.2
robotremoteserver==1.0.1
selenium==3.0.2
six==1.10.0
terminaltables==3.1.0
vboxapi==1.0
virtualenv==15.1.0
Werkzeug==0.11.11
wxPython==2.8.12.1
wxPython-common==2.8.12.1
XlsxWriter==0.9.4

**Comment by ImmoWetzel** [comment]
dont know if these outputs are related 
  File "/usr/lib/python2.7/dist-packages/wx-2.8-gtk2-unicode/wx/lib/expando.py", line 112, in OnTextChanged
    self._adjustCtrl()
  File "/usr/lib/python2.7/dist-packages/wx-2.8-gtk2-unicode/wx/lib/expando.py", line 125, in _adjustCtrl
    numLines = self.GetNumberOfLines()
  File "/usr/lib/python2.7/dist-packages/wx-2.8-gtk2-unicode/wx/lib/expando.py", line 184, in GetNumberOfLines
    count += self._wrapLine(line, dc, width)
  File "/usr/lib/python2.7/dist-packages/wx-2.8-gtk2-unicode/wx/lib/expando.py", line 210, in _wrapLine
    start = pte[idx]
IndexError: list index out of range
Segmentation fault (core dumped)

how to provide the code dump ?

**Comment by ImmoWetzel** [comment]
used strace to create a logfile.....
[logfile.txt.gz](https://github.com/robotframework/RIDE/files/685293/logfile.txt.gz)

**Comment by HelioGuilherme66** [comment]
I cannot tell much from the strace.
(My hunch is that there are too many files opened. But it is just a hunch.)
Are you able to repeatably produce the crash? If, so could you write the sequence of actions for us to try to reproduce?
Is this a recent installation of RIDE? If not, do you know of any factor that may changed the installation environment?
Thanks.

**Comment by ImmoWetzel** [comment]
Hi folks,

I can really reproduce this but not on a single click..
Best way is to open a context help window click into it to make it permanent.
Afterwards use ride with this open window. Click into several parts of ride. Change selected test, change a value and ride will crash mostly.
And yes its recently installed and an issue on several users here
Immo

**Comment by ImmoWetzel** [comment]
which possibility do we have to create more useful logfiles ?

**Comment by ImmoWetzel** [comment]
OK 
Here you have one way to create the crash on ubuntu linux 16.04
open ride
create a new project
create new testcases T1 
with a single line 
    log     something

put mouse cursor over "log"
press CTRL
detach the help window by clicking into the context help window
close the help window by clicking on the X on the window 

create a new test case T2
try to mark the first and second column with your mouse. ->segfault crash


mark something with the mouse
