### ISSUE TITLE
Ride not running on stop and start inbetween a case.

### ISSUE THREAD

**Issue by adityakoganti** [robotframework/RIDE#1674]
Hi i have found an issue with the latest version of Ride, If a case in stuck and if you are forced to stop the case and again start it, ride wont run unless you restart it. I dont know exactly whether the issue is with my PC or Ride, i haven't faced this issue in previous release so i hope problem is with RIDE.  If anyone facing the same issue support my post so the developers can look into it.

**Comment by tianyueguang** [comment]
I have the same problem.

**Comment by Nyral** [comment]
@adityakoganti @tianyueguang Is this issue still happening with latest release?

**Comment by HelioGuilherme66** [comment]
Closing because is too old and we cannot reproduce, or lack of information.
