### ISSUE TITLE
How to change background (Dark mode)

### ISSUE THREAD

**Issue by chevi** [robotframework/RIDE#1678]
Hi

I would like to change background of RIDE, because I prefer dark themes for eyes. How can I change them?

Grid has no setting in preferences for empty cells background. 
Also I don't know how to change background of the project tree and description field

Thanks

**Comment by devpc777** [comment]
I'm ok with the white background of the tree and settings field, but need to change the background in both editors. 
Also miss the possibility to change the keywords color and the font weight of other elements in the text editor. 

RIDE team,
there are a lot of people with sensitive eyes.

**Comment by elschman** [comment]
Is there any outlook when this could be implemented ?

**Comment by HelioGuilherme66** [comment]
@elschman I am working on it, but there are some performance issues. It will go out for sure in next Beta 2.

**Comment by HelioGuilherme66** [comment]
@elschman @devpc777 @chevi @vascobrunes @Nyral @jnhyperion @dpantelin Please test my development of general colours settings, by installing from my branch:
```
pip install -U https://github.com/HelioGuilherme66/RIDE/archive/colours.zip
```

If you want a pinkish, plum colour set add the following to the ~/.robotframework/ride/settings.cfg (on Windows see %APPDATA%). Then you can see it in Tools->Preferences->General:
```
[General]
font size = 11
# font face = 'Source Code Pro'
font face = ''
foreground = '#FFFFFF'
background = '#5C3566'
secondary foreground = '#DCEDFF'
secondary background = '#9F749A'
background help = '#C4A000'
foreground text = '#A40000'
apply to panels = False
```

**Comment by rbradhika530** [comment]
Hi Can I use this with Ride v2.0b1 ?

**Comment by HelioGuilherme66** [comment]
> Hi Can I use this with Ride v2.0b1 ?

Like I said, it will go on Beta2, which is the current development code.
