### ISSUE TITLE
Ride doesn't work - MAC OS El Capitan 10.11.6 - Python 2.7.9 - WxPython 2.8.12.1 unicode

### ISSUE THREAD

**Issue by TSavin** [robotframework/RIDE#1680]
Hi, 

I'm facing an issue when trying to launch Ride.py on my mac : 

- MAC OS El Capitan 10.11.6
- Python 2.7.9 :  /Library/Frameworks/Python.framework/Versions/2.7/bin/python
- WxPython 2.8.12.1 unicode  : /usr/local/lib/wxPython-unicode-2.8.12.1/lib/python2.7/site-packages/wx-2.8-mac-unicode
- robotframework (3.0.1)
- robotframework-ride (1.5.2.1)

import wxpython return : 

Python 2.7.9 (v2.7.9:648dcafa7e5f, Dec 10 2014, 10:10:46) 
[GCC 4.2.1 (Apple Inc. build 5666) (dot 3)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import wx
>>> wx.version()
'2.8.12.1 (mac-unicode)'

I've tried a new fresh install of Mac OS X but the issue is still the same 

ride.py returns : 

Admin:~ Administrateur$ ride.py
wxPython not found.
You need to install wxPython 2.8.12.1 with unicode support to run RIDE.
wxPython 2.8.12.1 can be downloaded from http://sourceforge.net/projects/wxpython/files/wxPython/2.8.12.1/

Thank's

**Comment by HelioGuilherme66** [comment]
Please try to replace (after doing backup) the __init__.py file in site-packages/robotide by this one:
[wxPython branch on my fork](https://github.com/HelioGuilherme66/RIDE/blob/wxPhoenix/src/robotide/__init__.py)

Make sure that when calling ride.py, you are using python2.7.9 (and not other version of python).

**Comment by TSavin** [comment]
Thank's for your reply.

Same happened : 

Admin:~ Administrateur$ ride.py
wxPython not found.
You need to install wxPython 2.8.12.1 with unicode support to run RIDE.
wxPython 2.8.12.1 can be downloaded from http://sourceforge.net/projects/wxpython/files/wxPython/2.8.12.1/
This version will run also on wxPython 3.0.2, download from https://sourceforge.net/projects/wxpython/files/wxPython/3.0.2.0/

**Comment by TSavin** [comment]
Hi,

Same error happened with last Python 2.7.13. 
How can i be sure that python 2.7.* is used when calling ride.py ?

**Comment by yassinej** [comment]
Any update on this issue?

**Comment by HelioGuilherme66** [comment]
All I can say, is that wxPython is not correctly installed (at least not in the place where RIDE is expecting).
Reporter, says wxPython is at /usr/local/lib/wxPython-unicode-2.8.12.1/lib/python2.7/site-packages
Probably RIDE is trying to find here:  /Library/Frameworks/Python.framework/Versions/2.7/site-packages

I do not have access to a MacOS, but I do recall to have a file setting to redirect to the correct place.
How was wxPython installed, from the pkg? With homebrew? We have some notes on how to install on MacOS, on the Wiki.

My advice is to uninstall wxPython and follow the instructions (including extracting the installer from the package and bypassing security (broken package message). Can't say more from memory now.

**Comment by yassinej** [comment]
I formatted my Mac. started from scratch and it all went well.

**Comment by sshan-CS** [comment]
@yassinej  Can you view keyword documentation on MAC?  When I move my mouse over,  there is a grey area, but no text.   Thank you

**Comment by sshan-CS** [comment]
@TSavin  SourceForge  WxPython 2.8.12.1 crashes now.

**Comment by gpankaj** [comment]
Sir any update on this?

**Comment by HelioGuilherme66** [comment]
@sshan-CS @gpankaj @TSavin If you want to try an EXPERIMENTAL version compatible with all wxPython, 2.8.12.1, 3.0.2 and new 4.0.0 (b1, b2, rc1) (ONLY valid for Python 2.7), you can download or install from https://github.com/HelioGuilherme66/RIDE/archive/python3.zip. With `pip install -U https://github.com/HelioGuilherme66/RIDE/archive/python3.zip`. To install wxPython 4.0.0 on MacOS, `pip install wxPython`.

**Comment by specialbiscuit** [comment]
the same problem

**Comment by yangquan1982** [comment]
the same problem to me, I downloaded wxPython 2.8.12.1 from SourceForge, it crashes, couldn't be installed.

**Comment by krysalead** [comment]
Hi,

I discover that it shows an error regarding wxPython but actually it is complaining about wxversion that can't be imported

**Comment by HelioGuilherme66** [comment]
Probably not relevant, one year or more later. If still reproducible, reopen with more information.
