### ISSUE TITLE
librarykeywords.db not created on initial run of ride.py - Win7, Python 2.7.9, wxPython 2.8.12.1

### ISSUE THREAD

**Issue by Wmjanderson** [robotframework/RIDE#1681]
System:
windows 7 SP1
Python 2.7.9 : /Library/Frameworks/Python.framework/Versions/2.7/bin/python
WxPython 2.8.12.1 unicode : /usr/local/lib/wxPython-unicode-2.8.12.1/lib/python2.7/site-packages/wx-2.8-win32-unicode
robotframework (3.0.1)
robotframework-ride (1.5.2.1)
Mechanism:
>ride.py
"Creating librarykeywords database to C:\Users\_my_name_\AppData\Roaming\RobotFramework\ride\librarykeywords.db"
HTTP Error 403: Must access using HTTPS instead of HTTP

Close out of session, restart CLI;  >ride.py results in the RIDE GUI, no keywords available.

**Comment by sarahmck** [comment]
I am having the same problem

**Comment by sarahmck** [comment]
That happened to me the first time I ran it after install.  After the first time, I had no issue.  Also, make sure to specify whatever libraries your keywords will come from, for example:

Add this to your Settings in order to import the selenium library:

*** Settings ***
Library	Selenium2Library

**Comment by HelioGuilherme66** [comment]
Probably not relevant, one year or more later. If still reproducible, reopen with more information.
