### ISSUE TITLE
Must be admin on windows to install

### ISSUE THREAD

**Issue by claytonneal** [robotframework/RIDE#1682]
Hiya
Is there a reason the install wont allow installation if your not logged in as an admin on windows? This is a blocker really in the financial institution where i work to get RF & Ride installed.
Thanks

**Comment by HelioGuilherme66** [comment]
I think if a non-admin can install with `pip` and wxPython on a user dir, there could be workaround.

**Comment by HelioGuilherme66** [comment]
Closed because (use OR operator):
- is too old,
- newest version should have it fixed,
- not reproducible,
- not an issue,
- is a question,
- lacks logs, versions info, e.t.c.,
- there is no other reason that justifies being opened.

(thanks @Nyral for validating)
