### ISSUE TITLE
Ride not know how to wrap arguments 

### ISSUE THREAD

**Issue by prajes02** [robotframework/RIDE#1684]
I am using robot framework with RIDE.  Here Keywords are getting wrapped with (...), But Arguments are not getting wrapped if we want to limit the length of the characters. 

and It will be good if we have line width marker option in editor.

**Comment by Nyral** [comment]
@prajes02 Line continuation is added by RobotFramework. This is not a RIDE issue.

**Comment by HelioGuilherme66** [comment]
Closed because (use OR operator):
- is too old,
- newest version should have it fixed,
- not reproducible,
- not an issue,
- is a question,
- lacks logs, versions info, e.t.c.,
- there is no other reason that justifies being opened.

(thanks @Nyral for validating)
