### ISSUE TITLE
Could just set the message log window in Run tag?

### ISSUE THREAD

**Issue by v522zy** [robotframework/RIDE#1688]
Could just set the message log window in Run tag?

v1.5 ，message log window is in Edit tag and also the other tags.

but while editing , Lager edit window is preferred,

Thanks

**Comment by HelioGuilherme66** [comment]
So, would you like to see the tag text box larger? Below is how I see it in Windows, and with wxPython 3.0.2 (with a beta version of RIDE).
![image](https://cloud.githubusercontent.com/assets/2866630/23504639/57cb17be-ff38-11e6-8694-f9425231320e.png)

**Comment by v522zy** [comment]
Sorry for my poor English.

Actually, I mean Just show the run log window in Run window, not the other windows

see the image below.

![image](https://cloud.githubusercontent.com/assets/19322753/23536517/6aa90080-0000-11e7-8863-e2ad82f2aef9.png)

**Comment by StefanIGit** [comment]
Nice idea to have the "run tab" in a extra window. :+1:  so you will not be kicked out the editor (grid or text view)
And a tipp about size of the editor (I case you did not know) clicking on the "Settings" button will minimize the settings area and enlarge the Grid editor.

![image](https://cloud.githubusercontent.com/assets/15795837/23891821/5d503a16-0898-11e7-9063-eb08238a2a49.png)

**Comment by Nyral** [comment]
With new RIDE, on python 3, you can move the tab to be at the bottom if you want.

![image](https://user-images.githubusercontent.com/39315668/59167282-14ceba80-8b39-11e9-8da0-4318bb85d12b.png)
