### ISSUE TITLE
Running tests with specified tags BUG

### ISSUE THREAD

**Issue by bendzsui** [robotframework/RIDE#1690]
Dear RIDE support,

I discovered an interesting Bug on the "RUN" tab in the text field for "Only run tests with these tags".
I write the following TAG to my test cases: TORPEDO and when I would like to execute them, I've got the following error message:
[ ERROR ] Suite 'TestCases' contains no tests with tag 'T OR PEDO'.

It seems that the parser for logic operands is very proactive :)

Thanks for your help!

**Comment by HelioGuilherme66** [comment]
This is not a RIDE bug, you get this behavior from Robot Framework command line:
```
C:\>robot --include TORPEDO tests.robot
[ ERROR ] Suite 'Tests' contains no tests with tag 'T OR PEDO'.

Try --help for usage information.
```

**Comment by Rathore2014** [comment]
I have also observed the same problem, in one of robot tests GET-AA-SUPPORT-FILE TAG has been used, but while calling this test we get error message:

contains no tests with tag 'GET-AA-SUPP OR T-FILE', let me know if anyone has found the solution

**Comment by HelioGuilherme66** [comment]
We are now with robotframework==3.1.1 and the problem still exists.
```
-i --include tag *       Select test cases to run by tag. Similarly as name
                          with --test, tag is case and space insensitive and it
                          is possible to use patterns with `*` and `?` as
                          wildcards. Tags and patterns can also be combined
                          together with `AND`, `OR`, and `NOT` operators.
                          Examples: --include foo --include bar*
                                    --include fooANDbar*
 -e --exclude tag *       Select test cases not to run by tag. These tests are
                          not run even if included with --include. Tags are
                          matched using the rules explained with --include.
```
Any solution should be discussed in Google Group or Slack, but on `robotframework` context, not RIDE.
Closed because (use OR operator):
- is too old,
- newest version should have it fixed,
- not reproducible,
- not an issue,
- is a question,
- lacks logs, versions info, e.t.c.,
- there is no other reason that justifies being opened.
