### ISSUE TITLE
[Error 123] of python RIDE run test

### ISSUE THREAD

**Issue by llchying** [robotframework/RIDE#1691]
Hi, 
I met below issue recently, while in the past my python works well. 
command:  --argumentfile c:\users\admin\appdata\local\temp\RIDEnya8ip.d\argfile.txt --listener C:\Python27\lib\site-packages\robotide\contrib\testrunner\TestRunnerAgent.py:62867:False C:\SVN\branches\FPEAutomation
[Error 123] The filename, directory name, or volume label syntax is incorrect

as I can't fix this isue, i already re-installed all my python and wxpython, RIDE etc, but the issue still exist. 

Please help on this issue. 
Thanks.

**Comment by llchying** [comment]
More info
Menu > Tools >View RIDE Log... 
20170408 16:33:33.251 [INFO]: Found Robot Framework version 3.0.2 from 'C:\Python27\lib\site-packages\robot'.

20170408 16:33:33.252 [INFO]: Started RIDE 1.5.2.1 using python version 2.7.10 with wx version 2.8.12.1 in win32.

**Comment by xiabei** [comment]
hello, i met the same problem , have you solved it?

**Comment by HelioGuilherme66** [comment]
There may be problems with filenames in Windows and Chinese configuration. You could try to rename the folders and testfiles to use latin characters (phonetic naming?).

**Comment by HelioGuilherme66** [comment]
Closed because (use OR operator):
- is too old,
- newest version should have it fixed,
- not reproducible,
- not an issue,
- is a question,
- lacks logs, versions info, e.t.c.,
- there is no other reason that justifies being opened.
