### ISSUE TITLE
RIDE Takes long time to load

### ISSUE THREAD

**Issue by vivekspawar** [robotframework/RIDE#1697]
Hi All,

We have more than 1000 cases so when we open the RIDE then it takes lot of time. It takes atleast 5 to 6 min. Is there any optimization technique or any  memory settings which we can change. 

Thanks
Vivek

**Comment by HelioGuilherme66** [comment]
Closed because (use OR operator):
- is too old,
- newest version should have it fixed,
- not reproducible,
- not an issue,
- is a question,
- lacks logs, versions info, e.t.c.,
- there is no other reason that justifies being opened.
