### ISSUE TITLE
pyautogui

### ISSUE THREAD

**Issue by pierre6677** [robotframework/RIDE#1700]
Hello,

I'm strugling to use the pyautogi library with ride.

I wrote the following test file 
*** Settings ***
Library           pyautogui
Library           OperatingSystem

*** Variables ***
${x}              1000
${y}              1200

*** Test Cases ***
mouse move to
    [Documentation]    c'est mon test, la souris doit bouger
    moveTo    ${x}    ${y]

as I ran the sequence i had the message

Starting test: Test2.mouse move to
20170611 17:38:50.337 :  FAIL : ValueError: The supplied sequence must have exactly 2 elements (4 were received).
Ending test:   Test2.mouse move to

Do you have any idea?

Thanks in advance,

BR,

Pierre

**Comment by HelioGuilherme66** [comment]
First of all, that is not a RIDE problem. It is a library problem.

You have to define the values as numeric. For example `${1000}`.

See if it works with those changes.

If not, you should consider to use a wrapper (a Robot Framework library which uses the python library).
Luckily, there already one for `pyautoit`, it is [robotframework-imagehorizonlibrary](https://github.com/Eficode/robotframework-imagehorizonlibrary). I tested with the following code, and worked fine.

```
*** Settings ***
Library           pyautogui
Library           OperatingSystem

*** Variables ***
${x}              ${160}
${y}              ${320}

*** Test Cases ***
mouse move to
    [Documentation]    c'est mon test, la souris doit bouger
    moveTo    ${x}    ${y}
```

**Comment by pierre6677** [comment]
Thanks, it Works as indicated.
Br,
Pierre


Le 12 juin 2017 12:25 AM, "Hélio Guilherme" <notifications@github.com> a
écrit :

**Comment by HelioGuilherme66** [comment]
Closed because (use OR operator):
- is too old,
- newest version should have it fixed,
- not reproducible,
- not an issue,
- is a question,
- lacks logs, versions info, e.t.c.,
- there is no other reason that justifies being opened.
