### ISSUE TITLE
Need to Relaunch RIDE to Run testcases

### ISSUE THREAD

**Issue by YangLuhua** [robotframework/RIDE#1701]
I need to relaunch RIDE in order to run the test cases. Otherwise it does not process all the test cases and will stop at a certain one. If I relaunch RIDE, everything goes smoothly and if I run the test cases again, there will not be any log message and there is no green triangle on the test case which is running. However, it still shows pass for some test cases and will stop at a certain one(not a random one).

**Comment by putaodoudou** [comment]
I meet the same problem. Whether this bug is fixed?

**Comment by HelioGuilherme66** [comment]
Neither of you give enough information. Do you have a small reproducible test case? Do you have any logs, for us to understand on what test it stops, and why?
Do your tests use Selenium2Library which has the known issue of non closed webdriver instances having effect in test runner?
It is also important to know on what Operating System are you using RIDE.

**Comment by HelioGuilherme66** [comment]
Closed because (use OR operator):
- is too old,
- newest version should have it fixed,
- not reproducible,
- not an issue,
- is a question,
- lacks logs, versions info, e.t.c.,
- there is no other reason that justifies being opened.
