### ISSUE TITLE
__init__.robot wasn't manage

### ISSUE THREAD

**Issue by jchabrol** [robotframework/RIDE#1702]
when you create __init__robot file, those file wasn't save.

**Comment by HelioGuilherme66** [comment]
I tried and it worked, created `__init__.robot` and added a Resource import. Then opened the containing folder, and the setting is there for the Test Suite level.

**Comment by jchabrol** [comment]
so with your method I agree that'll open a --init__.robot file.
but I can't add suite setup or teardown.
And the file wasn't reconysed during execution with ride.

**Comment by HelioGuilherme66** [comment]
Closed because (use OR operator):
- is too old,
- newest version should have it fixed,
- not reproducible,
- not an issue,
- is a question,
- lacks logs, versions info, e.t.c.,
- there is no other reason that justifies being opened.
