### ISSUE TITLE
Directory out of current directory

### ISSUE THREAD

**Issue by iliyazpasha1** [robotframework/RIDE#1704]
I am new to Robot Framework.Below issue may be simple but I am unable to solve it
my directory structure is like below

|A|
    > B
    >C

My testcase is running in C.I can get current path using ${CURDIR}(A/B/C).But I am unable to get path like (A/B).Please help me solve this issue.
This is my code 

*** Settings ***
Library  OperatingSystem

*** Variables ***
${testsRootFolder}  ${CURDIR}
${pagesFolder}  ${CURDIR}${/}..${/}B ------------> it is printing like A/B/C/../B but I want to print A/B

*** Test Cases ***
Printing
	Log To Console	${testsRootFolder}
	Log To Console	${pagesFolder}

**Comment by HelioGuilherme66** [comment]
Closed because (use OR operator):
- is too old,
- newest version should have it fixed,
- not reproducible,
- not an issue,
- is a question,
- lacks logs, versions info, e.t.c.,
- there is no other reason that justifies being opened.

**Comment by kenken08** [comment]
> I am new to Robot Framework.Below issue may be simple but I am unable to solve it
> my directory structure is like below
> 
> |A|
> > B
> >C
> 
> My testcase is running in C.I can get current path using ${CURDIR}(A/B/C).But I am unable to get path like (A/B).Please help me solve this issue.
> This is my code
> 
> *** Settings ***
> Library OperatingSystem
> 
> *** Variables ***
> ${testsRootFolder} ${CURDIR}
> ${pagesFolder} ${CURDIR}${/}..${/}B ------------> it is printing like A/B/C/../B but I want to print A/B
> 
> *** Test Cases ***
> Printing
> Log To Console	${testsRootFolder}
> Log To Console	${pagesFolder}

you can use "Normalize Path" in OperatingSystem  Library
just import the ```Library              OperatingSystem```
and put the command inside a variable
```${path}=            Normalize path             ${CURDIR}/../file.png```
then ``` Log to console                ${path}```
