### ISSUE TITLE
[Error 2] The system can't find the file specified. Something to do with win registry

### ISSUE THREAD

**Issue by crvikram** [robotframework/RIDE#1705]
When I attempt to run a simple gmail login program thru' RIDE, I am getting the following error.

command: pybot.bat --argumentfile c:\users\dell\appdata\local\temp\RIDEgq3cqz.d\argfile.txt --listener C:\Python27\lib\site-packages\robotide\contrib\testrunner\TestRunnerAgent.py:50809:False D:\Automation_project\TecHelium\WebTest\robot_test
[Error 2] The system cannot find the file specified

  It runs successfully when I run from the command line, thru' pybot command.
Please share any solution that will help for this kind of issue. Am not sure if it has to do with Windows registry. 
I have my system's environment variable path as well.: ".. C:\Python27;C:\Python27\Scripts; C:\Python27\Lib\site-packages".
                      I have attempted multiple uninstalls and re-installs. Also attempted to Python 2.17.13. But no luck so far. 

My system details:
   Windows 7, 64 bit.
   Python 2.7.12
   Robot framework
   RIDE 
   wxPython 2.8.12.1 (unicode) for Python 2.7

**Comment by prodigalhometown** [comment]
I met the same problem as you.

**Comment by SarathSainath** [comment]
Even i am getting same issue can some one help me on this

**Comment by HelioGuilherme66** [comment]
Closed because (use OR operator):
- is too old,
- newest version should have it fixed,
- not reproducible,
- not an issue,
- is a question,
- lacks logs, versions info, e.t.c.,
- there is no other reason that justifies being opened.
