### ISSUE TITLE
When to support python3

### ISSUE THREAD

**Issue by liufengchaoaa** [robotframework/RIDE#1708]

**Comment by CharmingYang0** [comment]
Maybe you can get some help from this [ticket](https://github.com/robotframework/RIDE/issues/1719).

**Comment by HelioGuilherme66** [comment]
Closed because (use OR operator):
- is too old,
- newest version should have it fixed,
- not reproducible,
- not an issue,
- is a question,
- lacks logs, versions info, e.t.c.,
- there is no other reason that justifies being opened.
