### ISSUE TITLE
In settings, fields are cropping after Tear Down

### ISSUE THREAD

**Issue by kulavardan** [robotframework/RIDE#1709]
![image](https://user-images.githubusercontent.com/24671765/29202936-4daa5016-7e8a-11e7-8060-78ee2ee64c7c.png)

![image](https://user-images.githubusercontent.com/24671765/29202944-759462c4-7e8a-11e7-96aa-dcf481a85f87.png)

**Comment by HelioGuilherme66** [comment]
This project is not being actively maintained, so don't expect fixes soon.
From the version you show, you are using from a branch probably `wxPython3-compatibility`. When reporting you should mention where did you get RIDE (if not version 1.5.2.1). I would like to know what is the version of wxPython you are using, and also the operative system.

You could try to install from my [fork](https://github.com/HelioGuilherme66/RIDE/releases/tag/v1.7) and see if the problem still exists. Please see the wiki about possible problems.

**Comment by HelioGuilherme66** [comment]
Closed because (use OR operator):
- is too old,
- newest version should have it fixed,
- not reproducible,
- not an issue,
- is a question,
- lacks logs, versions info, e.t.c.,
- there is no other reason that justifies being opened.
