### ISSUE TITLE
RIDE on MAC unable to show keywords documentation

### ISSUE THREAD

**Issue by sshan-CS** [robotframework/RIDE#1710]
I installed
robotframework-ride (2.0a1)
robotframework (3.0.2)
pip 9.0.1
python 2.7
on my MAC Sierra 10.12 (16A323).

But I am unable to view keyword documentation by moving my mouse over and press Ctl.  There is a grey box,  but no text showing up.

**Comment by yoannbrault** [comment]
Can you please try ctrl + space ?

**Comment by HelioGuilherme66** [comment]
Closed because (use OR operator):
- is too old,
- newest version should have it fixed,
- not reproducible,
- not an issue,
- is a question,
- lacks logs, versions info, e.t.c.,
- there is no other reason that justifies being opened.
