### ISSUE TITLE
The configuration of RIDE is too difficult on MAC.  No help could be found.  My company decide to choose robotframework in the beginning,  but now we might need to give up.

### ISSUE THREAD

**Issue by sshan-CS** [robotframework/RIDE#1717]
The configuration of RIDE is too difficult on MAC.  No help could be found.  My company decide to choose robotframework in the beginning,  but now we might need to give up.

**Comment by HelioGuilherme66** [comment]
You are not really reporting an error with RIDE.
Your company can still use Robot Framework without RIDE. There are more test editors and runners out there.

**Comment by HelioGuilherme66** [comment]
Closed because (use OR operator):
- is too old,
- not reproducible,
- not an issue,
- is a question,
- lacks logs, versions info, e.t.c.,
- there is no other reason that justifies being opened.
