### ISSUE TITLE
when RIDE will support python3?

### ISSUE THREAD

**Issue by ruancan** [robotframework/RIDE#1719]
wxpython4.0 has been released. It supports python3.
robotFrameWork also supports python3.
Does RIDE have any plans?

**Comment by aray0322** [comment]
I also want konw.

**Comment by luisxiaomai** [comment]
Hope it can support python3 asap

**Comment by HelioGuilherme66** [comment]
You can experiment from my fork, with:
```
pip install -U --pre https://github.com/HelioGuilherme66/RIDE/archive/python3.zip
```

**Comment by akshaykochar** [comment]
Any update on when ride with python 3 support will get stable release?

**Comment by akshaykochar** [comment]
@HelioGuilherme66

**Comment by HelioGuilherme66** [comment]
@akshaykochar 
There is no official stable release (this project is more a less abandoned).
You can  **experiment** latest development branch from my fork with:
```
sudo -H pip3 install -U https://github.com/HelioGuilherme66/RIDE/archive/python3.zip
```

**Comment by edfacundo** [comment]
Hi, I loaded RIDE above but can not execute it. What is the command to launch the app?
Thanks, Ed

**Comment by HelioGuilherme66** [comment]
Try instead this one, it creates a desktop shortcut:
```
sudo -H pip3 install -U https://github.com/HelioGuilherme66/RIDE/archive/neweditor.zip
```

**Comment by edfacundo** [comment]
Thanks!
Here is the return,
[root@localhost /]# python -m robotide.__init__
Traceback (most recent call last):
  File "/root/anaconda3/lib/python3.6/runpy.py", line 183, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "/root/anaconda3/lib/python3.6/runpy.py", line 109, in _get_module_details
    __import__(pkg_name)
  File "/root/anaconda3/lib/python3.6/site-packages/robotide/__init__.py", line 35, in <module>
    from robotide.utils import basestring, unicode
  File "/root/anaconda3/lib/python3.6/site-packages/robotide/utils/__init__.py", line 28, in <module>
    from .eventhandler import RideEventHandler
  File "/root/anaconda3/lib/python3.6/site-packages/robotide/utils/eventhandler.py", line 15, in <module>
    import wx
ModuleNotFoundError: No module named 'wx'

I tried installing wx with no luck.

**Comment by HelioGuilherme66** [comment]
You need wxPython. I was assumng that you knew RIDE already (or seen the Wiki).
install with:
```
sudo -H python3 -m pip install wxPython
```
If it is a Mac or Windows, if not you get the wheel from wxpython.org

**Comment by HelioGuilherme66** [comment]
It is pretty obvious:
from pygments.lexer import Lexer
ModuleNotFoundError: No module named 'pygments'

Solve with:
```
sudo -H python3 -m pip install Pygments
```

**Comment by JoffreyN** [comment]
@HelioGuilherme66 ERROR!
"该文件没有与之关联的程序来执行该操作。请安装一个程序，或者，如果已安装程序，请在控制面板中默认程序中创建一个关联"
E:\Users\Joffrey\Downloads\robotframework-ride-1.5.2.1>ride.py
系统无法执行指定的程序。

how to fix it?

**Comment by JoffreyN** [comment]
@HelioGuilherme66 Thanks!

**Comment by HelioGuilherme66** [comment]
@JoffreyN 
Regarding my fork.
Well, for Python 2.7 you can use wxPython, 2.8.12.1, 3.02, 4.0.1, 4.0.2a1.
For Python 3.6 you can use wxPython,  4.0.1, 4.0.2a1.
See instructions fo [my latest pre-release](https://github.com/HelioGuilherme66/RIDE/releases/tag/v1.7.2)

**Comment by Anney-Ying** [comment]
@Hélio Guilherme 
I have update robotframework ride according with your  latest pre-release. 
I create my own Library,but import error,it is red. 
[ ERROR ] Error in file 'E:\Programs\Python36-32\Scripts\TestDobot\Init_Dobot.txt': Importing test library 'TestRF' failed: ModuleNotFoundError: No module named 'MyClass'
Traceback (most recent call last):
  File "e:\programs\python36-32\lib\site-packages\TestRF\__init__.py", line 1, in <module>
    from MyClass import Test
My scripts is simple:
![444](https://user-images.githubusercontent.com/32087022/42367241-22052904-8136-11e8-8c43-6803bfb51c2a.PNG)
![555](https://user-images.githubusercontent.com/32087022/42367294-491cf67a-8136-11e8-96da-bb22040cdb83.PNG)

It can run at the python2.6 .

**Comment by HelioGuilherme66** [comment]
@Anney-Ying Glad that you installed and use my pre-release, however, you should not use this Issue to report a different problem. Also you are not reporting a problem but asking for help, that should be done in different forums that you see [here](http://robotframework.org/#support). 
About your specific problem, you must know the differences of Python 2.6, 2.7 and >3.5, so the first thing is to make sure your script or module is running on Python 3.6.

**Comment by wjlu** [comment]
i have use this  
sudo -H pip3 install -U https://github.com/HelioGuilherme66/RIDE/archive/neweditor.zip

but there is no desktop shortcut ,how can i run it ? thanks

**Comment by HelioGuilherme66** [comment]
@wjlu That is an old branch.
You may try to install from my latest development branch:
```
sudo -H pip3 install -U https://github.com/HelioGuilherme66/RIDE/archive/gificons.zip
```
Or you should try the latest pre-release, see the instructions and warnings, [here](https://github.com/HelioGuilherme66/RIDE/releases/tag/v1.7.2)

Note: when using versions from my fork Issues or Pull Request should also be reported there!

**Comment by wangjianlian** [comment]
RobotFrameWork also supports python3
Does RIDE have any plans?

**Comment by wangjianlian** [comment]
Robot Framework 3.0.4+pyhon3.6.2+ ride1.72  is  astable

**Comment by wangjianlian** [comment]
Testsuit have defined Variable, Testsuit have ressource
Variable  come from ressource should be defined again
python2 RIDE is OK

**Comment by xuxk1** [comment]
> Testsuit已经定义了Variable，Testsuit有资源
> 变量来自资源应该再定义
> python2 RIDE就行了
> 
> 资源
> ![1](https://user-images.githubusercontent.com/42568284/44388453-ba894c80-a55a-11e8-96f5-6893ad4c9604.png)
> 
> Testsuit
> ![2](https://user-images.githubusercontent.com/42568284/44388517-da207500-a55a-11e8-957e-7738d2569cf6.png)
> 
> 跑
> ![3](https://user-images.githubusercontent.com/42568284/44388547-f15f6280-a55a-11e8-89b7-88c8a6285125.png)

你这个问题是你使用的变量出现歧义了，跟RIDE没有关系

**Comment by hyh162213** [comment]
> > Testsuit已经定义了Variable，Testsuit有资源
> > 变量来自资源应该再定义
> > python2 RIDE就行了
> > 资源
> > ![1](https://user-images.githubusercontent.com/42568284/44388453-ba894c80-a55a-11e8-96f5-6893ad4c9604.png)
> > Testsuit
> > ![2](https://user-images.githubusercontent.com/42568284/44388517-da207500-a55a-11e8-957e-7738d2569cf6.png)
> > 跑
> > ![3](https://user-images.githubusercontent.com/42568284/44388547-f15f6280-a55a-11e8-89b7-88c8a6285125.png)
> 
> 你这个问题是你使用的变量出现歧义了，跟RIDE没有关系

求教三个问题，从python2的ride到python3的ride才出现的
以下三个问题有任何解决思路吗，感激不尽！
![image](https://user-images.githubusercontent.com/46335731/51547047-74853b80-1ea0-11e9-973d-18d7c568ae67.png)
![image](https://user-images.githubusercontent.com/46335731/51547096-91217380-1ea0-11e9-81b3-01940aab59e5.png)

**Comment by HelioGuilherme66** [comment]
RIDE 1.7.3.1 supports Python 3 now.

**Comment by MrEthan** [comment]
> pybot

I miss the same problem too, have you solve it?

**Comment by MrEthan** [comment]
> 
> 
> @HelioGuilherme66 i install RIDE-release,but do not run
> error:
> command: "no pybot" --argumentfile C:\Users\admin\AppData\Local\Temp\RIDEuthk1lcb.d\argfile.txt --listener D:\python\lib\site-packages\robotide\contrib\testrunner\TestRunnerAgent.py:5259:False D:\robot_project\test
> [WinError 2] 系统找不到指定的文件。
> i do not how to solve it

I miss the same problem too, have you solve it? 
RIDE 1.7.4.2 running on Python 3.7.8.

**Comment by xuxk1** [comment]
You can refer to this blog.If you have any questions, you can contact me again
https://mp.weixin.qq.com/s/zTo4w33ZzBjiPMr6NkvTLw
------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "robotframework/RIDE"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年8月28日(星期五) 下午4:12
收件人:&nbsp;"robotframework/RIDE"<RIDE@noreply.github.com&gt;;
抄送:&nbsp;"冷风"<962199374@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;;
主题:&nbsp;Re: [robotframework/RIDE] when RIDE will support python3? (#1719)





  
@HelioGuilherme66 i install RIDE-release,but do not run
 error:
 command: "no pybot" --argumentfile C:\Users\admin\AppData\Local\Temp\RIDEuthk1lcb.d\argfile.txt --listener D:\python\lib\site-packages\robotide\contrib\testrunner\TestRunnerAgent.py:5259:False D:\robot_project\test
 [WinError 2] 系统找不到指定的文件。
 i do not how to solve it
  
I miss the same problem too, have you solve it?
 RIDE 1.7.4.2 running on Python 3.7.8.
