### ISSUE TITLE
need to be root to get all of ride functionality

### ISSUE THREAD

**Issue by jacree** [robotframework/RIDE#1724]
When I run ride.py, I have to sudo /path to ride in order to see the "File Edit Tools etc.." menu bar

Is there a setting where I can get the menu bar and not be root or is this an installation issue. Just recently started using ride. I also noticed I have ride 1.5.2 installed and I see critical bug issue 1577. Is this the issue I am seeing and need a patch?

**Comment by HelioGuilherme66** [comment]
First you don't say what is your Operating System. The issue #1577 has many changes and we cannot deduct what problem are you having.

Please post here the Tools->Log when you run as normal user.
Thanks.

**Comment by jacree** [comment]
Hi,

This issus has been resolved on my end. Thanks


________________________________
