### ISSUE TITLE
Question regarding the screenshot in the Test Runner Plugin wiki

### ISSUE THREAD

**Issue by jacree** [robotframework/RIDE#1725]
I'm trying to figure out how to get the center panel under "local tests" enabled or viewed from test runner plugin. I have the plugin enabled and I can run test from the hierarchical view on the left panel. I'm not seeing this center pane. Only the left one and the dynamic run panel on the far right. I want to be able to pick and choose what tests to run. I'm on linux ubuntu, python 2.7.12 (latest install) with ride 1.5.2.1

**Comment by HelioGuilherme66** [comment]
That central panel is very ancient and does not exist any more. It was integrated in the left (tree) panel.
I attach a screenshot where we can see selected tests, the Tools menu, and the Search Tags and Search Tests dialogs, which allows to select and unselect tests.
![imagem](https://user-images.githubusercontent.com/2866630/31102974-7957917c-a7cc-11e7-87f6-bacc4d244821.png)

**Comment by HelioGuilherme66** [comment]
Explained that the use or look on newer version is not as screenshot shows.
