### ISSUE TITLE
RIDE 1.5.2.1 on Ubuntu 16.04 got Error: Tcl_AsyncDelete: async handler deleted by the wrong thread

### ISSUE THREAD

**Issue by ZDabrowski** [robotframework/RIDE#1726]
From time to time, RIDE experiences an error: "Tcl_AsyncDelete: async handler deleted by the wrong thread" during working on project. 
Issue occurs after performing general user operations: loading test with user libraries, add/remove/change name of keywords from tests/resources, change tag name. 

Environment:
Ubuntu 16.04
RIDE: 1.5.2.1
wxPython: 2.8.12.1
Python 2.7.12
python-tk: 2.7.11-2
robotframework: 3.0.2

**Comment by HelioGuilherme66** [comment]
Probably not relevant, one year or more later. If still reproducible, reopen with more information.
