### ISSUE TITLE
question windows10 ver 1703, os distinction error & etc.

### ISSUE THREAD

**Issue by bareum** [robotframework/RIDE#1727]
I use Python 2.7. In the meantime, when using ride on Windows 7, it worked fine without any problem, but it is difficult to run ride after installing Windows 10 with VHD.
Once you get a 0xc0000142 error in cmd, you will see the Windows version in the kernel version, and Windows 10 will continue to be Windows 8 on the ride.
How do I resolve this error?
Windows 10 I use is version 1703.

When you solve one problem, there are other problems. Help.

**Comment by HelioGuilherme66** [comment]
Closed because (use OR operator):
- is too old,
- not reproducible,
- not an issue,
- is a question,
- lacks logs, versions info, e.t.c.,
- there is no other reason that justifies being opened.
