### ISSUE TITLE
Power function ** bug: negative result

### ISSUE THREAD

**Issue by eniemela3** [robotframework/RIDE#1729]
I believe this is not the intended functionality of "**", at least it does not match to how it works in Python. Please see below

Calculation       
                             ${value}=          Set Variable     -3
                             ${result}=         Evaluate            ${value}**2
                             Log To Console                            ${result}

Print:
-9

Should have returned +9.

**Comment by HelioGuilherme66** [comment]
Yes I can confirm that behaviour. Here is a complete test case:
```
*** Test Cases ***
Calculation
    ${value}=    Set Variable    -3
    ${result}=    Evaluate    ${value}**2
    Log To Console    ${result}
    # Using Math
    ${value}=    Set Variable    ${-3}
    ${result}=    Evaluate    pow(${value},2)    math
    Log To Console    ${result}
```
And the corresponding output:
```
Starting test: Test Power.Calculation
20171103 14:43:04.005 :  INFO : ${value} = -3
20171103 14:43:04.017 :  INFO : ${result} = -9
20171103 14:43:04.030 :  INFO : ${value} = -3
20171103 14:43:04.036 :  INFO : ${result} = 9
Ending test:   Test Power.Calculation
```

However, this is not a RIDE bug. Please open an Issue on the Robot Framework project.

**Comment by pekkaklarck** [comment]
That seems to be how `eval` in Python works:

```python

**Comment by eniemela3** [comment]
I completely understand Pekka's explanation, but how can I make sure that a negative value stored into a _variable_ in my robot script will return a positive result when squared? Trying this out in python:
~~~~
Python 3.6.2 (v3.6.2:5fd33b5, Jul  8 2017, 04:14:34) [MSC v.1900 32 bit (Intel)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> var = -3
>>> var**2
9

**Comment by pekkaklarck** [comment]
This is all about operator precedence. Python evaluates `-3 ** 2` as `-(3 ** 2)` which obviously yields `-9`.
