### ISSUE TITLE
TELNET - terminal_emulation does not work

### ISSUE THREAD

**Issue by BenjiRyan** [robotframework/RIDE#1730]
![image](https://user-images.githubusercontent.com/33459831/32503525-b3b99360-c3dd-11e7-8b32-7bea7652d7dd.png)

I want to open a Telnet-Connection process the output in a virtual screen with Telnet "Terminal emulation". But every time I get this TypeError. But I never use the (unexpected) keyword argument 'encodings'

Can someone help me?

**Comment by BenjiRyan** [comment]
Please help me :(

**Comment by BenjiRyan** [comment]
Wäre schön, wenn mir jemand helfen kann :)

**Comment by HelioGuilherme66** [comment]
This is not a RIDE problem!

Looks like a `pyte` library problem.

Please use other methods to ask for help. For example, StackExchange, StackOverflow, Slack, Google Groups. 

See [robotframework.org](http://robotframework.org) support pages.

**Comment by pekkaklarck** [comment]
Yeah, this is not RIDE issue. Robot Framework itself has its own tracker and this is already reported as robotframework/robotframework#2693.

**Comment by BenjiRyan** [comment]
Thank you Guys :)
