### ISSUE TITLE
Some resources are red (RIDE 1.5.2.1 , Robot Framework 3.0.2 , Windows 7)

### ISSUE THREAD

**Issue by adikellerjobs** [robotframework/RIDE#1731]
Hi guys,
I use RIDE 1.5.2.1 running on Python 2.7.10. and run Robot Framework 3.0.2 on Windows 7.
I create a new script (see below) which contain 4 Resources, the first two are blue (in RIDE GUI) and the others are red.
All files exist in the same path, so why two of them marked in red?
Thanks

		*** Settings ***
		Force Tags        Critical    template    Conf=3    isTor=0    isSanity=0    headless    rcmd
		Library           Collections
		Library           BeAm.beacon.stress_tests
		Resource          ../../../BeAm/beacon/local_settings.txt
		Resource          ../../../BeAm/beacon/settings.txt
		Resource          ../../../BeAm/beacon/stress_tests.py
		Resource          ../../../BeAm/beacon/tests.py

		*** Test Cases ***
		Create Test Object
			[Tags]    must
			${TEST} =    BeaconTesting.Get Beacon Test    3
			Set Suite Variable    ${TEST}    ${TEST}

		Prepare Beacon Server
			[Tags]    prpr
			BeaconTesting.Change Mss Value    ${None}
			BeaconTesting.Prepare Server    ${TEST}

		Beacon Stoarm
			[Tags]    stress
			StressWorkers    ${TEST}

**Comment by HelioGuilherme66** [comment]
Python files are not Resources, so they appear in red. Move them to the Library section.

(If you find this fixed, please close this Issue. Thanks)

**Comment by adikellerjobs** [comment]
Thanks for the focal answer.
