### ISSUE TITLE
Python.exe has stopped woking when running ride.py

### ISSUE THREAD

**Issue by hoctester** [robotframework/RIDE#1732]
I using win 10 and python 2.7.7 

![image_720](https://user-images.githubusercontent.com/6380590/33168505-bd07f32e-d073-11e7-8b5e-38a6cac93d27.png)

**Comment by sujitdhamale** [comment]
i am also getting same error

**Comment by HelioGuilherme66** [comment]
Probably not relevant, one year or more later. If still reproducible, reopen with more information.
