### ISSUE TITLE
The ride couldn't run  wxpython 4.0.0b2 edition on python2.7 ???

### ISSUE THREAD

**Issue by jekoie** [robotframework/RIDE#1734]
The ride could run wxpython 4.0.0b2 edition on python2.7 ???
Could anyone can help me???

**Comment by jekoie** [comment]
The ride could not  run wxpython 4.0.0b2 edition on python2.7 ???
Could anyone can help me???

**Comment by HelioGuilherme66** [comment]
You can **try** to use from my fork at [Releases](https://github.com/HelioGuilherme66/RIDE/releases)

You can also **experiment** latest development branch with:
```
sudo -H pip install -U https://github.com/HelioGuilherme66/RIDE/archive/python3.zip
```

**Comment by jekoie** [comment]
it is work fine. 3Q very much.
