### ISSUE TITLE
Ride supported platform

### ISSUE THREAD

**Issue by github-rajeshkumar** [robotframework/RIDE#1735]
Request you to provide information on what Python and wxPython versions are required for RIDE 1.5.2.1? Thanks!

**Comment by 0xLeon** [comment]
RIDE only works with Python 2 and wxPython 2.8.12.1 with Unicode support, as you can read in the [Wiki pages](https://github.com/robotframework/RIDE/wiki/Installation-Instructions). There is a fork at HelioGuilherme66/RIDE@python3 supporting Python 3 and wxpython 4, but it's still pretty unstable.

**Comment by HelioGuilherme66** [comment]
Closed because (use OR operator):
- is too old,
- newest version should have it fixed,
- not reproducible,
- not an issue,
- is a question,
- lacks logs, versions info, e.t.c.,
- there is no other reason that justifies being opened.

(thanks @Nyral for validating)
