### ISSUE TITLE
[ ERROR ] File not Found. message reported at beginning of test execution but tests complete ok

### ISSUE THREAD

**Issue by malbertone** [robotframework/RIDE#1736]
RIDE 1.5.2.1 running on Python 2.7.10
Hi, I'm brand new on this Forum, so apologize if not providing enough information on the subject.
Have this issue with my RIDE execution, the GUI opens up fine and can run tests successfully, but my log session reports at the very beginning the error in the subject:
[ ERROR ] File not Found.

Log session shows:
command: pybot.bat -v hss-hip:10.15.172.143 -v local_ip:151.98.193.6 -v sess_var:12341;4532 -v IP_SM:10.15.172.147 -v RAMMBOCK_HOME:C:\DCE_Auto\Robot_Projects\Rammbock-HSS1.9\Rammbock-HSS1.9 --argumentfile c:\users\malberto\appdata\local\temp\RIDEdju5hl.d\argfile.txt --listener C:\Python27\lib\site-packages\robotide\contrib\testrunner\TestRunnerAgent.py:9455:False C:\DCE_Auto\Robot_Projects\spstests.18.0\spstests
=============================================================================================
Spstests                                                                                     
=============================================================================================

[ ERROR ] File not Found.
Spstests.Service Manager                                                                     
=============================================================================================
Spstests.Service Manager.Policy and Charging Configuration                                   
=============================================================================================
Spstests.Service Manager.Policy and Charging Configuration.15 Units Mapping :: Units and C...
...

The text edit reports:

*** Settings ***
Documentation     Units and Conversions entity tests
...               Author(s): Bhagyashree Swain
Library           RobotSPS
Variables         ../../variables.yaml

*** Test Cases ***
Create Unit
    ${typeConv}    Create TypeConverter Json    rightSideValue=65    rightSideUnit=Money    leftSideValue=1
    ${response}    Create Unit SM    defaultSMUnit=False    unitTypeName=Dollar    typeConverter=${typeConv}    kindOfUnit=MONEY    shortName=dollar
    ...    defaultUnit=False
    Verify Rest Response Code    ${response}    201
    Verify Rest Response Message    ${response}    Success
    ${respCreate}    Get Unit SM    unitTypeName=Dollar
    Log    ${respCreate}
    ${name}    Get Value From Response    ${respCreate}    [unitTypeName]
    Should Be Equal    Dollar    ${name}
    ${state}    Get Value From Response    ${respCreate}    [smProvState]
    Should Be Equal    NEW    ${state}
    ${unit}    Get Value From Response    ${respCreate}    [kindOfUnit]
    Should Be Equal    MONEY    ${unit}
...

Not sure which file is being looked for, since the overall execution seems to complete successfully.
Let me know if/how to provide more useful information.
Attaching one of the test cases, but the issue seems to be common to many if not all.
[testcase.txt](https://github.com/robotframework/RIDE/files/1702721/testcase.txt)

Thanks in advance!

Mike

**Comment by malbertone** [comment]
Adding also that when looking at the report, can see the issue is reported within the initial test suite configuration:

Documentation:
:param config_file: Provide path of variables.yaml file

Start / End / Elapsed:
20180207 14:26:20.969 / 20180207 14:26:21.007 / 00:00:00.038 

14:26:21.007 ERROR File not Found. 

But not really familiar with which configuration to check, thanks!
Mike

**Comment by HelioGuilherme66** [comment]
@malbertone What is the status of this? Looks like a problem on your side. (one year after probably does not make sense now :) )

**Comment by HelioGuilherme66** [comment]
Closed because (use OR operator):
- is too old,
- newest version should have it fixed,
- not reproducible,
- not an issue,
- is a question,
- lacks logs, versions info, e.t.c.,
- there is no other reason that justifies being opened.

(thanks @Nyral for validating)
