### ISSUE TITLE
'pybot.bat' is not recognized as an internal or external command,

### ISSUE THREAD

**Issue by ghousethanedar** [robotframework/RIDE#1740]
its showing as 'pybot.bat' is not recognized as an internal or external command, when I am trying to run a test case please help

**Comment by bhajojo** [comment]
Please add the location of punit.bat to environment variable

**Comment by bhajojo** [comment]
Please add path to python.bat to environment variable path if working on Windows

If working on mac add the path to bash profile

**Comment by ghousethanedar** [comment]
how can i find the location of python.bat file in my windows10

**Comment by bhajojo** [comment]
C:/python27/scripts

**Comment by ghousethanedar** [comment]
there is  no such file python.bat in C:/python27/scripts what to do please help

**Comment by bhajojo** [comment]
My bad...File name is pybot.bat

**Comment by ghousethanedar** [comment]
file ,is there then what to do next

**Comment by ghousethanedar** [comment]
thank you very much problem solved
thanks.

**Comment by HelioGuilherme66** [comment]
@ghousethanedar Please close this issue. Thanks.

**Comment by wjiang100** [comment]
issue on latest 3.1.1.

there is  no c:\python27\Scripts\pybot.bat 


C:\Python27>pip install robotframework
Collecting robotframework
  Downloading https://files.pythonhosted.org/packages/36/c6/6f89c80ac5a526a091bd383ffdfc64c9a68d9df0c775d4b36f03d8e0ac25/robotframework-3.1.1-py2.py3-none-any.whl (601kB)
    100% |UUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUU| 604kB 994kB/s
Installing collected packages: robotframework
Successfully installed robotframework-3.1.1

C:\Python27>pybot
'pybot' is not recognized as an internal or external command,
operable program or batch file.

C:\Python27>dir Scripts\pybo*
 Volume in drive C is OSDISK
 Volume Serial Number is xxxx

 Directory of C:\Python27\Scripts

File Not Found

C:\Python27>

then had to created it manually:

c:\python27\Scripts\pybot.bat:

@echo off
python -m robot.run %*

**Comment by mahmoudhabab** [comment]
I'm new to python and when installing it it is missing pybot , Can you please advise how to install it ?

I Installed ( python-3.7.2-amd64 ) to ( Win 10 64 bit )
then added both Python paths to environment variables :
C:\Users\(username)\AppData\Local\Programs\Python\Python37\
C:\Users\(username)\AppData\Local\Programs\Python\Python37\Scripts

then i installed Robot Framework using command ( pip install robotframework )
python --version
Python 3.7.2
robot --version
Robot Framework 3.1.1 (Python 3.7.2 on win32)
pip --version
pip 19.0.1 from c:\users\(username)\appdata\local\programs\python\python37\lib\site-packages\pip (python 3.7)

pybot --version

'pybot' is not recognized as an internal or external command,
operable program or batch file.


In the installation steps , after i ensure pybot is installed i should also complete installation of 
wxpython
pip install robotframework-ride

Shall i proceed , or ensure pybot installed as a pre-requisite ?

**Comment by Ramarajulu** [comment]
> I'm new to python and when installing it it is missing pybot , Can you please advise how to install it ?
> 
> I Installed ( python-3.7.2-amd64 ) to ( Win 10 64 bit )
> then added both Python paths to environment variables :
> C:\Users(username)\AppData\Local\Programs\Python\Python37
> C:\Users(username)\AppData\Local\Programs\Python\Python37\Scripts
> 
> then i installed Robot Framework using command ( pip install robotframework )
> python --version
> Python 3.7.2
> robot --version
> Robot Framework 3.1.1 (Python 3.7.2 on win32)
> pip --version
> pip 19.0.1 from c:\users(username)\appdata\local\programs\python\python37\lib\site-packages\pip (python 3.7)
> 
> pybot --version
> 
> 'pybot' is not recognized as an internal or external command,
> operable program or batch file.
> 
> In the installation steps , after i ensure pybot is installed i should also complete installation of
> wxpython
> pip install robotframework-ride
> 
> Shall i proceed , or ensure pybot installed as a pre-requisite ?

pybot is same as rebot(i am not sure)..try rebot --version...and use python version 2.7.14 to make ride working

**Comment by mahmoudhabab** [comment]
Thanks Ramarajulu for your reply
What i did ( as i was stuck ) , I Continue installation for both ( wxpython ,,,,, pip install robotframework-ride )
And Ignored pybot for now

Ride is working now , however pybot is not installed
Will continue with Ride till i have  any issue related to pybot

Thanks ,,,

**Comment by vickyeee861** [comment]
Hi, Please someone can help me, i have installed RIDE and created some test cases, which are the testcases have been ran i got an error.  if am running via command line to using "pybot RobotAutomation.robot" this command everything is working fine.  but am running via RIDE got an error.  please find the error log and give me the valuable solution . 

File "C:\Python27\lib\site-packages\robot\utils\application.py", line 83, in _execute
    rc = self.main(arguments, **options)
  File "C:\Python27\lib\site-packages\robot\run.py", line 431, in main
    suite.configure(**settings.suite_config)
  File "C:\Python27\lib\site-packages\robot\running\model.py", line 141, in configure
    model.TestSuite.configure(self, **options)
  File "C:\Python27\lib\site-packages\robot\model\testsuite.py", line 160, in configure
    self.visit(SuiteConfigurer(**options))
  File "C:\Python27\lib\site-packages\robot\model\testsuite.py", line 168, in visit
    visitor.visit_suite(self)
  File "C:\Python27\lib\site-packages\robot\model\configurer.py", line 47, in visit_suite
    self._filter(suite)
  File "C:\Python27\lib\site-packages\robot\model\configurer.py", line 61, in _filter
    self.include_tags, self.exclude_tags)
  File "C:\Python27\lib\site-packages\robot\model\testsuite.py", line 145, in filter
    included_tags, excluded_tags))
  File "C:\Python27\lib\site-packages\robot\model\filter.py", line 41, in __init__
    self.include_tests = include_tests
  File "C:\Python27\lib\site-packages\robot\utils\setter.py", line 35, in __set__
    setattr(instance, self.attr_name, self.method(instance, value))
  File "C:\Python27\lib\site-packages\robot\model\filter.py", line 53, in include_tests
    if not isinstance(tests, TestNamePatterns) else tests
  File "C:\Python27\lib\site-packages\robot\model\namepatterns.py", line 23, in __init__
    self._matcher = MultiMatcher(patterns, ignore='_')
  File "C:\Python27\lib\site-packages\robot\utils\match.py", line 67, in __init__
    for pattern in self._ensure_list(patterns)]
  File "C:\Python27\lib\site-packages\robot\utils\match.py", line 42, in __init__
    self._regexp = self._compile(self._normalize(pattern), regexp=regexp)
  File "C:\Python27\lib\site-packages\robot\utils\match.py", line 50, in _compile
    return re.compile(pattern, re.DOTALL)
  File "C:\Python27\lib\re.py", line 194, in compile
    return _compile(pattern, flags)
  File "C:\Python27\lib\re.py", line 251, in _compile
    raise error, v # invalid expression
  

Thanks,,

**Comment by Deepak-bit-ui** [comment]
hi instead of pybot use robot

**Comment by HelioGuilherme66** [comment]
@Deepak-bit-ui Thanks for answering to last comment on on Mar 27, 2019.

I am locking this now :)
