### ISSUE TITLE
Rename Test Suite always give Validation Error: Filename contains illegal characters

### ISSUE THREAD

**Issue by Idarab** [robotframework/RIDE#1741]
Ride 1.5.2.1
Robot Framework 3.0.2
python 2.7.14

When trying to rename a test suite in project tree the Validation Error occures, unless the name stays the same.

**Comment by Nyral** [comment]
@HelioGuilherme66 I get this too (on Windows 10).

**Comment by HelioGuilherme66** [comment]
Hopefully it is fixed. At least tested on Windows 10 with Python 3.7.4 on current master.

**Comment by ssaakkiii** [comment]
Me too！
