### ISSUE TITLE
test cases are stopped running when running continuously for many times. Only working for 1st run on opening RIDE. Note: Test cases are running on command prompt at anytime

### ISSUE THREAD

**Issue by MatrixAutomation** [robotframework/RIDE#1742]

**Comment by Nyral** [comment]
@MatrixAutomation Uncheck Show Message window before starting test execution.

![image](https://user-images.githubusercontent.com/39315668/58752507-75feea00-84b8-11e9-9ec2-e055a67031a3.png)

Does it still occur?

**Comment by HelioGuilherme66** [comment]
Closing because is too old and we cannot reproduce, or lack of information.
