### ISSUE TITLE
Library、Resource、Variables、Import Failed Help、Add Scalar、Add List、Add Dict buttons are not displayed.

### ISSUE THREAD

**Issue by vdingjiale** [robotframework/RIDE#1744]
RIDE 1.5.2.1 running on Python 2.7.12. 
ThinkPad T410 Windows 10 system
Library、Resource、Variables、Import Failed Help、Add Scalar、Add List、Add Dict buttons are not displayed.
<img width="960" alt="screen shot" src="https://user-images.githubusercontent.com/38714213/39228220-7d316fa4-484c-11e8-9d6a-2504b9cedcf6.png">

**Comment by HelioGuilherme66** [comment]
That problem still happens on my fork from this project (that panel code did not had changes).
You will get the buttons OK, if you shrink the Settings section, by just clicking the button.

The code can be improved by hiding the Import, Variables and Metadata when the Settings are expanded.

**Comment by jnhyperion** [comment]
Issue has been fixed in latest version.
