### ISSUE TITLE
how to debug a testcase?

### ISSUE THREAD

**Issue by wxl1989beyond** [robotframework/RIDE#1745]
'To set a break point add a new line above the problematic keyword use this "Comment | PAUSE" When the test case is started it will run normally until it hits the special Comment. Then you can use the Continue, Next and Step over buttons on the Run tab. '

how to user  "Comment | PAUSE" ,  it seems not work.

Input Text	name=email	11@11.com
Comment | PAUSE		
Input Password	name=password	123

**Comment by HelioGuilherme66** [comment]
@wxl1989beyond 
The '|' (pipe) was used to separate the command from the argument. If you are not using pipe separated format, jut remove it.
So this command will work (using 4 spaces):
```
Comment    PAUSE    # Note that in my fork a text starting with any variant of PAUSE will work 
```

**Comment by wxl1989beyond** [comment]
@HelioGuilherme66 
thanks .  the testcase  seems  pause at  break point.  but  Continue, Next and Step over buttons on the Run tab is  also  grey?
![image](https://user-images.githubusercontent.com/8497281/39412678-b8f8576e-4c52-11e8-894e-dbd76d91dfd7.png)

**Comment by HelioGuilherme66** [comment]
And I see in your previous screenshot, that the Log and Report buttons are grayed. This usually happens when running SeleniumLibrary tests and the webdriver is running in the background. Maybe this problem is related. (If that happens try to kill the chromedriver or geckodriver process).

**Comment by wxl1989beyond** [comment]
@Linhan-Shenzhen    
我用的python 2.7.14 , robotframework 3.0.2, RIDE 1.5.2.1 ， 可能是你的版本太低。  还是就是注意看下浏览器的驱动进程要杀掉， 例如chromedriver.exe

**Comment by HelioGuilherme66** [comment]
@wxl1989beyond This is your message translated with Google:

> I use python 2.7.14, robotframework 3.0.2, RIDE 1.5.2.1, may be your version is too low. Note that the browser is still a look of drive to kill the process, for example chromedriver.exe

**Comment by simplyviks** [comment]
it doesn't works for custom Scripts runner. 

i am trying to run test cases using a custom script that internally calls maven robot framework plugin to call java keywords.

**Comment by HelioGuilherme66** [comment]
Closed because (use OR operator):
- is too old,
- newest version should have it fixed,
- not reproducible,
- not an issue,
- is a question,
- lacks logs, versions info, e.t.c.,
- there is no other reason that justifies being opened.
