### ISSUE TITLE
RIDE-1.7.2 the Simplified-Chinese displayed problem 

### ISSUE THREAD

**Issue by Linhan-Shenzhen** [robotframework/RIDE#1747]
the Simplified-Chinese only in the middle frame displayed the incorrect coding 
![default](https://user-images.githubusercontent.com/38828352/39439329-cd146fd0-4cd9-11e8-8688-87cee0251458.png)

**Comment by HelioGuilherme66** [comment]
There is no easy solution for that. Those are the outputs of Robot.
@pekkaklarck Do you know anything about outputting Chinese characters (Test Cases names)?
I did try to set `chcp 936` but the output is similar (question marks in my case).
Here is a small example file:
```
*** Test Cases ***
simplified Chinese: 汉语
    Log To Console    This to Console simplified Chinese: 汉语;
    Log    This is normal log: simplified Chinese: 汉语;

```

**Comment by zhujunling-nj** [comment]
I have a similar problem. The test suite or test case in Chinese does not display at all.
I fixed this problem by modifying the _Lib/site-packages/robotide/contrib/testrunner/testrunner.py_ file.
![fixed](https://user-images.githubusercontent.com/26447863/39795243-638933b2-5381-11e8-897e-dde2803925b5.PNG)

**Comment by HelioGuilherme66** [comment]
@zhujunling-nj Your fix did not work for me. I see ??, instead of the characters. Are you using the same version of the code? (1.5.2.1)
What is the code page of your windows console? Output of `chcp`. Thanks.

**Comment by zhujunling-nj** [comment]
The version of python is 2.7.15
Theversion of wxPython is  wxPython2.8-win64-unicode-2.8.12.1-py27
The version of robotframework-ride is 1.5.2.1
The code page of winsows is cp 936
The encoding of robot file is utf-8

What is the output of the sys.getfilesystemencoding() in python.
In my host the output is 'mbcs'.

**Comment by hyh162213** [comment]
> I have a similar problem. The test suite or test case in Chinese does not display at all.
> I fixed this problem by modifying the _Lib/site-packages/robotide/contrib/testrunner/testrunner.py_ file.
> 
> ![fixed](https://user-images.githubusercontent.com/26447863/39795243-638933b2-5381-11e8-897e-dde2803925b5.PNG)

![image](https://user-images.githubusercontent.com/46335731/51545652-5ec24700-1e9d-11e9-8493-6611ef0754b6.png)
大神，按你的改法报错了，我的也是ride在用例执行结果显示的汉字是乱码

**Comment by zhujunling-nj** [comment]
@hyh162213 报措是可能是因为代码缩进没对齐，缩进最好统一用空格，不要用Tab

**Comment by hyh162213** [comment]
> @hyh162213 报措是可能是因为代码缩进没对齐，缩进最好统一用空格，不要用Tab

报错真的是空格的原因...我以后一定牢记。
但是按照上述方法修改了会引入新的问题，用例在执行完之后不会出结果，一直显示还在执行。
因为没有结果所以我也不知道乱码修复了没有...
我的电脑是win10x64，python3.7，rf3.1.1，rf-ride1.7.3.1
您知道是怎么回事么

**Comment by zhujunling-nj** [comment]
For the version 1.7.3.1,  modifying the Lib/site-packages/robotide/contrib/testrunner/testrunner.py file.
![default](https://user-images.githubusercontent.com/26447863/51646960-c66bb580-1fb5-11e9-82d5-91cf9f9d6ec3.PNG)
The author uses "latin1" to encode the output of robot in widows system, which is not suitable for Asian language. It is modified to "mbcs" code and automatically adapts to the code page settings of windows.
Expect the author to fix this bug in the next release.

**Comment by hyh162213** [comment]
> For the version 1.7.3.1, modifying the Lib/site-packages/robotide/contrib/testrunner/testrunner.py file.
> ![default](https://user-images.githubusercontent.com/26447863/51646960-c66bb580-1fb5-11e9-82d5-91cf9f9d6ec3.PNG)
> The author uses "latin1" to encode the output of robot in widows system, which is not suitable for Asian language. It is modified to "mbcs" code and automatically adapts to the code page settings of windows.
> Expect the author to fix this bug in the next release.

It works！Thank you so much.
Hope some day I can just be good like you.

**Comment by testwjz** [comment]
![image](https://user-images.githubusercontent.com/32086135/59481205-eda81e00-8e95-11e9-9d7f-f2892cff6eed.png)
