### ISSUE TITLE
TortoiseSVN integration issue with RIDE

### ISSUE THREAD

**Issue by RajivKumarVA** [robotframework/RIDE#1748]
Hi Team,

Getting the error:
**This is the error we got trying to execute TortoiseSVN executable file:
"The system cannot find the file specified"
Probably this file is not in your PATH. Try to reinstall TortoiseSVN.
Do you want to open the download page?**

RIDE 1.5.2.1 running along with Python 2.7.14
TortoiseSVN version 1.9.7.27907 is installed.

Though added C:\Program Files\TortoiseSVN\bin in PATH for System Variables, facing the problem.

What could be the issue?

**Comment by Nyral** [comment]
@RajivKumarVA Can you provide a test as example for us to reproduce the issue?

**Comment by HelioGuilherme66** [comment]
Closing because is too old and we cannot reproduce, or lack of information.
