### ISSUE TITLE
Extra 'a' added in pybot command

### ISSUE THREAD

**Issue by nkuruvil** [robotframework/RIDE#1750]
When running tests on RIDE, the command comes out as "pybot a --argumentfile..." as displayed in the run plugin, and the test fails with the result of unexpected error: [ ERROR ] Parsing 'a' failed: Data source does not exist.
When testing it manually on the terminal, keeping 'a' repeats the error, while removing 'a' allows the test to run normally. How do I remove 'a' when running robot from RIDE?

**Comment by HelioGuilherme66** [comment]
Although my version of RIDE is different from yours, to reproduce your problem I had to provoke it by adding an 'a' to the `robot`arguments. So, you just have to delete that 'a' from the Arguments field.
Here is my example:
![imagem](https://user-images.githubusercontent.com/2866630/40392142-8650ef5c-5e12-11e8-95d7-e200869130f3.png)

Please close this issue if there is no problem with RIDE.

**Comment by HelioGuilherme66** [comment]
How to fix documented
