### ISSUE TITLE
logs file are getting overwrite after each execution

### ISSUE THREAD

**Issue by rinchentundup** [robotframework/RIDE#1752]
Each time test case is executed, it generate the log file with the same name. So we are not able to see the logs and results of previous executions. Is there any way that previous logs are preserved ?

1st time execution:-

Deletion failed
SCRIPT ENDS HERE' does not contain 'Deletion Successful'
------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
RobotAutomation 4 | FAIL |
1 critical test, 0 passed, 1 failed
1 test total, 0 passed, 1 failed
============================================================================================================================================================================================================
Output: /tmp/RIDEFYKv7_.d/output.xml
Log: /tmp/RIDEFYKv7_.d/log.html
Report: /tmp/RIDEFYKv7_.d/report.html

test finished 20180503 07:53:28

2nd Time execution:-

Deletion failed
SCRIPT ENDS HERE' does not contain 'Deletion Successful'
----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
RobotAutomation 4 | FAIL |
1 critical test, 0 passed, 1 failed
1 test total, 0 passed, 1 failed
==========================================================================================================================================================================================================
Output: /tmp/RIDEFYKv7_.d/output.xml
Log: /tmp/RIDEFYKv7_.d/log.html
Report: /tmp/RIDEFYKv7_.d/report.html

test finished 20180503 10:05:22

[root@Robot RIDEFYKv7_.d]# ls -lrth
total 640K
rw-rr- 1 root root 205K May 3 10:04 1st_time_log.html
rw-rr- 1 root root 104 May 3 10:04 argfile.txt
rw-rr- 1 root root 9.4K May 3 10:05 output.xml
rw-rr- 1 root root 205K May 3 10:05 log.html
rw-rr- 1 root root 207K May 3 10:05 report.html
[root@Robot RIDEFYKv7_.d]# diff log.html 1st_time_log.html | wc -l
20
[root@Robot RIDEFYKv7_.d]#

Thus track of old execution is lost. In Automation framework, track record must be maintained for each execution

**Comment by Nyral** [comment]
@HelioGuilherme66 We could make an option to add timestamp or something like that.

**Comment by HelioGuilherme66** [comment]
@rinchentundup The solution for this problem can be solved by using `-d` option in arguments (since v1.7.4b2). See question number 4 in our [FAQ](https://github.com/robotframework/RIDE/wiki/F.A.Q.)
