### ISSUE TITLE
Index problem using "List Windows" on IE 

### ISSUE THREAD

**Issue by houesmalek** [robotframework/RIDE#1753]
Hello everyone, 

I'm working on RIDE and I'm facing a weired problem. I am making a test that opens a pop up and verifies its contain. This works perfectly with Firefox. However, when I make the exact same test on IE, I've got this message "IndexError: list index out of range". He only sees one window open (the first one) even if it is well synchronized as in Firefox (I didn't change anything)

Can you help please?

Thank you,
Malek

**Comment by HelioGuilherme66** [comment]
Closed because (use OR operator):
- is too old,
- newest version should have it fixed,
- not reproducible,
- not an issue,
- is a question,
- lacks logs, versions info, e.t.c.,
- there is no other reason that justifies being opened.

(thanks @Nyral for validating)
