### ISSUE TITLE
__all__ is not working in ride and displays the listner function as well

### ISSUE THREAD

**Issue by p74** [robotframework/RIDE#1754]
import

__all__ = ['a', 'b']

class ab:

    ROBOT_LIBRARY_SCOPE = 'TEST SUITE'
    ROBOT_LISTENER_API_VERSION = 2

    def __init__(self):
        bla

    def start_suite(self, data, result):
       some stuff
   
    def a():
        some stuff
 
    def b():
       some stuff
    
    def _c():
        some stuff

When i click in ride search keywords and select the library 
then the listener function is displayed as well and the "private" function c not
but i expect that the listener function is not displayed as well
(i did restart ride to make sure an inport is done)
or do I something wrong here? I use __ before and after all but it will not display here

thx

**Comment by HelioGuilherme66** [comment]
@p74 If you edit the text to be in a code block, there will not be changes on what you write. Please try to create a functional python code (paste the file content), for we be able to reproduce your problem. You mention the listener `__all__` but to me it looks like a list variable.

**Comment by p74** [comment]
The listener function is the function start_suite, and is called during the init of a suite.
see manual
http://robotframework.org/robotframework/latest/RobotFrameworkUserGuide.html#listener-interface

but i expect that only functions that are listed in __all__ are displayed 

code:

``from robot.libraries.BuiltIn import BuiltIn
from robot.api.logger import info, warn, error

__all__ = ['a', 'b']

class ab:

    ROBOT_LIBRARY_SCOPE = 'TEST SUITE'
    ROBOT_LISTENER_API_VERSION = 2

    def __init__(self):
        warn('init')

    def start_suite(self, data, result):
        warn('Listner')

    def a():
        warn('a')

    def b():
        warn('b')

    def _c():
        warn('c')

**Comment by HelioGuilherme66** [comment]
Thanks for the edit.
(I added `self` to a, b and _c functions)
This is the log output:
```
Starting test: Test Ab.test keywords
20180606 14:41:25.688 :  WARN : Listner
20180606 14:41:25.689 :  WARN : a
20180606 14:41:25.691 :  WARN : b
20180606 14:41:25.693 :  FAIL : 
No keyword with name 'ab._c' found. Did you mean:
    ab.B
    ab.A
Ending test:   Test Ab.test keywords
```
I was expecting to get the`_c` keyword, even if not in the `__all__` statement, because python does not really hide those functions. Looks like robot API is doing that for us. I do not see any other way to hide keywords.
(From RIDE side, the keywords detection is done using a copy of robot.library, so it gets what robot sends as valid.)
Maybe @pekkaklarck can say more about this.

For completeness, here is the test:
```
*** Settings ***
Library           ab.py

*** Test Cases ***
test keywords
    ab.Start Suite    this is data    result
    ab.a
    ab.b
    ab._c
```

**Comment by p74** [comment]
as _c is a kind of "private" function (you can discuss) i can understand that i can not call it and that it is blocked, that is for me perfect. but i expect also that i can not call listener functions as well. maybe its an idea that we have the possibility to block functions by our self as well.

**Comment by p74** [comment]
i will move this question to the robotframwork thx Helio for your answers

**Comment by Nyral** [comment]
@HelioGuilherme66 Not a RIDE bug?

**Comment by HelioGuilherme66** [comment]
Closed because (use OR operator):
- is too old,
- newest version should have it fixed,
- not reproducible,
- not an issue,
- is a question,
- lacks logs, versions info, e.t.c.,
- there is no other reason that justifies being opened.

(thanks @Nyral for validating)
