### ISSUE TITLE
Log and Report buttons are disabled in RIDE

### ISSUE THREAD

**Issue by kotes** [robotframework/RIDE#1755]
Log and Report buttons are in disable mode, after the execution of tests I am getting the path links in the console for log and report. I need to copy that path and put it in windows explorer to view the report.
Any help on this is highly appreciated.
Thanks,
Kotes.

**Comment by HelioGuilherme66** [comment]
Kill all webdriver running in processes.
chromedriver.exe
geckodriver.exe
IEDriverServer.exe

Buttons will be enabled again.

**Comment by HelioGuilherme66** [comment]
How to fix documented
