### ISSUE TITLE
python3.6 exec "pip install robotframework-ride" failed.

### ISSUE THREAD

**Issue by stgfeng** [robotframework/RIDE#1757]
Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\ADMINI~1\AppData\Local\Temp\pip-install-ukr3e0pr\robotframework-ride\setup.py", line 20, in <module>
        execfile(join(ROOT_DIR, 'src', 'robotide', 'version.py'))
    NameError: name 'execfile' is not defined

**Comment by HelioGuilherme66** [comment]
I am sure you did not searched this issue tracker for similar problems.

### The current version of RIDE, 1.5.2.1 is NOT compatible with Python 3

**Comment by chandrapola** [comment]
Is there any other version of RIDE that is compatible with python3 ?  as all the other components of robotframework are compatible with python3 why not RIDE , can you please suggest any other version of RIDE , that is compatible with Python3 

Collecting robotframework-ride
  Using cached https://files.pythonhosted.org/packages/3c/14/a5f97f5cf5e981f01e8c0b4c405b0dfc9bc86500cabb044d2c462f73004a/robotframework-ride-1.5.2.1.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\I325816\AppData\Local\Temp\pip-install-9q27xhj9\robotframework-ride\setup.py", line 20, in <module>
        execfile(join(ROOT_DIR, 'src', 'robotide', 'version.py'))
    NameError: name 'execfile' is not defined

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in C:\Users\I325816\AppData\Local\Temp\pip-install-9q27xhj9\robotframework-ride\

**Comment by sachansoft** [comment]
@HelioGuilherme66 how long RIDE will take to compatible with Python 3.

**Comment by HelioGuilherme66** [comment]
This Issue is now fixed, so closing:
Users may want to see: [latest releases](https://github.com/robotframework/RIDE/releases)
The best installation process is:
```
pip install -U -r https://raw.githubusercontent.com/robotframework/RIDE/master/requirements.txt
pip install -U robotframework-ride
```
