### ISSUE TITLE
brackets in xpath are not supported?

### ISSUE THREAD

**Issue by szustpaw** [robotframework/RIDE#1758]
Hello,
i using robotframework ride withe selenium library and i want to doubleclick to element specyfied as xpath (//span[contains(text(),"Testing_PSZ@System")])[1]
Unfortunately it fails on this step with information:
"ValueError: Element locator '(//span[contains(text(),"Testing_PSZ@System")])[1]' did not match any elements."
It looks like some RIDE error (not support brackets in xpath use as locator to keyword)?
Do You know maybe another way to click on first occurance of element (without using brackets)?

**Comment by HelioGuilherme66** [comment]
Closed because (use OR operator):
- is too old,
- newest version should have it fixed,
- not reproducible,
- not an issue,
- is a question,
- lacks logs, versions info, e.t.c.,
- there is no other reason that justifies being opened.

(thanks @Nyral for validating)
