### ISSUE TITLE
Using Robotframework with python3

### ISSUE THREAD

**Issue by ounes** [robotframework/RIDE#1761]
Hello,
I'm currently an Robotframework's user and I want to upgrade my python's version to 3.4. 
I read the ride's documentation and apparently It's not supported on python3.
Is there a solution on ride or another IDE that support python3 ?
Thank's in advance

**Comment by HelioGuilherme66** [comment]
Did you search about this, here? Probably not. [Here](https://github.com/robotframework/RIDE/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+python3) is the search for you.

However you can try from my fork (Important to read the text and understand the problems you may find). See the Releases page, [here](https://github.com/HelioGuilherme66/RIDE/releases).

**Comment by ounes** [comment]
Thanks you, it was helpfull !!!!

**Comment by HelioGuilherme66** [comment]
This Issue is now fixed, so closing:
Users may want to see: [latest releases](https://github.com/robotframework/RIDE/releases)
The best installation process is:
```
pip install -U -r https://raw.githubusercontent.com/robotframework/RIDE/master/requirements.txt
pip install -U robotframework-ride
```
