### ISSUE TITLE
Unable to Run Test Case in RIDE with Python 3.7

### ISSUE THREAD

**Issue by siddharth0307** [robotframework/RIDE#1763]
I installed RIDE with Python 3.7. I am able to open RIDE as well using ride.py command. However, when i run a test case it shows up below message:

Robot Framework installation not found.
To run tests, you need to install Robot Framework separately.
See http://robotframework.org for installation instructions.

=======================
But i have already installed robotframework on my system. As below:
  
C:\Python\robotframework-ride-1.5.2.1>pip freeze
asn1crypto==0.24.0
bcrypt==3.1.4
beautifulsoup4==4.6.1
cffi==1.11.5
cryptography==2.3
idna==2.7
jsonpatch==1.23
jsonpointer==2.0
paramiko==2.4.1
pyasn1==0.4.4
pycparser==2.18
Pygments==2.2.0
PyNaCl==1.2.1
PyPubSub==3.3.0
pytz==2018.5
pywin32==223
robotframework==3.0.4
robotframework-databaselibrary==1.0.1
robotframework-httplibrary==0.4.2
robotframework-ride==1.7.2
robotframework-selenium2library==3.0.0
robotframework-seleniumlibrary==3.1.1
robotframework-sshlibrary==3.1.0
selenium==3.13.0
six==1.11.0
waitress==1.1.0
WebOb==1.8.2
WebTest==2.0.30
wxPython==4.0.3

C:\Python\robotframework-ride-1.5.2.1>

**Comment by HelioGuilherme66** [comment]
First, if you installed RIDE 1.7.2, this is not the correct Issue tracker. It should be on my fork.

Why do you have this directory? C:\Python\robotframework-ride-1.5.2.1
Remove RIDE directory you do not need. There may be conflicts because of that.

The way RIDE searches for RobotFramework may depend on the order of the PATH environment variable. Better make sure the correct RobotFramework is found first. Look at Tools->RIDE Log.

Never tested RIDE with python 3.7.

**Comment by lvfengwen** [comment]
please run ride.py with python 2.7.10

**Comment by HelioGuilherme66** [comment]
This Issue is now fixed, so closing:
Users may want to see: [latest releases](https://github.com/robotframework/RIDE/releases)
The best installation process is:
```
pip install -U -r https://raw.githubusercontent.com/robotframework/RIDE/master/requirements.txt
pip install -U robotframework-ride
```

**Comment by sankalppatki** [comment]
i am still facing same issue

**Comment by HelioGuilherme66** [comment]
@sankalppatki Commenting on a closed issue does not help much to solve your problem.
The original problem was for an old version of RIDE. If you are sure there is a bug you cannot solve, then open a new Issue, mentioning was versions you are using.
