### ISSUE TITLE
It occur a UnicodeDecodeError when i click the button of “New Project”

### ISSUE THREAD

**Issue by fishasen** [robotframework/RIDE#1765]

**Comment by AngelaWanChina** [comment]
I met the same issue. Could you please let me how do you fix it? Thanks in advance

**Comment by AngelaWanChina** [comment]
HelioGuilherme66 mentioned how to fix it. Refer the link for detail:https://github.com/robotframework/ride/issues/1334

**Comment by HelioGuilherme66** [comment]
Closed because (use OR operator):
- is too old,
- newest version should have it fixed,
- not reproducible,
- not an issue,
- is a question,
- lacks logs, versions info, e.t.c.,
- there is no other reason that justifies being opened.

(thanks @Nyral for validating)
