### ISSUE TITLE
[PYTHON_EXECUTABLE]"' is not recognized as an internal or external command

### ISSUE THREAD

**Issue by ajaysmadhavan** [robotframework/RIDE#1768]
Hello

Below error is observed when running test in Ride.

command: pybot.bat --argumentfile c:\users\ajays\appdata\local\temp\RIDE8mh271.d\argfile.txt --listener C:\Python27\lib\site-packages\robotide\contrib\testrunner\TestRunnerAgent.py:58014 C:\Users\ajays\Documents\AJAY\Test.tsv
unexpected error: '"[PYTHON_EXECUTABLE]"' is not recognized as an internal or external command,
operable program or batch file.

**Comment by HelioGuilherme66** [comment]
Please open a command line and enter the commands and paste here the results:
```
pybot --version
type C:\Python27\Scripts\pybot.bat
```

**Comment by ajaysmadhavan** [comment]
Hi

Even for above commands below error is printed in command line.

'"[PYTHON_EXECUTABLE]"' is not recognized as an internal or external command,
operable program or batch file

**Comment by ajaysmadhavan** [comment]
Hi

After Reinstalling the packages again, Issue got resolved

**Comment by Gyaneswar** [comment]
Hi @ajaysmadhavan Can you remember which packages you reinstalled i am facing a similar issue
