### ISSUE TITLE
Content Assistant doesn't show in Win 10

### ISSUE THREAD

**Issue by Luka3008** [robotframework/RIDE#1770]
Content Assistant doesn't show in Win 10. 
Automatically add only **${/}** or other variable used previously in the test. IDE doesn't display functions or Documentation.

Environment 
OS: Win 10 pro 64 bit
Python: 2.7.13
robot: 1.5.2.1
wxPython: wxPython2.8-win32-unicode-2.8.12.1-py27 updated to 4.0.3

**Comment by lvfengwen** [comment]
i think wxPython must be  wxPython2.8-win32-unicode-2.8.12.1-py27, and did you resource the function, if you did . try restart the ride again ,sometimes its need restart to load the keyword resource ,hopes help you !

**Comment by Luka3008** [comment]
Problem solved.
I was using ConEmu app for the command line.  
Now I am using windows command line or PowerShell and it is working correctly.

**Comment by HelioGuilherme66** [comment]
Closed because (use OR operator):
- is too old,
- newest version should have it fixed,
- not reproducible,
- not an issue,
- is a question,
- lacks logs, versions info, e.t.c.,
- there is no other reason that justifies being opened.

(thanks @Nyral for validating)
