### ISSUE TITLE
Faulty error appears when the argument file is loaded from the home directory

### ISSUE THREAD

**Issue by p74** [robotframework/RIDE#1778]
I have a argument file  located in ~/A/B/C.txt 
and i fill in the arguments in ride: -A ~/A/B/C.txt 
The argument background color is red and error message is appear file does not exist 
but when i just press start my tests runs fine. 

is it possible to fix this in a new release?

**Comment by Nyral** [comment]
@p74 Does it work if you add full path, instead of relative path?

**Comment by p74** [comment]
Yes ... full path is indeed working

Op za 1 jun. 2019 21:23 schreef Nyral <notifications@github.com>:
