### ISSUE TITLE
Ride crash when i click in the top left data table field of a test template

### ISSUE THREAD

**Issue by p74** [robotframework/RIDE#1779]
1 Select a testcase within a test-template with a header

for example:
*** Test Cases ***    tabel Description 1      table Description 2

2 Open the tab edit

3 Click then in the upper left cell of the data table (the cell above "1") 
Error: Ride  will crash and give an error:  Segmentation fault (core dumped)

i use ride in a Linux os

**Comment by Nyral** [comment]
@p74 Does this still occur with latest release?

**Comment by p74** [comment]
I dont know we moved away from ride and i use red eclipse

Op za 1 jun. 2019 21:25 schreef Nyral <notifications@github.com>:

**Comment by jnhyperion** [comment]
I reproduced this bug.

**Comment by HelioGuilherme66** [comment]
Closing Issue as fixed.
Currently on RIDE v2.0.2.dev1 in Fedora Linux 36, Python 3.10.10, wxPython 4.0.7 (KDE Plasma 5 with darkmode, custom colors).
