### ISSUE TITLE
总是遇到如下问题，有人知道怎么解决不？ModuleNotFoundError：没有名为' version '的模块

### ISSUE THREAD

**Issue by VickyMzsdjl** [robotframework/RIDE#1780]
ModuleNotFoundError: No module named '__version__'

**Comment by HelioGuilherme66** [comment]
This is the Google translation of the title:
> (Always encounter a problem, people know how to solve not? (# 1780))

We need more information about the error you found.
How did it appear?
Please post the full output of the error (preferably using three ` in lines before and after).
