### ISSUE TITLE
How to change the font and size of project tree in the left of RIDE

### ISSUE THREAD

**Issue by leoggsh** [robotframework/RIDE#1785]
Hi,

I install the RIDE 1.5.2.1 on the Win10, in my office laptop.
The font size of the project tree is too small in the left side of the RIDE.

On the Win7, I can change this font and size by the following steps:
> right click on the desktop, select "Personalize"
> click "Window Color", open the "Window Color and Appearance" windows
> change the fond name and size in the "Window Color and Appearance" windows

But in the version of Win10 of my office laptop, I can not do it. This function has been removed.

Is there any other method to change this font and size of the project tree in the RIDE? Thanks.

Leo
![ride](https://user-images.githubusercontent.com/46175742/50464953-0481b380-09cf-11e9-8dab-e63c297ffd82.gif)

**Comment by hyh162213** [comment]
same question like you.
and I'd like to ask how make the table a little wider.
I open my ride always like this:
![image](https://user-images.githubusercontent.com/46335731/51544449-ee1a2b00-1e9a-11e9-8430-3b2b413f8035.png)

**Comment by HelioGuilherme66** [comment]
Fixed long time ago, probably after 2.0.8.1.
Font Type and Size (Test Suites and Files Explorer) can be changed by editing `settings.cfg`.
Using `Tools->Preferences->General, Grid or Text editors` font settings.
Font size can be increased/reduced with Mouse Wheel Roll +/-, for both editors.
