### ISSUE TITLE
RIDE path error : couldn't find library file (Nothing changed just pass a night)

### ISSUE THREAD

**Issue by Caspar2016** [robotframework/RIDE#1786]
Hi, there, I just encounter one problem.
RIDE version v1.7.3rc1 + python3.6 + win7
I have file right here:
Library           ../../06my_Library/06my_testcase_face.py
but, RIDE still said 20181228 10:46:21.565 :  FAIL : No keyword with name '***' found.
This testcase is all right, but has this error just one night!
I even selected Library -> Name -> Browse, but the error still there. (I have reinstalled RIDE but the error  still exist)

other infos:

D:\ProgramData\Anaconda3\Scripts>python ride.py
Thank you for helping developing and testing RIDE on Python 3 and wxPython 4
FAILED base64 list index out of range
FAILED D:\programming_python\1_restful_rf_vap\1_restful_rf_vap\04my_Component\.
./06my_Library/my_testcase_face.py Importing test library 'D:\programming_pyth
on\1_restful_rf_vap\1_restful_rf_vap\04my_Component\..\06my_Library\my_testca
se_face.py' failed: ModuleNotFoundError: No module named 'vas_rest_nodes_interfa
ce'
Traceback (most recent call last):
  File "D:\ProgramData\Anaconda3\lib\site-packages\robotide\lib\robot\utils\impo
rter.py", line 153, in _import
    return __import__(name, fromlist=fromlist)
  File "D:\programming_python\1_restful_rf_vap\1_restful_rf_vap\06my_Library\va
p_testcase_face.py", line 16, in <module>
    import vas_rest_nodes_interface
PYTHONPATH:
  D:\ProgramData\Anaconda3\Scripts
  D:\ProgramData\Anaconda3\python36.zip
  D:\ProgramData\Anaconda3\DLLs
  D:\ProgramData\Anaconda3\lib
  D:\ProgramData\Anaconda3
  D:\ProgramData\Anaconda3\lib\site-packages
  D:\ProgramData\Anaconda3\lib\site-packages\Babel-2.5.0-py3.6.egg
  D:\ProgramData\Anaconda3\lib\site-packages\pymysql-0.8.0-py3.6.egg
  D:\ProgramData\Anaconda3\lib\site-packages\pyinstaller-3.3.1-py3.6.egg
  D:\ProgramData\Anaconda3\lib\site-packages\future-0.16.0-py3.6.egg
  D:\ProgramData\Anaconda3\lib\site-packages\pefile-2017.11.5-py3.6.egg
  D:\ProgramData\Anaconda3\lib\site-packages\win32
  D:\ProgramData\Anaconda3\lib\site-packages\win32\lib
  D:\ProgramData\Anaconda3\lib\site-packages\Pythonwin
  D:\ProgramData\Anaconda3\lib\site-packages\robotide\spec
  D:\ProgramData\Anaconda3\lib\site-packages\robotide\lib
  D:\ProgramData\Anaconda3\lib\site-packages\robotide\contrib\testrunner\../../l
ib
  D:\ProgramData\Anaconda3\lib\site-packages\robotide\contrib\testrunner\../../l
ib
  ./vas_rest_interfaces
FAILED D:\programming_python\1_restful_rf_vap\1_restful_rf_vap\01my_Rest_testca
se\06迭代用例\../../06my_Library/my_testcase_face.py Importing test library 'D
:\programming_python\1_restful_rf_vap\1_restful_rf_vap\01my_Rest_testcase\06迭
代用例\..\..\06my_Library\my_testcase_face.py' failed: ModuleNotFoundError: No
 module named 'vas_rest_nodes_interface'
Traceback (most recent call last):
  File "D:\ProgramData\Anaconda3\lib\site-packages\robotide\lib\robot\utils\impo
rter.py", line 153, in _import
    return __import__(name, fromlist=fromlist)
  File "D:\programming_python\1_restful_rf_vap\1_restful_rf_vap\06my_Library\va
p_testcase_face.py", line 16, in <module>
    import vas_rest_nodes_interface
PYTHONPATH:
  D:\ProgramData\Anaconda3\Scripts
  D:\ProgramData\Anaconda3\python36.zip
  D:\ProgramData\Anaconda3\DLLs
  D:\ProgramData\Anaconda3\lib
  D:\ProgramData\Anaconda3
  D:\ProgramData\Anaconda3\lib\site-packages
  D:\ProgramData\Anaconda3\lib\site-packages\Babel-2.5.0-py3.6.egg
  D:\ProgramData\Anaconda3\lib\site-packages\pymysql-0.8.0-py3.6.egg
  D:\ProgramData\Anaconda3\lib\site-packages\pyinstaller-3.3.1-py3.6.egg
  D:\ProgramData\Anaconda3\lib\site-packages\future-0.16.0-py3.6.egg
  D:\ProgramData\Anaconda3\lib\site-packages\pefile-2017.11.5-py3.6.egg
  D:\ProgramData\Anaconda3\lib\site-packages\win32
  D:\ProgramData\Anaconda3\lib\site-packages\win32\lib
...

Many thanks!!!

**Comment by ravihuang** [comment]
修改my_testcase_face.py，在模块名前加个.试试

**Comment by HelioGuilherme66** [comment]
Closed because (use OR operator):
- is too old,
- newest version should have it fixed,
- not reproducible,
- not an issue,
- is a question,
- lacks logs, versions info, e.t.c.,
- there is no other reason that justifies being opened.

(thanks @Nyral for validating)
