### ISSUE TITLE
   ride.py,    from pubsub import pub ImportError: No module named pubsub

### ISSUE THREAD

**Issue by gaga128** [robotframework/RIDE#1794]
robotframework==3.1.1
robotframework-ride==1.7.3
wxPython==2.8.12.1
wxPython-common==2.8.12.1
![image](https://user-images.githubusercontent.com/18659947/51519338-a9bb6a80-1e5b-11e9-88d6-8b1e7c19b880.png)

**Comment by Hi-Fi** [comment]
Duplicate to #1793
