### ISSUE TITLE
RIDE:set default column size seems doesn't work

### ISSUE THREAD

**Issue by hyh162213** [robotframework/RIDE#1798]
ride-tools-preferences-grid editor-default column size
the default column size when first installed was 180,but I think it looked much more differently as 180.
Whatever I set the default column size(even as 9999),the table while using seems too tinny to input words.
![image](https://user-images.githubusercontent.com/46335731/51542926-5a932b00-1e97-11e9-927a-4300aee68788.png)
Whether it really does not work or I do not find the proper way to use it,
hope somebody can answer me :)

**Comment by malikbharat15** [comment]
Facing the same issue.Tried changing the column size also from default.Looking for options.

**Comment by HelioGuilherme66** [comment]
When the cells are empty, they are small, but when filled they resize. I know that the functionality is not OK, but it should not impede to work.

**Comment by hyh162213** [comment]
hope somebody can find way out,
there is no reason to give up good feature of old version.

**Comment by metafisics** [comment]
Yup !  Very annoying !  Is there still no fix for this ?

**Comment by Nyral** [comment]
Fixed by PR #1962

**Comment by Nyral** [comment]
Fixed through PR #1962
