### ISSUE TITLE
python v3.7.1 can open ride, but can't run the testcase

### ISSUE THREAD

**Issue by zhyalin** [robotframework/RIDE#1799]
![image](https://user-images.githubusercontent.com/45581070/51588288-a806ab00-1f1e-11e9-8eb3-a8ec055a3d77.png)

**Comment by zhyalin** [comment]
run ride has no log, the log always
 "20190124 09:46:48.226 [INFO]: Found Robot Framework version 3.1.1 from C:\Python37\lib\site-packages\robot.
20190124 09:46:48.227 [INFO]: Started RIDE 1.7.3.1 using python version 3.7.1 with wx version 4.0.4 in win32." 


run the testcase twice, the "ride.py" cmd window has follow message

"Traceback (most recent call last):
  File "C:\Python37\lib\site-packages\robotide\ui\actiontriggers.py", line 338, in __call__
    action.act(event)
  File "C:\Python37\lib\site-packages\robotide\action\action.py", line 89, in act
    self.action(event)
  File "C:\Python37\lib\site-packages\robotide\contrib\testrunner\testrunnerplugin.py", line 300, in OnRun
    command = self._create_command()
  File "C:\Python37\lib\site-packages\robotide\contrib\testrunner\testrunnerplugin.py", line 325, in _create_command
    self.get_current_profile(),
  File "C:\Python37\lib\site-packages\robotide\contrib\testrunner\testrunnerplugin.py", line 699, in get_current_profile
    return self._test_runner.get_profile(self.choice.GetStringSelection())
  File "C:\Python37\lib\site-packages\robotide\contrib\testrunner\testrunner.py", line 106, in get_profile
    return self.profiles[name]
KeyError: ''
Traceback (most recent call last):
  File "C:\Python37\lib\site-packages\robotide\contrib\testrunner\testrunnerplugin.py", line 300, in OnRun
    command = self._create_command()
  File "C:\Python37\lib\site-packages\robotide\contrib\testrunner\testrunnerplugin.py", line 325, in _create_command
    self.get_current_profile(),
  File "C:\Python37\lib\site-packages\robotide\contrib\testrunner\testrunnerplugin.py", line 699, in get_current_profile
    return self._test_runner.get_profile(self.choice.GetStringSelection())
  File "C:\Python37\lib\site-packages\robotide\contrib\testrunner\testrunner.py", line 106, in get_profile
    return self.profiles[name]
KeyError: ''
"

I run these command "actiontriggers.py", "action.py","testrunner.py","testrunnerplugin.py" in cmd,only "testrunnerplugin.py" has follow message
"testrunnerplugin.py:83: DeprecationWarning: NewId() is deprecated
  ID_RUN = wx.NewId()
testrunnerplugin.py:84: DeprecationWarning: NewId() is deprecated
  ID_RUNDEBUG = wx.NewId()
testrunnerplugin.py:85: DeprecationWarning: NewId() is deprecated
  ID_STOP = wx.NewId()
testrunnerplugin.py:86: DeprecationWarning: NewId() is deprecated
  ID_PAUSE = wx.NewId()
testrunnerplugin.py:87: DeprecationWarning: NewId() is deprecated
  ID_CONTINUE = wx.NewId()
testrunnerplugin.py:88: DeprecationWarning: NewId() is deprecated
  ID_STEP_NEXT = wx.NewId()
testrunnerplugin.py:89: DeprecationWarning: NewId() is deprecated
  ID_STEP_OVER = wx.NewId()
testrunnerplugin.py:90: DeprecationWarning: NewId() is deprecated
  ID_SHOW_REPORT = wx.NewId()
testrunnerplugin.py:91: DeprecationWarning: NewId() is deprecated
  ID_SHOW_LOG = wx.NewId()
testrunnerplugin.py:92: DeprecationWarning: NewId() is deprecated
  ID_AUTOSAVE = wx.NewId()
testrunnerplugin.py:93: DeprecationWarning: NewId() is deprecated
  ID_PAUSE_ON_FAILURE = wx.NewId()
testrunnerplugin.py:94: DeprecationWarning: NewId() is deprecated
  ID_SHOW_MESSAGE_LOG = wx.NewId()
"

my system is x64, use "pip install wxpython",the info is 
"Collecting wxPython
  Using cached https://files.pythonhosted.org/packages/bd/6e/ce469293cf6f7e391c11ec31161a9d6d0f2acffd05da2fb27bb3b3d81d1e/wxPython-4.0.4-cp37-cp37m-win_amd64.whl"

**Comment by SGond** [comment]
Hi I also getting same issue
![image](https://user-images.githubusercontent.com/46990782/51663530-0befa900-1fdd-11e9-8e60-d755b917fb2d.png)

**Comment by deepakaravind** [comment]
@metafisics Am running into the same issue as well?  What did you do to resolve this issue?   I am on python2.7 though

**Comment by yuanzhiyu000x** [comment]
@metafisics  I don't understand, please tell me some details. Thank you!!!!!!!

**Comment by metafisics** [comment]
> @metafisics I don't understand, please tell me some details. Thank you!!!!!!!

Hi !  While you're in your test case, go in there "Run" tab and in there you will see a dropdown called "Execution Profile". In my case nothing was selected, it was blank, so I simply selected "Robot".

Hope this helps !



![image](https://user-images.githubusercontent.com/40769284/52955766-8bae3080-335b-11e9-98cd-2f9c047d3b8f.png)

**Comment by yuanzhiyu000x** [comment]
> > @metafisics I don't understand, please tell me some details. Thank you!!!!!!!
> 
> Hi ! While you're in your test case, go in the "Run" tab and in there you will see a dropdown called "Execution Profile". In my case nothing was selected, it was blank, so I simply selected "Robot".
> 
> Hope this helps !
> 
> ![image](https://user-images.githubusercontent.com/40769284/52955766-8bae3080-335b-11e9-98cd-2f9c047d3b8f.png)
It works. Thank you for your patience~~~~!!!!!!!!!

**Comment by HelioGuilherme66** [comment]
It was bad usage because no running profile was selected
(this is more noticeable when upgrading from 1.5.2.1, because it may have been selected `pybot`)
