### ISSUE TITLE
Mac can hardly run robotframework-ride?

### ISSUE THREAD

**Issue by zhangyusheng0373** [robotframework/RIDE#1800]
My development environment：
Python 2.7.15
robotframework 3.1.1
wxPython  3.0.2.0
robotframework-ride 1.7.3.1
PyPubSub 3.3.0
System:
MacOS Mojave 10.14.2
Use ride Open up a robot project,The navigation bar on the left is very hard to click on,The test case writing unit is very small,Is there a stable version for the Mac？Or is it my development environment' problem?

**Comment by HelioGuilherme66** [comment]
Please close RIDE and update wxPython and others with:
```
pip install -r -U https://raw.githubusercontent.com/robotframework/RIDE/master/requirements.txt
```
The size of characters for editors can be set in Tools->Preferences

**Comment by zhangyusheng0373** [comment]
Thank you very much. The problem has been solved. This is due to the low version of wxpython
