### ISSUE TITLE
Unable to install RIDE on Linux (Debian testing)

### ISSUE THREAD

**Issue by hoijui** [robotframework/RIDE#1811]
It looks like RIDE can only be used on windows, right?

I asume it is windown only because on my (Linux) system, when running

    sudo pip install robotframework-ride

I get:

> Could not find a version that satisfies the requirement Pywin32 (from robotframework-ride)

**Comment by hoijui** [comment]
I asume it is windown only becasue on my (linux) system, when running

    sudo pip install robotframework-ride

I get:

> Could not find a version that satisfies the requirement Pywin32 (from robotframework-ride)

**Comment by 2Eagle2** [comment]
it works on linux too.
It only have some issues with pip install right now.
you can try:
`pip install -U -r https://raw.githubusercontent.com/robotframework/RIDE/master/requirements.txt`
download code from here
`python setup.py build` 
`python setup.py install`

**Comment by hoijui** [comment]
Thank you 2Eagle2!

# What finally worked for me

I am running Debian testing, and I first had to install the build requirements for the RIDE requirements:
	
	sudo apt-get install -y \
		libgstreamer-plugins-base1.0-dev \
		libwxgtk-webview3.0-gtk3-dev

though in other places I saw that one needs these too
(maybe I already had them, or my system is just "newer"):
	
	sudo apt-get install -y libgtk2.0-dev libgtk-3-dev \
		libjpeg-dev libtiff-dev \
		libsdl1.2-dev libgstreamer-plugins-base0.10-dev \
		libnotify-dev freeglut3 freeglut3-dev libsm-dev \
		libwebkitgtk-dev libwebkitgtk-3.0-dev

After that, as you said, I instaleld the requirements for building RIDE
(This took a long time, ~30min):

	pip install -U -r https://raw.githubusercontent.com/robotframework/RIDE/master/requirements.txt

Then getting RIDE sources, compiling and installing them
(jsut a few seconds):

	git clone git@github.com:robotframework/RIDE.git
	cd RIDE
	python setup.py build
	sudo python setup.py install

Then I can start RIDE from everywehre with:

	ride.py &

**Comment by wulifangy** [comment]
operating system： macos
error:
`Could not find a version that satisfies the requirement Pywin32 (from robotframework-ride) (from versions: )
No matching distribution found for Pywin32 (from robotframework-ride)`

Excuse me！How to resolve it？

**Comment by HelioGuilherme66** [comment]
@wulifangy You can see that fixed in current development version:
```
pip install -U https://github.com/robotframework/RIDE/archive/master.zip
```

**Comment by SztywnyMisha** [comment]
> it works on linux too.
> It only have some issues with pip install right now.
> you can try:
> `pip install -U -r https://raw.githubusercontent.com/robotframework/RIDE/master/requirements.txt`

after that i got this type of err:
Command "/usr/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-a8EMrx/wxPython/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-wsrH1M-record/install-record.txt --single-version-externally-managed --compile --user --prefix=" failed with error code 1 in /tmp/pip-build-a8EMrx/wxPython/

don`t know what to do??
> download code from here
> `python setup.py build`
> `python setup.py install`

**Comment by HelioGuilherme66** [comment]
@SztywnyMisha We usually do not look at closed issues. You should ask in Google Group or Slack channel #ride.

In any case, your system is probably different from the original poster. Your problem is the installation of wxPython. Linux users should install wxPython before installing RIDE. Look for the Downloads at wxPython.org and get the correct distro and python versions. You can install it with pip pointing to the package URL, like in `pip install URL_to_package`.

**Comment by Hussnain12** [comment]
to install ride on debian follow these steps: 
1. `sudo apt-get install libgtk-3-dev`
after this install following:
2.`sudo apt-get install libjpeg-dev libtiff-dev libsdl2-dev libgstreamer-plugins-base1.0-dev libgl1-mesa-dev libglu1-mesa-dev libwebp-dev libgtk-3-dev libnotify-dev freeglut3-dev`
after that install wxpython:
3. `pip3 install wxPython==4.2.1` check for the latest verion
4. pip3 install robotframework-ride

**Comment by HelioGuilherme66** [comment]
@Hussnain12 Writing content in closed issues is not useful.
You can create a question and answer in the FAQ in our Wiki. If you do that, please be detailed about the Debian version. Is it 9 or 10?
Thanks
