### ISSUE TITLE
Unable to run test cases if # comment is commented

### ISSUE THREAD

**Issue by StephaneSavard** [robotframework/RIDE#1812]
In any test case, enter a comment using the # sign, for example:

Lookup string values
    [Documentation]    Verifies creating an enumerated type (i.e. Lookup) using string values.
    # Copy the test project
    Copy Directory    ${PROJECT_PATH}    ${TEST_PROJECT_PATH}

Next, comment out the # comments:

Comment    # Copy the test project

When the test case is run, we get the following error and nothing runs:

[ ERROR ] Calling method 'start_keyword' of listener 'c:\python27\lib\site-packages\robotide\contrib\testrunner\TestRunnerAgent.py' failed: IndexError: list index out of range

Was working in an earlier release.

**Comment by HelioGuilherme66** [comment]
Confirming test sample:
```robot
*** Test Cases ***
Lookup string values
    [Documentation]    Verifies creating an enumerated type (i.e. Lookup) using string values.
    Comment    # Copy the test project
    Log    Test is OK?
```

**Comment by ArcticFox01** [comment]
I found this issue in python3.7.2 too.
