### ISSUE TITLE
Column sizing on Mac doesn't work.

### ISSUE THREAD

**Issue by technigirl** [robotframework/RIDE#1819]
I don't know if this a "new" issue or not, as this is my first time using RIDE on Mac, but the column sizing doesn't appear to work.  This makes the word wrap bothersome, mainly because the column size is not wide enough.  The wrap occurs before the end of the text is reached, and when I try to manually adjust the column size, the column size returns back to the automatic size when I save.  See attached picture.

I am using Mac OSX (Mojave), and Ride 1.74dev on Python3.7.
![screen shot 2019-02-04 at 3 45 33 pm](https://user-images.githubusercontent.com/6920990/52239636-8e595200-2894-11e9-9db8-8d2250e2f1b8.png)

The issue occurs even if I uncheck the "Autosize columns" box in Preferences.  Manually adjusting the default column width in Preferences also doesn't help.

**Comment by technigirl** [comment]
I can work around this by unchecking Autosize in Preferences, so I don't think it's really a major issue.

**Comment by technigirl** [comment]
Yes, you can install it, it is just the pip install that is broken.  You have to follow these steps:

pip install -U -r https://raw.githubusercontent.com/robotframework/RIDE/master/requirements.txt
<download code from here>
python setup.py build
python setup.py install

**Comment by qupan** [comment]
Thank you,I'll try it tonight.

**Comment by Nyral** [comment]
@technigirl Can you try this again with latest release? Wrapping should work differently.

**Comment by technigirl** [comment]
@Nyral the word wrap and spacing problems that I reported here are resolved with the latest release.  Closing.

**Comment by Nyral** [comment]
@technigirl Thank you for checking!
