### ISSUE TITLE
Not allowing to add or edit name of scalar variable 

### ISSUE THREAD

**Issue by bkashigar** [robotframework/RIDE#1821]
Ride not allowing to edit names of scalar variables.
Installed robotframework-ride 1.7.3.1 on top of python 2.7 in a fresh windows machine.
1. Launched RIDE UI using RIDE.py.
2. Created a test suite and added new sample test.
3. When tried to create a scalar variable in that suite, RIDE was not allowing to enter name of scalar variable.

The pop up was just showing {} but not allowing to enter any characters inside {}.

**Comment by HelioGuilherme66** [comment]
@bkashigar You are or want to be a Tester?
If so, you should know how to report a problem. Please add, at least, some minimal information on what is your setup and what were the steps you did until found the problem.

**Comment by bkashigar** [comment]
> @bkashigar You are or want to be a Tester?
> If so, you should know how to report a problem. Please add, at least, some minimal information on what is your setup and what were the steps you did until found the problem.

Sorry my bad @HelioGuilherme66 , updated with more information.

**Comment by HelioGuilherme66** [comment]
@bkashigar I did try to reproduce the problem, and in fact "apparently" you cannot edit the variable. There is a problem in some text fields editors that prevent showing the `caret`. For example selecting text does not highlight it, but cut and copy functions are still working. In your case, if you start typing the characters will show (but maybe in the wrong position).

**Comment by dltsdr** [comment]
I also have problem like this，I creat a new scalar，when I enter name have no cursor，entering Value and Comment are normal.
![video](https://user-images.githubusercontent.com/25201676/57745770-fecc0680-7700-11e9-96ed-7e0b32293723.gif)
This is my version
![version](https://user-images.githubusercontent.com/25201676/57743857-6a11da80-76f9-11e9-8891-41b18e262555.png)
@HelioGuilherme66
