### ISSUE TITLE
RIDE doesnt support new FOR loop syntax

### ISSUE THREAD

**Issue by kaamos91** [robotframework/RIDE#1826]
I just upgraded to Robotframework 3.1.1 and using RIDE 1.7.3.1
One of the new things since Robotframework 3.1 is the new syntax of FOR loop
which started to change from :FOR to FOR and END (in it's own line).
But in RIDE FOR is autocompleted to :FOR and acts like it doesn't know the END command.
Is there a solution for this?

**Comment by HelioGuilherme66** [comment]
@kaamos91 This is a known problem, but it is consistent with robot parser. The only modification done was to ignore the `END` because otherwise it would not allow o save the file. Since "we" are in a transition for the new syntax, let's leave it as it is.

**Comment by 9nehS** [comment]
robot 3.1.2rc1 has this bug fix: https://github.com/robotframework/robotframework/issues/3064
Does this means this issue is fixed indirectly?

**Comment by HelioGuilherme66** [comment]
Fixed by #1981 .
