### ISSUE TITLE
testcase can't run，python v2.7.15

### ISSUE THREAD

**Issue by yuanzhiyu000x** [robotframework/RIDE#1829]
![image](https://user-images.githubusercontent.com/47738038/52942129-562e3500-33a5-11e9-902b-98aea083ee65.png)
I had config environment variable,

C:\Python27;
C:\Python27\Scripts;
C:\Python27\Lib\site-packages

but "start" is not work.
Please tell me more details.Thank you~!!!!!

**Comment by mdks2008** [comment]
![image](https://user-images.githubusercontent.com/41201106/52955407-88508e80-33c7-11e9-901c-3be6c54b9ee3.png)

**Comment by yuanzhiyu000x** [comment]
@mdks2008  So simple~~！！！！Thank you~~~!!!!!!!!!!
