### ISSUE TITLE
Reopen ride，the Suite turns into Resource

### ISSUE THREAD

**Issue by yuanzhiyu000x** [robotframework/RIDE#1832]
I had added three Suites “应用系统、网系、数据中心”，but when I reopened RIDE， the two turned into Resource.  
![image](https://user-images.githubusercontent.com/47738038/53072618-a1b91e00-3520-11e9-90b4-cb8e35b0fcf8.png)

**Comment by HelioGuilherme66** [comment]
Do they really have test cases?

**Comment by yuanzhiyu000x** [comment]
> Do they really have test cases?

No test cases. 
Sorry for my bad English.

**Comment by HelioGuilherme66** [comment]
If they don't have test cases they show like that. It is not a bug, it's a feature :)

**Comment by HelioGuilherme66** [comment]
Usage clarified.

**Comment by Nyral** [comment]
When creating suite/resource, RIDE should add basic template sections, like `*** Settings ***`, `*** Test Cases ***` and `*** Keywords ***`. That way, if the user has created a suite without test cases, RIDE will show it as a suite next time when it's reopened.
