### ISSUE TITLE
GRID edit mode is missing in RIDE 1.7.3.1

### ISSUE THREAD

**Issue by mrmaramreddy** [robotframework/RIDE#1833]
Hi,

I upgraded to RIDE 1.7.3.1 and GRID edit tab is missing; instead I see 2 "Text Edit" tabs (please see attached screen). Can someone help if I need to change some setting to get GRID edit view?
Following is the output of 'pip freeze' command on my Windows 10 OS.

Pillow==5.4.1
Pygments==2.3.1
PyPubSub==3.3.0
pywin32==224
robotframework==3.1.1
robotframework-ride==1.7.3.1
robotframework-selenium2library==3.0.0
robotframework-seleniumlibrary==3.3.1
robotframeworklexer==1.1
selenium==3.141.0
six==1.12.0
urllib3==1.24.1
wxPython==4.0.4

Thanks,
Praveen
![ride 1 7 3 1](https://user-images.githubusercontent.com/17325364/53093395-ea4ee800-34dc-11e9-8647-7b8cd05c9482.PNG)

**Comment by HelioGuilherme66** [comment]
See if there are any error messages in Tools>RIDE Log, or at console screen if having one. Please tell us what is the operating system.

**Comment by mrmaramreddy** [comment]
Hi,

I am using Windows 10 OS, no errors in RIDE log (below is the RIDE log information). Note that I am able to run the tests successfully, only GRID view is missing.

20190220 06:36:49.779 [INFO]: Found Robot Framework version 3.1.1 from c:\python\python37\lib\site-packages\robot.
20190220 06:36:49.779 [INFO]: Started RIDE 1.7.3.1 using python version 3.7.2 with wx version 4.0.4 in win32.

Thanks,
Praveen

**Comment by HelioGuilherme66** [comment]
See if you have disabled the Editor on Tools->Manage Plugins.
![image](https://user-images.githubusercontent.com/2866630/53159474-dc24c880-35bd-11e9-8499-5c32fa0491da.png)

**Comment by mrmaramreddy** [comment]
Yes, I see the Editor checkbox is disabled (I never did that, may be default setting?). I enabled it and restarted RIDE which brought back GRID Edit option and also removed second Text Edit tab.

Thank you very much for the response.
