### ISSUE TITLE
template   ${EMPTY}  bug

### ISSUE THREAD

**Issue by tianya6607** [robotframework/RIDE#1834]
template eg:

login
    [Tags]    smoke    high
    [Template]    kwLogin
    ${EMPTY}    123456 
    Test01    ${EMPTY}

As long as the first non-null value is entered, the same field fails to enter the null value for the second time, and the last non-null value is used. first: 123456   second  shouled be empty,but it is 123456

**Comment by HelioGuilherme66** [comment]
Closing because is poorly reported or not a RIDE issue.
