### ISSUE TITLE
run keyword if  can not use  Evaluate

### ISSUE THREAD

**Issue by tianya6607** [robotframework/RIDE#1835]
eg:  
login
    [Tags]    smoke    high
    [Template]    kwLogin
    ${EMPTY}    123456 
    Test01    ${EMPTY} 
    Test01    1    
    Test01    'a' * 5
    Test01    'a' * 30
    Test01    'a' * 31

run keyword if  ‘*’  in  '${psw}'     ${psw}    Evaluate    ${psw}

fail

**Comment by drfunjohn** [comment]
my be:
${psw}=   run keyword if     ‘*’ in '${psw}'    Evaluate     ${psw}

**Comment by tianya6607** [comment]
thank you
${psw}    run keyword if    '*' in "${psw}"    Evaluate    ${psw}
it's ok。but，if  “run keyword if ” is not run  ， ${psw} = None
20190221 14:42:30.111 :  INFO : ${psw} = None
20190221 14:42:30.112 :  INFO : Typing text 'None' into text field 'name=password'.

**Comment by HelioGuilherme66** [comment]
Closing because is poorly reported or is not a RIDE issue.
To know about the community support options, go to [https://robotframework.org/](https://robotframework.org/#support).
