### ISSUE TITLE
Yaml support

### ISSUE THREAD

**Issue by AutomationSpririt** [robotframework/RIDE#1837]
Hello community,

we used to automate via Pycharm, now we are migrating to RIDE. So far, all the team are satisfied with this editor.

However, there is something missing: it not possible to work with Yaml variable files (not displayed in the project tree). Even that they are not marked in red on the Suite Settings part.

It is important for us because we use dictionary variables a lot, and yaml offer the best handling especially for non-technical testers.

Is it possible to include the support of yaml edition into RIDE?

**Comment by HelioGuilherme66** [comment]
I am working on an editor for it. If you have python skills, I could use some help.

**Comment by AutomationSpririt** [comment]
Great news, looking forward for it to be supported !

Unfortunately, we do not have the necessary skills to contribute, I hope that someone else could help on this matter.

Best regards

**Comment by AutomationSpririt** [comment]
Hello,

Is there any news regarding this topic? thank you.

**Comment by matthewdy** [comment]
What can I help？

**Comment by HelioGuilherme66** [comment]
@AutomationSpririt @matthewdy You can now double-click on an YAML file, on the File Explorer panel with current development version 1.7.4b1dev1, from `master` branch.
```
pip install -U https://github.com/robotframework/RIDE/archive/master.zip
```

**Comment by matthewdy** [comment]
@HelioGuilherme66 thanks!

**Comment by rbradhika530** [comment]
Hi [HelioGuilherme66](https://github.com/HelioGuilherme66)

I am not able to add .yml file to ride, any fix or solution,
