### ISSUE TITLE
Command "python setup.py egg_info" failed with error code 1

### ISSUE THREAD

**Issue by snehilmishra** [robotframework/RIDE#1840]
**Facing this issue with Python 3.7**
Getting error when try to install jsonlibrary 
pip install robotframework-jsonlibrary

Command "python setup.py egg_info" failed with error code 1 in C:\Users\SNEHIL~1.MIS\AppData\Local\Temp\pip-install-hl23y63p\robotframework-jsonlibrary\
**I updates setuptools too but still getting same error .** 

![image](https://user-images.githubusercontent.com/30474510/53467120-bb0b1e80-3a7a-11e9-98d1-b1e96e8f2c9d.png)

**Comment by HelioGuilherme66** [comment]
Closing because it is not a RIDE issue.
To know about the community support options, go to [https://robotframework.org/](https://robotframework.org/#support).
