### ISSUE TITLE
mac can`t install

### ISSUE THREAD

**Issue by hztgz** [robotframework/RIDE#1847]
TonyMac:~$ pip install robotframework-ride
DEPRECATION: Python 2.7 will reach the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 won't be maintained after that date. A future version of pip will drop support for Python 2.7.
Collecting robotframework-ride
  Using cached https://files.pythonhosted.org/packages/4e/a6/1835a17fa566b19c166735a9a75d55101e53b68566771ddb0b690dd4be83/robotframework_ride-1.7.3.1-py2.py3-none-any.whl
Collecting Pywin32 (from robotframework-ride)
  Could not find a version that satisfies the requirement Pywin32 (from robotframework-ride) (from versions: )
No matching distribution found for Pywin32 (from robotframework-ride)

**Comment by Jamesparagon** [comment]
same problem via py3.6. How to fix it?

**Comment by hztgz** [comment]
Refueling release update

**Comment by HelioGuilherme66** [comment]
If you are sure that pip is pointing to python3 system, then:
```
sudo -H pip install -r https://raw.githubusercontent.com/robotframework/RIDE/v1.7.3.1/requirements.txt
sudo -H pip install https://github.com/robotframework/RIDE/archive/v1.7.3.1.zip
```
If not certain, use `python3 -m pip`
