### ISSUE TITLE
Robot IDE - Import Errors on Startup

### ISSUE THREAD

**Issue by kvp1110** [robotframework/RIDE#1850]
Step to reproduce: 
File > Open Directory >  Navigate to your project (if there are result files - html in the project folder) then Robot IDE throws parsing errors. Screenshot shown as an example

![image](https://user-images.githubusercontent.com/42485400/54176720-51214a80-4466-11e9-97d1-7e345c7bd19f.png)

**Comment by HelioGuilherme66** [comment]
Yes, we are aware of that. It is an annoying window. Code should be changed to move reporting to RIDE Log, without disturbing user.

**Comment by HelioGuilherme66** [comment]
This was fixed by #1977
