### ISSUE TITLE
Robot Framework RIDE Log throws exceptions although the tests PASS successfully

### ISSUE THREAD

**Issue by kvp1110** [robotframework/RIDE#1851]
I am using RIDE over Python 2.7.15 installation (Windows 10 OS, 8GB RAM laptop)

This following exception shows up once in a while. The tests PASS but then we see this exception as shown in the screenshot. This does not always happen when I rerun the same test without any changes. 

![image](https://user-images.githubusercontent.com/42485400/54233926-5ae99300-44e4-11e9-9362-24fc7e1de4a3.png)

**Comment by kvp1110** [comment]
This error seems to be happening more frequently. There is no other problems observed. Just this warning message. 

Exception in thread Thread-1 (most likely raised during interpreter shutdown):
Traceback (most recent call last):
  File "C:\Python27\lib\threading.py", line 801, in __bootstrap_inner
  File "C:\Python27\lib\threading.py", line 754, in run
  File "C:\Python27\lib\SocketServer.py", line 230, in serve_forever
<type 'exceptions.AttributeError'>: 'NoneType' object has no attribute 'select'

**Comment by HelioGuilherme66** [comment]
Closing Issue as fixed.
Currently on RIDE v2.0.2.dev1 in Fedora Linux 36, Python 3.10.10, wxPython 4.0.7 (KDE Plasma 5 with darkmode, custom colors).
