### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'datafile_controller'

### ISSUE THREAD

**Issue by BrisMark** [robotframework/RIDE#1852]
ride.py is spewing tracebacks into stderr (but thankfully continues to work) with:
AttributeError: 'NoneType' object has no attribute 'datafile_controller'

Details
Linux robotframework01 3.10.0-957.5.1.el7.x86_64 #1 SMP Wed Dec 19 10:46:58 EST 2018 x86_64 x86_64 x86_64 GNU/Linux
Python 2.7.5
ride - 1.7.3.1
wxPython 2.8.12.0 (gtk2-unicode) - because we are on centos 7

Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/robotide/utils/eventhandler.py", line 24, in wrapped
    if self and self._can_be_edited(event):
  File "/usr/lib/python2.7/site-packages/robotide/utils/eventhandler.py", line 43, in _can_be_edited
    ctrl = self.get_selected_datafile_controller()
  File "/usr/lib/python2.7/site-packages/robotide/editor/settingeditors.py", line 210, in get_selected_datafile_controller
    return self._controller.datafile_controller
AttributeError: 'NoneType' object has no attribute 'datafile_controller'

**Comment by HelioGuilherme66** [comment]
@BrisMark You can install wxPython 4.0.4 in CentOS 7 (but still keep 2.8.12.0). You can go get the wheel at [wxPython Extras](https://extras.wxpython.org/wxPython4/extras/linux/). In the [BUILD.rest](https://github.com/robotframework/RIDE/blob/v1.7.3.1/BUILD.rest) document, there is explained how you can select different versions of wxPython.

**Comment by BrisMark** [comment]
Thanks. Solved. Some good instructions on multiversioning wxPython can be found [here](https://wiki.wxpython.org/MultiVersionInstalls#How_do_I_manually_convert_an_existing_install_to_a_multi-version.3F)
