### ISSUE TITLE
Chinese character random code

### ISSUE THREAD

**Issue by panda62** [robotframework/RIDE#1853]
so sorry, my English is very poo.RIDE 1.7.3.1
![图片](https://user-images.githubusercontent.com/40233059/54261784-9b5e1500-45a7-11e9-87c7-1dcb3e4272c7.png)

**Comment by panda62** [comment]
I've found the answer.
https://github.com/robotframework/RIDE/issues/1747
thanks！！！

**Comment by HelioGuilherme66** [comment]
@panda62 Does that mean that installing from current master, solved your problem?
Thanks.
