### ISSUE TITLE
 Importing test library AutoItLibrary failed in the new RIDE version 1.7.3.1

### ISSUE THREAD

**Issue by aagargoura** [robotframework/RIDE#1854]
I update the ride to the new version 1.7.3.1 but then AutoItLibrary turned to red and get this error:

: Importing test library "C:\Python27\Scripts\E-SYS_TEST_AUTOMATION\03_E-SYS\12_Oberflächentests\../../../../Lib/site-packages/AutoItLibrary/" failed

Traceback (most recent call last):
Initializing test library 'AutoItLibrary' with no arguments failed: com_error: (-2147221008, 'CoInitialize wurde nicht aufgerufen.', None, None)
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\robotide\lib\robot\running\testlibraries.py", line 167, in _get_instance
    return libcode(*self.positional_args, **dict(self.named_args))
  File "C:\Python27\Lib\site-packages\AutoItLibrary\__init__.py", line 84, in __init__
    self._AutoIt = win32com.client.Dispatch("AutoItX3.Control")
  File "C:\Python27\lib\site-packages\win32com\client\__init__.py", line 95, in Dispatch
    dispatch, userName = dynamic._GetGoodDispatchAndUserName(dispatch,userName,clsctx)
  File "C:\Python27\lib\site-packages\win32com\client\dynamic.py", line 114, in _GetGoodDispatchAndUserName
    return (_GetGoodDispatch(IDispatch, clsctx), userName)
  File "C:\Python27\lib\site-packages\win32com\client\dynamic.py", line 91, in _GetGoodDispatch
    IDispatch = pythoncom.CoCreateInstance(IDispatch, None, clsctx, pythoncom.IID_IDispatch)
  File "C:\Python27\lib\site-packages\robotide\spec\librarymanager.py", line 87, in _fetch_keywords
    return get_import_result(path, library_args)
  File "C:\Python27\lib\site-packages\robotide\spec\libraryfetcher.py", line 24, in get_import_result
    lib = robotapi.TestLibrary(path, args)
  File "C:\Python27\lib\site-packages\robotide\lib\robot\running\testlibraries.py", line 54, in TestLibrary
    lib.create_handlers()
  File "C:\Python27\lib\site-packages\robotide\lib\robot\running\testlibraries.py", line 100, in create_handlers
    self._create_handlers(self.get_instance())
  File "C:\Python27\lib\site-packages\robotide\lib\robot\running\testlibraries.py", line 159, in get_instance
    self._libinst = self._get_instance(self._libcode)
  File "C:\Python27\lib\site-packages\robotide\lib\robot\running\testlibraries.py", line 169, in _get_instance
    self._raise_creating_instance_failed()
  File "C:\Python27\lib\site-packages\robotide\lib\robot\running\testlibraries.py", line 314, in _raise_creating_instance_failed
    % (self.name, args_text, msg, details))

with the RIDE version 1.5.2.1 work fine
![ERROR](https://user-images.githubusercontent.com/8859685/54537225-7516eb80-4992-11e9-81e3-c8323121b531.PNG)

**Comment by HelioGuilherme66** [comment]
@aagargoura Sorry for only now have seeing this. The errors you see are happening on robotframework library files that are packaged together with RIDE. They are the same version that you have installed. If you run the test, outside RIDE, in the command window, don't you get any errors?
Thanks.

**Comment by theSeaHeartGit** [comment]
1. Same error on win2008 server for RIDE 1.7.3.1.
    -- python command import work fine
        >>> import win32com.client
        >>> win32com.client.Dispatch("AutoItX3.Control")
        <win32com.gen_py.AutoItX3 1.0 Type Library.IAutoItX3 instance at 0x41955912>
    -- Ride1.7.3.1 import error(same with up error)

2. uninstall RIDE1.7.3.1 & install RIDE 1.5.2.1, the AutoItLibrary work fine

**Comment by HelioGuilherme66** [comment]
@aagargoura and @theSeaHeartGit I suspecting that the problem may be because of non-ANSI characters in the path for the library AutoitLibrary. There are some experiments you can do. Install current development version, with `pip install -U https://github.com/robotframework/RIDE/archive/master.zip`
(it should still run with wxPython 2.8.12.1)
If the error is the same, then close RIDE and in command window:
`set PYTHONIOENCODING="UTF-8" `
and start RIDE with:
`python -m robotide.__init__ `

**Comment by lovelytxm** [comment]
Hi i had faced same issue, but i fixed it now.
steps:
1. remove the existing autoitlibrary 'pip uninstall robotframework-autoitlibrary'
2.down load autoitlibrary from 'https://pypi.org/project/robotframework-autoitlibrary/#files' to local PC
3.extract the zip file
4.open cmd as administrator 
5.use 'python setup.py' install to install it
C:\Users\xxx\Downloads\robotframework-autoitlibrary-1.2.4\robotframewo
rk-autoitlibrary-1.2.4>python setup.py install
then fine for me.

**Comment by jnhyperion** [comment]
closed, cannot reproduce

**Comment by thanatarnp** [comment]
> Hi i had faced same issue, but i fixed it now.
> steps:
> 1.remove the existing autoitlibrary 'pip uninstall robotframework-autoitlibrary'
> 2.down load autoitlibrary from 'https://pypi.org/project/robotframework-autoitlibrary/#files' to local PC
> 3.extract the zip file
> 4.open cmd as administrator
> 5.use 'python setup.py' install to install it
> C:\Users\xxx\Downloads\robotframework-autoitlibrary-1.2.4\robotframewo
> rk-autoitlibrary-1.2.4>python setup.py install
> then fine for me.
> robotframework 3.1.2
> robotframework-autoitlibrary 1.2.4
> robotframework-ride 1.7.3.1
> robotframework-selenium2library 3.0.0
> robotframework-seleniumlibrary 3.3.1
> robotframeworklexer 1.1
> selenium 3.141.0
> setuptools 40.6.2

It's worked.
