### ISSUE TITLE
How to create a new test case?

### ISSUE THREAD

**Issue by cpk011** [robotframework/RIDE#1856]
Hi.

I am running RIDE 1.7.3.1 on Python 3.7.2. The OS is MacOS 10.14.4. 
Within RIDE, I was able to create a new project, a new suite, a new resource, but I did not see a choice in the menu to create a new test case.
Is there supposed to be a choice for "New Test Case"?
<img width="1155" alt="Screen Shot 2019-03-27 at 9 14 00 PM" src="https://user-images.githubusercontent.com/25830321/55122556-caab7080-50d5-11e9-8833-94377a563e49.png">

Thanks.

Peter

**Comment by HelioGuilherme66** [comment]
@cpk011 The folder you selected is a Resource, therefore you cannot create Test Cases there. If you right click on the Test Suite `Registration` the option should appear.

**Comment by cpk011** [comment]
You are right. I was able to create test cases under Registration. 
If I remember correctly, both New Install and Registration are Test Suites but New Install is a directory and Registration is a file. 
Does that mean that I need to create Test Suite as a file and not a directory?

Now I am having a problem deleting Test Suites. 

Thanks.

Peter

**Comment by HelioGuilherme66** [comment]
Test Suites are always in a file, or in a directory having a `__init__.robot` file.
What you need is to open a directory, or when creating select a directory instead of a file.

**Comment by HelioGuilherme66** [comment]
Usage clarified.
