### ISSUE TITLE
Is there any way to view .rst files in RIDE

### ISSUE THREAD

**Issue by ruchigupta19** [robotframework/RIDE#1859]
I have a legacy project in Robot framework and all the files are kinda .rst files rather than being .robot, is there any way I can view these files in RIDE?

**Comment by Nyral** [comment]
Sorry, but that file type is deprecated and not supported by RIDE.

**Comment by HelioGuilherme66** [comment]
Closed because (use OR operator):
- newest version should have it fixed,
- not reproducible,
- not an issue,
- is a question,
- lacks logs, versions info, e.t.c.,
- there is no other reason that justifies being opened.

(thanks @Nyral for validating)

**Comment by Melebius** [comment]
> I have a legacy project in Robot framework and all the files are kinda .rst files rather than being .robot, is there any way I can view these files in RIDE?

According to my experience, you can _view_ and _run_ these files in RIDE (as of 1.7.4.1). However, if you _edit_ such a file and save it in RIDE, you’ll lose the .rst contents. See also #1447.
