### ISSUE TITLE
chinese keywords can't run success

### ISSUE THREAD

**Issue by floatice** [robotframework/RIDE#1860]
![image](https://user-images.githubusercontent.com/18067441/55217362-50e0c780-523a-11e9-9e3d-fa197d7d09dd.png)

**Comment by floatice** [comment]
windows 7 and windows 10 has the issue all

**Comment by floatice** [comment]
1.7.3.1 version

**Comment by HelioGuilherme66** [comment]
This happens only in Windows and with Python 2.7.

You can help me testing if it is fixed by installing current development version from my fork.
Please try:
```
pip install -U https://github.com/HelioGuilherme66/RIDE/archive/pre_release_win.zip
```

**Comment by HelioGuilherme66** [comment]
Closing because is too old and we cannot reproduce, or lack of information.
