### ISSUE TITLE
Reloading test suite does not release resources.

### ISSUE THREAD

**Issue by hankonon** [robotframework/RIDE#1868]
RIDE 1.7.3.1 running on Python 2.7.13.  Win 10.
1. Select File -> <test suite> when having it open.

Results:
Increased memory usage every time.

**Comment by hankonon** [comment]
Also, after reopening the test suite a few times, RIDE goes unresponsive and freezes. Could be related to other reported win 10 performance issues, like #1843

**Comment by HelioGuilherme66** [comment]
Can you prepare a sample *public* test file that we can use to reproduce?
The related case you mentioned is about large directories and file counts. Is your case similar? You mention a test file.
Thanks!

**Comment by hankonon** [comment]
I meant when you are having a folder open (where your tests are located), re-select it from the File menu to reload it and observe memory usage. (I was just using simply task manager). If you cannot reproduce with any folder containing tests, i can provide more details to really dig in to the issue.

**Comment by Nyral** [comment]
@HelioGuilherme66 I can reproduce it. Ram used by python to run RIDE increases each time you reload test suites. There is a memory leak somewhere...
