### ISSUE TITLE
Log and Report cannot be created if there is too many test case run with output

### ISSUE THREAD

**Issue by qch1842** [robotframework/RIDE#1871]
I found the issue in 1.5.2.1, there will be exception prompt while RIDE complete test run and try to write log and report, then I will get nothing. If reduced the output by limited test case or check loop. then they can be generated.
Looks like huge volume output lead the issue. 
Is it a bug? or where can I get a work around?

Thanks,
Shawn

**Comment by Soothsilver** [comment]
I suspect that's an issue with Robot Framework, not RIDE. Robot Framework consumes a lot of CPU and memory to generate the log and the report, especially if you use Jython.  

You can disable log and report generation with arguments "--log none --report none". You can then generate those files using `rebot`.

**Comment by HelioGuilherme66** [comment]
Closed because (use OR operator):
- newest version should have it fixed,
- not reproducible,
- not an issue,
- is a question,
- lacks logs, versions info, e.t.c.,
- there is no other reason that justifies being opened.

(thanks @Nyral for validating)
