### ISSUE TITLE
Please bring back tag wrapping

### ISSUE THREAD

**Issue by Nyral** [robotframework/RIDE#1873]
[This commit](https://github.com/robotframework/RIDE/commit/c2b6c65ae5e5b0c914d48c8a2f3e67e0915f7028#diff-080617b7b2d664f4a77ee560725d0009) has removed the tag wrapping functionality. As such, tags that exceed window width are not displayed.

**Comment by HelioGuilherme66** [comment]
@Nyral Please add a screenshot of an example. Thanks.

**Comment by Nyral** [comment]
Here you go:

![tag wrap](https://user-images.githubusercontent.com/39315668/55926931-e9545000-5c1b-11e9-852a-d1df97477f86.jpg)

Thanks for looking into it!

**Comment by HelioGuilherme66** [comment]
Fixed by #1929
