### ISSUE TITLE
Ride keyword autocomplete or auto suggestion not working

### ISSUE THREAD

**Issue by arpansar** [robotframework/RIDE#1877]

**Comment by arpansar** [comment]
I can run tests but when i am writing a keyword  and clicking crtl+space it is not showing auto complete.

**Comment by HelioGuilherme66** [comment]
If you are using Windows it must be Ctrl+Alt+Space

**Comment by arpansar** [comment]
yes solved.Thank you so much.

**Comment by ravichandrakk** [comment]
Thank you even I had the same issue

**Comment by HelioGuilherme66** [comment]
@arpansar @ravichandrakk Future versions will have this fixed and we go back to Ctrl-Space on Windows.
