### ISSUE TITLE
Keyword suggestion on updated RIDE (1.7.3.1) working by using 'Alt + Space' instead of 'Ctrl + Space'

### ISSUE THREAD

**Issue by imranreee** [robotframework/RIDE#1878]
Keyword suggestion on updated RIDE (1.7.3.1) working by using **'Alt + Space'** instead of **'Ctrl + Space'** on windows 10, at the same time it's also showing the toolbar suggestion(shown in image, please have a look).

**Note: Should work one function at a time by using 'Alt + Space'** 

![Untitled](https://user-images.githubusercontent.com/19637476/56195657-35a5f280-6057-11e9-9814-b00eec6c4499.png)

**Comment by HelioGuilherme66** [comment]
The thing is that Linux, MacOS and Windows have different combinations to call the keyword help.
(For lack of space I did not fully documented this in the Shortcut Keys help)
For Windows now is: Ctrl+Alt+Space
For Linux now is: Ctrl+Space                 (Alt+Space opens command search window)
For MacOS now is: Alt+Space                 (Command+Space opens command search window)

**Comment by imranreee** [comment]
Thank you for your quick reply and good to know that you have changed the shortcut functionality.  So, think should remove the Keyword Suggestion form **Alt + Space**, otherwise user will be confused like me.

**Comment by kiccsepi** [comment]
Please also note, that keyword tooltips no longer appear in setup and teardown settings.
(Entering to the user keyword definition by <ctrl + click> still works.)

**Comment by Nyral** [comment]
I'll see what I can do.

**Comment by Nyral** [comment]
Ok, so it seems that `CmdDown()` does not work when RIDE is started with `pythonw.exe`.

**Comment by Nyral** [comment]
@imranreee Ok, so it's not working because `Ctrl-Space` is now also registered for `Text Edit` and it seems to be conflicting. As a temporary solution, you can disable `Text Edit` if you want it to work.
