### ISSUE TITLE
Error when install v1.7.3.1 on mac

### ISSUE THREAD

**Issue by MEWTWOLIU** [robotframework/RIDE#1882]
when I install v1.7.3.1 on my mac ,it will print like this:

Collecting Pywin32 (from robotframework-ride==1.7.3.1)
  Could not find a version that satisfies the requirement Pywin32 (from robotframework-ride==1.7.3.1) (from versions: )
No matching distribution found for Pywin32 (from robotframework-ride==1.7.3.1)

     I think it because that the ride has two parts ,one is for macOS,the other is for windows,and when i install it ,the part of macOS can be finished easily,but the part for windows can`t,because we can`t find the windows system on a mac of course~  so at last the installation was interrupted by this bug.

    Of course I try your "two step" method (pip install -U -r https://raw.githubusercontent.com/robotframework/RIDE/master/requirements.txt
pip install -U robotframework-ride), but it doesn`t work for now.

**Comment by pjgois** [comment]
Same here!
