### ISSUE TITLE
running error

### ISSUE THREAD

**Issue by hztgz** [robotframework/RIDE#1885]
$ pip install --pre --upgrade robotframework-ride
DEPRECATION: Python 2.7 will reach the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 won't be maintained after that date. A future version of pip will drop support for Python 2.7.
Collecting robotframework-ride
  Downloading https://files.pythonhosted.org/packages/d0/81/951aa64195b0c16e469f65b7dc47da4d84aeb12f1b2b890ab73bab2e3455/robotframework-ride-2.0a1.tar.gz (576kB)
    100% |████████████████████████████████| 583kB 2.9MB/s 
Building wheels for collected packages: robotframework-ride
  Building wheel for robotframework-ride (setup.py) ... done
  Stored in directory: /Users/tonytang/Library/Caches/pip/wheels/51/03/bc/c8e9ae7425de6776430b2e361091b4a7b7c788306673ebdafd
Successfully built robotframework-ride
Installing collected packages: robotframework-ride
  Found existing installation: robotframework-ride 1.7.3
    Uninstalling robotframework-ride-1.7.3:
      Successfully uninstalled robotframework-ride-1.7.3
Successfully installed robotframework-ride-2.0a1
$ pip list
DEPRECATION: Python 2.7 will reach the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 won't be maintained after that date. A future version of pip will drop support for Python 2.7.
Package                        Version   
------------------------------ ----------
certifi                        2018.11.29
chardet                        3.0.4     
idna                           2.8       
natsort                        6.0.0     
Pillow                         5.4.1     
pip                            19.0.2    
pycrypto                       2.6.1     
Pygments                       2.3.1     
PyMySQL                        0.9.3     
PyPubSub                       3.3.0     
requests                       2.21.0    
robotframework                 3.1.1     
robotframework-databaselibrary 1.2       
robotframework-excellibrary    0.0.2     
robotframework-requests        0.5.0     
robotframework-ride            2.0a1     
robotframeworklexer            1.1       
setuptools                     40.8.0    
six                            1.12.0    
urllib3                        1.24.1    
wheel                          0.33.0    
wxPython                       4.0.4     
xlrd                           1.2.0     
xlutils                        2.0.0     
xlwt                           1.3.0     
$ ride.py
wxPython not found.
You need to install wxPython 2.8.12.1 or 3.0.2 or newer with unicode support to run RIDE. wxPython can be downloaded from http://sourceforge.net/projects/wxpython/files/wxPython/

**Comment by HelioGuilherme66** [comment]
@hztgz That is a problem I detected after the release. I must explicitly indicate the alpha version, like in:
```
pip install --pre --upgrade robotframework-ride==1.7.4a1
```
