### ISSUE TITLE
Disabled RIDE Log plugin because of error when opened a folder

### ISSUE THREAD

**Issue by HelioGuilherme66** [robotframework/RIDE#1886]
After opening a Test Suite folder, it failed and in next restart of RIDE the RIDE Log plugin is disabled:
![image](https://user-images.githubusercontent.com/2866630/56891504-9a5c4680-6a74-11e9-8653-06df97db8fb2.png)

Windows 10
Python 3.7.2
v1.7.4a1

**Comment by Nyral** [comment]
Did you open RIDE with pythonw? I sometimes get that, but only when I open with pythonw. Seems to occur more frequently when there's another instance open.

**Comment by HelioGuilherme66** [comment]
More info:
1. Open a test suite folder (used one from recent files list)
2. Run, Edit, Save, normal operations
3. Open a test suite file from File Explorer
4. Run, Edit, Save, normal operations
5. Re-Open the test suite folder (from recent files list)
6. Close RIDE
7. Start RIDE (I use desktop shortcut with `pythonw` on Windows 10)
8. The RIDE Log plugin becomes disabled
@Nyral Would you try to reproduce?
(How to fix: Open a test suite file, to be reopened at start; Close RIDE; Edit settings.cfg and Enable ride_log plugin)

**Comment by HelioGuilherme66** [comment]
Seems to be fixed already.
