### ISSUE TITLE
After upgrading RIDE to 2.0a1, RIDE cannot find wxpython

### ISSUE THREAD

**Issue by technigirl** [robotframework/RIDE#1887]
I just upgraded RIDE per the instructions in the release notes: pip install --pre --upgrade robotframework-ride

After this upgrade, running ride.py results in the following error:
wxPython not found.
You need to install wxPython 2.8.12.1 or 3.0.2 or newer with unicode support to run RIDE. wxPython can be downloaded from http://sourceforge.net/projects/wxpython/files/wxPython/

I have version 4.0.4 of wxpython installed, and this has not changed, the old version of RIDE (1.74) ran fine.

I am running on MacOS Mojave.

**Comment by HelioGuilherme66** [comment]
@technigirl This was already reported. See my answer here: [#1885](https://github.com/robotframework/RIDE/issues/1885#issuecomment-487493419)

**Comment by technigirl** [comment]
People should title their issues better.  :P . OK, thank you, that worked for me.

**Comment by HelioGuilherme66** [comment]
@moliveras Unfortunately pip does not allow to delete versions and always considers higher numbers. That version is obsolete. Next release will be `1.7.4b1`, and since is below 2, it must always be indicated.
