### ISSUE TITLE
Outdir issue with custom date

### ISSUE THREAD

**Issue by VarunJoshi** [robotframework/RIDE#1891]
I am not sure if there is already an issue created  for this but I am having an issue to set my outdir folder name as the date with latest RIDE

I am using this as argument:
```
--outputdir C:/Users/username/Desktop/Test_logs/%date:~-4,4%%date:~-10,2%%date:~-7,2% --timestampoutputs
```
The error I see is this: 
```
unexpected error: [ ERROR ] Creating output file directory 'C:\Users\username\Desktop\Test_logs\%date:~-4,4%%date:~-10,2%%date:~-7,2%' failed: The filename, directory name, or volume label syntax is incorrect
```

**Comment by HelioGuilherme66** [comment]
OK,
I can confirm that it happens in RIDE and not in command window.
(don't know if it will hard to fix, and it is only valid for Windows, so low-prio)

**Comment by VarunJoshi** [comment]
Thanks for the update

**Comment by krishnakanth19** [comment]
I'm also facing same issue.

**Comment by krishnakanth19** [comment]
Is there any update regarding this issue.

**Comment by HelioGuilherme66** [comment]
@krishnakanth19 No, there isn't.

**Comment by HelioGuilherme66** [comment]
In progress for 1.7.4b2. At least in Linux it is possible to use shell commands:
![image](https://user-images.githubusercontent.com/2866630/64134877-bed97e00-cdda-11e9-856a-1e6a6c334443.png)

**Comment by HelioGuilherme66** [comment]
Done in Windows, too;
![image](https://user-images.githubusercontent.com/2866630/64137621-43cf9200-cdf1-11e9-8d6a-cbbaaba402fc.png)
