### ISSUE TITLE
Chinese character random code

### ISSUE THREAD

**Issue by panda62** [robotframework/RIDE#1892]
![图片](https://user-images.githubusercontent.com/40233059/57173155-d836e180-6e5d-11e9-9f11-5f46c16a32a3.png)
windows10
ride1.7.4a1
python3.6

**Comment by HelioGuilherme66** [comment]
@panda62 Thanks for reporting this.
I have been spending a lot of effort to try to keep showing the correct characters in the different operating systems and python versions. More severe than showing the wrong symbols was the impossibility to run tests in directories with non-ascii characters, and also using of test tags with those characters. I would need your collaboration to try to fix this. Please open a Command Window and enter the command: `chcp` (paste here the text). Open an interactive python3 session: `python -i` and enter the commands:
```
import sys
sys.getfilesystemencoding()
```
 (paste here the text). Thanks.

**Comment by panda62** [comment]
> 
> 
> @panda62 Thanks for reporting this.
> I have been spending a lot of effort to try to keep showing the correct characters in the different operating systems and python versions. More severe than showing the wrong symbols was the impossibility to run tests in directories with non-ascii characters, and also using of test tags with those characters. I would need your collaboration to try to fix this. Please open a Command Window and enter the command: `chcp` (paste here the text). Open an interactive python3 session: `python -i` and enter the commands:
> 
> ```
> import sys
> sys.getfilesystemencoding()
> ```
> 
> (paste here the text). Thanks.

![图片](https://user-images.githubusercontent.com/40233059/57181584-4b753d80-6ec8-11e9-9d3e-0f70ff9faa87.png)
![图片](https://user-images.githubusercontent.com/40233059/57181599-7a8baf00-6ec8-11e9-99d0-4f64e6ce83e6.png)

Can I clear the garbled settings?Thanks.

**Comment by panda62** [comment]
@HelioGuilherme66 
![图片](https://user-images.githubusercontent.com/40233059/57181757-69dc3880-6eca-11e9-8166-b31700afdc2f.png)
![图片](https://user-images.githubusercontent.com/40233059/57181759-6ea0ec80-6eca-11e9-981c-b17b7fb64338.png)

Can I clear the garbled settings?Thanks.

**Comment by HelioGuilherme66** [comment]
@panda62 Can you please install from current master:
```
pip install -U https://github.com/robotframework/RIDE/archive/master.zip
```
Then see if it fixed your problem.

If not fixed, then install this other version:
```
pip install -U https://github.com/HelioGuilherme66/RIDE/archive/fix_chinese.zip
```

**Comment by panda62** [comment]
@HelioGuilherme66 I'm so sorry，our time is out of sync, just saw the news.
current master:
 `pip install -U https://github.com/robotframework/RIDE/archive/master.zip` 
same as before;

other version:
`pip install -U https://github.com/HelioGuilherme66/RIDE/archive/fix_chinese.zip`
like this,the console above has no information
![图片](https://user-images.githubusercontent.com/40233059/57203257-13ade900-6fe1-11e9-9489-726c82715d07.png)

**Comment by panda62** [comment]
@HelioGuilherme66 Chinese garbled is still the same.

**Comment by panda62** [comment]
@HelioGuilherme66 
1.7.3.1：After I made this modification, the Chinese display is normal.
Lib/site-packages/robotide/contrib/testrunner/testrunner.py
![图片](https://user-images.githubusercontent.com/40233059/57459429-ce6e0d80-72a5-11e9-894d-98646505cbcb.png)

1.7.4a1：Originally mbcs
![图片](https://user-images.githubusercontent.com/40233059/57459613-273da600-72a6-11e9-89c8-daf22bc2e30e.png)
But the first row of the console shows normal
![图片](https://user-images.githubusercontent.com/40233059/57459718-53592700-72a6-11e9-8c73-854d25e76a82.png)

**Comment by HelioGuilherme66** [comment]
Thanks for the info. (that line was probably working before your changes).
Well, this problem with non-ASCII characters exists a long time ago, and mostly is on Windows. Now I have fixed most important things that are:
- possible to run tests with chinese paths,
- possible to have include or exclude boxes with chinese tags,
- possible to have arguments with --include or --exclude chinese tags

The Log and Report still show correct symbols.
(so users can still run the tests, even if the outputs don't show correctly)

Will continue to try to fix, but other issues are first for now.

**Comment by panda62** [comment]
Okay thank you！

**Comment by panda62** [comment]
@HelioGuilherme66 Sorry to bother you again. this problem has been solved.
Lib\site-packages\robotide\contrib\testrunner\testrunnerplugin.py
![图片](https://user-images.githubusercontent.com/40233059/57503646-90afca00-7323-11e9-8fb2-cf3f2cfe27b2.png)
Chinese is now displayed normally in both CMD and RIDE.
Normal display in CMD before modification but not normal in RIDE.

**Comment by Nyral** [comment]
@panda62 Hi. Can you provide a txt file with the text that wasn't being displayed correctly? I may have have an idea about how it can be fixed.

**Comment by HelioGuilherme66** [comment]
@Nyral You can use my test example here: [https://robotframework.transformidea.com/playground/emoji.zip](https://robotframework.transformidea.com/playground/emoji.zip)

**Comment by Nyral** [comment]
@HelioGuilherme66 On windows the emoji test causes word wrap in grid to fail
`Traceback (most recent call last):
  File "C:\Python37\lib\site-packages\robotide\editor\cellrenderer.py", line 68, in Draw
    text = self._wordwrap(text, suggest_width, dc, breakLongWords=False)
  File "C:\Python37\lib\site-packages\robotide\editor\cellrenderer.py", line 46, in _wordwrap
    if line[idx] == ' ':
IndexError: string index out of range`

**Comment by panda62** [comment]
> 
> 
> @panda62 Hi. Can you provide a test file with the text that wasn't being displayed correctly? I want to test something.

I don't know how to give it to you. Can I post it directly in this message box?

**Comment by Nyral** [comment]
Sure. As long as it's not any sensitive information.

**Comment by Nyral** [comment]
@panda62 Nevermind. I think I may have found the cause.
Try adding this to your enviromental variables.
`PYTHONIOENCODING=utf8`

![REVISED-SYSTEM-PROPERITIES](https://user-images.githubusercontent.com/39315668/58673392-d9233c00-8353-11e9-81ed-a8e707f12d5b.png)

**Comment by panda62** [comment]
> 
> 
> @panda62 Nevermind that. I think I may have found the cause.
> Try the test with this added to your environmental variables.
> `PYTHONIOENCODING=UTF-8`
> 
> ![REVISED-SYSTEM-PROPERITIES](https://user-images.githubusercontent.com/39315668/58673508-4505a480-8354-11e9-864a-a5cd4ae81412.png)

After I set it up according to the method you said, I just executed this use case and the path is also Chinese.
![图片](https://user-images.githubusercontent.com/40233059/58675519-41d7dc00-8387-11e9-828e-f24ab4e8b444.png)

[测试中文编码问题.txt](https://github.com/robotframework/RIDE/files/3239318/default.txt)

**Comment by HelioGuilherme66** [comment]
Using the new development version, allows to change Font type in TestRunner, and with the env var set, the output is OK:
![image](https://user-images.githubusercontent.com/2866630/58707901-2207de80-83ae-11e9-8fda-552465df5b36.png)
Maybe @panda62 you are using the modified version of RIDE. Try to install the one from master.

**Comment by clclclclclclcl** [comment]
> @ HelioGuilherme66很抱歉再次打扰你。这个问题已经解决了。
> Lib \ site-packages \ robotide \ contrib \ testrunner \ testrunnerplugin.py 中文现在通常在CMD和RIDE中显示。 修改前在CMD中正常显示，但在RIDE中不正常。
> ![图片](https://user-images.githubusercontent.com/40233059/57503646-90afca00-7323-11e9-8fb2-cf3f2cfe27b2.png)
我按照你的方式修改以后，中文乱码问题全部解决，你是没有解决吗？

**Comment by Tony36051** [comment]
> Using the new development version, allows to change Font type in TestRunner, and with the env var set, the output is OK:
> ![image](https://user-images.githubusercontent.com/2866630/58707901-2207de80-83ae-11e9-8fda-552465df5b36.png)
> Maybe @panda62 you are using the modified version of RIDE. Try to install the one from master.

ver: robotframework-ride-1.7.4b1.dev1
py: py3.7
os: win7
OnTimer function will call AppendText with enc=True, which will cause encode error to RIDE in python3.   
After adding condition as pic below, it works in my situation. But I'm not sure if introducing other bug
![image](https://user-images.githubusercontent.com/3116066/62419222-c3acf400-b6ad-11e9-8183-a3700bf537da.png)

**Comment by HelioGuilherme66** [comment]
@Tony36051 That is an improvement for the Log window, but not for the Output window. Any way, it is a good suggestion and we need to make different writers for each window.
This is with your fix at line 551 (Output not OK, Log OK):
![image](https://user-images.githubusercontent.com/2866630/62471135-e580a680-b793-11e9-8d64-289a1dda15c9.png)

This is the development version (Output OK, Log not OK):
![image](https://user-images.githubusercontent.com/2866630/62471267-3f816c00-b794-11e9-96fd-2160f0c76d26.png)

@Nyral Do you want to take a look at this?

**Comment by Nyral** [comment]
@HelioGuilherme66 Looks like it's because we try to use the system's encoding (which could be anything!!). We need to make a one size fits all solution. `_AppendText` needs to be refactored entirely, it's a mess.

**Comment by HelioGuilherme66** [comment]
> @HelioGuilherme66 Looks like it's because we try to use the system's encoding (which could be anything!!). We need to make a one size fits all solution. `_AppendText` will have to be refactored entirely, it's a mess.

I agree.

**Comment by HelioGuilherme66** [comment]
This issue is considered fixed because the Output window shows correctly the characters.
For the other Log window was created #1983 .
