### ISSUE TITLE
The keyword in Resource can't  be Rename，if you modified and saved, the system will be broken!

### ISSUE THREAD

**Issue by 1369937822lxy** [robotframework/RIDE#1895]
environment:
ride  1.7.4a1  
mac  64bit
python  3.7.3

![图片](https://user-images.githubusercontent.com/47801803/57191344-119f4800-6f57-11e9-85cf-4293ef5057df.png)

**Comment by HelioGuilherme66** [comment]
@1369937822lxy Can you please install from current master:
```
pip install -U https://github.com/robotframework/RIDE/archive/master.zip
```
And see if the problem still happens?
Thanks.

**Comment by 1369937822lxy** [comment]
install successfully.
however,the problem still exist.
![image](https://user-images.githubusercontent.com/47801803/57203661-8bc9de00-6fe4-11e9-91e4-b5b4ceb900c4.png)

**Comment by Nyral** [comment]
@1369937822lxy Can you describe what happens? Does RIDE crash?

**Comment by Nyral** [comment]
@1369937822lxy Can you describe what happens? Does RIDE crash after renaming?
