### ISSUE TITLE
The test case where not used in suite can't be delete.if you open RIDE again,the tes case will be  still

### ISSUE THREAD

**Issue by 1369937822lxy** [robotframework/RIDE#1896]
environment:
ride 1.7.4a1  
mac 64bit
python 3.7

![image](https://user-images.githubusercontent.com/47801803/57191397-adc94f00-6f57-11e9-9438-64d532825be1.png)

**Comment by HelioGuilherme66** [comment]
@1369937822lxy Can you please install from current master:
```
pip install -U https://github.com/robotframework/RIDE/archive/master.zip
```
And see if the problem still happens?
Thanks.

**Comment by 1369937822lxy** [comment]
First selected ，then deleted, this test case will be delete  successfully. It‘s belong to operation question.
thank you very much!
