### ISSUE TITLE
Deleting a tag causes RIDE to crash

### ISSUE THREAD

**Issue by Nyral** [robotframework/RIDE#1900]
I'm unable to debug this one, RIDE doesn't throw any error when it crashes.
Any ideas?

Note: Please check this issue on your machine too.

**Comment by HelioGuilherme66** [comment]
Is it always reproducible?
Was an existing test file, with existing tag?
Was a new test file ir a recently added tag?
(in your tests, you shown that there are a lot of tags, maybe more than 6, was this the case?)

If you can create a small test file that always cause the crash on your system, please attach. Thanks.

**Comment by Nyral** [comment]
Number of tags or if it was recently added doesn't matter. It always crashes when I delete a tag, no matter the circumstances.

**Comment by HelioGuilherme66** [comment]
OK, now I confirm that it happens in Windows 10 with Python 3.7.2. And also on MacOS 10.14 with Python 3.7.3.

**Comment by HelioGuilherme66** [comment]
Fixed by #1908
