### ISSUE TITLE
Issues reported in google group

### ISSUE THREAD

**Issue by HelioGuilherme66** [robotframework/RIDE#1906]
We are seeing below issues in 1.7.4a1

1. Renaming Keywords is making RIDE to crash.
2. Renaming Resource file is making RIDE to hang. (reported earlier)
3. RIDE is converting new FOR loop syntax back to old syntax ':FOR' and removing 'END' marker at the end of FOR loop.
4. How do i convert .tsv files to .resource files? Tried manually renaming the extensions but RIDE is removing the indention without adding END marker. Even if i add explicitly it is removing.

Could you Please take a look at these issues. Thanks in advance.

**Comment by Nyral** [comment]
Are these for windows 10 or 7 or both?

**Comment by Nyral** [comment]
1 & 2: To clarify, this is only happening on MacOS and Win10?
4: I don't understand this one. Can you present this better? Or link me to the original report.

**Comment by HelioGuilherme66** [comment]
@Nyral I did try with Windows 10 on Python 3.7.2 and *new* wxPython 4.0.5 and did not see any crash.
Please try with new wxPython (I used current development version of RIDE).

**Comment by Nyral** [comment]
@HelioGuilherme66 I upgraded wxPython and it still crashes for me....
Right now I have Python 3.7.3 and wxPython 4.0.6.

I'm going to make a VM with Windows 10 and check this on separate install.

**Comment by HelioGuilherme66** [comment]
This should be fixed now.
