### ISSUE TITLE
RIDE does not allow to create .resource resource files extension

### ISSUE THREAD

**Issue by himperion92** [robotframework/RIDE#1909]
Since robotframework-3.1.1 you can use new ".resource" extension but RIDE does not allow to create this type of file netiher to import it as an external resource. Release notes: https://github.com/robotframework/robotframework/blob/master/doc/releasenotes/rf-3.1rc2.rst#new-resource-extension-for-resource-files

This issue has been reproduced in robotframework-ride-1.7.3.1 running on Python 2.7.16.

**Comment by HelioGuilherme66** [comment]
Fixed by #1921
