### ISSUE TITLE
RIDE hangs on first right-click on test cases/Suites  

### ISSUE THREAD

**Issue by MARK30** [robotframework/RIDE#1910]
RIDE gets hanged on when i right click on test cases or suites , and it remained in hanged position until i left click somewhere . this leads to productivity issues.

Thanks.

**Comment by Nyral** [comment]
When you first click/right click on a Suite, RIDE parses it and checks keyword imports.

If you have a very complex import structure, then it will take a lot of time.

**Comment by MARK30** [comment]
what good practices can i follow to make my import structure as light as possible?

**Comment by MARK30** [comment]
But this behavior causes our system to freeze for a few seconds.
