### ISSUE TITLE
Two edit issues

### ISSUE THREAD

**Issue by imgoat** [robotframework/RIDE#1913]
ride:1.7.4a1
os:win10 1905

issue 1:
gride editor autosize function only work if the first line is comment;
work
![图片](https://user-images.githubusercontent.com/50667159/57818791-27fb9e00-77b8-11e9-9df3-52b5e7f3a16f.png)
not work
![图片](https://user-images.githubusercontent.com/50667159/57818816-46fa3000-77b8-11e9-97ea-d353d1ecec02.png)

issue 2:
after save in text editor,the window scroll back to top,hope it can stay at cursor's last place.

**Comment by HelioGuilherme66** [comment]
@imgoat Please see if changing the options in Tools > Preferences > Grid Editor would help.

**Comment by imgoat** [comment]
for issue 1：
if disable word wrap and auto size rows，it's better
![图片](https://user-images.githubusercontent.com/50667159/57895822-33b29780-7880-11e9-91b9-641f8bf92dd9.png)

now I think the issue is because of each line of my keyword is begin with “execute command” grid，with a space between the two words；

not all begin with  “execute command” grid
![图片](https://user-images.githubusercontent.com/50667159/57896408-395dac80-7883-11e9-8b12-27eeff7b6110.png)

all begin with  “execute command” grid
![图片](https://user-images.githubusercontent.com/50667159/57896441-598d6b80-7883-11e9-9e52-c955e20b1936.png)
 
for issue 2：
no options for this issue。
its happen from RIDE version 1.7.3.1。
version 1.5.2.1 was ok；
