### ISSUE TITLE
Unable to import WindowsControl

### ISSUE THREAD

**Issue by pradeepbantu** [robotframework/RIDE#1925]
Hi Experts,

I am getting error message in ride log and hence i am unable to import WindowsControl
20190523 16:36:59.339 [INFO]: Failed to read keywords from library db:

20190523 16:36:59.395 [WARN]: Library import handling threw an unexpected exception

Traceback (most recent call last):
table libraries has 5 columns but 4 values were supplied
File "C:\Python27\lib\site-packages\robotide\spec\librarymanager.py", line 40, in run
if not self._handle_message():
File "C:\Python27\lib\site-packages\robotide\spec\librarymanager.py", line 66, in _handle_message
self._handle_insert_keywords_message(message)
File "C:\Python27\lib\site-packages\robotide\spec\librarymanager.py", line 95, in _handle_insert_keywords_message
lambda res: result_queue.put(res, timeout=3))
File "C:\Python27\lib\site-packages\robotide\spec\librarymanager.py", line 99, in _insert
library_name, library_args, keywords or [])
File "C:\Python27\lib\site-packages\robotide\spec\librarydatabase.py", line 84, in insert_library_keywords
lib = self._insert_library(library_name, library_arguments, cur)
File "C:\Python27\lib\site-packages\robotide\spec\librarydatabase.py", line 111, in _insert_library
cursor.execute('insert into libraries values (null, ?, ?, ?)', (name, unicode(arguments), time.time()))

Please help.

Thanks

**Comment by HelioGuilherme66** [comment]
Does this give you an idea of what is happening?

> table libraries has 5 columns but 4 values were supplied

What is this your are talking about?

> i am unable to export WindowsControl

What is the Library? How is it imported? Is there something wrong with that library? If you use it from command line `robot` will it work?

**Comment by pradeepbantu** [comment]
I am trying to import WindowsControl library 

![image](https://user-images.githubusercontent.com/37433888/58261135-6c6ed700-7d80-11e9-91a4-b69e5e0c1054.png)

that is not imported yet , i guess.

i just run import WindowsControl for importing at that time it did not give any error.
Above errors coming at the time of library addition.

**Comment by HelioGuilherme66** [comment]
@pradeepbantu You don't mention what version of RIDE you have (usually you should give that info).

If you have RIDE 1.5.2.1 and you installed the newer version, then to solve that, if you want to still use version 1.5.2.1 of RIDE, you have to delete the librarykeywords.db file (in the ride configuration folder).

**Comment by pradeepbantu** [comment]
Thanks , it works.
