### ISSUE TITLE
Ride don't have permissions to open .pem file?

### ISSUE THREAD

**Issue by krishnakanth19** [robotframework/RIDE#1931]
I have designed a keyword, which will return a encrypted data using a public key.
When, I run that .py file command prompt it is working fine and it is returning the encrypted data.
But, when I call same keyword from Ride, it is throwing the following error.

Can't open test.pem for reading, No such file or directory
140395350397376:error:02001002:system library:fopen:No such file or directory:../crypto/bio/bss_file.c:74:fopen('test.pem','r')
140395350397376:error:2006D080:BIO routines:BIO_new_file:no such file:../crypto/bio/bss_file.c:81:
unable to load Public Key 

I'm using RIDE 1.4.1 running on Python 2.7.14.  on Windows.

**Comment by HelioGuilherme66** [comment]
The error is `No such file or directory:../crypto/bio/bss_file.c:74:fopen('test.pem','r')`
When you run from RIDE you should use full path or relative to ${CURDIR}.
Did you run from console with `robot`? Try to run `robot` from a different path where your test file is, probably would get the same error.

**Comment by krishnakanth19** [comment]
It's not working... I've tried giving relative path like './test.pem'. It is working from IDLE but, the same keyword is not working from RIDE. Please find the below screen shot. I try to give the full path, its not working.

for Relative Path:

![image](https://user-images.githubusercontent.com/23556113/58778229-61713d80-85ef-11e9-9a69-f6d85d400938.png)

![image](https://user-images.githubusercontent.com/23556113/58778255-79e15800-85ef-11e9-81b0-8f83e89f1da9.png)

**Comment by HelioGuilherme66** [comment]
@krishnakanth19 Only by chance I saw your message on a closed issue. For questions you should ask in Slack, or Google Group, or StackOverflow.

Now I see you are using cygwin and python 2.7. I don't know if that would work for a `robot` library. Also when using cygwin, the paths changes like `/c/users/...`. Are you sure you used the correct path?
One thing is running a python script from IDE, like pyCharm or IDLE, another is using as a library in `robot`. You should make sure your tests run in the command window/shell, using the `robot` command.

**Comment by krishnakanth19** [comment]
I have resolved the issue. I'm using bash. So, when I launch bash, it is opening in different directory. So, I have moved to home directory. And I have placed .pem file in System32 directory in Windows. And its working fine.
