### ISSUE TITLE
No tests selected message

### ISSUE THREAD

**Issue by povar81** [robotframework/RIDE#1933]
I'm using custom script with ride in execution profile.
I run cases using tags like this:
-i tagname 
hence I don't need to select (tick) any case.
But  I always get the window saying no tests selected.
It wasn't like that in older versions for python 2, I was able to run cases using only tags, without selecting  cases in RIDE (by ticking them).

**Comment by HelioGuilherme66** [comment]
@povar81 You are correct. This is an improvement, I considered already. We can have detection of -i or -e flags and do not ask to proceed. We should also have a switch for the feature.

**Comment by povar81** [comment]
Thank you.
So are you going to include this fix into the next release? 
And when is it going to be ?

**Comment by HelioGuilherme66** [comment]
@povar81 You can now test the feature by `pip install -U https://github.com/robotframework/RIDE/archive/master.zip`
It will go in future 1.7.4 (no date planned).

**Comment by povar81** [comment]
Thank you, It works after disabling(unticking) option "asks for confirmation to run all tests if none selected".
