### ISSUE TITLE
Importing Scapylibrary using ride is unsuccessful

### ISSUE THREAD

**Issue by handa417** [robotframework/RIDE#1934]
Use the ride to import the ScapyLibrary report red prompt, and the keywords in ScapyLibrary can be used. The log and installation environment of the ride is as follows:

E:\Python37\Scripts>pip list
Package                         Version
------------------------------- -------
numpy                           1.16.3
Pillow                          6.0.0
pip                             19.1.1
Pygments                        2.4.1
PyPubSub                        3.3.0
pywin32                         224
robotframework                  3.1.2
robotframework-ftplibrary       1.6
robotframework-ride             1.7.4a1
robotframework-ScapyLibrary     0.1.5
robotframework-selenium2library 3.0.0
robotframework-seleniumlibrary  3.3.1
robotframeworklexer             1.1
scapy                           2.4.2
selenium                        3.141.0
setuptools                      40.8.0
six                             1.12.0
urllib3                         1.25.3
wxPython                        4.0.6

20190603 18:53:50.455 [INFO]: Found Robot Framework version 3.1.2 from E:\Python37\lib\site-packages\robot.

20190603 18:53:50.455 [INFO]: Started RIDE 1.7.4a1 using python version 3.7.3 with wx version 4.0.6 in win32.

20190603 18:54:35.170 [WARN]: Importing test library "ScapyLibrary" failed

Traceback (most recent call last):
Importing test library 'ScapyLibrary' failed: SyntaxError: invalid syntax (__init__.py, line 34)
Traceback (most recent call last):
  File "E:\Python37\lib\site-packages\robotide\lib\robot\utils\importer.py", line 153, in _import
    return __import__(name, fromlist=fromlist)
PYTHONPATH:
  E:\Python37\python37.zip
  E:\Python37\DLLs
  E:\Python37\lib
  E:\Python37
  E:\Python37\lib\site-packages
  E:\Python37\lib\site-packages\win32
  E:\Python37\lib\site-packages\win32\lib
  E:\Python37\lib\site-packages\Pythonwin
  E:\Python37\lib\site-packages\robotide\spec
  E:\Python37\lib\site-packages\robotide\lib
  E:\Python37\lib\site-packages\robotide\contrib\testrunner\../../lib
  E:\Python37\lib\site-packages\robotide\contrib\testrunner\../../lib
  File "E:\Python37\lib\site-packages\robotide\spec\librarymanager.py", line 87, in _fetch_keywords
    return get_import_result(path, library_args)
  File "E:\Python37\lib\site-packages\robotide\spec\libraryfetcher.py", line 24, in get_import_result
    lib = robotapi.TestLibrary(path, args)
  File "E:\Python37\lib\site-packages\robotide\lib\robot\running\testlibraries.py", line 50, in TestLibrary
    return_source=True)
  File "E:\Python37\lib\site-packages\robotide\lib\robot\utils\importer.py", line 72, in import_class_or_module
    self._raise_import_failed(name, err)
  File "E:\Python37\lib\site-packages\robotide\lib\robot\utils\importer.py", line 109, in _raise_import_failed
    raise DataError('\n'.join(msg))

**Comment by HelioGuilherme66** [comment]
@handa417 Some libraries do dynamic loading of keywords, so we need to generate a spec doc. You can follow the instructions on RIDE->Import Failed Help, and resolve your problem. See below my resolution:
![image](https://user-images.githubusercontent.com/2866630/58803882-6989a700-8608-11e9-9409-46189580892c.png)

Maybe the author should have a spec file on his project:
[ScapyLibrary.zip](https://github.com/robotframework/RIDE/files/3247685/ScapyLibrary.zip)
