### ISSUE TITLE
Problems with 'Run Keyword If' condition

### ISSUE THREAD

**Issue by BenjiRyan** [robotframework/RIDE#1937]
Hey Guys, i need your help. 
In my RobotFramework-Code i am using the Telnet 'Read' Keyword to get some informations which get saved into a variable immediately. 

To cut the information and only get the important information i created the following keyword:
![image](https://user-images.githubusercontent.com/33459831/58884657-1f282900-86e1-11e9-8b11-f52f63cd0aaa.png)

As you can see there is a return value/variable in the keyword above. **The cutted informations are numbers/values e.g. '123' or '1066'** and for my test i am getting three cutted informations.

After cut the specifict informations i want to calculate the difference between the first and second value and between the second and third value. But before the calculation my keyword checks conditions (gt, lt, eq), as you can see below.

![image](https://user-images.githubusercontent.com/33459831/58885999-7929ee00-86e3-11e9-9491-fb757c7b4f5b.png)

My problem is, that in case of the cutted values (e.g.) '321' (#1), '711' (#2) and '1066' (#3) RobotFramework says that the value '1066' is less than '711' and calculates '711 - 1066 = -355' and i can not find any solutions or declarations.

In the next comment i am going to add some informations about what i found out.

Thank you Guys, i hope you can help me!

**Comment by BenjiRyan** [comment]
I found out that in case of using handmade values e.g. '1066' and '0711' the calculation works after the correct condition -> '1066 - 0711 = 355'.

Is it about the length of the strings which are generated in my cutting keyword?

**Comment by HelioGuilherme66** [comment]
@BenjiRyan The purpose o GitHub RIDE issue tracker is to report bugs or suggest enhancements. If you go to robotframework.org Support you will see links for Slack channel (also here at README), and Google Groups, or you can ask in StackOverflow.

About your problem, since it is easy, you have to convert the values to numbers if want to do arithmetic. Numbers in robotframework are referenced like, for example: ${1066}. There are converting keywords.

**Comment by BenjiRyan** [comment]
@HelioGuilherme66 thanks for your answer and your reference.
I hope it is ok when i comment on your solution:

I tried to convert my return value/variable to number(s) but it also became to the same problem :(

**Comment by HelioGuilherme66** [comment]
@BenjiRyan Please post on StackOverflow (using text, not images). That way people can reproduce and help.

**Comment by BenjiRyan** [comment]
Ok now i have a solution and it works!

In my conditions i put the arguments/cutted values in quotation marks. In this case, the cutted values a convert to strings. So i have to define the conditions without quotation marks and i need to convert them to numbers with the keyword Convert To Number :)


Thanks for Help
