### ISSUE TITLE
Symbol will automatically transfer to Chinese format

### ISSUE THREAD

**Issue by shenjianyun** [robotframework/RIDE#1949]
I write automation test both on win (win10 + python 2.7.14 + robotframework 3.1.1 + robotframework-ride 1.7.3.1) and mac(Mac 10.13.6 +python 3.7.3 + robotframework 3.1.2 + robotframework-ride 1.7.3.1)
I copy the automation folder from win to Mac, then I had some strange problems, the symbols ' or ...  can not be recognized in ride, it seems to automatically transfer to ‘ and … , (I write a demo to show the issue, see screenshot)it's so strange, and I don't know why, I have to change the resource fire or text file format to txt and modify with Mac editor every times when the file have any changes every time.
screenshot1:
![screenshot1](https://user-images.githubusercontent.com/48910607/59242176-239e9580-8c3d-11e9-9530-650690064fe1.png)
![screenshot1-problem](https://user-images.githubusercontent.com/48910607/59242199-3fa23700-8c3d-11e9-8cbd-1b03663b8ff0.png)

screenshot2:
![screenshot2](https://user-images.githubusercontent.com/48910607/59242230-61032300-8c3d-11e9-87e7-7dfef5fed132.png)
![screenshot2-problem](https://user-images.githubusercontent.com/48910607/59242260-7aa46a80-8c3d-11e9-897b-40dcbbe97e27.png)

below is the edit with Mac editor and run normally:
![afterEdit](https://user-images.githubusercontent.com/48910607/59242384-e7b80000-8c3d-11e9-8937-887b61002af7.png)
![afterEditResults](https://user-images.githubusercontent.com/48910607/59242518-7a589f00-8c3e-11e9-9487-1ab4c4fa2999.png)

**Comment by HelioGuilherme66** [comment]
@shenjianyun There is an automated option in MacOS to replace some characters. Go to `System Preferences > Keyboard > Text ` and disable `Use smart quotes and dashes`.
I don't know if there is an option for the `...` but for the '´' will work.

**Comment by shenjianyun** [comment]
@HelioGuilherme66 Thank you so much! I tried and  works well both for ' ‘'  and '...' when disable the option!
