### ISSUE TITLE
info on keywords from Builtin library is not displayed

### ISSUE THREAD

**Issue by povar81** [robotframework/RIDE#1952]
In older versions of robotframework I didn't have to include Builtin library into settings, but now if I don't set 
Library           BuiltIn
keywords like should be equal are shown as black (keyword not found).
They still work when I run them even without the Library           BuiltIn in settings
it's just that info on them is not shown in edit mode.

**Comment by HelioGuilherme66** [comment]
@povar81 That is unusual situation. Probably RIDE's keywords database needs to be rebuilt. It may also happen if you are using RIDE installed in Python 2.7 and using robot from Python 3+. To fix do a reinstall of robot in the same python you use RIDE: `pythonX -m pip install -U --force robotframework` (where X is the version of python).

Please paste here the text from Tools->RIDE Log.

**Comment by povar81** [comment]
no, both ride and robot are on python 3.6, I'm using latests versions of ride and robot:
robotframework==3.1.1
robotframework-ride==1.7.4b1.dev1
wxPython==4.0.5

**Comment by HelioGuilherme66** [comment]
@povar81 I assume you don't see any errors in `Tools->RIDE Log`, since you did not paste here as requested. Still not enough information for us to reproduce or investigate.

**Comment by povar81** [comment]
sorry,  I can't reproduce it. 
I didn't change anything, maybe just restarded windows.
Right now all the keywords are displayed normally (found and info on them is shown).

**Comment by HelioGuilherme66** [comment]
OK, sometimes it takes a while to fill DB, or restarts makes them visible to RIDE.
