### ISSUE TITLE
[Wiki] Installation instructions are outdated (say Python 2.7 is required)

### ISSUE THREAD

**Issue by cmorty** [robotframework/RIDE#1956]
While reading the [installtion instructions](https://github.com/robotframework/RIDE/wiki/Installation-Instructions), I almost installed Python 2.7 before I decided it might just work with Python 3 . This is very confusing and easy to fix. Yet, as I'm not famillair with Ride yet, I did not want to mess with the Wiki.

**Comment by HelioGuilherme66** [comment]
You are correct. The instructions are really outdated. We have the Release Notes that should have more updated content, but the Wiki should be our base document. You can try to edit a copy of the Wiki and then send to us (would be better if in a Pull Request (PR) ). We would then see the differences and accept or comment on them. Please see the end of the first page of the Wiki, on how to make a copy.
![image](https://user-images.githubusercontent.com/2866630/60081594-0207d880-972a-11e9-8300-fdb273076f67.png)

**Comment by cmorty** [comment]
@HelioGuilherme66 Actually I was hoping that someone who has the correct information just edits the wiki (max 5 min) before I clone it, edit it to the best of my knowledge (which is probably not sufficient), make a merge-request, it gets reviewed, I adjust it, etc (taking more than 5 min just to get to the MR-Step).

**Comment by duohedron** [comment]
I updated the install instructions, but I cannot create a pull request to a wiki repository, so I created a new one here: https://github.com/duohedron/RIDE-wiki
@HelioGuilherme66 you can review it and merge it if you find it okay.

**Comment by HelioGuilherme66** [comment]
@cmorty @duohedron The WIKI is now updated. Thanks for reporting and proposing changes.
