### ISSUE TITLE
Different file level issues (1.7.4)

### ISSUE THREAD

**Issue by testwjz** [robotframework/RIDE#1957]
hi，When a variable is added under a folder, the test suite under the folder cannot use the variable
![image](https://user-images.githubusercontent.com/32086135/60086457-ab23f280-976d-11e9-9fa8-4c1d121f8844.png)

as shown above。
expected result ：The url1 and url variables should be automatically associated
actual result：Only the variable url in the test suite is associated, and the variable url1 in the upper folder of the test suite is not associated

PS：Do you support variables defined in files and associate them with the following test suites Or I'm using it incorrectly。

Looking forward to your reply ！

**Comment by Nyral** [comment]
You've added the variable to a directory in tree. When you do that, RIDE creates a `__init__` file for that directory. Think of it as a resource.

For the variable to be usable in the suite, you need to import the init file as resource.

**Comment by testwjz** [comment]
thanks
