### ISSUE TITLE
robotframework-ride-1.7.3.1.zip lacks requirements.txt

### ISSUE THREAD

**Issue by VladimirChukharev** [robotframework/RIDE#1960]
Installation from sources fails due to absence of a requirements.txt file in the ROOT_DIR directory.

It seems I' the first to try installing ride version 1.7.3.1 from sources ;-)

**Comment by HelioGuilherme66** [comment]
In next versions only the src package will be used to install. All source files should be in zip file.

**Comment by VladimirChukharev** [comment]
One more thing. Installation includes compiling to *.pyc files, and publish/messages3.py produces the following:
```
..../publish/messages3.py", line 27
    class RideMessage(object, metaclass=messagetype.messagetype):
                                       ^
SyntaxError: invalid syntax

```
This is with Python2.7, but "class C(..., metaclass=M):" syntax is Python3.x only.

I'm not sure this is a bug, just wanted to inform you.

**Comment by HelioGuilherme66** [comment]
It is not a bug. That is Python3 syntax (the reason that messages3.py file exists :)). Just ignore that.

**Comment by Nyral** [comment]
We will get rid of it in the future™
