### ISSUE TITLE
How to close text editor's auto wrap

### ISSUE THREAD

**Issue by k870611** [robotframework/RIDE#1966]
If the line is too long, e.g.      
    @{mylist}    Create List    ${arg1}    ${arg2}    ${arg3}    ${arg4}    ${arg5}    ${arg6}

after click "Apply Changes" button (in Text Editor tab ), Save, or Run the test case, it will auto wrap to 

    @{mylist}    Create List    ${arg1}    ${arg2}    ${arg3}    ${arg4}    ${arg5}
    ...    ${arg6} 

How do I close this function (Disable auto warp) ?
Thanks and best regard.

**Comment by Nyral** [comment]
It's done by RobotFramework. Unfortunately it can't be disabled.
I suggest you [open a ticket there](https://github.com/robotframework/robotframework/issues) for them to make an option for this.

**Comment by Nyral** [comment]
This is done by [RobotFramework tidy function](https://robot-framework.readthedocs.io/en/3.0/_modules/robot/tidy.html), which RIDE calls every time when saving.

**Comment by k870611** [comment]
Thanks Nyral, it works, thanks a lot ~~~~~~~~~~~

**Comment by HelioGuilherme66** [comment]
@k870611 Please explain what justifies the reopening of the issue.
Also it would be nice to know what code changes you did to solve the problem. Maybe we can improve Text Editor by adding an option. Thanks.

**Comment by k870611** [comment]
@HelioGuilherme66 

Like Nyral says, I change datafilewriter.py (both robotide and robot's ) line 52 (txt_column_count from 8 to 10. (txt_column_count = 8 => txt_column_count = 10)

And reopen is because I want to ask does pdb is useable in ride ??
Thanks and best regard.

**Comment by Nyral** [comment]
It's not very usable. You need to look for something else. 
I haven't found anything either. 😞
