### ISSUE TITLE
Get error "Robot Framework installation not found" when run test case with ride1.7.3.1 on mac

### ISSUE THREAD

**Issue by shenjianyun** [robotframework/RIDE#1968]
<img width="1068" alt="1" src="https://user-images.githubusercontent.com/48910607/61265522-1ee07a80-a7c3-11e9-95c8-29ad18709754.png">
when run test get error like the screenshot.
i use :
mac os 10.14.5
python 3.7.3
robotframework 3.1.2
ride 1.7.3.1
see the screen shot below:
<img width="570" alt="2" src="https://user-images.githubusercontent.com/48910607/61265629-9910ff00-a7c3-11e9-861c-c831d929d1b5.png">
i tried uninstall robotframework 3.1.2 and install 3.1.1, and this not work for me.
here is the ride log:
<img width="1100" alt="3" src="https://user-images.githubusercontent.com/48910607/61265732-25bbbd00-a7c4-11e9-8386-44afce6f891f.png">

i just run robot testcase.robot in command line,  this work normally, this so strange

**Comment by HelioGuilherme66** [comment]
@shenjianyun Something is wrong with your robotframework installation. I suspect the PATH env variable does not contain an entry to find robot. I see that RIDE did find robot 3.1.2 in the correct place, but when trying to run it did not (from the last screen capture). On the first screen capture I see you used `robot` and RIDE tried to call `pybot`, to avoid that, you should select `robot 3.1` from the drop-down list.
Please confirm that you can run `robot` from terminal with:
```
robot --version
```
Thanks.

**Comment by shenjianyun** [comment]
@HelioGuilherme66 Thanks your reply so soon, i read the issue https://github.com/robotframework/robotframework/issues/2818, i want to create a pybot.bat, but i don't know where to put it ,(on window maybe is python/tools/scripts)
in command i run robot --version and reboot--version, both it work normally, when execute pybot --version, it show command not found
the strange is:
i use a new mac whit the same robot , ride and python, everything work well on the old mac, i tried copy the ride source folder from the old mac to the current new , it works without the error!! and i don't know why
may be there are some modifies in ride souce file?? i install ride with resource file cause  when i execute below you write in other issue comment:
pip install -U -r https://raw.githubusercontent.com/robotframework/RIDE/master/requirements.txt
pip install -U robotframework-ride
it still get error like 'couldn't find a version that satisfies the requirement pywin32...'
All in all, can run test case with ride now.
i will close the issue.
