### ISSUE TITLE
error 13 permission denied 

### ISSUE THREAD

**Issue by 7thSkyServices** [robotframework/RIDE#1972]

**Comment by 7thSkyServices** [comment]
i am facing this problem mostly while using Ride.py ,, I tried a lot to solve this but all in vain .. Kindly help me and guide me , i will be very thankful to your for this  kindness ....

**Comment by HelioGuilherme66** [comment]
This is not a correct Issue report. You should ask in other places, like [StackOverflow](https://stackoverflow.com/questions/tagged/robotframework-ide), or our [Google Group](https://groups.google.com/forum/#!forum/robotframework-users) or on our [Slack channel #ride](https://github.com/robotframework/RIDE#ride).

In any of those places, you should know how to describe your problem and basic info of the versions  in use.
