### ISSUE TITLE
packing ride with pyinstaller

### ISSUE THREAD

**Issue by hyh162213** [robotframework/RIDE#1976]
The idea occurs to me that if I can pack rf-ride with pyinstaller.
I tried so hard to settle any lacking of imports or images while packing.
but when I finally finished , ride reports a resource file problem and reopen itself over again.
![image](https://user-images.githubusercontent.com/46335731/62669007-83f14f80-b9c0-11e9-8bb8-7e2d6ed68a8e.png)
Any idea where I can handle the problem?
Thanks.

**Comment by Nyral** [comment]
Go [here](https://github.com/robotframework/RIDE/blob/master/src/robotide/application/application.py) and comment line 65 (self._find_robot_installation). See if it works now.

If you share what you've made, we can turn it into an official installer.

**Comment by hyh162213** [comment]
I am glad if I could do some help.
What I 've done is just correct the relation path which may cause error after packing with pyinstaller.
But there is still bit more porblem,by your guide I tried to annotate the version check method,
It seems not to reopen again,and I soon find that ride.exe packed by pyinstaller doesn't have the button "RUN"!
Is the button "RUN" a kind of plugins or something?
sincerely.

**Comment by hyh162213** [comment]
I am glad if I could do some help.
What I 've done is just correct the relation path which may cause error after packing with pyinstaller.
But there is still bit more porblem,by your guide I tried to annotate the version check method,
It seems not to reopen again,and I soon find that ride.exe packed by pyinstaller doesn't have the button "RUN"!
Is the button "RUN" a kind of plugins or something?
sincerely.
![11](https://user-images.githubusercontent.com/46335731/62758549-53d5a980-bab1-11e9-833c-c86302a3f07f.png)

**Comment by HelioGuilherme66** [comment]
Yes, Run is a plugin (all those tabs are Plugins, but as built in). When is missing, it might indicate that was not possible to load it. Try to see RIDE Log if there is any error.
You can also go see Tools > Manage Plugins.

**Comment by hyh162213** [comment]
Log throws no error and tools->manage plugin just does not has the option "Test Runner".
Hope I can find where is the plugin's location or code path witch I can wirte in spec for pyinstaller.
![image](https://user-images.githubusercontent.com/46335731/62911991-fabf8b80-bdb8-11e9-90a0-3c8cdb8fd819.png)

**Comment by HelioGuilherme66** [comment]
Code is at: src/robotide/contrib/testrunner

**Comment by hyh162213** [comment]
thanks,I finally get over it.
though I haven't finally pack ride to  available all together,I belive I can finally made it.
The main train of thougt of me to pack ride with pyinstaller is to customize "ride.spec".
When running ride,it may load some image or plugin,lib witch pyi may miss.
the spec file is kind of config while packing app.
just add the miss resource and find the right running path can solve the problem,
or make adaption for pyi in ride code,reverse is okay either,that might be a quite project.

to customize "ride.spec",for example,
use "pyi-makespec ride" to create ride.spec
when missing run plugins,open ride.spec,add to Analysis.datas
with [('~/lib/robotide/contrib/testrunner','robotide/contrib/testrunner')
('~/lib/robotide/controller','robotide/controller')
]
and the run button can be porperly load.

**Comment by HelioGuilherme66** [comment]
@hyh162213 Are you going to have a separate project for installer, or creating a Pull Request with your suggestions?
