### ISSUE TITLE
The colon of "FOR" keyword is vanish automatic on Ride 1.7.4 

### ISSUE THREAD

**Issue by TedCobra** [robotframework/RIDE#1988]
Run the test that contain the "FOR" keyword will thowing a error of "FOR loop contains no keywords."

Env：RF==3.1.1
         ride==1.7.4
         os==win10
         python==2.7

**Comment by HelioGuilherme66** [comment]
@TedCobra Please see the [FAQ](https://github.com/robotframework/RIDE/wiki/F.A.Q.) entry about this.
(Using RF 3.1.2)

**Comment by TedCobra** [comment]
> @TedCobra Please see the [FAQ](https://github.com/robotframework/RIDE/wiki/F.A.Q.) entry about this.
> (Using RF 3.1.2)
Thx！

**Comment by TedCobra** [comment]
> @TedCobra Please see the [FAQ](https://github.com/robotframework/RIDE/wiki/F.A.Q.) entry about this.
> (Using RF 3.1.2)

Thx!

**Comment by HelioGuilherme66** [comment]
This is solved following instructions from [FAQ](https://github.com/robotframework/RIDE/wiki/F.A.Q.), i.e.:
If using `: FOR` test can be executed, but if edited it must be changed to new `FOR ... END` syntax.
