### ISSUE TITLE
Can't upgrade ride to 1.7.4b1 with pip

### ISSUE THREAD

**Issue by crystalcheng** [robotframework/RIDE#1989]
![image](https://user-images.githubusercontent.com/17669102/63916343-cdd2d000-ca6a-11e9-914b-bd39a593c6fd.png)

**Comment by HelioGuilherme66** [comment]
@crystalcheng You are correct, the package is not there yet. Please install with:
```
pip install --upgrade https://github.com/robotframework/RIDE/archive/v1.7.4b1.zip
```

**Comment by HelioGuilherme66** [comment]
Fixed now, but install instructions are not correct. The right command is:
```
pip install --upgrade robotframework-ride==1.7.4b1
```
To start RIDE one possible way is:
```
python -m robotide.__init__
```
Or run the shortcut creation script must be started with:
```
python -m robotide.postinstall -install
```

**Comment by crystalcheng** [comment]
@HelioGuilherme66 
i upgrade ride to 1.7.4b1 successfully with
`pip install --upgrade robotframework-ride==1.7.4b1`
but i can't start RIDE with
`python -m robotide.__init__` or `ride.py`
![image](https://user-images.githubusercontent.com/17669102/64104224-6daf9700-cda6-11e9-9fbe-10195d2a1e24.png)

**Comment by HelioGuilherme66** [comment]
Again, you are correct. This time was the Windows line ending messing the starter files. It is fixed now in *current* development. You can install with:
```
pip install --upgrade https://github.com/robotframework/RIDE/archive/master.zip
```
Or you can download and replace the `ride.py` file.

You are missing the `PyPubSub`module (I wonder why it was not installed with RIDE, because it is a dependency).
You can install dependencies manually with:
```
sudo pip install -r https://github.com/robotframework/RIDE/raw/master/requirements.txt
```

**Comment by HelioGuilherme66** [comment]
@crystalcheng Please upgrade to Beta 2:
```
pip install --upgrade robotframework-ride==1.7.4b2
```
There should not be problems now.
