### ISSUE TITLE
Reset changes after validation

### ISSUE THREAD

**Issue by tjsrocha94** [robotframework/RIDE#1996]
When I save and the pop-up alerting for syntax error and asking if I want to reset changes shows up, some times I click 'No' and RIDE resets the changes anyway.

**Comment by tjsrocha94** [comment]
RIDE Version: 1.7.3.1

**Comment by HelioGuilherme66** [comment]
@tjsrocha94 CONGRATULATIONS! You found a bug long time known by me. I was waiting for some user to report it. Sorry for the inconvenience.

**Comment by HelioGuilherme66** [comment]
Let me add that the issue is always reproductible, by:

1. Change the file causing validation error in Text Editor,
2. Save the file by using menu, or shortcut Ctrl-S,
3. The pop-up appears and replying No, would still revert the changes.

**Comment by tjsrocha94** [comment]
No problem. I am happy to help :)

**Comment by HelioGuilherme66** [comment]
Fixed by #1998
