### ISSUE TITLE
New Test Suite name is changed after first save

### ISSUE THREAD

**Issue by tjsrocha94** [robotframework/RIDE#1997]
When I create a new Test Suite and edit it, after the first time I save it RIDE changes its name and loses its format.

**Comment by HelioGuilherme66** [comment]
Please install 1.7.4b1 and see if the same problem happens.
```
pip install -U robotframework-ride==1.7.4b1
```

**Comment by tjsrocha94** [comment]
I tried and it doesn't. Will keep using this one :)
Thank you.
