### ISSUE TITLE
Changing Preferences Does Not Allow You To change The White Background Or Empty Keyword Spaces

### ISSUE THREAD

**Issue by irmike** [robotframework/RIDE#2000]
In an attempt to make a full dark themed IDE, I tried using the User Preferences only to find out it is limited and can not set the full background to black. Some sections, like the documentation background, the test suites section, and the edit background can not be changed to black or any other color.

**Comment by Nyral** [comment]
A ticket for creating a dark theme exists already. See #1678.
If it bothers you that much, then you can just invert the screen colors.
