### ISSUE TITLE
There are 2 locations for "settings.cfg" and one isn't used at all

### ISSUE THREAD

**Issue by irmike** [robotframework/RIDE#2001]
Location 1: \AppData\Roaming\RobotFramework\ride

Location 2: C:\DeploymentUnit\Python\Lib\site-packages\robotide\preferences

Location 1 is actually used and changed by Ride but any changes to Location 2 do not affect Ride and vice-versa.

**Comment by Nyral** [comment]
Location 2 file is used to initialize Location 1 file when RIDE is first started on a new PC.
