### ISSUE TITLE
`pip install robotframework-ride` not working on Ubuntu 18.04.3 LTS

### ISSUE THREAD

**Issue by ragreenburg** [robotframework/RIDE#2004]
When typing in `pip install robotframework-ride`into the command line I get the error:
`Could not find a version that satisfies the requirement Pywin32 (from robotframework-ride) (from versions: )`
`No matching distribution found for Pywin32 (from robotframework-ride)`

**Comment by HelioGuilherme66** [comment]
@ragreenbug This problem is solved already in current Beta version. Install with
```
pip install robotframework-ride==1.7.4b2
```

**Comment by ragreenburg** [comment]
When running that I get the error at the end:
`Command "/home/greenbur/anaconda3/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-install-d2kq42xd/wxPython/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-record-r15ejuag/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-install-d2kq42xd/wxPython/`

**Comment by HelioGuilherme66** [comment]
@ragreenburg See the release notes ([here](https://github.com/robotframework/RIDE/blob/master/doc/releasenotes/ride-1.7.4.rst). There is a recommendation for Linux users to install first wxPython from their site.

**Comment by ragreenburg** [comment]
When doing that I get past that error but trying to run it with the `python -m robotide.__init__` command, which is listed on the release notes, I get a long error that ends with `AttributeError: 'ImportError' object has no attribute 'message'`

**Comment by HelioGuilherme66** [comment]
Is that the same python as:
 ```/home/greenbur/anaconda3/bin/python ```

Because I am sure that Ubuntu has python installed by default.
Other problem maybe, RIDE did not install correctly. Looks like is missing PyPubSub. Now that you have wxPython, you should reinstall RIDE (use `--force`).

Can't you use Slack for communication?

**Comment by ragreenburg** [comment]
I believe it is, yes. I tried reinstalling while using `--force` and it gives the error of `  ERROR: Could not find a version that satisfies the requirement Pywin32 (from robotframework-ride) (from versions: none)`
`ERROR: No matching distribution found for Pywin32 (from robotframework-ride)`
I don't have Slack but I can get it set up if you think it'll make this easier/smoother?

**Comment by HelioGuilherme66** [comment]
So, you forgot to add the Beta version!
Use the command:
```
pip install --force -U robotframework-ride==1.7.4b2
```
For Slack you only need to use the browser after registration, see README.rst on this project page.
