### ISSUE TITLE
TestRunner arguments are not reparsed if they are modified

### ISSUE THREAD

**Issue by Nyral** [robotframework/RIDE#2008]
You have to restart RIDE for it to use the modified arguments

Steps to reproduce:
1. Go to `Run` tab
2. Write some arguments (e.g. `-d 123456789`)
3. Run test (report is generated with name `123456789`)
4. Modify arguments (e.g. `-d 1234` )
4. Run test (report is generated with same name at step 3)

RIDE version: 1.7.4rc1.dev
wxPython version: 4.0.6
OS: Windows 10

Notes: 
- `-d` is argument for setting test report name
- not reproducible on linux, so issue might have been introduced by fix from #1891

**Comment by HelioGuilherme66** [comment]
The Workaround is to *Disable* and then *Enable* the Test Runner plugin in Tools>Manage Plugins.

**Comment by Nyral** [comment]
Thanks, it works.
