### ISSUE TITLE
1.7.4b2 - Failed to load image... dialog bog whenever ride is started

### ISSUE THREAD

**Issue by moliveras** [robotframework/RIDE#2015]
I installed ride 1.7.4b2 on a centos7 system, running RF 3.1.2.

Whenever ride is started (ride.py &) I get a dialog box that I must close.  The box is shown in the attached image and I am also attaching the text from the save option under details.

![image](https://user-images.githubusercontent.com/38561769/65174866-ba8aa300-da1f-11e9-8326-f7f5e9071f35.png)

**Comment by moliveras** [comment]
[robot@RobotFramework]$ cat log.txt
02:13:19 PM: DIB Header: Image width > 32767 pixels for file.
02:13:19 PM: Failed to load image 0 from file '/usr/lib/python2.7/site-packages/robotide/widgets/robot.ico'.
02:13:20 PM: DIB Header: Image width > 32767 pixels for file.
02:13:20 PM: Failed to load image 0 from file '/usr/lib/python2.7/site-packages/robotide/widgets/robot.ico'.
02:13:20 PM: DIB Header: Image width > 32767 pixels for file.
02:13:20 PM: Failed to load image 0 from file '/usr/lib/python2.7/site-packages/robotide/widgets/robot.ico'.
02:13:20 PM: DIB Header: Image width > 32767 pixels for file.
02:13:20 PM: Failed to load image 0 from file '/usr/lib/python2.7/site-packages/robotide/widgets/robot.ico'.
02:13:20 PM: DIB Header: Image width > 32767 pixels for file.
02:13:20 PM: Failed to load image 0 from file '/usr/lib/python2.7/site-packages/robotide/widgets/robot.ico'.
02:13:20 PM: DIB Header: Image width > 32767 pixels for file.
02:13:20 PM: Failed to load image 0 from file '/usr/lib/python2.7/site-packages/robotide/widgets/robot.ico'.
02:13:20 PM: DIB Header: Image width > 32767 pixels for file.
02:13:20 PM: Failed to load image 0 from file '/usr/lib/python2.7/site-packages/robotide/widgets/robot.ico'.
02:13:20 PM: DIB Header: Image width > 32767 pixels for file.
02:13:20 PM: Failed to load image 0 from file '/usr/lib/python2.7/site-packages/robotide/widgets/robot.ico'.
02:13:20 PM: DIB Header: Image width > 32767 pixels for file.
02:13:20 PM: Failed to load image 0 from file '/usr/lib/python2.7/site-packages/robotide/widgets/robot.ico'.
02:13:20 PM: DIB Header: Image width > 32767 pixels for file.
02:13:20 PM: Failed to load image 0 from file '/usr/lib/python2.7/site-packages/robotide/widgets/robot.ico'.
02:13:20 PM: DIB Header: Image width > 32767 pixels for file.
02:13:20 PM: Failed to load image 0 from file '/usr/lib/python2.7/site-packages/robotide/widgets/robot.ico'.
02:13:20 PM: DIB Header: Image width > 32767 pixels for file.
02:13:20 PM: Failed to load image 0 from file '/usr/lib/python2.7/site-packages/robotide/widgets/robot.ico'.
02:13:20 PM: DIB Header: Image width > 32767 pixels for file.
02:13:20 PM: Failed to load image 0 from file '/usr/lib/python2.7/site-packages/robotide/widgets/robot.ico'.

**Comment by moliveras** [comment]
I realized that I am not able to view any tests in ride.  I was able to run them.

**Comment by Nyral** [comment]
Python 2.7?

**Comment by HelioGuilherme66** [comment]
@moliveras Please paste here the output of:
```
python -m pip list
```

**Comment by moliveras** [comment]
yes, this is python 2.7
[robot@RobotFramework]$ python -V
Python 2.7.5

[robot@RobotFramework]$ python -m pip list
DEPRECATION: Python 2.7 will reach the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 won't be maintained after that date. A future version of pip will drop support for Python 2.7. More details about Python 2 support in pip, can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support
Package                          Version
-------------------------------- ----------
Appium-Python-Client             0.28
asn1crypto                       0.24.0
atomicwrites                     1.3.0
attrs                            18.2.0
backports.ssl-match-hostname     3.5.0.1
bcrypt                           3.1.7
blivet                           0.61.15.72
Brlapi                           0.6.0
cffi                             1.12.3
chardet                          2.2.1
configobj                        4.7.2
configshell-fb                   1.1.23
coverage                         3.6b3
cryptography                     2.7
cupshelpers                      1.0
decorator                        3.4.0
di                               0.3
dnspython                        1.12.0
docutils                         0.14
enum34                           1.1.6
ethtool                          0.8
firstboot                        19.5
fros                             1.0
funcsigs                         1.0.2
futures                          3.1.1
idna                             2.4
iniparse                         0.4
initial-setup                    0.3.9.43
ipaclient                        4.6.4
ipaddress                        1.0.22
ipalib                           4.6.4
ipaplatform                      4.6.4
ipapython                        4.6.4
IPy                              0.75
javapackages                     1.0.0
jwcrypto                         0.4.2
kitchen                          1.2.5
kmod                             0.1
langtable                        0.0.31
lxml                             3.2.1
more-itertools                   5.0.0
netaddr                          0.7.5
netifaces                        0.10.4
nose                             1.3.7
npm                              0.1.1
ntplib                           0.3.2
numpy                            1.16.5
optional-django                  0.1.0
paramiko                         2.6.0
pathlib2                         2.3.3
perf                             0.1
Pillow                           5.4.1
pip                              19.2.3
pluggy                           0.8.1
ply                              3.4
policycoreutils-default-encoding 0.1
py                               1.7.0
pyasn1                           0.1.9
pyasn1-modules                   0.0.8
pycparser                        2.19
pycryptodomex                    3.7.3
pycups                           1.9.63
pycurl                           7.19.0
Pygments                         2.2.0
pygobject                        3.22.0
pygpgme                          0.3
pyinotify                        0.9.4
pykickstart                      1.99.66.19
pyliblzma                        0.5.3
PyNaCl                           1.3.0
pyOpenSSL                        0.13.1
pyparsing                        1.5.6
pyparted                         3.9
PyPubSub                         3.3.0
pysmbc                           1.0.13
pytest                           4.2.0
pytest-runner                    4.2
python-augeas                    0.5.0
python-dateutil                  1.5
python-dmidecode                 3.10.13
python-ldap                      2.4.15
python-linux-procfs              0.4.9
python-meh                       0.25.2
python-messaging                 0.5.12
python-nss                       0.16.0
python-yubico                    1.2.3
pytoml                           0.1.14
pytz                             2016.10
pyudev                           0.15
pyusb                            1.0.0b1
pyxattr                          0.5.1
PyYAML                           3.10
qrcode                           5.0.1
registries                       0.1
requests                         2.6.0
robotframework                   3.1.2
robotframework-appiumlibrary     1.5.0.4
robotframework-ride              1.5.2.1
robotframework-sshlibrary        3.3.0
rtslib-fb                        2.1.63
scandir                          1.9.0
schedutils                       0.4
scp                              0.13.2
selenium                         3.141.0
seobject                         0.1
sepolicy                         1.1
setroubleshoot                   1.1
setuptools                       40.5.0
six                              1.12.0
slip                             0.4.0
slip.dbus                        0.4.0
SSSDConfig                       1.16.2
subprocess32                     3.2.6
targetcli-fb                     2.1.fb46
urlgrabber                       3.10
urllib3                          1.10.2
urwid                            1.1.1
virtualenv                       16.6.0
wxPython                         2.8.12.1
wxPython-common                  2.8.12.1
yum-langpacks                    0.4.2
yum-metadata-parser              1.1.4

**Comment by HelioGuilherme66** [comment]
We cannot help you much. Your Python is too old, but RIDE 1.5.2.1, should work on it. Was it working before? Or is a first time installation? If not possible to upgrade, you can install a different Python version (not replacing the system one).

**Comment by moliveras** [comment]
1.5.2.1 *works* however it crashes a lot and does not support some of the newer syntax such as the END statement on FOR loops.  The info on the robotframework-ride page says that this is the last version to support python 2.7, is that not true?  What is the last version of python supported?

Thanks

**Comment by HelioGuilherme66** [comment]
@moliveras Your pip reported version 1.5.2.1. But now you are talking about newest version 1.7.4b2. If you are wanting to use 1.7.4b2 with *wxPython 2.8.12.1*, that can be problematic, because, although we try to keep compatibility, we don't test it anymore. You can try to install a newer wxPython, just select the correct GTK and distro from [wxPython Linux packages](https://extras.wxpython.org/wxPython4/extras/linux/). You can have several versions installed and select the one you want, see our BUILD.rst document.

**Comment by moliveras** [comment]
OK not so much my python version but my wxPython version.  I will try to build a later version of wxPython  Thanks!

**Comment by moliveras** [comment]
I was able to install wxPython-4.0.6 via pip and that seems to have resolved the issue.
btw... is there anyway to prevent the Files section from coming up in the lower left had side?  I am able to close it but it always comes up when I start ride.

Thanks again!

**Comment by HelioGuilherme66** [comment]
In the future it will be possible to configure panels position and visibility.
But the Files panel is an interesting feature (I think), If you right-click on a folder or file, it opens in RIDE editor (if supported type), if not it opens in a builtin basic editor. (For example, a .json, .py, .xml, .yml, ...)

**Comment by HelioGuilherme66** [comment]
I am closing this as wont-fix, because the problem has workaround that is to install newer wxPython version.

**Comment by moliveras** [comment]
Can you add a dependency for wxPython 4.0 on robotframework-ride?

**Comment by HelioGuilherme66** [comment]
No need to pin the version. Users can have several versions installed and select the one to use.
