### ISSUE TITLE
Parameters can not take effect in time

### ISSUE THREAD

**Issue by panda62** [robotframework/RIDE#2021]
1.7.4b2：参数不能实时生效，控制台命令日志反斜线会越来越多
![图片](https://user-images.githubusercontent.com/40233059/65785640-6f8f2f00-e187-11e9-975f-fc9cba642c04.png)
作如下修改后正常（增加一行）：
![图片](https://user-images.githubusercontent.com/40233059/65785799-c563d700-e187-11e9-977d-d51cbcafd08f.png)
@HelioGuilherme66

**Comment by Nyral** [comment]
This issue has been fixed. See [#2008](https://github.com/robotframework/RIDE/issues/2008).
Please search before opening a ticket.

**Comment by HelioGuilherme66** [comment]
@panda62 You should use English on Issue reports. This is the translation of your text: 

> The parameters do not take effect in real time, the console command log backslash will be more and more
---
> Normally modified as follows (add one line)

So it seems you don't like the `\\` in the execution of `robot`. That is not a problem as long it works :).

You can use `/` and the problem is gone. Please try with: `-d F:/RobotTestport/robotPort`

**Comment by panda62** [comment]
@HelioGuilherme66 
I did not describe Clear
yes,use `/` the problem is gone, but use `\`
first run
![图片](https://user-images.githubusercontent.com/40233059/65809261-3b8b2c80-e1ce-11e9-94c1-5980a1ff49d5.png)
Second run
![图片](https://user-images.githubusercontent.com/40233059/65809284-8c028a00-e1ce-11e9-8126-95181928861a.png)
Multiple runs
![图片](https://user-images.githubusercontent.com/40233059/65809302-b2c0c080-e1ce-11e9-874c-93f4476d2e06.png)

An increase in the code `self.arguments = self._arguments.GetValue()` in `_parse_windows_command` method, so that all parameters are taken from the parameter box every time it test execution, this problem can be solved
