### ISSUE TITLE
The Simplified-Chinese displayed problem 

### ISSUE THREAD

**Issue by Arvingrep** [robotframework/RIDE#2022]
参照Issues的更改了好几次都是报错，然而cmd 和cmder 界面运行都是没有报错

![image](https://user-images.githubusercontent.com/48466044/65833353-1c8db700-e302-11e9-9dba-ea6b8098f7ba.png)

![image](https://user-images.githubusercontent.com/48466044/65833390-9160f100-e302-11e9-96c0-a7ef77f43beb.png)

**Comment by wenzhaoxian** [comment]
参照Issues 1747 的方法还是不可以

**Comment by HelioGuilherme66** [comment]
@wenzhaoxian Esta é a tradução daquilo que escreveste em Chinês:
```
De acordo com as alterações dos problemas, é relatado várias vezes, mas as interfaces cmd e cmder estão sendo executadas sem erros.
```
e também:
```
O método de se referir às edições 1747 ainda não é possível.
```

Não faz muito sentido, pois não?
----
Imagine that everyone communicate in their native language. We could never get to understand the programs and issues. For example, this `robot` and `RIDE` were first developed by Finish people. I thank them for always communicate in English, when the audience is International. We now have excellent online and free translation web sites, but even so, we must spend some time using them, when it would not be necessary if the original was in English.
----

**Comment by HelioGuilherme66** [comment]
@wenzhaoxian See the [README](https://github.com/robotframework/RIDE/) and then the Release Notes for version 1.7.4, there you can see how to install version 1.7.4b2 which contains the fix (for the command output, only).
