### ISSUE TITLE
"PermissionError: [Errno 13] Permission denied"

### ISSUE THREAD

**Issue by thuypt35** [robotframework/RIDE#2025]
I got issue: "PermissionError: [Errno 13] Permission denied" when I tried to save new project
and when I edit the project's name and save, it show log: 
command: robot --argumentfile C:\Users\ADMINI~1\AppData\Local\Temp\RIDE_sgoomai.d\argfile.txt --listener f:\python\lib\site-packages\robotide\contrib\testrunner\TestRunnerAgent.py:54848:False F:\Python\Scripts\demo.None
[ ERROR ] Parsing 'F:\Python\Scripts\demo.None' failed: Unsupported file format 'none'.
=> a file has name like  *.none was created

**Comment by HelioGuilherme66** [comment]
@thuypt35 You don't mention your RIDE's version, but that problem is fixed already. Please install current Beta version.

**Comment by thuypt35** [comment]
Yes, thank you, I solved it

**Comment by rbradhika530** [comment]
I am facing issue with current RIDE v2.0.5 running on Python 3.9.6.
