### ISSUE TITLE
Separate Font and Colorization

### ISSUE THREAD

**Issue by vyvital** [robotframework/RIDE#2027]
Looks like Font and Colorizations are in the same function and both depend on the `Pygments` library thus both get skipped if the library is missing.
Moreover when uninstalling the library the same font will look differently.

Also it looks like there is an issue when swapping between Courier and Courier New.
When swapping it doesnt do anything, but when picking another font it does.
Maybe because these 2 are the only fonts that contain the same word?

`1.7.4b2`

**Comment by HelioGuilherme66** [comment]
Fixed by #2056
