### ISSUE TITLE
cases continue running when I press stop

### ISSUE THREAD

**Issue by povar81** [robotframework/RIDE#2030]
This has appeared for a very long time in previous versions of ride, back in versions 1.5 and earlier.
When I press stop I expect all cases to be stopped, but instead they continue running in background.
I had to manually find process and kill it, or restart ride, after pressing stop button.

**Comment by HelioGuilherme66** [comment]
In most of the cases appears a message indicating to send STOP a second time. Please confirm if that message is not in log window.

**Comment by povar81** [comment]
What message do you mean? 
I don't get any message in ride itself.

**Comment by HelioGuilherme66** [comment]
Here is an example of the `Second Stop will force exit`.
![image](https://user-images.githubusercontent.com/2866630/67130236-94ac1600-f1f8-11e9-9cc4-904263f5e680.png)

However, on Linux and depending the libraries, or test suite, the message may appear when the test is already stopped. On Windows that message would usually appear and work as expected.

**Comment by povar81** [comment]
I'm on windows, I don't get this message, all get is this: 
[ SENDING STOP SIGNAL ]
And the stop button becomes disabled (greyed out), but all the test still continue running in background.

**Comment by povar81** [comment]
I'm using custom script to run cases: in RIDE I indicate a tag of a specific case that I want to run in Arguments:
-i tagname
and it goes to script. If I run this way and press stop I get one message :
[ SENDING STOP SIGNAL ]

But if I just use RIDE without custom script and just manually select (tick) cases and press stop, then indeed I can press stop two times, and both times I get the same message:
[ SENDING STOP SIGNAL ]
[ SENDING STOP SIGNAL ]

However the case still continues running (so a problem is with both methods of running)

**Comment by HelioGuilherme66** [comment]
That was the missing information. *Custom script*, is not the normal TestRunner script. The feature was designed for TestRunner. The Stop command must be processed by the listener. There is not much we can do about stopping a custom script. Maybe if you pass a listener that would process the Stop signal, it can work.
