### ISSUE TITLE
for loop syntax problem

### ISSUE THREAD

**Issue by povar81** [robotframework/RIDE#2031]
when I use old syntax  
  : FOR    ${i}    IN RANGE    ${size}
    \    ${var}    Get From List    ${varList}    ${i}
I get a warning that slashes should not be used 
but when I remove them, the whole cell gets removed and I get FOR loop doesn't have any keywords.

**Comment by povar81** [comment]
It seems like the empty cells under FOR dissapear adn I get FOR loop doesn't have any keyword for some reason.

**Comment by povar81** [comment]
I get 'FOR loop contains no keywords' message

**Comment by HelioGuilherme66** [comment]
@povar81 This is explained here at [FAQ](https://github.com/robotframework/RIDE/wiki/F.A.Q.)

**Comment by povar81** [comment]
The problem is I wanted to have my test both python 2 and 3 compatible, and the only problem seems to be now is these for loop.
Is it going to stay like that forever or will be changed back to support old syntax in future releases?

**Comment by HelioGuilherme66** [comment]
This is not related to what python version you use, but with `robot` version. Old syntax will not be supported. Maybe someone can make a converter to old syntax.

**Comment by povar81** [comment]
I didn't have this problem in your developer's version RIDE 1.7.4b1dev1. But I don't have the install link anymore.
Could you please give a link to it?

**Comment by povar81** [comment]
Could you please explain what is the reason for this change?
in faq it says that the robot supports the old syntax of for loops:
Robot Framework is tolerant to the old : FOR format, and the test suite can be executed correctly.
So why is changed automatically in ride?

**Comment by raykudryavka123** [comment]
@povar81 if you want to use the old style for loop，you can try copy the whole old version robotframework dir (for example ".\Lib\site-packages\robot" v3.0.4) to replace the ".\Lib\site-packages\robotide\lib\robot" dir. And the .robot file will not be modified when you save it in ride, i test it's ok when i use ride=v1.7.4b2 and robotframe==v3.0.4

**Comment by povar81** [comment]
Are suggesting to copy old robotframework 2.8 over the new v3.1.2? 

Let me clarify: I have 2 systems: one with python 2 and robotframework 2.8  
and another one with python 3 and robotframework 3.4.0.

I want to be able to run same cases on different systems and different pythons and robotframeworks, and it all works fine except for this for loop problem.
I don't want to modify robotframework 3.4.0 not to break anything.

**Comment by povar81** [comment]
Are suggesting to copy old robotframework 2.8 over the new v3.1.2? 

Let me clarify: I have 2 systems: one with python 2 and robotframework 2.8  
and another one with python 3 and robotframework 3.4.0.

I want to be able to run same cases on different systems and different pythons and robotframeworks, and it all works fine except for this for loop problem.
I don't want to modify robotframework 3.4.0 not to break anything.
