### ISSUE TITLE
RIDE 1.7.4b2 remove all indentation for FOR loop

### ISSUE THREAD

**Issue by sfdcselenium01** [robotframework/RIDE#2036]
1.7.4b2 change :FOR to FOR and remove "\":
    : FOR     ${folder} IN [ @{path} ]
    \    Log To Console    --${lev}${folder}

However, it removes all  indentation for FOR loop automatically. Now when running test cases and get error "FOR loop contains no keywords."

New codes uing 1.7.4b2:

FOR    ${folder}    IN    @{path}
Log To Console    --${lev}${folder}

**Comment by HelioGuilherme66** [comment]
@sfdcselenium01 That is explained [here](https://github.com/robotframework/RIDE/wiki/F.A.Q.)
