### ISSUE TITLE
Not displayed correctly in RTL Language systems

### ISSUE THREAD

**Issue by Asafffff** [robotframework/RIDE#2038]
Hey,
My computer Language is Hebrew, but I believe it happens for more RTL language such as arabic.

I'd be happy if you can force the program to use LTR layout, like many other programs.

Couldn't find anything online.
![image](https://user-images.githubusercontent.com/21221486/67882113-627cab80-fb4a-11e9-9d16-b799bf76ad01.png)

Most annoying:
![image](https://user-images.githubusercontent.com/21221486/67882040-3eb96580-fb4a-11e9-96ad-002a0d82d5f4.png)

**Comment by emanlove** [comment]
I am seeing some documentation around forcing the direction .. http://xoomer.virgilio.it/infinity77/wxPython/Widgets/wx.Window.html#SetLayoutDirection

**Comment by emanlove** [comment]
My guess is that SetLayoutDirection does not cascade through child windows. Although the is no setters under wx.Locale it looks like you could start off by specifying a Locale - https://wxpython.org/Phoenix/docs/html/wx.Locale.html#wx.Locale.__init__

**Comment by HelioGuilherme66** [comment]
@emanlove Thank you for your comments. Localization is on our plans and then care for these issues will be taken.

(in my case, there are some GUI elements from GTK that appear translated to my locale, because we are using defaults)

**Comment by emanlove** [comment]
@HelioGuilherme66 wasn't there an issue where the grid showed up in minimized size as @Asafffff shows above? I am able to set the locale on a running instance to Hebrew. But my grid is not minimized. I kind of think this is that issue and has not relation to the language setting.

**Comment by emanlove** [comment]
Here is my little experiment. I little modification under src/robotide/application/application.py

```
    def OnInit(self):
        del self._initial_locale
        self._initial_locale = wx.Locale(wx.LANGUAGE_ARABIC)
        # Needed for SetToolTipString to work
        wx.HelpProvider.Set(wx.SimpleHelpProvider())  # TODO adjust to wx versions 
```

I set it to Arabic to be able to see a difference on my machine. I am thinking that it will be tough to discern when to change the language and when not to. And I am thinking with my quick experiment that this is not a RTL issue but a different issue altogether.

**Comment by HelioGuilherme66** [comment]
@Asafffff Please confirm the fix by installing current master.
(I tested on Linux with python 3.7.4 and wxPython 4.0.6)
`pip install -U https://github.com/robotframework/RIDE/archive/master.zip`

**Comment by Asafffff** [comment]
Sorry for not answering questions, I wasn't getting any emails about it except from the "Closed" operation!

@HelioGuilherme66 
It's getting better! thanks for everyone.
We still have some issues, that are not forced:

The INFO popup when installing the program still has the RTL settings:
![image](https://user-images.githubusercontent.com/21221486/68104167-ad981500-fee2-11e9-804f-eefdc28128fb.png)

Looks like any popup like "Create test", "Import from library", "Variables" etc, is not direction forced-
![image](https://user-images.githubusercontent.com/21221486/68104196-dcae8680-fee2-11e9-8892-ce4fcd12b762.png)
OR
![image](https://user-images.githubusercontent.com/21221486/68104251-08317100-fee3-11e9-903d-470ca3925bd0.png)

It looks like these are the only problems currently.
Screenshot of updated version, with correct direction and table columns are not minimized:
![image](https://user-images.githubusercontent.com/21221486/68104331-59d9fb80-fee3-11e9-83ad-983378591860.png)

**Comment by HelioGuilherme66** [comment]
Thanks. I need to take care also for all dialog windows (did not see a way to set language to English).

**Comment by HelioGuilherme66** [comment]
@Asafffff You can again test from `master`.

**Comment by Asafffff** [comment]
@HelioGuilherme66 Tested, for some reason - everything is now RTL and not LTR. It overrode the fix implemented in the previous merge (?) somehow.
Tried upgrading through pip, and cloning the git repo and running it myself through ./src/bin/ride.py

![image](https://user-images.githubusercontent.com/21221486/69476355-a8433180-0de1-11ea-8d3d-f8903fc717cf.png)

**Comment by HelioGuilherme66** [comment]
It looks like you are not running the fixed version. To be sure, first uninstall all RIDE versions (even in Python 2.7 and 3.7). Then install from development:
```
pip install --no-cache-dir https://github.com/robotframework/RIDE/archive/master.zip
```
(On Windows I prefer to install on `cmd` window ran as Administrator. On other systems with `sudo -H`)

**Comment by Asafffff** [comment]
works! thank you very much for the help!
