### ISSUE TITLE
RIDE 1.7.4B2 sometime will crash silently

### ISSUE THREAD

**Issue by qch1842** [robotframework/RIDE#2042]
1.7.4b2 running on Python 3.7.4. Win10

usually I have 2 RIDE instance running concurrently with different test suite with different tags.

I found the RIDE disappeared without any error notification several times after the long time run as check, the ride was launched 1 day or more before, and the test may have already run several cycle or just in first cycle. the test will last 10 ~ 30 hours. some keyword has FOR loop  embedded FOR loop

and as I tried to get log.html by rebot in command, I will get following error: 

E:\Users\Test\Temp\RIDE6i5apnr5.d>rebot --log log.html --flattenkeywords foritem output.xml
[ ERROR ] Reading XML source 'output.xml' failed: ParseError: no element found: line 22586760, column 310

I guess the output.xml also has been impact by crash that not written properly.

Is this a known issue or how can I collect log for this?

Thanks,
Shawn

**Comment by HelioGuilherme66** [comment]
@qch1842 My view on this use case of RIDE is the following:
- If you are expecting long runs of your tests, you should use the command line or script (or CI) to start them.
- RIDE is (should be) focused on the development of test cases.
- There may be Operating System mechanisms that can affect a GUI application, like memory management, disk space or lock files restrictions. RIDE itself may have memory leaks, or the unreported crashes like you report.
- In the cases you want to recover a broken output.xml, you should use the `-d` option to generate the output.xml, log.html and report.html files in a safe directory for latter access. Not in the temporary random directory RIDE created.

**Comment by Nyral** [comment]
I'd also like to add that RobotFramework won't be able to process an output.xml file if it's too large. My recommendation is to keep the test 1 hour short and to repeatedly rerun the test.

**Comment by HelioGuilherme66** [comment]
Closing because of no response from author.
