### ISSUE TITLE
Importing test library AutoItLibrary failed in RIDE version 1.7.3 and RED extension framework eclipse

### ISSUE THREAD

**Issue by davidmezza** [robotframework/RIDE#2046]
I need to be able to upload a file to a web page. the simple type upload works well with the "ChooseFile" method of selenium 4.0, while with the advanced upload it does not, because it creates a loading bar that allows the file not to be loaded instantly and then by the load button. To solve this problem I discovered AutoIt library with the "Send" method but I can't use it because eclipse in the red.xml does not recognize me. After loading the library with the init___py file like other selenium type libraries etc ... these warnings come out as errors see link.

https://drive.google.com/file/d/1e-ly86qnuavvt3mRjcx645GEflQxY1kB/view?usp=sharing

https://drive.google.com/file/d/1hrg9MdR0zZ_AQ68rw3ZzNARdsR7tNUoI/view?usp=sharing

**Comment by HelioGuilherme66** [comment]
This is not the correct Issue tracker.
