### ISSUE TITLE
Double quote translate to another format automatically in Grid Editor causes error.

### ISSUE THREAD

**Issue by hidebear** [robotframework/RIDE#2050]
**Environment:**
OS: Mac OS 10.15.1
Robot Framework: Robot Framework 3.1.2 (Python 3.7.3 on darwin)
RIDE: 1.7.4rc1.dev

**Description**
While typing string comparison like "${My string}" != "${EMPTY}" which causes invalid character error.
And after some trying found that type double quote in Gride Editor will automatically translate into another format (but type it on Text Edit is fine).

![image](https://user-images.githubusercontent.com/21049399/68723272-12462480-05f3-11ea-8bd8-053bb50527e1.png)

Which will cause the error 
![image](https://user-images.githubusercontent.com/21049399/68723325-2f7af300-05f3-11ea-8823-62535e26de50.png)

So I now have to switch to Text Edit mode while trying to enter the quote symbol.

**Comment by HelioGuilherme66** [comment]
@hidebear This is a known problem of MacOS. Please see how to solve on our [FAQ](https://github.com/robotframework/RIDE/wiki/F.A.Q.#frequently-asked-questions).
