### ISSUE TITLE
The timestamp of xml, report and log is equal

### ISSUE THREAD

**Issue by aitormars** [robotframework/RIDE#2051]
**Environment:**
OS: Windows10
Robot Framework: Robot Framework 3.1.2 (Python 2.7)
RIDE: 1.7.3.1

**Description:**
When ride finish the execution the log, the report and the xml files have the same timestamp for all files. The previous version set the timestamp with end of execution to report and log.

Output:  C:\LogsRide\output-20191113-155339.xml
Log:     C:\LogsRide\log-20191113-155339.html
Report:  C:\LogsRide\report-20191113-155339.html

**Comment by HelioGuilherme66** [comment]
@aitormars That does not look like RIDE generated files. What options are you using? Did you run outside RIDE (command window) with `robot`?
When you say previous version, are you talking about RIDE, or `robot`? Please indicate clearly the versions you are referring.

**Comment by aitormars** [comment]
Hi @HelioGuilherme66 it's seems that is a robotframework issue because I ran in command window and the timeStamp is the same for the three files. I 'll open this ticket in robotframework.
Thanks you for the support,
