### ISSUE TITLE
Cyrillic symbols from documentation are not displayed

### ISSUE THREAD

**Issue by povar81** [robotframework/RIDE#2052]
Whenever there's a Russian/Ukrainian text in documentation it's not displayed properly:
https://imgur.com/a/gZWaUOB

**Comment by HelioGuilherme66** [comment]
That is not documentation, but command window output.
You need to give info on what versions of RIDE, system and python.
There are several issues related to characters (like Chinese).

**Comment by povar81** [comment]
Windows 7.
Python 3.7.4,
robotframework==3.1.2,
robotframework-ride==1.7.4b1.dev1 (I'm usring dev1 version because it's the last one supporting the old for loop syntax)

**Comment by povar81** [comment]
wxPython==4.0.6

**Comment by HelioGuilherme66** [comment]
Closing because we cannot reproduce in current development version.

**Comment by povar81** [comment]
Cyrillic text is shown properly
in RIDE v2.0.8.1 running on Python 3.7.4.
thank you
