### ISSUE TITLE
how to run ride on windows in venv ?

### ISSUE THREAD

**Issue by elschman** [robotframework/RIDE#2058]
I do have several venv and would like to run the ride just in this environment. How to do it ?
currently execute ride.py inside the activated venv loads the python environment from the main environment and ignores the venv

**Comment by HelioGuilherme66** [comment]
You add the PYTHONPATH to the virtualenv scripts and site-packages in RIDE Tools>Preferences or you create a starter script (.bat, .cmd, .sh or .command) to modify the PATH so it finds first the virtualenv, then launches RIDE.

**Comment by elschman** [comment]
Bom dia,

 

I do have the scripts path as first element in PATH.

 

But if I than start ride my only in venv visible lib taut_topology is not found.

 


20191120 15:59:28.022 [WARN]: Importing test library "taut_topology.Gfast" failed

Traceback (most recent call last):
Importing test library 'taut_topology.Gfast' failed: ImportError: No module named taut_topology
Traceback (most recent call last):
  File "C:\Python\Python27\lib\site-packages\robotide\lib\robot\utils\importer.py", line 153, in _import
    return __import__(name, fromlist=fromlist)
PYTHONPATH:
  C:\Users\iwetzel\PycharmProjects\pyLibHuaConf\venv_2.7\Scripts
  C:\Windows\system32\python27.zip
  C:\Python\Python27\DLLs
  C:\Python\Python27\lib
  C:\Python\Python27\lib\plat-win
  C:\Python\Python27\lib\lib-tk
  C:\Python\Python27
  C:\Python\Python27\lib\site-packages
  C:\Python\Python27\lib\site-packages\setuptools-39.1.0-py2.7.egg
  C:\Python\Python27\lib\site-packages\win32
  C:\Python\Python27\lib\site-packages\win32\lib
  C:\Python\Python27\lib\site-packages\Pythonwin
  C:\Python\Python27\lib\site-packages\robotide\spec
  C:\Python\Python27\lib\site-packages\robotide\lib
  C:\Python\Python27\lib\site-packages\robotide\contrib\testrunner\../../lib
  C:\Python\Python27\lib\site-packages\robotide\contrib\testrunner\../../lib
  File "C:\Python\Python27\lib\site-packages\robotide\spec\librarymanager.py", line 87, in _fetch_keywords
    return get_import_result(path, library_args)
  File "C:\Python\Python27\lib\site-packages\robotide\spec\libraryfetcher.py", line 24, in get_import_result
    lib = robotapi.TestLibrary(path, args)
  File "C:\Python\Python27\lib\site-packages\robotide\lib\robot\running\testlibraries.py", line 50, in TestLibrary
    return_source=True)
  File "C:\Python\Python27\lib\site-packages\robotide\lib\robot\utils\importer.py", line 72, in import_class_or_module
    self._raise_import_failed(name, err)
  File "C:\Python\Python27\lib\site-packages\robotide\lib\robot\utils\importer.py", line 109, in _raise_import_failed
    raise DataError('\n'.join(msg))


20191120 15:59:28.709 [INFO]: Found Robot Framework version 3.1.1 from C:\Python\Python27\lib\site-packages\robot.

20191120 15:59:28.710 [INFO]: Started RIDE 1.7.3.1 using python version 2.7.15 with wx version 4.0.4 in win32.

 

 


Immo Wetzel
PGP Fingerprint (GMX) : D894 088D 3CE5 D769 7B89 518B E009 4219 129E 4642
ICQ: 30151767
Skype: immo_we

 
 

Gesendet: Mittwoch, 20. November 2019 um 15:44 Uhr
Von: "Hélio Guilherme" <notifications@github.com>
An: robotframework/RIDE <RIDE@noreply.github.com>
Cc: elschman <elschman@wetznet.de>, Author <author@noreply.github.com>
Betreff: Re: [robotframework/RIDE] how to run ride on windows in venv ? (#2058)


You add the PYTHONPATH to the virtualenv scripts and site-packages in RIDE Tools>Preferences or you create a starter script (.bat, .cmd, .sh or .command) to modify the PATH so it finds first the virtualenv, then launches RIDE.

**Comment by HelioGuilherme66** [comment]
Activate virtualenv, only start RIDE after that.

Is this your virtualenv python path, after being activated?
```
C:\Python\Python27\lib\site-packages\
```

Can't you use Slack for questions or troubleshooting?
