### ISSUE TITLE
参考常见问题的FOR解决方法，仍无法使用

### ISSUE THREAD

**Issue by LazyTang** [robotframework/RIDE#2059]
![image](https://user-images.githubusercontent.com/37360490/69323416-a4000280-0c81-11ea-82d0-b15524d0cf0d.png)
FOR	${i}	IN	1	2	
	log	${i}			
	Exit For Loop If	${i}==2			
END					
这样写，运行是报错
20191121 17:06:36.817 :  FAIL : Variable '${i}' not found.

![image](https://user-images.githubusercontent.com/37360490/69323499-d01b8380-0c81-11ea-8423-8d734b233425.png)
![image](https://user-images.githubusercontent.com/37360490/69323514-da3d8200-0c81-11ea-8a37-c92bda6b0263.png)

**Comment by HelioGuilherme66** [comment]
@LazyTang Você podia nos facilitar se escrevesse em Inglês. Assim não tínhamos que ir usar serviços de tradução para perceber o que escreveu em Chinês. Escrevi de propósito em Português para que você veja o esforço desnecessário.

**Comment by HelioGuilherme66** [comment]
Well the following code is working on latest development version:
```
*** Test Cases ***
for loop numeric
    FOR    ${i}    IN    1    2    3    4
        Log    ${i}
        Exit For Loop If    ${i}==2
    END

for loop range
    FOR    ${i}    IN RANGE    1    4
        Log    ${i}
        Exit For Loop If    ${i}==2
    END
```

**Comment by LazyTang** [comment]
I use you to run the code, still have a problem
20191122 09:07:44.890 :  FAIL : Variable '${i}' not found.

**Comment by HelioGuilherme66** [comment]
What is the version of `robot`?
```
robot --version
```

**Comment by LazyTang** [comment]
Robot Framework 3.0 (Python 3.7.4 on darwin)

**Comment by HelioGuilherme66** [comment]
Please upgrade to 3.1.2.

(and there was an important fix for MacOS, on current master if you want and can try)

**Comment by LazyTang** [comment]
Thank you. I will try to update it

**Comment by LazyTang** [comment]
![image](https://user-images.githubusercontent.com/37360490/69390325-d5bcac00-0d09-11ea-83dc-c6725978d7b9.png)
Hello, after upgrading to 3.1.2, it cannot be used

robot --version：
Robot Framework 3.1.2 (Python 3.7.4 on darwin)

At runtime, the following problems occur:
Robot Framework installation not found.
To run tests, you need to install Robot Framework separately.
See http://robotframework.org for installation instructions.

**Comment by HelioGuilherme66** [comment]
On the Run tab select the profile `robot 3.1`

**Comment by LazyTang** [comment]
Ok, problem solved. Thank you
