### ISSUE TITLE
blank screen

### ISSUE THREAD

**Issue by mansaa8015** [robotframework/RIDE#2063]
Hi team,

I have started working on robotframework and I get a blank screen on opening edit tab instead og getting tables.

**Comment by HelioGuilherme66** [comment]
Search Issue tracker for similar problems.
If you are a Software Tester, Developer or **USER**, you must know how to report problems/issues.
For questions, there are other means like, StackOverflow, the Internet, Our Google Groups or our Slack at #ride channel.
