### ISSUE TITLE
Edit Grid missing in RIDE

### ISSUE THREAD

**Issue by trba101** [robotframework/RIDE#2066]
Hi,
I recently ionstalled:
python 3.8
robotframework
ride 1.7.3
I do not see the grid in the edit mode in RIDE.
Checking the RIDE settings file the GRID section is empty.
Is there anything I need to configure

**Comment by HelioGuilherme66** [comment]
From the README:

### Attention, don't install RIDE on Python 3.8 (wait for version 2.0)

If you had searched these Issues, you would have noticed the tag `Python3.8` and the same problem reported.

**Comment by trba101** [comment]
Thanks. I did not search the issues carefully.
