### ISSUE TITLE
RIDE latest version 1.7.3.1 is not compatible with Python 3.8

### ISSUE THREAD

**Issue by ankuru** [robotframework/RIDE#2069]
Hi Team,

RIDE latest version 1.7.3.1 is not compatible with Python 3.8, it is compatible with Python 2.7. However, Python 2.7 will retire very soon on January 1, 2020. I have heard RIDE 2.0 is in pipeline for release and it should support Python 3.x. 
Question/Concern: 
**1)Is there a workaround which should allow me to RIDE 1.7.3.1 with Python 3.8?
2)When we will get an official stable release for RIDE which will support python 3.8?
3)As of now do I have only one option and that is to use RIDE with python 2.x?**

After I upgraded from Python 2.7 to 3.7, here is the error I am getting on cmd when hitting "ride.py". With python 2.7 it worked perfectly fine and launched the editor for me.
<img width="960" alt="Ride py cmd error" src="https://user-images.githubusercontent.com/27549077/69791760-3016aa80-11eb-11ea-97dd-6d025cb2a2e9.png">

Please post the resolution asap as my current project work is completely dependent on it.

Thanks and Regards,
Ankur Upadhyay

**Comment by HelioGuilherme66** [comment]
@ankuru You can install Python 3.7 and RIDE will work on that. You can still install and use RIDE on Python 2.7, but having `robot` on other Python versions.

You should try to install current development version from `master` branch (but not on Python 3.8).

**Comment by ankuru** [comment]
Hi Team,

So RIDE latest version 1.7.3.1 is compatible with Python 3.7 but not 3.8.
Is it correct? Also can you let me know which wxpython and robot framework
version i need to install which would be compatible with RIDE 1.7.3.1 and
python 3.8
 (#2069)

Thanks and Regards,
Ankur Upadhyay

**Comment by HelioGuilherme66** [comment]
@ankuru Yes, latest released 1.7.3.1 is compatible with Python 3.7. But there are a lot of fixes on current development version 1.7.4rc1, which is better to try.

Development for Python 3.8 will only start after the release of 1.7.4 being, which will be in November or December 2019.

**Comment by ankuru** [comment]
Hi Team,

Thanks for the update.
Can you also let me know
*Which wxpython and robot framework version i need to install which would
be compatible with RIDE 1.7.3.1 and python 3.7*

*Thanks and Regards,*
*Ankur Upadhyay*

**Comment by HelioGuilherme66** [comment]
Read the version Release Notes. Usually the latest version of wxPython is OK.

**Comment by ankuru** [comment]
@HelioGuilherme66 
*As per this RIDE official GitHub page:- https://github.com/robotframework/RIDE/wiki/Installation-Instructions. It's mentioned that RIDE runs only on the regular Python, not on Jython nor IronPython. Python 2.6 is the minimum version. Notice that similarly as Robot Framework, RIDE does not yet support Python 3. Notice also that on OS X RIDE requires 32-bit Python version.*
**So I am totally confused which all versions of the following software I should install to work properly:-** 

**1. Python
2. RIDE
3. robot framework 
4. wxpython**

Here is a screenshot of GitHub ride official page
![image](https://user-images.githubusercontent.com/27549077/69847457-31081480-129d-11ea-9e29-c59a8e98c53b.png)

Please help me out.

Ankur Upadhyay

**Comment by ankuru** [comment]
@HelioGuilherme66 

Thank You so much. It worked, I can use RIDE now with Python 3.7 and able to run my scripts.
These are all the software and versions that worked for me:

**1. Python 3.7.0 (https://www.python.org/ftp/python/3.7.0/python-3.7.0-amd64.exe)
2. robot framework 3.1.2 (pip install -U robotframework)
3. wxpython 4.0.7.post2 (pip install -U wxPython)
4. RIDE 1.7.3.1 (pip install -U robotframework-ride)**

Ankur Upadhyay

**Comment by ankuru** [comment]
@HelioGuilherme66 Can you please help me out, how to resolve the above issue?

**Comment by xmatikale** [comment]
Hello, I'm also using Python 3.8. I managed to install Robot Framework to Python 3.7 with this command:

`py -3.7 -m pip install robotframework-ride`

**Comment by aabhalekar** [comment]
While searching for python 3.8 and ride, found following information. Tried dev version and it worked for me.

Information:
Attention, don't install RIDE on Python 3.8 (wait for release of version 2.0)
Or you can install from development, where running on Python 3.8 is supported (since February 2020)
Install with: [source, shell] pip install -U https://github.com/robotframework/RIDE/archive/master.zip

**Comment by Gaurav21git** [comment]
Hi team,

I am using Python 2.7 but while installing Appium Library with the help of command: pip install robotframework-appiumlibrary, I am getting below error:

![image](https://user-images.githubusercontent.com/43947717/87902698-f515ff80-ca77-11ea-9653-54f5f991b8eb.png)

And also, could you please let me know, Version compatibility between RIDE & Appium Library.
