### ISSUE TITLE
Not able to run test script in ride with custom path for reports file

### ISSUE THREAD

**Issue by ankuru** [robotframework/RIDE#2080]
Hi Team,

I am providing below path in arguments section to store my all 3 report files
`--outputdir C:/AutomationLogs/%date:~-4,4%%date:~-10,2%%date:~-7,2% --timestampoutputs`
After running the test case in RIDE I am getting below error 
```
command: robot --outputdir C:/AutomationLogs/%date:~-4,4%%date:~-10,2%%date:~-7,2% --timestampoutputs --argumentfile C:\Users\ANKURU~1\AppData\Local\Temp\RIDE8oamkluy.d\argfile.txt --listener "c:\program files\python37\lib\site-packages\robotide\contrib\testrunner\TestRunnerAgent.py:60199:False" "C:\Users\ankurupadhyay\Downloads\Project Docs\RobotProject\LendingTree"
unexpected error: [ ERROR ] Creating output file directory 'C:\AutomationLogs\%date:~-4,4%%date:~-10,2%%date:~-7,2%' failed: The filename, directory name, or volume label syntax is incorrect

Try --help for usage information.

test finished 20191204 13:14:24
```

Below are the versions of relevant Softwares I am using and tests are running fine when reports path is set to default: 
```
1. Python 3.7.0
2. robot framework 3.1.2
3. wxpython 4.0.7.post2
4. RIDE 1.7.3.1
```

Can someone help me with this? I know this is a duplicate issue but that didn't resolve my issue.

Thanks,
Ankur Upadhyay

**Comment by ankuru** [comment]
@HelioGuilherme66 Can you please help me out in resolving the above issue?

**Comment by HelioGuilherme66** [comment]
@ankuru That is fixed in current development version. Please install:
`pip install -U https://github.com/robotframework/RIDE/archive/master.zip`

**Comment by ankuru** [comment]
Hey @HelioGuilherme66 But will it be compatible with below software versions?
```
1. Python 3.7.0
2. robot framework 3.1.2
3. wxpython 4.0.7.post2
```

**Comment by HelioGuilherme66** [comment]
@ankuru Of course, it will be compatible. You could have just try it!
