### ISSUE TITLE
Not able to see all arguments of python method when calling using Keyword in RIDE

### ISSUE THREAD

**Issue by ankuru** [robotframework/RIDE#2081]
I created below python class
```
class Class_Student:
    def add_number(self, b):
        return self + b

    def sub_number(self, b):
        return abs(self - b)

    def mul_number(self, b):
        return self * b

    print(str(sub_number(10, 20)))
```
Able to import it successfully in RIDE test suite also.

But when i am calling any method using keyword like this:

![image](https://user-images.githubusercontent.com/27549077/70213335-1501e880-175f-11ea-8208-51965aaa8eae.png)

It is only showing me one argument instead of 2 that i created in my python method.
![image](https://user-images.githubusercontent.com/27549077/70213421-48dd0e00-175f-11ea-88a7-229430e24506.png)

**@HelioGuilherme66 Can you please help me here?
Why I am not able to see/pass 2 arguments here?**

**Comment by ankuru** [comment]
Can someone look into this from RIDE team?

**Comment by HelioGuilherme66** [comment]
@ankuru That is a basic mistake you are doing on Python programming. The `self` is not an argument. It represents the actual object when you are running a python script (in other words the "instance"). Other programming languages use the word `this`.
Look for some better example of python programming.

You should ask this type of questions on our Slack channel.
