### ISSUE TITLE
Python3.8，I install ride 1.7.2--1.7.4b2,testCase's edit no gui

### ISSUE THREAD

**Issue by luowqn** [robotframework/RIDE#2082]
I install ride 1.7.2--1.7.4b2,but testCase's edit no gui

wxPython 4.0.7.post2
robotframework  4.0.7.post2

![image](https://user-images.githubusercontent.com/20413980/70515683-b37fb680-1b70-11ea-9943-b87516c87123.png)

**Comment by luowqn** [comment]
i reinstall python  ===>python3.8 to python3.7.5 , it have no this question

**Comment by HelioGuilherme66** [comment]
@luowqn We have this already reported, and I have a warning on the README at project page.
