### ISSUE TITLE
ctrl+A doesn't do anything

### ISSUE THREAD

**Issue by povar81** [robotframework/RIDE#2084]
On older RIDE (1.5 and older) I was able to select contents of the whole case when I pressed ctrl+A.
But on version RIDE 1.7.4rc1.dev running on Python 3.7.4 (on Windows 7) it doesn't do anything.

What's the alternative for that now?
Is it possible to bring it back?

**Comment by HelioGuilherme66** [comment]
We did not do that change deliberately.

**Comment by HelioGuilherme66** [comment]
Investigation revealed that feature is working on version 1.7.4b1 but not on 1.7.4b2.

**Comment by HelioGuilherme66** [comment]
This is partially fixed. More code changes are needed.

**Comment by HelioGuilherme66** [comment]
@Nyral I increased the priority of this issue, because Ctrl-Shift-J is also not working (but gets fixed on your branch/PR). We don't have any other way to start the JSON editor on a cell.
