### ISSUE TITLE
Please make an option to disable automatic for loop formatting

### ISSUE THREAD

**Issue by povar81** [robotframework/RIDE#2085]
We have both 
new RIDE 1.7.4rc1.dev version (with Python 3) 
and
older 1.5 versions (with Python 2), and literally hundrends of test suites with thousands cases.

They all work perfectly fine on both versions, except when it comes to FOR loops: they get broken every time we have to change something on newer RIDE.
The FAQ only says that it works like that and that's it, no explanation why, no alternative.

Is it possible to add some option disabling the FOR loop autoformatting?

**Comment by HelioGuilherme66** [comment]
The solution is to upgrade RIDE (and wxPython), unless you use robotframework <3.1. We try to keep RIDE compatible with current robotframework.
What version of robotframework you use?
`robot --version`

**Comment by povar81** [comment]
Let's discuss it in one thread:
https://github.com/robotframework/RIDE/issues/2029
