### ISSUE TITLE
For help

### ISSUE THREAD

**Issue by numbpeople** [robotframework/RIDE#2087]
![1577098164984](https://user-images.githubusercontent.com/45647907/71353769-06b42900-25b5-11ea-802f-895545ae9186.jpg)

How should I set the default cells width and length. Every time I open ride to create testcase it looks like this, which makes me feel bad
environment：
macOS Mojave（10.14.6）

**Comment by numbpeople** [comment]
![1577098581359](https://user-images.githubusercontent.com/45647907/71354129-f18bca00-25b5-11ea-8cbe-f26bed30a5f0.jpg)
pip3 list

**Comment by numbpeople** [comment]
Added: this happens when I use python3.7 and is normal when I use python2.7.

**Comment by Nyral** [comment]
You're using an older version of RIDE. Use the following command to update:

`pip install -U git+https://github.com/robotframework/RIDE.git@master`

**Comment by numbpeople** [comment]
@Nyral I tried to install your old version, but I need to uninstall ride1.7.3.1. I tried to uninstall the installed ride, but was prompted with an error.
“Installing collected packages: robotframework-ride
  Found existing installation: robotframework-ride 1.7.3.1
    Uninstalling robotframework-ride-1.7.3.1:
ERROR: Could not install packages due to an EnvironmentError: [Errno 13] Permission denied: 'PKG-INFO'
Consider using the `--user` option or check the permissions.”

**Comment by numbpeople** [comment]
@Nyral I think it's because I have pythin2.7 and python3.7 installed on my MAC, and I have ride installed on both versions of python. How should I uninstall all the installed ride? I want to reinstall it. How should I delete it clean.
