### ISSUE TITLE
Edit test case page not displaying in Ride

### ISSUE THREAD

**Issue by dineshvpd** [robotframework/RIDE#2089]
![Ride _ EDit Option not working](https://user-images.githubusercontent.com/33411722/71410810-c0220580-266c-11ea-8de9-df643e883ac1.JPG)

**Comment by HelioGuilherme66** [comment]
This Issue report sucks!
Are you a software tester? Would you report an issue like that to your development team?
(I know what is the problem, and you would too if cared to search here)

**Comment by duongnguyenquy** [comment]
I have this issue too. 
python 3 and install the 1.7.4b2 version. 
It cannot show anything like the image above.
I tried to delete this file librarykeywords.db in 
C:\Users\duongnq5\AppData\Roaming\RobotFramework\ride
But nothing helps

**Comment by HelioGuilherme66** [comment]
Look at issues with the label **Python3.8**

**Comment by bakobela** [comment]
I have the same issue on Mac
