### ISSUE TITLE
How to solve this problem

### ISSUE THREAD

**Issue by numbpeople** [robotframework/RIDE#2093]
![1577333717709](https://user-images.githubusercontent.com/45647907/71458235-c6cf8a80-27dc-11ea-8cf0-905992ff007e.jpg)
How to solve this problem

**Comment by HelioGuilherme66** [comment]
Maybe the problem does not happen with newest version 1.7.4. Please understand the changes it will cause with the upgrade. Also you should upgrade wxPython to 4.0.7post2.
