### ISSUE TITLE
deleted variable remaining in The tree ,bug actually deleted 

### ISSUE THREAD

**Issue by Fengjiya** [robotframework/RIDE#2094]
environment : RIDE 1.7.3.1 running on Python 2.7.17. 
when define a variable in the txt file, and it display in the tree on the left .
But when deleted the variable ,it still  remaining in The tree, and not display in the list in the grid .

**Comment by HelioGuilherme66** [comment]
@Fengjiya I did not reproduce (on Linux, Python 3.7.6, RIDE 1.7.4.1dev0). These are my steps:

1. On Text Editor add *** Variables *** section and a scalar definition
2. Click Apply Changes. (the variable appears on Tree)
3. On Text Editor delete the *** Variables *** section and scalar definition
4. Click Apply Changes. (the variable disappears from Tree)
