### ISSUE TITLE
I can't create more than 1 suite in the same directory 

### ISSUE THREAD

**Issue by liuJessica** [robotframework/RIDE#2095]
robotframework-ride 1.7.3.1
If I create two suites in the sam directory ,I can't save them

**Comment by HelioGuilherme66** [comment]
@liuJessica 
Please clarify what are the steps to reproduce. When you create a new project, you have the option of a test suite (a file) or a directory (with test suites files). You right-click some root folder and then **New Suite**, twice, wrote some test cases on them and you could not save. Did you get any error message?
