### ISSUE TITLE
Ride.py is not opening the IDE

### ISSUE THREAD

**Issue by kodaliy** [robotframework/RIDE#2098]
I am trying to work with robot framework on python 3.8 version. However i am facing issues with the ride. Will ride works with python 3.8 version? Below are the steps that i have followed for the installation.

1) installed python version 3.8(32 bit)
2) installed robotframework 3.1.2
3) installed wxpython 4.0.7 (32bit)
4) installed ride 

After following the above steps tried opening the IDE from command prompt by typing ride.py how ever i end up with the below error
![pip-freeze](https://user-images.githubusercontent.com/20738237/71547116-bb898400-29c1-11ea-92c2-19abba2f1253.PNG)
![ridepyError](https://user-images.githubusercontent.com/20738237/71547120-c0e6ce80-29c1-11ea-8dce-0ce3895f00c4.PNG)

**Comment by Nyral** [comment]
read the wiki: https://github.com/robotframework/RIDE/wiki/Installation-Instructions#python

**Comment by HelioGuilherme66** [comment]
Fixed by #2128

**Comment by nikhitha-tr** [comment]
can i pls know the solution for this issue

**Comment by HelioGuilherme66** [comment]
@nikhitha-tr The solution is in the README.md page that you see when click on Code of this project. (You have to install the pre-release version on the current development)

**Comment by aksh721** [comment]
> Fixed by #2128

I am not able to open ride.py where I have installed below 

Python 3.8.5
pip 21.3.1
Robot Framework 4.1.3 (Python 3.8.5 on win32)
 HelioGuilherme66 or any one can you please help me open RIDE IDE

**Comment by HelioGuilherme66** [comment]
@aksh721 Just try to install the development version. Before that upgrade WxPython to 4.1.1.
