### ISSUE TITLE
ride.py can't run successfully if pubsub's version is 0.1.2

### ISSUE THREAD

**Issue by AaronLoong** [robotframework/RIDE#2117]
![image](https://user-images.githubusercontent.com/31234576/72677106-ba84d780-3ad3-11ea-8606-a3f6e8a678b1.png)
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/robotide/publish/publisher.py", line 21, in <module>
    from pubsub import Publisher
ImportError: cannot import name 'Publisher' from 'pubsub' (/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/pubsub.py)

python version: 3.7.5
RIDE version: 1.7.4

**Comment by HelioGuilherme66** [comment]
@AaronLoong That is a very old version of PyPubSub. Install a newer one.

**Comment by AaronLoong** [comment]
> @AaronLoong That is a very old version of PyPubSub. Install a newer one.

ok, thanks for reply.
