### ISSUE TITLE
FOR loop issue when using RIDE

### ISSUE THREAD

**Issue by fengqiX** [robotframework/RIDE#2119]
**Environment**: RIDE 1.7.4 running on Python 3.7.3. 
There is a problem When i create FOR Loop in using **RIDE**
When i am under **Edit** tab to create FOR loop, it is working with no error message.
![image](https://user-images.githubusercontent.com/29168659/72937836-198e5a80-3d27-11ea-90f4-68dd13e35080.png)
                                                          _Syntax under Edit_

![image](https://user-images.githubusercontent.com/29168659/72937375-3f672f80-3d26-11ea-8cab-cb9b6a3deab7.png)
                                                                  _Results_

However, when i switch to ** Text Edit** it gives an error messages indicate that something is wrong which is right and working,
![image](https://user-images.githubusercontent.com/29168659/72937401-4beb8800-3d26-11ea-857c-ec0dbb26ebf2.png)
                                               _Error message to correct the code_

When it corrects my code as shows below, it shows a runtime error as **FOR loop contains no keywords.**
![image](https://user-images.githubusercontent.com/29168659/72937530-8bb26f80-3d26-11ea-90c2-e21e6a6bd195.png)
                                                          _Code after corrected_
![image](https://user-images.githubusercontent.com/29168659/72937651-bef4fe80-3d26-11ea-9d0b-7272f56eadf9.png)
                                                             _Error Message_

It is pretty annoying to switch back and forth. Please help checking on this issue.
Here is the whole image of **Run** page. 
![image](https://user-images.githubusercontent.com/29168659/72938989-3deb3680-3d29-11ea-94ab-886cef215b0f.png)

**Comment by HelioGuilherme66** [comment]
@fengqiX Future Robot Framework 3.2, will not accept the old `: FOR` format bu only the `FOR/END` format. We have an explanation of this RIDE situation in the [FAQ](https://github.com/robotframework/RIDE/wiki/F.A.Q.#2-q-in-the-newest-versions-of-ride-174-and-with-robot-framework-312-when-i-edit-a-test-suite-having--for-then-when-is-executed-appears-the-following-error-for-loop-contains-no-keywords-how-to-fix-this).

You can already start converting to the new format, or you may try to disable Text Editor.

**Comment by grossvati** [comment]
@fengqiX In your case you can try the new syntax for a loop

FOR    ${ii}    IN RANGE    10
            log
            log
END

I hope this will work in both editors

**Comment by Sergix555** [comment]
> @fengqiX In your case you can try the new syntax for a loop

I struggle with this issue as well.
Whatever I choose YES or NO, the Text Editor changes my code to:
FROM:
 ```
   FOR    ${i}    IN RANGE    0    5
    Log    Result of simple iteration FOR
    END
```
TO
```
    : FOR    ${i}    IN RANGE    0    5
    \    Log    Result of simple iteration FOR

```

 
**ENV:**   RIDE 1.7.3.1 running on Python 3.7.4.

**Comment by HelioGuilherme66** [comment]
@Sergix555 That problem of the Yes/No was fixed (you are using Linux, right?).
See my answer referring to FAQ. You can not use Text Editor to change to old FOR style.

Upgrade to RIDE 1.7.4.1, old style is going to disappear on 3.2.

**Comment by grossvati** [comment]
In my comment github deleted some spaces. FOR and END are on the same position. Your Log-command is indented.

FOR    ${i}    IN RANGE    0    5
    Log    Result of simple iteration FOR
END

**Comment by Sergix555** [comment]
Thank you guys!
I've updated RIDE with command:
`pip install --upgrade robotframework-ride`
And now I haven't problem with switchin from **Edit** to **Test edit**
It look like this:
![image](https://user-images.githubusercontent.com/44416467/73085043-bba07500-3ed6-11ea-9124-140ec7b0cfe2.png)
```
TestFOR
    FOR    ${i}    IN RANGE    0    5
        Log    Result of simple iteration FOR ${i}
    END
# It has 4 spaces before FOR body
```
And I got this output:

> Starting test: R Mon.testFOR
> 20200124 18:17:33.742 :  INFO : Result of simple iteration FOR 0
> 20200124 18:17:33.746 :  INFO : Result of simple iteration FOR 1
> 20200124 18:17:33.748 :  INFO : Result of simple iteration FOR 2
> 20200124 18:17:33.752 :  INFO : Result of simple iteration FOR 3
> 20200124 18:17:33.753 :  INFO : Result of simple iteration FOR 4
> Ending test:   R Mon.testFOR

**Comment by HelioGuilherme66** [comment]
Closing because there is enough documentation about the functionality.
