### ISSUE TITLE
Add CONTRIBUTING document

### ISSUE THREAD

**Issue by adrianyorke** [robotframework/RIDE#2120]
It is good practice that repositories contain a CONTRIBUTING document in the root directory.

This makes it easy for contributors, especially first time contributors, to follow project standards and create pull requests in accordance with how the maintainers would like submissions to be made.

The format of this document is normally Markdown (.md) or reStructuredText (.rst/.rest).  Both formats are used across GitHub repositories, although reStructuredText is more standardised, has more features and is better suited for project documentation, e.g. Linux kernel and Robot Framework.  A more detailed comparison can be found here: https://eli.thegreenplace.net/2017/restructuredtext-vs-markdown-for-technical-documentation/

> The RIDE project already contains reStructuredText format documents in the root directory (BUILD.rest & README.rest) so this format is recommended to maintain consistency with the existing documentation.

**Comment by adrianyorke** [comment]
@HelioGuilherme66 has shared some ideas/preferences via Slack conversation:
1. Something similar to SeleniumLibrary or Robotframework projects
2. we have two Contributing profiles. The `user/tester` that can report Issues on tracker. `developer` who wants to send code.
3. The self learning flow is enough. Reading the Wiki, and running the Demo (because allows to see and change the code).
4. There is basic structure a user must know. The App loop, the Frame, and messages/events.
5. There is a nice Elements and Events inspector that helps to see the App running mechanics (there should be somewhere a diagram of the structure of a wxPython/wxWidgets app)
6. On our CONTRIBUTING doc, we should have links to the tutorials we think good.
7. Sonar Lint and PyCharm suggestions recommended for code style, PEP8 or flake8.  The repository is not checking with CI at this time but the maintainers are considering adding this in the near future using Travis or GitActions.
8. Mention RIDE currently supports Python 3.6 & 3.7.  3.8 is not supported.
9. Git: developers should create a branch to work on and not work on master.  There is no specific guidance regarding branch naming although a short name describing the feature is commonly used.
10. Always create a branch (topic/feature branch) for the changes to be done. The commits should be short changes, and not to many files at same time.
11. wxPython has long functions names plus arguments, and they need to be split.  Minimum line length of 90 characters is proposed.
12. Black Code formatter may be taken into use in the future so consider complying with Black guidelines.  Exceptions are max line length and string delimiters (by default Black suggests double quote always).
13. Mention Wish List: https://github.com/robotframework/RIDE/wiki/Wish-List (Check we have GitHub issues for all of these as some contributors may only browse the issues looking for something to help with).

**Comment by adrianyorke** [comment]
I am currently working on the first version of this document and will issue a PR once it is ready for review.

**Comment by adrianyorke** [comment]
Added new label "good first issue" using same settings as Robot Framework project:
* good first issue
* Good for newcomers
* #7057ff

**Comment by adrianyorke** [comment]
Consider adding this project to the following site:
https://github.com/MunGell/awesome-for-beginners

* RIDE (label: good first issue)
  RIDE is a development environment for Robot Framework test cases.

**Comment by HelioGuilherme66** [comment]
Moving to 2.1 because of lack of resources (time and people)

**Comment by sofezticated-gentleman** [comment]
Hi @HelioGuilherme66 ,is this issue still open?

**Comment by HelioGuilherme66** [comment]
@sofezticated-gentleman Yes it is active.

Please follow the suggestions.

Thanks for collaborating!

**Comment by sofezticated-gentleman** [comment]
@HelioGuilherme66 I have added the points mentioned by @adrianyorke. This is my first issue so if there are any mistakes or changes please do tell me

**Comment by HelioGuilherme66** [comment]
@sofezticated-gentleman Thank you for your effort.
Let me clarify this Feature Request :) :
- We want to have a new file in the root of the project named, `CONTRIBUTING.adoc` 
(I prefer to use the ascii doctor markdown format)
- You should take a look of other projects' CONTRIBUTING` files. For example, the template of GitHub, and other Robotframework projects.
- Use the suggestions you already added to BUILD.md, but not literally
- Mostly important is to clarify how to contribute, you did part of it, but it should be:
    -- fork the project
    -- create a topic branch
    -- do the changes, commit and push to your fork and branch
    -- create a Pull Request (PR) (previous step may already print an URL to create a Pull Request)
    -- write a meaningful description of the PR and possibly include a reference to an existing Issue
    (then the maintainers, should review and merge  to `master` branch the pull request)

**Comment by sofezticated-gentleman** [comment]
@HelioGuilherme66 is there a different mailing list for RIDE users if so then please send me so that I could add it in the documentation

**Comment by sofezticated-gentleman** [comment]
Submitting Issues

> - Report Bug
> - Enhancement Request

Code contribution 

>-Chose something
>- Pull request
>- Coding Convention
>- Tests
>- Documentation

Apart from these are there any more topics or subtopics needed in the `CONTRIBUTION.adoc` file?

**Comment by HelioGuilherme66** [comment]
@sofezticated-gentleman All the communication means are those on the README.adoc page

**Comment by HelioGuilherme66** [comment]
> Apart from these are there any more topics or subtopics needed in the CONTRIBUTION.adoc file?
Those are OK.

**Comment by sofezticated-gentleman** [comment]
@HelioGuilherme66 

> @sofezticated-gentleman All the communication means are those on the README.adoc page

oh okay

**Comment by sofezticated-gentleman** [comment]
@HelioGuilherme66 where can I get more info about test, user guide and documentation for RIDE. Also do RIDE support the latest versions of Python?

**Comment by HelioGuilherme66** [comment]
`... get more info about test, user guide and documentation for RIDE. Also do RIDE support the latest versions of Python?`

Tests . We only have unit tests. look at /utest
Docs --> We only have the Wiki
Versions -> Reference is `/README.adoc` should be v1.74.2 -> supports 2.7, 3.6 and 3.7. v2.0b1 removes 2.7 and adds 3.8. Current development and 2.0b2 adds 3.9 and 3.10.

**Comment by sofezticated-gentleman** [comment]
@HelioGuilherme66  where can i find more information on unit testing for the ride and its procedure??

**Comment by JFoederer** [comment]
Did you already find this document?
https://github.com/robotframework/RIDE/blob/master/BUILD.rest#unit-tests
