### ISSUE TITLE
How to force silent or unattend installation via pip?

### ISSUE THREAD

**Issue by adampawlikowski** [robotframework/RIDE#2122]
I'm trying to automate the installation of robotframework-ride as part of an image build.  How can I pass an answer to the prompt to create a desktop shortcut?  My build is getting stuck on this portion of the installation.

**Comment by HelioGuilherme66** [comment]
@adampawlikowski I am sorry about that. As a workaround, for now, you can try to get the zip package and edit line 67 of `setup.py`:
- From: `        command = sys.executable + " " +postinstaller_file + " -install"`
- To: `        command = sys.executable + " " +postinstaller_file + "  -f -q -install"`

Other option is to copy the RIDE shortcut to the user's Desktop, before installation. This way the creation is skipped.

If these strategies don't work, remove the postinstall commands.

I can consider adding support for environment variable to control those options.

**Comment by HelioGuilherme66** [comment]
@adampawlikowski Could you try the current development version? I have added an 8 seconds timeout for the dialog. Please note that current version is for Python >= 3.6.

**Comment by HelioGuilherme66** [comment]
Closing because can be tested on soon to be pre-released, v2.0b1.
