### ISSUE TITLE
NoSuchWindowException: Message: Browsing context has been discarded

### ISSUE THREAD

**Issue by amitgla22** [robotframework/RIDE#2126]
Setup failed:
NoSuchWindowException: Message: Browsing context has been discarded

Getting this error on running the test script on firefox and chrome both, the test execution halts and keeps on waiting at the first step of opening the browser.

Any suggestions will be welcome.

Thanks
Amit jaiswal

**Comment by HelioGuilherme66** [comment]
@amitgla22 That is not an issue report. That should be searched on the Internet. It is not RIDE issue.
(looks like a problem with Selenium).
