### ISSUE TITLE
Running ride.py invokes error from CMD line - v. 1.7.4.1

### ISSUE THREAD

**Issue by SoupStaihn** [robotframework/RIDE#2127]
I just installed the package and when I run ride.py I get

botide.preferences.configobj.UnreprError'> Parse error in value at line 44.
<class 'robotide.preferences.configobj.UnreprError'> Parse error in value at line 45.
<class 'robotide.preferences.configobj.UnreprError'> Parse error in value at line 46.
<class 'robotide.preferences.configobj.UnreprError'> Parse error in value at line 47.
<class 'robotide.preferences.configobj.UnreprError'> Parse error in value at line 48.
<class 'robotide.preferences.configobj.UnreprError'> Parse error in value at line 49.
<class 'robotide.preferences.configobj.UnreprError'> Parse error in value at line 50.
<class 'robotide.preferences.configobj.UnreprError'> Parse error in value at line 51.
<class 'robotide.preferences.configobj.UnreprError'> Parse error in value at line 52.
<class 'robotide.preferences.configobj.UnreprError'> Parse error in value at line 53.
<class 'robotide.preferences.configobj.UnreprError'> Parse error in value at line 54.
<class 'robotide.preferences.configobj.UnreprError'> Parse error in value at line 55.
<class 'robotide.preferences.configobj.UnreprError'> Parse error in value at line 56.
<class 'robotide.preferences.configobj.UnreprError'> Parse error in value at line 57.
<class 'robotide.preferences.configobj.UnreprError'> Parse error in value at line 58.
<class 'robotide.preferences.configobj.UnreprError'> Parse error in value at line 59.
<class 'robotide.preferences.configobj.UnreprError'> Parse error in value at line 60.
<class 'robotide.preferences.configobj.UnreprError'> Parse error in value at line 61.

**Comment by Nyral** [comment]
That's cause you're trying to use RIDE with Python 3.8
If you had bothered to read the release notes or the README, you'd have seen that we don't support that yet.

**Comment by SoupStaihn** [comment]
Ouch.  I just started using this.  Don't bite me.

**Comment by fatou705** [comment]
Hello
When it is possible tu use RIDE with Python 3.8?
Thanks

**Comment by HelioGuilherme66** [comment]
@fatou705 Don't expect it to be soon. I use Fedora 31, and only Fedora 32 will have Python 3.8, first beta of Fedora 32 will be in the end of February.
What you can do if on Windows or MacOS is to install from current development, where a fix for Python 3.8 was merged. If you do that please comment on the issues with tag **Python3.8**, mentioning your OS and result of test. Thanks.

**Comment by HelioGuilherme66** [comment]
Fixed by #2128
