### ISSUE TITLE
Cannot edit existing cell text with F2

### ISSUE THREAD

**Issue by theHumanCentipede** [robotframework/RIDE#2135]
I remember from the past that pressing F2 under a cell left the text cursor at the end of the existing text to complete or reedit the cell.
After last upgrade I've noticed that this behaviour is not present anymore. F2 under a cell 'removes' the focus and you cannot edit anymore the cell until you use the mouse and click to get back the focus

RIDE 1.7.4.1 running on Python 3.6.5.  (OS Windows10)

**Comment by Nyral** [comment]
We had to remove focus on Windows because it was causing text selection to become stuck on Windows 10. It should work fine on Linux or MacOS.

**Comment by HelioGuilherme66** [comment]
Fixed by #2140
