### ISSUE TITLE
Content of json editor turn to be string when open again 

### ISSUE THREAD

**Issue by Fengjiya** [robotframework/RIDE#2139]
days ago ,I entered in the json editor ,like this :
{
    "type": 1,
    "skuID": [  ${skuId
        }
    ],
    "skuType": [
        1
    
}

But when I open the ride editor cell with json editor ,it turn out to be :
{ \ \ \ \ "type": 1, \ \ \ \ "skuID": [ \ \ \ \ \ \ \ \ ${skuId} \ \ \ \ ], \ \ \ \ "skuType": [ \ \ \ \ \ \ \ \ 1 \ \ \ \ ] }

Version :Python2.7.17 + RIDE 1.7.3.1

**Comment by HelioGuilherme66** [comment]
Worked fine on Linux with Python 3.7.5 + RIDE current development.
Example:
```
    ${skuId}=    Set Variable    teste
    ${jvar}=    Set Variable    {"type": 1, "skuID": ["${skuId}"], "skuType": [1]}
    Log Many    ${skuId}    ${jvar}
```

**Comment by HelioGuilherme66** [comment]
If you copy from JASON editor, you'll get that formatted data. But the usual process is to Save (which validates JASON).
![image](https://user-images.githubusercontent.com/2866630/74610069-ce7a2400-50e7-11ea-9da5-f22bdec694a1.png)
