### ISSUE TITLE
 ride 1.7.4.1 CTRL + 1 function is available, but the content is not in ${}, now ${} is outside

### ISSUE THREAD

**Issue by xieyingbiao** [robotframework/RIDE#2145]
ride 1.7.4.1 CTRL + 1 function is available, but the content is not in ${}, now ${} is outside

**Comment by HelioGuilherme66** [comment]
@xieyingbiao If you are using Python 3, then you can try our development code for RIDE v2.0 on `master`, it has that fixed. Just see the README.

**Comment by HelioGuilherme66** [comment]
Closing because can be tested on soon to be pre-released, v2.0b1.
