### ISSUE TITLE
I get thousands of gtk_widget_set_allocation: assertion

### ISSUE THREAD

**Issue by elschman** [robotframework/RIDE#2147]
I I scroll inside the testsuite subwindow I get thousands of lines of 
(ride.py:6508): Gtk-CRITICAL **: 14:59:44.871: gtk_widget_set_allocation: assertion '_gtk_widget_get_visible (widget) || _gtk_widget_is_toplevel (widget)' failed

Ubuntu 18.04.4

**Comment by HelioGuilherme66** [comment]
This is only showing in console. Don't know if we can fix it, because is the wxPython originating it (may have change the way to process elements).
