### ISSUE TITLE
RIDE TaskBar icon in Win10 is black on dark grey... hard to see

### ISSUE THREAD

**Issue by CMTaylor** [robotframework/RIDE#2148]
![RIDE_Icon](https://user-images.githubusercontent.com/1346041/75463005-29671300-5953-11ea-8165-23ba90ea05f8.png)
The "Robot Face" icon is fine, but please change it to a brighter colour (like green passing icon or blue executing icon in RIDE) so that it can be seen in Win10.

**Comment by HelioGuilherme66** [comment]
@CMTaylor If you like, just replace the file [..\site-packages\robotide\widgets\robot.ico](https://github.com/robotframework/RIDE/blob/master/src/robotide/widgets/robot.ico) in your installed files.
