### ISSUE TITLE
Failed bulding wheel for wxPython

### ISSUE THREAD

**Issue by pauri32** [robotframework/RIDE#2150]
Hi,

I'm trying to install RIDE for Ubuntu 18.04, and I have problems when:

`Running setup.py bdist_wheel for wxPython ...`

The installation gets stucked from this point and the system hungs if I don't stop the running. The versions installed are python 3.6.9 and wxPython 4.0.7.post2.

**Comment by HelioGuilherme66** [comment]
Real machine or virtual? What was the initial command to install RIDE? This one?
```
sudo python3 -m pip install robotframework-ride
```

**Comment by pauri32** [comment]
It's a real machine, but I was trying to install it with other commands. After using this initial command RIDE is installed, thank you.
