### ISSUE TITLE
Getting error while running ride.py

### ISSUE THREAD

**Issue by Sharmarahul09** [robotframework/RIDE#2161]
on ubuntu 16.04.6 LTS, I installed a robot framework and ride.
the installation was with no error.
but when I launch ryde.py,
the RIDE 's GUI is not open and the ERROR MESSAGE below is displaying on the screen.
And I have installed Ride first then wxpython (By mistake)

the configuration is:
 ubuntu 16.04.6 LTS

*python --version
Python 2.7.12
*robot --version
Robot Framework 3.1.2 (Python 2.7.12 on linux2)
*pip list
robotframework                  3.1.2                 
robotframework-ride             1.7.4.1               
robotframework-selenium2library 3.0.0                 
robotframework-seleniumlibrary  4.3.0 

*sudo aptitude search python-wxgtk2.8
i   python-wxgtk2.8                                                                       - wxWidgets Cross-platform C++ GUI toolkit (wxPython binding)                                    
p   python-wxgtk2.8:i386                                                                  - wxWidgets Cross-platform C++ GUI toolkit (wxPython binding)                                    
p   python-wxgtk2.8-dbg                                                                   - wxWidgets Cross-platform C++ GUI toolkit (wxPython binding, debug version)                     
p   python-wxgtk2.8-dbg:i386                                                              - wxWidgets Cross-platform C++ GUI toolkit (wxPython binding, debug version)     

*sudo aptitude search python-wxversion
i A python-wxversion                                                                      - API for selecting the wxPython version to use

This is the error message i recieve after running ride.py

Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/robotide/__init__.py", line 82, in main
    _run(inpath, not noupdatecheck, debug_console)
  File "/usr/local/lib/python2.7/dist-packages/robotide/__init__.py", line 111, in _run
    ride = RIDE(inpath, updatecheck)
  File "/usr/local/lib/python2.7/dist-packages/robotide/application/application.py", line 45, in __init__
    wx.App.__init__(self, redirect=False)
  File "/usr/lib/python2.7/dist-packages/wx-2.8-gtk2-unicode/wx/_core.py", line 7981, in __init__
    self._BootstrapApp()
  File "/usr/lib/python2.7/dist-packages/wx-2.8-gtk2-unicode/wx/_core.py", line 7555, in _BootstrapApp
    return _core_.PyApp__BootstrapApp(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/robotide/application/application.py", line 61, in OnInit
    coreplugins.get_core_plugins())
  File "/usr/local/lib/python2.7/dist-packages/robotide/context/coreplugins.py", line 22, in get_core_plugins
    from robotide.editor.texteditor import TextEditorPlugin
  File "/usr/local/lib/python2.7/dist-packages/robotide/editor/texteditor.py", line 48, in <module>
    import robotframeworklexer
  File "/usr/local/lib/python2.7/dist-packages/robotide/editor/robotframeworklexer.py", line 18, in <module>
    from pygments.lexer import Lexer
  File "/usr/local/lib/python2.7/dist-packages/pygments/lexer.py", line 49
    class Lexer(metaclass=LexerMeta):
                         ^
SyntaxError: invalid syntax

Use --help to get usage information.

**Comment by HelioGuilherme66** [comment]
@Sharmarahul09 First, try to uninstall Pygments, and then see if RIDE starts. If success you have to install a version of Pygments that would work on your python 2.7.

**Comment by Sharmarahul09** [comment]
> @Sharmarahul09 First, try to uninstall Pygments, and then see if RIDE starts. If success you have to install a version of Pygments that would work on your python 2.7.
> 
> Also, the wxPython version should be updated, download or install from wxpython.org.

I'm not able to uninstall Pygments tried  to find in the dpkg --list ,still not successful
How to uninstall Pygments?

**Comment by HelioGuilherme66** [comment]
Pygments, like the other libraries RIDE uses are installed with `pip` . I would try to update pygments to the version 2.5.2:
```
sudo -H pip install -U --force pygments==2.5.2
```

**Comment by disalassalyjose** [comment]
Had the same issue, fixed with the version of pygment 2.5.2.
