### ISSUE TITLE
Unable to run Robot Test from eclipse RIDE

### ISSUE THREAD

**Issue by ramganesh19** [robotframework/RIDE#2171]
![image](https://user-images.githubusercontent.com/12521269/77678189-c7ec9100-6f5e-11ea-8ff1-a361f4dcf210.png)

An internal error occurred during: "Launching Robot Tests".
Unable to find output console. Trying to look for a console with name:
Login.robot [Robot] C:\Users\....\AppData\Local\Programs\Python\Python37\python.exe

C:\Users\...>python --version
Python 3.7.7

C:\Users\.....>pip --version
pip 20.0.2 from c:\users\saura\appdata\local\programs\python\python37\lib\site-packages\pip (python 3.7)

C:\Users\....>pip list
Package        Version
-------------- -------
pip            20.0.2
robotframework 3.1.2
setuptools     41.2.0

Eclipse IDE for Enterprise Java Developers.

Version: 2020-03 (4.15.0)
Build id: 20200313-1211

Latest RED using Eclipse Marketplace

**Comment by ramganesh19** [comment]
@HelioGuilherme66 Appreciate some input on why it got. I tired resetting the Robot perspective and see both console and message log window open, but i still get error. Sorry it could be silly mistake i am making, but i am kind of stuck at this point

**Comment by HelioGuilherme66** [comment]
@ramganesh19 This is RIDE issue tracker not RED.

**Comment by ramganesh19** [comment]
Thanks. I just found out and saw your comments. Appreciate your response

**Comment by mbrabante** [comment]
Hi @ramganesh19 ,

Were you able to fix this issue? If yes, kindly advise how did you fix it.

Appreciate any inputs you could provide. Thank you!

**Comment by EarlGrey65** [comment]
Hello @ramganesh19,
I have the same issue on CentOS 8.
Did you solve the problem?
Thank you!
