### ISSUE TITLE
File disappear from Menu Tree after it be modified by outer editor

### ISSUE THREAD

**Issue by garrett-liu** [robotframework/RIDE#2183]
In RIDE, Open Directory, files show in Menu Tree. Then I open one file in another editor, modify the file.
When I check RIDE Menu Tree, sometimes the modified file disappear and I can't reload it unless to close and reopen RIDE.

**Comment by HelioGuilherme66** [comment]
Need more info. It is not clear the procedure to reproduce. What type of file are you talking? What changes you do in the outer editor? What operating system? What version of RIDE? What version of Python?

**Comment by jnhyperion** [comment]
@garrett-liu did you rename the data files from outer editor?

I found out a similar reproduce steps:

1. rename data file from out editor
2. click the original file in the RIDE tree
3. click yes button of the "File changed on disk" popup

then that data file will disappear forever until you restart RIDE or reopen workspace directory.

**Comment by HelioGuilherme66** [comment]
@jnhyperion Thank you for researching this (and for all the other fixes). I'd like to talk directly to you. Do you have access to our Slack, or other instant chat system?

About this problem, we also have #1930, and there is a wxPython function to get a broadcast of changed files on disk (we should be listening to the specific files or directories). Maybe you could study that solution. Thanks.

**Comment by jnhyperion** [comment]
@HelioGuilherme66 let's talk in slack.

**Comment by garrett-liu** [comment]
There are more information.
1.text file which named as xxx.robot.
2.Operating system is Win 10 Enterprise.
3.
robotframework-ride           1.7.4.2
wxPython                      4.0.7.post2
Python 3.7.6

Because the editor in RIDE is  hard-to-use,  I use RED to edit my scripts. Sometimes I need to run script in RIDE because it easy to select case. So I will open the same folder in RED and RIDE, modify script content in RED, then click the file in RIDE to update.  I don't change the file name. But sometimes the file will disappear.

**Comment by HelioGuilherme66** [comment]
@garrett-liu Thanks for the information.
We would like to improve RIDE, so please clarify when you say is hard-to-use. Are you talking about the Grid/Cell Editor, or Text Editor?
What things you think RIDE is missing that RED is better?

**Comment by garrett-liu** [comment]
@HelioGuilherme6
When I use RIDE in Win10, I feel it has below problems or insufficient.
1.When there are many folders and expand dozens and hundreds of testcases in Menu tree,  win10 will has no response when click RIDE menu or switch application for some minutes. This problem is fatal.

2. Grid/Cell Edittor and Text Editor, the characters are fuzzy.
3.Test Editor,  will auto change the code position if the line start with ... or #.  It'a a trouble when I compare files between local and git repo.
4.Cell Edittor, if the keyword name which in the first colucm is long, it will auto line feed, but the line height will don't change, so I can't see the keyowrd which in second line.
5.Text editor, can't highlight the selected keyword/parameter in same page.
6.Text editor, can't find/replace in page or in project.

I and most of my colleagues use the Text editor in most of the time, because many of our cases are complex and have many relationships. And in Text editor, it easy to copy from one case and past to next case.
We need to write many keywords as user library. In many times, we need the editor as a simple source code editor (highlight,  jump to definition, find and replace, etc.)
