### ISSUE TITLE
Newbie here ! Ride.py the system cannot execute the specified program

### ISSUE THREAD

**Issue by patrickepce** [robotframework/RIDE#2185]
Hello everybody, i'm new in these python, pip & robotframework things and i have some issues about ride.py.  As you can see on the topics, i have that problem and haven't found any solution for it & i found these and this must be the perfect place that will help me to solve my problem, so here is the thing :

1. I watch on youtube about setting up robotframework (install python -> pip -> robotframework -> wxpython -> robotframework-ride -> run ride.py)
2. At first i use the latest version for all steps, then when i run ride.py i got error & i search for it and i came across solution that says this version of Ride is not compatible with Python v3.8.2 and have to wait for Ride v2.0
3. So, i uninstall everything and reinstall using Python v3.7 then pip -> robotframework-> wxpython -> robotframework-ride, everything went and then 
4. This thing happens
![image](https://user-images.githubusercontent.com/64345190/80298483-f7d5c100-87b6-11ea-8b56-5499c64bce92.png) 
5. Here is the info for all my installation using pip freeze
![image](https://user-images.githubusercontent.com/64345190/80298491-0fad4500-87b7-11ea-9d03-ab62b64d900c.png)

And i haven't found the solution for it, please help Oh great Github people !

Thankyou so much

**Comment by HelioGuilherme66** [comment]
@patrickepce The new version of wxPython may have caused problems for our released version. You can try to install our development version, see the README on our code page. Otherwise you can install wxPython version 4.0.7.post2.

**Comment by patrickepce** [comment]
@HelioGuilherme66 okay thankyou so much ! i'm going to try it

**Comment by HaaiHenkie** [comment]
Hello @HelioGuilherme66,
I noticed a new release 1.7.4.2 which actually deals with this problem:

> The only change on this version is making the wxPython version locked up to 4.0.7.post2.

However, when I do a clean install of this version (i.e. wxPython is not installed), wxPython 4.1.0 will be installed. In the repository I have checked setup.py for the Release/1.7.4.2 branch and indeed it contains the requirement `'wxPython<=4.0.7.post2'`. Then I made a local clone of this branch and installed it to a virtual environment with `pipenv install -e .`. The result was that the correct version 4.0.7.post2'of wxPython was installed.

So the release itself is correct. I believe something went wrong with packaging the release. Ik packaged myself with `python setup.py sdist bdist_wheel` and compared the generated wheel with the one downloaded from PyPI. I found a difference on line 20 of robotframework_ride-1.7.4.2.dist-info/METADATA. In the locally generated wheel it says `Requires-Dist: wxPython (<=4.0.7.post2)` and in the wheel downloaded from PyPI it says:`Requires-Dist: wxPython`.

You might want to release a post-release to correct this,

Best regards,

Henk

**Comment by HaaiHenkie** [comment]
Small addition: I just saw that RIDE download from PyPI is a zip and not a wheel. The zip contains a setup.py different  from the one in the Release/1.7.4.2 branch at Github. At line 25 the new restriction is missing:

    REQUIREMENTS = ['wxPython', 'PyPubSub', 'Pygments']

**Comment by HelioGuilherme66** [comment]
@HaaiHenkie Thank you for your analysis. I noticed that my new version did not do the intended result, but I thought it was a limitation of `pip`. I'll see if I can fix it.

**Comment by HelioGuilherme66** [comment]
@HaaiHenkie The package is now fixed on PyPi. Normal install with `pip install robotframework` should consider wxPython version.

**Comment by HaaiHenkie** [comment]
Hello @HelioGuilherme66 ,

Yes it worked! To get it working I had to delete my pip cache, so for all people that already did the upgrade it would have been better if you had made a new version.

Best regards,

Henk
