### ISSUE TITLE
Getting from: can't read /var/mail/robotide in ubuntu 16

### ISSUE THREAD

**Issue by praveens24** [robotframework/RIDE#2191]
ride.py
from: can't read /var/mail/robotide
/usr/local/bin/ride.py: line 27: syntax error near unexpected token `*sys.argv[1:]'
/usr/local/bin/ride.py: line 27: `    main(*sys.argv[1:])'

Note: robotide in /var/mail/

**Comment by HelioGuilherme66** [comment]
Not enough information. What is the version of python? What is the version of RIDE? How was installed?

**Comment by praveens24** [comment]
Python 3.8.2,

sudo pip install -U robotframework-ride==1.7.4.2

**Comment by HelioGuilherme66** [comment]
@praveens24  See the project README, or FAQ. RIDE for Python 3.8, must be the development version.
