### ISSUE TITLE
No Test Selected Message for the Selected Testcase.

### ISSUE THREAD

**Issue by harikarthickt** [robotframework/RIDE#2193]
![Screenshot (411)](https://user-images.githubusercontent.com/27634017/81041064-7c68c380-8eca-11ea-8485-afd3a0523d3c.png)

- I have rearranged the testcases using ctrl + up and ctrl + down.
- Once I have rearranged, I selected a testcase and click the "Run" button.
- It shows that pop window with the message - "No Tests Selected. Continue Anyway?"

**Comment by HelioGuilherme66** [comment]
Could not reproduce on Windows 10 with (from RIDE Log):
```
20200505 15:18:20.054 [INFO]: Found Robot Framework version 3.1.2 from D:\vpython\python27\lib\site-packages\robot.

20200505 15:18:20.055 [INFO]: Started RIDE 1.7.4.2 using python version 2.7.16 with wx version 4.0.7.post2 in win32.
```

Please @harikarthickt post here the same info from RIDE Log. Thanks

**Comment by harikarthickt** [comment]
Sorry it is not reproducible. Hence I am closing this issue.
