### ISSUE TITLE
Relax Pywin32 requirement

### ISSUE THREAD

**Issue by merovingien** [robotframework/RIDE#2194]
Hello,

First thanks for your great work on RIDE !

I try to install it on MSys2 based python, via pip, and it fails to get Pywin32. After research, it is because Pywin32 is not compatible with Python built with mingw compiler, which is used by MSys. There are works in progress but it seems to be tricky.

But Pywin32 is required by RIDE only to create a desktop shortcut, and I consider this feature as optional : missing shortcut is acceptable to me, compared to no installation at all or to take a dedicated version of Python only to install RIDE.

So, is there a way to set Pywin32 as an optional requirement ? Or a way to create the shortcut without using Pywin32 ?

Thanks for your attention.

**Comment by jnhyperion** [comment]
You can use command:

pip install --no-deps robotframework-ride

tp install without any dependencies, then manually install other necessary dependcies in:

https://github.com/robotframework/RIDE/blob/master/requirements.txt
