### ISSUE TITLE
Keywords not highlighted and no suggestion for them in RIDE

### ISSUE THREAD

**Issue by axiom41** [robotframework/RIDE#2195]
Hello.
After updating robotframework-seleniumlibrary to 4.4.0, many of its keywords seem that are not recognized and “highlighted in blue” in RIDE editor (v1.7.4.2, using RF 3.2.1), and keyword suggestion does not work (for example, on “click element”, “Input text”, "Capture Page Screenshot", etc.):

![image](https://user-images.githubusercontent.com/9963199/81173394-47c73b80-8fa0-11ea-9b3a-748b7b4913e5.png)

Test execution seems to work fine anyway, but syntax highlighting and keyword suggestion are too important in test writing.

At the moment, I had to revert to v4.3.0 that works fine:

![image](https://user-images.githubusercontent.com/9963199/81173415-4eee4980-8fa0-11ea-949e-b10267f77d9a.png)

I also received this from robotframework-seleniumlibrary developer, where i initially submitted the issue:

> In Robot Framework 3.2 the dynamic library API get_keyword_arguments changed and SeleniumLibrary 4.4, by PythonLibCore changes, use the changed format if RF 3.2 or greater is used. This is RIDE specific problem, please report the problem in RIDE issue tracker. Closing this issue.

Could you please check and verify on your side, or provide some workaround to make v4.4.0 working?

Many thanks in advance for your support

Best regards

**Comment by HelioGuilherme66** [comment]
The only possible workaround, is to generate SeleniumLibrary XML for keywords documentation and then import as explained in **Import Failed Help** button in Suite Settings section.

**Comment by HelioGuilherme66** [comment]
Seems that there is no workaround for this problem. I have generated SeleniumLibrary.xml and place it on known places, but still the docs are not loaded. This may be because there are some docs in DB, and the missing ones are not loaded from the XML file. Also there is no Import XML option, because it did not failed.

Attached is the SeleniumLibrary.xml.txt (must remove .txt).
[SeleniumLibrary.xml.txt](https://github.com/robotframework/RIDE/files/4794150/SeleniumLibrary.xml.txt)

**Comment by HelioGuilherme66** [comment]
Closing because can be tested on soon to be pre-released, v2.0b1.

**Comment by sarozNep** [comment]
I still have this issue in Robot Framework 3.2.2

**Comment by Temizzi** [comment]
I have the same issue.. I am running:
- RIDE 1.7.4.2 running on Python 3.7.0.
- robotframework-seleniumlibrary 5.1.0

How to solve this?

**Comment by HelioGuilherme66** [comment]
@sarozNep and @Temizzi Please try with v2.0b1 like I mentioned on https://github.com/robotframework/RIDE/issues/2195#issuecomment-654361611

 I am not surprised that robotframework-seleniumlibrary 5.1.0 documentation can be broken.

**Comment by vncs1880** [comment]
Hello @HelioGuilherme66 thank you for the help. Apart from actually fixing the issue I noticed you had difficulties to implement your suggested workaround. May I suggest also facilitating future workarounds (i.e. things you mentioned like providing means to import xml **even if it did not fail**, or a button to **delete the db**)

> Seems that there is no workaround for this problem. I have generated SeleniumLibrary.xml and place it on known places, but still the docs are not loaded. This may be because there are some docs in DB, and the missing ones are not loaded from the XML file. Also there is no Import XML option, because it did not failed.
> 
> Attached is the SeleniumLibrary.xml.txt (must remove .txt).
> [SeleniumLibrary.xml.txt](https://github.com/robotframework/RIDE/files/4807041/SeleniumLibrary.xml.txt)
> 
> --EDIT--
> Attached is the SeleniumTestabilityLibrary.xml.txt (must remove .txt). New from instructions on [FAQ](https://github.com/robotframework/RIDE/wiki/F.A.Q.#10--q-i-have-installed-or-updated-seleniumlibrary-to-version-440-and-there-are-missing-keyword-docs-or-some-keywords-are-not-recognized-as-such-how-can-i-fix-this-so-the-keywords-help-or-auto-complete-works).
> [SeleniumTestabilityLibrary.xml.txt](https://github.com/robotframework/RIDE/files/4854871/SeleniumTestabilityLibrary.xml.txt)
> 
> --EDIT--
> @axiom41
> The above XML file is now correct, and we can have the keywords docs for SeleniumLibrary 4.4.0.
> The file will be on (Windows): `%APPDATA%\RobotFramework\ride\library_xmls\SeleniumLibrary.xml`
> Linux and MacOS: `~/.robotframework/ride/library_xmls/SeleniumLibrary.xml`
> 
> The easiest way to update this documentation is (all libraries keyword docs will have to re-generated, this may cause some delay when opening "for the first time" a test suite with a "new" Library import):
> 
> 1. With RIDE closed, delete the DB file at: `%APPDATA%\RobotFramework\ride\librarykeywords.db` or   `~/.robotframework/ride/librarykeywords.db`
> 2. Uninstall SeleniumLibrary 4.4.0 (you may need to use `sudo -H`):
>    `pip uninstall robotframework-seleniumlibrary`
> 3. Start RIDE and open or create a basic test suite using SeleniumLibrary, for example:
> 
> ```
> *** Settings ***
> Library           SeleniumLibrary
> 
> *** Test Cases ***
> SeleniumTest
>     Open Browser
> ```
> 
> 1. On the test suite settings, there is the Library import statement with SeleniumLibrary on red color. Right click on it and use `Import Library Spec XML` to locate the SeleniumLibrary.xml file attached in this comment.
> 2. Install SeleniumLibrary 4.4.0 (you may need to use `sudo -H`):
>    `pip install robotframework-seleniumlibrary`
> 
> After some seconds, the red color changes to black and you can go to Grid Editor and use the keyword docs (`Open Browser` should be in blue color, or the one you selected for keywords).

**Comment by Temizzi** [comment]
> @sarozNep and @Temizzi Please try with v2.0b1 like I mentioned on [#2195 (comment)](https://github.com/robotframework/RIDE/issues/2195#issuecomment-654361611)
> 
> I am not surprised that robotframework-seleniumlibrary 5.1.0 documentation can be broken.

Yesy v2.0b1 fixed the syntax highlight problem.. But I got a warning message saying that module 'psutil' was not found right after launch RIDE everytime as below...
![image](https://user-images.githubusercontent.com/1772583/112748737-65562700-8ff0-11eb-9bf9-4b89b0a849d6.png)

**Comment by HelioGuilherme66** [comment]
@rbradhika530 Sometimes it takes some time ;) to load the keyword docs. A restart of RIDE should fix it. If not then there should be complete error logged in Tools->View RIDE Log.
