### ISSUE TITLE
The robotframe3.0 framework runs on win10

### ISSUE THREAD

**Issue by hxr1990** [robotframework/RIDE#2196]
Does the robotframework3.0 fully support win10? I am currently using the win7 system, planning to upgrade to the win10 system, whether there will be RF script incompatibility

**Comment by HelioGuilherme66** [comment]
Yes, of course. Otherwise there would be a lot of people complaining!
Next time don't create an Issue, better ask on other forums/mailing lists/instant chat that we provide.
