### ISSUE TITLE
Arguments text box failing  when -A argument_file_foo.txt is added as option

### ISSUE THREAD

**Issue by theHumanCentipede** [robotframework/RIDE#2200]
When I use the -A option to add an argument.txt file to the command execution the text box is highlighted in RED as if an error would be present. 
The pop up windows shows the next error:
"opening argument file foo.txt failed: [Errno 2] No such file or directory"
The curious is that despite of the error when I play run the file is really found and the tests are executed with the proper arguments included in the file: 

command: robot -V bench_A_cfg.py -A argument_sets/develop.txt --argumentfile C:\Users\M0081495\AppData\Local\Temp\RIDE72zwf4p8.d\argfile.txt --listener C:\Python36-32\lib\site-packages\robotide\contrib\testrunner\TestRunnerAgent.py:62471:False C:\_mahle_electronic_code_projects\ssb_test_rf
TestRunnerAgent: Running under CPython 3.6.5

**Comment by HelioGuilherme66** [comment]
Fixed by #2453
