### ISSUE TITLE
FOR loop contains no keywords.

### ISSUE THREAD

**Issue by SourabhNew** [robotframework/RIDE#2201]
Hey,
When I run the FOR loop I get the error "FOR loop contains no keywords."
Note: Already tried degrading versions.

Below are pip details:
natsort==6.2.1
numpy==1.16.6
Pillow==6.2.2
Pygments==2.5.2
PyPubSub==3.3.0
pywin32==227
robotframework==3.2
robotframework-excellibrary==0.0.2
robotframework-ride==1.7.4.2
robotframework-selenium2library==3.0.0
robotframework-seleniumlibrary==3.0.0a2
robotframeworklexer==1.1
selenium==3.141.0
six==1.14.0
urllib3==1.25.9
wxPython==4.0.7.post2
xlrd==1.2.0
xlutils==2.0.0
xlwt==1.3.0
![ForLoopError](https://user-images.githubusercontent.com/65108820/83355724-f29fff00-a37e-11ea-800f-8b38a59636d3.PNG)
![ForLoopError2](https://user-images.githubusercontent.com/65108820/83355734-fc296700-a37e-11ea-8f9b-96d1713cc53f.PNG)

**Comment by HelioGuilherme66** [comment]
@SourabhNew I do not see any problem! The error message is correct.
