### ISSUE TITLE
FOR loop contains no keywords. 

### ISSUE THREAD

**Issue by SourabhNew** [robotframework/RIDE#2202]
Hey,
When I run the FOR loop I get the error "FOR loop contains no keywords."
Note: Already tried degrading versions.

Below are pip details:
natsort==6.2.1
numpy==1.16.6
Pillow==6.2.2
Pygments==2.5.2
PyPubSub==3.3.0
pywin32==227
robotframework==3.2
robotframework-excellibrary==0.0.2
robotframework-ride==1.7.4.2
robotframework-selenium2library==3.0.0
robotframework-seleniumlibrary==3.0.0a2
robotframeworklexer==1.1
selenium==3.141.0
six==1.14.0
urllib3==1.25.9
wxPython==4.0.7.post2
xlrd==1.2.0
xlutils==2.0.0
xlwt==1.3.0
ForLoopError
ForLoopError2

![ForLoopError](https://user-images.githubusercontent.com/65108820/83356771-dfdcf880-a385-11ea-9a75-de757c67f2dc.PNG)
![ForLoopError2](https://user-images.githubusercontent.com/65108820/83356775-e4091600-a385-11ea-8619-3a8724ee5e77.PNG)

**Comment by HelioGuilherme66** [comment]
This is exactly the same as #2201, I closed it with the below message.

@SourabhNew I do not see any problem! The error message is correct.

DO NOT OPEN MORE ISSUES LIKE THIS, USE OTHER COMMUNICATION MEANS.

Pay good attention to the error messages. In this case, the message is from Robot Framework run.
