### ISSUE TITLE
run option disable in ride

### ISSUE THREAD

**Issue by apoom15** [robotframework/RIDE#2203]
I want to install old version of ride as the lab is having older ride version.
But run option is disable in ride.
Could you please help me resolve this issue?

numpy==1.16.6
paramiko==2.7.1
Pillow==6.2.2
pycparser==2.20
Pygments==2.5.2
pylint==1.9.5
PyNaCl==1.3.0
PyPubSub==3.3.0
pywin32==227
requests==2.23.0
robotframework==2.8.2
robotframework-ride==1.5.2.1
robotframework-sshlibrary==2.1.3
scp==0.13.2
singledispatch==3.4.0.3
six==1.14.0
urllib3==1.25.9
win-inet-pton==1.1.0
wrapt==1.12.1

Start option is not working.
<img width="700" alt="ride_problem" src="https://user-images.githubusercontent.com/64464032/83381921-8c0ef580-a3ff-11ea-9331-7d1356952072.PNG">

**Comment by HelioGuilherme66** [comment]
@apoom15 You need to select an Execution Profile to activate the Run button.
