### ISSUE TITLE
Checkboxes are not visible in testsuite tree

### ISSUE THREAD

**Issue by foxter11** [robotframework/RIDE#2204]
I am using RIDE 1.7.4.2 in virtualenv with python 3.6.9, wxPython 4.0.7.post2. 
System is Ubuntu 18.04 upgraded from 16.04 some time ago but I had to install wxPython for 16.04 because some packages were still linked to 16.04 versions. 
When RIDE is started I ave no option to select specific testcases because checkboxes are not visible (only robot icon is visible left to each testcase). I tried recreating virtualenv with python2.7, re-installing wxPython, but nothing helps. 
I see following debug message on console while ride is started:
08:28:33: Debug: window wxStyledTextCtrl(0x20dcaa0, ) lost focus even though it didn't have it

**Comment by HelioGuilherme66** [comment]
@foxter11 I think you should try to force the installation of wxPython for 18.04. There must be a package at wxpython.org.

**Comment by foxter11** [comment]
With wxPython for 18.04 it doesn't even start - it fails with segmentation fault with some symlink related issues (gettime).

**Comment by HelioGuilherme66** [comment]
So, wxPython should be fixed. Try the GTK2 vs GTK3 package. Run a basic test like in this file:
```python
#!/usr/bin/env python
import wx

print(f"This app is running with wxPython version {wx.VERSION}")
app = wx.App(redirect=False, useBestVisual=True)  # Create a new app, don't redirect stdout/stderr to a window.
frame = wx.Frame(None, wx.ID_ANY, "Hello World") # A Frame is a top-level window.
frame.Show(True)     # Show the frame.
app.MainLoop()
```

**Comment by foxter11** [comment]
It's a problem with wxPython - it causes segFault on import. In the meantime I installed it on another Ubuntu 18 machine and it works fine.
