### ISSUE TITLE
smart quotes bleeding into Edit, not present in Text Edit w/macOSX host

### ISSUE THREAD

**Issue by schaefer01** [robotframework/RIDE#2206]
See framework issue titled: String compare in keyword like "Set Variable If" get SyntaxError: invalid character in identifier (<string>, line 1) #3371

The response before closing the issue blamed the user for a RIDE/OS problem. MacOSX has smart quotes that needs to be disabled inside the RIDE tool.

The closing comment for #3371: "such functionality should be disabled."  is not useful if, for some apps smart quotes are needed and in other apps, like RIDE, smart quotes are harmful.

thx!

**Comment by HelioGuilherme66** [comment]
@schaefer01 I have plans to fix that on issue #2159.

**Comment by HelioGuilherme66** [comment]
Fixed by #2247
