### ISSUE TITLE
Adding "..." as a prefix to ELSE in edit becomes two lines of "..." in text edit, weird right?

### ISSUE THREAD

**Issue by schaefer01** [robotframework/RIDE#2207]
I looks like this:

Run Keyword if    ${result.rc} == 0    log    first
    ...
    ...    ELSE    log    second

So I run and get the expected error. I then delete the first line of ... and the test passes, 
but the edit box now appends the else to the next column in the if statement, like this:

Run Keyword if    ${result.rc} == 0    log    first  ELSE    log    second

Is this expected and normal behavior?  If so, when where is this documented?

thanks,
  bob s.

I'm using ride v1.7.4b2

**Comment by HelioGuilherme66** [comment]
I did not tested on v1.7.4b2 but on development version, and I do not get that behavior. I do get the ... removed from Grid Editor, and not on Text Editor. A single ... on a line before ELSE is removed in Text Editor.

**Comment by schaefer01** [comment]
Do you have a regression test suite for robot foundation?

Do you have a sets of tests under robot framework that can be used to test RIDE? That would be pretty sweet!

On Jun 12, 2020, at 5:16 PM, Hélio Guilherme <notifications@github.com<mailto:notifications@github.com>> wrote:



I did not tested on v1.7.4b2 but on development version, and I do not get that behavior. I do get the ... removed from Grid Editor, and not on Text Editor. A single ... on a line before ELSE is removed in Text Editor.
