### ISSUE TITLE
deleting text doesn't deleted until overwritten

### ISSUE THREAD

**Issue by schaefer01** [robotframework/RIDE#2208]
Hi,
  If I delete a command in the "edit" screen, such as "comment" or "fatal error", but do not overwrite with something else, even a space character, the command comes back when I click the save icon.

I'm using ride 1.7.4b2, etc. etc.

I'm trying to check as many RIDE keywords/features as I can in RIDE as my project intends to use RIDE for testing new hardware and software intended for a smallsat/ space application. 
How cool is that?

Do you have a test suite in RIDE that tests all the features of RIDE - so I don't have to keep bugging you with everything I discover, day by day? I'm more concerned of any fatal issues that would prevent our use of RIDE or robot framework, rather than the small stuff.

bob s.

**Comment by HelioGuilherme66** [comment]
Thanks for the report. I confirm the bug :(

We only have Unit tests. We sure would like to have functional tests, but would need to first select the library to test, like, SikuliLibrary or other image based. It must be cross-platform.

**Comment by schaefer01** [comment]
hi, Hélio

 thank you, I’m thrilled this is an active open source project with someone looking at issues!

 question, not an issue:  I’m looking for a link to all keywords (not user defined keywords but for all built-in keywords.

   I’ve found if, else, loop, comment, variable definition, log, run, should-be - but they are all in different places in the documentation.

   Is there as simple list of all keywords so I can test their function?

bob s.



On Jun 15, 2020, at 8:33 AM, Hélio Guilherme <notifications@github.com<mailto:notifications@github.com>> wrote:



Thanks for the report. I confirm the bug :(

We only have Unit tests. We sure would like to have functional tests, but would need to first select the library to test, like, SikuliLibrary or other image based. It must be cross-platform.

**Comment by HelioGuilherme66** [comment]
The documentation at robotframework.org is the best place to look.

If you explore RIDE, then you have a link at **Help->User Guide**.

As you have seen, I removed unneeded text from your previous message. Please don't do that. And this Issue tracker should only be used to report and talk about the reported problem.

**Comment by schaefer01** [comment]
ok, will do.

On Jun 15, 2020, at 8:49 AM, Hélio Guilherme <notifications@github.com<mailto:notifications@github.com>> wrote:



The documentation at robotframework.org<http://robotframework.org> is the best place to look.

If you explore RIDE, then you have a link at Help->User Guide.

As you have seen, I removed unneeded text from your previous message. Please don't do that. And this Issue tracker should only be used to report and talk about the reported problem.

**Comment by HelioGuilherme66** [comment]
@schaefer01 Please confirm if the problem still exists in current Beta or development from `master`.

**Comment by schaefer01** [comment]
Hi, I don't know.
I am bouncing across different aspects of a project where robot is just one part. When I pick up robot again, I'll either detect the problem again, or it will have been fixed, and I won't. I won't know until then.
