### ISSUE TITLE
variable creation, weird interaction with reusing the same variable name across test cases

### ISSUE THREAD

**Issue by schaefer01** [robotframework/RIDE#2209]
Hi,
  If I use the same variable in two test cases, without adding the variable at the top level settings, the second use generates an error that seems to indicate the variable creation as not a keyword.

I used the keyword  "${result}=" twice in two test cases, I even copy-and-pasted to make sure the problem wasn't a spelling error for the second case. The problem didn't go away until I added "${result}" to the top level settings Variable.

I'm not sure if this is a RIDE or framework issue. 
I'm using RIDE v1.7.4b2, and framework, the latest available by pip for macosx.
thx,
 bob s..

**Comment by HelioGuilherme66** [comment]
@schaefer01 (Bob?)
It is always good if you can paste the exact error message. That one looks like from robotframework level, specially if it appears at Run time, console or info logs. Try to make an example that we can use to confirm (and please use the code formatting when reporting).
For these cases, if you can, please use the Slack channel #ride, on the README we have a link to register in Slack.

**Comment by schaefer01** [comment]
Ok,
  I’ll replicate the error and get back to you

On Jun 15, 2020, at 8:43 AM, Hélio Guilherme <notifications@github.com<mailto:notifications@github.com>> wrote:



@schaefer01<https://github.com/schaefer01> (Bob?)
It is always good if you can paste the exact error message. That one looks like from robotframework level, specially if it appears at Run time, console or info logs. Try to make an example that we can use to confirm (and please use the code formatting when reporting).
For these cases, if you can, please use the Slack channel #ride, on the README we have a link to register in Slack.

**Comment by schaefer01** [comment]
I could not duplicate this issue in a new project/test case. 
I withdraw this as an issue.

**Comment by HelioGuilherme66** [comment]
Good to know.
I this case, you could have closed your own Issue ;)
I'll do it for you.

**Comment by schaefer01** [comment]
I’m new to this, no surprise.

On Jun 15, 2020, at 12:07 PM, Hélio Guilherme <notifications@github.com<mailto:notifications@github.com>> wrote:



Good to know.
I this case, you could have closed your own Issue ;)
I'll do it for you.
