### ISSUE TITLE
Can't edit list or dictionary variables with macos version

### ISSUE THREAD

**Issue by it40093** [robotframework/RIDE#2213]
I have RIDE 1.7.4.2 running on MacOs Catalina, I try creating a new dictionary variable but I'm not able to see columns where to fill values, see attached image.

![image](https://user-images.githubusercontent.com/25978208/85876928-b5d8f380-b7d6-11ea-9df6-455f4bdc2eb2.png)

**Comment by HelioGuilherme66** [comment]
@it40093 Please paste here information about the Python version and also the wxPython. You get this from RIDE>Tools>View RIDE Log.

Thanks.

**Comment by it40093** [comment]
RIDE 1.7.4.2 using python version 3.7.7 with wx version 4.0.7.post2 in darwin
thanks

**Comment by HelioGuilherme66** [comment]
@it40093 Hello,
I have tested in Catalina, and I don't see the same you do.
![image](https://user-images.githubusercontent.com/2866630/86223443-7831ed00-bb7f-11ea-8c99-a67b15a91a46.png)

**Comment by it40093** [comment]
Hi Helio,
thanks for ypur reply. It looks like the issue is not related to OS. What else can I check in my installation?

**Comment by HelioGuilherme66** [comment]
You may try to start ride.py from terminal to see debug messages. Then create a new project and add a Dictionary variable. I don't have any other ideas.

**Comment by it40093** [comment]
Hi Helio, by running RIDE from terminal I get the following message:
This program needs access to the screen. Please run with a Framework build of python, and only when you are logged in on the main display of your Mac.
Any suggestion?

**Comment by HelioGuilherme66** [comment]
That message is from operating system. I think it is missing permissions to run from terminal. There are some tutorials on the Net, explaining how to change those permissions on MacOS Catalina.

**Comment by jnhyperion** [comment]
@it40093 it's probably because you're using a virtual python environment.

**Comment by it40093** [comment]
yes, you're right. I tried running ride.py with pythonw and it works. By this way  the editor for lists and dictionaries works properly and each time I edit a list (or dictionary) the following message is shown on the teminal: 
DEBUG: Called resize coluumns, width=586.
I discovered that the old command script starting RIDE was pointing a different python installation out of virtual enviroment. 
So at the end it seems that the issue is related to my installation, and thenfore you may close it.
Many thanks for your help

**Comment by HelioGuilherme66** [comment]
Closing because problem is not observed on correct installation of RIDE.
