### ISSUE TITLE
        Run Keyword If    ELSE    reports error

### ISSUE THREAD

**Issue by markicos** [robotframework/RIDE#2222]
Run Keyword If    ${time}!= 0.0    keywordX    ${var} 
        ELSE    Log Many    This is not working

It reports 'Else' is a reserved keyword. It must be in uppercase (ELSE) when used as a marker with 'Run Keyword If'.

**Comment by HelioGuilherme66** [comment]
Closing Issue as fixed.
Currently on RIDE v2.0.2.dev1 in Fedora Linux 36, Python 3.10.10, wxPython 4.0.7 (KDE Plasma 5 with darkmode, custom colors)

Screen captures:
![image](https://user-images.githubusercontent.com/2866630/230778542-4737dcfd-2d9e-4ade-a58a-ece9870ab4f4.png)

![image](https://user-images.githubusercontent.com/2866630/230778744-ac5f0842-e231-4729-917c-675b2e6080b8.png)

Test file
```robot
*** Test Cases ***
Run If False
    Run Keyword If    "${TRUE}" != "${TRUE}"    Run Keyword If    "${TRUE}" != "${TRUE}"    Log    A    loglevel=DEBUG
    ...    ELSE    Log    B    loglevel=DEBUG
    ...    ELSE    Log    C    loglevel=DEBUG
    #ELSE    Log    B    loglevel=DEBUG
    #ELSE    Log    C    loglevel=DEBUG

Run If Else
    Run Keyword If    "${TRUE}" != "${TRUE}"    Log    A    level=WARN
    ...    ELSE IF    "${TRUE}" == "${TRUE}"    Log    B    level=INFO
    ...    ELSE    Log    C    level=DEBUG
```
