### ISSUE TITLE
Should remove html format data file support

### ISSUE THREAD

**Issue by jnhyperion** [robotframework/RIDE#2226]
Because from from Robot Framework 3.2 HTML files are not supported at all.

**Comment by HelioGuilherme66** [comment]
This is being considered, but not to remove completely. I plan to have a convert suggestion when a file of that type is opened.
This will be handled later when Robot Framework 3.2.1 be the internal library, and this is not expected to go in RIDE 2.0.

**Comment by HelioGuilherme66** [comment]
Fixed since v2.1dev3.
