### ISSUE TITLE
Error loading theme icon 

### ISSUE THREAD

**Issue by lidanqing123** [robotframework/RIDE#2227]
~$ ride.py

(ride.py:17800): Gtk-WARNING **: 18:36:29.699: Error loading theme icon 'go-previous' for stock: Unable to load image-loading module: /usr/lib/x86_64-linux-gnu/gdk-pixbuf-2.0/2.10.0/loaders/libpixbufloader-svg.so: /lib/x86_64-linux-gnu/librsvg-2.so.2: undefined symbol: cairo_tag_end

(ride.py:17800): Gtk-WARNING **: 18:36:29.701: Error loading theme icon 'go-next' for stock: Unable to load image-loading module: /usr/lib/x86_64-linux-gnu/gdk-pixbuf-2.0/2.10.0/loaders/libpixbufloader-svg.so: /lib/x86_64-linux-gnu/librsvg-2.so.2: undefined symbol: cairo_tag_end

(ride.py:17800): Gtk-WARNING **: 18:36:29.719: Error loading theme icon 'document-open' for stock: Unable to load image-loading module: /usr/lib/x86_64-linux-gnu/gdk-pixbuf-2.0/2.10.0/loaders/libpixbufloader-svg.so: /lib/x86_64-linux-gnu/librsvg-2.so.2: undefined symbol: cairo_tag_end

(ride.py:17800): Gtk-WARNING **: 18:36:29.722: Error loading theme icon 'folder' for stock: Unable to load image-loading module: /usr/lib/x86_64-linux-gnu/gdk-pixbuf-2.0/2.10.0/loaders/libpixbufloader-svg.so: /lib/x86_64-linux-gnu/librsvg-2.so.2: undefined symbol: cairo_tag_end

(ride.py:17800): Gtk-WARNING **: 18:36:29.724: Error loading theme icon 'document-save' for stock: Unable to load image-loading module: /usr/lib/x86_64-linux-gnu/gdk-pixbuf-2.0/2.10.0/loaders/libpixbufloader-svg.so: /lib/x86_64-linux-gnu/librsvg-2.so.2: undefined symbol: cairo_tag_end

(ride.py:17800): Gtk-WARNING **: 18:36:29.727: Error loading theme icon 'document-save-as' for stock: Unable to load image-loading module: /usr/lib/x86_64-linux-gnu/gdk-pixbuf-2.0/2.10.0/loaders/libpixbufloader-svg.so: /lib/x86_64-linux-gnu/librsvg-2.so.2: undefined symbol: cairo_tag_end

(ride.py:17800): Gtk-WARNING **: 18:36:29.750: Error loading theme icon 'drive-harddisk' for stock: Unable to load image-loading module: /usr/lib/x86_64-linux-gnu/gdk-pixbuf-2.0/2.10.0/loaders/libpixbufloader-svg.so: /lib/x86_64-linux-gnu/librsvg-2.so.2: undefined symbol: cairo_tag_end

(ride.py:17800): Gtk-WARNING **: 18:36:29.752: Error loading theme icon 'media-optical' for stock: Unable to load image-loading module: /usr/lib/x86_64-linux-gnu/gdk-pixbuf-2.0/2.10.0/loaders/libpixbufloader-svg.so: /lib/x86_64-linux-gnu/librsvg-2.so.2: undefined symbol: cairo_tag_end

(ride.py:17800): Gtk-WARNING **: 18:36:29.754: Error loading theme icon 'media-floppy' for stock: Unable to load image-loading module: /usr/lib/x86_64-linux-gnu/gdk-pixbuf-2.0/2.10.0/loaders/libpixbufloader-svg.so: /lib/x86_64-linux-gnu/librsvg-2.so.2: undefined symbol: cairo_tag_end

(ride.py:17800): Gtk-WARNING **: 18:36:29.755: Error loading theme icon 'text-x-generic' for stock: Unable to load image-loading module: /usr/lib/x86_64-linux-gnu/gdk-pixbuf-2.0/2.10.0/loaders/libpixbufloader-svg.so: /lib/x86_64-linux-gnu/librsvg-2.so.2: undefined symbol: cairo_tag_end

(ride.py:17800): Gtk-WARNING **: 18:36:29.788: Error loading theme icon 'system-run' for stock: Unable to load image-loading module: /usr/lib/x86_64-linux-gnu/gdk-pixbuf-2.0/2.10.0/loaders/libpixbufloader-svg.so: /lib/x86_64-linux-gnu/librsvg-2.so.2: undefined symbol: cairo_tag_end

(ride.py:17800): Gtk-WARNING **: 18:36:29.960: Error loading theme icon 'gtk-cancel' for stock: Unable to load image-loading module: /usr/lib/x86_64-linux-gnu/gdk-pixbuf-2.0/2.10.0/loaders/libpixbufloader-svg.so: /lib/x86_64-linux-gnu/librsvg-2.so.2: undefined symbol: cairo_tag_end

(ride.py:17800): Gtk-WARNING **: 18:36:30.040: Error loading theme icon 'go-up' for stock: Unable to load image-loading module: /usr/lib/x86_64-linux-gnu/gdk-pixbuf-2.0/2.10.0/loaders/libpixbufloader-svg.so: /lib/x86_64-linux-gnu/librsvg-2.so.2: undefined symbol: cairo_tag_end

(ride.py:17800): Gtk-WARNING **: 18:36:31.332: Error loading theme icon 'dialog-error' for stock: Unable to load image-loading module: /usr/lib/x86_64-linux-gnu/gdk-pixbuf-2.0/2.10.0/loaders/libpixbufloader-svg.so: /lib/x86_64-linux-gnu/librsvg-2.so.2: undefined symbol: cairo_tag_end

(ride.py:17800): Gtk-WARNING **: 18:36:31.337: Error loading theme icon 'gtk-ok' for stock: Unable to load image-loading module: /usr/lib/x86_64-linux-gnu/gdk-pixbuf-2.0/2.10.0/loaders/libpixbufloader-svg.so: /lib/x86_64-linux-gnu/librsvg-2.so.2: undefined symbol: cairo_tag_end

(ride.py:17800): Gtk-WARNING **: 18:36:31.341: Error loading theme icon 'dialog-error' for stock: Unable to load image-loading module: /usr/lib/x86_64-linux-gnu/gdk-pixbuf-2.0/2.10.0/loaders/libpixbufloader-svg.so: /lib/x86_64-linux-gnu/librsvg-2.so.2: undefined symbol: cairo_tag_end

(ride.py:17800): Gtk-WARNING **: 18:36:31.342: Error loading theme icon 'dialog-warning' for stock: Unable to load image-loading module: /usr/lib/x86_64-linux-gnu/gdk-pixbuf-2.0/2.10.0/loaders/libpixbufloader-svg.so: /lib/x86_64-linux-gnu/librsvg-2.so.2: undefined symbol: cairo_tag_end

(ride.py:17800): Gtk-WARNING **: 18:36:31.344: Error loading theme icon 'dialog-information' for stock: Unable to load image-loading module: /usr/lib/x86_64-linux-gnu/gdk-pixbuf-2.0/2.10.0/loaders/libpixbufloader-svg.so: /lib/x86_64-linux-gnu/librsvg-2.so.2: undefined symbol: cairo_tag_end

(ride.py:17800): Gtk-WARNING **: 18:36:31.347: Error loading theme icon 'edit-copy' for stock: Unable to load image-loading module: /usr/lib/x86_64-linux-gnu/gdk-pixbuf-2.0/2.10.0/loaders/libpixbufloader-svg.so: /lib/x86_64-linux-gnu/librsvg-2.so.2: undefined symbol: cairo_tag_end

(ride.py:17800): Gtk-WARNING **: 18:36:31.349: Error loading theme icon 'document-save' for stock: Unable to load image-loading module: /usr/lib/x86_64-linux-gnu/gdk-pixbuf-2.0/2.10.0/loaders/libpixbufloader-svg.so: /lib/x86_64-linux-gnu/librsvg-2.so.2: undefined symbol: cairo_tag_end

(ride.py:17800): Gtk-WARNING **: 18:36:41.770: Error loading theme icon 'gtk-ok' for stock: Unable to load image-loading module: /usr/lib/x86_64-linux-gnu/gdk-pixbuf-2.0/2.10.0/loaders/libpixbufloader-svg.so: /lib/x86_64-linux-gnu/librsvg-2.so.2: undefined symbol: cairo_tag_end

**Comment by lidanqing123** [comment]
I don't know why so much Error

**Comment by HelioGuilherme66** [comment]
So many errors, because GTK used by wxPython is not finding the icons. There are more errors from GTK, but we do not control them, not even wxPython controls it. This kind of problems is observed in Linux. They do not interfere with RIDE work.

To avoid seeing them, start ride from a Desktop Shortcut.

You should add more info about your system, like:
Linux distribution and version
Graphical manager used, i.e. Gnome (or Gnome Classic), KDE - Plasma, XFCE, ....
wxPython version (and GTK3 or GTK2 build)
