### ISSUE TITLE
[Linux] Tree node settings is hidden after expanding or collapsing

### ISSUE THREAD

**Issue by jnhyperion** [robotframework/RIDE#2235]
![image](https://user-images.githubusercontent.com/20297196/87509641-9120bf00-c6a4-11ea-8e9e-ce134d5dfe14.png)

**Comment by HelioGuilherme66** [comment]
@jnhyperion I have added a new label ThirdParty, to be used in cases like this one because I almost certain it is caused by wxPython version 4.1.

**Comment by HelioGuilherme66** [comment]
Currently on RIDE v2.0.2.dev1 in Fedora Linux 36, Python 3.10.10, wxPython 4.0.7 (KDE Plasma 5 with darkmode, custom colors), this does not happen, but it happens with wxPython 4.1.1 and 4.2.0.
