### ISSUE TITLE
Receiving error while running ride.py

### ISSUE THREAD

**Issue by shweta1087** [robotframework/RIDE#2238]
Received error while running ride.py in cmd.

<class 'robotide.preferences.configobj.UnreprError'> Parse error in value at line 71.
<class 'robotide.preferences.configobj.UnreprError'> Parse error in value at line 13.
Traceback (most recent call last):
  File "c:\program files\python\python38\lib\site-packages\robotide\application\application.py", line 58, in OnInit
    self.frame = RideFrame(self, self._controller)
  File "c:\program files\python\python38\lib\site-packages\robotide\ui\mainframe.py", line 175, in __init__
    self._init_ui()
  File "c:\program files\python\python38\lib\site-packages\robotide\ui\mainframe.py", line 279, in _init_ui
    self.tree = Tree(self, self.actions,
  File "c:\program files\python\python38\lib\site-packages\robotide\ui\tree.py", line 86, in __init__
    self._images = TreeImageList()
  File "c:\program files\python\python38\lib\site-packages\robotide\ui\images.py", line 42, in __init__
    TestCaseController: _TreeImage(self, 'robot.png'),
  File "c:\program files\python\python38\lib\site-packages\robotide\ui\images.py", line 80, in __init__
    self.normal = self._get_image(image_list, normal)
  File "c:\program files\python\python38\lib\site-packages\robotide\ui\images.py", line 91, in _get_image
    img = wx.Image(path, wx.BITMAP_TYPE_PNG).ConvertToBitmap()
wx._core.wxAssertionError: C++ assertion "strcmp(setlocale(LC_ALL, NULL), "C") == 0" failed at ..\..\src\common\intl.cpp(1579) in wxLocale::GetInfo(): You probably called setlocale() directly instead of using wxLocale and now there is a mismatch between C/C++ and Windows locale.
Things are going to break, please only change locale by creating wxLocale objects to avoid this!
OnInit returned false, exiting...
Error in atexit._run_exitfuncs:
wx._core.wxAssertionError: C++ assertion "GetEventHandler() == this" failed at ..\..\src\common\wincmn.cpp(478) in wxWindowBase::~wxWindowBase(): any pushed event handlers must have been removed

C:\WINDOWS\system32>

Current System Configuration:
1) Python 3.8.4
2) Robot Framework 3.2.1 (Python 3.8.4 on win32)
3) WxPython:
C:\WINDOWS\system32>pip show WxPython
Name: wxPython
Version: 4.0.7.post2
Summary: Cross platform GUI toolkit for Python, "Phoenix" version
Home-page: http://wxPython.org/
Author: Robin Dunn
Author-email: robin@alldunn.com
License: wxWindows Library License (https://opensource.org/licenses/wxwindows.php)
Location: c:\program files\python\python38\lib\site-packages
Requires: pillow, numpy, six
Required-by: robotframework-ride

C:\WINDOWS\system32>

4) Robotframework-ride:
C:\WINDOWS\system32>pip show WxPython
Name: wxPython
Version: 4.0.7.post2
Summary: Cross platform GUI toolkit for Python, "Phoenix" version
Home-page: http://wxPython.org/
Author: Robin Dunn
Author-email: robin@alldunn.com
License: wxWindows Library License (https://opensource.org/licenses/wxwindows.php)
Location: c:\program files\python\python38\lib\site-packages
Requires: pillow, numpy, six
Required-by: robotframework-ride

C:\WINDOWS\system32>
![RobotFramework_CMDError](https://user-images.githubusercontent.com/12950471/87675395-f2c05680-c794-11ea-9b0c-396b26f5e5cc.PNG)

Please help.

**Comment by HelioGuilherme66** [comment]
@shweta1087 What is the version of RIDE? How did you installed it?

Did you read the [info](https://github.com/robotframework/RIDE#welcome-to-the-development-version-of-ride---next-release-will-be-version-20) on project page?
