### ISSUE TITLE
Not able to run appium test cases from ride.py 

### ISSUE THREAD

**Issue by anunay1** [robotframework/RIDE#2242]
I get the below error when I am trying to run Appium test cases from ride.py 

command: robot --argumentfile C:\Users\INANTHA3\AppData\Local\Temp\RIDEpdjdedbf.d\argfile.txt --listener C:\Users\INANTHA3\AppData\Local\Programs\Python\Python37\lib\site-packages\robotide\contrib\testrunner\TestRunnerAgent.py:38822:False C:\Users\INANTHA3\AppData\Local\Programs\Python\Python37\Scripts\SampleTests.robot
TestRunnerAgent: Running under CPython 3.7.2

=================================================================================================================================================
SampleTests :: Suite description                                                                                                                 
=================================================================================================================================================

[ WARN ] Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000022C355C5CC0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')': /session

[ WARN ] Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000022C355C5DA0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')': /session

[ WARN ] Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000022C320D80B8>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')': /session
Test title                                                                                                                               | FAIL |
MaxRetryError: HTTPConnectionPool(host='arguments', port=80): Max retries exceeded with url: /session (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000022C355F40F0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))
-------------------------------------------------------------------------------------------------------------------------------------------------
SampleTests :: Suite description                                                                                                         | FAIL |
1 critical test, 0 passed, 1 failed
1 test total, 0 passed, 1 failed
=================================================================================================================================================

[ WARN ] Keyword 'Capture Page Screenshot' could not be run on failure: No application is open
Output:  C:\Users\INANTHA3\AppData\Local\Temp\RIDEpdjdedbf.d\output.xml
Log:     C:\Users\INANTHA3\AppData\Local\Temp\RIDEpdjdedbf.d\log.html
Report:  C:\Users\INANTHA3\AppData\Local\Temp\RIDEpdjdedbf.d\report.html

test finished 20200720 00:49:37

Starting test: SampleTests.Test title
20200720 00:49:30.282 :  WARN : Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000022C355C5CC0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')': /session
20200720 00:49:32.544 :  WARN : Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000022C355C5DA0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')': /session
20200720 00:49:34.810 :  WARN : Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000022C320D80B8>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')': /session
20200720 00:49:37.105 :  FAIL : No application is open
20200720 00:49:37.116 :  WARN : Keyword 'Capture Page Screenshot' could not be run on failure: No application is open
20200720 00:49:37.135 :  FAIL : MaxRetryError: HTTPConnectionPool(host='arguments', port=80): Max retries exceeded with url: /session (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000022C355F40F0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))
Ending test:   SampleTests.Test title

The same issue is observed when I use pycharm also. I have started the appium server at 127.0.0.1:4723

**Comment by HelioGuilherme66** [comment]
@anunay1 You say the problem also happens with PyCharm:
> The same issue is observed when I use pycharm also. I have started the appium server at 127.0.0.1:4723

Did you, also opened an Issue in PyCharm issue tracker? (I hope not).

You probably would have the same problem when running from command window, so probably there is some problem with you setup.

**Comment by anunay1** [comment]
That is what I am not able to figure out what is the problem with my setup.

**Comment by HelioGuilherme66** [comment]
You, will need to use other ways to figure that out. This is an Issue tracker to report problems or improvements.
