### ISSUE TITLE
Not able to install appium library with RIDE,

### ISSUE THREAD

**Issue by Gaurav21git** [robotframework/RIDE#2244]
Hi team,

I am using Python 2.7 but while installing Appium Library with the help of command: pip install robotframework-appiumlibrary, I am getting below error, Could you please suuport to resolve this issue. 

![image](https://user-images.githubusercontent.com/43947717/87911704-affac900-ca89-11ea-80d3-d9892479cf90.png)

And also, could you please let me know, Version compatibility between RIDE & Appium Library.

**Comment by HelioGuilherme66** [comment]
That looks like a Python 3 type hint.
RIDE should be seen as an Editor of test suites. There is no problems of compatibility with Libraries.

**Comment by Gaurav21git** [comment]
It is mentioned in the GitHub RobotFramework forum that Appium Libraries are compatible with Python 2.7 but I am getting error while trying to install it. 
GitHub:
![image](https://user-images.githubusercontent.com/43947717/88047820-d7c45c80-cb6f-11ea-93bb-fbe56c048c78.png)

Error Log
Collecting robotframework-appiumlibrary
  Using cached https://files.pythonhosted.org/packages/c1/94/52425cffd920a6938b4b923477e9120886b50aa023097671efc7d38306da/robotframework_appiumlibrary-1.5.0.6-py2.py3-none-any.whl
Collecting Appium-Python-Client>=0.28 (from robotframework-appiumlibrary)
  Using cached https://files.pythonhosted.org/packages/21/ca/3261b5da5b6851ea5297f44b2dc7f3167f00a7ce3e99907b49bf69c56360/Appium-Python-Client-1.0.2.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "c:\users\a1029532\appdata\local\temp\pip-build-znkxs_\Appium-Python-Client\setup.py", line 19, in <module>
        from appium.common.helper import library_version
      File "appium\common\helper.py", line 20
        def extract_const_attributes(cls: type) -> Dict[str, Any]:
                                        ^
    SyntaxError: invalid syntax

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in c:\users\a1029532\appdata\local\temp\pip-build-znkxs_\Appium-Python-Client\

This is a issue in RobotFramework, please provide some better solution.

**Comment by HelioGuilherme66** [comment]
If you look carefully, you will see that you are installed a cached version of the library. Use --force option to get the correct package.

**Comment by Gaurav21git** [comment]
As you suggested, I tried same with command - a.	pip install robotframework-appiumlibrary --force, but still getting same error. I had tried with different version of Python, 2.7, 3.0, 3.0.1, 3.2.3, 3.8.4, 3.8 but no one seems to be compatible with RobotFramework Appium Libraries. 
Please provide support which version is compatible for AppiumLibraries


![image](https://user-images.githubusercontent.com/43947717/88185035-10883280-cc51-11ea-93d3-206ea7c2d22c.png)

**Comment by HelioGuilherme66** [comment]
Sorry, you are making some errors. You can see in your output you are still using cached values.
This is because the correct command is `pip install -U --force robotframework-appiumlibrary`.

No need for more comments on this issue.

**Comment by Gaurav21git** [comment]
Hi, I have tried with the same command that you mentioned but the error remains same. I am posting it just to expect some support from RobotFramework team. For reference,

![image](https://user-images.githubusercontent.com/43947717/88367166-b601ea00-cda8-11ea-96f4-02c11898769a.png)

**Comment by HelioGuilherme66** [comment]
That problem is a Python 3 related. You should install Python 3 and the rest of Appium libraries for it.

**Comment by ashett13** [comment]
If you are using python 2.7
Install below version
pip install Appium-Python-Client==0.52
pip install robotframework-appiumlibrary==1.6
