### ISSUE TITLE
Ride is not working with Python 3.8.4

### ISSUE THREAD

**Issue by Gaurav21git** [robotframework/RIDE#2245]
Hi Team,

I am working on Mobile Automation with Appium through Robot Framework, I had installed:
Appium-Python-Client==1.0.2
decorator==4.4.2
docutils==0.16
kitchen==1.2.6
numpy==1.19.0
Pillow==7.2.0
Pygments==2.6.1
Pypubsub==4.0.3
pywin32==228
robotframework==3.2.1
robotframework-appiumlibrary==1.5.0.6
robotframework-ride==1.7.4.2
robotframework-seleniumlibrary==4.4.0
selenium==3.141.0
six==1.15.0
urllib3==1.25.9
wxPython==4.0.7.post2
Python == 3.8.4

But when i tried to launch RIDE through command prompt, I am getting an error

![image](https://user-images.githubusercontent.com/43947717/88030653-2286aa00-cb59-11ea-956f-acebc0de1024.png)

Could you please provide support to overcome this issue.

**Comment by HelioGuilherme66** [comment]
Yes, we know that version is not compatible.
Try the new Beta version.

**Comment by Gaurav21git** [comment]
Can you please provide the Appium Library & Python version which are compatible with RIDE. I had already tried

Python 2.7.15
Python 3.0.1
Python 3.2.3

With above version, when i tried to install Appium Library it throws exception:



Collecting robotframework-appiumlibrary
  Using cached https://files.pythonhosted.org/packages/c1/94/52425cffd920a6938b4b923477e9120886b50aa023097671efc7d38306da/robotframework_appiumlibrary-1.5.0.6-py2.py3-none-any.whl
Collecting Appium-Python-Client>=0.28 (from robotframework-appiumlibrary)
  Using cached https://files.pythonhosted.org/packages/21/ca/3261b5da5b6851ea5297f44b2dc7f3167f00a7ce3e99907b49bf69c56360/Appium-Python-Client-1.0.2.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "c:\users\a1029532\appdata\local\temp\pip-build-znkxs_\Appium-Python-Client\setup.py", line 19, in <module>
        from appium.common.helper import library_version
      File "appium\common\helper.py", line 20
        def extract_const_attributes(cls: type) -> Dict[str, Any]:
                                        ^
    SyntaxError: invalid syntax

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in c:\users\a1029532\appdata\local\temp\pip-build-znkxs_\Appium-Python-Client\


Thanks,

**Comment by HelioGuilherme66** [comment]
You may have better luck using other forums. Here is supposed to be a place to report problems.

Your Python versions are too old. Better try with Python >= 3.6.
