### ISSUE TITLE
Documentation cannot display with multi-line format in Settings

### ISSUE THREAD

**Issue by jnhyperion** [robotframework/RIDE#2258]
<img width="824" alt="image" src="https://user-images.githubusercontent.com/20297196/88625172-d39dbf00-d0da-11ea-9ef6-b818d1aad293.png">

**Comment by Nyral** [comment]
It can, but you need a line empty between them.

**Comment by jnhyperion** [comment]
> It can, but you need an empty line between them. See https://robotframework.org/robotframework/latest/RobotFrameworkUserGuide.html#newlines-in-test-data
> What we actually need is a custom built RichTextCtrl for FR documentation format.

Documentation text ctrl is instance of HtmlWindow.
`
@property
def visible_value(self):
       return utils.html_format(utils.unescape(self.value))
`
it's using robotframework library html format method, looks like this method fails to format plain text '\n' to html tag '<br>'

**Comment by jnhyperion** [comment]
I found the correct usage:

<img width="717" alt="image" src="https://user-images.githubusercontent.com/20297196/89150717-c593e680-d591-11ea-9c35-9185bef5f896.png">

so it actually supported. close this issue.
