### ISSUE TITLE
Deleting a line in a test causes it to split in two if you save from text editor

### ISSUE THREAD

**Issue by Nyral** [robotframework/RIDE#2263]
I recorded the scenario, so it's easier to understand.

![ezgif-6-6f009a1c5ab3](https://user-images.githubusercontent.com/39315668/89184240-270f8180-d5a1-11ea-80f7-92be12086939.gif)

More details:
- Go to a test case and ensure one line is empty (either by deleting its contents or inserting a new one)
- Without saving go to text editor and change something (won't work without this)
- Apply changes, either by using button from text editor or Save button from toolbar

**Comment by HelioGuilherme66** [comment]
Did you used Ctrl-D to delete the line?

**Comment by Nyral** [comment]
@HelioGuilherme66 Ctrl-D would have removed it entirely. I used the Delete key.

**Comment by HelioGuilherme66** [comment]
Closing Issue as fixed.
Currently on RIDE v2.0.2.dev1 in Fedora Linux 36, Python 3.10.10, wxPython 4.0.7 (KDE Plasma 5 with darkmode, custom colors).
