### ISSUE TITLE
Grid View setting is not visible on Windows 10

### ISSUE THREAD

**Issue by bhajojo** [robotframework/RIDE#2266]
Not able to See Grid View Setting on Windows 10

Logs in ride
20200808 22:33:25.649 [INFO]: Found Robot Framework version 3.1.2 from C:\Users\xxxxxxx\AppData\Local\Programs\Python\Python37\lib\site-packages\robot.

20200808 22:33:25.650 [INFO]: Started RIDE 1.7.4.2 using python version 3.7.3 with wx version 4.0.6 in win32.

**Comment by HelioGuilherme66** [comment]
Please try with current Beta version. You should also upgrade wxPython to 4.0.7.post2.

**Comment by bhajojo** [comment]
Still not working

20200808 22:51:15.332 [INFO]: Found Robot Framework version 3.2.1 from C:\Users\xxxxxx\AppData\Local\Programs\Python\Python37\lib\site-packages\robot.

20200808 22:51:15.334 [INFO]: Started RIDE v2.0b1 using python version 3.7.3 with wx version 4.0.7.post2 in win32.

**Comment by HelioGuilherme66** [comment]
Can you please add a screenshot. I am having a difficulty in understanding your problem.

**Comment by bhajojo** [comment]
Please find the screenshot : 

On selecting Grid Editor 
![image](https://user-images.githubusercontent.com/7836709/89728927-93313000-da4e-11ea-9434-d2710f02f71e.png)

**Comment by HelioGuilherme66** [comment]
@bhajojo Thank you for the screenshot. I still cannot figure out what is going on. I suggest some experiments:

- This Python installation on C:\Users\xxxxxx\AppData\Local\Programs\Python\Python37\ may be impacted by the user name.
   Try to install latest python 3.7 on a simpler path, for example C:\Python37, then RIDE and needed libraries.
- Run RIDE from command window with `python -m robotide.__init__`  . This way there may appear wxPython error messages.

The type of problem looks more related with wxPython, than with RIDE itself.

**Comment by bhajojo** [comment]
1 . Installing Python 37 in C/Python  folder has resolved the issue
