### ISSUE TITLE
Cursor will always move to the end of new line if pressing enter in Text Editor

### ISSUE THREAD

**Issue by jnhyperion** [robotframework/RIDE#2271]
1. put cursor in one line of Text Editor
2. press enter to start new line
3. the cursor is expected to be in the head of new line, like other text editor
4. actually it's always in the end of new line

**Comment by HelioGuilherme66** [comment]
I think that it is working as expected.
If you type a new line after a section (***), it goes to start. If after a Test Case or Keyword, then it auto-idents.

Even if you type empty newlines, and it auto-indents, they will be removed before saving or clicking Apply changes.
