### ISSUE TITLE
I want to use event_firing_webdriver when import SeleniumLibrary， an error has occurred in RIDE

### ISSUE THREAD

**Issue by lijiahao10086** [robotframework/RIDE#2274]
when I choose .py file ,

*** Settings ***
Library           SeleniumLibrary    event_firing_webdriver=${CURDIR}/MyListener.py

**error log:**

Traceback (most recent call last):
Initializing test library 'SeleniumLibrary' with arguments [ event_firing_webdriver=./MyListener.py ] failed: DataError: Importing test library './MyListener.py' failed: ImportError: Import by filename is not supported.
Traceback (most recent call last):
None

Version information：
Package Version

bcrypt 3.1.7
cffi 1.14.1
cryptography 3.0
enum34 1.1.10
ipaddress 1.0.23
numpy 1.16.6
paramiko 2.7.1
Pillow 6.2.2
pip 20.2.1
pycparser 2.20
Pygments 2.5.2
PyNaCl 1.4.0
PyPubSub 3.3.0
pywin32 228
robotframework 3.1.2
robotframework-pythonlibcore 2.1.0
robotframework-ride 1.7.4.2
robotframework-seleniumlibrary 4.5.0
robotframework-sshlibrary 3.4.0
scp 0.13.2
selenium 3.141.0
setuptools 41.2.0
six 1.15.0
urllib3 1.25.10
win-inet-pton 1.1.0
wxPython 4.0.7.post2

But,I run it by the command line，it works

**Comment by HelioGuilherme66** [comment]
@lijiahao10086 If you are using RIDE in Python 3, then you can install current Beta and see if the error still happens.
If not using Python 3, and if Run executes the Test OK just like from command line, then just ignore the error.

**Comment by lijiahao10086** [comment]
I using py2.7，It will cause the library import to fail，I can‘t use SeleniumLibrary in RIDE

**Comment by HelioGuilherme66** [comment]
Yes, it will fail. But you can still Run the test case.

Note: this issue was originally opened in [SeleniumLibrary project.](https://github.com/robotframework/SeleniumLibrary/issues/1622)

**Comment by lijiahao10086** [comment]
ok~Thank you very much for your reply. It's my pleasure，hhhhh

**Comment by jnhyperion** [comment]
I confirmed this is a bug:

The library import result displayed in UI is always fail in this case, actually, the library is already imported successfully.

**Comment by jnhyperion** [comment]
duplicated with: https://github.com/robotframework/RIDE/issues/1417
