### ISSUE TITLE
Fix Del key on MacOS Cell Edit.

### ISSUE THREAD

**Issue by HelioGuilherme66** [robotframework/RIDE#2299]
On Grid Editor, write some text in a cell (ignore the beeps ;) )
Then select text or move cursor to have text on right, and press Del. The whole cell content was being cleared, after a fix the Del is not being detected.

(Note: Not  sure when stopped working)

**Comment by jnhyperion** [comment]
Press cmd + delete on a cell will not work, right?

**Comment by HelioGuilherme66** [comment]
No. Just plain Delete (not Backspace). I don't even know what Cmd+Delete would do. And Delete is working when not editing the cell.

**Comment by jnhyperion** [comment]
My MacBook only have a delete button, in RIDE, it works as Backspace button, I remembered Cmd + delete worked as delete the cell, but now it's also not working.

**Comment by jnhyperion** [comment]
The correct behaviour should be:

Press `delete` -> delete the cell

there's no `Backspace` button on Mac.

For now, pressing `delete`, it works as windows `Backspace`.

**Comment by HelioGuilherme66** [comment]
Closing Issue as fixed.
Currently on RIDE v2.0.2.dev1 in Fedora Linux 36, Python 3.10.10, wxPython 4.0.7 (KDE Plasma 5 with darkmode, custom colors).
