### ISSUE TITLE
Ride Shortcut keys 'Alt-Space' in Grid in conflict with Windows system Shortcut keys

### ISSUE THREAD

**Issue by Jessie-sunny** [robotframework/RIDE#2301]
1.Using shortcut keys 'Alt-Space' in  Windows ride grid.
2. The systems window will be trigered.
![image](https://user-images.githubusercontent.com/70616681/91925003-b4600600-ed06-11ea-8bec-a189174fa398.png)

**Comment by HelioGuilherme66** [comment]
Don't use Alt+Space on Windows, use Ctrl-Space.

**Comment by Nyral** [comment]
PR #2260 Might have indirectly fixed this issue too. Please retest.

**Comment by Jessie-sunny** [comment]
@Nyral , I download the lastest master code, the issue still reproduced. My system is Windows10.

**Comment by HelioGuilherme66** [comment]
@Jessie-sunny It will be fixed only after Nyral PR  being merged to master. Just wait some more time.

**Comment by HelioGuilherme66** [comment]
Moving to 2.1 because of lack of resources (time and people)

**Comment by HelioGuilherme66** [comment]
This cannot be handled by RIDE. Users should use Ctrl-Space in Windows, or Alt-Space in systems that allows it (maybe only in Linux). Mac users should use Command-Space.
In some situations users, can try to use Ctrl-Alt-Space to have the action.
