### ISSUE TITLE
Grid issues with 'FOR' loop statements

### ISSUE THREAD

**Issue by jnhyperion** [robotframework/RIDE#2302]
1. incorrect lower case 'for, end' is recognized as keywords
2. in for loop statement, update 'for' to upper case but cannot save changes
3. when correct the for to upper case, the statement is still in red

**Comment by HelioGuilherme66** [comment]
This is still present in RIDE v2.0.2.dev1 in Fedora Linux 36, Python 3.10.10, wxPython 4.0.7 (KDE Plasma 5 with darkmode, custom colors).
