### ISSUE TITLE
I set the font color, size, and style, and I restored the default values each time I ran the test case.

### ISSUE THREAD

**Issue by numbpeople** [robotframework/RIDE#2303]
I use python3.8 and ride v2.0b1 on my MAC. I set the font color, size, and style in the Gird Editor, and I restore the default values each time I run the test case.

**Comment by jnhyperion** [comment]
Do you mean your configurations in `Grid Editor` settings is not saved after restarting?

**Comment by numbpeople** [comment]
@jnhyperion yes。I set the font color by right-clicking on font>show styles in edit, but every time I run the test case, I edit the font color to restore the default white.

**Comment by numbpeople** [comment]
@jnhyperion 
![image](https://user-images.githubusercontent.com/45647907/91945384-775d3900-ed31-11ea-813f-98d7c5042d85.png)
每次编辑时我都需要重新设置下字体颜色。

**Comment by jnhyperion** [comment]
it's not RIDE's feature, it's Apple's default App font setting feature.

If you want to change font and colors, please go to `Tools -> Preferences -> Grid Editor`.

**Comment by jnhyperion** [comment]
Or you can remove the settings cache:  `rm ~/.robotframework/ride/settings.cfg` and restart RIDE.

**Comment by numbpeople** [comment]
@jnhyperion 
![image](https://user-images.githubusercontent.com/45647907/91956472-47189900-ed37-11ea-9c0b-cbbed7b83944.png)
I set the font like this.

**Comment by jnhyperion** [comment]
@numbpeople  this may change your system font, and I guess your probably changed your system font default colors by mistake. Try to use another font in grid settings.
