### ISSUE TITLE
search in text edit doesnt work

### ISSUE THREAD

**Issue by elschman** [robotframework/RIDE#2307]
text search doesnt work cos the return value of FindText is a tuple not single int.
PR #2306

**Comment by HelioGuilherme66** [comment]
This was never observed before. If you do Ctrl-F then go to text input field to search text. If you select some text and press Ctrl-G will search again with that text.

**Comment by jnhyperion** [comment]
confirmed, this issue only happens in wxPython 4.1.0

stc.StyledTextCtrl.FindText return type is changed from `int` -> `tuple(int, int)`.

@HelioGuilherme66 maybe we should lock wxPython version to 4.1.0 to avoid potential compatibility issues.

**Comment by elschman** [comment]
I wouldnt do so... better not to fix as we saw in the past often chenging wxPython versions... Better check if there is a tuple returned and decide based on this ... as done here

**Comment by elschman** [comment]
and why the bug label is removed.. for 2.0 this is a bug!

**Comment by jnhyperion** [comment]
Because the root cause is wxPython dependent, we're using label `ThirdParty` to mark this kind of issues.
