### ISSUE TITLE
search a new text doesnt work...

### ISSUE THREAD

**Issue by elschman** [robotframework/RIDE#2308]
always the first text will be searched and replaced in search text window.

**Comment by HelioGuilherme66** [comment]
Please detail the steps you do, because I do not understand the problem.

**Comment by ImmoWetzel** [comment]
the keyboard shortcuts are fine but if you enter a new search string into the _search_field and click on search again... it should search the new string ... but jumps back to the old one. cos the old search result is still the selected one...

provided PR #2309

**Comment by jnhyperion** [comment]
confirmed, it's a bug
