### ISSUE TITLE
ride robot framework

### ISSUE THREAD

**Issue by emmaisong** [robotframework/RIDE#2315]
Hi,
   My "RIDE" robot framework quits each time I try to launch it. what could be the problem?

**Comment by HelioGuilherme66** [comment]
@emmaisong I have no clue of what is the problem.

But this Issue tracker is to report problems. You have a problem, and you are the only person who knows what system and versions you use. And what steps did you take until the problem started.

If you wanted to have more immediate help to solve your problem, you should have used another communication channel, like we list on our README project page.
