### ISSUE TITLE
Double click RIDE destop shortcut icon popup a error window when RIDE already opened.

### ISSUE THREAD

**Issue by Jessie-sunny** [robotframework/RIDE#2319]
1. Open Ride by command line 'ride.py'
2. Double click Ride destop shortcut icon popup a error window ,then Ride opend again.
3. One project will be opend in two Ride.

![image](https://user-images.githubusercontent.com/70616681/93318064-ced6cb00-f840-11ea-8545-320e8ebf4c5e.png)

**Comment by HelioGuilherme66** [comment]
@Jessie-sunny It would helped if you reported the Operating System, RIDE and Python versions.
We will assume it is Windows, by the looks of the dialog.

**Comment by jnhyperion** [comment]
should be resolved by PR: https://github.com/robotframework/RIDE/pull/2323
