### ISSUE TITLE
the  status message won't fit into the screen 

### ISSUE THREAD

**Issue by povar81** [robotframework/RIDE#2320]
the fail/pass status message won't fit into the screen like it used to, so I have to scroll right to see it.
https://slack-files.com/T07PJQ9S7-F019S1E10NR-f981f78485
https://slack-files.com/T07PJQ9S7-F019S1EK6PP-5454210818

RIDE v2.0b1 running on Python 3.7.4. 
OS: windows10

**Comment by HelioGuilherme66** [comment]
Check option:
```
 -W --consolewidth chars  Width of the console output. Default is 78.
```
