### ISSUE TITLE
RIDE not able to perform Excel write operation.

### ISSUE THREAD

**Issue by pkhot5** [robotframework/RIDE#2333]
Hello,

We currently have installed Python27 and wxPython 4.0.7.post2, using that and PIP we have robotframework running on v3.1.2 and robotframework-RIDE running on v1.7.4.2

We also have a excel and openpyxl lib installed for Excel read and write operations. Again we are not able to perform write operations in our Excel file. We are able to create Excel file but no write operations can be performed. We were able to achieve this in older versions of RIDE. So here's our concern, what version of Excel is RIDE able to read and write? We are using Excel for Office 365(32-bit).

**Comment by pkhot5** [comment]
Is there any way we can address or get help on this issue? We have seen you have other communication channel, README project page. Where can I find this README project page?

**Comment by HelioGuilherme66** [comment]
> Is there any way we can address or get help on this issue? We have seen you have other communication channel, README project page. Where can I find this README project page?

In the main page of this project, [Code](https://github.com/robotframework/RIDE) link. Look for Slack.
