### ISSUE TITLE
RIDE keywords disappear or get deleted after first run. 

### ISSUE THREAD

**Issue by pkhot5** [robotframework/RIDE#2334]
Hello,

We currently have installed Python27 and wxPython 4.0.7.post2, using that and PIP we have robotframework running on v3.1.2 and robotframework-RIDE running on v1.7.4.2

Glitch we've noticed in the current installed version of RIDE(v1.7.4.2) is after we try, edit and run our testcases, they run perfectly fine(whatever maybe the output) but for the second run if we have to make any changes in keyword or in code then our keywords are nowhere to be seen. Keywords tree gets completely blank and all our previously set keywords get deleted. My only solution to this problem is close and reopen RIDE and it gets to a point where we have to keep this process repeating even for a minor change. How do I correct or get past this glitch? It doesn't used to happen when we had previous versions of RIDE.

**Comment by HelioGuilherme66** [comment]
@pkhot5 Please retest on new version 2.0b2.

**Comment by HelioGuilherme66** [comment]
Closing because of no response from author.
