### ISSUE TITLE
Editor is not visible

### ISSUE THREAD

**Issue by bakobela** [robotframework/RIDE#2335]
I installed the Ride version 1.7.4.2 with the following packages on my Mac but the editor window is empty. I can edit the tests only in text mode.

Installed packages:

Python version: 3.8.6

Package                                           Version
------------------------------------------------- -----------
certifi                                           2020.6.20
chardet                                           3.0.4
idna                                              2.10
keyboard                                          0.13.5
numpy                                             1.19.4
Pillow                                            8.0.1
pip                                               20.2.1
Pygments                                          2.7.2
pynput                                            1.7.1
pyobjc                                            6.2.2
pyobjc-core                                       6.2.2
pyobjc-framework-Accounts                         6.2.2
pyobjc-framework-AddressBook                      6.2.2
pyobjc-framework-AdSupport                        6.2.2
pyobjc-framework-AppleScriptKit                   6.2.2
pyobjc-framework-AppleScriptObjC                  6.2.2
pyobjc-framework-ApplicationServices              6.2.2
pyobjc-framework-AuthenticationServices           6.2.2
pyobjc-framework-AutomaticAssessmentConfiguration 6.2.2
pyobjc-framework-Automator                        6.2.2
pyobjc-framework-AVFoundation                     6.2.2
pyobjc-framework-AVKit                            6.2.2
pyobjc-framework-BusinessChat                     6.2.2
pyobjc-framework-CalendarStore                    6.2.2
pyobjc-framework-CFNetwork                        6.2.2
pyobjc-framework-CloudKit                         6.2.2
pyobjc-framework-Cocoa                            6.2.2
pyobjc-framework-Collaboration                    6.2.2
pyobjc-framework-ColorSync                        6.2.2
pyobjc-framework-Contacts                         6.2.2
pyobjc-framework-ContactsUI                       6.2.2
pyobjc-framework-CoreAudio                        6.2.2
pyobjc-framework-CoreAudioKit                     6.2.2
pyobjc-framework-CoreBluetooth                    6.2.2
pyobjc-framework-CoreData                         6.2.2
pyobjc-framework-CoreHaptics                      6.2.2
pyobjc-framework-CoreLocation                     6.2.2
pyobjc-framework-CoreMedia                        6.2.2
pyobjc-framework-CoreMediaIO                      6.2.2
pyobjc-framework-CoreML                           6.2.2
pyobjc-framework-CoreMotion                       6.2.2
pyobjc-framework-CoreServices                     6.2.2
pyobjc-framework-CoreSpotlight                    6.2.2
pyobjc-framework-CoreText                         6.2.2
pyobjc-framework-CoreWLAN                         6.2.2
pyobjc-framework-CryptoTokenKit                   6.2.2
pyobjc-framework-DeviceCheck                      6.2.2
pyobjc-framework-DictionaryServices               6.2.2
pyobjc-framework-DiscRecording                    6.2.2
pyobjc-framework-DiscRecordingUI                  6.2.2
pyobjc-framework-DiskArbitration                  6.2.2
pyobjc-framework-DVDPlayback                      6.2.2
pyobjc-framework-EventKit                         6.2.2
pyobjc-framework-ExceptionHandling                6.2.2
pyobjc-framework-ExecutionPolicy                  6.2.2
pyobjc-framework-ExternalAccessory                6.2.2
pyobjc-framework-FileProvider                     6.2.2
pyobjc-framework-FileProviderUI                   6.2.2
pyobjc-framework-FinderSync                       6.2.2
pyobjc-framework-FSEvents                         6.2.2
pyobjc-framework-GameCenter                       6.2.2
pyobjc-framework-GameController                   6.2.2
pyobjc-framework-GameKit                          6.2.2
pyobjc-framework-GameplayKit                      6.2.2
pyobjc-framework-ImageCaptureCore                 6.2.2
pyobjc-framework-IMServicePlugIn                  6.2.2
pyobjc-framework-InputMethodKit                   6.2.2
pyobjc-framework-InstallerPlugins                 6.2.2
pyobjc-framework-InstantMessage                   6.2.2
pyobjc-framework-Intents                          6.2.2
pyobjc-framework-IOSurface                        6.2.2
pyobjc-framework-iTunesLibrary                    6.2.2
pyobjc-framework-LatentSemanticMapping            6.2.2
pyobjc-framework-LaunchServices                   6.2.2
pyobjc-framework-libdispatch                      6.2.2
pyobjc-framework-LinkPresentation                 6.2.2
pyobjc-framework-LocalAuthentication              6.2.2
pyobjc-framework-MapKit                           6.2.2
pyobjc-framework-MediaAccessibility               6.2.2
pyobjc-framework-MediaLibrary                     6.2.2
pyobjc-framework-MediaPlayer                      6.2.2
pyobjc-framework-MediaToolbox                     6.2.2
pyobjc-framework-Metal                            6.2.2
pyobjc-framework-MetalKit                         6.2.2
pyobjc-framework-ModelIO                          6.2.2
pyobjc-framework-MultipeerConnectivity            6.2.2
pyobjc-framework-NaturalLanguage                  6.2.2
pyobjc-framework-NetFS                            6.2.2
pyobjc-framework-Network                          6.2.2
pyobjc-framework-NetworkExtension                 6.2.2
pyobjc-framework-NotificationCenter               6.2.2
pyobjc-framework-OpenDirectory                    6.2.2
pyobjc-framework-OSAKit                           6.2.2
pyobjc-framework-OSLog                            6.2.2
pyobjc-framework-PencilKit                        6.2.2
pyobjc-framework-Photos                           6.2.2
pyobjc-framework-PhotosUI                         6.2.2
pyobjc-framework-PreferencePanes                  6.2.2
pyobjc-framework-PushKit                          6.2.2
pyobjc-framework-Quartz                           6.2.2
pyobjc-framework-QuickLookThumbnailing            6.2.2
pyobjc-framework-SafariServices                   6.2.2
pyobjc-framework-SceneKit                         6.2.2
pyobjc-framework-ScreenSaver                      6.2.2
pyobjc-framework-ScriptingBridge                  6.2.2
pyobjc-framework-SearchKit                        6.2.2
pyobjc-framework-Security                         6.2.2
pyobjc-framework-SecurityFoundation               6.2.2
pyobjc-framework-SecurityInterface                6.2.2
pyobjc-framework-ServiceManagement                6.2.2
pyobjc-framework-Social                           6.2.2
pyobjc-framework-SoundAnalysis                    6.2.2
pyobjc-framework-Speech                           6.2.2
pyobjc-framework-SpriteKit                        6.2.2
pyobjc-framework-StoreKit                         6.2.2
pyobjc-framework-SyncServices                     6.2.2
pyobjc-framework-SystemConfiguration              6.2.2
pyobjc-framework-SystemExtensions                 6.2.2
pyobjc-framework-UserNotifications                6.2.2
pyobjc-framework-VideoSubscriberAccount           6.2.2
pyobjc-framework-VideoToolbox                     6.2.2
pyobjc-framework-Vision                           6.2.2
pyobjc-framework-WebKit                           6.2.2
Pypubsub                                          4.0.3
requests                                          2.24.0
robotframework                                    3.2.2
robotframework-pythonlibcore                      2.1.0
robotframework-requests                           0.7.1
robotframework-ride                               1.7.4.2
robotframework-seleniumlibrary                    4.5.0
selenium                                          3.141.0
setuptools                                        49.2.1
six                                               1.15.0
urllib3                                           1.25.11
wxPython                                          4.0.7.post2

**Comment by HelioGuilherme66** [comment]
We know that version 1.7.4.2 is not compatible with Python 3.8.
You should install the pre-release or development version like we suggest on the [README](https://github.com/robotframework/RIDE).
