### ISSUE TITLE
Cannot run tests in version 2.0b1

### ISSUE THREAD

**Issue by Tom-de-tester** [robotframework/RIDE#2338]
Hi,
I installed ride version 2.0b1 because I had issues with the selenium library in the mainstream version. It did not recognize the keyword open browser. So I read on the robot framework that a posibility to solving that issue was upgrading to 2.0b1.
So I did how ever restarting the workbench helped to solve my selenium issue, however it created a new issue that is, I am not able to run tests. Not using keyboard shortcuts nor via the absent icons.

I am running RIDE on a virtual windows 10 instance using parallels (version 16). The windows version is 10.(buildnumber: 19041.572) using a 32bit instance of python version 3.7.9
my previous version of ride was: 1.7.4.2

![missing buttons](https://user-images.githubusercontent.com/12008332/99093480-d1e90000-25d2-11eb-9a60-7e33141ae83d.PNG)

**Comment by Tom-de-tester** [comment]
When I start Ride I get the message:
Importin plugin module c:\Phyton37\lib\site-packages\robotide\contrib\testrunner\testrunnerplugin.py failed: No module named 'psutil'

**Comment by HelioGuilherme66** [comment]
Yes, that is a known problem.
You can fix it by installing PsUtil:
`pip install psutil` 

Or by installing current development version, future Beta2, look at README on the Code tab of this project.
(I really need to release a Beta2, but wanted to include more nice stuff ;) )

**Comment by Tom-de-tester** [comment]
Thanx

Met vriendelijke groet,

Tom Langerhorst
SQA-consultant @ L-TAD

E: mail@tomdetester.nl
T:+31618812123
S: @tomdetester

Deze mail is verzonden van mijn telefoon, hierdoor kunnen er onbedoelde spelfouten in het bericht voor komen.

**Comment by rbradhika530** [comment]
<img width="1674" alt="image" src="https://user-images.githubusercontent.com/103515571/165830754-1d5d440c-9367-412a-a25b-5e04f7477466.png">
How to make Test suit visible with this version of ride in python 3.9

**Comment by rbradhika530** [comment]
@HelioGuilherme66 Please help here

**Comment by HelioGuilherme66** [comment]
@rbradhika530 Please don't comment on closed issues, and use different channels for support (see README).

The text is white and the same color of the background. This is fixed in current development version.

**Comment by rbradhika530** [comment]
@HelioGuilherme66 sure will open new issue, can you please share that development version or link?

**Comment by HelioGuilherme66** [comment]
@rbradhika530 See this FAQ answer: https://github.com/robotframework/RIDE/wiki/F.A.Q.#13--q-i-have-installed-the-development-version-v20b2dev5-but-it-is-broken-how-can-i-revert-to-a-previous-version
