### ISSUE TITLE
Python library with keyword only arguments fails to load

### ISSUE THREAD

**Issue by JFoederer** [robotframework/RIDE#2342]
Both Python and Robot framework have had updates to support named arguments, but when such a library is loaded in RIDE it fails. More specifically it fails when any of the named arguments also includes a default value.

Take for instance this basic example
`def kw(self, *, arg1=None):`

Which results in this error in the RIDE log:
`Traceback (most recent call last):
list index out of range
  File "C:\Python37\lib\site-packages\robotide\spec\librarymanager.py", line 87, in _fetch_keywords
    return get_import_result(path, library_args)
  File "C:\Python37\lib\site-packages\robotide\spec\libraryfetcher.py", line 29, in get_import_result
    ) for kw in lib.handlers]
  File "C:\Python37\lib\site-packages\robotide\spec\libraryfetcher.py", line 29, in <listcomp>
    ) for kw in lib.handlers]
  File "C:\Python37\lib\site-packages\robotide\spec\libraryfetcher.py", line 40, in _parse_args
    parsed[index] = parsed[index] + '=' + str(args.defaults[value])  # DEBUG str(value)`

**Comment by HelioGuilherme66** [comment]
@JFoederer Thank you for the report and PR.

I would like to know what version of RIDE you are using: released==1.7.4.2 Beta==2.0b1 or from `master` (I assume this is the one). Also the version installed of Robot Framework (RIDE uses internally, the 3.1.2 and some code is copied from it).

About the problem. You say:

> Take for instance this basic example
> ```def kw(self, *, arg1=None):```

I believe that this is invalid code for Robot Framework standards, because the varargs should come in last position.
So the code should be (but I did not confirmed):
```def kw(self, arg1=None, *):```

Did you find an example library with your case?
Thanks.

**Comment by JFoederer** [comment]
Hi @HelioGuilherme66,

Thank you for the quick response. After running into the issue I have first upgraded to 2.0b1 and I have taken the current master as a base for my changes. My installed Robot framework version is 3.2.2 on a Windows machine.

The example was encountered in a proprietary library at a client's site. I first suspected the library, but checking against the Robot documentation revealed that the implementation was actually correct, supported and had a purpose.
https://robotframework.org/robotframework/latest/RobotFrameworkUserGuide.html#getting-keyword-arguments

The feature is called _named-only arguments_ The difference is in how you can call the keyword with arguments

`def kw(self, arg1=None, *args):`

allows for both positional and named usage:
`kw    value`
`kw    arg1=value`

with `def kw(self, *, arg1=None):` the first option will be rejected and forces the use of named arguments. Or it clearly separates positional arguments from named arguments if you have both.

Please note that your suggestion `def kw(self, arg1=None, *):` is actualy rejected causing the error `SyntaxError: named arguments must follow bare *`
