### ISSUE TITLE
RF Case Select checkbox missing on CENTOS 7 linux 

### ISSUE THREAD

**Issue by theSeaHeartGit** [robotframework/RIDE#2345]
Hi, Guys
      We just install the RIDE 1.7.4.1 on CENOS 7 linux and fund that the 'Case Select checkbox' missing. It's very inconvenient for case select running. Could you please help check this issue?  
      For detail, please check the following snapshot pic.
![image](https://user-images.githubusercontent.com/51774425/100331088-b3d7c280-300a-11eb-865f-8435b9c98932.png)

Thx
Sean

**Comment by HelioGuilherme66** [comment]
@theSeaHeartGit Please give more details on versions used: Python, wxPython (and if GTK2 or GTK3)
You may want to try the pre-release version Beta 1. Look at the README on the Code tab of this project. Thanks.

**Comment by theSeaHeartGit** [comment]
@HelioGuilherme66 thanks for your information.
The more detail information as following:
python -- 3.6.6
wxPython -- 4.0.4
GTK3 (should be, detail as following)
----------------GTK----------------------------------------------------
$ pkg-config --list-all|grep gtk
gtk+-x11-3.0                             GTK+ - GTK+ Graphical UI Library
webkit2gtk-4.0                          WebKitGTK+ - Web content engine for GTK+
javascriptcoregtk-3.0                 JavaScriptCoreGTK+ - GTK+ version of the JavaScriptCore engine
gtk+-unix-print-2.0                   GTK+ - GTK+ Unix print support
javascriptcoregtk-4.0                 JavaScriptCoreGTK+ - GTK+ version of the JavaScriptCore engine
gtk+-unix-print-3.0                   GTK+ - GTK+ Unix print support
gtk+-wayland-3.0                      GTK+ - GTK+ Graphical UI Library
gtk+-2.0                                     GTK+ - GTK+ Graphical UI Library (x11 target)
webkit2gtk-web-extension-4.0  WebKitGTK+ Web process extensions - Web content engine for GTK+ - Web process extensions
gtk+-3.0                                     GTK+ - GTK+ Graphical UI Library
webkitgtk-3.0                             WebKit - Web content engine for GTK+
gtk+-x11-2.0                              GTK+ - GTK+ Graphical UI Library (x11 target)


---------------PIP--------------------------------------------------------------------------------------------
pip list output as following:

Package                         Version
------------------------------- ------------
aiofiles                        0.3.2
airtest                         1.1.4
alembic                         0.9.10
amqp                            1.4.9
aniso8601                       3.0.2
anyjson                         0.3.3
Appium-Python-Client            0.26
APScheduler                     3.5.1
arrow                           0.12.1
asn1crypto                      0.24.0
atomicwrites                    1.3.0
attrs                           19.3.0
bcrypt                          3.1.4
beautifulsoup4                  4.8.1
billiard                        3.3.0.23
blinker                         1.4
cached-property                 1.5.2
Camelot                         12.6.29
celery                          3.1.26.post2
certifi                         2018.4.16
cffi                            1.14.0
chardet                         3.0.4
click                           6.7
colorama                        0.4.1
colorlog                        3.1.4
comtypes                        1.1.7
config                          0.4.0
ConfigArgParse                  1.2.3
coverage                        4.5.4
cryptography                    2.2.2
cx-Oracle                       7.3.0
dateparser                      0.7.0
decorator                       4.3.0
Deprecated                      1.2.10
distro                          1.5.0
Django                          2.0.6
django-celery                   3.2.2
djangorestframework             3.8.2
djangorestframework-jwt         1.11.0
docker                          3.7.3
docker-compose                  1.23.2
docker-pycreds                  0.4.0
dockerpty                       0.4.1
docopt                          0.6.2
docutils                        0.14
dominate                        2.3.1
dukpy                           0.2.2
elasticsearch                   6.3.1
Elixir                          0.7.1
et-xmlfile                      1.0.1
filelock                        3.0.12
fire                            0.2.1
Flask                           1.0.2
Flask-APScheduler               1.8.0
Flask-BasicAuth                 0.2.0
Flask-Bootstrap                 3.3.7.1
Flask-Cors                      3.0.6
Flask-HTTPAuth                  3.2.4
flask-ldap3-login               0.9.15
Flask-Login                     0.2.11
Flask-Mail                      0.9.0
Flask-Migrate                   2.3.0
Flask-Moment                    0.5.1
flask-redis                     0.4.0
Flask-RESTful                   0.3.6
Flask-Script                    2.0.6
Flask-SQLAlchemy                2.3.2
Flask-SSLify                    0.1.5
Flask-WTF                       0.14.2
ForgeryPy                       0.1
future                          0.16.0
gevent                          20.5.0
geventhttpclient-wheels         1.3.1.dev3
gitdb2                          2.0.6
GitPython                       2.1.15
googleapis-common-protos        1.5.3
greenlet                        0.4.14
grpcio                          1.15.0
grpcio-tools                    1.15.0
gunicorn                        19.9.0
har2case                        0.1.8
hrpc                            1.0.8
httpie                          1.0.0
httplib2                        0.11.3
HttpRunner                      1.4.8
httptools                       0.0.11
humanize                        0.5.1
idna                            2.7
importlib-metadata              1.1.0
itchat                          1.3.10
itsdangerous                    0.24
javascripthon                   0.10
jdcal                           1.4.1
Jinja2                          2.10.3
JPype1                          1.0.2
jsonpath-rw                     1.4.0
jsonschema                      2.6.0
jupyter-echarts-pypkg           0.1.1
kitchen                         1.2.6
kombu                           3.0.37
ldap                            1.0.2
ldap3                           2.5.1
lml                             0.0.2
locust                          1.0.1
locustio                        0.8.1
logzero                         1.5.0
macropy3                        1.1.0b2
Mako                            1.0.7
Markdown                        2.6.11
MarkupSafe                      1.1.1
marshmallow                     2.16.0
mock                            2.0.0
moment                          0.8.2
mongoengine                     0.15.3
more-itertools                  7.2.0
msgpack                         1.0.0
msgpack-python                  0.5.6
mss                             4.0.3
multidict                       4.4.2
mysql-connector-python          8.0.12
nose                            1.3.7
numpy                           1.15.4
opencv-contrib-python           3.4.2.17
opencv-python                   4.1.2.30
openpyxl                        3.0.2
packaging                       19.2
pandas                          1.0.3
paramiko                        2.4.2
pbr                             4.2.0
Pillow                          5.2.0
pip                             20.2.3
pluggy                          0.13.0
ply                             3.11
poco                            0.97.1
pocoui                          1.0.79
progress                        1.5
prompt-toolkit                  1.0.18
protobuf                        3.6.0
psutil                          5.7.0
psycopg2                        2.7.5
py                              1.8.0
pyaml                           18.11.0
pyasn1                          0.4.4
pyasn1-modules                  0.2.2
pycparser                       2.18
pyecharts                       0.5.5
pyecharts-javascripthon         0.0.6
pyecharts-jupyter-installer     0.0.3
PyGithub                        1.43.5
pyglet                          1.3.2
Pygments                        2.2.0
PyJWT                           1.6.4
pymongo                         3.7.1
PyMySQL                         0.9.2
PyNaCl                          1.3.0
pyparsing                       2.4.5
pypng                           0.0.18
PyPubSub                        3.3.0
PyQRCode                        1.2.1
pytest                          3.7.1
pytest-html                     1.19.0
pytest-metadata                 1.8.0
python-crontab                  2.5.1
python-dateutil                 2.7.3
python-dotenv                   0.9.1
python-editor                   1.0.3
python-gitlab                   1.8.0
python-xlib                     0.28
pytz                            2018.5
pywinauto                       0.6.3
PyYAML                          3.13
pyzmq                           17.0.0
redis                           2.10.6
regex                           2018.8.29
requests                        2.20.1
requests-toolbelt               0.8.0
robotframework                  3.1.2
robotframework-appiumlibrary    1.5.0.6
robotframework-databaselibrary  1.2.4
robotframework-debuglibrary     2.2.1
robotframework-excellentlibrary 1.0.0
robotframework-redislibrary     1.2.1
robotframework-requests         0.7.1
robotframework-ride             1.7.4.1
robotframework-seleniumlibrary  3.3.1
selenium                        3.13.0
setuptools                      50.3.0
six                             1.11.0
smmap                           3.0.4
smmap2                          3.0.1
soupsieve                       1.9.4
SQLAlchemy                      1.3.16
sqlalchemy-migrate              0.13.0
sqlparse                        0.3.1
stomp.py                        6.1.0
svn                             0.3.46
Tempita                         0.5.2
termcolor                       1.1.0
texttable                       0.9.1
times                           0.7
typing-extensions               3.7.4.3
tzlocal                         1.5.1
urllib3                         1.24.3
visitor                         0.1.3
wcwidth                         0.1.7
websocket-client                0.48.0
Werkzeug                        0.14.1
wheel                           0.35.1
wrapt                           1.12.1
WTForms                         2.1
wxPython                        4.0.4
xlrd                            0.7.1
xlwt                            0.7.2
zipp                            0.6.0

**Comment by HelioGuilherme66** [comment]
You can try to upgrade wxPython, and then RIDE (just have the version fixed for wxPython):
```
sudo -H pip install -U https://extras.wxpython.org/wxPython4/extras/linux/gtk3/centos-7/wxPython-4.0.7.post2-cp36-cp36m-linux_x86_64.whl
sudo -H pip install -U robotframework-ride

```

**Comment by theSeaHeartGit** [comment]
@HelioGuilherme66  Appreciate your grade help.
The RIDE work fine after upgrade wxPython from version 4.0.4 to 4.0.7.
