### ISSUE TITLE
[PARSER]: UnicodeDecodeError: 'utf-8' codec can't decode byte 0xbb in position 36: invalid start byte

### ISSUE THREAD

**Issue by liyadong123** [robotframework/RIDE#2348]
RIDE 1.7.4.2 running on Python 3.6.2. 
============================================
Q1:when i open ride
"[PARSER]: UnicodeDecodeError: 'utf-8' codec can't decode byte 0xbb in position 36: invalid start byte" is displayed in the parser log
============================================
Q2:when i run a testcase
run error:"command: robot --argumentfile C:\Users\6666666\AppData\Local\Temp\RIDEjpa7auw4.d\argfile.txt --listener C:\Python36\lib\site-packages\robotide\contrib\testrunner\TestRunnerAgent.py:56000:False D:\git\testCase2\TestCase
[ ERROR ] Parsing 'D:\git\testCase2\TestCase\tests\01用-应用系统\01中文应用' failed: UnicodeDecodeError: 'utf-8' codec can't decode byte 0xbb in position 91: invalid start byte

Try --help for usage information.

test finished 20201211 16:04:29"

note:my testcase compiled in Chinese，and use UTF-8 code

**Comment by jnhyperion** [comment]
Version 1.7.4.2 does not support Python3 properly, please use latest version instead:

`pip install -U https://github.com/robotframework/RIDE/archive/master.zip`

**Comment by HelioGuilherme66** [comment]
@liyadong123 You should try this [proposal](https://github.com/robotframework/RIDE/wiki/F.A.Q.#5-q-on-windows-when-running-test-suites-with-asian-characters-on-filenames-or-paths-the-output-and-log-panels-show-those-characters-with--how-to-fix).
