### ISSUE TITLE
 I can't start the RIDE tool

### ISSUE THREAD

**Issue by JoaoPequeno** [robotframework/RIDE#2351]
Hello. I cant run the RIDE:
`C:\Users\João Pequeno\Downloads\robotframework-autoitlibrary-1.2.7>ride.py
Traceback (most recent call last):
  File "c:\users\joão pequeno\appdata\local\programs\python\python38-32\lib\site-packages\robotide\application\application.py", line 64, in OnInit
    self._plugin_loader.enable_plugins()
  File "c:\users\joão pequeno\appdata\local\programs\python\python38-32\lib\site-packages\robotide\application\pluginloader.py", line 36, in enable_plugins
    p.enable_on_startup()
  File "c:\users\joão pequeno\appdata\local\programs\python\python38-32\lib\site-packages\robotide\application\pluginconnector.py", line 52, in enable_on_startup
    self.enable()
  File "c:\users\joão pequeno\appdata\local\programs\python\python38-32\lib\site-packages\robotide\application\pluginconnector.py", line 57, in enable
    self._plugin.enable()
  File "c:\users\joão pequeno\appdata\local\programs\python\python38-32\lib\site-packages\robotide\contrib\testrunner\testrunnerplugin.py", line 225, in enable
    self._add_tab_to_notebook()
  File "c:\users\joão pequeno\appdata\local\programs\python\python38-32\lib\site-packages\robotide\contrib\testrunner\testrunnerplugin.py", line 814, in _add_tab_to_notebook
    self._output_panel = self._build_output_panel(self.panel)
  File "c:\users\joão pequeno\appdata\local\programs\python\python38-32\lib\site-packages\robotide\contrib\testrunner\testrunnerplugin.py", line 842, in _build_output_panel
    self.show_message_log,
  File "c:\users\joão pequeno\appdata\local\programs\python\python38-32\lib\site-packages\robotide\pluginapi\plugin.py", line 136, in __getattr__
    raise AttributeError("No attribute or settings with name '%s' found" % name)
AttributeError: No attribute or settings with name 'show_message_log' found
OnInit returned false, exiting...
Error in atexit._run_exitfuncs:
wx._core.wxAssertionError: C++ assertion "GetEventHandler() == this" failed at ..\..\src\common\wincmn.cpp(478) in wxWindowBase::~wxWindowBase(): any pushed event handlers must have been removed`

My list of framework is:
`C:\Users\João Pequeno\Downloads\robotframework-autoitlibrary-1.2.7>pip list
Package                      Version
---------------------------- -----------
numpy                        1.19.4
Pillow                       8.0.1
pip                          20.1.1
psutil                       5.7.3
Pygments                     2.7.3
Pypubsub                     4.0.3
pywin32                      300
robotframework               3.2.2
robotframework-autoitlibrary 1.2.7
robotframework-ride          2.0b2.dev1
setuptools                   47.1.0
six                          1.15.0
wxPython                     4.0.7.post2`

Can you help me?

Thanks and best regards,
João Pequeno

**Comment by HelioGuilherme66** [comment]
@JoaoPequeno Olá, como é que vai o Robin dos Bosques? (desculpa lá, deves estar sempre a ouvir isto :) )

You don't say how you installed RIDE, but I know it was from our current development on `master`.

You can fix your install by adding:
`show_message_log = True` in the section 
```
[Plugins]
[[Test Runner]]
```
of the settings.cfg file at `%APPDATA%\RobotFramework\ride`


Or better install this, which includes a fix:
```
python -m pip install -U https://github.com/HelioGuilherme66/RIDE/archive/colours.zip
```

**Comment by JoaoPequeno** [comment]
@HelioGuilherme66  Obrigado pela resposta! Infelizmente o erro permanece :(

Hi! Unfortunately the error remains :(


I downloaded the version you indicated:
`C:\Users\João Pequeno\AppData\Local\Programs\Python\Python38-32>python -m pip install -U https://github.com/HelioGuilherme66/RIDE/archive/colours.zip
Collecting https://github.com/HelioGuilherme66/RIDE/archive/colours.zip
  Using cached https://github.com/HelioGuilherme66/RIDE/archive/colours.zip
Requirement already satisfied, skipping upgrade: wxPython in c:\users\joão pequeno\appdata\local\programs\python\python38-32\lib\site-packages (from robotframework-ride==2.0b2.dev2) (4.0.7.post2)
Requirement already satisfied, skipping upgrade: PyPubSub in c:\users\joão pequeno\appdata\local\programs\python\python38-32\lib\site-packages (from robotframework-ride==2.0b2.dev2) (4.0.3)
Requirement already satisfied, skipping upgrade: Pygments in c:\users\joão pequeno\appdata\local\programs\python\python38-32\lib\site-packages (from robotframework-ride==2.0b2.dev2) (2.7.3)
Requirement already satisfied, skipping upgrade: psutil in c:\users\joão pequeno\appdata\local\programs\python\python38-32\lib\site-packages (from robotframework-ride==2.0b2.dev2) (5.7.3)
Requirement already satisfied, skipping upgrade: Pywin32 in c:\users\joão pequeno\appdata\local\programs\python\python38-32\lib\site-packages (from robotframework-ride==2.0b2.dev2) (300)
Requirement already satisfied, skipping upgrade: pillow in c:\users\joão pequeno\appdata\local\programs\python\python38-32\lib\site-packages (from wxPython->robotframework-ride==2.0b2.dev2) (8.0.1)
Requirement already satisfied, skipping upgrade: six in c:\users\joão pequeno\appdata\local\programs\python\python38-32\lib\site-packages (from wxPython->robotframework-ride==2.0b2.dev2) (1.15.0)
Requirement already satisfied, skipping upgrade: numpy; python_version >= "3.0" in c:\users\joão pequeno\appdata\local\programs\python\python38-32\lib\site-packages (from wxPython->robotframework-ride==2.0b2.dev2) (1.19.4)
Using legacy setup.py install for robotframework-ride, since package 'wheel' is not installed.
Installing collected packages: robotframework-ride
  Attempting uninstall: robotframework-ride
    Found existing installation: robotframework-ride 2.0b2.dev2
    Uninstalling robotframework-ride-2.0b2.dev2:
      Successfully uninstalled robotframework-ride-2.0b2.dev2
    Running setup.py install for robotframework-ride ... done
Successfully installed robotframework-ride-2.0b2.dev2
WARNING: You are using pip version 20.1.1; however, version 20.3.3 is available.
You should consider upgrading via the 'C:\Users\João Pequeno\AppData\Local\Programs\Python\Python38-32\python.exe -m pip install --upgrade pip' command.`


When I execute the command "ride.py", the following error appears:
`C:\Users\João Pequeno\AppData\Local\Programs\Python\Python38-32>ride.py
Traceback (most recent call last):
  File "C:\Users\João Pequeno\AppData\Local\Programs\Python\Python38-32\lib\site-packages\robotide\application\application.py", line 105, in OnInit
    self._find_robot_installation()
  File "C:\Users\João Pequeno\AppData\Local\Programs\Python\Python38-32\lib\site-packages\robotide\application\application.py", line 295, in _find_robot_installation
    str(rf_version, 'utf-8'), str(os.path.dirname(rf_file), 'utf-8'))).publish()
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xe3 in position 11: invalid continuation byte
OnInit returned false, exiting...
Error in atexit._run_exitfuncs:
wx._core.wxAssertionError: C++ assertion "GetEventHandler() == this" failed at ..\..\src\common\wincmn.cpp(478) in wxWindowBase::~wxWindowBase(): any pushed event handlers must have been removed`

**Comment by HelioGuilherme66** [comment]
That is a different error :)

**Comment by jnhyperion** [comment]
@HelioGuilherme66 Fixed in: https://github.com/robotframework/RIDE/pull/2349/files#diff-3364619b98bb0fb4e1585706346814f5d994dfc9f6f7f25dd2edc1eb7a2f84a8

**Comment by Devyani18** [comment]
> @JoaoPequeno Olá, como é que vai o Robin dos Bosques? (desculpa lá, deves estar sempre a ouvir isto :) )
> 
> You don't say how you installed RIDE, but I know it was from our current development on `master`.
> 
> You can fix your install by adding:
> `show_message_log = True` in the section
> 
> ```
> [Plugins]
> [[Test Runner]]
> ```
> 
> of the settings.cfg file at `%APPDATA%\RobotFramework\ride`
> 
> Or better install this, which includes a fix:
> 
> ```
> python -m pip install -U https://github.com/HelioGuilherme66/RIDE/archive/colours.zip
> ```

Hey Thanks! This worked for me.

**Comment by HelioGuilherme66** [comment]
@JoaoPequeno Please retest on new version 2.0b2.

**Comment by Harm10** [comment]
@HelioGuilherme66 Will this issue also be solved by your last update for coping with diacritic characters on Windows?

**Comment by HelioGuilherme66** [comment]
@Harm10 this is already fixed, but was waiting for confirmation from issue creator.

**Comment by HelioGuilherme66** [comment]
Closing because of no response from author.
