### ISSUE TITLE
Setting (or saving) width of left side window(s)?

### ISSUE THREAD

**Issue by Harm10** [robotframework/RIDE#2353]
Each time I start RIDE the left side window(s) are small and I have to make them slightly wider. Can this size be set somewhere? Or just save that size when exiting?
I am on Windows and have version 1.7.4.2 (on the dev version I see the same behavior)

**Comment by HelioGuilherme66** [comment]
@Harm10 I have that feature already working but on my personal branch `colours`. You can see it on my PR or you can wait for next Beta 2.

**Comment by Harm10** [comment]
Thanks for your reply and message that it will be included in v2.0
I will await that new version.
