### ISSUE TITLE
"Search Keywords" could not search some selenium Keywords in Mac OS

### ISSUE THREAD

**Issue by gigglegile** [robotframework/RIDE#2354]
1.  Mac OS info: Catalina 10.15.7(19H15)
2. pip list: 
Package                         Version
------------------------------- -----------
numpy                           1.19.5
Pillow                          8.1.0
pip                             20.3.3
Pygments                        2.7.3
Pypubsub                        4.0.3
robotframework                  3.2.2
robotframework-pythonlibcore    2.2.1
robotframework-ride             1.7.4.2
robotframework-selenium2library 3.0.0
robotframework-seleniumlibrary  4.5.0
selenium                        3.141.0
setuptools                      51.1.1
six                             1.15.0
urllib3                         1.26.2
wxPython                        4.0.7.post2
3. steps:  after open the RIDE successfully; writing a simple script: 
![image](https://user-images.githubusercontent.com/33651173/103749162-1aa3bf00-5040-11eb-9d5d-94a0b38a7ad9.png)
the 'open browser' is black, while other keywords are blue; 
and in 'Search Keywords', there is not 'open browser'; 
actually, there are many selenium keywords can not be searched 
but, the script can run successfully;

**Comment by caohongjia** [comment]
Windows Operation Environment also search some keywords will be black not blue, but the test is PASS

Win10 OS: 1803(10.0.17134.1)

pip list: 

numpy                           1.20.2
Pillow                          8.1.2
pip                             21.0.1
Pygments                        2.8.1
Pypubsub                        4.0.3
pywin32                         300
robotframework                  4.0
robotframework-pythonlibcore    2.2.1
robotframework-ride             1.7.4.2
robotframework-selenium2library 3.0.0
robotframework-seleniumlibrary  5.1.3
selenium                        3.141.0
setuptools                      47.1.0
six                             1.15.0
urllib3                         1.26.4
wxPython                        4.0.7.post2

**Comment by HelioGuilherme66** [comment]
@gigglegile Please retest on new version 2.0b2.

**Comment by HelioGuilherme66** [comment]
Closing because of no response from author.
