### ISSUE TITLE
[MacOS] Can't start RIDE

### ISSUE THREAD

**Issue by BrunoAndroidDev** [robotframework/RIDE#2362]
Hello,

I've have tested so many ways to have a good environment but I failed every time and I'm lost...
What I have tested:
- python3.9 with the last version of Robot Framework, as specified in the README, 2.0b2.dev1
- python3.9 with the last released version, ie 1.7.4.2
- python2.7 with RF 1.7.4.2 and the last one
- python3.8 with the same two versions of RF

And none is working. I've seen 2 issues about it, #2357 and #2351, but both are on Windows and I don't think I encounter the same problem because I'm on MacOS Mojave (10.14.6)

Below are the logs with python3.8 and RIDE 2.0b2.dev1 when I try to launch RIDE
```
$ ride.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/robotide/application/application.py", line 64, in OnInit
    self._plugin_loader.enable_plugins()
  File "/usr/local/lib/python3.8/site-packages/robotide/application/pluginloader.py", line 36, in enable_plugins
    p.enable_on_startup()
  File "/usr/local/lib/python3.8/site-packages/robotide/application/pluginconnector.py", line 52, in enable_on_startup
    self.enable()
  File "/usr/local/lib/python3.8/site-packages/robotide/application/pluginconnector.py", line 57, in enable
    self._plugin.enable()
  File "/usr/local/lib/python3.8/site-packages/robotide/contrib/testrunner/testrunnerplugin.py", line 225, in enable
    self._add_tab_to_notebook()
  File "/usr/local/lib/python3.8/site-packages/robotide/contrib/testrunner/testrunnerplugin.py", line 814, in _add_tab_to_notebook
    self._output_panel = self._build_output_panel(self.panel)
  File "/usr/local/lib/python3.8/site-packages/robotide/contrib/testrunner/testrunnerplugin.py", line 842, in _build_output_panel
    self.show_message_log,
  File "/usr/local/lib/python3.8/site-packages/robotide/pluginapi/plugin.py", line 136, in __getattr__
    raise AttributeError("No attribute or settings with name '%s' found" % name)
AttributeError: No attribute or settings with name 'show_message_log' found
OnInit returned false, exiting...
Error in atexit._run_exitfuncs:
wx._core.wxAssertionError: C++ assertion "GetEventHandler() == this" failed at /Users/robind/projects/bb2/dist-osx-py38/build/ext/wxWidgets/src/common/wincmn.cpp(470) in ~wxWindowBase(): any pushed event handlers must have been removed
```

And here are the installed frameworks

```
$ pip3 list
Package             Version
------------------- ----------
numpy               1.19.5
Pillow              8.1.0
pip                 20.3.3
psutil              5.8.0
Pygments            2.7.4
Pypubsub            4.0.3
robotframework-ride 2.0b2.dev1
setuptools          51.1.1
six                 1.15.0
wheel               0.36.2
wxPython            4.1.1
```

Can anyone help me ?

**Comment by HelioGuilherme66** [comment]
That problem should be already fixed in current development branch.
Please try to install with:

`pip install -U https://github.com/robotframework/RIDE/archive/master.zip`

**Comment by BrunoAndroidDev** [comment]
It is already the command line I used, but with pip3 instead pip, as you
can see in the framework list :


> robotframework-ride 2.0b2.dev1



Le jeu. 28 janv. 2021 à 17:22, Hélio Guilherme <notifications@github.com> a
écrit :

**Comment by HelioGuilherme66** [comment]
You can try to install from my `colours` branch:
```
pip3 install -U https://github.com/HelioGuilherme66/RIDE/archive/colours.zip
```
Or add the missing attribute `show_message_log = True` in the [Test Runner] section of the file settings.cfg.

**Comment by BrunoAndroidDev** [comment]
Installing from the colours branch fix my issue.
Thanks a lot !



Le jeu. 28 janv. 2021 à 21:34, Hélio Guilherme <notifications@github.com> a
écrit :
