### ISSUE TITLE
Open directory or test suite when starting ride

### ISSUE THREAD

**Issue by Harm10** [robotframework/RIDE#2364]
As we are using several projects saved in different directories I would like to have an option to start RIDE and open a specified directory. ride.py does not have a start-up parm at the moment.
Can such a feature be added?

**Comment by HelioGuilherme66** [comment]
@Harm10 As far as I know this feature exists from basically the beginning of the project.

I have tested on Windows 10 and is working:
```
C:\>ride d:\Testes\Trial

C:\>ride d:\Testes\Trial\commented_lines.robot
```

If you are talking about the Desktop shortcut, then it is a matter to modify it.

**Comment by Harm10** [comment]
We are using bat file and I tried it and it works! Is this anywhere documented?

NB: If you have spaces in your project folder name you need to use quotes like this
`C:\>ride "d:\Testes\A Trial"`

**Comment by HelioGuilherme66** [comment]
@Harm10 Yes it is documented. For example:
```
$ ride --help
RIDE -- Robot Framework test data editor

Usage: ride.py [--noupdatecheck] [--debugconsole] [--version] [inpath]

RIDE can be started either without any arguments or by giving a path to a test
data file or directory to be opened.

To disable update checker use --noupdatecheck.

To start debug console for RIDE problem debugging use --debugconsole option.

To see RIDE's version use --version.

RIDE's API is still evolving while the project is moving towards the 1.0
release. The most stable, and best documented, module is `robotide.pluginapi`.
```

**Comment by Harm10** [comment]
I know this issue was closed a while ago but it seems the inpath is not picked up by version 2.0b1? (Running on Python 3.7.9)
Irrespective what I supply as path the last one used is opened. Is there something changed in 2.0b1?

**Comment by HelioGuilherme66** [comment]
@Harm10 Please try to give me some similar conditions for me to try to reproduce the error. What operating system, `chcp` if Windows, exact command and directory path you used.

**Comment by Harm10** [comment]
Windows 10. Command is from a bat file: `ride.py --noupdatecheck "%cd%\cps project"`
Var %cd% holds the current directory like so:
`set cd=%~dp0
REM remove last char (= \)
set cd=%cd:~0,-1%`

Do you need more?

**Comment by HelioGuilherme66** [comment]
I would like to see the full expanded command, with the %cd% actual value.

**Comment by Harm10** [comment]
I have made an echo for it (is this what you expect?):
`ride.py --noupdatecheck "D:\RobotFramework\cps project"`

If I leave out --noupdatecheck the result is the same (so not opening that inpath)

**Comment by HelioGuilherme66** [comment]
@Harm10 I tried with a similar path and it is working, on latest development version.
I did not used variables in the argument. This was my command:

```
C:\temp>ride --noupdatecheck "D:\temp\cps project"
```

My RIDE Log:
```
20210514 17:39:17.933 [INFO]: Started RIDE v2.0b2.dev3 using python version 3.8.6 with wx version 4.1.1 in win32.
```

**Comment by Harm10** [comment]
I tried it with the latest Dev version installed and still it opens the last used location in stead of the specified one.
My log
`20210514 21:47:42.632 [INFO]: Found Robot Framework version 4.0 from D:\Program Files\Python\lib\site-packages\robot.

20210514 21:47:42.632 [INFO]: Started RIDE v2.0b2.dev3 using python version 3.7.9 with wx version 4.1.1 in win32.`

So how to resolve this issue?

**Comment by HelioGuilherme66** [comment]
You are using that %cd% construction, and that is probably why there is problems.

This variable expansion would be too expensive to resolve on RIDE side, because:

- it is exclusive for Windows operating system
- you can change your starting command to use expanded variable

**Comment by Harm10** [comment]
So I tried it without the %cd% construction by hard coding the full location but it still does not work.
So the variable is not the reason I think.

I use a different version of RIDE at work (will get the version on monday) that works fine like this.

Can I perhaps debug something?

**Comment by Harm10** [comment]
What should happen if I start ride.py with option --debugconsole ?
Because nothing extra seems to happen?

**Comment by HelioGuilherme66** [comment]
It should be very notorious, running with `--debugconsole`. But I don't use Windows for developing RIDE, and can't test.

About using Windows variables, I did some especial parsing for TestRunner to parse the arguments by Operating System, before using them. That should be probably the same technique.

**Comment by Harm10** [comment]
Please leave out the analysis of the variable used. As I said hard coding the inpath also does not open that location.
Same thing when I do not use a bat file but enter the command directly in a command box.

I think --debugconsole displays some messages in the command box that is opened when ride starts. But when they are displayed and for what reason still eludes me.

Can I debug the inpath issue in some way? What script will be executed when an inpath is processed? So I can put in some debug statements to see what is happening? I am a developer so not afraid of doing such things (as long as it on platforms I am familiar with)

**Comment by HelioGuilherme66** [comment]
You are probably using an old version of RIDE. Like I said, this is working on current development version. In the [CHANGELOG](https://github.com/robotframework/RIDE/blob/master/CHANGELOG.adoc) the 3rd fix is related with arguments.

**Comment by Harm10** [comment]
My log shows:
`20210516 12:12:37.440 [INFO]: Found Robot Framework version 4.0.2 from D:\Program Files\Python\lib\site-packages\robot.

20210516 12:12:37.440 [INFO]: Started RIDE v2.0b2.dev3 using python version 3.7.9 with wx version 4.1.1 in win32.`

That is the RIDE version you asked me to install.
Please point me to the script that should process the inpath so I can try to debug?

In the settings.cfg the default directory has a value which is the same as the location that RIDE is now opening while disregarding the inpath.

**Comment by Harm10** [comment]
I found this report [https://stackoverflow.com/questions/29540541/python-script-does-not-take-sys-argv-in-windows](url) which describes a similar problem.
I added 
```
# Count the arguments
arguments = len(sys.argv) - 1
print ("The script is called with %i arguments" % (arguments))
```
 to D:\Program Files\Python\Scripts\ride.py and started ride.py with some arguments to find that none of them were received.
If I change the command to include python to start script ride.py the arguments are received (and the inpath works).

I checked my register and it looks that it is OK but I am sure I have 2 python installs so maybe that is the reason the arguments are not picked up when I just do ride.py? Any idea?

Probably others could encounter this problem too! 
So I think the inpath (and the other argument's) instruction should report something about this?

In my case the working command is
`python "D:\Program Files\Python\Scripts\ride.py" --noupdatecheck "D:\RobotFramework\cps project"`

**Comment by HelioGuilherme66** [comment]
To be sure you use the correct Python and avoiding ride.py or ride.bat you can use:
`D:\Program Files\Python\python.exe -m robotide.__init__ --noupdatecheck "D:\RobotFramework\cps project"`

The desktop shortcut uses pythonw to avoid a command window.
