### ISSUE TITLE
how can after log-in move to another page?

### ISSUE THREAD

**Issue by nickbreeze7** [robotframework/RIDE#2366]
Hello 
I want to test-case with ride fraemwork.
My purpose is test B page.
When i open browser B page , it included A log-in page.
**Easily speaking this process like  A log-in page move B page drop-down & click element .**
How can i do that??
From this week , started project...

**Comment by HelioGuilherme66** [comment]
@nickbreeze7 You should know that this is an Issue tracker, which means it is to report problems with RIDE software, or to suggest improvements.

You should look at robotframework.org pages to see where to ask questions. Searching the Internet will find some examples of Web testing with Robot Framework.
