### ISSUE TITLE
Release plans for RIDE 2.x

### ISSUE THREAD

**Issue by axiom41** [robotframework/RIDE#2367]
Hi there…
Very long time since the latest 2.0 beta release of the editing tool (July 2020)...
When do you think we can expect an update to this beta and also a final 2.x release, even because Selenium library has stepped forward to rel. 5.1.0 a couple of days ago and Python 3.8 and 3.9 (both not compatible with RIDE 1.7.4.2) have been released since Oct. 2019 and Oct. 2020, respectively?

Are you going to test the 2.0 beta with Selenium library 5.1.0 or at least if the workaround proposed for Selenium library > 4.3.0 in issue #2195 is still applicable to rel. 1.7.4.2, by locally regenerating the library xml file?

Many thanks in advance for your support.

**Comment by Harm10** [comment]
I am interested too in the release planning. When is someone going to answer this question?

**Comment by kanchi240** [comment]
Is 2.0 support RF4.0 IF/ELSE and SKIP new feature?

**Comment by Harm10** [comment]
Apparently it is hard for RIDE support to give any reaction to our questions? :-(

**Comment by axiom41** [comment]
In another thread (see link below), @HelioGuilherme66 (apparently the only RIDE team member who is still dealing with the tool) replied this way to the same question, so i guess all we can do is to be (very) patient...

https://github.com/robotframework/RIDE/issues/2371#issuecomment-804801086

**Comment by HelioGuilherme66** [comment]
@axiom41 We have now the new version 2.0b2.
