### ISSUE TITLE
In grid mode, multiple selected rows are not pasted correctly

### ISSUE THREAD

**Issue by axiom41** [robotframework/RIDE#2388]
Hello.
In Win10 x64, Python 3.7.9 x64 and RIDE 2.0b1 maybe there is a bug in pasting multiple lines to another location. Single line is pasted correctly.
Please look at the following images to see what happens (issue is in the last one; it's not happening with RIDE 1.7.4.2):

![image](https://user-images.githubusercontent.com/9963199/114899437-3ffc5200-9e13-11eb-9f3f-23d70eeed5db.png)

![image](https://user-images.githubusercontent.com/9963199/114899468-45599c80-9e13-11eb-83fe-a6639a2f4656.png)

![image](https://user-images.githubusercontent.com/9963199/114899491-4be81400-9e13-11eb-904d-38e9d20120f2.png)

![image](https://user-images.githubusercontent.com/9963199/114899542-54d8e580-9e13-11eb-836a-d2109c481085.png)

![image](https://user-images.githubusercontent.com/9963199/114899568-5bfff380-9e13-11eb-9679-5f7bc30553c5.png)

**Comment by HelioGuilherme66** [comment]
I confirm (at least on Windows).
It only happens when copying multiple lines.

Workaround is to copy blocks of cells, or use Text Editor.
