### ISSUE TITLE
RIDE can't run winform exe

### ISSUE THREAD

**Issue by vb123er951** [robotframework/RIDE#2389]
Hi, I am testing a winform exe with RIDE, but I cannot run the winform exe within RIDE (if use SciTE write au3 script and it executes successfully), can someone help about this problem?

I use Anaconda Python 3.6 with newest robot framework and autoitlibrary v1.1

here is my script
```
*** Settings ***
Library           AutoItLibrary

*** Variables ***
${winformexe}     D:\\practice\\HelloWorld\\HelloWorld\\bin\\Release\\netcoreapp3.1\\HelloWorld.exe

*** Test Cases ***
TC0
    [Documentation]    My first test case in ride
    Run    ${winformexe}
    Win Wait Active    Form1
    Control Set Text    Form1    \    [NAME:textBox1]    test
```

and the error message RIDE shows is
```
===============================================================================================================================================================
Testing                                                                                                                                                        
===============================================================================================================================================================
TC0 :: My first test case in ride                                                                                                                      | FAIL |
Window 'Form1' () failed to be active in 60 seconds
```

p.s. I program the winform exe myself, it is a simple app that only contain a button and a textbox, some text will appear in textbox when push the button.

**Comment by HelioGuilherme66** [comment]
That does not seem a problem of RIDE, because you opened the file, no report of broken library, and you ran it on TestRunner.
To be sure the same problem happens in command window, you must test in `cmd` or `powershell`.

**Comment by vb123er951** [comment]
I test script in `cmd` and the result is same...

the command: `robot -d output -t TC4 Automating_program_1.robot`
and the result is
![image](https://user-images.githubusercontent.com/15091938/115641617-057f4180-a34c-11eb-9374-c2b89f6e3bf3.png)

**Comment by HelioGuilherme66** [comment]
Then you confirm that this is not a RIDE issue.

You should try to ask on other Forum, like the ones we list on the README file, or StackOverflow,

To try to debug you should run the test with `--loglevel TRACE`.

Good luck.
