### ISSUE TITLE
Repeating warnings/questions 'Files Changed On Disk' when RIDE Test Suites Explorer gets focus

### ISSUE THREAD

**Issue by randyxxl** [robotframework/RIDE#2391]
When switching between RIDE and another application (e.g. Firefox) I repeatedly get the warning/question 'Files Changed On Disk - Do you want to reload the workspace?' when I click the Test Suites Explorer pane.

The happens almost every time when I re-enter RIDE and click the Test Suites Explorer. As far as I can see no other application is active nor writing to the RF project folder. I suspect it is a bug in RIDE, but maybe another library is misbehaving.

My project is stored in a subfolder of MyDocuments.

Current setup:
`RIDE v2.0b1 running on Python 3.7.9  on Windows 10` 

```

$ pip list
Package                        Version
------------------------------ -----------
appdirs                        1.4.4
bcrypt                         3.2.0
beautifulsoup4                 4.9.3
certifi                        2020.12.5
cffi                           1.14.3
chardet                        4.0.0
cryptography                   3.4.7
idna                           2.10
lxml                           4.5.2
numpy                          1.20.2
paho-mqtt                      1.5.1
paramiko                       2.7.2
Pillow                         8.2.0
pip                            21.1.1
psutil                         5.8.0
pycparser                      2.20
Pygments                       2.8.1
PyMySQL                        1.0.2
PyNaCl                         1.4.0
Pypubsub                       4.0.3
pywin32                        300
requests                       2.25.1
robotframework                 4.0.1
robotframework-databaselibrary 1.2.4
robotframework-difflibrary     0.1.0
robotframework-mqttlibrary     0.7.1.post3
robotframework-pythonlibcore   2.2.1
robotframework-ride            2.0b1
robotframework-seleniumlibrary 5.1.3
robotframework-sshlibrary      3.6.0
scp                            0.13.3
selenium                       3.141.0
setuptools                     56.0.0
six                            1.15.0
soupsieve                      2.0.1
tqdm                           4.50.2
urllib3                        1.25.10
webdrivermanager               0.10.0
wxPython                       4.1.1
```

**Comment by HelioGuilherme66** [comment]
Still not enough information to understand the root cause. But you say:
>My project is stored in a subfolder of MyDocuments.

If you open a folder on RIDE, it will monitor the changes to project files, if you have other application that modifies those files then you should get the pop-up.

You can experiment to make a copy of your project to some folder out of system directories, like on C:\temp,
And then see if RIDE behaves the same way.

**Comment by randyxxl** [comment]
I did some extra testing using different disks and locations. 

The folder & file structure I use:
```
<parent folder>
 ├─ RF
 │  ├─ .robot
 │  ├─ database_connect.robot
 │  └─ Demo.robot
 └─ RF_credentials
    └─ crendentials.robot
```

Checked variables:
- Turn off OneDrive (OneDrive might do some I/O, although it should be monitoring a different folder)
- Turn off Sync  (Sync might do some I/O, although it should be monitoring a different folder)
- Different disks
  -  C:  (SSD in raid 0)
  -  J:  (HDD)
  -  M:  (SSD)
- Different parent folders as listed below

It turns out that the folder location makes the difference:

- OK parent folder:
```
- C:\tmp
- C:\Users\<name>\Documents
- J:\tmp
- J:\Gebruikers\<name>\Mijn Documenten\tmp
- J:\Gebruikers\<name>\tmp
- J:\Users\<name>\tmp\
- M:\Robot Framework Tests
- M:\RobotFrameworkTests
```

- NOK parent folder:
```
- 'Documents' (Maps to `J:\Gebruikers\<name>\Mijn Documenten` instead of default `C:\Users\name\My Documents` )
- J:\Gebruikers\<name>\Mijn Documenten
- J:\Gebruikers\<name>
```

I think the repeating message has something to do with the mapping of 'My Documents' (Dutch: 'Mijn Documenten') to a non-standard folder. Most users have their documents stored in My Documents and its located at `C:\Users\<name>\Documents`. 
My documents folder has been moved/mapped to `J:\Gebruikers\<name>\Mijn Documenten`. 

As long as my parent folder is not the mapped user folder `<name>` or `<name>\Mijn Documenten` everything works fine.
Using a subfolder `tmp` in `<name>` or `<name>\Mijn Documenten` is OK. 

Maybe someone with extensive knowledge of the way Windows works can explain this behaviour. 

Btw: the reasons for moving my storage to HDD were that SSD storage was very expensive at the time of building my pc, about 9 years ago, and running 2 SSDs in raid 0 was not recommended. Nowadays I would configure my pc differently.  😉

**Comment by HelioGuilherme66** [comment]
Thanks for having done the experiments.

You agree that RIDE is working as expected, and this issue can be closed?

**Comment by randyxxl** [comment]
Let's close this issue as it's an edge case. It's not applicable to many users and the work-around is pretty easy: create an extra folder for your tests.
