### ISSUE TITLE
Block commenting not working in 2.0b1?

### ISSUE THREAD

**Issue by Harm10** [robotframework/RIDE#2392]
I am on version 2.0b1 on Python 3.7.9
If I select several lines and want to block comment them this does not work.
(Only the last line gets commented)
Similar behavior for uncommenting.

**Comment by HelioGuilherme66** [comment]
@Harm10 This is fixed in current master, version v2.0b2.dev3.

**Comment by Harm10** [comment]
Like in the other issue: is that available for pip install?

**Comment by HelioGuilherme66** [comment]
Yes, you can install with pip, see the [README](https://github.com/robotframework/RIDE)

**Comment by Harm10** [comment]
Forgive my ignorance but on that page there is only the instruction on how to install beta version 2.0b1.
So what is the syntax to install 2.0b2.dev3?

**Comment by HelioGuilherme66** [comment]
You missed the two lines before:

    Install with:

    pip install -U https://github.com/robotframework/RIDE/archive/master.zip

**Comment by Harm10** [comment]
Now you mention it I could have missed that before....... As I am missing that I assume others do as well so a suggestion to change the text just above the pip install: "Install with:" change it to "Install latest pre-release and development with:"

Anyway the problem of the block select and then commenting them all is not solved in this version. It still only does the last one of the block.
Come to say it. If I select a block of lines to delete it also only deletes the last one.

Another remark on this dev version. It colors the background of the Test Suites explorer to yellow. Is that intentional?

Also a remark on the release notes shown.
It states:
"wxPython will be updated to version 4.0.7post2 
wxPython version 4.1, is not recommended to be used with RIDE. "
I have wxPython 4.1.1. installed and during the pip install I get "Requirement already satisfied". So I guess that text should change?

**Comment by HelioGuilherme66** [comment]
>Anyway the problem of the block select and then commenting them all is not solved in this version. It still only does the last one of the block.
>Come to say it. If I select a block of lines to delete it also only deletes the last one.

You mention a "block" selection, but you are referring to "lines" selection.
For me a "block" selection is a group of cells, and the functions are working as expected. 

When you have "lines" selected those functions are not working correctly because the selection is lost.
Now that this difference of language is identified I understand the actual problem.

As a workaround, always use the keys shortcuts on the cells ("block") and not on the lines.


>Another remark on this dev version. It colors the background of the Test Suites explorer to yellow. Is that intentional?
Yes, it is a new feature. You now can change the colors on global elements, on Tools->Preferences->General.

>Also a remark on the release notes shown.
>(...)
You are right. Some text is not updated.

**Comment by Harm10** [comment]
I am sorry for the misunderstanding. In Windows world a block select is a selection of lines (at least it is to me).

I assume this bug is somewhere on the to-do list? Because deleting can be done like you describe but commenting/uncommenting not as far as I aware.

**Comment by HelioGuilherme66** [comment]
>(...) but commenting/uncommenting not as far as I aware.

Use the shortcut keys Ctrl-3 and Ctrl-4.

And you can use them too in Text Editor.

Sure the bug is in a TODO list, jointly with the 167 issues, being the oldest from 2010 !

**Comment by Harm10** [comment]
> Sure the bug is in a TODO list, jointly with the 167 issues, being the oldest from 2010 !

Perhaps someone can assist?

**Comment by axiom41** [comment]
Hello...
Is this issue maybe related to #2388? It seems almost the same behaviour, using rows instead of cell blocks...
