### ISSUE TITLE
Cannot select keywords

### ISSUE THREAD

**Issue by 492456131** [robotframework/RIDE#2396]
The version used is: 2.0b1
Create New Resource After，Search in files keywords,After finding the result，Mouse click on the keyword, the page jumps to the top of the keywords file。
My system is windows 7。

**Comment by 492456131** [comment]
![image](https://user-images.githubusercontent.com/16437314/125180593-46417500-e22e-11eb-98ea-22235b11cead.png)

**Comment by HelioGuilherme66** [comment]
@492456131 I don't understand the problem.
Are you talking about the Text Editor?
>Mouse click on the keyword, the page jumps to the top of the keywords file。
What is that file?

How you searched in files keywords?

**Comment by 492456131** [comment]
![image](https://user-images.githubusercontent.com/16437314/125183264-b5779300-e247-11eb-86f5-96c11164fc01.png)

**Comment by 492456131** [comment]
This bug only manifests itself if you have a keyword that is longer than the window, and you wish to insert and edit keywords in various places. As soon as you start typing, the scroll bar jumps back to the last place you viewed, which can prevent you from seeing what you are doing.

This bug was produced on Centos 6.8 with Python 2.7.6 and wxPython 3.0.2.

This bug is minor but annoying. Scrolling the mouse wheel can correct the position problem when it occurs, but it will happen again if you move to a different area of the keyword to edit/add lines.

**Comment by 492456131** [comment]
This bug only manifests itself if you have a keyword that is longer than the window, and you wish to insert and edit keywords in various places. As soon as you start typing, the scroll bar jumps back to the last place you viewed, which can prevent you from seeing what you are doing.

This bug was produced on Centos 6.8 with Python 3.8 and wxPython  4.0.7.post2.

This bug is minor but annoying. Scrolling the mouse wheel can correct the position problem when it occurs, but it will happen again if you move to a different area of the keyword to edit/add lines.

**Comment by MummanaSubramanya** [comment]
> This bug only manifests itself if you have a keyword that is longer than the window, and you wish to insert and edit keywords in various places. As soon as you start typing, the scroll bar jumps back to the last place you viewed, which can prevent you from seeing what you are doing.
> 
> This bug was produced on Centos 6.8 with Python 3.8 and wxPython 4.0.7.post2.
> 
> This bug is minor but annoying. Scrolling the mouse wheel can correct the position problem when it occurs, but it will happen again if you move to a different area of the keyword to edit/add lines.

Hi can you please tell me how you got wxPython 4.0.7.post2 with centos6.8 ? I could not find wxpython in this link https://extras.wxpython.org/wxPython4/extras/linux/gtk3/ . I could only see centos7 and centos8. Can you please share the details?

**Comment by HelioGuilherme66** [comment]
@MummanaSubramanya What is the Python version you have? It should be possible to use CentOS 7 files. Did you tried?

**Comment by MummanaSubramanya** [comment]
Im trying to python3.8 when I try to install wxpython its says "wxPython-4.0.7.post2-cp36-cp36m-linux_x86_64.whl is not a supported wheel on this platform."

**Comment by HelioGuilherme66** [comment]
Of course the python version must match the wheel package. If you don't find the correct package, then you must build it.

But you can have RIDE installed in the stock version of Python 3.6 and use other Python to actual run the tests,
