### ISSUE TITLE
Indentation for nested FOR loop is missing after saving file

### ISSUE THREAD

**Issue by sfdcselenium01** [robotframework/RIDE#2398]
From Robot Framework 4.0, nested FOR loop is supported:

FOR	${root}	IN	1	2		
	FOR	${child}	IN	3	4	5
		FOR	${grandchild}	IN	7	9
			Log Many	${root}	${child}	${grandchild}
		END				
	END					
END		

However, after saving file, and reopen saved robot framework using RIDE, all indentation for nested FOR loop are removed, codes become:

FOR	${root}	IN	1	2	
FOR	${child}	IN	3	4	5
FOR	${grandchild}	IN	7	9	
	Log Many	${root}	${child}	${grandchild}	
END					
END					
END					

Same problem for nested IF ELSE statements.

RIDE Environment:
RIDE v2.0b1 running on Python 3.7.9.; Robot Framework 4.0.2

**Comment by HelioGuilherme66** [comment]
@sfdcselenium01 Thanks for the report. This is known because RIDE is not updated to new features on Robot Framework 4.0.
