### ISSUE TITLE
Can't adjust interface colors and can't make dictionary and list variables on MAC

### ISSUE THREAD

**Issue by B-real00** [robotframework/RIDE#2400]
I have troubles with the interface colors on MAC. My python version is 3.9.4 on BigSur 11.4 and I'm using the dark mode theme. I can't see the names of file and folders in my project structure and I having troubles with creating the test case while I am typing the background is yellow and text color white and I don't see anything.
I also having troubles with creating list and dictionary variables. 
I will attach screenshots.

<img width="798" alt="Screen Shot 2021-07-22 at 3 25 45 PM" src="https://user-images.githubusercontent.com/54351967/126833282-17445f38-cfea-46ff-9470-77e336150611.png">
<img width="806" alt="Screen Shot 2021-07-22 at 10 31 05 AM" src="https://user-images.githubusercontent.com/54351967/126833286-ee6f1e8d-dabb-4fd2-99ec-6c7a1527324b.png">
<img width="700" alt="Screen Shot 2021-07-22 at 10 40 56 AM" src="https://user-images.githubusercontent.com/54351967/126833287-7a0c05f3-386c-4c37-9652-9ca581a5ce9e.png">
<img width="254" alt="Screen Shot 2021-07-22 at 11 22 09 AM" src="https://user-images.githubusercontent.com/54351967/126833288-9b2c9670-0e74-4a60-9540-6212c16c933c.png">

**Comment by HelioGuilherme66** [comment]
@B-real00 You repeat the question done in StackOverflow, but still did not say what version you used to install RIDE.
I recommend to uninstall RIDE, and then install again from master branch as explained in README.adoc.

You should alway give info about the version you use. Get the Tools->RIDE Log output and paste here.
