### ISSUE TITLE
How to send AWS credentials with GET request in RIDE please?

### ISSUE THREAD

**Issue by Saruto85** [robotframework/RIDE#2405]
${params}=    Create Dictionary    Authorization=AWS4-HMAC-SHA256 Credential=fsdf/aws4_request, SignedHeaders=content-type;host;x-amz-date, Signature=sdfsdf

    Create Session    newSession    ${base}
    ${response}=    Get On Session    newSession    url=${oldActCode}    headers=${params}
    ${status_code}=    convert to string    ${response.status_code}

It gives me 403 error, un authorized.
What to do please?

**Comment by HelioGuilherme66** [comment]
@Saruto85 Sorry, this is not a RIDE specific problem. I see that you already asked about this on other forums,  hope you get an answer there.
