### ISSUE TITLE
python3.9+robotframework+ride  Chinese error

### ISSUE THREAD

**Issue by yuwy9988** [robotframework/RIDE#2408]
python3.9+robotframework+ride
It's no use modifying  testrunnerplugin，unic.py,testrunner,
How can we solve it

![image](https://user-images.githubusercontent.com/89013845/129545455-0296a6f6-ba7f-4ab5-8b0f-bc4736be564f.png)

**Comment by HelioGuilherme66** [comment]
@yuwy9988 That is not a RIDE error. That is an error from the keyword in Requests Library, because you are seeing it from the log of `robot`.

You should try to do the proposed encoding of the request.

**Comment by yuwy9988** [comment]
How should I set it  and How to set when the label page disappears run tag
