### ISSUE TITLE
run tag page disappear How do you get it back

### ISSUE THREAD

**Issue by yuwy9988** [robotframework/RIDE#2409]
![image](https://user-images.githubusercontent.com/89013845/129561007-55dde881-dbff-4b05-af6f-c81cdbe0fd92.png)

**Comment by HelioGuilherme66** [comment]
There should be some info at Tools>View RIDE Log

Usually to fix, you need to remove the settings from the TestRunner plugin on the settings.cfg file.
You can also see if it is enabled in the Manage Plugins.

**Comment by yuwy9988** [comment]
It's solved. Thank you
