### ISSUE TITLE
Move lines up/down does not work correctly

### ISSUE THREAD

**Issue by ChrisSchneebauer** [robotframework/RIDE#2411]
Hi, we're using RIDE v2.0b1 with Python 3.8.10, Windows.

Problem is, when selecting a line in the editor and moving the line with SHIFT-ALT-UP (or DOWN), the line can only be moved one line. Because the focus remains on the originally selected line.

This seems to be similar to an old issue: #767

Also occurs with current master (v2.0b2.dev3).

**Comment by HelioGuilherme66** [comment]
This is fixed, at least in v2.0.8dev25.
