### ISSUE TITLE
Option "Only run tests with the tags" not working with specific patterns like '1-S_IMPORT_33'

### ISSUE THREAD

**Issue by Fengjiya** [robotframework/RIDE#2414]
Hi，I come to meet some errors with tags like '1-S_IMPORT_01' /'1-S_IMPORT_25'/'1-S_IMPORT_XXX' when using "Only run tests with these tags",it doesn't works with ERROR msg:
[ ERROR ] Suite 'Scbn Uitest' contains no tests matching tag '1-S IMP OR T 01' and matching name '' in suites 'xxx'.

But the option works well with tags like '1-SY_W_015'、'1-ZCQQFBTZQYFB_002' etc.

Here is my system info:
python:3.7.3
ride:1.7.4.2

**Comment by HelioGuilherme66** [comment]
This is a known problem with Robotframework. The labels are being interpreted as using the OR operator. Verify if running on the command line generates the same error. Search Robotframework docs or forums on that. Try to use lowercase labels in the filter call.
