### ISSUE TITLE
Regarding RIDE framework error 

### ISSUE THREAD

**Issue by Guneet20844** [robotframework/RIDE#2416]
While I am trying to run my test case in RIDE I am getting error .Python insallation not found . Even though I have installed python and added its path in environment variable. So what should I do .Where I need to save my project  so that it can recognize the path

**Comment by Harm10** [comment]
I can already guess the first reply: what version of RIDE, robot framework and Python?
You can check in command box with command `where python` if the PATH setting is OK.
Another command to test whether the packages are correctly installed `pip list`
