### ISSUE TITLE
RIDE didn't show the resource files under a directory for few resource files 

### ISSUE THREAD

**Issue by ychavhan** [robotframework/RIDE#2422]
I have created a project where I have a directory and I have added two resource files to it in pycharm.
I can see those files in explorer and in PyCharm without any issues but whenever I opens the RIDE IDE, it only shows the parent directory and not the listing the resource files underneath.

**Comment by HelioGuilherme66** [comment]
@ychavhan I cannot reproduce your case, or is missing some clear way to reproduce. Did you reopen the project after creation of the files?
Below is a screenshot of an example test, where the unused resource files appear with names in gray color:
![image](https://user-images.githubusercontent.com/2866630/139712938-157e0bd4-2a97-45fe-92b7-18445c08d645.png)

**Comment by ychavhan** [comment]
@HelioGuilherme66 Yes I have tried with reopening the project multiple times but no luck !
Please find below my setup configuration:
robotframework    v4.1.2
robotframework-ride   v1.7.4.2
wxPython     v4.0.7.post2

Can you share please confirm once if I am using the right Ride version as yours.

Please find the attached snapshots for both PyCharm where I can see the resources files and RIDE IDE where I cant.

![Pycharm_Snap](https://user-images.githubusercontent.com/55395095/139785673-1eaed6e2-412d-4831-a02e-71b6cfdbffad.jpg)

![ride_snap_resource](https://user-images.githubusercontent.com/55395095/139785696-94373daf-e48a-467e-b7c8-1c3a2f5c3434.jpg)

**Comment by HelioGuilherme66** [comment]
We really have a fix for that in current released 2.0 Beta, as you can see in [CHANGELOG](https://github.com/robotframework/RIDE/blob/master/CHANGELOG.adoc).
Please see how to install that 2.0b1 in the [README](https://github.com/robotframework/RIDE/blob/master/README.adoc).

I would recommend to instal the current development version, since it has more fixes.

**Comment by ychavhan** [comment]
Yup it worked in 2.0b1 build. Thank you very much !
