### ISSUE TITLE
RIDE freezes on every action when large number of variables are imported from file

### ISSUE THREAD

**Issue by amitlohar** [robotframework/RIDE#2423]
In out project, we import variables from 3 different files. Total count of these variables is around **2900**.
We have a main master resource file in which we declare what all is to be imported.

When we try to create a testcase, each and every action takes ~10secs to respond for example ctrl+s action, or even adding/writing something in cell and pressing TAB takes ~10secs to complete/respond. This freeze time increase as the number of lines in test case grow.

The workaround we do for this is:
1. Once the RIDE is opened/loaded, we remove these 3 files import line.
2. Reload (close and open) RIDE
3. Then add the removed lines from Step1, (do not reload RIDE). After this things are normal until RIDE again reloaded with those import lines present.

RIDE ver = v2.0b1 running on Python 3.7.7 Same issue happens even on stable release of RIDE.
robotframework  = 4.1.2
robotframework-seleniumlibrary =5.1.3
Windows Server 2016, 16gb RAM 2cpu

**Comment by chevi** [comment]
We have imports from file and slow performance of the Ride too...
Will test this issue, after fix

**Comment by amitlohar** [comment]
Tested on the new beta build, (2.0b3), issue still exists.
Python 3.7.7
robotframework = 6.0
robotframework-seleniumlibrary =6.0.0
Windows Server 2016, 16gb RAM 2cpu

**Comment by HelioGuilherme66** [comment]
There are improvements that may solve your problem, even without code changes in RIDE.
If the variables are defined in a *.robot file (imported as a Resource), those files should be renamed to *.resource.
If the files with variables definitions are in a normal directory separated from tests, try to rename that directory with a prefix `_`.
So, "resources" or "lib" would be "_resources" and "_lib". With this, Robot Framework and RIDE will not look for test suites there.

**Comment by amitlohar** [comment]
So we have all our keywords written in Resources folder with .robot extension. I will try to change it to .resource.
Adding _ prefix does not show the folder in tree view which is downside for me, since i need them to read/edit if changes.
Hopefully changing extension to .resource will help.

I will try and test it out soon.

**Comment by HelioGuilherme66** [comment]
@amitlohar 
>Adding _ prefix does not show the folder in tree view which is downside for me, since i need them to read/edit if changes.
This should not happen. The folders will be visible in RIDE, only they will not be searched for tests. If resource files are not used by any test suite, they will appear in gray color.

(please use the current development version from `master` if you can. Thanks.)

**Comment by amitlohar** [comment]
I no longer have access to code base and the environment which I was using while reporting the issue. (left the organization)
I won't be able to replicate the scenario or provide any logs/assistance on this further, if no one else is facing this issue anymore, we can close this issue.

**Comment by chevi** [comment]
Hi

Yes, "changing extension to .resource" really helps 

Thanks

**Comment by HelioGuilherme66** [comment]
Assuming Performance is in acceptable levels, this is marked as Fixed.
Thanks for the feedback.
