### ISSUE TITLE
ride.py -> Segmentation fault (core dumped)

### ISSUE THREAD

**Issue by Ishira1601** [robotframework/RIDE#2430]
**Environment:**
Ubuntu 20.04
Python 3.7
Robot Framework 4.1.3 
robotframework-ride   1.7.4.2  
wxPython  4.0.7.post2 
PyPubSub 4.0.3
Pygments 2.10.0
pillow 7.0.0
six 1.14.0
numpy 1.21.2

I have been using RIDE with python 3.8 for sometime but due to some compatibility issues I had to downgrade to python 3.7. RIDE has since stopped working. I reinstall robot and ride both. The installation itself seemed problem free. But when I try to 
`ride.py` in the terminal I get the following error `Segmentation fault (core dumped)`

**Comment by HelioGuilherme66** [comment]
Maybe need more information, strange it only shows the `Segmentation fault (core dumped)`.

Things you can try:
- Completely uninstall RIDE, first with `pip `and then probably even going to site-packages and  removing robotide directory. 
  Then install again (maybe is better with `sudo`)
- Try running with:
   `python3 -m robotide.__init__ `
   or
   `python3 -m robotide.__init__  --debugconsole`
- Install the Beta version like explained at the README on the Code section here.
- Install the current development version like explained at the README on the Code section here (would need to upgrade wxPython to 4.1.1.)

**Comment by Ishira1601** [comment]
1. Uninstall RIDE
`pip uninstall robotframework-ride`
```
Found existing installation: robotframework-ride 1.7.4.2
Uninstalling robotframework-ride-1.7.4.2:
  Would remove:
    /home/user/.local/bin/ride.py
    /home/user/.local/bin/ride_postinstall.py
    /home/user/.local/lib/python3.7/site-packages/robotframework_ride-1.7.4.2.dist-info/*
    /home/user/.local/lib/python3.7/site-packages/robotide/*
Proceed (y/n)? y
  Successfully uninstalled robotframework-ride-1.7.4.2
```
2. Deleted robotide from both python3.8 and python3.7 folders
3. Install robotframework-ride
`sudo pip install robotframework-ride`
```
[sudo] password for user: 
Collecting robotframework-ride
  Downloading robotframework-ride-1.7.4.2.tar.gz (846 kB)
     |████████████████████████████████| 846 kB 2.1 MB/s 
Collecting PyPubSub
  Downloading Pypubsub-4.0.3-py3-none-any.whl (61 kB)
     |████████████████████████████████| 61 kB 1.7 MB/s 
Collecting Pygments
  Downloading Pygments-2.10.0-py3-none-any.whl (1.0 MB)
     |████████████████████████████████| 1.0 MB 12.3 MB/s 
Collecting wxPython<=4.0.7.post2
  Downloading wxPython-4.0.7.post2.tar.gz (68.9 MB)
     |████████████████████████████████| 68.9 MB 90 kB/s 
Requirement already satisfied: pillow in /usr/lib/python3/dist-packages (from wxPython<=4.0.7.post2->robotframework-ride) (7.0.0)
Requirement already satisfied: six in /usr/lib/python3/dist-packages (from wxPython<=4.0.7.post2->robotframework-ride) (1.14.0)
Collecting numpy
  Downloading numpy-1.21.5-cp37-cp37m-manylinux_2_12_x86_64.manylinux2010_x86_64.whl (15.7 MB)
     |████████████████████████████████| 15.7 MB 10.5 MB/s 
Building wheels for collected packages: robotframework-ride, wxPython
  Building wheel for robotframework-ride (setup.py) ... done
  Created wheel for robotframework-ride: filename=robotframework_ride-1.7.4.2-py3-none-any.whl size=950979 sha256=f35ff7bc4cea5c6497088605472277a5748a64d112a0a4c62b1ed8f36e7e99a8
  Stored in directory: /root/.cache/pip/wheels/fc/7e/ad/62316f036476f8a3eba3830dcb12649d85d209e5a42416c348
  Building wheel for wxPython (setup.py) ... done
  Created wheel for wxPython: filename=wxPython-4.0.7.post2-cp37-cp37m-linux_x86_64.whl size=135043773 sha256=f358403ef52ae41eac96d8b18834dfcca7244b4a8b3f90658a2bb9caa12f6ee0
  Stored in directory: /root/.cache/pip/wheels/eb/ec/e1/6f6afceb2d8395a2c534e042f1c9bd4cc4e39dda47c5ed5fd6
Successfully built robotframework-ride wxPython
Installing collected packages: PyPubSub, Pygments, numpy, wxPython, robotframework-ride
Successfully installed PyPubSub-4.0.3 Pygments-2.10.0 numpy-1.21.5 robotframework-ride-1.7.4.2 wxPython-4.0.7.post2

```
4.  `ride.py`
`Segmentation fault (core dumped)`
5. `python3 -m robotide.__init__`
`Segmentation fault (core dumped)`
6. `python3 -m robotide.__init__ --debugconsole`
`Segmentation fault (core dumped)`

**Comment by HelioGuilherme66** [comment]
I am trying to reproduce on a VirtualBox image...

**Comment by Ishira1601** [comment]
what's the version of ride I should install because this happens
`pip install robotframework-ride`
`
Processing /home/user/.cache/pip/wheels/fc/7e/ad/62316f036476f8a3eba3830dcb12649d85d209e5a42416c348/robotframework_ride-1.7.4.2-py3-none-any.whl
Requirement already satisfied: Pygments in /home/user/.local/lib/python3.7/site-packages (from robotframework-ride) (2.10.0)
Processing /home/user/.cache/pip/wheels/eb/ec/e1/6f6afceb2d8395a2c534e042f1c9bd4cc4e39dda47c5ed5fd6/wxPython-4.0.7.post2-cp37-cp37m-linux_x86_64.whl
Requirement already satisfied: PyPubSub in /home/user/.local/lib/python3.7/site-packages (from robotframework-ride) (4.0.3)
Requirement already satisfied: pillow in /usr/lib/python3/dist-packages (from wxPython<=4.0.7.post2->robotframework-ride) (7.0.0)
Requirement already satisfied: six in /usr/lib/python3/dist-packages (from wxPython<=4.0.7.post2->robotframework-ride) (1.14.0)
Requirement already satisfied: numpy; python_version >= "3.0" in /home/user/.local/lib/python3.7/site-packages (from wxPython<=4.0.7.post2->robotframework-ride) (1.21.2)
Installing collected packages: wxPython, robotframework-ride
  Attempting uninstall: wxPython
    Found existing installation: wxPython 4.1.1
    Uninstalling wxPython-4.1.1:
      Successfully uninstalled wxPython-4.1.1
Successfully installed robotframework-ride-1.7.4.2 wxPython-4.0.7.post2
`

**Comment by HelioGuilherme66** [comment]
I suspect that wxPython is not working correctly. Please run the following test:
`python3 -c "from wx import VERSION; print(VERSION)"`

If there is some error, then it is missing a dependency, and we need to install.

**Comment by Ishira1601** [comment]
`python3 -c "from wx import VERSION; print(VERSION)"` ->
```
Segmentation fault (core dumped)
```
According to the FAQ page:  "At the time of this writing, you should use: python3 -m pip install https://extras.wxpython.org/wxPython4/extras/linux/gtk2/centos-7/wxPython-4.0.7.post2-cp36-cp36m-linux_x86_64.whl"
