### ISSUE TITLE
Saving .robot file in grid mode breaks some specific keywords (RIDE v2.0b2.dev5)

### ISSUE THREAD

**Issue by axiom41** [robotframework/RIDE#2433]
Hello.
I'm using the library "robotframework-seleniumscreenshots 0.9.5" (https://pypi.org/project/robotframework-seleniumscreenshots/) and, after updating RIDE to the latest v2.0b2.dev5, when i edit a .robot file containing keywords from such library, RIDE breaks each of them by replacing a character with 4 "spaces" and consequently changing the rest of the KW that stops to work after that

for example, one of the "original" lines, in text mode was:
**${PointyNote}&nbsp;&nbsp;&nbsp;&nbsp;Add Pointy Note&nbsp;&nbsp;&nbsp;&nbsp;css:input#btn_ricerca&nbsp;&nbsp;&nbsp;&nbsp;text=Ricerca pratica&nbsp;&nbsp;&nbsp;&nbsp;background=#6dbfc0&nbsp;&nbsp;&nbsp;&nbsp;position=bottom**

After editing with RIDe the file that contains it, it's changed/malformed to:
**${PointyNote}&nbsp;&nbsp;&nbsp;&nbsp;Add Pointy Note&nbsp;&nbsp;&nbsp;&nbsp;css:inpu&nbsp;&nbsp;&nbsp;&nbsp;#btn_ricerca \ \ \ text=Ricerca pratica \ \ \ background=#6dbfc0 \ \ \ position=bottom**

(the "t" of word "input" is replaced by 4 spaces and all other 4 spaces (separating parameters in original KW) are split to single space characters in a single, unique parameter

This seems to happen only on KW imported from that specific library and it was not happening with RIDE v2.0b2.dev4

Can you please investigate on this (in the meantime i had to revert to RIDE v2.0b2.dev4)?

Many thanks in advance

**Comment by HelioGuilherme66** [comment]
Thanks for the report @axiom41. The changes I did in code were exactly on the area of processing # as the start of a comment, but I did not consider all possible situations, including the ones you show (use in css or color markers).
I'll work on fixing this as soon as possible.

**Comment by axiom41** [comment]
Hi @HelioGuilherme66 
I just tested it and it seems to work on those KW
I additionally tested, for example, on a list variable that was initially defined as:
**@{test1} | first | # | second | # | third**

that, after a "sanity check" error on save, is still changed to:
**@{test1} | first | # \ \ \ second \ \ \ # \ \ \ third**

In this case, using the escape char \ right before # seems to solve the problem:
**@{test1} | first | \# | second | \# | third**

Same for scalar and dict ones

**Comment by axiom41** [comment]
A new bug has been introduced with this change (not present in previous 2.0b2.dev5) in the Test Case grid mode: Setup, Teardown, Template and Tags are not showing in their own fields in Settings but they are added in the Test Case grid as additional lines (see red rectangles in picture below); also, a blank column is added at the beginning of each line in the grid (see orange rectangle in picture below), corrupting all of them

Reverting to 2.0b2.dev4 again then

![image](https://user-images.githubusercontent.com/9963199/154448924-62278ffa-46b0-447a-b3c4-104ca221b872.png)

**Comment by rbradhika530** [comment]
@HelioGuilherme66  I am not able to find Edit Run and Text edit option in robotframeork editor

Earlier it was working fine
