### ISSUE TITLE
If # character is in Documentation it is automatically changed-reformated

### ISSUE THREAD

**Issue by irapths** [robotframework/RIDE#2435]
Hello

When a RF file opened with RIDE its documentation parts (`Documentation` and `[Documentation]`) that contain '#' character are automatically changed.
All characters from '#' until the end of the line are removed from place and appended to the 1st line of `Documentation` or `[Documentation]` they are inside. If there are more than one lines they are appended also.

**Example**
This KW
```
No Doc
    [Documentation]    
    ...
    ...    # # char in KW documentation
    No Operation
```
is transformed to this:
```
No Doc
    [Documentation]    \    # # char in KW documentation
    No Operation
```

Affects v2.0b2.dev5 (before and after the fix for #2433)

I include some additional testing examples (as code here because I had problems uploading them as file).
I'm not sure if all usages of '#' as code line comment I include in example are correct.

```
*** Settings ***
Documentation     Library contains Keywords to read configuration files
...
...               | `Normalize Text` |
...
...               # # char in suite documentation
...               \# Escaped # char in suite documentation
...
...               Examples:
...               | ${text1} | Normalize TextId | Text | # Suite documentation 'inline comment' |
Resource          JSON_reader.resource    # Resource comment


*** Variables ***
${NoKeyError}     Error:NoKeyError    # Variable comment

*** Keywords ***
Normalize Text
    [Arguments]    ${text}    ${keepspaces}=${False}
    [Documentation]    Normalizes the given TextId
    ...
    ...    # # char in KW documentation
    ...    \# Escaped # char in suite documentation
    ...
    ...    Examples:
    ...    | ${text1} | Normalize TextId | Text | # KW documentation 'inline comment' 1 |
    ...    | ${text3} | Normalize TextId | \ \ text \ \ | # KW documentation 'inline comment' 2 |
    ...    | ${text5} | Normalize TextId | te xt | keepspaces=${True} | # KW documentation 'inline comment' 3 |
    ${normText}    Set Variable If    ${keepspaces}    1    2    # KW code inline comment 1
    # KW code line comment in single cell
    #    KW code line comment with text in 2nd cell
    \# NOT KW code line comment because # is escaped
    IF    '${LOG_LEVEL}' == 'DEBUG'
        Log    '${text}' -> '${normText}'    level=DEBUG    # KW code inline comment 2
        Log    '${text}' -> '${normText}'    level=DEBUG        # KW code inline comment after 1 empty cell
    END
    [Return]    ${normText}

No Doc
    [Documentation]    
    ...
    ...    # # char in KW documentation
    No Operation
```

**Comment by HelioGuilherme66** [comment]
@irapths Thanks for the report.
The # processing is at very low level, on the moment the file is read from the disk. This means that the separation in "cells" is not considering the context of where they are. The system does not know if inside a Documentation block or other.

Is this really a problem of having the continuing line marker (...) resolved to empty line? Did you get a warning of deprecation of empty (...) lines? (run the test in a cmd/shell/terminal).

As far as I can see this behavior is already existing since robot 3.1.2 (the base version RIDE uses).

**Comment by irapths** [comment]
Hello @HelioGuilherme66 and THANK YOU VERY MUCH about all the effort of maintaining RIDE

In my company we all use RIDE as main editor and execute Test from inside it and from command line (windows) and Jenkins (Linux), but never had any deprecation warning as you mention.
To be honest I'm not even aware of the deprecation of _continuing line marker (...) resolved to empty line_ inside the Documentation.

So I simplify the above example as bellow, in order to focus on the main issue.

**Code in file** (RIDE 1.7.4.2 running on Python 3.7.9)
```
No Doc
    [Documentation]    Doc
    ...    | A table with | # char |
    No Operation
```
**Code in editor** (RIDE v2.0b2.dev5 running on Python 3.7.9. )
```
No Doc
    [Documentation]    Doc    # char |
    ...    | A table with |
    No Operation
```
**Code in GUI documentation editor window** (RIDE v2.0b2.dev5 running on Python 3.7.9. )
```
Doc
| A table with |
```

I use dev version of RIDE v2.0 the last 1.5 years and since v2.0b2.dev4 I was created with it many RF files with lot of "empty documentation lines (...)", tables in documentations with '#' in them and use '#' as inline comment (in the very last cell of a code line).
I personally don't like/use '"' for code line comments and I prefer the "Comment" KW instead, but other Co-Workers do (all use the 2.0dev2 version).
(We try to remove ALL comments with '#' but needs lot of time and effort and we are not there yet)

Until yesterday (v2.0b2.dev4) all files were loaded as they were stored and any update was written/saved as it was seen in editor, in "documentation editor window" and "documentation field".

After updating to v2.0b2.dev5 I have to check for unwanted changes on files before every commit and revert them. I'm really OK with, for now, this since it is my choice to use dev versions of RIDE :-) , but this not disappears the issue.

**Comment by HelioGuilherme66** [comment]
@irapths Good that you risk to use the development version. It helps me detecting problems soon.

I am working on this # comments, because I need to fix indentation for nested FOR, and then for IF, WHILE and TRY/EXPECT.
The original RIDE always reformat content (on Text Editor), and there is no easy way to avoid that (only by using a "dumb" text editor, like the builtin CustomSourceEditor, with File->Open External File).

As for the deprecation warnings they may be shown in newer versions of `robot`. For this it is always good to add to Issues the initial output of Tools->View RIDE Log, for example:

```
20220217 11:46:47.992 [INFO]: Found Robot Framework version 5.0b1 from C:\Python39\lib\site-packages\robot.

20220217 11:46:47.994 [INFO]: Started RIDE v2.0b2.dev5 using python version 3.9.9 with wx version 4.1.1 in win32.
```

**Comment by irapths** [comment]
My bad I didn't include environment info
```
20220217 15:08:50.324 [INFO]: Found Robot Framework version 4.1.3 from C:\Users\GiannisRaptis\Apps\RobotFmw2\lib\site-packages\robot.

20220217 15:08:50.324 [INFO]: Started RIDE v2.0b2.dev5 using python version 3.7.9 with wx version 4.1.1 in win32.
```

I don't know if this help but I tried to disable the "Text Editor" and after restart I opened the same file with "Grid Editor".
The results were the same. Sting `    # char |` was not visible in "Documentation" area nor in "Documentation" editor window.
Any changes I make in Documentation are saved and the `    # char |` string continues to be on the end of 1st line.
If the new edit contains a part like ` # text` at the end it is visible and saved on save (checked with different editor), but after close/reopen RIDE and file it is not there - as the `    # char |` - but is appended at the end of 1st line.

To be completely clear, this issue is ONLY for the Documentation fields, not Code parts.

**Comment by HelioGuilherme66** [comment]
@irapths Please see if there was improvements on this area, in current development version 2.0b2.dev7.
(# in doc GUI still not visible) and (this is a keyword: `\# NOT KW code line comment because    # is escaped` )

**Comment by HelioGuilherme66** [comment]
@irapths Thanks. I'll see what I can do.

**Comment by HelioGuilherme66** [comment]
This is still happening on v2.0b2.

After saving original in RIDE, the comments move from steps to documentation (this is not acceptable):
- reformatted:
```
*** Settings ***
Documentation     Library contains Keywords to read configuration files    # # char in suite documentation \ \ \ # char in suite documentation \ \ \ # Suite documentation 'inline comment' \|
...
...               \| `Normalize Text` \|
...
...
...               \# Escaped
...
...               Examples:
...               \| ${text1} \| Normalize TextId \| Text \|
Resource          JSON_reader.resource    # Resource comment

*** Variables ***
${NoKeyError}     Error:NoKeyError    # Variable comment

*** Keywords ***
Normalize Text
    [Arguments]    ${text}    ${keepspaces}=${False}
    [Documentation]    Normalizes the given TextId    # # char in KW documentation \ \ \ # char in KW documentation \ \ \ # KW documentation 'inline comment' 1 \| \ \ \ # KW documentation 'inline comment' 2 \| \ \ \ # KW documentation 'inline comment' 3 \|
    ...
    ...
    ...    \# Escaped
    ...
    ...    Examples:
    ...    \| ${text1} \| Normalize TextId \| Text \|
    ...    \| ${text3} \| Normalize TextId \| \ \ text \ \ \|
    ...    \| ${text5} \| Normalize TextId \| te xt \| keepspaces=${True} \|
    ${normText}    Set Variable If    ${keepspaces}    1    2    # KW code inline comment 1
    # KW code line comment in single cell
    # \ \ \ KW code line comment with text in 2nd cell
    \# NOT KW code line comment because    # is escaped
    IF    '${LOG_LEVEL}' == 'DEBUG'
        Log    '${text}' -> '${normText}'    level=DEBUG    # KW code inline comment 2
        Log    '${text}' -> '${normText}'    level=DEBUG    # KW code inline comment after 1 empty cell
    END
    [Return]    ${normText}

No Doc
    No Operation
```

**Comment by HelioGuilherme66** [comment]
@irapths Can you please test from current master (2.0b3.dev2)?
