### ISSUE TITLE
Setup and Teardown tables corrupted after PR #2434

### ISSUE THREAD

**Issue by HelioGuilherme66** [robotframework/RIDE#2436]
A new bug has been introduced with this change (not present in previous 2.0b2.dev5) in the Test Case grid mode: Setup, Teardown, Template and Tags are not showing in their own fields in Settings but they are added in the Test Case grid as additional lines (see red rectangles in picture below); also, a blank column is added at the beginning of each line in the grid (see orange rectangle in picture below), corrupting all of them

Reverting to 2.0b2.dev4 again then

![image](https://user-images.githubusercontent.com/9963199/154448924-62278ffa-46b0-447a-b3c4-104ca221b872.png)

_Originally posted by @axiom41 in https://github.com/robotframework/RIDE/issues/2433#issuecomment-1042758294_

**Comment by axiom41** [comment]
Hi Hélio.
I just downloaded and tested the new RIDE v2.0b2.dev6 (running on Python 3.7.9 and Windows).
This issue seems resolved and now all the Tables work fine and grid is no more corrupted.

I think you can close also this one then.
