### ISSUE TITLE
RIDE freezes when try to edit an existing list or dictionary variable

### ISSUE THREAD

**Issue by irapths** [robotframework/RIDE#2438]
## The problem
RIDE freezes when try to edit an existing list or dictionary variable.
(via Edit and not via Text Edit)

## Steps to reproduce
1. Open an existing resource file
2. Use Editor UI
3. Create a new _List_ variable (OR a _Dictionary_)
   Result: The _List Variable_ pop-up window is visible (OR the _Dictionary Variable_)
4. Use a valid name
5. Add at least one item
6. Save the variable
7. Edit the created list (OR dictionary)

## Expected
* The _List variable_ pop-up window is visible (OR the _Dictionary Variable_)
* The list can be edited (OR dictionary)

## Actual result
* RIDE freezes

## Additional info
OS: Widows 10

RIDE log
```
20220318 16:46:42.298 [INFO]: Found Robot Framework version 4.1.3 from C:\Users\USER\Apps\RobotFmw2\lib\site-packages\robot.
20220318 16:46:42.298 [INFO]: Started RIDE v2.0b2.dev5 using python version 3.7.9 with wx version 4.1.1 in win32.
```

**Comment by HelioGuilherme66** [comment]
@irapths Please retest on new version 2.0b2.

**Comment by HelioGuilherme66** [comment]
Closing because of no response from author.
