### ISSUE TITLE
RIDE needs lot of time to finish "Find Usages" operation.

### ISSUE THREAD

**Issue by irapths** [robotframework/RIDE#2439]
## The problem
RIDE needs lot of time to finish "Find Usages" operation.

## Steps to reproduce
1. Open an existing project
2. Right click on a KW on the _Test Suits_ tree-view
3. Select _Find Usages_
  Result: Pop-up window for results of the operation opens
4. Wait until the operation finish
  Tip: Wait until the part **Searching ...** disappears from the window title
5. Check the needed time to finish

## Actual result
* The needed time in tested project is >2:30 minutes

## Additional info
RIDE 2.0b2.dev4 had the same issue but cannot didn't opened it then.
Using RIDE 1.7.4.2 on the same project the needed time is <15 seconds

The same issue exists on "Rename" operation (on RIDE v2.0b2.dev4 and not on v1.7.4.2) also.
I can open different ticket but I will wait from a maintainer info-feedback before do it since it seems to me that it uses the "Find Usages" operation under the hood.

OS: Windows 10
RIDE 2.0b2.dev5 log
````
20220318 16:46:42.298 [INFO]: Found Robot Framework version 4.1.3 from C:\Users\USER\Apps\RobotFmw2\lib\site-packages\robot.
20220318 16:46:42.298 [INFO]: Started RIDE v2.0b2.dev5 using python version 3.7.9 with wx version 4.1.1 in win32.
````

RIDE 1.7.4.2 log
```
20220318 17:09:08.810 [INFO]: Found Robot Framework version 3.2.2 from C:\Users\USER\Apps\RobotFmw\lib\site-packages\robot.
20220318 17:09:08.810 [INFO]: Started RIDE 1.7.4.2 using python version 3.7.9 with wx version 4.0.7.post2 in win32.
```

**Comment by HelioGuilherme66** [comment]
@irapths Please retest on new version 2.0b2.

**Comment by HelioGuilherme66** [comment]
Closing because of no response from author.
