### ISSUE TITLE
RIDE didn't show the resource files under a directory for few resource files

### ISSUE THREAD

**Issue by WarWolflll** [robotframework/RIDE#2440]
Hello, my issue is the same with issue #2422. I have created a project where I have a directory and I have added directories in it. But when I exit RIDE and re-open it, it only shows the parent directory and not the listing the resource files underneath.

My setup configuration:
robotframework                 4.1.3
robotframework-ride            2.0b2.dev5
wxPython                       4.1.1

**Comment by guyongqiangx** [comment]
I meet the same issue with below configuration:
robotframework 5.0.1
robotframework-ride 2.0b2.dev10
wxPython 4.1.1

I close the RIDE, try to use pycharm for edit some of the files, then re-open RIDE, no files there:

<img width="213" alt="1655974524(1)" src="https://user-images.githubusercontent.com/22298198/175259515-b9cd1504-5fc6-4bb5-a4f4-6d58fa231647.png">
<img width="203" alt="1655974552(1)" src="https://user-images.githubusercontent.com/22298198/175259613-c6597e03-5b02-4e7c-a3e8-0048dbf54533.png">
