### ISSUE TITLE
IF - Keyword was not detected by RIDE 

### ISSUE THREAD

**Issue by robtail** [robotframework/RIDE#2441]
Hi

"IF" -keyword was not found by RIDE. 
"IF" and ELSE Not in the help list (ctrl+space) and looks black if i type it into Edit.
![image](https://user-images.githubusercontent.com/77631362/160134889-2440806e-4dd0-4f29-9eb2-85d6865dce6d.png)

I have RIDE v2.0b1 running on Python 3.7.9.  along with this lib versions:
robot                              20071211
robotframework                     4.1.3
robotframework-pythonlibcore       3.0.0
psutil                             5.9.0

Please advise how to have recognised by RIDE.

Best Regards, 
Robert

**Comment by HelioGuilherme66** [comment]
Thanks for the report. This is a known fault, as the robotframework version for keywords identification is 3.1.2.

If I don't make a fix for the next release, then will go on 2.1.

**Comment by robtail** [comment]
Hi,
Thanks for all your effort to keep Ride alive!! :)
Best Regards, 
Robert
