### ISSUE TITLE
RIDE keyword search error

### ISSUE THREAD

**Issue by Northxw** [robotframework/RIDE#2449]
&emsp; Hello, when I use the search function of the RIDE development tool, an error occurs, as shown in the figure.

![image](https://user-images.githubusercontent.com/38708989/168714926-401e57bf-b673-40a5-a892-1904669fb82d.png)

&emsp; I have tried searching in Chinese, English, special characters, etc., no matter whether the keyword exists or not, the error log results are the same.

&emsp; Then I edited the file lib\site-packages\robotide\editor\texteditor.py and added a print. For example, when I go to search for the tools keyword in the TEST.robot file, the output looks like this:

![image](https://user-images.githubusercontent.com/38708989/168716750-ccefd200-b7ea-40a5-a3cf-60653b73a48d.png)

The contents of the TEST.robot file are as follows:
```
*** Settings ***

*** Variables ***

*** Test Cases ***

Use robot tools
    ${test_dict}    Create Dictionary    a=1    b=2
    log    ${test_dict}
    ${test_dict_res}    Get Dictionary Items    ${test_dict}
    log    ${test_dict_res}
```

The development environment information is as follows:
```
python3.8.10 64bit
Windows 10 21H1 64bit
```

The python dependency library is as follows:
```
Pypubsub==4.0.3
robotframework==5.0
robotframework-ftplibrary==1.9
robotframework-pythonlibcore==3.0.0
robotframework-ride==2.0b1
robotframework-selenium2library==3.0.0
robotframework-sshlibrary==3.8.0
wxPython==4.1.1
```

If you need the details of the environment, I can package it and send it to you, looking forward to your reply.

**Comment by HelioGuilherme66** [comment]
This is fixed in current development version.
From the [CHANGELOG](https://github.com/robotframework/RIDE/blob/master/CHANGELOG.adoc): `Fixed search in Text Editor with wxPython 4.1.0`
