### ISSUE TITLE
Cell edit with F2 not working in RIDE 1.7.4.2

### ISSUE THREAD

**Issue by robot-user-rudi** [robotframework/RIDE#2450]
When I'm using F2 key to edit a cell, cell color is changed to light yellow, but cursor is not positioned.
So pressing cursor left or right afterwards changes the cell instead of moving around in the cell.

This was working fine in RIDE 1.5.
I observe this on Python 2.7.13 as well as on Python 3.7.9.

**Comment by robot-user-rudi** [comment]
1st installation:
Windows Server 2008 R2
Python 2.7.13
Installed libraries:
Package                         Version
------------------------------- -----------
-ryptography                    3.3.2
bcrypt                          3.1.7
certifi                         2020.12.5
cffi                            1.14.4
chardet                         4.0.0
cryptography                    3.3.2
enum34                          1.1.10
idna                            2.10
ipaddress                       1.0.23
numpy                           1.16.6
paramiko                        2.2.1
Pillow                          6.2.2
pip                             20.3.4
prompt-toolkit                  2.0.10
pyasn1                          0.4.8
pyasn1-modules                  0.2.8
pycparser                       2.20
pycrypto                        2.6.1
Pygments                        2.5.2
PyNaCl                          1.4.0
PyPubSub                        3.3.0
python-ldap                     3.2.0
pywin32                         228
requests                        2.25.1
robotframework                  3.1.2
robotframework-debuglibrary     2.2.1
robotframework-pythonlibcore    2.2.1
robotframework-requests         0.8.0
robotframework-ride             1.7.4.2
robotframework-selenium2library 3.0.0
robotframework-seleniumlibrary  4.5.0
robotframework-sshlibrary       3.6.0
robotremoteserver               1.1
scp                             0.13.3
selenium                        3.141.0
setuptools                      28.8.0
six                             1.15.0
UNKNOWN                         0.0.0
urllib3                         1.26.3
wcwidth                         0.1.9
win-inet-pton                   1.1.0
wxPython                        4.0.7.post2

**Comment by robot-user-rudi** [comment]
2nd installation:
Windows Server 2012 R2
Python 3.7.9
Installed libraries:
Package                         Version
------------------------------- -----------
asn1crypto                      1.4.0
async-generator                 1.10
attrs                           21.4.0
bcrypt                          3.2.0
certifi                         2021.10.8
cffi                            1.15.0
chardet                         4.0.0
charset-normalizer              2.0.12
cryptography                    37.0.2
h11                             0.13.0
idna                            3.3
numpy                           1.21.6
outcome                         1.1.0
paramiko                        2.7.2
Pillow                          8.0.1
pip                             22.0.4
prompt-toolkit                  2.0.10
psutil                          5.9.0
pyasn1                          0.4.8
pyasn1-modules                  0.2.8
pycparser                       2.21
Pygments                        2.12.0
PyNaCl                          1.4.0
pyOpenSSL                       22.0.0
Pypubsub                        4.0.3
PySocks                         1.7.1
python-ldap                     3.3.1
pywin32                         300
requests                        2.27.1
robotframework                  3.2.2
robotframework-debuglibrary     2.2.2
robotframework-pythonlibcore    3.0.0
robotframework-requests         0.9.2
robotframework-ride             1.7.4.2
robotframework-selenium2library 3.0.0
robotframework-seleniumlibrary  6.0.0
robotframework-sshlibrary       3.8.0
robotframeworklexer             1.1
robotremoteserver               1.1
scp                             0.14.4
selenium                        4.1.5
setuptools                      62.1.0
six                             1.16.0
sniffio                         1.2.0
sortedcontainers                2.4.0
trio                            0.20.0
trio-websocket                  0.9.2
typing_extensions               4.2.0
urllib3                         1.26.9
wcwidth                         0.2.5
wheel                           0.37.1
wsproto                         1.1.0
wxPython                        4.0.7.post2

**Comment by HelioGuilherme66** [comment]
This is fixed in current development version.
From the [CHANGELOG](https://github.com/robotframework/RIDE/blob/master/CHANGELOG.adoc): `Changed moving to keyword definition to be with Ctrl-Click (keep Ctrl-B action)`
  `- To edit cell use F2 or Double-Click`
