### ISSUE TITLE
Wrong background color on commented lines

### ISSUE THREAD

**Issue by axiom41** [robotframework/RIDE#2452]
Hello.
Since a couple of dev releases (i'm currently using RIDE v2.0b2.dev8 on Windows environment, with Python 3.7.9), grid mode is showing a red background on commented lines for non-empty cells from the 4th one onwards:

![image](https://user-images.githubusercontent.com/9963199/168970882-b615e937-6568-4329-8bc9-c9229644ac2a.png)

**Comment by HelioGuilherme66** [comment]
@axiom41 Thanks for the report. This is known but lower priority (and there are more coloring problems in other cases like in indented blocks, WHILE, IF, ...).

**Comment by JFoederer** [comment]
Is there a central place where the known coloring issues are collected? I have also spotted two other, (not indentation related) issues and want to check if they are already known issues.

**Comment by HelioGuilherme66** [comment]
@JFoederer Maybe is better to create a new issue.

I know that there are some inconsistencies. For example the keywords use in Text Editor are always in red (or some other default).
