### ISSUE TITLE
Start buttons to run tests do not work in v2.0b2.dev9

### ISSUE THREAD

**Issue by axiom41** [robotframework/RIDE#2454]
Hello Hélio.
After updating RIDE to v2.0b2.dev9, both buttons to run/start (in top button menu and in Run tab) tests are not active anymore.
Also F8 is inactive.
I'm running RIDE on Win 10 with Python 3.7.9 x64

Reverted to v2.0b2.dev8

**Comment by HelioGuilherme66** [comment]
@axiom41 RIDE works perfectly when using **installed** older Robot Framework (for example 3.2.1). It was working on my testing because it works fine with the IDE (it sets PYTHONPATH to use provided lib/robot). The fix will be to ensure it uses the provided lib.

**Comment by HelioGuilherme66** [comment]
After all, the problem is that when launching with `pythonw.exe` the stdout window is not appearing like it used to. If we launch RIDE from a command window, it will work.

**Comment by axiom41** [comment]
Hi Hélio.
Yes, i tried launching RIDE from a cmd window and it worked. While waiting for a fix with pythonw.exe, i'll keep using this workaround.

Thanks again for your support.
