### ISSUE TITLE
FOR cycle corrupted when changing step value

### ISSUE THREAD

**Issue by axiom41** [robotframework/RIDE#2456]
Hi Hélio
In grid mode, i noticed that often, changing the step value in a "FOR - END" cycle, the entire content of the cycle is removed, as shown in the 2 attached pics. Undo with Ctrl-Z does not restore the cycle, so i have to reload the file without saving and make the change in text mode.
I'm on RIDE v2.0b2.dev10 (but issue was present also in previous versions), Win 10 and Python 3.7.9 x64

![image](https://user-images.githubusercontent.com/9963199/173758022-cd41ed0c-0b1d-4a59-b5fd-bfec70820f05.png)

![image](https://user-images.githubusercontent.com/9963199/173758124-7309da9b-4e37-49af-ba9e-c98f340beaf2.png)

**Comment by HelioGuilherme66** [comment]
Thanks, for the report.
I know, of this, and still trying to fix. This is because of indentation.

**Comment by HelioGuilherme66** [comment]
@axiom41 Unfortunately, the current master v2.0b2.dev12 still have this problem!!!!

This is a **BLOCKER** for next pre-release!!
