### ISSUE TITLE
Wrong indentation on FOR cycle (RIDE v2.0b2.dev11, text mode editing)

### ISSUE THREAD

**Issue by axiom41** [robotframework/RIDE#2460]
Hi Hélio.
After updating to v2.0b2.dev11, i noticed that, in text mode editing, keywords placed within a FOR/END cycle at "root" level were shifted by 4 additional extra spaces. Inner FOR/END cycles leave internal keywords with proper 4-spaces indentation.
This happens even just opening a file and extra indentation spaces are obviously saved after any modification.

Please check the before/after in the attached pics.
Reverting to v2.0b2.dev10

![image](https://user-images.githubusercontent.com/9963199/176194062-88a4816c-7717-45cc-9d02-c327056248c1.png)

![image](https://user-images.githubusercontent.com/9963199/176194179-3f130c03-3982-4edb-97f5-c19b93378c3c.png)

**Comment by axiom41** [comment]
Unfortunately they are also saved on file if any modification is made. If file is not saved, spaces are not added.

**Comment by HelioGuilherme66** [comment]
@axiom41 Can you come to our Slack? I would to like to chat with you :).

Do you have time to prepare a test case file (or test Suite) indentation of all the new blocks special keywords: FOR, IF, ELSE, ELSE IF, END, WHILE, CONTINUE, BREAK, TRY, EXCEPT. ?

Current dev version already support them, and only the first FOR have indentation problems. Still to fix some rows delete, insertions and undo/redo (take care with production test cases, you may lose FOR loops content).

**Comment by axiom41** [comment]
Hi Hélio.
Here is a "quick & dirty" file containing the various loops, just to test the RIDE behavior.
It seems that only FOR is affected by the "extra-indenting" and just at "root" level
[Loop01.zip](https://github.com/robotframework/RIDE/files/9002900/Loop01.zip)

Will try to join you on Slack

**Comment by axiom41** [comment]
Sorry, i closed by mistake
