### ISSUE TITLE
RobotFramework Installed but not recognized when 'robot --version' command ran

### ISSUE THREAD

**Issue by emadushe** [robotframework/RIDE#2461]
![image](https://user-images.githubusercontent.com/106224971/178070950-ce48a8aa-292d-49bf-921f-c8a13ddfd245.png)

**Comment by HelioGuilherme66** [comment]
@emadushe That is not a problem with RIDE, but with robotframework installation.

You must add to the PATH the (...)\python310\scripts where tools are installed.
