### ISSUE TITLE
Wrong argument hint color on multi-line statements

### ISSUE THREAD

**Issue by JFoederer** [robotframework/RIDE#2465]
Consider a keyword that takes exactly three arguments. When vertically aligning the arguments over multiple lines using the continuation ellipses (...), the argument hint colors the cells on the first line instead.
![image](https://user-images.githubusercontent.com/32476108/179055757-8f103815-7140-44bf-a18c-b12ea25a75fd.png)

**Comment by HelioGuilherme66** [comment]
This issue is related to #1978

**Comment by HelioGuilherme66** [comment]
@JFoederer This simple problem was really complicated to fix!
But finally it is done in v2.0.8dev5.

Here is a sample test suite:
[test_multiline_steps.robot.txt](https://github.com/robotframework/RIDE/files/12429071/test_multiline_steps.robot.txt)

**Comment by JFoederer** [comment]
Auch! Every now and then simple issues tend to do that. Wasn't expecting that on this one though. I'll be sure to give it a try.
