### ISSUE TITLE
Ride EDIT screen is blank

### ISSUE THREAD

**Issue by Nguyenvi1402** [robotframework/RIDE#2474]
![image](https://user-images.githubusercontent.com/67002344/185565527-678094b1-383b-415b-a575-8dc6d3a97b39.png)
 
python version 3.9.13

**Comment by Nguyenvi1402** [comment]
Can someone help me?

**Comment by HelioGuilherme66** [comment]
Maybe this helps: https://github.com/robotframework/RIDE/wiki/F.A.Q.#15--q-i-have-recently-installed-the-development-version-and-wxpython-420-since-then-the-grid-editor-appears-empty-or-faulty-how-to-fix

**Comment by zhangys1989** [comment]
I have the same problem

Ride open blank

my python version is 3.8.10\3..10\3.7.5
anyone can help me?

**Comment by HelioGuilherme66** [comment]
@zhangys1989 I labeled this Issue as bad issue report, because the creator does not mention what version of RIDE and wxPython is using.

For you and @Nguyenvi1402, if you are using wxPython 4.2.0, you can use the current development version of RIDE.

**Comment by zhangys1989** [comment]
> Can someone help me?



> @zhangys1989 I labeled this Issue as bad issue report, because the creator does not mention what version of RIDE and wxPython is using.
> 
> For you and @Nguyenvi1402, if you are using wxPython 4.2.0, you can use the current development version of RIDE.
python version is 3.8.10\3.10\3.7.5
wxPython 4.2.0
ride version is 2.0b1 and 1.7.4.2
I tested both versions, but they didn't work

**Comment by zhangys1989** [comment]
python version is 3.8.10\3.10\3.7.5
wxPython 4.2.0
ride version is 2.0b1 and 1.7.4.2
I tested both versions, but they didn't work

**Comment by zhangys1989** [comment]
@HelioGuilherme66 
python version is 3.8.10\3.10\3.7.5
wxPython 4.2.0
ride version is 2.0b1 and 1.7.4.2
I tested both versions, but they didn't work

**Comment by HelioGuilherme66** [comment]
@zhangys1989 Like I said, you must install the development version from `master` branch. See the README.adoc on this project Code page.

**Comment by zhangys1989** [comment]
@HelioGuilherme66 thank you very much
