### ISSUE TITLE
RIDE crashes whenever i try to remove any tag from a suite or test case and press enter

### ISSUE THREAD

**Issue by bajoriaraghav** [robotframework/RIDE#2487]
1. Open RIDE
2. Navigate to any test case or suite that has tags
3. Remove the tag and press enter
4. RIDE gets CRASH

It closes the RIDE terminal window as well and hence error could not be captured. Crash is easily reproducible

RIDE version : 1.7.4.2
ROBOT Framework version : 3.1.2
Python version : 3.7.9

**Comment by HelioGuilherme66** [comment]
@bajoriaraghav Software testers should know how to report issues. Missing essential information.

**Comment by bajoriaraghav** [comment]
@HelioGuilherme66 Updated the version details in the description.

**Comment by HelioGuilherme66** [comment]
Well, we had that Bug before and it was fixed. Maybe in the development version.
That version will not have maintenance.

You can try to install the current 2.0 Beta2.

I advise you to make a backup of your ~/.robotframework/ride or %APPDATA%\Robotframework\ride (in Windows) and install.

to upgrade:
`pip install -U --pre robotframework-ride`  

to install (maybe in a different python install, or virtualenv):
`pip install --pre robotframework-ride` 

RIDE will use whatever version of RobotFramework you have installed and in path, the one that `robot --version` is valid.

**Comment by bajoriaraghav** [comment]
@HelioGuilherme66 Thanks for the update
