### ISSUE TITLE
use python run case，invalid syntax，A screenshot error occurred

### ISSUE THREAD

**Issue by zhangys1989** [robotframework/RIDE#2489]
EDIT: Removed image for security reasons

Python 3.10.5
robotframework                  5.0.1
robotframework-appiumlibrary    1.6.3
robotframework-databaselibrary  1.2.4
robotframework-pythonlibcore    3.0.0
robotframework-ride             2.0b2.dev23
wxPython                        4.2.0

**Comment by zhangys1989** [comment]
@HelioGuilherme66 python run case,A screenshot error occurred

**Comment by HelioGuilherme66** [comment]
@zhangys1989 This is not related with RIDE.

You are trying to run a robot test with a call to python.
