### ISSUE TITLE
Cursor jumps to the begining of the already typed words when pressing CTRL+SPACE

### ISSUE THREAD

**Issue by Futhark1988** [robotframework/RIDE#2491]
1. Open RIDE
2. Navigate to any test case or suite
3. Go to the Text Edit view
4. Start typing a keyword e.g Get
5. Press CTRL+SPACE

**Current result:**
The list of possible keywords are shown, but the cursor jumps to the begining of the keyword. This is unfortunate as one might start typing again to narrow down the list of possible keywords further, but as the cursor jumps to the begining of the word the typing is continued BEFORE the already typed word, thus messing up the search and input.

**Expected result:**
The cursor should remain at the end of the already typed word (e.g. Get), as there can be several keywords with the same begining and typing the next word should narrow down the list of possible keywords.

**RIDE version** : v2.0b2
**ROBOT Framework version** : 5.1b1
**Python version** : 3.10.6
**OS**: Windows 11 Home 21H2
**wxPython**: 4.2.0

**Comment by HelioGuilherme66** [comment]
@Futhark1988 Please try the new v2.0.7 where I did some changes in the autocomplete.

It is not perfect, but the cursor position will remain before the existing keyword, but this is needed for the replacing with the new content.

When you call the autocomplete in an empty space, you can type for refining the search.

Now, when we have existing library prefixes, for example like `SeleniumLibrary.` that content will be kept.

**Comment by HelioGuilherme66** [comment]
@Futhark1988 This is now fixed in current development version, v2.0.8dev20.
