### ISSUE TITLE
Skip and Skip If Keywords Crashing in  robotframework-ride==2.0b1

### ISSUE THREAD

**Issue by keshavvprabhu** [robotframework/RIDE#2492]
Skip and Skip If causes RIDE to crash. It runs fine on CLI without any issues. 

RobotFramework Version : robotframework==5.0.1
RIDE Version: robotframework-ride==2.0b1
Python : 3.7 (64 bit)

![image](https://user-images.githubusercontent.com/17060111/192342367-58766ba3-d436-4ca9-9e97-c56110a39891.png)

Error Observed:

  File "D:\workspace\py37\lib\site-packages\robotide\contrib\testrunner\TestRunnerAgent.py", line 260, in _send_socket
    self.filehandler.flush()
  File "C:\Users\kesha\AppData\Local\Programs\Python\Python37\lib\socket.py", line 607, in write
    return self._sock.send(b)
ConnectionAbortedError: [WinError 10053] An established connection was aborted by the software in your host machine

From CLI it works fine:
![image](https://user-images.githubusercontent.com/17060111/192342636-bd1b2120-fb69-4806-91d2-87254dbad82a.png)

**Comment by HelioGuilherme66** [comment]
@keshavvprabhu This was fixed in current v2.0b2.
Please upgrade RIDE with:
```
pip install -U --pre robotframework-ride
```
