### ISSUE TITLE
Creating testcases dynamically through prerunmodifiers does not work when using RIDE

### ISSUE THREAD

**Issue by tlietz** [robotframework/RIDE#2495]
In a suite, I have multiple testcases.

I am trying to dynamically create a testcase, `Last_Tc`, with a prerunmodifier that will always run as the last testcase no matter which tests I select to run in RIDE.

With the following code, `Last_Tc` does not run when executing my tests from RIDE. I think it has something to do with the mechanism that RIDE uses to skip testcases in a suite that are not checkmarked. 

```python
from robot.api import SuiteVisitor

class RerunTests(SuiteVisitor):

    def __init__(self):
        pass

    def start_suite(self, suite):
        tc = suite.tests.create(name='Last_Tc', doc=...)
        tc.body.create_keyword(name='Log', args=['I go last'])
```

Is this expected behaviour? If so, how can I make it so that RIDE always executes `Last_Tc`?

**Comment by JFoederer** [comment]
I have been successfully modifying test suites at run time, and have also been running them from RIDE. The tree view in RIDE will only report its check marks on test cases that were there at the start, but the reports show all the new and moved test cases as well.

A difference might be that I was using the [listener interface](https://robotframework.org/robotframework/latest/RobotFrameworkUserGuide.html#toc-entry-588). Capturing the suite from the `start_suite` method.

**Comment by tlietz** [comment]
Using the [listener interface](https://robotframework.org/robotframework/latest/RobotFrameworkUserGuide.html#toc-entry-588) works
