### ISSUE TITLE
AttributeError: 'CodeEditorPanel' object has no attribute 'CodeModules'

### ISSUE THREAD

**Issue by zhuyu4839** [robotframework/RIDE#2496]
RIDE Version: 2.0b2
RF Version: 6.0rc2
wxPython Version: 4.1.1

Traceback (most recent call last):
  File "...\robotide\editor\customsourceeditor.py", line 702, in OnRadioButton
    if modSelected != self.CodeModules.GetActiveID():
AttributeError: 'CodeEditorPanel' object has no attribute 'CodeModules'
Error in atexit._run_exitfuncs:
wx._core.wxAssertionError: C++ assertion "GetEventHandler() == this" failed at ..\..\src\common\wincmn.cpp(470) in wxWindowBase::~wxWindowBase(): any pushed event handlers must have been removed

**Comment by HelioGuilherme66** [comment]
Closing because it is not something we can reproduce.
