### ISSUE TITLE
[Issue Loading Test Data][Ride Robot[v.1.7.4.2][Mac OS Catalina]

### ISSUE THREAD

**Issue by fawziridwan** [robotframework/RIDE#2498]
Hi @HelioGuilherme66  kindly help to fix this issue, i tried to run Ride on Mac OS Catalina, but have loading test data on +- 2 minutes/still loading, i am using 

Requirement install on my Device
- Python 3.6.8
- pip
- robot framework (v.4.1.3)
- RIDE (v.1.7.4.2)
- SeleniumLibrary v4.1.0
- Webdriver (chromedriver untuk chrome)
- gherkin2robotframework 0.3

<img width="1680" alt="image" src="https://user-images.githubusercontent.com/17183383/198500872-60fccdd9-25d2-4cdf-82fe-31b29141910f.png">

**Comment by fawziridwan** [comment]
Hit all, this issue was solve, i am using other version Ride 1.7.4b2, and working fine.

**Comment by HelioGuilherme66** [comment]
@fawziridwan You are doing things wrong. Using an older version of RIDE is not the solution.
You did not selected a test suite, but you instructed RIDE to search from the root of your Mac disk. Of course it will take time.
.
