### ISSUE TITLE
[ ERROR ] Suite 'x' contains no tests matching name 'xxx'

### ISSUE THREAD

**Issue by Northxw** [robotframework/RIDE#2499]
Hi @HelioGuilherme66, when I execute a single test case on the command line, it prompts that the test case does not exist in the test suite, as the picture shows：

![2FEAB4CA-C21D-467c-A61E-A2480AD78E42](https://user-images.githubusercontent.com/38708989/198548033-ca5a52d5-e56a-4a99-b733-9309c32abc71.png)

Then, when I started the RIDE development tool, I found that the Route test suite was recognized as a configuration file.

![Snipaste_2022-10-28_17-01-20](https://user-images.githubusercontent.com/38708989/198548667-c5afc532-a623-47db-93e4-e3c1bf2da4bd.png)

Google solution, the reason for the problem given by someone is: when the robot test suite was created at the beginning, the file format was txt, which can be solved by modifying it to Robot format. Then right-click to select "Change Format" to modify it to Robot format, but the problem remains exist.

Next, I think that the problem may be caused by the special name of the Route, but it still doesn't help after changing it to another name.

![2022-10-28 171116](https://user-images.githubusercontent.com/38708989/198550776-be2ea93f-8fa5-46e4-b710-c11d6d821d57.png)

![5190B9A1-7692-4da2-8B41-847C15467E21](https://user-images.githubusercontent.com/38708989/198551254-61dced4b-e5f6-4f43-a692-a5c18d1650c0.png)

Next I tried to fix it by copying the PPPOE test suite and then renaming it to the Route test suite, to no avail.

The robot framework has not been studied in depth, and I have less experience. I can't think of other solutions. I hope to solve or answer it. Thank you very much.

---

The robot test files and environment information are listed below:

1. **Route.robot**. the variable information such as `${client1_ip}` `${fw_if1}` in the file comes from the resource files Common.robot and UK_Route.robot.
```python
*** Settings ***
Resource          ../Resources/Common.robot
Resource          ../Resources/UK_Route.robot

*** Variables ***
${TRACERT_TIMEOUT}    10

*** Keywords ***
Route_Config_001
    [Documentation]   
    [Tags]    static-route    config    reboot
    ${add_correct_route_use_multipath_1}    Set Variable    \nip static-route 1.1.1.1 32 multipath gateway ${client1_ip} gateway ${client2_ip} gateway ${server1_ip} gateway ${server2_ip} interface ${fw_if1} interface ${fw_if2} interface ${fw_if3} interface ${fw_if4}
    ${add_wrong_route_use_multipath_1}    Set Variable    \nip static-route 1.1.1.1 32 multipath gateway ${client1_ip} gateway ${client2_ip} gateway ${server1_ip} gateway ${server2_ip} interface ${fw_if1} interface ${fw_if2} interface ${fw_if3} interface ${fw_if4} interface ${fw_if0}
    ${add_wrong_route_use_multipath_2}    Set Variable    \nip static-route 1.1.1.1 32 multipath gateway ${client1_ip} gateway ${client2_ip} gateway ${server1_ip} gateway ${server2_ip} interface ${fw_if1} interface ${fw_if2} interface ${fw_if3} interface ${fw_if4} gateway ${client1_vm_eth}
    ${show_multipath}    Set Variable    \nshow running-configuration | grep multipath
    Comment    Step 1: Configure an equal-cost route that includes gateway and interface and satisfies the number of specifications
    ${fw_conn}    Connect    ${dev3_info[0]}
    Run Keywords    Write    \nconfig
    ...    AND    Sleep    ${MINIMUM_TIME}
    Write    ${add_correct_route_use_multipath_1}
    ${output}    Read    delay=${DEFAULT_TIME}s
    Should Not Contain    ${output}    Error    ignore_case=True
    Write    ${show_multipath}
    ${output}    Read    delay=0.5s
    Should Contain    ${output}    ${fw_if1}    ${fw_if2}    ${fw_if3}    ${fw_if4}
    Should Contain    ${output}    ${client1_ip}    ${client2_ip}    ${server1_ip}    ${server2_ip}
    Comment    Step 2: Configure two wrong equal-cost routes that contain gateway and interface but do not meet the specified number
    Write    ${add_wrong_route_use_multipath_1}
    ${output}    Read    delay=0.5s
    Should Contain    ${output}    Error    ignore_case=True
    Should Contain    ${output}    Too many parameters
    Write    ${add_wrong_route_use_multipath_2}
    ${output}    Read    delay=0.5s
    Should Contain    ${output}    Error    ignore_case=True
    Should Contain    ${output}    Too many parameters
    Comment    Step 3: Save the configuration and restart the device
    Reboot And Wait Firewall
    Comment    Step 4: View Equal Cost Routing Configuration
    ${fw_conn}    Connect    ${dev3_info[0]}
    Run Keywords    Write    \nconfig
    ...    AND    Sleep    ${MINIMUM_TIME}
    Write    ${show_multipath}
    ${output}    Read    delay=0.5s
    Should Contain    ${output}    ${fw_if1}    ${fw_if2}    ${fw_if3}    ${fw_if4}
    Should Contain    ${output}    ${client1_ip}    ${client2_ip}    ${server1_ip}    ${server2_ip}
    [Teardown]
```
2. Environmental information.
```text
Windows10 21H1 19043.2130
Python3.8.10
Cmder 210912 stable
```
![2022-10-28 172633](https://user-images.githubusercontent.com/38708989/198554089-b7e655b7-edff-49d3-a783-36b8b092676b.png)

Please let me know if you need any other info, it would be greatly appreciated.

**Comment by HelioGuilherme66** [comment]
When you run the test in a terminal and get an error, it confirms that it is not a bug in RIDE.
This is the kind of question you should have asked in our Forum.
From the error you show in terminal there is no test case with that name. This could make you wonder, what tests are there then?
You shoul have tried to run the Route.robot without any selection option.

Looking to the Test Suites tree, we see that Route.robot appears grayed. This and the fact it shows the file extension, indicates that it is not used in ant test suite. Also, the missing test execution checkboxes and the cogwheel icons, indicates they are Keywords and not Test Cases.

Probably the initial use of the file was as Resource. If you like to go that way, I recommend to change the extension to .resource .

Other alternative is to change the section *** Keywords *** to *** Test Cases ***.

**Comment by HelioGuilherme66** [comment]
You can upgrade RIDE to 2.0b2. See the ReadMe file.

**Comment by Northxw** [comment]
> When you run the test in a terminal and get an error, it confirms that it is not a bug in RIDE. This is the kind of question you should have asked in our Forum. From the error you show in terminal there is no test case with that name. This could make you wonder, what tests are there then? You shoul have tried to run the Route.robot without any selection option.
> 
> Looking to the Test Suites tree, we see that Route.robot appears grayed. This and the fact it shows the file extension, indicates that it is not used in any test suite. Also, the missing test execution checkboxes and the cogwheel icons, indicates they are Keywords and not Test Cases.
> 
> Probably the initial use of the file was as Resource. If you like to go that way, I recommend to change the extension to .resource .
> 
> Other alternative is to change the section *** Keywords *** to *** Test Cases ***.

Thank you very much for pointing out the problem.
