### ISSUE TITLE
Change the style for the client

### ISSUE THREAD

**Issue by ANemo-yj** [robotframework/RIDE#2503]
If I can change the client's custom style? If you can what documents should I modify?
For example, I want to change the appearance of some icon should I change?
![image](https://user-images.githubusercontent.com/58975405/201303160-de2fba79-157d-48e7-a5fe-8768d678bcf2.png)

**Comment by HelioGuilherme66** [comment]
This is an advantage of being open source software and interpreted language. You can change the files in the `widgets` directory on the installation of RIDE.
