### ISSUE TITLE
Extremely slowness to run a single test case in Ride v2.0b3.dev1 running on Python 3.9.6. 

### ISSUE THREAD

**Issue by preeram8** [robotframework/RIDE#2504]
Iam using Ride version v2.0b3.dev1 running on Python 3.9.6.  I upgraded python version from 3.7 to 3.9 and had to install the new version of RIDE as well. Now i see extreme slowness in running single test case, It takes 35 mins to run a single case which used to take less than a min in the older version.

**Comment by HelioGuilherme66** [comment]
That is really strange, because execution does not depend much on RIDE, but on Robot Framework.
@preeram8 Paste here to top of RIDE>Tools>View RIDE Log, and also the output of a command window/terminal/shell: `robot --version`.

**Comment by preeram8** [comment]
Here is Ride Log:
20221129 00:00:35.931 [INFO]: Found Robot Framework version 6.0.1 from C:\Users\pr0366\AppData\Local\Programs\Python\Python39\lib\site-packages\robot.

20221129 00:00:35.931 [INFO]: Started RIDE v2.0b3.dev1 using python version 3.9.6 with wx version 4.1.1 in win32.

20221129 00:00:35.931 [INFO]: Found Robot Framework version 6.0.1 from 

Robot Version from cmd promt:
C:\Users\pr0366\AppData\Local\Programs\Python\Python39\lib\site-packages\robot.

20221129 00:00:35.931 [INFO]: Started RIDE v2.0b3.dev1 using python version 3.9.6 with wx version 4.1.1 in win32.

**Comment by HelioGuilherme66** [comment]
From a cmd window:
`robot --version`

**Comment by HelioGuilherme66** [comment]
Closing because of no response from author.
