### ISSUE TITLE
RIDE not opening with ride.py command , but launch correctly when user have desktop shortcut for RIDE

### ISSUE THREAD

**Issue by SonalD98** [robotframework/RIDE#2507]
I was opening RIDE editor using ride.py command but recently it's not working, giving below error:
Traceback (most recent call last):
  File "C:\Program Files\Python37\Scripts\ride.py", line 21, in <module>
    from robotide import main
ModuleNotFoundError: No module named 'robotide'

But my other colleague have RIDE desktop shortcut, they are able to open RIDE from there.
Please help.

**Comment by JFoederer** [comment]
As by the [FAQ](https://github.com/robotframework/RIDE/wiki/F%2eA%2eQ%2e), on Python 3.7 one can use `python -m robotide.__init__`

**Comment by HelioGuilherme66** [comment]
>using ride.py command but recently it's not working
What was the "recently" change in your system?
Did you installed other Python version?
What version of RIDE you use? Some details about versions is important, but first try to understand what was the change.

**Comment by SonalD98** [comment]
@HelioGuilherme66 @JFoederer Thanks for your quick response.
Able to launch Ride with command python -m robotide.__init__

**Comment by HelioGuilherme66** [comment]
@SonalD98 Try to edit the desktop shortcut, so it uses the working command.
