### ISSUE TITLE
Make Ctrl-Shift-3 or 4 to insert or remove  '#  ' comments

### ISSUE THREAD

**Issue by HelioGuilherme66** [robotframework/RIDE#2508]
- When do Ctrl-Shift-3, to insert '# ' on the cursor position, or at left of the word if on it
- When do Ctrl-Shift-4, to remove each '# ' starting from left
- The same for Grid Editor, but with cell as reference

Note: It is #\<SPACE\> to add or remove

**Comment by Harm10** [comment]
For the first editor the Text editor Tab is meant? If so why are the existing options like Ctrl-2 not in the right click menu? 

"to insert '# ' on the cursor position, or at left of the word if on it" what is meant by "at left of the word if on it"? Please explain by using an example

 "to remove each '# ' starting from left" in the text editor is meant for the while until the cursor location?

**Comment by Harm10** [comment]
@HelioGuilherme66 Did you notice my questions?

**Comment by HelioGuilherme66** [comment]
@Harm10 Yes I did.

The feature is for both editors.
Examples of commented lines, where ^ means the cursor position:
```
# Log    #this is not a comment    HTML^
```
(comment) Would result in:
```
# Log    # this is not a comment    # HTML^
```
(uncomment) Would result in:
```
Log    # this is not a comment    # HTML^
```
(uncomment) Would result in:
```
Log    this is not a comment    # HTML^
```
(uncomment) Would result in:
```
Log    this is not a comment    HTML^
```
From:
```
Log    this is not a co^mment    HTML
```
(comment) Would result in:
```
Log    # this is not a comment    HTML
```

- When adding #, also add a space
- When removing #, also remove a space if exists and does not change cell separation
- When adding #, consider first leftmost pos of cell at cursor (cell are spaces separated by the setting in Preferences->Save)
- Feature must consider Blocks comment and uncomment (see the Comment code and unit tests)

To discuss:
- When removing #, should start from leftmost cell (start of line), or from start of cell nearest to cursor?
-

**Comment by Harm10** [comment]
You forgot to answer "If so why are the existing options like Ctrl-2 not in the right click menu?" 
This is the texteditor.py file. Ctrl-2 is active but not mentioned.

**Comment by Harm10** [comment]
I have some weird behavior on the editor that is interfering with my testing (code is almost ready).
If I create a TC like this
![afbeelding](https://user-images.githubusercontent.com/1517188/209406283-eb2a58f7-65f9-4e8b-a0e6-4596ce47fafa.png)
which looks like this in the text editor
![afbeelding](https://user-images.githubusercontent.com/1517188/209406316-73ddd0a8-22cd-4deb-b13c-bab45369bd3d.png)
and save the lot, exit RIDE and restart the TC looks like this:
![afbeelding](https://user-images.githubusercontent.com/1517188/209406349-2125cea0-b617-4865-8e48-90426d27419b.png)
and in the text editor:
![afbeelding](https://user-images.githubusercontent.com/1517188/209406376-c7e9b758-d52d-4fae-8af4-2b9610808999.png)

It is essential to exit RIDE to see this behavior. Is there some prettifying process active when RIDE starts?
Is this is a (known) bug?

**Comment by HelioGuilherme66** [comment]
This is a known behavior (for now). The spaces escaping happens at read moment. It is annoying when we uncomment because the escapes are not removed. This is one of the many things to fix in the future.

**Comment by Harm10** [comment]
OK. Should I take this behavior into account? Currently I use the tab_size to discern the different cell contents in the text editor. If these escapes are there everything is considered as one cell (as the grid editor now does).

**Comment by Harm10** [comment]
What is the procedure for Review? Just create a PR?

**Comment by HelioGuilherme66** [comment]
Yes, just create the PR.

**Comment by Harm10** [comment]
I created new [PR](https://github.com/robotframework/RIDE/pull/2510). I hope I followed the process correctly now.
I also closed the previous PR as it made it impossible for me to create this new PR.

**Comment by HelioGuilherme66** [comment]
The correct procedure would be to create a new branch and make the PR from there. These are the steps you should have done (just for future reference):

1. git checkout master
2. git checkout -b thenewbranch
3. git rebase -i 336962567186ba69ab573d9077143bad2503ad4f    # drop the changes done
4. # You now have a branch with the same commit as original master
5. # You could have kept the changes in your local master
6. git commit -a -m "This is a message about the changes done"
7. git push origin thenewbranch
8. # A link to create Pull Request could be shown

**Comment by Harm10** [comment]
I do not work with git console! I told you so already. And I will not start to do so. Only work with Github and VSCode and its Command template.

My sequence:
1. Created fork from RIDE Dev on Github = my master
2. Created branch from that master called development on Github
3. Cloned these 2 in VSCode
4. Worked on development and committed my changes
5. Merged those into my master after first syncing that
6. Created a PR from that master

What can I change to give you a PR you can work with? Again I will not work with direct git commands.

**Comment by HelioGuilherme66** [comment]
You should not do:
>5. Merged those into my master after first syncing that

The PR should be done from the `development` branch.
You should only Pull to master after PR have been merged (or sync with upstream project).

**Comment by Harm10** [comment]
OK. Shall I redo the PR?

**Comment by HelioGuilherme66** [comment]
@Harm10 In Grid editor when we select several cells, it should **Insert** `# ` in the leftmost selected.
If multiple rows, all leftmost cells should have inserted `# `.

Grid Editor, has three modes of cell "selection":
- Navigation, where the cell is only outlined
- Selection, where the cell is highlighted
- Edition, where the content can be changed

For the remove # function, when in Edition or Navigation, removes the `#` or `# `, from the cell "selected" or next on the left (for each Ctrl-Shift-4, until the beginning of the row).
For the Selection, removes all `#` or `# ` from each beginning of rows. If the Selection is kept (a goal not attained in Text Editor), then continue removing from leftmost to rightmost (on each Ctrl-Shift-4 stroke).

**Comment by Harm10** [comment]
I will have a new look at this now I understand the sharp commenting logic better.

**Comment by HelioGuilherme66** [comment]
Completed with minor deviations from requirements. Unit tests not done.
