### ISSUE TITLE
Make all Keyboard shortcuts common between Grid and Text Editors.

### ISSUE THREAD

**Issue by HelioGuilherme66** [robotframework/RIDE#2512]
For example:
[x] Ctrl-1 to 5 were missing on Text Editor. 
[x] Ctrl-T is missing in Grid Editor.
[x] Ctrl-D, Ctrl-I are missing in Text Editor.

**Comment by Harm10** [comment]
I first concentrated on getting the same options in the Grid Editor and Edit pull down menu. I also rearranged their sequences to get the same on both. I also looked at the menu for row number select.

I have some trouble in understanding the key registrations in the texteditor. Ctrl-T is active there but where is this set and where is the code? I cannot find it in texteditor.py
And what is Ctrl-T compared to Alt-up and Alt-down? Those Alt codes are not active in texteditor. To me Ctrl-T seems to be superfluous and should be replaced by Alt-up like used by the grid editor. Swap a row is the same as move the current row up?

Also already the report that shortcut Alt-space for Content Assist does not work properly in the grid editor (Ctrl-space does work properly).
I also find sometimes 3 different key bindings for this.
So the question first is: which key shortcuts should start Content Assist?
Perhaps handling all Content Assist logic should go into another issue?

The texteditor has shortcut Del commented out. Is this with reason?

**Comment by HelioGuilherme66** [comment]
>Ctrl-T is active there but where is this set and where is the code? I cannot find it in texteditor.py
We do not set it. It is by default from scintilla (stc) library. For example, just try it on Notepad++ :)
I'd like to have it in Grid Editor, just to be equal to Text Editor.

There is a small difference on Ctrl-T  versus Alt-Up, the cursor remains in the same position. In Grid Editor, Alt-Up, keeps the whole moved row highlighted.
Of course that Alt-Up/Down are priority key actions to implement in Text Editor.

Alt-Space works on Text Editor but not in Grid Editor. Text should be corrected to Ctrl-Alt-Space for Grid Editor. Text is correct for Tools->Content Assist.
(this combination existed in the past, but can not be used in Windows and Mac)

There was a time that Del was needed in Windows. Also I did try to implement in Mac, but that key does not exist in Mac keyboards.

**Comment by Harm10** [comment]
OK. Will try to add Ctrl-T in grid editor, row display menu and Edit menu. Also Alt-up/down in text editor.

Btw Is there a way to influence the right click menu on Text editor? It only displays the default (Windows?) settings currently I feel.

Alt-Space is active in Grid editor but displays content assist and some pull down menu in the upper left corner. Please tell me what key combination should activate Content Assist. In grid editor you can use Ctrl-Space, Ctrl-Alt-Space and Alt-Space. The latter has that weird side effect I described.

I will leave the Del commented in text editor?

**Comment by HelioGuilherme66** [comment]
>Btw Is there a way to influence the right click menu on Text editor? It only displays the default (Windows?) settings currently I feel.

We would need to make our own menu and join the default. Not important for now.

Leave Ctrl-Space and Ctrl-Alt-Space as is for Grid Editor, only the Help->Shortcuts keys needs to be corrected.

Yes, commented code, ("dead code")  is to remain as is, for now.

Please try to make PR, only for Grid Editor and other for Text Editor. We should try to have small PR and with fewer files modified.

**Comment by Harm10** [comment]
Will you create a new issue for Text editor menu so it will not be forgotten? Or do I have that authorization myself?

Content Assist: so I will remove Alt-Space from the Grid editor?

What do you mean with: "only the Help->Shortcuts keys needs to be corrected"

I will try to do 2 PR's. The grid editor will also include the Edit pull down menu as it is activated by clicking on a cell.
(My days off have finished so I have to do real work again.... :-)  So my "speed" will become lower.

**Comment by Harm10** [comment]
@HelioGuilherme66 Can you please answer my questions?

**Comment by HelioGuilherme66** [comment]
@Harm10 
Only need to update the  he Help->Shortcuts keys content to have Ctrl-Alt-Space for Grid Editor.
Specifically, line 163 of file ` src/robotide/context/__init__.py`  must be changed to:
```
        <td>Ctrl-Space or Ctrl-Alt-Space</td>
``` 

Leave code as is.

**Comment by Harm10** [comment]
Created a PR for the grid editor related files: https://github.com/robotframework/RIDE/pull/2513

**Comment by Harm10** [comment]
@HelioGuilherme66 Can I continue working on my branch or should I better wait for you to process the PR?

**Comment by HelioGuilherme66** [comment]
I am processing the PR. You should create a branch per PR, and then don't do more modification on it.

**Comment by Harm10** [comment]
Could you please also have a look at the comments I made on yours in the PR? Part of this issue was, in my view, also displaying the short cuts in the same ORDER in the Edit pull down menu and the Cell right click menu. Or was this irrelevant? I am a person of details......... :-)

**Comment by HelioGuilherme66** [comment]
@Harm10 This is not big deal. I saw you made the order of menu items consistent, and that is how it should be. Let's leave this how it is.

**Comment by Harm10** [comment]
I made an inventory of shortcuts missing from the Text editor.
As there are more than I thought perhaps we should try to add them through different PR's?

Missing are:
Alt-Up (Move rows up)
Alt-Down (Move rows down)
Ctrl-I (Insert rows)
Ctrl-D (Delete rows)

Ctrl-Shift-V (Paste text as a new row)

Alt-Enter (Move cursor down)
Ctrl-Shift-I (Insert cells)
Ctrl-Shift-D (Delete cells)

Can you specify what should be added right now and what later (or perhaps should not be added at all)?
I assume the first 4 are the most important in light of the type of editor?
