### ISSUE TITLE
Issues with clearing suite/test setup/teardown from grid editor

### ISSUE THREAD

**Issue by JFoederer** [robotframework/RIDE#2540]
It is not possible to, from the grid editor, see the difference between an empty setup or a removed setup. You can get an empty setup when editing and clearing all characters from the keyword field. Because a test setup at test case level overrules the test setup from test suite level, this can result in unexpected behavior, when the (empty) test setup is executed instead of the intended one. You cannot spot the mistake (empty test setup keyword) from the grid editor. It looks the same as after clicking the _Clear_ button, which removes the setup all together.

Also the clear buttons do not sync properly with the text editor. The text and grid editors are supposed to be kept in sync, but this does not happen when using the clear buttons from the grid editor. Switching to the text editor after using _Clear_ from the grid editor, still shows the cleared item in the text view.

**Comment by HelioGuilherme66** [comment]
This will be fixed in 2.0.1.dev3
