### ISSUE TITLE
can‘t open RIDE

### ISSUE THREAD

**Issue by Miago123** [robotframework/RIDE#2543]
From the Tools menu open Manage Plugins, and then disable all options，and reopen.
Now I can’t open RIDE，how can I fix it？

**Comment by Miago123** [comment]
reinstall is not useful……

**Comment by HelioGuilherme66** [comment]
@Miago123 
You should have used other "support" means, like Forum or Slack.

If you don't mind losing settings, like TestRunner execution filters or arguments, or colors definitions, you can delete the file `settings.cfg` or even the robotframework/ride directory (losing also libraries documentation help).

More info is in the Wiki or F.A.Q.

**Comment by Miago123** [comment]
thanks

**Comment by Miago123** [comment]
where is the settings.cfg？

**Comment by Miago123** [comment]
![image](https://user-images.githubusercontent.com/125736314/219865690-cc965afc-8977-4008-a7c5-b0cfc19af2dd.png)
it seems not useful？

**Comment by Miago123** [comment]
![image](https://user-images.githubusercontent.com/125736314/219867111-89a80aa8-c75e-4f56-9462-4bdcd6a0875d.png)

**Comment by HelioGuilherme66** [comment]
@Miago123 You are looking at source code.
You should look to your user settings. There is a section on the Wiki, really easy.

**Comment by Miago123** [comment]
where is the Wiki？How？I've never used it……

**Comment by Miago123** [comment]
a~~thank you~~when I delete all the files under path  %APPDATA%\RobotFramework\ride ,it's works,thanks~
![image](https://user-images.githubusercontent.com/125736314/219937831-a4a36e64-5dc8-43b0-a7ba-b71c612dd96e.png)
![image](https://user-images.githubusercontent.com/125736314/219937846-852820f3-dcdd-4246-aea5-42e3a8c316c0.png)
