### ISSUE TITLE
Source codes modified by other text editors are not detected by RIDE 2.0

### ISSUE THREAD

**Issue by sfdcselenium01** [robotframework/RIDE#2557]
When codes are modified in other text editors, RIDE 2.0 failed to detect the changes and still keep old version of codes.

RIDE: 2.0
Python: 3.8.10
OS: Windows 10

**Comment by HelioGuilherme66** [comment]
Please describe how to reproduce.
- Using a local disk drive?
- With a single Test Case file opened?
- With a directory of Test Suites opened?
- Was a change in an existing file inside the opened directory or Test Case file?

- Try to do the change but with RIDE minimized.

**Comment by sfdcselenium01** [comment]
1. When RIDE open directory where robot framework project is located
2. In the same time, open any robot framework files under the same directory, and modify the file using text editor like Notepad++ or VS Code, and save the changes

In old version v1.7.4.2, RIDE will detect any changes under its open directory, and dialog will popup to ask for reloading, so modified files will be reloaded into RIDE

However, RIDE 2.0 fails to detect any changes in its open directory. I have to exit RIDE and reopen the directory, then the modified files can be reloaded into RIDE
