### ISSUE TITLE
Sharp commented lines with multiple cells get tab translated to \ \ \ 

### ISSUE THREAD

**Issue by Harm10** [robotframework/RIDE#2560]
I have these kind of lines in my code:
`# Check 1 basic table that should exist   schema check not possible`
These are 2 cells
Version 2.0 changes this to:
`# Check 1 basic table that should exist \ \ \ schema check not possible`
And all is in 1 cell after this. The back slashes are visible in the grid editor.

**Comment by HelioGuilherme66** [comment]
@Harm10 This is fixed in new release, v2.0.8.
