### ISSUE TITLE
Missing blank lines between sections in .robot files

### ISSUE THREAD

**Issue by axiom41** [robotframework/RIDE#2562]
Hello.
Just a small bug: i use Robocop to statically check the Robot Framework files and it reports that blank lines are missing between sections, in text mode of course (actually RIDE was keeping them in older versions, but since the last ones they're always removed, even by adding them manually).
Please check the screenshot as an example:
![image](https://user-images.githubusercontent.com/9963199/225271485-3dcc139a-ab0a-48f8-aab1-5d0bd40294c9.png)

Would it be possible to restore them?
Thanks for your support.

**Comment by HelioGuilherme66** [comment]
@axiom41 It was my change, on purpose. I will revert it.
(I want to do even more, like being configurable).

You can do the modification already on you installation, (and confirm this fix it):
Open in an a file editor, or Python code IDE the file:
`<python installation files/site-packages>/robotide/lib/robot/writer/filewriters.py`
change lines from line 63, from current:
```python
    def _write_table(self, table, is_last):
        self._write_header(table)
        self._write_rows(self._formatter.format_table(table))
        # if not is_last:
        #    print(f"DEBUG: writing table {self._formatter.format_header(table)}")
        #    self._write_empty_row(table)
``` 

To:
```python
    def _write_table(self, table, is_last):
        self._write_header(table)
        self._write_rows(self._formatter.format_table(table))
        if not is_last:
            self._write_empty_row(table)
```



Thank you for being a loyal "customer"!!! :)
