### ISSUE TITLE
Ride.py doesn't work in calvin linux

### ISSUE THREAD

**Issue by Snorny** [robotframework/RIDE#2565]
Hello,

I have done all the necessary installations to be able to use RobotFramework.

But after installing ride the IDE launch via ryde.py does not work. Ride.py is not recognized.

I have attached a picture with the versions of each tool needed.
(I have hide the proxy adress)

![robot](https://user-images.githubusercontent.com/79095228/227213908-ef3952e7-105c-4541-a132-2d9b56ad153a.PNG)

Thanks in advance for your help.

**Comment by Snorny** [comment]
I've found the solution on #1811

**Comment by HelioGuilherme66** [comment]
@Snorny Glad that you found a solution, but can you write here what commands you needed to do?
