### ISSUE TITLE
Unable to run test cases in RIDE

### ISSUE THREAD

**Issue by jitenderkumaryadav** [robotframework/RIDE#2580]
Hi,
After opening the ride, I am selecting simple test case and start the run after selecting Execution Profile as robot 3.1. But it not running test case and give error attached in screen shot. Can you please help here

**RIDE logs**
20230420 16:37:40.758 [INFO]: Found Robot Framework version 6.0.2 from C:\Users\j11kumar\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\robot.

20230420 16:37:40.758 [INFO]: Started RIDE 2.0 using python version 3.7.9 with wx version 4.2.0 in win32.

![image](https://user-images.githubusercontent.com/29803010/233385812-18afc776-7670-43b2-acf9-365aeaaa8d8d.png)

**Comment by jitenderkumaryadav** [comment]
This issue is resolved after upgrading python version to 3.10.8

**Comment by HelioGuilherme66** [comment]
@jitenderkumaryadav Do you have two Python 3.7 installations?
I see this long path for Python
`C:\Users\j11kumar\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\` 
This is a strange location to have Python installed.
