### ISSUE TITLE
Make configurable which system file explorer to use

### ISSUE THREAD

**Issue by HelioGuilherme66** [robotframework/RIDE#2596]
For example in Linux, currently the search is done by Dolphin and Nautilus, but user may be in a Linux that does not have any of those or may wish to use a different one.

Example:
----------------------------------
|  Environment |  File Explorer |
|----------------|----------------|
|  LXQt             | pcmanfm-qt   |
|                      |                         |
|---------------|-----------------|

**Comment by ksokolowski** [comment]
Hello.
Could we also configure which browser to use for opening logs?
IMO it is similar issue, that could be done as part of the same enhancement.
