### ISSUE TITLE
Inverted logic of "Edit" tab > "Settings" button

### ISSUE THREAD

**Issue by ESP4Ever** [robotframework/RIDE#2598]
RIDE v2.0.5 running on Python 3.10.6.
Ubuntu 22.04

![image](https://github.com/robotframework/RIDE/assets/44872879/f0b1b0f0-5415-4261-9722-4d02c7941410)
![image](https://github.com/robotframework/RIDE/assets/44872879/324d4160-ba18-4f1c-b8ef-a524600d4d0c)

**Comment by ESP4Ever** [comment]
Hello!
Just upgraded from  wxPython 4.2.0 to 4.2.1 - same issue

**Comment by AndrewYang885** [comment]
![RF Setting Issue](https://github.com/robotframework/RIDE/assets/119938504/2c45b5a4-f0e8-4f43-be23-ae1f08f73389)
Same Issue

**Comment by AndrewYang885** [comment]
I run it in Windows11...not sure if this resulted from some software's versions incompatible or not.

**Comment by HelioGuilherme66** [comment]
You are not seeing this bug. When we expand the Settings, the visible elements, Imports, Variables,... are moved down, and when collapsed they move up.
In Linux this is not happening.
