### ISSUE TITLE
Small search text box in Text Editor (macOS Catalina)

### ISSUE THREAD

**Issue by HelioGuilherme66** [robotframework/RIDE#2604]
Attached is a screenshot of the Search Text Box in Text Editor, showing the size too small.
![image](https://github.com/robotframework/RIDE/assets/2866630/11f2ebdc-ddb8-49fb-8455-9e51e6968ec5)

macOS Catalina (intel) version 10.15.7
Python 3.11, wxPython 4.2.1
RIDE 2.0.5

**Comment by HelioGuilherme66** [comment]
@rbradhika530 As you can see in the screenshot, those tabs are present in macOS.

You must have a different problem.

**Comment by rbradhika530** [comment]
@HelioGuilherme66  Robot Framework version 6.1 from /Users/radhika.bharti/Library/Python/3.9/lib/python/site-packages/robot.

20230614 08:07:08.090 [INFO]: Started RIDE v2.0.5 using python version 3.9.12 with wx version 4.2.1 in darwin.

**Comment by rbradhika530** [comment]
@HelioGuilherme66  Parsing '/Users/radhika.bharti/test-automation/TestCases/Regression/Communication.robot' failed: PermissionError: [Errno 13] Permission denied - while executing TC permission denied

**Comment by HelioGuilherme66** [comment]
Fixed in v2.0.8dev24.
