### ISSUE TITLE
Resource file disappears from the editor view

### ISSUE THREAD

**Issue by JFoederer** [robotframework/RIDE#2607]
While working on a project I have frequent occurrences where a `.resource` disappears from under my nose when saving progress.

Attached is a small project that, for me, has a 100% reproduction rate following these steps:

1. Open or reload the folder (Titanic)
2. Open `make_it_disappear.resource` in the text editor
3. Copy/Paste line 3 to a new line 4
4. Save
5. Delete line 4
6. Save
7. Copy/Paste line 3 to a new line 4
8. save

Now the file is no longer present in the tree view. The tree view selection jumps to the top-folder and the text editor shows the top folder's `__init__.robot` file contents.

Versions: Windows 10, Python 3.10.6, RIDE 2.0.5

Interesting detail: If you remove the reference to the resource file from the top-folder `__init__.robot`, it still opens when loading the project. This does not happen on an even smaller project that contains only the misbehaving file.

[Titanic.zip](https://github.com/robotframework/RIDE/files/11745718/Titanic.zip)

**Comment by HelioGuilherme66** [comment]
@JFoederer I reproduced the bug in Windows 10, but not in Fedora 38.
I'll see if happens in macOS too.

**Comment by HelioGuilherme66** [comment]
Anyone wanting to chase this bug, can help me by using the branch where I had identified the last location before it happens (after saving).
See https://github.com/HelioGuilherme66/RIDE/tree/fix_text_editor

**Comment by JFoederer** [comment]
That feels a lot more stable, good job!
