### ISSUE TITLE
Variables imported from YAML file not recognized in RIDE

### ISSUE THREAD

**Issue by ksokolowski** [robotframework/RIDE#2623]
Hello.

I guess the issue title says eveyrhing. RIDE is not recognizing any varibles from YAML files.
They are highligted as incorrect variables. Naturaly, when executing RF with such variables everything works.
It would be great to have possiblity to see that YAML provided variables are correctly imported, and RIDE could naturaly help auto suggest variable syntax (they are following RF extended variable syntax).

**Comment by HelioGuilherme66** [comment]
@ksokolowski Can you, please, attach a sample YAML file with variables definitions? (you probably need to add .txt extension, to attach here).

**Comment by ksokolowski** [comment]
Hello.

Sure. I guess the similar issue was visible when I have tried to import JSON file with variables. 
But I prefer data as YAMLs for my projects.  
[browsers.yaml.txt](https://github.com/robotframework/RIDE/files/12429233/browsers.yaml.txt)
[youtube_main.yaml.txt](https://github.com/robotframework/RIDE/files/12429236/youtube_main.yaml.txt)

**Comment by HelioGuilherme66** [comment]
Thanks for the files.

JSON will also be part of this enhancement.

**Comment by ksokolowski** [comment]
Thank you!

**Comment by HelioGuilherme66** [comment]
I don't know about the highlight, but the context autocomplete is working. Now also for JSON files in v2.0.8dev7.
