### ISSUE TITLE
In use case edit GUI, when the cell content contains \n,  User switch the mouse focus to another use case, the current cell keeps flashing and getting stuck

### ISSUE THREAD

**Issue by nwf2021** [robotframework/RIDE#2629]
100% reproduction
steps
1 The first step is to write the "log hello \nwf" in the edit GUI of use case 1
2 Step 2: Click on the cell "hello \nwf"
![RIDE with line_hang](https://github.com/robotframework/RIDE/assets/78520065/3025db09-09d3-4ee7-9278-ce7b74a8d078)
  , Keep the mouse selected in the cell
3 Step 3: Switch the mouse and click on Test Case 2 or  Any User Keyword  
4 At this point, the cell "hello \nwf" keeps flashing and the RIDE is stuck

**Comment by HelioGuilherme66** [comment]
@nwf2021 There was a known problem in Windows and some older versions of RIDE. To workaround this, you can make the '\n' visible in Grid Editor since v2.0.6 by setting to False the `filter newlines` option in the settings.cfg file.
