### ISSUE TITLE
RIDE does not import Pandas library

### ISSUE THREAD

**Issue by manojpaul8** [robotframework/RIDE#2635]
RIDE version: v2.0.6
Python interpreter version: 3.10
Operating system and its version: Win10

'Import Pandas' does not work from RIDE.

**Comment by HelioGuilherme66** [comment]
@manojpaul8 That is not a Test Case which I can use to reproduce the problem.
I don't see the relation with RIDE.

You can use newesrt version of RIDE, v2.0.7

**Comment by HelioGuilherme66** [comment]
Closing because it is not something we can reproduce.
