### ISSUE TITLE
sometimes Run/Text editor tabs are missing, when the RIDE is launched

### ISSUE THREAD

**Issue by manojpaul8** [robotframework/RIDE#2636]
RIDE version: v2.0.6
Python interpreter version: 3.10
Operating system and its version: Win10

-Sometimes when you launch RIDE, it doesn't show Run or Text editor tabs.
-We need to go to  'Manage Plugins' menu to re-enable it, but it may crash the application first time when you attempt to re-enable.
-Next launch we are able to actually reenable.

Note: This issue does not occur all the times.

**Comment by winyz** [comment]
upgrade  RIDE：2.0.b1 ->2.0.7
python version:3.9
Operating system:windows 10


After the upgrade, launch, the program  does not display the RUN tab.
no errors in RIDE.log.

Find the plugin“Navigate-Manage Plugin-Test Runner”, disable the plugin, and close the application,

Lanch RIDE again, enable the running plug-in, then run tab is  displayed，RIDE  works fine.

**Comment by winyz** [comment]
@HelioGuilherme66  So far , it is all right.

**Comment by manojpaul8** [comment]
@HelioGuilherme66  We are still on v2.0.6. 

Was this issue resolved in v2.0.7 or you want me to also check if the issue is present in v2.0.7.

Like @winyz mentioned, I do not see errors in RIDE log when the tabs are missing.

**Comment by HelioGuilherme66** [comment]
>you want me to also check if the issue is present in v2.0.7.

Yes, please try 2.0.7, because is the latest released version.

**Comment by HelioGuilherme66** [comment]
Closing because we have now a new release v2.1, and users should try it.
Use the command:
`pip install -U robotframework-ride`
Or from RIDE, **Help->Check for Upgrade**.
