### ISSUE TITLE
Issue to run robotic test cases

### ISSUE THREAD

**Issue by bansal1988** [robotframework/RIDE#2652]
Hi, 
i am trying to run my test suite in Robotic framework with Ride.py, but having following error

command: robot -A C:\Users\shivban\AppData\Local\Temp\RIDEcdox96ca.d\argfile.txt --listener C:\Users\shivban\AppData\Local\Programs\Python\Python311\Lib\site-packages\robotide\contrib\testrunner\TestRunnerAgent.py:61744:False C:\Users\shivban\Desktop\cpak\cpak\ROBOT\CPAK
TestRunnerAgent: Running under CPython 3.11.6

=========================================================================================================================================================
CPAK                                                                                                                                                     
=========================================================================================================================================================
CPAK.REGULAR FLOW                                                                                                                                        
=========================================================================================================================================================

[ WARN ] The chromedriver version (84.0.4147.30) detected in PATH at C:\Users\shivban\AppData\Local\Programs\Python\Python311\Scripts\chromedriver.exe might not be compatible with the detected chrome version (117.0.5938.63); currently, chromedriver 117.0.5938.149 is recommended for chrome 117.*, so it is advised to delete the driver in PATH and retry
TC1                                                                                                                                              | FAIL |
SessionNotCreatedException: Message: session not created: This version of ChromeDriver only supports Chrome version 84
Stacktrace:
Backtrace:
	Ordinal0 [0x011987E3+2852835]
	Ordinal0 [0x01085BB1+1727409]
	Ordinal0 [0x00F5E4B9+517305]
	Ordinal0 [0x00EF0BA0+68512]
	Ordinal0 [0x00EED3A0+54176]
	Ordinal0 [0x00F0D9F7+186871]
	Ordinal0 [0x00F0D7FD+186365]
	Ordinal0 [0x00F0B70B+177931]
	Ordinal0 [0x00EF2584+75140]
	Ordinal0 [0x00EF3650+79440]
	Ordinal0 [0x00EF35E9+79337]
	Ordinal0 [0x0109AD5C+1813852]
	GetHandleVerifier [0x012BC616+1075574]
	GetHandleVerifier [0x012BC367+1074887]
	GetHandleVerifier [0x012C7497+1120247]
	GetHandleVerifier [0x012BCC16+1077110]
	Ordinal0 [0x01093206+1782278]
	Ordinal0 [0x0109C3BB+1819579]
	Ordinal0 [0x0109C523+1819939]
	Ordinal0 [0x010B2B45+1911621]
	BaseThreadInitThunk [0x759200C9+25]
	RtlGetAppContainerNamedObjectPath [0x77297B4E+286]
	RtlGetAppContainerNamedObjectPath [0x77297B1E+238]
---------------------------------------------------------------------------------------------------------------------------------------------------------
CPAK.REGULAR FLOW                                                                                                                                | FAIL |
1 test, 0 passed, 1 failed
=========================================================================================================================================================
CPAK                                                                                                                                             | FAIL |
1 test, 0 passed, 1 failed
=========================================================================================================================================================
Output:  C:\Users\shivban\AppData\Local\Temp\RIDEcdox96ca.d\output.xml
Log:     C:\Users\shivban\AppData\Local\Temp\RIDEcdox96ca.d\log.html
Report:  C:\Users\shivban\AppData\Local\Temp\RIDEcdox96ca.d\report.html

Test finished 20231008 20:07:25

**Comment by bansal1988** [comment]
I have Version 117.0.5938.63 (Official Build) (64-bit) in my system

**Comment by HelioGuilherme66** [comment]
@bansal1988 Dear user, please understand that this issue tracker is only for RIDE problems or suggestions for improvements. (RIDE is an editor of test cases which allows to run with **robot** or **RPA**).
The problem you report is related with SeleniumLibrary, but it is not an issue to report because the solution is shown in the error message.
>chrome version (117.0.5938.**63**); currently, chromedriver 117.0.5938.**149** 
You need to upgrade your chromedriver.exe to the newer version.
