### ISSUE TITLE
Unable to see the Run tab in Robotframework RIDE

### ISSUE THREAD

**Issue by eragupta** [robotframework/RIDE#2659]
Suddenly the run tab is disappeared and I am not able to bring it back. Tried installing and reinstalling the Robotframework-ride but nothing is helping - 

OS - MacOS Apple Silicon
Python 3.11
Robotframework - 6.1.1
robotframework-ride - 2.0.7

**Comment by HelioGuilherme66** [comment]
@eragupta Usually there should be error messages in `Tools->View RIDE Log`, please put them here.

One possible workaround is to go to `Tools->Manage Plugins` and enable `Test Runner` (or disable). Then restart RIDE, and reactivate the plugin.

To have more information, you should tell us, how you started RIDE:

- From the Applications Launcher (or Desktop shortcut) --> error messages are only visible from RIDE Log
- From the terminal (`ride.py` or `python -m robotide.__init__`) --> may have error messages visible

You did not mention what was the operating system version, is it the newest, Sonama ?

**Comment by HelioGuilherme66** [comment]
Closing because we have now a new release v2.1, and users should try it.
Use the command:
`pip install -U robotframework-ride`
Or from RIDE, **Help->Check for Upgrade**.
