### ISSUE TITLE
Can't install ride, pip is not working.

### ISSUE THREAD

**Issue by TwK22** [robotframework/RIDE#2661]
OS: Winodws 11 Pro
Python: Python 3.10.0
I installed everything as should be but i keep getting this error 

"Successfully installed robotframework-ride-2.0.8.dev23
WARNING: There was an error checking the latest version of pip."

![image](https://github.com/robotframework/RIDE/assets/148210817/6cd1c08e-12e7-4082-a91c-77fc30e000d0)

**Comment by HelioGuilherme66** [comment]
You got a success message, and then an error in pip.
This is not RIDE problem.
