### ISSUE TITLE
comments display problem, RIDE v2.0.5

### ISSUE THREAD

**Issue by Jasonlya** [robotframework/RIDE#2670]
Here's what I want
![image](https://github.com/robotframework/RIDE/assets/44518459/530a534d-1f1f-4a19-8de7-15fc9d14e892)
but，Once I save,exit ride.exe ,reopen
![image](https://github.com/robotframework/RIDE/assets/44518459/096e23c2-6ab3-43c7-8a27-5d67a5fa26b3)

**Comment by HelioGuilherme66** [comment]
@Jasonlya This is solved in latest version v2.0.8.
Please upgrade.
