### ISSUE TITLE
have any optimization measures?

### ISSUE THREAD

**Issue by guohui1992** [robotframework/RIDE#2671]
Hello, I am using RIDE to open the automated testcase engineering library, which is very slow and too laggy in use. Do you have any optimization measures?

**Comment by HelioGuilherme66** [comment]
If you really want to have some valuable answer from me, please do a proper report, with details about versions, and size of your project and some indicators, like the time it takes to load.

**Comment by HelioGuilherme66** [comment]
Closing because (OR statements):
- Issue report is does not have enough or relevant info
- No follow up from reporter
- Not anything we can reproduce
- Reducing the number of opened issues
