### ISSUE TITLE
V2.0.8.1's NEW KEY WORD MUST input argument 

### ISSUE THREAD

**Issue by Jasonlya** [robotframework/RIDE#2673]
After upgrading my RIDE version from V2.0.5 to V2.0.8.1, I noticed that when creating a new keyword in the interface, it is mandatory to fill in the 'argument' field in order to save the keyword.

There are no specific error messages or indications in the RIDE logs. When I click 'OK', there is no response and I am unable to save.

RIDE version ：V2.0.8.1
Python interpreter version ：3.10.1
Operating system and its version：win 10

**Comment by JFoederer** [comment]
@Jasonlya , can you please complete your issue report following the guidelines:
https://github.com/robotframework/RIDE/blob/5fa2ec014b8cf475bac10e65b6476800450f9aed/CONTRIBUTING.adoc#submitting-issues

**Comment by Jasonlya** [comment]
Supplemented.

**Comment by HelioGuilherme66** [comment]
@Jasonlya Thanks for the report.

As a workaround, you can create with a variable as argument and later remove it by clicking the Clear button, on the keyword settings section.
