### ISSUE TITLE
Grid and Text editors do not sync selected file

### ISSUE THREAD

**Issue by JFoederer** [robotframework/RIDE#2675]
The Text editor does not follow file selection changes while the Grid editor is active.

Reproduction scenario:

- Open a test suite with at least 2 files (2 test suites or test suite + resource)
- Select file 1 and switch between grid and text editor to confirm they are the same file
- With the grid editor open, select file 2
- Switch to the Text editor
- **Defect:** The Text editor shows file 1, whereas it should have shown file 2

_Using RIDE v2.0.9dev1 running on Python 3.11.0._

**Comment by HelioGuilherme66** [comment]
@JFoederer Please retest this one. I think is fixed in some versions now.

**Comment by JFoederer** [comment]
Yes, I can confirm the fix.
