### ISSUE TITLE
Test runner listener is not compatible with Robot framework 7.

### ISSUE THREAD

**Issue by JFoederer** [robotframework/RIDE#2677]
Running tests from RIDE with Robot framework 7 yields many errors of this style in the console log window:
`[ ERROR ] Calling method 'log_message' of listener '<...>\Python\Python311\Lib\site-packages\robotide\contrib\testrunner\TestRunnerAgent.py' failed: AttributeError: 'Output' object has no attribute '_xmllogger'`

Source of the exception: https://github.com/robotframework/RIDE/blob/master/src/robotide/contrib/testrunner/TestRunnerAgent.py#L126C5-L126C5

This caused by changes on the Robot side: https://github.com/robotframework/robotframework/commit/3704a2867f7f0c4cbcda505d2ae0c58aedee5ad5

Then new interface does not appear to support the `_log_message_is_logged` call that is currently used.
`AttributeError: 'XmlLoggerAdapter' object has no attribute '_log_message_is_logged'`

**Comment by sskfny** [comment]
Any rough idea on when RIDE will support robotframework 7 ?

**Comment by JFoederer** [comment]
You can give this branch a try: https://github.com/JFoederer/RIDE/tree/Robot-Framework-7-compatability
If this runs OK and does not cause backward compatability issues, then RF7 support could be just around the corner.

To install: `pip install -U https://github.com/JFoederer/RIDE/archive/Robot-Framework-7-compatability.zip`

**Comment by HelioGuilherme66** [comment]
@JFoederer Thanks!
Your code fixed this bug :)

v2.1dev12
