### ISSUE TITLE
Getting Calling method 'log_message' of listener 'C:\Users\..\AppData\Local\Programs\Python\Python39\lib\site-packages\robotide\contrib\testrunner\TestRunnerAgent.py' failed: AttributeError: 'Output' object has no attribute '_xmllogger'

### ISSUE THREAD

**Issue by error404x0016** [robotframework/RIDE#2695]
I got this error when running tests in RIDE after I upgraded robot framework via pip install --upgrade

![2024-01-22_23h15_40](https://github.com/robotframework/RIDE/assets/86699749/2deecb8d-06c7-41f6-8714-fb45cc7b1dea)

**Comment by HelioGuilherme66** [comment]
The previous issue was reporting this, #2677.

For now, the solution is to downgrade robotframework to 6.1.1.

**Comment by error404x0016** [comment]
thanks for the tip, i'll downgrade my robotframework to 6.1.1 and relay this to my fellow qa

**Comment by HelioGuilherme66** [comment]
Fixed in v2.1dev12.
