### ISSUE TITLE
[RIDE 2.0.8.1] Detached tree view can't be restored

### ISSUE THREAD

**Issue by ESP4Ever** [robotframework/RIDE#2696]
Hello,

I've somehow detached the tree view and it was impossible to attach it back due to attach icons were spread across the screen and were not operational. Now I've a 5x5mm window in the upper left corner of RIDE which can't be resized. Please help!
![image](https://github.com/robotframework/RIDE/assets/44872879/62bbd912-0e5d-4df5-b7fe-f011b777077a)

**Comment by HelioGuilherme66** [comment]
See this entry in FAQ. https://github.com/robotframework/RIDE/wiki/F.A.Q.#16--q-i-have-closed-the-test-suites-tree-panel-and-now-i-cannot-restore-it-even-after-restarting-ride-current-version-20b2

**Comment by ESP4Ever** [comment]
Thank you! Unfortunately, if the mentioned string is deleted, RIDE doesn't start and reports a parsing error. A complete deletion of the settings file helped

**Comment by JFoederer** [comment]
Can't you still reach the cross to close it and then reactivate using the view menu?
![image](https://github.com/robotframework/RIDE/assets/32476108/f4194c1d-26ae-4c1a-aeba-45c3d4314913)
