### ISSUE TITLE
Supporting Robot Framework 7's new VAR syntax

### ISSUE THREAD

**Issue by JFoederer** [robotframework/RIDE#2703]
In Robot Framework 7 a [new syntax for declaring variables](https://robotframework.org/robotframework/latest/RobotFrameworkUserGuide.html#var-syntax) is introduced. To complete RF7 support from RIDE this new syntax should be supported. Support would entail syntax highlighting and adding declared variables to the suggestions while editing.

**Comment by HelioGuilherme66** [comment]
Partially done in v2.1dev53.
Still missing to fix multiline variables in Variables section.
Still missing to get names/values for VAR defined variables.

**Comment by HelioGuilherme66** [comment]
Missing variables recognition in autocomplete :(.
