### ISSUE TITLE
FileExplorer enabled setting is never set to False

### ISSUE THREAD

**Issue by JFoederer** [robotframework/RIDE#2719]
By default the File Explorer is opened, which is also stored in the `settings.cfg` file. Unless this file edited manually there is no way to persist the _opened_ setting at value False. I would expect that if the File Explorer is closed using the cross on the panel or by toggling it from the _View_ menu, that this choice is remembered.

**Comment by HelioGuilherme66** [comment]
The File Explorer is a Plugin, and the Enable state stored in `settings.cfg` is the Plugin state. If we Disable the Plugin, then the Menu option is removed.

The toggle idea, to Show/Hide the File Explorer (and maybe the Project Explorer) and persist this state, is a good idea.
