### ISSUE TITLE
Run error when selecting tests by checkbox(es) in v2.1dev20

### ISSUE THREAD

**Issue by axiom41** [robotframework/RIDE#2724]
Hello.
Using latest v2.1dev20, i get the error below when i try to run tests that i've selected by checkbox(es).

I built a project (folder) named "MyProject" where i created a "TestSuite.robot" file containing a single "TestCase" test. Selecting its checkbox and running it, i get:

`[ ERROR ] Suite 'MyProject' contains no tests matching name 'TestSuite.TestCase' in suite 'TestSuite'.`

It works if test(s) is(are) not selected by checkbox(es).

Test selection by checkbox(es) still works in v2.1dev19 (so i reverted to that).

I'm on Win 11 x64, Python 3.11, Robot Framework 6.1.1

Many thanks in advance for your support.

**Comment by HelioGuilherme66** [comment]
@axiom41 Thanks. I had already detected it, but was silently trying to fix.
(It would be already if I knew what was changed)
You can install previous commit for v2.1dev19, it is working there.
