### ISSUE TITLE
In the most recent version of Ride (2.0.8.1 and 2.0.8) , Ctrl+Space does not display Keyword suggestions. 

### ISSUE THREAD

**Issue by ap0087105** [robotframework/RIDE#2728]
Installed latest version of Ride (2.0.8.1 and 2.0.8). Imported required Selenium Library. 
When tried to type some word like **'Open'**  It does not show any keyword recommendation. 
![image](https://github.com/robotframework/RIDE/assets/136758194/92ad6f56-876c-4568-becd-4f03a5455a5b)

**Comment by HelioGuilherme66** [comment]
It may take some time to load the keywords documentation.
First see if the Library import shows in red color. If so, see the Tools->View RIDE Log.

Try to reload the project after the first time you add the Library import.

I am assuming you are running RIDE in a real machine. You did not even mentioned what operating system you are using, so please, improve your report.

**Comment by HelioGuilherme66** [comment]
@ap0087105  How is the current situation? Did it started working OK?
Did you tried v2.1a3 or current developent?
