### ISSUE TITLE
Insert rows Ctrl-I  option moved from top position 

### ISSUE THREAD

**Issue by povar81** [robotframework/RIDE#2730]
When I clicked right button to call menu of options - Insert rows was in the top position:
on  older versions:
RIDE 1.2.2 running on Python 2.7.0
![image](https://github.com/robotframework/RIDE/assets/7736848/0f7eb06b-4083-4411-b49b-2c8b88a9d739)

RIDE 1.7.4.2 running on Python 3.7.4. 
![image](https://github.com/robotframework/RIDE/assets/7736848/32e02e41-ba48-4c66-88df-cccd203c1505)

but in new version RIDE v2.0.8.1 running on Python 3.7.4 it is moved down, which is counter intuitive in my opinion (after a decade of being in the top position)
![image](https://github.com/robotframework/RIDE/assets/7736848/d6a9bd2b-87ee-42db-8dcb-c9a4775a8398)

**Comment by HelioGuilherme66** [comment]
Better use the Ctrl-I then.
This kind of issues would be better discussed in direct messaging at #ride channel in Slack. Can you use Slack?

**Comment by povar81** [comment]
Yes,
I'm on slack but this one I thought to discuss here - to know if this feature will be ever changed back.

**Comment by HelioGuilherme66** [comment]
Fixed in 2.1dev84.
