### ISSUE TITLE
The GUI editing is very stuck, which seriously affects the use of it.

### ISSUE THREAD

**Issue by TheSongg** [robotframework/RIDE#2732]
OS - Win10
Python 3.8.10
Robotframework - 4.3.10
robotframework-ride - 2.0.7

The interface operation is very stuck, such as opening a case or opening a keyword, the software response is quite slow. This problem was not found in versions before 2.0.

**Comment by HelioGuilherme66** [comment]
@TheSongg  You should upgrade to 2.8.01.
Old versions will not be fixed.

**Comment by TheSongg** [comment]
Thank you very much for your reply! I have tried the latest version, and it is also stuck. I changed a few PCs, and they are all the same problem.

**Comment by TheSongg** [comment]
2.8.0.1 or 2.0.8.1？

**Comment by HelioGuilherme66** [comment]
Yes, 2.0.8.1 is latest released.

I need more information on the definition of slowness or being stuck.

Is your test cases file too large?
Are you talking about the Test Editor, or Grid Editor?
What is the version of wxPython?

Is this slowness so bad that makes you not wanting to use RIDE? Can you work with it and use new features?

**Comment by TheSongg** [comment]
> Yes, 2.0.8.1 is latest released.
> 
> 
> 
> I need more information on the definition of slowness or being stuck.
> 
> 
> 
> Is your test cases file too large?
> 
> Are you talking about the Test Editor, or Grid Editor?
> 
> What is the version of wxPython?
> 
> 
> 
> Is this slowness so bad that makes you not wanting to use RIDE? Can you work with it and use new features?
  
wxpython：4.1.0

When I click test case from the Test Suites tree node or click back to Edit tab from other tab, the Edit tab need 3~4 seconds to load and display。

When I only open a test suite file，test editor and grid editor are also slow.

**Comment by HelioGuilherme66** [comment]
You can try to upgrade wxPython to 4.2.1.

After that, if did not improve, you can try the development version, because still runs on Python 3.8.

**Comment by TheSongg** [comment]
> You can try to upgrade wxPython to 4.2.1.
> 
> 
> 
> After that, if did not improve, you can try the development version, because still runs on Python 3.8.

Thank you very much. I'll try it tomorrow.

**Comment by TheSongg** [comment]
> You can try to upgrade wxPython to 4.2.1.
> 
> 
> 
> After that, if did not improve, you can try the development version, because still runs on Python 3.8.

After upgrade wxPython to version 4.2.1, the performance of RIDE has been improved.
How can I avoid this situation? Reduce test cases file size or reduce external resource references?

**Comment by HelioGuilherme66** [comment]
This was a problem with wxPython, there is not much we can do to improve.
Only have the general rule of the smaller the test cases files, the faster they load.
Colorization and style of Cells or Content affects the rendering of them. This can only improved from optimizing the code, but there are many factors in stake here.

Closing this as fixed.
