### ISSUE TITLE
ValueError: No language with name '' found.

### ISSUE THREAD

**Issue by JenikaGo** [robotframework/RIDE#2734]
I'm having problems with my RIDE. getting this error when trying to run test cases
[ ERROR ] Unexpected error: ValueError: No language with name '' found.

I have attached a screenshot of said error
![2024-03-22_15h49_25](https://github.com/robotframework/RIDE/assets/164476736/50e72427-c1a7-46f8-83e6-7fcd8dcbd4b7)

here are the current versions I'm using:
RIDE -- v2.0.8.1
Python -- 3.9
robot framework -- 7.0

Thank you for your help🙇‍♀️

**Comment by HelioGuilherme66** [comment]
@JenikaGo I see the errors are coming from Robot Framework. Those will probably appear if you run the test from a command window/shell/terminal.

You probably have a Language: setting in your test case. You should try to comment that line with a #, and then try to open in RIDE. Note: RIDE 2.0.8.1 is not prepared to parse Language setting.

If you really want to use the Language: setting, then use it with a correct language defined. You can try the current development version, with that feature implemented.

**Comment by HelioGuilherme66** [comment]
Well, you did wrote:

> here are the current versions I'm using:
> RIDE -- v2.0.8.1

The first screen capture, was from the Run panel, with an error from Robot Framework (that may be caused by RIDE).

Now after using 2.1dev21 version, it may have set a value `language` in settings.cfg. With RIDE closd, you should edit that file and delete the line, or set to 'English`.
In Windows the file is at `%APPDATA%\RobotFramework\ride\settings.cfg`.

**Comment by JenikaGo** [comment]
I have deleted the lines with "Language" but I'm still getting the error.

Should I just uninstall everything, then re-install everything from scratch?
![2024-03-22_20h47_51](https://github.com/robotframework/RIDE/assets/164476736/3c019580-09b4-4a1e-ad79-5edad6df107e)

**Comment by HelioGuilherme66** [comment]
Well, I am a bit lost on this.

Make sure you don't have any instance of RIDE running. Close all windows
(was there a language setting, you show 0 hits?)

Please run your test case in a **new** command window, with a similar command you would use in RIDE. For example:
```
cmd.exe
cd  "<path to your project>\OSHD-robot\Lifting Equipment"
robot -t NewExam-HappyPath eService\Examination.robot

```
If there are no errors similar than those you first shown, then robot is OK.

Try to start RIDE from that directory with only the test case file:
```
python -m robotide.__init__  eService\Examination.robot

```

Then Run that test case (by selecting checkbox).

----
If the problem still exists, then:
- exit RIDE
- delete the directory `%APPDATA%\RobotFramework\`  (you may want to make a safe copy of settings.cfg if you want to use some settings).
- Start RIDE
- Open the project and Run the same test case.

If the problem still exists, then
**Thank you for your persistence in using RIDE**

**Comment by HelioGuilherme66** [comment]
Well, you did not cd to the directory of the project:

>cd  "<path to your project>\OSHD-robot\Lifting Equipment"

You can see the error message is about the wrong path to the file.

You can start RIDE normally and then open just that Examination.robot file. Then Run, and you should have the same failure as in command window.
(no more language errors ;) )

**Comment by JenikaGo** [comment]
Thank you so much! 🙇‍♀️
I was able to finally run my test case in RIDE without language errors! 🎉

![2024-03-23_13h02_51](https://github.com/robotframework/RIDE/assets/164476736/3156da7e-66dc-409f-8f67-4857b831d956)

![2024-03-23_13h02_31](https://github.com/robotframework/RIDE/assets/164476736/38031433-62cb-4bf8-accf-31d6d46f673e)

Do I need to do these steps every time I run a test case? or I should be able to use RIDE without any problems now?
`cmd.exe
cd  "<path to your project>\OSHD-robot\Lifting Equipment"
robot -t NewExam-HappyPath eService\Examination.robot
`
`python -m robotide.__init__  eService\Examination.robot`

**Comment by HelioGuilherme66** [comment]
>Do I need to do these steps every time I run a test case? or I should be able to use RIDE without any problems now?

No, of course not. The problem was solved by removing the setting `language = None` . This is something I need to fix, RIDE needs to ignore that setting, if not valid.

If you have the possibility, please use our Slack. We would troubleshoot this faster.

**Comment by HelioGuilherme66** [comment]
Using development version 2.1dev21, added setting `language = None` from a file without the setting. This broke running tests in v2.0.8.1 (wierd).
