### ISSUE TITLE
After successful installing of ride it is not running.

### ISSUE THREAD

**Issue by Wriki-tmsl** [robotframework/RIDE#2755]
Current Configuration
Ubuntu 22.04
Python 3.10

Traceback (most recent call last):
```

  File "/home/wrikimartin/.local/lib/python3.10/site-packages/robotide/application/application.py", line 89, in OnInit

    self.frame = RideFrame(self, self._controller)

  File "/home/wrikimartin/.local/lib/python3.10/site-packages/robotide/ui/mainframe.py", line 113, in __init__

    self._init_ui()

  File "/home/wrikimartin/.local/lib/python3.10/site-packages/robotide/ui/mainframe.py", line 204, in _init_ui

    self.tree = Tree(self, self.actions, self._application.settings)

  File "/home/wrikimartin/.local/lib/python3.10/site-packages/robotide/ui/treeplugin.py", line 209, in __init__

    treemixin.DragAndDrop.__init__(self, parent, **_TREE_ARGS)

  File "/usr/lib/python3/dist-packages/wx/lib/mixins/treemixin.py", line 510, in __init__

    super(DragAndDrop, self).__init__(*args, **kwargs)

  File "/usr/lib/python3/dist-packages/wx/lib/agw/customtreectrl.py", line 2919, in __init__

    self.SetFocus()

TypeError: could not convert 'Tree' to 'Panel'

OnInit returned false, exiting...

Exception ignored in atexit callback: <built-in function _wxPyCleanup>

wx._core.wxAssertionError: C++ assertion "GetEventHandler() == this" failed at ../src/common/wincmn.cpp(477) in ~wxWindowBase(): any pushed event handlers must have been removed
```
This is the output

**Comment by HelioGuilherme66** [comment]
@Wriki-tmsl  We need more information.

- was this a first time installation?
- what was the command to install?
- what is the version of, RIDE, wxPython? (`pip list`)
- what was the command to start RIDE (or, was from Desktop shortcut)?
- are you using Gnome or KDE/Plasma, or other Windows Manager?

**Comment by Wriki-tmsl** [comment]
Hi,
Yes, it was a first-time installation.
Command: pip install robotframework-ride (building wheel of wxpython took a
long time)
Versions
pip==22.0.2
ride==2.0.8.1
wxPython==4.0.7
Starting from the desktop, it is unresponsive, and when accessed via
ride.py, it displays the following output:.
I am in an Ubuntu environment.
Warm Regards,
Abhiraj Banerjee

**Comment by Wriki-tmsl** [comment]
Thank you for the quick responses. 
The issue has been fixed, and Ride is running smoothly on my machine.
I would like to discuss some further modifications in this editor as a user.

**Comment by HelioGuilherme66** [comment]
@Wriki-tmsl 
>I would like to discuss some further modifications in this editor as a user.

For conversations, you should use #ride channel at Slack or the topic Tools->RIDE in our Forum, see the README at Code section of this GitHub.
