### ISSUE TITLE
Robot Framework IDE 1.7.4.1 takes 30 seconds to open a project with 900 files, and there is an optimization solution for subsequent loading, such as lazy loading?

### ISSUE THREAD

**Issue by guohui1992** [robotframework/RIDE#2783]
![image](https://github.com/robotframework/RIDE/assets/22585034/595fb6ab-0f53-4b20-b49b-a3a12fac5934)

**Comment by guohui1992** [comment]
in windows10

**Comment by HelioGuilherme66** [comment]
@guohui1992 Why you use RIDE 1.7.4.1? Are you using Python 2.7?

There will not be any support for older versions. We currently are developing version 2.1 and the latest released version is 2.0.8.

What if your version of Robot Framework? If it is higher than 6.0, and with Python 3.8 to 3.12, you can try the current development version, and experiment RIDE in Chinese :).

Closing this Issue.

**Comment by guohui1992** [comment]
Thank you very much for your response. After upgrading RIDE to version 2.0.8.1 and Robot Framework to version 6.1.1, the loading speed of the project has improved significantly. The Python version used is 3.7.
When using RIDE 2.0.8.1, if the AND keyword is used in the setup or teardown of a test case, it will split the following content into the test case. 
in ride 1.7.4.1：
![image](https://github.com/robotframework/RIDE/assets/22585034/0792fd49-1f24-4b95-8c73-ba2f688717f5)
 in ride2.0.8.1：
![image](https://github.com/robotframework/RIDE/assets/22585034/f21fdb5a-c081-463a-87c0-f70df3a804ab)

**Comment by HelioGuilherme66** [comment]
@guohui1992 The problem you mention is fixed in current development version like I mention in #2778 

You don't have conditions to experiment this fix, because of your Python 3.7.

**Comment by guohui1992** [comment]
ok, thank you very much. I will upgrade the Python version used in my project and look forward to the release of Ride2.1.
