### ISSUE TITLE
[Grid Editor] After CTRL+C, the CTRL+X on a multiple cell sellection is not working properly

### ISSUE THREAD

**Issue by ZDabrowski** [robotframework/RIDE#2807]
After pressing CTRL+C shortcut key, a subsequent CTRL+X/CTRL+V operation on a multiple cell selection is not working properly.
Out of the entire selection, only one cell was cut and pasted.

**Environment**
Python 3.10.12
wxPython 4.2.1
robotframework 6.0.2
robotframework-ride 2.1.dev50
Ubuntu 22.04.4 LTS

**Steps**
1. On a Grid Editor press CTRL+C
![obraz](https://github.com/robotframework/RIDE/assets/32097744/40c8e7b0-c6e0-43cb-8527-04a006c02220)
3. On a Grid Editor select multiple cells (e.g. (2,2:2,5) 
![obraz](https://github.com/robotframework/RIDE/assets/32097744/b382d343-219e-4bf0-b87d-3535252ffd31)
and press CTRL+X. Only one cell has been cut.
![obraz](https://github.com/robotframework/RIDE/assets/32097744/baee730b-ed6b-4675-b68b-115299778eee)
5. On a Grid Editor press CTRL+V. Only one cell has been pasted.
![obraz](https://github.com/robotframework/RIDE/assets/32097744/6faab743-7c05-4a62-970e-035b1129ebaf)

**Additional info**
After switching to the "Text Editor" and back to the "Grid Editor", CTRL+X works fine until the CTRL+C or CTRL+C/CTRL+V is pressed.

Sample of code.
```robotframework
*** Test Case ***
test1
    FOR    ${idx}    IN RANGE    5
        Run Keywords    user keyword1    cell 1    cell 2
        ...    AND    user keyword2    cell 3
    END

*** Keywords ***
user keyword2
    [Arguments]    ${user}
    LOG    user ${user}    WARN

user keyword1
    [Arguments]    ${arg1}    ${arg2}
    LOG    user ${arg1} and ${arg2}    WARN
```

**Comment by HelioGuilherme66** [comment]
Unfortunately, I had to do an workaround for double-actions that is happening on Linux (and could not pin point where they come from). Need to review all keyboard actions.
Now I can confirm that the interaction with Ctrl-C and Ctrl-X is messing the selected range and using only top left cell. ALSO IN WINDOWS.
