### ISSUE TITLE
[Grid Editor] Subsequent shortcut key action works only on the top row of the selection

### ISSUE THREAD

**Issue by ZDabrowski** [robotframework/RIDE#2815]
A first shortcut key operation on a multiple cells' selection works properly.
However, any subsequent operation impacts only the top row of the selection.
It can be observed when using CTRL+SHIFT+I, CTRL+SHIFT+D, but also ALT+Up/ALT+Down.

**Environment**
Python 3.10.12
wxPython 4.2.1
robotframework 6.0.2
robotframework-ride 2.1.dev53
Ubuntu 22.04.4 LTS

**Steps**
1. Select multiple cells
![obraz](https://github.com/robotframework/RIDE/assets/32097744/0871cd7d-132a-4593-98c8-b00bbf65d884)
2. Press shortcut CTRL+SHIFT+I to insert cells. (OK)
![obraz](https://github.com/robotframework/RIDE/assets/32097744/32512f34-2045-4af6-b51a-308abc14e0c5)
3. Press CTRL+SHIFT+I again. The action only occurred on the top row of the selection.
![obraz](https://github.com/robotframework/RIDE/assets/32097744/fc29deb6-f27d-44f6-ac15-049335fa525d)
4. Select multiple cells again. (refresh selection)
5. Press shortcut CTRL+SHIFT+D to remove multiple cells. (OK)
![obraz](https://github.com/robotframework/RIDE/assets/32097744/16b44059-3609-4d27-bc75-51e5cbdde008)
6. Press shortcut CTRL+SHIFT+I to insert cells. The action only occurred on the top row of the selection.
![obraz](https://github.com/robotframework/RIDE/assets/32097744/2c434f9e-8522-4d46-9149-1043a0010b34)

ALT+Up scenario:
1. Select cells
![obraz](https://github.com/robotframework/RIDE/assets/32097744/ee7f41b6-d151-46a4-99ae-45ca37bcec18)
2. Press ALT+Up (OK)
![obraz](https://github.com/robotframework/RIDE/assets/32097744/8b3392aa-18e5-4f7c-b389-fa110e104a1f)
3. Press ALT+Up again. Only "4th line" moved up.
![obraz](https://github.com/robotframework/RIDE/assets/32097744/c9d957dc-0b5d-4c7e-84b9-e5d3a9aef8f3)

**Additional info**
It looks like an active selection persist in cache only for one action.
```robotframework
*** Test Cases ***
Test Rows
    Log    1st line
    Log    2nd line
    Log    3rd line
    Log    4th line
```

**Comment by HelioGuilherme66** [comment]
@ZDabrowski This one was a hard one to find, and I am not still totally convinced of the fix. In some situations, the Cursor (the highlighted cell), is lost even if the selection remains. When this happens,  wxWidgets (from C++ core), returns the error:
`(__init__.py:15846): Gtk-CRITICAL **: 02:05:36.930: gtk_widget_event: assertion 'WIDGET_REALIZED_FOR_EVENT (widget, event)' failed`
This means it does not know where the **key press** happened.

I fixed the Ctrl-X in Linux (need to test in Windows), but I did see the bad behavior when doing a lot of actions in a short period of time.
:crossed_fingers:
