### ISSUE TITLE
[Grid Editor] A single CTRL + Z operation reverses the last two actions

### ISSUE THREAD

**Issue by ZDabrowski** [robotframework/RIDE#2837]
When we press CTRL + Z, the last two actions on a Grid Editor will be undone at once.

**Environment**
Python 3.10.12
wxPython 4.2.1
robotframework 6.0.2
robotframework-ride 2.1.dev61
Ubuntu 22.04.4 LTS

**Steps**
0. Code example
![obraz](https://github.com/user-attachments/assets/582d4a59-0a70-48ac-8590-85d1bc258855)
1. Insert three cels. **3x CTRL + SHIFT + I** (OK)
![obraz](https://github.com/user-attachments/assets/ee3ce058-0bdd-48a1-97c2-a61ad6c904ae)
2. Undo action by pressing **1x CTRL + Z** hotkey
![obraz](https://github.com/user-attachments/assets/72cde3c4-5f50-4cf4-bfba-680901b4a47f)
3. Add two rows, **2x CTRL + I**
![obraz](https://github.com/user-attachments/assets/9709dd6d-b86f-4ace-a9a1-b7c2930a43e7)
4. Undo action by pressing **1x CTRL + Z** hotkey
![obraz](https://github.com/user-attachments/assets/eb346fca-110f-4ff8-b90e-956b3dd89f3e)
5. Add a **Comment** (row 5)
![obraz](https://github.com/user-attachments/assets/3d692bd8-4c48-458c-957f-64597dd7390d)
6. Undo action by pressing **1xCTRL + Z** hotkey (two last actions: (5.) and (1.) reversed)
![obraz](https://github.com/user-attachments/assets/34f7e9e4-69ac-40e8-8a1b-b650682b9883)
7. Delete two rows, **2x CTRL + D**
![obraz](https://github.com/user-attachments/assets/3f532ea4-e68f-4049-bfca-f7c2647f2703)
8. Undo action by pressing **1xCTRL + Z** hotkey
![obraz](https://github.com/user-attachments/assets/34f7e9e4-69ac-40e8-8a1b-b650682b9883)

**Additional info**
In the other hand, when pressing CTRL+Y (redo hotkey) multiple times, each subsequent action will be restored one at a time - as expected.

```robotframework
*** Test Cases ***
Test Rows
    Log    1st line
    Log    2nd line
    Log    3rd line
    Log    4th line
```

**Comment by HelioGuilherme66** [comment]
@ZDabrowski Thanks for the report.

In Linux there has been this situations of "double actions", which I had to condition in several actions. Seems that I also need to do for **Ctrl-Z**.
