### ISSUE TITLE
Once you save an empty Suite file, it is no longer possible to add and save test cases.

### ISSUE THREAD

**Issue by ZDabrowski** [robotframework/RIDE#2856]
Once you save an empty Suite file, it is no longer possible to add and save test cases.

**Environment**
Python 3.10.12
wxPython 4.2.1
robotframework 6.0.2
robotframework-ride 2.1.dev70
Ubuntu 22.04.4 LTS

**Steps**
1. On a Tree View, Right click on Folder and select `New Suite`
![obraz](https://github.com/user-attachments/assets/914a83fc-4802-44fc-9f63-57d7ba96f21e)
2. After selection goes to the newly created Suite, `Editor` tab is active, save the file
![obraz](https://github.com/user-attachments/assets/31878a2c-626a-449f-af52-c3eaf125afc8)
3. Under Suite file create New Test case by `New Test Case` right click command, and check the `Text Edit` tab - file is empty!
![obraz](https://github.com/user-attachments/assets/39a75c3e-44c1-4650-89f1-79bfa4c68029)
4. After switching back to the `Editor` Tab, test case is gone.

**Additional info**
It's possible to add settings, variables and keywords. Just like for the Resource file.
In case when newly created Suite file has an *, it is possible to create and save test cases.

**Comment by HelioGuilherme66** [comment]
This is a corner case, because you switched to Text Edit before adding any content, so the `*** Test Cases ***` was not written, and disappeared. That's why the file is considered to be a Resource file, and as such, no Tests can be added.

**Comment by ZDabrowski** [comment]
It can be reproduced if you just save the "Suite" file before adding test cases. You can ommit switching to Text Edit to have this defect reproduced.
**Steps**
1. `New Suite` "newsuite.robot"
2. Save the "newsuite.robot"
![obraz](https://github.com/user-attachments/assets/a7dc96f4-c375-4b5f-936c-4a1c520c6bf5)
3. `New Test Case` and add content
![obraz](https://github.com/user-attachments/assets/8128beb7-fb84-4bb4-9e27-7cd7de05d274)
4. Save the "newsuite.robot". Test case disappear (at least on my side).

If the empty files are considered as "Resource" files, so what about adding `*** Test Cases ***` section to `New Suite` files by default?

**Comment by HelioGuilherme66** [comment]
@ZDabrowski This is fixed in current development, v2.1de73.
