### ISSUE TITLE
[Grid Editor] Cell edit with `F2` hotkey is not working

### ISSUE THREAD

**Issue by ZDabrowski** [robotframework/RIDE#2858]
Cannot enter the edit mode of the cell when the `F2` hotkey is pressed,
Additionally, when `F2` is pressed on a non-empty cell and then on the empty cell, the content will be pasted.

**Environment**
Python 3.10.12
wxPython 4.2.1
robotframework 6.0.2
robotframework-ride 2.1.dev70
Ubuntu 22.04.4 LTS

**Steps**
1. Enter some content into cells 
![obraz](https://github.com/user-attachments/assets/d5124754-3301-4522-a37f-f1a45c424de7)
2. Press F2 to enter edition mode (cell content blinked for a while, but did not enter edition mode)
![obraz](https://github.com/user-attachments/assets/7beffb33-70f1-4eed-94fb-d06ddf12f89b)
3. Move cursor to the other, empty cell and press F2 (cell filled with the content of previously selected cell)
![obraz](https://github.com/user-attachments/assets/5b7a2cb5-3444-4f77-9cb6-b9b1ec3fe04c)
4. Move cursor to the cell with content and press F2
![obraz](https://github.com/user-attachments/assets/1553a6e4-0f20-40f5-ba3e-8e37fd0b766b)
6. Move cursor to the empty cells and press F2
![obraz](https://github.com/user-attachments/assets/cdf8eda7-046f-4fdc-8827-8954c22e8028)

**Additional info**
Did not notice `F2` shortcut key description in the `Help`->`Shorcut keys`->`Grid` 
Double-click is working properly.

**Comment by HelioGuilherme66** [comment]
Fixed in v2.1dev74.
