### ISSUE TITLE
ride.exe: Fatal error in Launcher

### ISSUE THREAD

**Issue by JFoederer** [robotframework/RIDE#2861]
Typing ride in the command prompt on my Windows machine redirects to `ride.exe` in the default Python's Scripts folder. Running that .exe either like this or by selecting it directly results in this error:
![image](https://github.com/user-attachments/assets/44dc4657-c8c3-43fe-9074-c3992c7de550)

The path to ride.exe is correct, but pythonww.exe seems to have a **w** too many.

**Comment by HelioGuilherme66** [comment]
@JFoederer This is fixed in v2.1b1.

You should uninstall RIDE, so that the new executable replaces the bugged one.
Install with `pip install --pre robotframework-ride`

**Comment by HelioGuilherme66** [comment]
@JFoederer I found that when starting `ride.exe` from the source code path, i.e. `C:\\Git\RIDE\` the pythonww.exe exists. Just try to `cd ..` and run again.
