### ISSUE TITLE
[Grid Editor] setting last argument in the keyword as ${EMPTY} impossible

### ISSUE THREAD

**Issue by Roboteus** [robotframework/RIDE#2870]
![image](https://github.com/user-attachments/assets/d1389d46-7ab8-4af8-af6e-d646c35d0c30)

Windows 11
Python 3.11.9
wxPython 4.2.1
robotframework-ride 2.1.dev73

**Comment by HelioGuilherme66** [comment]
@Roboteus Fixed in v2.1dev75.
