### ISSUE TITLE
[Grid Editor] Saving doesn't automatically remove empty rows

### ISSUE THREAD

**Issue by Roboteus** [robotframework/RIDE#2871]
1. Make space between keywords
![image](https://github.com/user-attachments/assets/68edf534-c894-4dd5-987a-eabb06934e7d)
2. Type CTRL+S

Stated result:
empty row didn't disappear

Acceptance criteria:
empty row disappeared (removed)

Windows 11
Python 3.11.9
wxPython 4.2.1
robotframework-ride 2.1.dev73

**Comment by HelioGuilherme66** [comment]
I cannot reproduce this in:
Fedora 40
Python 3.12.5
wxPython 4.2.1
robotframework-ride 2.1.dev75

**Comment by Roboteus** [comment]
started to work at:
Python 3.12.7
wxPython 4.2.2
RIDE 2.1.1
Windows11
