### ISSUE TITLE
[Grid Editor] Adding any value to the cell creates additional horizontal scrollbar and move it a little to the right

### ISSUE THREAD

**Issue by Roboteus** [robotframework/RIDE#2872]
![image](https://github.com/user-attachments/assets/819d0a47-4d43-46d1-95f7-3f8126a12c2e)

Windows 11
Python 3.11.9
wxPython 4.2.1
robotframework-ride 2.1.dev73

**Comment by HelioGuilherme66** [comment]
The new scroll bars appear because we needed to fix them missing in expanded Settings in Test Suites.
This is a minor side-effect, and the user can understand the use.

**Comment by HelioGuilherme66** [comment]
Fixed in v2.1.dev76.
Unknown origin of the following side-effect:
- After expanding Settings in Test Cases or Keywords, and collapsing, the scrolling stops working. To recover the correct scrolling, you should select another Test Case or Keyword, and return to the affected item.
