### ISSUE TITLE
[BUG] RIDE replaceing "Test Setup/Teardown" to "Task Setup/Teardown" even if option in menu is disabled

### ISSUE THREAD

**Issue by Roboteus** [robotframework/RIDE#2883]
![image](https://github.com/user-attachments/assets/4af80ad6-f3c4-426b-b5d5-16ebc58c8418)

![image](https://github.com/user-attachments/assets/4307af60-e438-4ce8-8783-118c4ee58cfb)

Windows 11
Python 3.11.9
wxPython 4.2.2a1
robotframework-ride 2.1dev78

**Comment by HelioGuilherme66** [comment]
@Roboteus Please be more detailed on what steps you performed.

**Comment by Roboteus** [comment]
started to work at:
Python 3.12.7
wxPython 4.2.2
RIDE 2.1.1
Windows11
