### ISSUE TITLE
[BUG] Third-Party JTAG Server Application Fails to Initialize in Robot Framework RIDE

### ISSUE THREAD

**Issue by AndresSanchez229** [robotframework/RIDE#2909]
### **Bug Report**
**Summary:** Running a third-party JTAG interface application from Robot Framework works as expected, but it fails when executed from Robot Framework RIDE. The server started by the third-party application is not accessible from the client with RIDE.

**Steps to Reproduce:**
1. Run the third-party JTAG interface application using Robot Framework.
2. Observe that the server starts and is accessible from the client.
3. Run the same application using RIDE.
4. Observe that the server starts but is not accessible from the client.
5. Expected Result: The server started by the third-party JTAG interface application should be accessible from the client when run from both Robot Framework and Robot Framework RIDE.

**Actual Result:** The server is accessible when run from Robot Framework but not when run from Robot Framework RIDE.

**Environment:**
Robot Framework Version: 7.0.1
Robot Framework RIDE Version: 2.1
Operating System: Windows 11
Third-Party Application: Xillinx Vivado Lab 2018 (over [pylinx](https://github.com/raczben/pylinx))
No hardware is required for the test, just the Vivado Lab tool.

**Additional Information:**
This is a simplified code:
```python
import pylinx

xsct_server = None
xsct = None
try:
    win_xsct_executable = r'xsdb.bat'
    connection_port = 3100
    xsct_server = pylinx.XsctServer(win_xsct_executable, port=connection_port, verbose=False)
    xsct = pylinx.Xsct('localhost', connection_port)
finally:
    if xsct is not None:
        xsct.close()
    if xsct_server is not None:
        xsct_server.stop_server()
```
It returns an error during the execution of xsct = pylinx.Xsct('localhost', connection_port), but I have tried to start the server outside the Robot Framework library, commenting " xsct_server = pylinx.XsctServer(win_xsct_executable, port=connection_port, verbose=False)" line, and it works. I would say the problem is with the server initialization from RIDE.

When the client tries to access to the server initialized from Robot Framework library and executed with RIDE, it returns this error message:
![image](https://github.com/user-attachments/assets/d3a6534e-da33-417c-9e09-93057481ac21)

**More Information:** 
pylinx.XsctServer just executes internally this command:
```python
subprocess.Popen('xsdb.bat -eval "xsdbserver start -port 3100" -interactive', stdout=open(os.devnull, 'w'))
```

**Update:**
I have replicated the same issue using a very basic python code that runs the robot command from subprocess.Popen with the same configuration than "contrib\testrunner\Process.py:run_command"

**Workaround**:
I have applied this changes in contrib\testrunner\Process.py:
```diff
    def run_command(self, command):
        # We need to supply stdin for subprocess, because other ways in python
        # subprocess will try using sys.stdin which causes an error in windows
        # print("DEBUG: enter run_command %s dir %s" % (command, self._cwd))
        subprocess_args = dict(bufsize=0,
                               stdout=subprocess.PIPE,
                               stderr=subprocess.PIPE,
-                             stdin=subprocess.PIPE,
+                            stdin=None,
                               cwd=self._cwd)
```
And the server initializes properly and the client is able to communicate with the server, it is under analysis, how we can force it without RIDE modification.

**Comment by HelioGuilherme66** [comment]
@AndresSanchez229 Good that you find the root cause. You think it would be good to have some switch (maybe an environment variable) to control that `stdin` parameter? This way you could set it for your special case.
A Pull Request would be most welcomed.
I really would like to have more collaborators on the project 😆
