### ISSUE TITLE
Open libraries and variable files to external configurable editor

### ISSUE THREAD

**Issue by robotframework-ride** [robotframework/RIDE#361]
> *Originally submitted to [Google Code](http://code.google.com/p/robotframework-ride/issues/detail?id=334) by mikko.harila on 1 Dec 2009*

Keyword which is defined in Python code could be a link which would open
the python code file, if wanted, with wanted editor (e.g. IDLE). Just
viewing the file and path to it would be enough at least in the beginning.

**Comment by robotframework-ride** [comment]
> *Originally submitted to [Google Code](http://code.google.com/p/robotframework-ride/issues/detail?id=334#c2) by @pekkaklarck on 16 Dec 2009*


This issue actually contains two issues:

1) Showing the path where keywords (and variables) originate from. Technically this
ought to be relatively easy using `inspect.getsource`. In my opinion this requires
having new "test library view" where the generic library documentation and all the
keywords are shown, and where we could have also a possibility to view the source. I
created a new <a href="https://code.google.com/p/robotframework-ride/issues/detail?id=352" title="Test library view with generic documentation and source code">issue 352</a> about this and there's existing <a href="https://code.google.com/p/robotframework-ride/issues/detail?id=79" title="Show variable files in the UI">issue 79</a> about variable file
views. Both of these should be implemented in 1.0 but are not mandatory.

2) Making it possible to open the source files into an external, configurable,
editor. This can be done after 1) but has, in my opinion, lower priority and is out
of the scope of the 1.0 release.


Because we have <a href="https://code.google.com/p/robotframework-ride/issues/detail?id=79" title="Show variable files in the UI">issue 79</a> and <a href="https://code.google.com/p/robotframework-ride/issues/detail?id=352" title="Test library view with generic documentation and source code">issue 352</a> to show the source, the only thing left to
this issue is 2). I've updated the summary accordingly.

**Comment by robotframework-ride** [comment]
> *Originally submitted to [Google Code](http://code.google.com/p/robotframework-ride/issues/detail?id=334#c3) by @jrantanen on 12 Nov 2010*


There could be "Open with ..." and "Open with default editor" selections on right click context menu. This would require to store users preferred editors in the settings.

**Comment by yanne** [comment]
I'll close this, since I'd much rather just support opening Python files in RIDE itself.
