### ISSUE TITLE
Words longer than cell width are not shown fully in the grid

### ISSUE THREAD

**Issue by robotframework-ride** [robotframework/RIDE#369]
> *Originally submitted to [Google Code](http://code.google.com/p/robotframework-ride/issues/detail?id=342) by @khusa on 4 Dec 2009*

The editor cell content is wrapped from the invisible part/column in the
cell, so that it gives a wrong impression of the line break location. (The
line break isn't the same as the cell border, but further in the invisible
part of the cell)

**Comment by robotframework-ride** [comment]
> *Originally submitted to [Google Code](http://code.google.com/p/robotframework-ride/issues/detail?id=342#c1) by @yanne on 16 Dec 2009*


This seems to happen only when a single word is longer that the cell width.

This is problematic to fix because there are may optional behaviors:

1) the cell could overflow to next cell if that cell is empty
2) there could be some indicator showing that not all content is visible
3) the whole column could become wider automatically

Each of these in nontrivial to implement and this issue is quite minor, so unless
there is a some other good reason to fix this, we consider closing this as 'Won't Fix'.

**Comment by robotframework-ride** [comment]
> *Originally submitted to [Google Code](http://code.google.com/p/robotframework-ride/issues/detail?id=342#c2) by @yanne on 5 Sep 2010*


We'll investigate what, if any, technical solution would be reasonable to implement.

**Comment by robotframework-ride** [comment]
> *Originally submitted to [Google Code](http://code.google.com/p/robotframework-ride/issues/detail?id=342#c3) by @yanne on 8 Sep 2010*


Could not properly fix this now, too complicated to fix for the benefit at the moment

**Comment by robotframework-ride** [comment]
> *Originally submitted to [Google Code](http://code.google.com/p/robotframework-ride/issues/detail?id=342#c5) by @jrantanen on 25 Mar 2011*


<a class="closed_ref" href="https://code.google.com/p/robotframework-ride/issues/detail?id=759" title="It is almost impossible to see the whole content of a cell if you have long string without spaces"> Issue 759 </a> has been merged into this issue.

**Comment by yanne** [comment]
This is hopefully partially alleviated by #1449, so closing this for now.
