### ISSUE TITLE
Test library view with generic documentation and source code

### ISSUE THREAD

**Issue by robotframework-ride** [robotframework/RIDE#379]
> *Originally submitted to [Google Code](http://code.google.com/p/robotframework-ride/issues/detail?id=352) by @pekkaklarck on 16 Dec 2009*

RIDE already knows about libraries and their keywords but there's no single
view to show library contents. This view would allow showing libraries'
generic documentation and we could also show their source code when it's
available via `inspect.getsource`.

**Comment by robotframework-ride** [comment]
> *Originally submitted to [Google Code](http://code.google.com/p/robotframework-ride/issues/detail?id=352#c1) by @pekkaklarck on 16 Dec 2009*


See also <a href="https://code.google.com/p/robotframework-ride/issues/detail?id=79" title="Show variable files in the UI">issue 79</a> about the variable file view and <a href="https://code.google.com/p/robotframework-ride/issues/detail?id=334" title="Open libraries and variable files to external configurable editor">issue 334</a> about opening libraries
and variable files into an external editor.

**Comment by robotframework-ride** [comment]
> *Originally submitted to [Google Code](http://code.google.com/p/robotframework-ride/issues/detail?id=352#c2) by @yanne on 3 Sep 2010*


<a class="closed_ref" href="https://code.google.com/p/robotframework-ride/issues/detail?id=261" title="Test library documentation view"> Issue 261 </a> has been merged into this issue.

**Comment by yanne** [comment]
I'll close this, since opening the test library source to RIDE is the best solution to this problem
