### ISSUE TITLE
Manage Run Configuration screen can not be closed or dismissed on OSX

### ISSUE THREAD

**Issue by robotframework-ride** [robotframework/RIDE#471]
> _Originally submitted to [Google Code](http://code.google.com/p/robotframework-ride/issues/detail?id=444) by jerry57 on 16 Apr 2010_

Mac OS X 10.6.3
python 2.6.1
jython 2.5.1
ride 0.22.1
robotframework 2.1.3

Launch RIDE (ride.py . &amp;)
Click Run
Click Manage Run Configurations
Click Cancel button (Window remains)
Click "X" to close window (Window remains)
Click Run &amp; then Manage Run Configurations to "uncheck/select" (Window remains)
The only way to dismiss the window is to Click OK

**Comment by robotframework-ride** [comment]
> *Originally submitted to [Google Code](http://code.google.com/p/robotframework-ride/issues/detail?id=444#c1) by @yanne on 28 Jun 2010*


Mac OSX is not currently supported platform at NSN, who is the sponsor of RF core development team. In addition to that, we have only limited access to Mac OSX machines to even test possible fix(es).

Contribution to fix and test this issue is more than welcome.

**Comment by robotframework-ride** [comment]
> *Originally submitted to [Google Code](http://code.google.com/p/robotframework-ride/issues/detail?id=444#c2) by pavis... on 2 Nov 2010*


Similar  behavior is observed for :

1. New project, New resource
2. Open Directory, Open file

Mac OS X 10.6.3
python 2.6.1
jython 2.5.1
ride 0.29.0

**Comment by robotframework-ride** [comment]
> *Originally submitted to [Google Code](http://code.google.com/p/robotframework-ride/issues/detail?id=444#c4) by john.gl... on 26 Sep 2011*


I've confirmed these are fixed in HEAD on MAC OS 10.6

**Comment by robotframework-ride** [comment]
> *Originally submitted to [Google Code](http://code.google.com/p/robotframework-ride/issues/detail?id=444#c6) by @mkorpela on 26 Sep 2011*


Works in Mac OS  10.6.8

**Comment by Nyral** [comment]
@HelioGuilherme66 There is no such thing as Manage Run Configurations anymore.

**Comment by HelioGuilherme66** [comment]
@Nyral Yes there is ;)
Macros > Manage Run Configurations

![image](https://user-images.githubusercontent.com/2866630/58204017-522aef80-7cd3-11e9-9ebc-dd77dd50bf37.png)

**Comment by HelioGuilherme66** [comment]
Closed because (use OR operator):
- is too old,
- newest version should have it fixed,
- not reproducible,
- not an issue,
- is a question,
- lacks logs, versions info, e.t.c.,
- there is no other reason that justifies being opened.

**Comment by Nyral** [comment]
@HelioGuilherme66 I spoke too fast, sorry.
