### ISSUE TITLE
Windows installer puts wrong Python path in ride.py

### ISSUE THREAD

**Issue by robotframework-ride** [robotframework/RIDE#539]
> _Originally submitted to [Google Code](http://code.google.com/p/robotframework-ride/issues/detail?id=508) by spielman... on 2 Sep 2010_

As far as I believe to understand the installer, ride.py is changed or generated dynamically during the installation. The ride.py I get contains:
# !C:\Python26\python.exe

but on my system, I have Python 2.7 and it's installed in an entirely different path. If I try to run ride.py which is on my PATH, I get a Windows dialog asking me which program I want to open the file with.

**Comment by robotframework-ride** [comment]
> *Originally submitted to [Google Code](http://code.google.com/p/robotframework-ride/issues/detail?id=508#c1) by spielman... on 2 Sep 2010*


RIDE starts as soon as I've selected to open the file with python.exe, which is okay but still seems a little weird. I still can't see why the shebang path points to C:\Python26 though, even if this is not even evaluated on Windows systems.

**Comment by robotframework-ride** [comment]
> *Originally submitted to [Google Code](http://code.google.com/p/robotframework-ride/issues/detail?id=508#c2) by @pekkaklarck on 2 Sep 2010*


This is the same problem as reported in <a class="closed_ref" href="https://code.google.com/p/robotframework-ride/issues/detail?id=487" title="Location of Python interpreter might not be correct in ride.py "> issue 487 </a> that we decided to WontFix. I still think this is a distutils bug and trying to fix it in RIDE is too much work. We should, however, document this in the installation instructions because this is the second time this is reported. We probably should also report the underlying issue to <a href="http://bugs.python.org" rel="nofollow">http://bugs.python.org</a>.

**Comment by robotframework-ride** [comment]
> *Originally submitted to [Google Code](http://code.google.com/p/robotframework-ride/issues/detail?id=508#c3) by @yanne on 2 Sep 2010*


Also note that the shebang has absolutely no effect on Windows machines.

**Comment by robotframework-ride** [comment]
> *Originally submitted to [Google Code](http://code.google.com/p/robotframework-ride/issues/detail?id=508#c4) by spielman... on 3 Sep 2010*


Yes, as I realized in the 2nd comment, this is irrelevant for Windows, but I would say +1 on the documentation proposal.

**Comment by HelioGuilherme66** [comment]
Closed because (use OR operator):
- is too old,
- newest version should have it fixed,
- not reproducible,
- not an issue,
- is a question,
- lacks logs, versions info, e.t.c.,
- there is no other reason that justifies being opened.
