### ISSUE TITLE
New test case files added to file system should be noticed

### ISSUE THREAD

**Issue by yanne** [robotframework/RIDE#597]
> _Originally submitted to [Google Code](http://code.google.com/p/robotframework-ride/issues/detail?id=564) by @pekkaklarck on 29 Oct 2010_

It would be convenient if RIDE would notice new files added to the open project. This would be especially handy when new files appear as part of version control update.

Resource files can probably be ignored as they are anyway shown only when referenced by test case files or other resource files.

Technically this would require periodically running os.listdir and checking are there any new test case files. Shouldn't be too complicated.

**Comment by yanne** [comment]
I'd prefer using a real library, like https://pypi.python.org/pypi/watchdog to implement this.

**Comment by fzuellich** [comment]
Would like to pick this issue up.

**Comment by HelioGuilherme66** [comment]
This is implemented and working, at least in v2.0.8.dev25.
