### ISSUE TITLE
RIDE gets stucked in "File Changed On Disk" -dialog

### ISSUE THREAD

**Issue by robotframework-ride** [robotframework/RIDE#636]
> *Originally submitted to [Google Code](http://code.google.com/p/robotframework-ride/issues/detail?id=602) by juho.saarinen on 15 Nov 2010*

Steps to reproduce:
1. Write some text to eg. notepad and hit enter.
2. Copy whole written line to clipboard (including line change).
3. Paste text to RIDE's test case (straight to cell, not in cell's edit mode).
4. When trying to save/edit cell again, "File Changed On Disk" -dialog just keep showing up and preventing edit/save.
5. Works fine, if text is pasted in edit mode (cursor blinking in cell)

Log that's written to console:
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\robotide\ui\actiontriggers.py", line 342, in __call__
    action.act(event)
  File "C:\Python27\lib\site-packages\robotide\action\action.py", line 71, in act
    self.action(event)
  File "C:\Python27\lib\site-packages\robotide\utils\eventhandler.py", line 23, in wrapped
    method(self, event)
  File "C:\Python27\lib\site-packages\robotide\ui\mainframe.py", line 187, in OnSave
    self.save()
  File "C:\Python27\lib\site-packages\robotide\ui\mainframe.py", line 197, in save
    controller.execute(SaveFile())
  File "C:\Python27\lib\site-packages\robotide\controller\filecontrollers.py", line 103, in execute
    return command.execute(self)
  File "C:\Python27\lib\site-packages\robotide\controller\commands.py", line 267, in execute
    datafile_controller.save()
  File "C:\Python27\lib\site-packages\robotide\controller\filecontrollers.py", line 186, in save
    self._chief_controller.serialize_controller(self)
  File "C:\Python27\lib\site-packages\robotide\controller\chiefcontroller.py", line 190, in serialize_controller
    self._serialize_file(controller)
  File "C:\Python27\lib\site-packages\robotide\controller\chiefcontroller.py", line 207, in _serialize_file
    serializer.serialize(controller.datafile)
  File "C:\Python27\lib\site-packages\robotide\writer\serializer.py", line 46, in serialize
    writer_serializer.serialize(datafile)
  File "C:\Python27\lib\site-packages\robotide\writer\serializer.py", line 79, in serialize
    self.table_handlers[table.type](table)
  File "C:\Python27\lib\site-packages\robotide\writer\serializer.py", line 117, in _testcase_table_handler
    self._handle_testcase(tc)
  File "C:\Python27\lib\site-packages\robotide\writer\serializer.py", line 122, in _handle_testcase
    self._write_elements(tc)
  File "C:\Python27\lib\site-packages\robotide\writer\serializer.py", line 91, in _write_elements
    self._writer.element(element)
  File "C:\Python27\lib\site-packages\robotide\writer\writer.py", line 103, in element
    self._write_data([self._get_tcuk_name()]+content, indent=1)
  File "C:\Python27\lib\site-packages\robotide\writer\writer.py", line 160, in _write_data
    data = self._encode(data)
  File "C:\Python27\lib\site-packages\robotide\writer\writer.py", line 133, in _encode
    return [ cell.encode('UTF-8').replace('\n', ' ') for cell in row ]
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe4 in position 34: ordinal not in range(128)

Version information:
RIDE: Version 0.29.2 running on Python 2.7.0 using Robot Framework 2.5.3. 
JYBOT: Robot Framework 2.5.3 (Jython 2.5.2b1 on java1.6.0_22)
PYBOT: Robot Framework 2.5.3 (Python 2.7 on win32)
OS: Windows Vista, 32bit

**Comment by robotframework-ride** [comment]
> *Originally submitted to [Google Code](http://code.google.com/p/robotframework-ride/issues/detail?id=602#c2) by @jussimalinen on 15 Nov 2010*


Can you elaborate what happens between steps 3 and 4? You just paste the text to the cell (when not in edit mode) and immediately (no clicks or steps between) press ctrl-s to save and get an error?

Doing that (and playing around with some other combinations, like trying to edit the cell and so on) I am unable to reproduce this on Windows XP. Also no problem on Linux. I don't have a Vista machine available right now, but I could try this on Windows 7 later.

**Comment by robotframework-ride** [comment]
> *Originally submitted to [Google Code](http://code.google.com/p/robotframework-ride/issues/detail?id=602#c3) by @jussimalinen on 15 Nov 2010*


Oh, btw, what is your wxPython version?

You can find that out by running "python" from command line and then giving the following commands:
import wx
wx.VERSION

**Comment by robotframework-ride** [comment]
> *Originally submitted to [Google Code](http://code.google.com/p/robotframework-ride/issues/detail?id=602#c4) by juho.saarinen on 15 Nov 2010*


WX: 
Python 2.7 (<a href="https://code.google.com/p/robotframework-ride/source/detail?r=27">r27</a>:82525, Jul  4 2010, 09:01:59) [MSC v.1500 32 bit (Intel)] on win32
Type "help", "copyright", "credits" or "license" for more information.
&gt;&gt;&gt; import wx
&gt;&gt;&gt; wx.VERSION
(2, 8, 11, 0, '')

**Comment by robotframework-ride** [comment]
> *Originally submitted to [Google Code](http://code.google.com/p/robotframework-ride/issues/detail?id=602#c6) by juho.saarinen on 15 Nov 2010*


Reproducing, another way.
Paste "Tässä on sitten paririviä pitkä avainsana" to first cell
Take copy of cell 1 (go over cell with eg. arrow keys and press ctrl+c). 
Paste that copy to second (move to second cell with arrow keys. If cursor is blinking everything works fine).
Hit enter after text is pasted, and try to save test case.

At least that way I get error all the time now.

**Comment by robotframework-ride** [comment]
> *Originally submitted to [Google Code](http://code.google.com/p/robotframework-ride/issues/detail?id=602#c7) by @jussimalinen on 15 Nov 2010*


Alright, I was able to reproduce now, but only if I include non ascii characters to the text string that I copy.

**Comment by robotframework-ride** [comment]
> *Originally submitted to [Google Code](http://code.google.com/p/robotframework-ride/issues/detail?id=602#c8) by @mkorpela on 16 Nov 2010*


This should help (<a href="https://code.google.com/p/robotframework-ride/source/detail?r=9e5138253f">revision 9e5138253f</a>).
Now all strings that enter model should be utf-8 encoded unicode strings.

**Comment by robotframework-ride** [comment]
> *Originally submitted to [Google Code](http://code.google.com/p/robotframework-ride/issues/detail?id=602#c10) by @mkorpela on 17 Nov 2010*


Fixed in (<a href="https://code.google.com/p/robotframework-ride/source/detail?r=9e5138253f">revision 9e5138253f</a>)

**Comment by NiveditaMirjikar** [comment]
Facing this issue with beta version of robotframework ride

Steps to reproduce:
-- Install the beta version of ride in the windows platform
-- Try to launch the ride IDE with the following command from the command prompt
python -m robotide.__init__
-- Psutil not found error message window pops up, click ok
-- Once the ride IDE launches soon after closing the Psutil error message window
-- Files changed on disk dialogue pops up every time when tried to use RIDE

![2021-06-25_17h59_31](https://user-images.githubusercontent.com/43817882/123428308-4a8d5180-d5e3-11eb-8d44-cfed0ec8794b.png)
![2021-06-25_18h07_22](https://user-images.githubusercontent.com/43817882/123428317-4cefab80-d5e3-11eb-889d-8c4674447e8c.png)
