### ISSUE TITLE
Ride should find where variables are set by "set test/suite/global variable" keyword

### ISSUE THREAD

**Issue by yanne** [robotframework/RIDE#756]
> _Originally submitted to [Google Code](http://code.google.com/p/robotframework-ride/issues/detail?id=721) by @jussimalinen on 2 Mar 2011_

I would like to be able to search where variable value is set dynamically.

**Comment by yanne** [comment]
> *Originally submitted to [Google Code](http://code.google.com/p/robotframework-ride/issues/detail?id=721#c1) by @mkorpela on 4 Mar 2011*


This has some same elements as Find Usages / Occurrences..

**Comment by yanne** [comment]
> *Originally submitted to [Google Code](http://code.google.com/p/robotframework-ride/issues/detail?id=721#c5) by @mkorpela on 21 Jan 2013*


Similar elements with <a href="https://code.google.com/p/robotframework-ride/issues/detail?id=643" title="Variable source in information popup should be link when possible">Issue 643</a>

**Comment by Nyral** [comment]
@HelioGuilherme66 Not valid anymore. Why?
You can use Find Where Used on variables.
You can also see location of variable in popup from autocomplete.

**Comment by HelioGuilherme66** [comment]
Closed because (use OR operator):
- is too old,
- newest version should have it fixed,
- not reproducible,
- not an issue,
- is a question,
- lacks logs, versions info, e.t.c.,
- there is no other reason that justifies being opened.

(thanks @Nyral for validating)
