### ISSUE TITLE
RIDE can not maintain the "..." ellipsis in a new line when re-opens the project

### ISSUE THREAD

**Issue by robotframework-ride** [robotframework/RIDE#877]
> *Originally submitted to [Google Code](http://code.google.com/p/robotframework-ride/issues/detail?id=842) by vitogod on 17 Aug 2011*

When a test case has a line with many cells including keywords and their arguments in RIDE, I want to use the ellipsis "..." to continue the previouse line, like below (display in cells format in RIDE)

${returnValue1}	${returnValue2}	keyword	arg1 arg2 
... arg3 arg4

then click save all button, the ellipsis is saved, and maintained when switching different test cases. But if closed RIDE or re-opened the project in RIDE, the ellipsis would be removed automatically, the two lines previously would form a single line like below

${returnValue1}	${returnValue2}	keyword	arg1 arg2 arg3 arg4

I wonder if the ellipsis could be maintained so it's easier to check the whole test case without dragging the scrollbar?

**Comment by robotframework-ride** [comment]
> *Originally submitted to [Google Code](http://code.google.com/p/robotframework-ride/issues/detail?id=842#c2) by vitogod on 17 Aug 2011*


Dear owner,
Would you please give some comments on this, Thanks in advance.

**Comment by robotframework-ride** [comment]
> *Originally submitted to [Google Code](http://code.google.com/p/robotframework-ride/issues/detail?id=842#c3) by @mkorpela on 18 Aug 2011*


This is a valid issue.

Requires changes to Robot Framework.

**Comment by robotframework-ride** [comment]
> *Originally submitted to [Google Code](http://code.google.com/p/robotframework-ride/issues/detail?id=842#c5) by @mkorpela on 19 Aug 2012*


<a class="closed_ref" href="https://code.google.com/p/robotframework-ride/issues/detail?id=1029" title="... disappear when reload"> Issue 1029 </a> has been merged into this issue.

**Comment by robotframework-ride** [comment]
> *Originally submitted to [Google Code](http://code.google.com/p/robotframework-ride/issues/detail?id=842#c6) by Eugene.K... on 10 Sep 2012*


I'm wondering is there a workaround for this issue which can help maintain dictionaries with 10-12 and more pairs?

**Comment by robotframework-ride** [comment]
> *Originally submitted to [Google Code](http://code.google.com/p/robotframework-ride/issues/detail?id=842#c7) by @pekkaklarck on 6 Nov 2012*


I agree that losing the information about how lines are slit is really annoying. This is due to RIDE using Robot's parsing modules to get the data and those modules combining split lines.

I submitted an issue to Robot about keeping lines separate [1]. I don't know how easy task that is so cannot tell if/when this issue actually can be fixed. 

[1 <a href="https://code.google.com/p/robotframework/issues/detail?id=1272" rel="nofollow">https://code.google.com/p/robotframework/issues/detail?id=1272</a>

**Comment by robotframework-ride** [comment]
> *Originally submitted to [Google Code](http://code.google.com/p/robotframework-ride/issues/detail?id=842#c9) by @mkorpela on 21 Jan 2013*


Waiting for Robot Framework changes. Too big task.

**Comment by robotframework-ride** [comment]
> *Originally submitted to [Google Code](http://code.google.com/p/robotframework-ride/issues/detail?id=842#c10) by derek.robati on 30 Jan 2013*


This is also an issue for me. I hope RFW's maintainers can fix this so that RIDE can implement a solution.

**Comment by robotframework-ride** [comment]
> *Originally submitted to [Google Code](http://code.google.com/p/robotframework-ride/issues/detail?id=842#c11) by mic... on 6 Mar 2013*


I am actually willing to donate if I can get this fixed. I really hate having to maintain my data in seperate CSV files just because RIDE cannot deal with tabular data.

**Comment by robotframework-ride** [comment]
> *Originally submitted to [Google Code](http://code.google.com/p/robotframework-ride/issues/detail?id=842#c12) by @mkorpela on 12 Mar 2013*


@&#8288;michel: Thanks, but currently core team is fully funded by Nokia Siemens Network.

Why do you need to keep your data in a separate CSV file?

**Comment by robotframework-ride** [comment]
> *Originally submitted to [Google Code](http://code.google.com/p/robotframework-ride/issues/detail?id=842#c13) by mic... on 22 Mar 2013*


@&#8288;mikko

I work for a financial institution and all of our data are in tabular(CSV) format. For small datasets(10 rows x 8 cols) I would like to include the tabular data in-line with the test case; this way everybody can see the whole test case in one page view.

Since RIDE doesn’t preserve the ellipses I have started to create the test suites in HTML, but when my test suite has about 400 rows and 10 columns(about 8 test cases) Visual Studio 2010’s performance degrades to where it is almost unusable. Having separate CSV files would solve my performance problems, but it would reduce test clarity.

This has caused me to wonder if providing tabular data inline is even possible for me, since there is no tool that seems to be a perfect fit(except RIDE if ellipses were preserved).

**Comment by robotframework-ride** [comment]
> *Originally submitted to [Google Code](http://code.google.com/p/robotframework-ride/issues/detail?id=842#c14) by @mkorpela on 21 Oct 2013*


<a class="closed_ref" href="https://code.google.com/p/robotframework-ride/issues/detail?id=1295" title="Please keep the origin text format"> Issue 1295 </a> has been merged into this issue.

**Comment by robotframework-ride** [comment]
> *Originally submitted to [Google Code](http://code.google.com/p/robotframework-ride/issues/detail?id=842#c15) by @mkorpela on 10 Mar 2014*


<a class="closed_ref" href="https://code.google.com/p/robotframework-ride/issues/detail?id=1329" title="RIDE collapses multi-rows keywords after relaunch"> Issue 1329 </a> has been merged into this issue.

**Comment by robotframework-ride** [comment]
> *Originally submitted to [Google Code](http://code.google.com/p/robotframework-ride/issues/detail?id=842#c16) by @mkorpela on 7 Apr 2014*


<a class="closed_ref" href="https://code.google.com/p/robotframework-ride/issues/detail?id=1349" title="Allow choosing the format of arguments with keywords"> Issue 1349 </a> has been merged into this issue.

**Comment by yanne** [comment]
I think we won't be able to support this in the grid editor. I'll think it's wiser to enhance the text editor, so that if exact formatting is important, it can be achieved with the text editor.
