### ISSUE TITLE
Keyword completion on OSX doesn't work fully

### ISSUE THREAD

**Issue by robotframework-ride** [robotframework/RIDE#900]
> *Originally submitted to [Google Code](http://code.google.com/p/robotframework-ride/issues/detail?id=865) by @pekkaklarck on 27 Sep 2011*

Starting from 0.39 keyword completion on OSX works for some extend (<a class="closed_ref" href="https://code.google.com/p/robotframework-ride/issues/detail?id=146" title="Keyword completion and documentation popups don't work on OSX at all"> issue 146 </a>) but not fully. Hopefully the functionality can be still enhanced in the future.

**Comment by robotframework-ride** [comment]
> *Originally submitted to [Google Code](http://code.google.com/p/robotframework-ride/issues/detail?id=865#c1) by @pekkaklarck on 27 Sep 2011*


The main problem with keyword completion is that wx.PopupWindow doesn't work on OSX with wxPython 2.8. It apparently works with wxPython 2.9 but that is an unstable development version with some API changes compared to 2.8. Porting RIDE to wxPython 2.9 could anyway be one solution for this problem.

**Comment by robotframework-ride** [comment]
> *Originally submitted to [Google Code](http://code.google.com/p/robotframework-ride/issues/detail?id=865#c2) by andreas.brain on 11 Jan 2012*


Keyword completion on OSX works for me.
It doesn't matter if the cell is empty, or if you already typed some characters. It is also possible to filter the search result by continuing to type.

Mac OS X 10.6.8
RIDE: 0.39.1
wxPython: py27-wxpython @&#8288;2.8.12.1 (MacPorts)
Python: 2.7.2, <a href="https://code.google.com/p/robotframework-ride/source/detail?r=3">Revision 3</a> (MacPorts)

**Comment by robotframework-ride** [comment]
> *Originally submitted to [Google Code](http://code.google.com/p/robotframework-ride/issues/detail?id=865#c3) by andreas.brain on 11 Jan 2012*


Ok, maybe I have to take that back. It seems, that Python 2.6.7 was the active version. And I don't know the wxPython version.
Reinstalled all the stuff through MacPorts, and suddenly the UI looks different. Nicer, somehow, but I'm not able anymore, to refine the search by typing

**Comment by robotframework-ride** [comment]
> *Originally submitted to [Google Code](http://code.google.com/p/robotframework-ride/issues/detail?id=865#c4) by @yanne on 11 Jan 2012*


You can find out the wxPython version from Tools | Ride Log.

**Comment by robotframework-ride** [comment]
> *Originally submitted to [Google Code](http://code.google.com/p/robotframework-ride/issues/detail?id=865#c5) by andreas.brain on 11 Jan 2012*


Yes, now it's 2.8.12.1, but I'm not sure anymore, if this is the same version I used before, since MacPorts can have multiple versions installed, but only one will be used. The UI now looks different (compare the screenshots above).
So, keyword auto complete on a Mac worked with a specific version, and I don't know which...

**Comment by yanne** [comment]
This actually works with current RIDE and wxPython 2.8.12.1
