### ISSUE TITLE
tree: Show unused resource files

### ISSUE THREAD

**Issue by robotframework-ride** [robotframework/RIDE#905]
> _Originally submitted to [Google Code](http://code.google.com/p/robotframework-ride/issues/detail?id=870) by chetan.dewangan on 29 Sep 2011_

I had created following hierarchy :

Root Folder
    |--- Test Folder
    |--- Only Test Cases
    |--- Variable Folder
    |--- Only Variables
    |--- User Keyword folder
    |--- Only User Keywords

On re-opening above Root folder only Test case folder and file is visible.

**Comment by robotframework-ride** [comment]
> *Originally submitted to [Google Code](http://code.google.com/p/robotframework-ride/issues/detail?id=870#c1) by @mkorpela on 30 Sep 2011*


Ride currently only opens the files that are referenced by the suite files.

I'll change the summary to "tree: Raw file system view".

**Comment by robotframework-ride** [comment]
> *Originally submitted to [Google Code](http://code.google.com/p/robotframework-ride/issues/detail?id=870#c3) by @mkorpela on 10 Jun 2012*


<a class="closed_ref" href="https://code.google.com/p/robotframework-ride/issues/detail?id=979" title="RIDE failed to load resources in ubuntu 12.04 LTS"> Issue 979 </a> has been merged into this issue.

**Comment by HelioGuilherme66** [comment]
Closing because can be tested on soon to be pre-released, v2.0b1.
