### ISSUE TITLE
Support wxPython 3.0

### ISSUE THREAD

**Issue by yanne** [robotframework/RIDE#924]
> _Originally submitted to [Google Code](http://code.google.com/p/robotframework-ride/issues/detail?id=888) by @yanne on 17 Nov 2011_

We explicitly select wxPython 2.8 if it is found using  wxversion.select('2.8') in roboide/**init**.py

However, wxPython 2.9 has been available for some time, so we should prefer that if it's found.

**Comment by yanne** [comment]
> *Originally submitted to [Google Code](http://code.google.com/p/robotframework-ride/issues/detail?id=888#c1) by jerry57 on 17 Nov 2011*


On a Lion laptop I installed wxPython 2.9.2.4 cocoa and then removed the ride install that was there and installed 0.39.1.  When I tried to launch ride.py I am getting the following.

Note: previous 2.8.12.1-1 wxPython was uninstalled and env for VERSIONER
(unset VERSIONER_PYTHON_PREFER_32_BIT)
was removed.

IPC-Freud:de jerry$ ride.py . &amp;
[1] 645
IPC-Freud:de jerry$ Traceback (most recent call last):
  File "/usr/local/bin/ride.py", line 22, in &lt;module&gt;
    main(sys.argv[1:])
  File "/Library/Python/2.7/site-packages/robotide/__init__.py", line 59, in main
    _run(*args)
  File "/Library/Python/2.7/site-packages/robotide/__init__.py", line 68, in _run
    ride = RIDE(inpath)
  File "/Library/Python/2.7/site-packages/robotide/application/application.py", line 35, in __init__
    wx.App.__init__(self, redirect=False)
  File "/usr/local/lib/wxPython-2.9.2.4/lib/python2.7/site-packages/wx-2.9.2-osx_cocoa/wx/_core.py", line 8593, in __init__
    self._BootstrapApp()
  File "/usr/local/lib/wxPython-2.9.2.4/lib/python2.7/site-packages/wx-2.9.2-osx_cocoa/wx/_core.py", line 8158, in _BootstrapApp
    return _core_.PyApp__BootstrapApp(*args, **kwargs)
  File "/Library/Python/2.7/site-packages/robotide/application/application.py", line 40, in OnInit
    self.frame = RideFrame(self, self._controller)
  File "/Library/Python/2.7/site-packages/robotide/ui/mainframe.py", line 63, in __init__
    self._init_ui()
  File "/Library/Python/2.7/site-packages/robotide/ui/mainframe.py", line 91, in _init_ui
    self.tree = Tree(splitter, self.actions)
  File "/Library/Python/2.7/site-packages/robotide/ui/tree.py", line 71, in __init__
    action_registerer.register_actions(actions)
  File "/Library/Python/2.7/site-packages/robotide/ui/mainframe.py", line 272, in register_actions
    self.register_action(action)
  File "/Library/Python/2.7/site-packages/robotide/ui/mainframe.py", line 266, in register_action
    self._menubar.register(action)
  File "/Library/Python/2.7/site-packages/robotide/ui/actiontriggers.py", line 52, in register
    menu = self._create_menu(action.menu_name)
  File "/Library/Python/2.7/site-packages/robotide/ui/actiontriggers.py", line 38, in _create_menu
    self._insert_menu(menu, before_help)
  File "/Library/Python/2.7/site-packages/robotide/ui/actiontriggers.py", line 46, in _insert_menu
    self._mb.Insert(index, menu.wx_menu, menu.name)
  File "/usr/local/lib/wxPython-2.9.2.4/lib/python2.7/site-packages/wx-2.9.2-osx_cocoa/wx/_core.py", line 12245, in Insert
    return _core_.MenuBar_Insert(*args, **kwargs)
ValueError: in method 'MenuBar_Insert', expected argument 2 of type 'size_t'

[1]+  Exit 1                  ride.py .

To get ride.py to use 2.9 I edited:
src/robotide/__init__.py
and changed the following
from:
try:
    import wxversion
    from wxversion import VersionError
    wxversion.select('2.8')
to:
try:
    import wxversion
    from wxversion import VersionError
    wxversion.select('2.9')

saved and installed after removing old install of 0.39.1

If I can help out testing this, just give a shout.

**Comment by yanne** [comment]
> *Originally submitted to [Google Code](http://code.google.com/p/robotframework-ride/issues/detail?id=888#c2) by @yanne on 4 Jan 2012*


I made the change to __init__.py so that 2.9 is selected if available. The problems have to investigated more thoroughly for the next release.

**Comment by yanne** [comment]
> *Originally submitted to [Google Code](http://code.google.com/p/robotframework-ride/issues/detail?id=888#c3) by @mkorpela on 13 Feb 2012*


wxpython 2.9 is now only used in OSX as there have been many odd issues in Windows 7

**Comment by yanne** [comment]
> *Originally submitted to [Google Code](http://code.google.com/p/robotframework-ride/issues/detail?id=888#c4) by @mkorpela on 13 Feb 2012*


Still not working.

**Comment by yanne** [comment]
> *Originally submitted to [Google Code](http://code.google.com/p/robotframework-ride/issues/detail?id=888#c5) by @mkorpela on 15 Feb 2012*


Moving to future release. Enough content in RIDE 0.42.

**Comment by yanne** [comment]
> *Originally submitted to [Google Code](http://code.google.com/p/robotframework-ride/issues/detail?id=888#c6) by @mkorpela on 19 Mar 2012*


Making release moving these to the next one

**Comment by yanne** [comment]
> *Originally submitted to [Google Code](http://code.google.com/p/robotframework-ride/issues/detail?id=888#c7) by @mkorpela on 6 May 2012*


Not in 0.44

**Comment by yanne** [comment]
> *Originally submitted to [Google Code](http://code.google.com/p/robotframework-ride/issues/detail?id=888#c8) by BlackBel... on 16 Jul 2012*


I am stuck and dead in my RIDE evaluation because I can't get past this error with wxPython 2.9.3(.11?) and the latest RIDE. Any hope before I give up?

**Comment by yanne** [comment]
> *Originally submitted to [Google Code](http://code.google.com/p/robotframework-ride/issues/detail?id=888#c9) by jerry57 on 16 Jul 2012*


I ended up falling back to wx 2.8.  I used "wxPython2.8-osx-unicode-py2.7" from the info below.  Never was able to get 2.9 working yet.

<a href="http://www.wxpython.org/download.php" rel="nofollow">http://www.wxpython.org/download.php</a>

Mac OSX Binaries
The wxPython binaries for OSX are mountable disk images. Simply double click to mount the image and then run the installer application in the image. Download the image that matches the version of Python that you want to use it with, and unless you know for sure that you need the ansi build please get the Unicode build. These binaries should work on all versions of OSX from 10.3.9 onwards on either PPC or i386 architectures. Since they use the Carbon API they are limited to running in 32-bit mode.

wxPython2.8-osx-unicode-py2.6
wxPython2.8-osx-ansi-py2.6 	
wxPython2.8-osx-unicode-py2.7
wxPython2.8-osx-ansi-py2.7

**Comment by yanne** [comment]
> *Originally submitted to [Google Code](http://code.google.com/p/robotframework-ride/issues/detail?id=888#c11) by jyrki.wa... on 18 Aug 2012*


Some background to this: wxPython is obviously directly dependent on wxWindows, on OS X 2.8.* and 2.9.* are not compatible in that 2.8.* uses Carbon support (correctly noted already), 2.9.* is built on Cocoa. This has the effect that software built on 2.8 is not immediately usable on 2.9. One additional consequence on OS X is that the Carbon support means that RIDE has to run in 32-bit mode. The consequence of this, on the other hand, is that as this support does not exist anymore on 10.8, RIDE does not run on 10.8 until it has been modified a bit:) (With some hacking that may be achieved, but this means diving into deep and dangerous waters…)

**Comment by yanne** [comment]
> *Originally submitted to [Google Code](http://code.google.com/p/robotframework-ride/issues/detail?id=888#c12) by @yanne on 18 Aug 2012*


I have a version that works somewhat with wxPython 2.9. I have to still test whether this breaks 2.8 compatibility. If not, we could try to include the fixes in the next RIDE release.

**Comment by yanne** [comment]
> *Originally submitted to [Google Code](http://code.google.com/p/robotframework-ride/issues/detail?id=888#c13) by ironst... on 31 Aug 2012*


@&#8288; janne if you could share a patch that would help me out immensely...   
I'm trying to get RIDE built on OSX 10.8 w/ Mac Ports and it just can't be done atm...    

wxWidgets 2.8.12 doesn't build and building against wxWidgets-devel puts you against 2.9 where you start with Publisher incompatibilities in the API (which I believe I got past) and then hit other incompatibilities, which were beyond my python-newb google+patch fixing abilities. :D

**Comment by yanne** [comment]
> *Originally submitted to [Google Code](http://code.google.com/p/robotframework-ride/issues/detail?id=888#c14) by ironst... on 31 Aug 2012*


It seems wxWidgets 2.8.12 in macports depends on Carbon, however with 10.8, support for carbon is no longer there...  

There's a ticket here that talks about hacking it with the 10.6 SDK (but that's not supported)...
<a href="http://trac.macports.org/ticket/35372" rel="nofollow">http://trac.macports.org/ticket/35372</a>

**Comment by yanne** [comment]
> *Originally submitted to [Google Code](http://code.google.com/p/robotframework-ride/issues/detail?id=888#c15) by jyrki.wa... on 1 Sep 2012*


Hi,
this is just to confirm that trying to build RIDE on OS X 10.8 w/MacPorts is not going to be successful before it works with 2.9.x (I happen to maintain all those ports). I wrote c11, but there I for some odd reason used the old name of wxWidgets (thx MS for causing confusion), but the situation should be clear.

**Comment by yanne** [comment]
> *Originally submitted to [Google Code](http://code.google.com/p/robotframework-ride/issues/detail?id=888#c16) by @yanne on 3 Sep 2012*


I managed to get RIDE running with wx2.9 under OSX Lion.

The commit is in my fork of RIDE: <a href="https://github.com/yanne/RIDE" rel="nofollow">https://github.com/yanne/RIDE</a>

It is not fully functional yet, more specifically, it still crashes if data source is given from the command line, or if the recent files plugin is enabled. But disabling recent files plugin by editing ~/.robotframework/ride/settings.cfg, and opening RIDE empty, and using menus to open data source seem to work.

I have not done extensive testing, so it might break on other places.

**Comment by yanne** [comment]
> *Originally submitted to [Google Code](http://code.google.com/p/robotframework-ride/issues/detail?id=888#c18) by @yanne on 4 Sep 2012*


My pull request was merged yesterday, so it is safer to clone

<a href="https://github.com/robotframework/RIDE.git" rel="nofollow">https://github.com/robotframework/RIDE.git</a>

**Comment by yanne** [comment]
> *Originally submitted to [Google Code](http://code.google.com/p/robotframework-ride/issues/detail?id=888#c19) by ironst... on 4 Sep 2012*


Here's my revised script to build and run RIDE...    Subsequent runs can use "ride/ride.sh" to start again...  

  RIDE_START=../ride.sh
  PYTHON_VER="2.7"
  DASH_PYTHON_VER="-${PYTHON_VER}"
  PY=$(echo ${PYTHON_VER}| tr -d '.')
  sudo port install py${PY}-virtualenv py${PY}-pip py${PY}-paver wxWidgets-devel git-core
  PAVER=paver${DASH_PYTHON_VER}
  virtualenv${DASH_PYTHON_VER} --system-site-packages ride # create a virtual python environment for RIDE w/ access to system python libs (i.e. wxPython 2.8)
  cd ride
  # Make Pybot available from system-site-packages OR pip install robotframework if it's not there.
  if [ ! -e bin/pybot ]; then
    if [ -e /opt/local/bin/pybot${DASH_PYTHON_VER} ]; then
      ln -s /opt/local/bin/pybot${DASH_PYTHON_VER} bin/pybot
      ln -s /opt/local/bin/rebot${DASH_PYTHON_VER} bin/rebot
    else
      bin/pip install robotframework
    fi
  fi
  bin/pip install robotframework-seleniumlibrary # Install Selenium Library
  bin/pip install paramiko robotframework-sshlibrary # Install SSH Library
  git clone <a href="https://github.com/robotframework/RIDE.git" rel="nofollow">https://github.com/robotframework/RIDE.git</a>
  cd RIDE
  echo '#!/usr/bin/env bash' &gt; "${RIDE_START}"
  echo 'cd "$(dirname $0)"' &gt;&gt; "${RIDE_START}"
  echo 'export PATH=$(pwd)/bin:${PATH}' &gt;&gt; "${RIDE_START}"
  echo "export PYTHONPATH=\$(pwd)/lib/python${PYTHON_VER}/site-packages" &gt;&gt; "${RIDE_START}"
  echo 'cd "RIDE"' &gt;&gt; "${RIDE_START}"
  echo "${PAVER} run \$*" &gt;&gt; "${RIDE_START}"
  chmod +x "${RIDE_START}"
  "${RIDE_START}"

**Comment by yanne** [comment]
> *Originally submitted to [Google Code](http://code.google.com/p/robotframework-ride/issues/detail?id=888#c20) by @jussimalinen on 6 Nov 2012*


Is this actually done already?

**Comment by yanne** [comment]
> *Originally submitted to [Google Code](http://code.google.com/p/robotframework-ride/issues/detail?id=888#c22) by @jussimalinen on 19 Nov 2012*


No, not done. A lot of things fail on 2.9. Usually to segmentation fault.

**Comment by yanne** [comment]
> *Originally submitted to [Google Code](http://code.google.com/p/robotframework-ride/issues/detail?id=888#c23) by mojca.mi... on 25 Dec 2013*


Are there any news about compatibility with wxWidgets 3.0?

**Comment by yanne** [comment]
> *Originally submitted to [Google Code](http://code.google.com/p/robotframework-ride/issues/detail?id=888#c24) by mojca.mi... on 30 Dec 2013*


I didn't want to open a new ticket because of that (I would nevertheless suggest renaming the title of this ticket to "Support for wxPython 3.0 in OSX"), but I wanted to tell that ride doesn't even start if wxPython 3.0 is installed:

&gt; ride.py-2.7 
Wrong wxPython version.
You need to install wxPython 2.8 or 2.9 toolkit with unicode support to run RIDE.
See <a href="http://wxpython.org" rel="nofollow">http://wxpython.org</a> for more information.

I'm aware that support for 2.9 was suboptimal and often problematic, but with 3.0 it fails just because it seen an unknown version of wxPython.

The MacPorts ticket is in <a href="https://trac.macports.org/ticket/41977" rel="nofollow">https://trac.macports.org/ticket/41977</a>

**Comment by yanne** [comment]
> *Originally submitted to [Google Code](http://code.google.com/p/robotframework-ride/issues/detail?id=888#c25) by jerry57 on 25 Jun 2014*


I have tried Janne's wxPython3-compatibility branch (<a href="https://github.com/robotframework/RIDE" rel="nofollow">https://github.com/robotframework/RIDE</a>) of RIDE and am getting the following:

Here are the instructions from his email:
git clone <a href="https://github.com/robotframework/RIDE" rel="nofollow">https://github.com/robotframework/RIDE</a>
git checkout wxPython3-compatibility
paver run

You may need to run `pip install paver` first.


Here are some of the results of my runs:

When I start it the first time I am getting "iCCP: known incorrect sRGB profile" errors reported from paver, but it starts up and I can navigate to one of our projects here.

If I shut it down by clicking the window close button or CMD-Q, it appears to close normally, but then can't be restarted.  I get a python crash report.  If I removed the settings.cfg file, then I can start RIDE again with the paver run command.

I tried to access the Tools-&gt;Preferences I am getting the attached screen shot showing only "Number 4".  All of the Preferences windows are being displayed incorrectly.

I was on Mac OS X 10.9.3
python 2.7.5
wxPython 3.0.0.0 osx-cocoa (classic)
RobotFramework 2.8.5
RIDE from repo above (1.2.3+)

**Comment by yanne** [comment]
> *Originally submitted to [Google Code](http://code.google.com/p/robotframework-ride/issues/detail?id=888#c26) by @yanne on 26 Jun 2014*


I updated wxPython3 branch with fixes to Preferences dialog and the ICCP error message.

Basic editing seems okay also.

I'll change the title of this issue to reflect the goal of getting wxPython 3.0 working

**Comment by yanne** [comment]
> *Originally submitted to [Google Code](http://code.google.com/p/robotframework-ride/issues/detail?id=888#c27) by jerry57 on 26 Jun 2014*


I did a fresh pull this morning.

The preferences windows are all working now.  There are minor issues of not all content displaying, but changing values does seem to save and update.  The excludes window help ends up coming up behind the preferences pane (guessing prefs is modal) and has to be drug out from under prefs pane to read.

I opened an existing project I had on my machine, it opened fine and I was able to edit, save, create new and delete testcases/suites without a problem.  Grid layout is a problem (not sizing right) but basic functionality working.

I was also able to run testcases from within RIDE.  output did not go where I expected though, ended up in "/var/folders/5k/cn 16sg50434z35qcts7vjdh0000gn/T/RIDEzw1HK2.d/output.xml (argfile.txt, report.html &amp; log.html)  All four files went to same directory.  The arguments line was visible originally, but I clicked on something and it went away and I can't seem to get it back. Did get it back by deleting .robotframework/ride/settings.cfg.

I also believe the crash I am seeing on restart is because of the "recent_files = [u'/Users/jerry/trunk/Groupy']" line in the settings.cfg.  If I delete that line between startups, then RIDE starts without error.

I can upload screenshots that show most of these errors/problems if needed.

**Comment by yanne** [comment]
> *Originally submitted to [Google Code](http://code.google.com/p/robotframework-ride/issues/detail?id=888#c28) by jerry57 on 26 Jun 2014*


If I remove the entry from "recent_files = []" then the crash does not seem to happen anymore.

**Comment by yanne** [comment]
> *Originally submitted to [Google Code](http://code.google.com/p/robotframework-ride/issues/detail?id=888#c29) by rdesgroppes on 25 Sep 2014*


Hi,
I come up with the little wrapper script (using monkey patching) that allows us transitioning from wx 2.8 to 3.0, while using the last official release of RIDE.
The script is attached: you'll see the number of changes is not that important. I guess some are missing, but I've been using a "pay as you go" approach.
Regarding your valuable ongoing efforts, I'd recommend using a little abstraction layer instead of distributing try/except (ImportErrors) here and there.

Principle:
robotide.ui.wxal.__init__.py
    version = [int(x) for x in wx.__version__.split('.')[:2]]
    if version &gt;= [3, 0]
        from .v3_0 import *
    elif ...
    else:
        from .v2_8 import *
robotide.ui.wxal.v2_8.py
    from wx.lib.pubsub import setupv1
    ...
    ColorRGB = wx.ColorRGB
    ...
robotide.ui.wxal.v3_0.py
    from wx.lib.pubsub import setuparg1
    ...
    ColorRGB = wx.ColourRGB
    ...

... then: from robotide.ide.wxal import ColorRGB

Best regards,
Regis

**Comment by yanne** [comment]
> *Originally submitted to [Google Code](http://code.google.com/p/robotframework-ride/issues/detail?id=888#c30) by jerry57 on 24 Oct 2014*


Tried the "monkey patching" script today (10/24/14) and I am getting a stacktrace/crash report.  Did a latest install using pip of RIDE.  Had to fall back to the wxpython-compatibility branch to get it working.  At least we can limp a long with RIDE for now on Mavericks and Yosemite.

My current OS is Mac OS X 10.10 Yosemite

I know there is talk of moving to a webbased editor, but when will that be done versus fixing/updating RIDE for now?

**Comment by yanne** [comment]
> *Originally submitted to [Google Code](http://code.google.com/p/robotframework-ride/issues/detail?id=888#c31) by anadan... on 12 Nov 2014*


Can someone give me some advice on how to/whether I should fall back to wxPython 2.8? I went to the download page listed above but don't see older versions. Also, I'm on Mac and read here that 2.9 it "supports Mac better". <a href="https://github.com/robotframework/RIDE/wiki/Installation-Instructions" rel="nofollow">https://github.com/robotframework/RIDE/wiki/Installation-Instructions</a>  

At the moment I can't run ride.py at all.

When I try to inspect robotframework I get this:
Could not find any downloads that satisfy the requirement wxpython-common
Some externally hosted files were ignored (use --allow-external wxpython-common to allow).

**Comment by yanne** [comment]
> *Originally submitted to [Google Code](http://code.google.com/p/robotframework-ride/issues/detail?id=888#c32) by jerry57 on 12 Nov 2014*


Unfortunately your best bet right now is to fall back to 2.8.12.1 wxPython.  I have gotten it running on Mavericks and Yosemite both without issue.  Using the new wxPython 3.0 is very limited (can get ride running, but that is about it).

**Comment by yanne** [comment]
> *Originally submitted to [Google Code](http://code.google.com/p/robotframework-ride/issues/detail?id=888#c33) by @yanne on 19 May 2015*


<a class="closed_ref" href="https://code.google.com/p/robotframework-ride/issues/detail?id=1308" title="Can't get RIDE to start"> Issue 1308 </a> has been merged into this issue.

**Comment by yanne** [comment]
> *Originally submitted to [Google Code](http://code.google.com/p/robotframework-ride/issues/detail?id=888#c34) by @yanne on 19 May 2015*


<a class="closed_ref" href="https://code.google.com/p/robotframework-ride/issues/detail?id=1317" title="wxPython 3 support"> Issue 1317 </a> has been merged into this issue.

**Comment by yanne** [comment]
> *Originally submitted to [Google Code](http://code.google.com/p/robotframework-ride/issues/detail?id=888#c35) by @yanne on 19 May 2015*


<a class="closed_ref" href="https://code.google.com/p/robotframework-ride/issues/detail?id=1360" title="RIDE 1.3 installation on windows 7 32bit show R6034 run time error"> Issue 1360 </a> has been merged into this issue.

**Comment by yanne** [comment]
Since 2.8.12.1 seems quite stable in OSX, and all RIDE features are working with it, I'll change this title for general wxPython 3.0 support, which should be implemented anyway at some point.

**Comment by HelioGuilherme66** [comment]
Unfortunately I did not succeed to start RIDE with wxPython 2.9.5 and 3.0.2. Now crashes after message opening test files. Micrososft debug info shows crash at wxbase295u_vc90_x64.dll.

**Comment by wxjeacen** [comment]
I also confront with this problem... 
Just can not start ride with wxpython version 3.0.

**Comment by mojca** [comment]
What's the status of wxWidgets 3.0 support? I see that a number of changes from #1537 have been merged, but it's not clear to me whether the software now supports wxPython 3.0 or not. This is the last port in our package manager on macOS that blocks the removal of GTK2-based wxPython 2.8 (and consequently block the removal of python 2.6).

(Disclaimer: I don't know how to use it or how to test robotframework-ride, I'm only in charge for packaging wxWidgets and would like to get rid of the old stuff.)

**Comment by HelioGuilherme66** [comment]
This is now resolved since version 1.7.3.1 (and maybe with 1.5.2.1).
