### ISSUE TITLE
Ability to ignore a directory when loading data

### ISSUE THREAD

**Issue by yanne** [robotframework/RIDE#961]
> *Originally submitted to [Google Code](http://code.google.com/p/robotframework-ride/issues/detail?id=926) by @mkorpela on 3 Feb 2012*

On some specific projects RIDE loads at start up a huge amount of data -- this can take a very long time. Making RIDE start up time extremely big issue for those specific projects.

This could easily be circumvented by having a setting that ignores data loading from certain directory in to RIDE. Similar as exclude directory in some IDEs.

This of course could also help in situations where RIDE mistakingly identifies that a keyword is from certain file (for example when a variable value is used in an import).

This request came from a NSN user.

**Comment by yanne** [comment]
> *Originally submitted to [Google Code](http://code.google.com/p/robotframework-ride/issues/detail?id=926#c1) by @pekkaklarck on 3 Feb 2012*


Shouldn't this be implemented in Robot instead RIDE? That way the speed-up is gained also when running tests.

**Comment by yanne** [comment]
> *Originally submitted to [Google Code](http://code.google.com/p/robotframework-ride/issues/detail?id=926#c2) by @mkorpela on 3 Feb 2012*


In this specific case the files in question are really needed when running the tests. There loading when using RIDE is the problem.

What I'm suggesting is a temporary solution to this specific acute problem. It is cheap to implement. We could have an improved solution once RIDE can lazy load files - as lazy loading resolves the problem completely.

**Comment by yanne** [comment]
> *Originally submitted to [Google Code](http://code.google.com/p/robotframework-ride/issues/detail?id=926#c5) by @mkorpela on 16 Feb 2012*


Fixed after <a href="https://github.com/robotframework/RIDE/commit/265b107af7d777a1c8eeb02f8ddeb79e79b8cc5e" rel="nofollow">https://github.com/robotframework/RIDE/commit/265b107af7d777a1c8eeb02f8ddeb79e79b8cc5e</a>

Now there is a new setting: "exclude resources directory"

**Comment by yanne** [comment]
> *Originally submitted to [Google Code](http://code.google.com/p/robotframework-ride/issues/detail?id=926#c6) by @mkorpela on 18 Feb 2012*


Setting name changed.

New name is "ignored resource directory".

**Comment by amitbendale8** [comment]
Hi, 

How do we use "ignored resource directory" feature.

Folder structure is like
--Folder 1
--Folder 2
--Folder 3
--Folder 4

How do we specifically ignore some folder ?

Thanks
Amit
