### ISSUE TITLE
Library import with relative path doesn't work in RIDE 0.41

### ISSUE THREAD

**Issue by yanne** [robotframework/RIDE#965]
> *Originally submitted to [Google Code](http://code.google.com/p/robotframework-ride/issues/detail?id=930) by pohjonen.antti on 16 Feb 2012*

With new 0.41 RIDE/1/ we are experiencing problems with library imports and therefore Keyword Completion doesn’t work.

The issue is shown while trying to use imports with path in test cases, we get a following WARN statement /2/, even if the library would have postfix as .py it doesn’t work /3/.

PYTHONPATH is set to ‘C:\Documents and Settings\username\workspace\tests\robot’ and Robot Framework is able to use those imports without problems.

Also with dot notation (lib.some_library) I was able to import libraries and Keyword Completion seems to work, but most of resource files and test suites are using old path declaration.

With absolute path import everything works nicely,if postfix .py is also used and in MS Windows(at least) path without whitespaces is used. (C:\Documents and Settings\ doesn't work)

BR,
-Antti

/1/ 20120215 12:16:19.232 [INFO]: Started RIDE 0.41 using python version 2.7.2 with wx version 2.8.12.1.

/2/ 0120215 12:16:39.107 [WARN]: Importing test library "lib/libpoller" failed
 

Traceback (most recent call last):
Importing test library 'lib/libpoller' failed: ImportError: Import by filename is not supported.
Traceback (most recent call last):
  None

PYTHONPATH:
  C:\Python27\lib\site-packages\robotide\lib\robot\libraries
  C:\Python27\lib\site-packages\robotide\lib
  C:\Python27\lib\site-packages\wx-2.8-msw-unicode
  C:\Python27\lib\site-packages\wx-2.8-msw-unicode
  C:\Python27\Scripts
  C:\Python27\lib\site-packages\construct-2.06-py2.7.egg
  C:\Python27\lib\site-packages\futures-2.1.2-py2.7.egg
  C:\Python27\lib\site-packages\suds-0.4-py2.7.egg
  C:\Python27\lib\site-packages\pylint-0.25.1-py2.7.egg
  C:\Python27\lib\site-packages\logilab_astng-0.23.1-py2.7.egg
  C:\Python27\lib\site-packages\logilab_common-0.57.1-py2.7.egg
  C:\Python27\lib\site-packages\xmlbuilder-1.0-py2.7.egg
  C:\Documents and Settings\username\workspace\tests\robot
  C:\Documents and Settings\username\workspace\tests\robot\lib
  C:\WINDOWS\system32\python27.zip
  C:\Python27\DLLs
  C:\Python27\lib
  C:\Python27\lib\plat-win
  C:\Python27\lib\lib-tk
  C:\Python27
  C:\Python27\lib\site-packages
  .
  C:\Python27\lib\site-packages\robotide\spec

  File "C:\Python27\lib\site-packages\robotide\spec\xmlreaders.py", line 59, in __init__
    self.keywords, self.doc = self._init_from_library(self.name, args)

  File "C:\Python27\lib\site-packages\robotide\spec\xmlreaders.py", line 68, in _init_from_library
    lib = RobotTestLibrary(name, args)

  File "C:\Python27\lib\site-packages\robotide\lib\robot\running\testlibraries.py", line 37, in TestLibrary
    libcode = importer.import_class_or_module(name)

  File "C:\Python27\lib\site-packages\robotide\lib\robot\utils\importer.py", line 58, in import_class_or_module
    self._raise_import_failed(name, err)

  File "C:\Python27\lib\site-packages\robotide\lib\robot\utils\importer.py", line 97, in _raise_import_failed
    raise DataError('\n'.join(msg))
 

/3/ 20120215 12:16:39.186 [WARN]: Importing test library "lib/libjson.py" failed

Traceback (most recent call last):
Importing test library 'lib/libjson.py' failed: ImportError: Import by filename is not supported.
Traceback (most recent call last):
  None

PYTHONPATH:
  C:\Python27\lib\site-packages\robotide\lib\robot\libraries
  C:\Python27\lib\site-packages\robotide\lib
  C:\Python27\lib\site-packages\wx-2.8-msw-unicode
  C:\Python27\lib\site-packages\wx-2.8-msw-unicode
  C:\Python27\Scripts
  C:\Python27\lib\site-packages\construct-2.06-py2.7.egg
  C:\Python27\lib\site-packages\futures-2.1.2-py2.7.egg
  C:\Python27\lib\site-packages\suds-0.4-py2.7.egg
  C:\Python27\lib\site-packages\pylint-0.25.1-py2.7.egg
  C:\Python27\lib\site-packages\logilab_astng-0.23.1-py2.7.egg
  C:\Python27\lib\site-packages\logilab_common-0.57.1-py2.7.egg
  C:\Python27\lib\site-packages\xmlbuilder-1.0-py2.7.egg
  C:\Documents and Settings\username\workspace\tests\robot
  C:\Documents and Settings\username\workspace\tests\robot\lib
  C:\WINDOWS\system32\python27.zip
  C:\Python27\DLLs
  C:\Python27\lib
  C:\Python27\lib\plat-win
  C:\Python27\lib\lib-tk
  C:\Python27
  C:\Python27\lib\site-packages
  .
  C:\Python27\lib\site-packages\robotide\spec
File "C:\Python27\lib\site-packages\robotide\spec\xmlreaders.py", line 59, in __init__ 
  self.keywords, self.doc = self._init_from_library(self.name, args)

File "C:\Python27\lib\site-packages\robotide\spec\xmlreaders.py", line 68, in _init_from_library 
  lib = RobotTestLibrary(name, args)

File "C:\Python27\lib\site-packages\robotide\lib\robot\running \testlibraries.py", line 37, in TestLibrary 
  libcode = importer.import_class_or_module(name)

File "C:\Python27\lib\site-packages\robotide\lib\robot\utils\importer.py", line 58, in import_class_or_module
  self._raise_import_failed(name, err)

File "C:\Python27\lib\site-packages\robotide\lib\robot\utils\importer.py", line 97, in _raise_import_failed 
  raise DataError('\n'.join(msg))

**Comment by yanne** [comment]
> *Originally submitted to [Google Code](http://code.google.com/p/robotframework-ride/issues/detail?id=930#c2) by @mkorpela on 16 Feb 2012*


Could you define a reproducable example?

**Comment by yanne** [comment]
> *Originally submitted to [Google Code](http://code.google.com/p/robotframework-ride/issues/detail?id=930#c3) by pohjonen.antti on 17 Feb 2012*


A little example. Just unpack the zip file and set the folder into PYTHONPATH. Test execution with RF works fine, but RIDE cannot import lib/MyLibrary.py and see those keywords.

**Comment by yanne** [comment]
> *Originally submitted to [Google Code](http://code.google.com/p/robotframework-ride/issues/detail?id=930#c4) by @mkorpela on 17 Feb 2012*


Thanks - can produce!

**Comment by yanne** [comment]
> *Originally submitted to [Google Code](http://code.google.com/p/robotframework-ride/issues/detail?id=930#c6) by @mkorpela on 17 Feb 2012*


Doesn't work in 0.40.2 either

**Comment by yanne** [comment]
> *Originally submitted to [Google Code](http://code.google.com/p/robotframework-ride/issues/detail?id=930#c7) by @mkorpela on 17 Feb 2012*


Does work in 0.39.1

**Comment by yanne** [comment]
> *Originally submitted to [Google Code](http://code.google.com/p/robotframework-ride/issues/detail?id=930#c8) by @mkorpela on 17 Feb 2012*


See robot/running/namespace.py[_resolve_path]

**Comment by saravanan-1988** [comment]
<img width="545" alt="Image" src="https://github.com/user-attachments/assets/80e0b666-0768-4766-a581-71bafefaa373" />

Hi, Am getting library import error, I have already done PYTHON_PATH, please help me to resolve the same

My RIDE log

   from Robo_FIT.GenericLibraries.GenericOpLibs.SerialLogging.SerialLogThread import SerialLogThread
PYTHONPATH:
  ['C:\RoboFit\Robo_FIT\GenericLibraries\GenericOpLibs'
  'C:\RoboFit\CRE\Libraries\ProjectLibs']
  C:\Users\SRAJARA3\AppData\Local\Programs\Python\Python310\Scripts\ride.exe
  C:\Users\SRAJARA3\AppData\Local\Programs\Python\Python310\python310.zip
  C:\Users\SRAJARA3\AppData\Local\Programs\Python\Python310\DLLs
  C:\Users\SRAJARA3\AppData\Local\Programs\Python\Python310\lib
  C:\Users\SRAJARA3\AppData\Local\Programs\Python\Python310
  C:\Users\SRAJARA3\AppData\Roaming\Python\Python310\site-packages
  C:\Users\SRAJARA3\AppData\Roaming\Python\Python310\site-packages\win32
  C:\Users\SRAJARA3\AppData\Roaming\Python\Python310\site-packages\win32\lib
  C:\Users\SRAJARA3\AppData\Roaming\Python\Python310\site-packages\Pythonwin
  C:\Users\SRAJARA3\AppData\Local\Programs\Python\Python310\lib\site-packages
  C:\Users\SRAJARA3\AppData\Local\Programs\Python\Python310\lib\site-packages\robotide\spec
  C:\Users\SRAJARA3\AppData\Local\Programs\Python\Python310\lib\site-packages\robotide\lib
  C:\Users\SRAJARA3\AppData\Local\Programs\Python\Python310\lib\site-packages\robotide\contrib\testrunner\../../lib
  C:\Users\SRAJARA3\AppData\Local\Programs\Python\Python310\lib\site-packages\robotide\contrib\testrunner\../../lib
  File "C:\Users\SRAJARA3\AppData\Local\Programs\Python\Pytho
