### ISSUE TITLE
Editing controls should be disabled when file status is READ ONLY

### ISSUE THREAD

**Issue by robotframework-ride** [robotframework/RIDE#987]
> _Originally submitted to [Google Code](http://code.google.com/p/robotframework-ride/issues/detail?id=950) by @mkorpela on 9 Mar 2012_

see <a class="closed_ref" href="https://code.google.com/p/robotframework-ride/issues/detail?id=157" title="RIDE should not allow editing read-only files"> issue 157 </a> .

**Comment by HelioGuilherme66** [comment]
Working on it. Text Editor is now Read Only and Background color changes to darker or lighter.
